### ISSUE TITLE
Bug in The Quest "Sister City"

### ISSUE THREAD

**Issue by SmileyPirate** [Wynncraft/Issues#4462] opened 2016-03-05 20:16 UTC
The Hourglass in Selchar isn't dropping the sand at all. I standed near it, i watched it, and nothing! Is it just a bug for me, or can nobody do anything about it?

**Comment by Odnod** [comment] 2016-03-05 20:17
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-05 20:18 UTC
