### ISSUE TITLE
Chests and buttons not working?!?!?!?!?

### ISSUE THREAD

**Issue by SpeederSam** [Wynncraft/Issues#4183] opened 2016-02-20 01:31 UTC
# Delete this line if you've searched for a duplicate issue first
I have tried multiple times on certain quests and at certain chests to fix this issue, but the best I can do is to change servers every so often and hope for the best. As of right now I went to open a loot chest that is one of the special ones and it said you don't have permission for this area even though there were the sparkle things coming off of it. This has happened with buttons also, but sometimes I am able to fix this by changing servers. This is getting really annoying. Please help, this is probably the 3rd or 4th of the special chests I have been unable to open :(.

**Comment by Trixter313** [comment] 2016-02-20 02:04
Duplicate of https://github.com/Wynncraft/Issues/issues/4151

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-20 02:04 UTC
