### ISSUE TITLE
/fixquests is buggy.

### ISSUE THREAD

**Issue by TheDerpyMan** [Wynncraft/Issues#3371] opened 2015-12-30 22:32 UTC
I don't know what starts the bug, but I'm gonna tell you my circumstances.

Lvl 80, I have finished all quests in Wynn except Haven Antiquity. If I use /fixquests I get 2 Yellow Crystal Shards and 2 Purple Crystal Shards (I finished the Wynnexcavation quests), If I use /fixquests again I get only 2 Purple Crystal Shards. If I continue, I can get unlimited (Purple) Crystal shards.

**Comment by Forcellrus** [comment] 2015-12-30 22:42
Same thing here

**Comment by superabel123** [comment] 2015-12-31 12:29
Errrrr it happened to me too,
/fixquests doesn't actually work and actually gives you more purple crystal shards instead

**Comment by Equipa2** [comment] 2015-12-31 18:06
It happened to me too but i want get back my baab´s wool for the bob´s battle but it only give purple crystals

**Comment by HeyloLP** [comment] 2016-01-01 23:50
@Equipa2 baab's wool is untradeable not a quest item so go back to maro peaks and kill him again

**Comment by DarkDemonDragon** [comment] 2016-01-02 14:29
As @HeyloLP certain quest related items aren't tagged as "Quest Items". While they may be unTradeable, if you can drop an item normally like a non-quest item then it will NOT be returned to you if you do /fixquests.

**Comment by ImSickPT** [comment] 2016-01-02 20:02
@DarkDemonDragon 1st - Once I ate my corrupted potato and the /fixquests command gave it back to me. 
2nd - Quest Items are marked as Quest Items and they are not droppable. 
3rd - Baab's Wool is an untradeable and cannot be given to you by the /fixquests command.

**Comment by HeyloLP** [comment] 2016-01-02 21:19
@ImSickPT 
i'd like to add that baab's wool a mob drop is and so you could get infinite baab's wool so of you lost it go back to his cave and kill him again

**Comment by ImSickPT** [comment] 2016-01-02 21:54
I was not able to understand you. Please try again.

**Comment by DarkDemonDragon** [comment] 2016-01-04 04:06
@ImSickPT that's exactly my point.

**Comment by ImSickPT** [comment] 2016-01-04 17:16
@DarkDemonDragon sorry, i misunderstood

**Comment by HeyloLP** [comment] 2016-01-05 19:23
@ImSickPT  Baab's wool isn't a quest item just a mob drop

**Comment by ImSickPT** [comment] 2016-01-06 00:49
@HeyloLP really? I already knew that -.-

**Comment by Trixter313** [comment] 2016-01-09 14:20
Duplicate of https://github.com/Wynncraft/Issues/issues/3311

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-09 14:20 UTC
