### ISSUE TITLE
Hunger of the Gerts, Part 1 - "sum txt"

### ISSUE THREAD

**Issue by C0meGetS00me** [Wynncraft/Issues#5434] opened 2016-07-08 11:50 UTC
While doing hunger of gerts part 1 and trying to escape cell i have sum txt error.. what now? :/

**Comment by XavierEXE** [comment] 2016-07-08 23:55
If you get this after solving the puzzle in the cell with the cauldrons, relog or wait a few minutes, or redo the puzzle, your quest book hasn't updated yet. The staff forgot to add text for the quest there, so it just says "sum txt" ._.

**Comment by Moe-Ronickah** [comment] 2016-07-09 01:24
This is a dupe of #3450, but that issue was closed long ago.

**Comment by ThunderRemix** [comment] 2016-07-09 07:47
I encountered this issue with trying to escape the cell without the helmet on.

**Comment by C0meGetS00me** [comment] 2016-07-10 01:27
I wrote /kill and still have this quest, idk what to do, and i had the helmet on.

**Comment by AckroWynn** [comment] 2016-07-21 08:19
It's pretty annoying, because, whatever GM that made this quest, was too lazy to put a unique message in these spots. It will be difficult to assist, if I am needed.

**Comment by Moe-Ronickah** [comment] 2016-07-21 14:19
Can it, will it, be fixed?  I don't know if we should keep this alive, or close it with a notice that it's known, and on the table for fixing.

**Comment by AckroWynn** [comment] 2016-07-26 16:11
Moe, to be honest, I am not sure if it is/what is broken. Can whoever knows what's broken please explain in further detail?

**Comment by Villageacules** [comment] 2016-07-26 18:58
Known bug, addressed this update.

**Closed by Villageacules** 2016-07-26 18:58 UTC
Labels: Quests

**Comment by Jacys2811** [comment] 2016-08-08 18:14
This problem have begun to happen to me too. ._.

**Comment by Jacys2811** [comment] 2016-08-08 18:16
It keeps saying "sum txt" and tp'ing me back in the cell.
I've tried 5 different servers within 20 minutes. :p
