### ISSUE TITLE
Lost my armor for not loaded skill points

### ISSUE THREAD

**Issue by beaumos** [Wynncraft/Issues#4460] opened 2016-03-05 19:39 UTC
I have lost my armor because my skills point are not enough to wear my armor, but if have al my armor on I have enough skills point to wear it all. Now I had a full inventorie when I change the server. Because I had not enough skillpoint to wear some of my armor when I joined the other server. Al my armor disappeared. except my boots and hat, here is a list of my items I have lost :(
![2016-03-05_19 30 20](https://cloud.githubusercontent.com/assets/16364216/13549937/dcd0b7be-e311-11e5-85e7-16b82d343fd3.png)
Please fix this bug, and is it possible that I can get my lost stuff back?

I am sorry if I make some grammer of spelling mistakes, my english is not that good. If you guys aren't understanding me, I wil type my text in dutch and let translate it by google translate ;)

Greetings beaumos,

**Comment by Trixter313** [comment] 2016-03-05 20:27
Duplicate of https://github.com/Wynncraft/Issues/issues/4304

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-05 20:27 UTC
