### ISSUE TITLE
Item bombs give powders that do not stack

### ISSUE THREAD

**Issue by Rellia** [Wynncraft/Issues#6928] opened 2016-12-19 20:36 UTC
The powders received from item bombs are the buggy powders which do not stack with the common powders that are received generally from mobs.

**Comment by Charizard841a** [comment] 2016-12-20 00:00
Throw them on the floor along with the normal, and pick them up. they will almost always restack.

**Comment by Trixter313** [comment] 2016-12-20 04:39
Duplicate of https://github.com/Wynncraft/Issues/issues/6646

**Closed by Trixter313** 2016-12-20 04:39 UTC
