### ISSUE TITLE
Jungle Fever: Liquid Emerald Glitch/Bug

### ISSUE THREAD

**Issue by Slash282** [Wynncraft/Issues#7100] opened 2017-01-04 21:08 UTC
I was doing the Jungle Fever Quest, and I accidentally right-clicked the stack of "Almuj's Liquid Emeralds". It bugged out, now there are 63 of the Emeralds and I cannot finish this quest. Please help

**Comment by thecoolkogut4** [comment] 2017-01-04 23:05
duplicate of  #5567

**Closed** 2017-01-05 00:40 UTC
