### ISSUE TITLE
/fixquests not working

### ISSUE THREAD

**Issue by Lexwomy** [Wynncraft/Issues#2080] opened 2015-07-10 01:38 UTC
When I did fixquests, it gave me 2 purple crystal shards, which i didn't need. It kept on giving me the same items.
![2015-07-09_20 36 10](https://cloud.githubusercontent.com/assets/13265459/8610639/71cbc89a-267a-11e5-9191-c5ed2fec33fd.png)
![2015-07-09_20 39 29](https://cloud.githubusercontent.com/assets/13265459/8610652/9ead861e-267a-11e5-8803-7cc2c0e13922.png)

**Comment by Moe-Ronickah** [comment] 2015-07-10 07:02
Duplicate of #2078 .  Please close this report and make a comment in #2078 , if you wish.  Thank you.

We are just waiting for a fix.

**Closed** 2015-07-11 15:18 UTC
