### ISSUE TITLE
The Shadow of The Beast Gltich?

### ISSUE THREAD

**Issue by Matt10y** [Wynncraft/Issues#4786] opened 2016-04-10 02:03 UTC
After I completed this quest it says I got 1920 emeralds, but I only got like 2 blocks of them. This is really weird, I'm not too mad though.

**Comment by Trixter313** [comment] 2016-04-11 05:46
Duplicate of https://github.com/Wynncraft/Issues/issues/3562

Please direct any future comments top the original thread. Thanks!

**Closed by Trixter313** 2016-04-11 05:46 UTC
