### ISSUE TITLE
Lost Items In Duel.

### ISSUE THREAD

**Issue by LifelessWolf** [Wynncraft/Issues#5023] opened 2016-05-18 20:47 UTC
So I dueled my friend, and when I lost it killed me and I lost EVERYTHING. I'm on World 11 as this is made and my username is LifelessWolf.

**Comment by YunoFGasai** [comment] 2016-05-18 21:15
How many soul points did you have?

**Comment by Trixter313** [comment] 2016-05-23 00:18
Appears to be a duplicate of https://github.com/Wynncraft/Issues/issues/3559

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-05-23 00:18 UTC
