### ISSUE TITLE
Jester Necklace disappeared from bank

### ISSUE THREAD

**Issue by sulkbliss** [Wynncraft/Issues#5320] opened 2016-06-27 14:23 UTC
I picked up a Jester necklace the other day and placed it in my bank. I noticed today that it had* disappeared from my bank. I've since found a second one and this one has yet to disappear, but I found this odd. Perhaps there's a confliction with these new items and the bank system?

IGN Psychedelic10

**Comment by Moe-Ronickah** [comment] 2016-06-27 16:13
"I noticed today that it had all but disappeared from my bank" means that it had almost disappeared, but that it was still there.  I'll take it that is not what you meant.

A couple of questions:
Did you upgrade your bank?  If you did, and the necklace was in the bank, it will vanish, as jester necklaces are based on glass panes, as is the unaccessed part of the bank.
Did you put the necklace in the bank, just before a server reset?  Sometimes there is a tiny amount of server lag that causes items to disappear under those conditions.
Were you in a hurry at any time that you were in your bank?  Sometimes items get accidentally picked up and dropped if you work in your inventory too quickly.

**Comment by sulkbliss** [comment] 2016-06-27 16:21
I upgraded my bank shortly after I had placed the necklace in it. I didn't notice it had disappeared with the tiles. I had no idea that would happen.

**Comment by BlockCrusha** [comment] 2016-06-27 19:24
The exact same thing just happened to me, upgrading bank spaces does indeed completely delete jester necklaces....multiple for that matter, this is the kind of situation where we SHOULD be able to have admins get our items back right? assuming we have evidence, which is unlikely :/

**Comment by Trixter313** [comment] 2016-06-28 00:13
Ah, that would make this a duplicate of https://github.com/Wynncraft/Issues/issues/4091 then.

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-06-28 00:13 UTC
