### ISSUE TITLE
Broken Weapon

### ISSUE THREAD

**Issue by BlahtheIceguy** [Wynncraft/Issues#3622] opened 2016-01-10 09:53 UTC
![2016-01-10_17 50 39](https://cloud.githubusercontent.com/assets/16412301/12220975/defd15f2-b7c2-11e5-994d-4e2c4b15eb70.png)

This happened. I've tried relogging, changing classes, but my fierte has become this. I can't do anything and I've got no usable weapons to get myself out of this.

**Comment by TobiGaming** [comment] 2016-01-10 14:39
Im having the same problem... i got 2 rare spears name "Ik-El_van and Ik_el_vynn" (these where both obtained after the gavel update

**Comment by Trixter313** [comment] 2016-01-10 16:00
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-10 16:00 UTC
