### ISSUE TITLE
Seaskipper

### ISSUE THREAD

**Issue by ImmortalCraft15** [Wynncraft/Issues#7418] opened 2017-02-22 01:49 UTC
I wanted to use the seaskipper to get back to Nemract and the description didn't pop up and I was stuck there for a good 10-15 mins and I had to wait for the server to restart, then I got the description and I spawned at Nemract. Hope this doesn't happen to me again. lol

**Comment by Pyromanical** [comment] 2017-02-22 02:10
If that happens just switch worlds.  If you are still stuck after switching worlds a few times, do /kill, you will respawn back at the beginning of the game, then just walk thru and continue on to what aver you were doing.

**Comment by Numbermaniac** [comment] 2017-02-22 06:16
Duplicate of #7383

**Closed** 2017-02-23 00:47 UTC
