### ISSUE TITLE
Creeper Infiltration

### ISSUE THREAD

**Issue by ReyDeLosCreepers** [Wynncraft/Issues#5881] opened 2016-08-29 19:16 UTC
The creeper infiltration quest is broken, you can't wear the creeper mask because it is unidentified, but you also can't identify it.

**Comment by Zapliner** [comment] 2016-08-30 00:59
same here

**Comment by ZuraSenpai** [comment] 2016-08-30 04:39
The fix seems to be inconsistent. I was able to identify both the creeper mask and the reward bracelet from the Elemental Exercise this afternoon about 8 hours ago. I was unable to identify them yesterday and had to wait a couple of hours for a fix.

Bracelet Reward from Elemental Exercise Quest:
![160a4b2c-6e08-11e6-9928-597baf7a04ac](https://cloud.githubusercontent.com/assets/21308230/18076238/129bf4a8-6e31-11e6-931a-ff69cbf1a6e1.png)

**Comment by Trixter313** [comment] 2016-08-30 22:47
Duplicate of https://github.com/Wynncraft/Issues/issues/5864

**Closed by Trixter313** 2016-08-30 22:47 UTC
