### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by DrWaffleBottom** [Wynncraft/Issues#4343] opened 2016-02-28 21:33 UTC
I made a tier 2 horse and then I brought 2 tier ones and the I put them together making a tier 2 horse but it just got rid of one of them and then I tried put the tier one with the tier thinking it would make tier because I thought it just glitched out and called it a tier 1 and then I put them together and I got a tier 1. This was a lost of 72 emerald blocks which took me a very long time to get because I was only level 28 at the time.

Please fix this and I know there's no proof of all of this but it's just a game.

**Comment by Trixter313** [comment] 2016-02-29 12:38
Duplicate of #4344

**Closed by Trixter313** 2016-02-29 12:38 UTC
