### ISSUE TITLE
Small Typo on name of Merchant

### ISSUE THREAD

**Issue by coreynj** [Wynncraft/Issues#5800] opened 2016-08-22 03:39 UTC
There's a small typo in the name of the Emerald Merchant to the far left in the bank in Almuj. The "E" should be capitalized.

![2016-08-21_22 35 06](https://cloud.githubusercontent.com/assets/21165622/17843132/08737330-67f0-11e6-91d0-baf9c5fd364b.png)

**Comment by Trixter313** [comment] 2016-08-22 04:17
Duplicate of https://github.com/Wynncraft/Issues/issues/3389

Should be fixed in the next update.

**Closed by Trixter313** 2016-08-22 04:17 UTC
