### ISSUE TITLE
Error occoured while contacting login servers.

### ISSUE THREAD

**Issue by KeepoPrideHD** [Wynncraft/Issues#3925] opened 2016-01-30 15:00 UTC
Error occoured while contacting login servers. Are they down?

Of course thousands and thousands of posts say "it just needs time". Well. It consumed enough time already. This bug is't about time, since NO bugs are about time. It's a server error that makes 400 people play instead of 900. In that 500 not playing I am. I can join around one time out of 800 attempts, and I counted that all by myself, confirmed 4 times. Results:
1st join: 789 attempts
2nd join: 845 attempts
3rd join: 809 attempts
4th join: 797 attempts.

As you know, such a number of attempts takes more than an HOUR to do. That means I've already wasted around 4-5 hours on that bug (just to write that lol). I want someone to fix that, since more people try to join than play. Once again: Don't say it;s about time when you don't know what it is about.

**Comment by Trixter313** [comment] 2016-01-30 15:33
Duplicate of https://github.com/Wynncraft/Issues/issues/3917

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-30 15:33 UTC
