### ISSUE TITLE
Pirate Town's npcs

### ISSUE THREAD

**Issue by gabriel338PT** [Wynncraft/Issues#4210] opened 2016-02-21 13:16 UTC
So, recently, with my level 39 warrior, i was heading to llevingar, and i got to pirate town, and i didn't found some npcs!
There wasn't item identifiers and the esmerald merchants! 
Sadly i couldn't take a print, but i hope this will be fixed.

**Comment by Trixter313** [comment] 2016-02-21 14:46
Duplicate of #3272 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-21 14:46 UTC
