### ISSUE TITLE
Corrupted chunks (Roots of Corruption)

### ISSUE THREAD

**Issue by CloudyBogdan** [Wynncraft/Issues#7821] opened 2017-04-12 03:08 UTC
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

I know there has been a report about the missing chunks in Detlas but, check out the missing chunks in the Roots of Corruption.
https://www.youtube.com/watch?v=sLOdmPuz8a0

**Comment by DebugMC** [comment] 2017-04-12 03:13
should be fixed by tomorrow.

**Comment by LordHelmchen98** [comment] 2017-04-12 03:29
Duplicate of #7817

**Closed by LordHelmchen98** 2017-04-12 03:29 UTC
