### ISSUE TITLE
Boats

### ISSUE THREAD

**Issue by TheArmandas** [Wynncraft/Issues#7370] opened 2017-02-12 20:37 UTC
Whenever i place a boat down and try to swim it begins to sink, and also when i placed down my boat near the treasure island it disappeared i had space in my inv so i couldn't of dropped checked everything re-logged and nothing worked

**Comment by thecoolkogut4** [comment] 2017-02-13 01:18
if you want to use a boat, I recommend using Mc version 1.8.9. be aware that when you go into 1.8.9 the wither bar won't load and some textures (for items) will be broken.

**Comment by DebugMC** [comment] 2017-02-13 15:27
Duplicate of #7149 and #6770

**Closed** 2017-02-13 18:48 UTC
