### ISSUE TITLE
Worm Holes Quest Xp Glitch

### ISSUE THREAD

**Issue by DarrianProducts** [Wynncraft/Issues#5137] opened 2016-06-03 20:07 UTC
I have just finished Worm Holes at lvl 55 1% of xp. The quest says it will give 175,000 exp, or 175k exp, and lvl 55 requires 204,000 exp to lvl up. I have finished the quest and my exp ball is nowhere close to full, it is about 1/3 of the way there and that is obviosly not 175,000 exp.

Is this just a glitch, or is the xp a typo, because worm holes is a meduim lvl 55 quest, and there is no way that it would provide 175k xp....

Please help!

**Comment by Moe-Ronickah** [comment] 2016-06-04 02:52
duplicate of #4990 

It's a typo, but I'm still waiting to hear back how much xp it's really supposed to be.

**Closed by Moe-Ronickah** 2016-06-04 02:52 UTC
Labels: Duplicate, Quests

**Comment by DarrianProducts** [comment] 2016-06-05 19:39
Actually not...

**Comment by Moe-Ronickah** [comment] 2016-06-05 23:19
Actually, it is a typo, and it has been fixed.
