### ISSUE TITLE
Cant attack territorys 

### ISSUE THREAD

**Issue by castle6750** [Wynncraft/Issues#6318] opened 2016-10-02 19:52 UTC
Our guild is trying to attack a few territory's, and none of the mobs are spawning to defend it. I know that it glitches sometimes, but not this much. Is this currently a know issue?

**Comment by thecoolkogut4** [comment] 2016-10-03 02:43
if you are attacking a place in gavel, 100% of the time no mobs will spawn. If you attack places in wynn there is a slight chance that mobs will spawn. wars only work in wynn atm.

**Comment by Moe-Ronickah** [comment] 2016-10-03 02:44
Search for "guild attack" and tell me which one of the 51 issues this is a duplicate of.  In other words, you've just broken Area 51 and yes, guild are horribly borked.

**Closed by Moe-Ronickah** 2016-10-03 02:44 UTC
Labels: Duplicate
