### ISSUE TITLE
Wynncraft can't leave guild

### ISSUE THREAD

**Issue by erickgithub** [Wynncraft/Issues#5465] opened 2016-07-12 06:28 UTC
Is there any way I can contact someone to kick me from my inactive guild, changed name and had no idea of this bug till now..

**Comment by sammyvsparks** [comment] 2016-07-12 06:36
Duplicate of https://github.com/Wynncraft/Issues/issues/3665 ; Please read this issue as it contains more information regarding this issue.

**Closed** 2016-07-12 14:01 UTC
Labels: Duplicate
