### ISSUE TITLE
Potions Bug

### ISSUE THREAD

**Issue by TheAllStar** [Wynncraft/Issues#4599] opened 2016-03-19 22:03 UTC
Potions of Healing look like Potions of Mana (it's blue instead of pink).

**Comment by Trixter313** [comment] 2016-03-19 22:14
Could you post a screenshot showing this? Thanks!

**Comment by TheAllStar** [comment] 2016-03-20 18:49
![2016-03-20_11 30 27](https://cloud.githubusercontent.com/assets/17955288/13906364/d316df24-ee91-11e5-87c4-383032336613.png)

**Comment by DarkDemonDragon** [comment] 2016-03-23 12:28
Where you get this? Did you buy it, get it from a mob drop, or randomly pick it up? Also, do you have more than 1?

**Comment by Trixter313** [comment] 2016-03-24 10:47
Appears to be a duplicate of the 2nd part of https://github.com/Wynncraft/Issues/issues/4548

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-24 10:47 UTC
