### ISSUE TITLE
The Ultimate Weapon quest bug

### ISSUE THREAD

**Issue by RockyPlayzMC** [Wynncraft/Issues#4429] opened 2016-03-04 03:42 UTC
The stones in the water (whetstones) aren't spawning please fix

**Comment by Odnod** [comment] 2016-03-04 03:58
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-04 08:51 UTC
