### ISSUE TITLE
SACCHARUMS Bugged ?!

### ISSUE THREAD

**Issue by Neemz** [Wynncraft/Issues#4484] opened 2016-03-06 21:04 UTC
Hi,
I would like to know if for someone SACCHARUMS are bugged ?
I changed many times in another servers but no change :'(
Its the item SACCHARUMS are not generated ? bugged ?

**Comment by Trixter313** [comment] 2016-03-06 21:08
Duplicate of #4236 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-06 21:08 UTC
