### ISSUE TITLE
Quest items aren't spawning

### ISSUE THREAD

**Issue by duclong889** [Wynncraft/Issues#4385] opened 2016-03-01 18:11 UTC
![image](https://cloud.githubusercontent.com/assets/17551875/13436811/9733998e-e013-11e5-8ead-f5b87f0db206.png)
I'm doing Beneath the depths quest but there is no faded map spawning, i tried to relog, switch server, /class but it isn't fix.

**Comment by Trixter313** [comment] 2016-03-01 18:19
Duplicate of https://github.com/Wynncraft/Issues/issues/4236

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-01 18:19 UTC
