### ISSUE TITLE
No permissions to interact in a world

### ISSUE THREAD

**Issue by Padfoot76** [Wynncraft/Issues#4213] opened 2016-02-21 19:14 UTC
I got on this morning and I was questing, and I found out that I couldn't open any loot chests or interact with any buttons or fence gates, etc. When I would right click on these things to try the message that would come up would just say "You don't have permission for this area." If this could get fixed so I can finish a quest or open a loot chest that would be great!
- Padfoot76

**Comment by Alexicon1** [comment] 2016-02-21 19:57
Relog your game, and change classes there and back. It shouldn't be like that.

**Comment by BlueThunder25** [comment] 2016-02-22 03:34
This also sometimes will happen when holding an item, but if you use your bare hand, you will be able to interact with chests and so forth.

**Comment by Trixter313** [comment] 2016-02-22 20:09
Duplicate of https://github.com/Wynncraft/Issues/issues/3902

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-22 20:09 UTC
