### ISSUE TITLE
Quest ???

### ISSUE THREAD

**Issue by unusualphysics** [Wynncraft/Issues#6411] opened 2016-10-17 01:53 UTC
When you put the tech chip behind he who watches the blue next to the red and brown, under the yellow (hint) the door does not open after you throw the item on the ground.

**Comment by unusualphysics** [comment] 2016-10-17 01:53
I could not say where exactly where it was because that would be giving away a part of the ??? quest.

**Comment by ThunderRemix** [comment] 2016-10-17 03:21
you are allowed to say where it is. the yellow flower is known to bug.

**Comment by unusualphysics** [comment] 2016-10-18 01:03
Thanks 👍

**Comment by Trixter313** [comment] 2016-10-19 19:53
Duplicate of https://github.com/Wynncraft/Issues/issues/6138

**Closed by Trixter313** 2016-10-19 19:53 UTC
