### ISSUE TITLE
Mesarock Arch

### ISSUE THREAD

**Issue by airboo** [Wynncraft/Issues#8779] opened 2017-08-15 08:24 UTC
I recently obtained a new legendary bow and found that it wasn't textured with the WynnCraft resource pack textures and appears to be broken or glitched, as you can see it does not look like a bow.

![2017-08-15_16 11 55](https://user-images.githubusercontent.com/31031808/29307870-1a341fe2-81d6-11e7-925d-8294da6c6ab3.png)

**Comment by Rulzzzz** [comment] 2017-08-15 12:52
I have a similar wepaon, Its called "King of Blocks", I think, i forgot :P

**Comment by thecoolkogut4** [comment] 2017-08-15 12:56
Join the server on 1.8.9 and it should be fixed.

**Comment by LordHelmchen98** [comment] 2017-09-29 23:54
Duplicate of #4548

**Closed by LordHelmchen98** 2017-09-29 23:54 UTC
