### ISSUE TITLE
item textures visible before identifieing

### ISSUE THREAD

**Issue by Olaf-jonanas** [Wynncraft/Issues#4311] opened 2016-02-27 15:34 UTC
if you drop unique, rare or legendairy weapons on the ground they show what texture they get after you identify them while you havent identified them yet and when you identify them you dont see the texture swapping animation. 
I know did is a known issue but the next thing hasnt been said:

when you have 2 of the same weapons (same lvl range and for the same class) and they have the same texture when you drop them they stack and when you give the stacked items to the identifier you only get 1 outcome while when you would unstack and when you unstack them and give them to the idenifier it still stacks and you still pnly get 1 item
i tested it and when you put 1 of the items in your bank and then identifiy them seperately by switching what is in your bank and what is in your inventory you get different item stats, so it is not the exsact same item

Sorry for my bad english and not knowing how to spell identify

**Comment by Moe-Ronickah** [comment] 2016-06-03 08:34
Duplicate of #3318 .  If you want to follow the discussion of this issue, please follow the original post.  Thank you.

**Closed by Moe-Ronickah** 2016-06-03 08:34 UTC
Labels: Duplicate
