### ISSUE TITLE
Suspended Flowers, Quest Bug

### ISSUE THREAD

**Issue by Deraklich** [Wynncraft/Issues#4422] opened 2016-03-03 23:14 UTC
I'm stuck on this quest, When i go to the cave (To find the 4 flowers) the texture of the flowers are bugged. In fact, there is only a half-part of the flower who's visible. And i can't take the flowers.
Thanks for your help ! :D (Sorry for my english, I'm French ^^)

**Comment by Odnod** [comment] 2016-03-04 00:47
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-04 23:11 UTC
