### ISSUE TITLE
Bear helmet

### ISSUE THREAD

**Issue by Robinjo7** [Wynncraft/Issues#3837] opened 2016-01-24 12:02 UTC
The helmet you can buy on the The Bear Zoo Island is not updated.

**Comment by Trixter313** [comment] 2016-01-24 17:43
Could you post a screenshot of what the item shows when you mouse over it in your inventory?

**Comment by Robinjo7** [comment] 2016-01-24 18:33
![screenshot 12](https://cloud.githubusercontent.com/assets/16863545/12538118/5023a610-c2d1-11e5-911b-d20ce4ee1737.png)

**Comment by DarkDemonDragon** [comment] 2016-01-26 13:13
Duplicate of #3314 Please close this.

**Closed** 2016-01-27 02:33 UTC
