### ISSUE TITLE
horse glitch

### ISSUE THREAD

**Issue by Tomben1** [Wynncraft/Issues#5206] opened 2016-06-11 21:23 UTC
while riding a horse you can end up not being where you really are. this is especially a problem on the bridge, as you can think your out of the bridge while really being on the bridge. this also affects playing with others as you cant move on horse together quickly.
I think this might be caused by how fast you should move (Speed) and how fast the horse is really moving (the default horse moving speed)

**Comment by Trixter313** [comment] 2016-06-11 21:25
This should only happen while using 1.9+ and we reccomend using 1.8 to play Wynncraft because it isn't 1.9 or 1.10 ready yet. Let us know if switching to 1.8 fixes the issue. Thanks!

**Comment by Moe-Ronickah** [comment] 2016-06-12 12:52
Duplicate of #5188 .  This is a Minecraft issue, not a Wynncraft issue.  Wynncraft is 1.8 and you use any higher version at your own risk.

**Closed by Moe-Ronickah** 2016-06-12 12:52 UTC
Labels: Duplicate
