### ISSUE TITLE
Canyon Condor

### ISSUE THREAD

**Issue by iLeo69** [Wynncraft/Issues#4366] opened 2016-02-29 22:20 UTC
Help. I am doing the quest Canyon Condor and there any gold spawning.

**Comment by Bhaka** [comment] 2016-02-29 23:19
None of the quests where items spawn will work. The server is currently bugged. I have noticed this bug as well with the Suspended Flowers quest. Hope this gets fixed ASAP, gamebreaking.

**Comment by Odnod** [comment] 2016-03-02 06:51
Duplicate of #4236, please close this issue and put any additional comments on the original. Thanks!

Please know that this bug is very well known and is being worked on.

**Closed** 2016-03-02 07:33 UTC
