### ISSUE TITLE
Wynnexcavation Site C

### ISSUE THREAD

**Issue by DubTheDev** [Wynncraft/Issues#4426] opened 2016-03-04 01:06 UTC
# Delete this line if you've searched for a duplicate issue first
At the location of the red crystal, the red crystal shards are not spawning

**Comment by Odnod** [comment] 2016-03-04 01:08
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-04 02:22 UTC
