### ISSUE TITLE
Can't Leave MY Guild

### ISSUE THREAD

**Issue by Shmexy** [Wynncraft/Issues#5658] opened 2016-08-04 15:25 UTC
i can't leave my guild i changed my Username name and now i see everything double in the guild chat  and i can't leave my guild what should i do (no one can kick me)
![2016-08-04_18 24 23](https://cloud.githubusercontent.com/assets/16360421/17407686/f050cdd4-5a70-11e6-9429-87d4532d1b30.png)

**Comment by Trixter313** [comment] 2016-08-04 16:32
Duplicate of #3665 

Guilds are very broken right now and we don't currently have a fix for this issue.

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-08-04 16:32 UTC
