### ISSUE TITLE
Liquid emeralds throwing bug

### ISSUE THREAD

**Issue by C0meGetS00me** [Wynncraft/Issues#5402] opened 2016-07-05 18:25 UTC
Hello, i was just trying to trade with player with LE in my hand, but when i hold Shift and then right click on him my 3 LE has just throw like xp bottle, trade pop up, and xp disappear forever :(

**Comment by YunoFGasai** [comment] 2016-07-05 19:20
the le wasn't thrown, log back in and move stuff in your inventory, its a graphical glitch.

**Comment by Moe-Ronickah** [comment] 2016-07-05 22:17
@C0meGetS00me , did you find your LE?

**Comment by C0meGetS00me** [comment] 2016-07-06 00:28
No, it was 2 days ago. It's not visual bug. I was 56 when this happened and now im 63 so i moved items in my inv very many times.. Idk why this happened..

**Comment by Moe-Ronickah** [comment] 2016-07-06 05:15
I believe that you may have actually thrown the LE on the ground.  LE is protected, in that it cannot be picked up by another player, however, it vanishes fairly quickly.  I suggest that you don't hold LE in your hotbar when you go trade with anyone, so that you don't accidentally drop it.

**Comment by YunoFGasai** [comment] 2016-07-06 06:06
I'll try to recreate the bug

**Comment by YunoFGasai** [comment] 2016-07-06 07:13
cant seem to recreate the bug in game

**Comment by C0meGetS00me** [comment] 2016-07-06 11:55
Moe, i dont dropped it, i was searching for it around and i did not pick it up again, it happened in item identifier room near ragni on emerald trail in small house, close to key merchant, so the space for it to drop wasnt that big, player asked if someone would give him some emeralds to identify item, and I was about to give him some blocks.. Maybe I gave him this LE without putting it in trade, idk :(

**Comment by Moe-Ronickah** [comment] 2016-07-15 13:51
I'm sorry, but this really is a duplicate of #2703.  LE vanishes rather quickly when dropped or thrown.  There is really nothing we can do to help the situation, right now, as admins already know about this.

**Closed by Moe-Ronickah** 2016-07-15 13:51 UTC
