### ISSUE TITLE
Items not spawning on the ground with quests 

### ISSUE THREAD

**Issue by H3EX** [Wynncraft/Issues#4403] opened 2016-03-02 19:10 UTC
Hi,

I've recently joined the server and have some issues with quests. My friend told me items should be on the ground for quests like Suspended Flowers and a few other ones. 

Is this a bug or am I doing something wrong

**Comment by WizKid101** [comment] 2016-03-02 19:12
same here
i dont know why

**Comment by DarkDemonDragon** [comment] 2016-03-02 19:51
Duplicate of #4236 

Please close this issue and follow the original. Thanks!

**Closed** 2016-03-05 05:50 UTC
Labels: Duplicate
