### ISSUE TITLE
Double Sand Swept Tomb Boss Glitch

### ISSUE THREAD

**Issue by TheHeroThief** [Wynncraft/Issues#6861] opened 2016-12-09 21:45 UTC
When I finished the first stage of the boss I jumped witch somehow spawned another one that fell down with me, so when I got to the second stage I was also fighting the first stage of the boss, I was level 58 and it still compleatly wrecked me XD I can imagine how somebody would feel if they were on level and died because of that

**Comment by dyredhead** [comment] 2016-12-10 00:09
same thing happened to me and my friend when we were fighting the dungeon

**Comment by dyredhead** [comment] 2016-12-10 00:10
we just took each took one on

**Comment by dyredhead** [comment] 2016-12-10 00:10
ask a friend to do the dungeon with you

**Comment by dyredhead** [comment] 2016-12-10 00:10
archer works best

**Comment by thecoolkogut4** [comment] 2016-12-10 05:16
duplicate of another issue, can't find it atm (on mobile) but you could be getting x2 xp out of the dungeon if you kill the boss twice

**Comment by Spaites** [comment] 2016-12-10 06:13
My friend and I were put in the same situation. We both died but still received the reward for completing the dungeon. Some people may like this but it is a bug that should be fixed as it can screw over players with few soul points. [Recorded Fight (Youtube).](https://youtu.be/-VCHcC7H9g8)

**Comment by Moe-Ronickah** [comment] 2016-12-21 04:15
Duplicate #6796

**Closed by Moe-Ronickah** 2016-12-21 04:15 UTC
