### ISSUE TITLE
Never ending glitch on Green Skinned Trouble quest

### ISSUE THREAD

**Issue by REXkarmaIsBae** [Wynncraft/Issues#7397] opened 2017-02-19 15:15 UTC
I am on a never ending glitch on the quest called 'Green Skinned Trouble' i am on the part where i need to enter the cave and complete the puzzle. I have finished the light part but i am just falling through the hole repeatedly and it keeps saying "NULL" and i cannot move out of this glitch and i am stuck here until someone helps me out. I play on world 5

**Comment by ColinRioux** [comment] 2017-02-19 20:44
Hi, potential duplicate of #6820. Please do `/kill`, if you can, with 5 or more soul points. I also suggest logging into a different world (since classes carry across all worlds). 

If that gets you out of the hole in which you are stuck, please follow the steps in your quest book carefully, and use the wiki, https://wiki.wynncraft.com/index.php?title=Green_Skinned_Trouble, as a guide. 

Thanks!

**Closed by ColinRioux** 2017-02-19 20:44 UTC
