### ISSUE TITLE
Beneath the Depths quest bug

### ISSUE THREAD

**Issue by treeyo** [Wynncraft/Issues#4299] opened 2016-02-26 23:55 UTC
SPOILERS

I am at the room where the maps are supposed to drop, no maps are dropping.  I even checked the wiki and I was at the right place.  The screenshots even had many maps just sitting on the floor.   I even tried dropping an emerald on the chest.  Please help :c

~treeyo

**Comment by Odnod** [comment] 2016-02-27 00:01
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

This issue is very well known and is being worked in.

**Closed** 2016-02-27 00:27 UTC
