### ISSUE TITLE
Typo in Finding the Light

### ISSUE THREAD

**Issue by GaPoiVN** [Wynncraft/Issues#4966] opened 2016-05-10 10:31 UTC
so Im doing the quest "Finding the Light" , and then I found this typo
http://imgur.com/z1DDdpP
"Sasha: Look, that’s the price. I CAN' change it. It’s all safely stored in my basement."
I think that should be "can't" , not "can'"

**Comment by Endeh** [comment] 2016-05-13 03:02
Duplicate of #4692

**Comment by Trixter313** [comment] 2016-05-13 16:09
Ah, nice catch. Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-05-13 16:09 UTC
Labels: Quests
