### ISSUE TITLE
Guild Xp

### ISSUE THREAD

**Issue by Trollguy69** [Wynncraft/Issues#2083] opened 2015-07-10 20:58 UTC
When i do the command /Guild xp 100 and I kill many mobs my guild is still at lvl1 with 0 XP. Plz fix this bug

**Comment by Moe-Ronickah** [comment] 2015-07-11 20:07
This is a duplicate of #2074 , which is being worked on.

Would you please add any comments that you have to that issue, and close this one?  Thanks!

**Closed** 2015-09-11 19:57 UTC
