### ISSUE TITLE
Armour turns into slime balls and won't apply my new skin.

### ISSUE THREAD

**Issue by PlasticJustice** [Wynncraft/Issues#1971] opened 2015-06-07 20:40 UTC
For the past few months or so, every time I put on armour it turn into slime balls. I was okay with that until I changed my skin and it kept using my old skin. It only happens on my account. On my brother's account his armour doesn't turn into slime balls and it applies his skin changes. So what's wrong and why me?

**Comment by epicman739** [comment] 2015-06-09 01:39
There was an update a while back that added custom armor skins, and the armor had to be replaced with slimeballs to avoid interferance with the custom skins. The armor skin system using your old skin is a known issue, and should be dealt with soon.
If you would like to revert to the old armor system, just use Minecraft 1.7.10.

**Comment by Trixter313** [comment] 2015-06-19 08:13
Duplicate of https://github.com/Wynncraft/Issues/issues/1909 I believe.

**Closed** 2015-07-06 03:37 UTC
Labels: duplicate
