### ISSUE TITLE
LOST ALL MY ITEMS!

### ISSUE THREAD

**Issue by PikaArt** [Wynncraft/Issues#2559] opened 2015-11-25 18:35 UTC
I lost all my items! They got replaced with the starter wand, a marriage ring, and saccharum. When I last logged off I had 1 soul point so I could not have died and lost it! HELP! I am 12|Mage please help me!

**Comment by PikaArt** [comment] 2015-11-25 18:36
If I can not get stuff I might as well quit Wynncraft. Spent all day yesterday playing quests all for nothing.

**Comment by SkySaito** [comment] 2015-11-25 20:19
Sometimes bugs can happen. Don't quit WynnCraft like that for this little problem, since you are only lvl 12, you'll find new gear really fast. And if you quit so fast you'll never experience how cool this server is.
Just continue your journey in this province and you'll not regret it.

**Comment by PikaArt** [comment] 2015-11-25 20:22
It just sucks I have to play a longer time before I can have fun with the harder mobs ;-;

**Comment by SkySaito** [comment] 2015-11-25 20:26
Well it seems bad but this server worth these little problems, but sorry for this :/

**Comment by Moe-Ronickah** [comment] 2015-11-25 20:58
This is a duplicate of #1245.  It is recurring issue that, so far, has defied repair.  Please close this issue, but it will still be noted as still here.

**Closed** 2015-12-25 20:38 UTC
