### ISSUE TITLE
Light dust is not spawning

### ISSUE THREAD

**Issue by Glenncrafter** [Wynncraft/Issues#4482] opened 2016-03-06 19:50 UTC
Hello,

I'm playing wynncraft now and doing the 'temple of legends' quest (from lvl68).
I'm now at the stage where i need light dust for, but for some reasong it's not spawning in the light dust cavern.
I think the spawner isn't placed after the update and now the quest is bugged and we can't do the quest :(

I hope you place a spawner of light dust or just fix the bug.

**Comment by Trixter313** [comment] 2016-03-06 20:53
Duplicate of #4236 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-06 20:53 UTC
