### ISSUE TITLE
i do not have permission to use doors or open chests anywhere.

### ISSUE THREAD

**Issue by Carvex1** [Wynncraft/Issues#6420] opened 2016-10-19 08:02 UTC
i keep getting the "you don't have permission for this area" error message when trying to open chests and doors, but then when i have my friend try to use the chest or door they can open it without any problems. the chests and doors are not restricted in anyway so i don't know what the problem is.

**Comment by LordHelmchen98** [comment] 2016-10-19 18:12
Duplicate of #3902

This issue is related to the retextured items. I thinks its a problem if the weapon is a retextured slab. The game doesnt want you to do something with it and thats why you get those permission messages. It should work fine if you use your bare hands or another weapons that doesnt have that bug.

**Closed** 2016-10-19 19:36 UTC
