### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by sarah7272665** [Wynncraft/Issues#3619] opened 2016-01-09 16:05 UTC
For some reason I cant connect to Wynncraft, it says unable to connect however when it says I can it still wont let me please help!

**Comment by gerlove** [comment] 2016-01-09 16:13
I have the same problem!

**Comment by Deadoverlord** [comment] 2016-01-09 16:27
same i have been checking beck every half hour but it wont let me connect and it says 100/100 people on isnt the server more than 100 people? or slots

**Comment by sarah7272665** [comment] 2016-01-09 16:36
Yea and the error message for me says "Exception Connecting:RuntimeException : Server is online mode! @ net.md_5.bungee.Server.Connector:261"

**Comment by Deadoverlord** [comment] 2016-01-09 16:37
yea

**Comment by Deadoverlord** [comment] 2016-01-09 16:37
same

**Comment by Trixter313** [comment] 2016-01-09 16:54
Duplicate of https://github.com/Wynncraft/Issues/issues/3596

Please direct any future comments to the original thread. Thanks

**Closed by Trixter313** 2016-01-09 16:54 UTC

**Comment by Deadoverlord** [comment] 2016-01-09 16:57
looked at it its about the items not the server and that was 2 days ago it worked perfect yesterday

**Comment by Trixter313** [comment] 2016-01-09 17:14
It's not about items, someone just mentioned items and they are both talking about not being able to connect.

**Comment by Deadoverlord** [comment] 2016-01-09 17:16
yea but still 2 days ago and the person who started it made it about items and other people went into connecting

**Comment by Trixter313** [comment] 2016-01-09 18:07
I don't see anywhere where the OP said anything about items? And no matter when it occured, they are the same issue and some people are getting the same error codes.

**Comment by Deadoverlord** [comment] 2016-01-09 18:22
ok im just trying to watch Ytube bye

**Comment by sarah7272665** [comment] 2016-01-09 18:52
I doubt this is a duplicate. The other issue was two days ago and they probably werent having the same problem. I just want to know whats going on and the other issue isnt specific so I dont know if they got the same error message.
