### ISSUE TITLE
Animal dungeon boss bug

### ISSUE THREAD

**Issue by DavidTennant17** [Wynncraft/Issues#4902] opened 2016-04-27 13:18 UTC
the bug that happened to me is recorded on this video.. https://www.youtube.com/watch?v=hYR-S7LsBKg&feature=youtu.be

**Comment by thecoolkogut4** [comment] 2016-04-27 19:22
what is your IGN? Il go check this out to see if its still going on.

**Comment by DavidTennant17** [comment] 2016-04-28 14:29
DavidTennant17 is my IGN

**Comment by Moe-Ronickah** [comment] 2016-04-30 12:48
Duplicate of #3191 .  Thank you for your video of this issue!  Please refer all future comments to #3191 .

**Closed by Moe-Ronickah** 2016-04-30 12:48 UTC
Labels: Duplicate, Game Mechanics, Quests

**Comment by Moe-Ronickah** [comment] 2016-05-23 00:05
PS - Don't forget to turn off your entity radar, now that we can see that the Boss Cow vanishes.
