### ISSUE TITLE
Guild Experience

### ISSUE THREAD

**Issue by Francis12qwasyx** [Wynncraft/Issues#5090] opened 2016-05-26 17:39 UTC
IGN: Francis12qwasyx
Guild: TNA

Hello,

TNA has experienced quite a few problems regarding the guild XP throughout the past year, with large amounts of XP being suddenly deducted from our total.

We are currently level 52, and until just recently thought that the reason we could not get past level 52 was that this was the maximum level. However another guild has just reached level 53 without any problems ... and now im writing this email.

Basically every time our experience reached an amount close to level 53 it was converted into a negative sum. We once reached 96% on level 52 yet it was set to -96% shortly afterwards and we had to work ourselves back up.

The exact amount of xp we have lost over time is unknown - i remember a while back at level 49 we were reset several times as well. Either way it would be nice to have the xp we have repeatedly lost reinstated some how.

Here are a few screenshots: Note that these were taken in chronological order...
http://imgur.com/a/qlEV8

In addition, a youtuber (MrSebbelonien) who was once in our guild has made several videos where he does not talk about the guild xp, however the videos are uploaded in chronological order and the xp is shown at the top of the screen.

https://www.youtube.com/watch?v=z-tlCt8Q7Rg&feature=youtu.be (42% on 4th June)
https://www.youtube.com/watch?v=CVGvh-EU2Ok&feature=youtu.be (71% on 5th June)
https://www.youtube.com/watch?v=rz8Dy6asTao&feature=youtu.be (-50% on 19th June)
https://www.youtube.com/watch?v=Mvw8vE3aQ-4&feature=youtu.be (-14% on 20th June)
https://www.youtube.com/watch?v=Pe5S2sNi7EA&feature=youtu.be (-15% on 9th August)
https://www.youtube.com/watch?v=DoNeWndpuoc (1% on 15th August)

Heres a picture of our current xp (next to this email and my pc calender to work as timestamp)
http://img.prntscr.com/img?url=http://i.imgur.com/MWlSJeh.png

It would be great if you could do something about this

Francis Nash

--- Pulled from an email i sent to support@wynncraft.com since the reply told me i should bring it into github instead of support---

**Comment by Moe-Ronickah** [comment] 2016-05-26 22:25
Hi, Francis.
I'm sorry about all of the troubles that guilds are having, and I can tell you that Salted and Jumla are aware of the myriad of problems with guilds.  I have heard that a guild overhaul is on the list of issues that they are looking it, however, I have _no idea_ when the guild revamp will happen, nor do I know the extent of what they will do when the revamp comes.  If I hear of anything that is confirmed with all of the guild issues, as to when or what may or will be done, I'll pass it along.
Moe

**Comment by Moe-Ronickah** [comment] 2016-05-27 02:13
PS:
This is a duplicate of #4695 , so I'm closing it.  Please follow #4695 and comment there, as needed.

**Closed by Moe-Ronickah** 2016-05-27 02:13 UTC
