### ISSUE TITLE
Mage Island bug the NPC is not taking what he wants

### ISSUE THREAD

**Issue by mrennix** [Wynncraft/Issues#6557] opened 2016-11-02 23:09 UTC
Rayshryoth is not taking 12 Sky Vapor I did so many things hes just not taking it

**Comment by thecoolkogut4** [comment] 2016-11-02 23:49
walk back down, make sure you hit the tripwire on the way into the vapour cave. then go back up top to him

**Comment by LordHelmchen98** [comment] 2016-11-02 23:52
Do you have a light dust with you?

**Comment by Veilune** [comment] 2016-11-04 04:07
I've got this bug too...
It's telling me in the quest book that I need to give 12 Sky Vapor to Rayshyroth, but when I talk to him he says "Remember, check your quest book for guidance."
![2016-11-03_18 22 42](https://cloud.githubusercontent.com/assets/23252191/19994188/878fe694-a2b0-11e6-859e-e69742accaa6.png)
I've tried a lot of things, including /kill, farming almost a stack of Sky Vapor, /fixquests, hitting the tripwire in the cave and talking to Kelight (Which does nothing).

Would be great if this could be fixed, thanks :)

**Comment by LordHelmchen98** [comment] 2016-11-04 09:39
@mrennix @Veilune This is a bit unclear as neither your quest book nor Rayshyroth tell that to you, but you have to bring a light dust as well. 
Also this seems to be a duplicate of #6372 look there for more information.

**Closed** 2016-11-05 18:52 UTC
