### ISSUE TITLE
Marauder's Dues problem

### ISSUE THREAD

**Issue by Rellia** [Wynncraft/Issues#6922] opened 2016-12-19 11:32 UTC
I have started the quest, Marauder's Dues, and the wizard won't let me get anywhere near him from any angle, shouting about the title every time. The wiki doesn't even mention this as an issue, so, is it supposed to require some sort of armour to complete, or is it bugged?

**Comment by Rellia** [comment] 2016-12-19 11:58
I am now standing infront of him, at the coordinates the quest book tells me to go to, exactly, and...

![penis](https://cloud.githubusercontent.com/assets/23388884/21312085/56e35576-c5e2-11e6-97e8-e49922b930fc.png)

**Comment by LordHelmchen98** [comment] 2016-12-19 13:13
So when you got to him he refused to talk to you? He never said anything else?
The only thing I can imagine right now is that you skipped a quest book update for whatever reason. Maybe it is an update triggered by a tripwire on the ground.

**Comment by thecoolkogut4** [comment] 2016-12-19 13:26
as lord said, you need to walk up the path and walk up the stairs because there's tripwire thst updates your quest book. if you try to jump up/climb up the mountain it will not let you progress in the quest

**Comment by Rellia** [comment] 2016-12-19 14:31
I have run all the way up and down the tower, but I constantly get that message I've made as the title all along the path to the wizard... I don't understand how to update the quest book, because the book already tells me to go to those coordinates and confront the wizard...

**Comment by Rellia** [comment] 2016-12-19 14:32
When I get that message, I get kicked back, just like other barriers to entry or certain areas.

**Comment by Rellia** [comment] 2016-12-19 14:33
Where can I start climbing the path?

**Comment by LordHelmchen98** [comment] 2016-12-19 17:47
Normally you start at that sign that warns you not to enter. Then you go up towards the tower and you sneak through some tunnels to avoid the stronger ranged mobs.

**Comment by Rellia** [comment] 2016-12-19 21:03
where does the path start? I can't find a path to the tower without it...

**Comment by LordHelmchen98** [comment] 2016-12-20 11:59
If you can't manage to find it I can maybe help you later my time zone is CET

**Comment by Moe-Ronickah** [comment] 2016-12-21 18:56
DUPLICATE OF #5696
You can follow and comment on your issue, there.

**Closed by Moe-Ronickah** 2016-12-21 18:56 UTC
Labels: Duplicate
