### ISSUE TITLE
Guilds are not leveling

### ISSUE THREAD

**Issue by MythikiX** [Wynncraft/Issues#2145] opened 2015-07-27 02:26 UTC
Heyo. So I was working on leveling my guild which I havn't devoted myself to until now. But then I soon found out I'm gaining NO GUILD XP whatsoever. And I checked a bunch of times and it says that I contribute 100% of my XP. Still. No dice.

So, if you can, please help by fixing this glitch! Thanks!

Oh, and if you need it, my username is Hellgame.

**Comment by Trixter313** [comment] 2015-07-27 02:57
Duplicate of https://github.com/Wynncraft/Issues/issues/2074

What we suggest doing is closing the duplicate issue and following the original if you'd like to stay up to date on the status of the issue. Thanks!

**Closed** 2015-07-27 17:18 UTC
