### ISSUE TITLE
Stuck in Nether with all classes

### ISSUE THREAD

**Issue by meatloaf4311** [Wynncraft/Issues#4791] opened 2016-04-10 16:49 UTC
I was bored, so while in wynn i wander into the nether portal.

Thing is after realizing lvl 65 isnt high enough, I wanted to leave. But my Wynn position body is still in the portal. And if I try to ./class it still goes to the nether. I am stuck in the nether with no way out.

Help wynn is ruined for me if I cant ever leave.

./kill is disabled in the nether so I cant do that either

**Comment by Lorigami** [comment] 2016-04-10 19:36
Also an issue for me. Please fix! I want to enjoy dxp!

**Comment by Trixter313** [comment] 2016-04-10 19:39
Duplicate of #4784 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-10 19:39 UTC
