### ISSUE TITLE
/find

### ISSUE THREAD

**Issue by Mathmatician17** [Wynncraft/Issues#5835] opened 2016-08-27 23:39 UTC
This isn't really a bug report, but more of a typo.  When you do /find without any arguments, it will say "Invalid Synthax."  I think it might be intentional, but shouldn't it say "Invalid Syntax."

**Comment by Trixter313** [comment] 2016-08-27 23:55
Duplicate of https://github.com/Wynncraft/Issues/issues/5715

**Closed by Trixter313** 2016-08-27 23:55 UTC
