### ISSUE TITLE
the pack

### ISSUE THREAD

**Issue by milbrandtt** [Wynncraft/Issues#4773] opened 2016-04-08 20:56 UTC
It said i was downloading the custom resource pack. then it kicked me and now i dont have the pack and it looks like trash

**Comment by PenguinInSnow** [comment] 2016-04-08 21:26
Hello, All you got to do to fix the problem is go on your server list, Click on Edit and then click on *Server Ressource Packs* to make it Enabled and then when you'll log onto one of the multiple servers, the texture pack should be present. Hope it helped :)

**Comment by milbrandtt** [comment] 2016-04-08 23:24
I just tried that and it does the "do you want to download and automagically install it" and clicked yes but it still doesn't work..

**Comment by Trixter313** [comment] 2016-04-09 00:14
Try closing Minecraft, [going to your .minecraft folder](http://minecraft.gamepedia.com/.minecraft) and deleting anything in the server-resource-packs folder, then restarting Minecraft and attempt to login again.

Also, what version of Minecraft are you using to login?

Thanks!

**Comment by Verret001** [comment] 2016-04-19 13:13
Closed due to inactivity over ten days

**Closed** 2016-04-19 13:13 UTC
