### ISSUE TITLE
Spells and a wand

### ISSUE THREAD

**Issue by Bowmastergo** [Wynncraft/Issues#4318] opened 2016-02-27 20:37 UTC
My wand that i used before the update Dévoreuse stopped working and now the wand i want to use the spells arent working!!! plz fix

**Comment by TrashcanMan** [comment] 2016-02-28 00:57
Yeah, almost all items with accented characters in their name are broken, you'll just have to wait for the fix.

**Comment by Moe-Ronickah** [comment] 2016-02-28 03:28
Duplicate of #3161

Please direct any future comments to the original thread. Thanks!

**Closed by Moe-Ronickah** 2016-02-28 03:28 UTC
Labels: Duplicate
