### ISSUE TITLE
Armor disapearing.

### ISSUE THREAD

**Issue by MageEcho** [Wynncraft/Issues#4337] opened 2016-02-28 18:43 UTC
Hi all,

So, today I logged on, as usual. What was different about today was that, for some reason, i had 3k health instead of my 6k health. Why? Simple. My Crystal and my Spectre(my skill point required armor) were missing. Bug? Fix plez? I dunno, please get my armor back, or do something like what happened last time, where you guys reverted the condition of all players' inventory to a week back, when there were no issues. Please fix, and maybe get my armor back. Thanks a whole ton.

~A concerned archer.(IGN:  _The_Echo_)

**Comment by Zevys** [comment] 2016-02-28 18:59
Same issue that happend to me my crystal 3/4 Mregen and 50 reflection is gone...

**Comment by Trixter313** [comment] 2016-02-28 19:31
Duplicate of #3443 

Unfortunately Wynncraft has a strict no refunds policy so there's nothing we can do about the lost items but we are working on fixing the skill points issue to prevent this from happening again.

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-28 19:31 UTC
