### ISSUE TITLE
Big Bug: Duel killing

### ISSUE THREAD

**Issue by Iceloono** [Wynncraft/Issues#7321] opened 2017-02-04 16:38 UTC
I was starting a new warrior class, and as I was level 9, I challenged a random Lvl 10 Mage. Now the next part I'm not sure if its my Internet or server, but the duel started and we exchanged spells. I was on low health, and tried to get close to him. After some basic attacks, he won the duel, but I used bash right after he used his basic attack and he disappeared/died. We tried to recreate this with me to make sure he wasn't trolling, and surely enough, I was killed, teleported to ragni, and most importantly, lost 2 soul points

**Comment by Iceloono** [comment] 2017-02-04 16:39
This is probably harder to recreate with high level characters

**Comment by Iceloono** [comment] 2017-02-04 16:52
Keep in mind, this is a random Mage, I had no control what he/she did in the duel.

**Comment by thecoolkogut4** [comment] 2017-02-04 18:51
thorns and reflection on your Armour cause you to die (lose 2sp) in duels. I'm pretty sure this is a duplicate

**Comment by Pyromanical** [comment] 2017-02-04 20:01
#3559 and #7090

**Comment by Iceloono** [comment] 2017-02-05 04:19
No I made sure, no thorns or reflection, this is lvl 9. Neutral damage

**Comment by DebugMC** [comment] 2017-02-07 17:31
@Iceloono no it is a dupe of #7090 :I I made that issue myself

**Closed** 2017-05-07 16:50 UTC
Labels: Duplicate
