### ISSUE TITLE
Big hole near the Grand Youth quest

### ISSUE THREAD

**Issue by SS12121** [Wynncraft/Issues#7826] opened 2017-04-12 04:29 UTC
![2017-04-12_12 25 47](https://cloud.githubusercontent.com/assets/26766304/24941271/b2723022-1f7b-11e7-9d7a-67add82d3b50.png)
![2017-04-12_12 26 50](https://cloud.githubusercontent.com/assets/26766304/24941272/b65d917c-1f7b-11e7-9e33-ed3e4e581f8f.png)

**Comment by numbermaniac** [comment] 2017-04-12 08:35
Lots of chunk errors are around the map at the moment. This is a known issue, and a duplicate of #7816.

**Closed** 2017-04-12 09:54 UTC
