### ISSUE TITLE
No Light Dust Spawning in Light dust cave Temple of legends quest

### ISSUE THREAD

**Issue by Frostwulfe** [Wynncraft/Issues#4485] opened 2016-03-06 21:13 UTC
This issue has not been fixed, there are other issues about things not spawning but not this one. I'm not sure if you are aware of this issue but it hasn't been fixed in a while and I can't level up without doing this quest. Please fix this ASAP. Thanks

**Comment by Trixter313** [comment] 2016-03-06 21:34
Duplicate of #4236 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-06 21:34 UTC
