### ISSUE TITLE
Suspended Flowers Issue

### ISSUE THREAD

**Issue by RubixTitan** [Wynncraft/Issues#4115] opened 2016-02-13 17:53 UTC
Hello, I was just going to tell admins/builders/GM's why when you complete suspended flowers you get the xp and boots, however, you do not get the 28 emeralds. Please have a look at the problem. Thank you.

From Rubix Titan

**Comment by Trixter313** [comment] 2016-02-13 18:11
Duplicate of https://github.com/Wynncraft/Issues/issues/3562

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-13 18:11 UTC
