### ISSUE TITLE
/guild stats/leaderboard not working

### ISSUE THREAD

**Issue by motoki317** [Wynncraft/Issues#4749] opened 2016-04-04 08:05 UTC
Title says all, /guild stats, or /guild leaderboard isn't working for about 1 month already.
When I type those commands, it won't show up anything.
By the way, my guild is "UltimateXeons", or "UXs".

**Comment by Moe-Ronickah** [comment] 2016-04-07 02:13
Duplicate of #3529

**Closed by Moe-Ronickah** 2016-04-07 02:13 UTC
