### ISSUE TITLE
I lost my armor

### ISSUE THREAD

**Issue by emilhansen** [Wynncraft/Issues#4168] opened 2016-02-18 09:22 UTC
Hey, yesterday i logged in for the first time after the new update.
I clicked my gear to look at it because it said unidentified and i did not know why.
I had a full inventory and all my gear just disappered.
Can i get it back somehow? Please.. I don't remember what gear i had but it was some pretty rare gear..

**Comment by Odnod** [comment] 2016-02-18 11:01
There is no way to get your gear back, sorry. This same thing happened to me back in December with full old endgame armor.

**Comment by Trixter313** [comment] 2016-02-18 12:13
Duplicate of https://github.com/Wynncraft/Issues/issues/3153

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-18 12:13 UTC
