### ISSUE TITLE
Idol Boss Arena - Mobs can get pushed out of arena

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7211] opened 2017-01-19 17:05 UTC
Pretty easy bu to cause. You just need an archer that can do arrow shield and tier 2 arrow storm. Just spam arrow shield + storm and you can push mobs thru blocks sometimes (and whats rly wierd is their hp bar gets far away...) 

I can show screenshots once I get a chance (prob sat) but easiest mobs to test it on is the Matryoshaka (The boss in jungle village that drops a 20 slot chestplate) or CoW

**Comment by DebugMC** [comment] 2017-01-19 17:06
I can easily get the matryoshka out by arrow shield hits him up then i just hit him. I **THINK** there is a hole in the barriers on the side, as I have hit him above the arena before.

#6439

**Comment by Moe-Ronickah** [comment] 2017-01-19 21:19
This is a job for @AckroWynn , I believe.

**Comment by AckroWynn** [comment] 2017-01-20 14:16
I am not really able to fix this. @Moe-Ronickah this is probably an issue for @Jumla

**Comment by DebugMC** [comment] 2017-01-20 14:42
Also CoW has barriers in the sides of arena that are useless, you can't camp there, its just more places for CoW to get stuck. Sometimes he even tp's into the floor

**Comment by Moe-Ronickah** [comment] 2017-01-21 01:12
It's going to be a while before this is fixed.

**Comment by DebugMC** [comment] 2017-01-23 21:27
I figure the pushing will be a while, but will the arena of CoW be updated? There's a lot of unnecessary barriers on the side.

**Comment by AckroWynn** [comment] 2017-01-25 15:04
The CoW arena is supposed to have all those barriers

**Comment by DebugMC** [comment] 2017-01-25 16:01
But why? Its not like you can get anywhere or get out of agro range... all it does for me is cause more mobs to get stuck in barriers...

**Comment by Moe-Ronickah** [comment] 2017-03-05 14:43
DebugMC, Ackro, a member of the Content Team, has already said that the barriers are supposed to be there.  There is no discussion of this, here.  If you want to discuss why, you will need to post it on the forums.  This is an issue tracker.  Please refrain from this type of discussion.  Thanks.

**Comment by Moe-Ronickah** [comment] 2017-03-05 14:45
Also, as I'm now QA, I'll assign this to myself and see if there is anything that I can do to fix this.

**Comment by Moe-Ronickah** [comment] 2017-03-05 14:48
Ah, Duplicate of #7023

**Closed by Moe-Ronickah** 2017-03-05 14:48 UTC
Labels: Duplicate
