### ISSUE TITLE
issue with the book merchant in thanos

### ISSUE THREAD

**Issue by TomatoViking** [Wynncraft/Issues#7369] opened 2017-02-12 19:55 UTC
at the book merchant in thanos http://imgur.com/x2WAGqr

and this is not just a 1.8.9 thing in 1.10.2 http://imgur.com/eDYumqI

you can still buy the books so this is a rather minor issue

**Comment by thecoolkogut4** [comment] 2017-02-13 01:17
duplicate of #7037

**Comment by ColinRioux** [comment] 2017-02-13 18:44
For reference: this has been fixed on build, and will be pushed in the next map update (which will probably be corkus). Thanks.

**Closed by ColinRioux** 2017-02-13 18:44 UTC
