### ISSUE TITLE
Lost Items

### ISSUE THREAD

**Issue by DementedSorrow** [Wynncraft/Issues#4818] opened 2016-04-13 02:31 UTC
I was grinding, and I filled my inventory with emeralds so I didn't pick up junk. I died, and I lost my legendary bow, my chestplate and helmet.

I also had way over three soul points.

**Comment by Sandertv** [comment] 2016-04-13 12:19
They are not allowed to give back those items, probably because people could just fake it and it wouldn't be fair for other players. I'm sure the answer on this question is going to be a no on refunding. Also, what is this issue even about anyway?

**Comment by YunoFGasai** [comment] 2016-05-13 11:46
this is a duplicate of #3821 please refer any and all comments to the original thread

**Closed** 2016-05-21 04:12 UTC
Labels: Duplicate
