### ISSUE TITLE
Canyon Condor Bug

### ISSUE THREAD

**Issue by Crazyj704** [Wynncraft/Issues#4240] opened 2016-02-24 03:21 UTC
#4236 When I get to the end of the mine near Old Man Jenkins, the gold does not appear on the ground. I have waited about 10 minutes and switched between servers and still it is not there.

**Comment by Odnod** [comment] 2016-02-24 03:23
So it seems this issue is still prevalent. This has been an problem throughout the day and I am sure it is being solved asap.

**Comment by DarkDemonDragon** [comment] 2016-02-24 13:25
Duplicate of #4236 Please close this and follow the original.

**Closed** 2016-02-26 01:32 UTC
