### ISSUE TITLE
Pet Riding Bug

### ISSUE THREAD

**Issue by ItzFlip** [Wynncraft/Issues#3783] opened 2016-01-19 21:06 UTC
So I was recently in the dark woods, and decide to use my silver fish pet. As I was grinding, I rode my pet on accident, and this happened... 

![](http://i.imgur.com/VGYzCC4.png)

Yeah, It became a horse,

And when right clicked again it would change breeds like white, chestnut, and other horse breeeds not in wynncraft. 

Even sometimes a donkey 

![](http://i.imgur.com/WQLBYZ7.png)

So yeah thats pretty much it.

**Comment by BlahBlah161616** [comment] 2016-01-19 23:37
Oooo a donkey, fun!

**Comment by Dar-krusos** [comment] 2016-01-20 01:34
Well, if you can't keep it that way permanently, then it's just a glitch. Did you happen to right-click the pet while holding a saddle? That could be why it occurred.

If, in fact, the pet stays like that permanently, the developers will have to do something about it, so please tell us if it has stayed that way after respawning it.

**Comment by ThunderRemix** [comment] 2016-01-20 01:52
Salted already knows about this bug since I told him about it. The effect is not permanent and can be used to spawn in vanilla saddles. These saddles cannont be used to create horses.

**Comment by HeyloLP** [comment] 2016-01-22 22:00
1. that the pet turns in to a horse is intended
2. the changing breed is a known bug which will be fixed

**Comment by Trixter313** [comment] 2016-01-30 15:20
Are you still experiencing this issue where the horse isn't invisible? Thanks!

**Comment by Moe-Ronickah** [comment] 2016-04-20 22:02
@ItzFlip , fixed or not fixed?  I know, it's not a llama, so it will never be perfect, but is the issue fixed?

**Comment by Moe-Ronickah** [comment] 2016-05-27 03:21
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.

**Closed by Moe-Ronickah** 2016-05-27 03:21 UTC
Labels: Game Mechanics

**Comment by HeyloLP** [comment] 2016-06-03 19:39
the issue is still around

**Comment by Moe-Ronickah** [comment] 2016-06-05 23:08
And it will be, possibly forever, unless our coder can figure out how to make horses and other pets react differently to a right-click.  It's a normal Minecraft interact-with-this mechanic and the pet switching glitch is a feature of Minecraft 1.9.x.

**Comment by DebugMC** [comment] 2017-01-13 19:47
Bug fixed, you can't ride pets/players anymore.
