### ISSUE TITLE
Stop the aids pls items desapearing

### ISSUE THREAD

**Issue by ChaosDunkFTW** [Wynncraft/Issues#5085] opened 2016-05-25 12:09 UTC
I login and fking lose my stuff ? ._.
I was grinding and i logged on then next day when i logged in i lost my speaker,Memento,and jester bracelet !
I payed like 40 le for those 3 items!
Its like the wynncraft doesnt want me 2 play ._.

**Comment by YunoFGasai** [comment] 2016-05-25 12:12
was your inventory full upon logging in? 
how many soulpoints did you have when you logged off? 
where did you log off?

**Comment by ChaosDunkFTW** [comment] 2016-05-25 12:15
i logged in whit 14 sp and yes it was full 
I logged off in  ice thingy area where i grind but i looked around me there was nothing on the ground ._.

**Comment by YunoFGasai** [comment] 2016-05-25 13:16
duplicate of #4814 
please refer all future comments to the original thread

**Closed** 2016-05-25 23:45 UTC
Labels: Duplicate
