### ISSUE TITLE
MY BOW IS A HALF SLAB

### ISSUE THREAD

**Issue by razzoe2880** [Wynncraft/Issues#4667] opened 2016-03-27 09:25 UTC
my precision bow look is a half slab.
is it something in the resource pack or what

**Comment by DarkDemonDragon** [comment] 2016-03-27 13:19
Yes it's probably something to do with the resource pack. What version of Minecraft are you using?

**Comment by Trixter313** [comment] 2016-03-27 14:27
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-27 14:27 UTC

**Comment by DarkDemonDragon** [comment] 2016-03-27 14:32
@Trixter313 he's using the Precision bow not the relic bow.

**Comment by Trixter313** [comment] 2016-03-27 14:43
The other comments and the title mention that it affects other bows also. They are all in one issue rather than being scattered all around.
