### ISSUE TITLE
Could Not Find a Server to Connect to

### ISSUE THREAD

**Issue by Mininglover21** [Wynncraft/Issues#3843] opened 2016-01-24 15:29 UTC
It says it couldn't find a server to connect to and to report it. Is the server restarting or something?

**Comment by pebblewolf** [comment] 2016-01-24 15:34
I am having the same problem

**Comment by sonicrush** [comment] 2016-01-24 16:24
Same. Please help!

**Comment by samwj02** [comment] 2016-01-24 17:16
Happening to me as well :s

**Comment by Trixter313** [comment] 2016-01-24 18:04
Duplicate of https://github.com/Wynncraft/Issues/issues/3830

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-24 18:04 UTC
