### ISSUE TITLE
Players can't log into servers when joining with default "play.wynncraft.com"

### ISSUE THREAD

**Issue by Rentai** [Wynncraft/Issues#5059] opened 2016-05-22 19:59 UTC
play.wynncraft.com seems to place users in a fallback lobby.

Players can only join servers if they join with an IP address other then "play.wynncraft.com".

https://forums.wynncraft.com/threads/having-problems-logging-into-a-server-try-this.127688/

**Comment by Devdiablooper** [comment] 2016-05-22 20:16
i've already tried that, won't work for me.

**Comment by Moe-Ronickah** [comment] 2016-05-22 23:08
If play.wynncraft.com isn't working for you, then try play.wynncraft.net.They are exactly the same server, but, for some reason, they seem to be handled differently by the main server.  It's also possible that while one isn't working NOW, it will work in 5 min.  If you are still having trouble, shut down Minecraft, wait 5 min., then try again. Sometimes, it takes 2 or 3 tries to get in, but you will get in.

**Comment by AVeryBoredGamer** [comment] 2016-05-25 02:33
Moe-Ronickah, doesn't work, stop saying that and closing the forums.

**Comment by Moe-Ronickah** [comment] 2016-05-26 00:11
@AVeryBoredGamer , it does work, and I will keep saying it.  I've been stuck in the fallback server loop for more than 30 minutes.  Changing the IP may be the solution, time may be the solution.  Either way, the admins are aware of it, and creating multiple issues of it is pointless.  I could just as easily close every issue, and just tag it as "DUPLICATE", there are enough of them that finding an open one should not be a problem.

**Comment by Moe-Ronickah** [comment] 2016-05-27 03:44
After doing some reading, and talking to some people, I've learned a few things.  First, the fallback server is a place that players should go to pretty much only if the main lobby is fully packed, so players going there just shouldn't happen, as more lobbies should open up, instead.  Second, the issue of the compass not working in the fallback lobby is unrelated to the fallback server, itself.

Third, your ONLY options are to use an alternate game address, such as .net or .org or exit the game and _wait long enough_ for the server to "forget" that you were there.

My other comments, above, remain valid.  We will just have to bear with it until the issues get resolved.

**Comment by Moe-Ronickah** [comment] 2016-06-03 15:09
duplicate of #5012

**Closed by Moe-Ronickah** 2016-06-03 15:09 UTC
Labels: Duplicate
