### ISSUE TITLE
Accents Destroying Items (Pélier)

### ISSUE THREAD

**Issue by Boomfan56** [Wynncraft/Issues#3291] opened 2015-12-28 19:13 UTC
I recently decided to identify my Pélier legendary helmet. It worked fine until I switched servers, when it turned into a string of raw code and stopped giving any bonuses at all (no health or anything else). It seems the game doesn't recognize it as armor. I'm fairly certain the accent is causing this problem as my other accented items are bugged as well and have been in the past. 

http://i.imgur.com/Rsn4SmS.png

**Comment by Trixter313** [comment] 2015-12-28 20:59
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please add any further comments to the linked issue. Thanks!

**Closed by Trixter313** 2015-12-28 20:59 UTC
Labels: duplicate
