### ISSUE TITLE
Spawn Glitches

### ISSUE THREAD

**Issue by M00BAK** [Wynncraft/Issues#8645] opened 2017-07-22 23:59 UTC
My friend and I, who are both Level 45, were working on the quest "Green Skinned Trouble", which takes place in the Gavel Province/around Llevigar. He is an Archer and I am an Assassin, so naturally he has less defense. He died to some of the rats on the "Only one of the paths will show the way" part of the quest, in the Orc dungeon.

When he respawned, he was all the way at the beginning of the game. The very beginning, like, before Ragni. Which is in the Province of Wynn.

Obviously, he had gone into Llevigar beforehand, so he should've respawned there. Instead, he respawned where he did, the tutorial area.

Is there some issue in classes that cause this, or something involving the coordinates of the dungeon? Is there any way to stop this, and has it happened to anyone else?

**Comment by Locky1110** [comment] 2017-07-23 05:15
The reason he respawned there is because its the location of the place
Since its so far, it didn't know where to spawn him, thus spawning him at the caravan. I'm pretty sure theres not way to stop this.

**Comment by Villageacules** [comment] 2017-08-01 04:27
There is currently no way around this due to the way the respawn system works in Wynn, but there may be fix in the future for those offmap quest areas. I will leave this open.

(Duplicate of #7893 , #7936 , and others)

**Closed** 2017-10-01 21:46 UTC
