### ISSUE TITLE
Wynncraft Excavation Site c

### ISSUE THREAD

**Issue by DikkeHenk1989** [Wynncraft/Issues#4351] opened 2016-02-29 12:27 UTC
I tried to finish the quest Wynncraft Excavation Site C.
Last objective of the quest is to escape the cave with the crystal.
But the crystal is nowhere to be found, im at the location where it should be. 
Switched to different lobby's but without succes.

Any1 knows how to fix this?

**Comment by 63502** [comment] 2016-02-29 17:40
The quest is bugged. Red crystal shards do not drop at this time, so the quest cannot be completed.

**Comment by DikkeHenk1989** [comment] 2016-02-29 18:04
Please fix this.

**Comment by Moe-Ronickah** [comment] 2016-02-29 21:05
Duplicate of Quest Items Are Not Spawing #4236 .  Please refer all future comments to the original thread.

**Closed by Moe-Ronickah** 2016-02-29 21:05 UTC
Labels: Duplicate
