### ISSUE TITLE
Emerald Merchant Reveals Item Names

### ISSUE THREAD

**Issue by Exvhius** [Wynncraft/Issues#4180] opened 2016-02-19 21:18 UTC
I've only noticed this in the Emerald Merchant Menu, but it might work in Weapon and Armor shops too. I don't know, I'll check when I can get back on Wynncraft.

If you go into the Emerald Merchant trade menu with an unidentified item, its normal name will show up in italics.

Example:
I loot an unidentified Legendary 68-72 dagger from the temple of legends.
I go to the emerald merchant in Troms
I mouse over the dagger. It reads "_Chakram_"
I go to the Item Identifier. The daggers are indeed Chakram.

**Comment by Trixter313** [comment] 2016-02-19 21:58
If you could post a

**Comment by SpeederSam** [comment] 2016-02-20 01:32
It has happened for me also. All I would have to do to know if the weapon is good is to look it up in the wiki.

**Comment by ThunderRemix** [comment] 2016-02-20 23:03
Dupe of #4059

**Comment by Moe-Ronickah** [comment] 2016-02-21 00:45
Admin have been notified.

**Closed by Moe-Ronickah** 2016-02-21 00:45 UTC
Labels: Duplicate
