### ISSUE TITLE
Lost Twenty Seven Blocks of Emeralds in the Zombie Dungion

### ISSUE THREAD

**Issue by drag0nr1der** [Wynncraft/Issues#2494] opened 2015-11-07 14:40 UTC

**Comment by drag0nr1der** [comment] 2015-11-07 14:41
Seawingfire lost here entire wealth in the Zombie Dungion.

**Comment by drag0nr1der** [comment] 2015-11-07 14:42
did not die or press q

**Comment by brainscript** [comment] 2015-11-07 14:46
@drag0nr1der I don't think anybody can help you with a **_detailed_** description like this. *#Sarcasm*

**Comment by SeawingFire** [comment] 2015-11-07 21:20
SeawingFire is me and i'll tell you detailed. I was waiting just outside of the zombie dungeon. Waiting for Drag0nr1der. We went in and during the parkour I fell off . In the boss room we killed the boss with fire so he died of fire and responed. We finally killed him again and I was so happy. Before we went in we made a deal about horse trading. So I went in my inventory to find the emerald blocks and they were gone. All 37  of them.

**Comment by SeawingFire** [comment] 2015-11-08 17:53
27 of them

**Comment by SeawingFire** [comment] 2015-11-08 22:30
I was level 37 mage

**Comment by DarkDemonDragon** [comment] 2015-11-09 02:05
This can't really be resolved without proof. If staff allowed you to receive your emeralds like this, tons of trolls would claim they also "lost" emeralds and demand them to be "returned" :/

**Comment by SeawingFire** [comment] 2015-11-14 13:55
I know I just reporting a bug. Don't need them back.

**Comment by FlyingfrogsES** [comment] 2015-11-14 22:21
Wynncraft does not have refunds on items deatoryed by a glitch or being dropped by the user. What most likely happened was that you dropped them. Therefore this was not a bug :)

**Closed** 2015-12-25 20:38 UTC
