### ISSUE TITLE
item gliched

### ISSUE THREAD

**Issue by jojoIv** [Wynncraft/Issues#3486] opened 2016-01-03 00:01 UTC
![2016-01-02_16 59 13](https://cloud.githubusercontent.com/assets/16521494/12076670/45748146-b172-11e5-819c-526a85eaa4a4.png)
what happened? This was a legendary spear previously why is it like this now?
can someone please help?
thanks

**Comment by Trixter313** [comment] 2016-01-03 00:02
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-03 00:02 UTC
