### ISSUE TITLE
bolt blizzard and arrow storm are not working

### ISSUE THREAD

**Issue by herobrian11** [Wynncraft/Issues#2742] opened 2015-12-21 18:16 UTC
bolt blizzard and arrow storm are not working but says it is casted and takes mana and does no dmg or show any way of seeing it

**Comment by Trixter313** [comment] 2015-12-22 21:41
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Trixter313** [comment] 2015-12-22 21:48
Duplicate of https://github.com/Wynncraft/Issues/issues/2730

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!

**Closed** 2015-12-25 20:35 UTC
