### ISSUE TITLE
I can't identify the Ghostly Helmet

### ISSUE THREAD

**Issue by mistleberry** [Wynncraft/Issues#5914] opened 2016-08-30 15:40 UTC
I cannot identify the ghostly helmet as it already says it has been identified when it hasn't. I can provide you with pictures if you need me to.

**Comment by Trixter313** [comment] 2016-08-30 19:18
The pictures would be helpful, thanks!

**Comment by Trixter313** [comment] 2016-08-30 22:49
Duplicate of https://github.com/Wynncraft/Issues/issues/5911

**Closed by Trixter313** 2016-08-30 22:49 UTC
