### ISSUE TITLE
Sister City Quest Bug

### ISSUE THREAD

**Issue by mdragonwhite** [Wynncraft/Issues#4277] opened 2016-02-25 20:14 UTC
I can't find the hourglass sand in selchar

**Comment by MrMaggen** [comment] 2016-02-25 20:19
it is to the right of the way you get up

**Comment by Odnod** [comment] 2016-02-25 20:23
Duplicate of #4236, please close this thread and put any additional comments on the original. Thanks!

**Closed** 2016-02-25 21:50 UTC
