### ISSUE TITLE
Guild bag report

### ISSUE THREAD

**Issue by reddddddxd** [Wynncraft/Issues#7279] opened 2017-01-28 11:21 UTC
I cant leave my guild and nothing is working...

**Comment by LordHelmchen98** [comment] 2017-01-28 12:28
Duplicate of #3665. Look there for more information.
Unfortunately there is no known fix so you will have to wait until guilds get fixed. Hopefully that happens soon.

**Closed** 2017-01-28 14:50 UTC
