### ISSUE TITLE
beneath the depths mage

### ISSUE THREAD

**Issue by meelock** [Wynncraft/Issues#3540] opened 2016-01-04 23:23 UTC
the mage at mage island didn't take my faded map, nor the 20 eb, so i ended up with both the old and the new map...

**Comment by DarkDemonDragon** [comment] 2016-01-05 13:09
As long as you have the new map and your questbook updates, you are good to continue the quest.

**Comment by meelock** [comment] 2016-01-10 02:50
but still the quest is bugged, and probably needs to be fixed.

**Comment by Trixter313** [comment] 2016-01-30 04:47
Duplicate of https://github.com/Wynncraft/Issues/issues/3416

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-30 04:47 UTC
