### ISSUE TITLE
Temple of Legends light dust

### ISSUE THREAD

**Issue by Moneybags101** [Wynncraft/Issues#4390] opened 2016-03-01 22:11 UTC
#4287 So I did everything the quest told to do. I found the light cave and no lightdust seems to spawn when the quest said go back to jorkin he just says "do you have the dust?" and I cant continue without it. I tried going on different servers, restarted minecraft. But nothing seens to be working. I hope you can help me with this. Thank you

Minecraft name: Moneybags101

**Comment by Odnod** [comment] 2016-03-02 06:50
Duplicate of #4236, please close this issue and put any additional comments on the original. Thanks!

Please know that this bug is very well known and is being worked on.

**Closed** 2016-03-02 07:48 UTC
Labels: Duplicate
