### ISSUE TITLE
Guild xp not Increasing

### ISSUE THREAD

**Issue by IcyShrub** [Wynncraft/Issues#7408] opened 2017-02-20 19:09 UTC
I had guild xp set to 100% and after a bit it stopped increasing the guild xp even though it said xp was still going to the guild. 
![2017-02-20_13 02 31](https://cloud.githubusercontent.com/assets/21267762/23138550/b0eb01ec-f76d-11e6-95ba-dcd48506f90d.png)
![2017-02-20_13 03 06](https://cloud.githubusercontent.com/assets/21267762/23138553/b6b28cc6-f76d-11e6-9698-b560292e2459.png)
![2017-02-20_13 03 15](https://cloud.githubusercontent.com/assets/21267762/23138557/be05567a-f76d-11e6-97d4-977d22efab5b.png)

**Comment by DebugMC** [comment] 2017-02-20 19:23
Guilds will be reworked "Soon™"

**Comment by ColinRioux** [comment] 2017-02-21 01:35
This is a duplicate of many issues, and has already been reported. The development team is aware of it, and the whole system needs to be redone anyways. 

There is no release date of when guilds will be fixed.

**Closed by ColinRioux** 2017-02-21 01:35 UTC
