### ISSUE TITLE
Guild 

### ISSUE THREAD

**Issue by Alphacrafting** [Wynncraft/Issues#6337] opened 2016-10-05 06:33 UTC
I can't leave my guild, I keep in typing yes into the sign and after I will lose 3 soul points but I cant leave.

**Comment by Imaxe** [comment] 2016-10-05 09:02
You probably changed your name. Didn't you? You can't leave a guild if you've changed the name. This will be fixed in the future.

**Comment by Alphacrafting** [comment] 2016-10-05 09:52
If I change my name back to original will it work?

**Comment by Trixter313** [comment] 2016-10-05 18:53
Duplicate of #3665 

You can try changing it back but I believe that that hasn't worked for people in the past.

**Closed by Trixter313** 2016-10-05 18:53 UTC
