### ISSUE TITLE
Green Gloop Quest Bugged

### ISSUE THREAD

**Issue by xRiftx** [Wynncraft/Issues#3413] opened 2016-01-01 03:26 UTC
The Level 31 quest "Green Gloop" is bugged. I gathered the 8 Slimey Goo required to complete the quest, and the NPC Eluzterp won't accept the items and just asks "Have you gotten the 8 Slimey Goo yet?"
![2015-12-31_19 19 14](https://cloud.githubusercontent.com/assets/16505993/12069656/42ed2a42-aff4-11e5-8ff7-4f4acf32e4ea.png)

My IGN is Riftide, and I'm not sure if this bug is just for me or if it has been affecting other players as well.

**Comment by Trixter313** [comment] 2016-01-01 07:39
I believe this is a duplicate of https://github.com/Wynncraft/Issues/issues/3227

Please refer future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-01 07:39 UTC
