### ISSUE TITLE
Ranked player can bring others into the TOL

### ISSUE THREAD

**Issue by ComputerDude** [Wynncraft/Issues#5644] opened 2016-08-01 22:06 UTC
I have no proof, but someone said that if anyone who is VIP/VIP+ and sits on a player that has not done the TOL quest, they can enter.

**Comment by Trixter313** [comment] 2016-08-01 22:37
This has been reported before and closed by a staff member so admins are aware of the issue, if it still even exists. I thought I remembered it being fixed but maybe not.

Duplicate of https://github.com/Wynncraft/Issues/issues/2102

**Closed by Trixter313** 2016-08-01 22:37 UTC

**Comment by Moe-Ronickah** [comment] 2016-08-03 14:04
If you see someone in ToL who is obviously of too low a level to be in there, you can take a screen cap of them and report them on the forums in Player Reports.  Also, if you see someone taking a friend in there, and can get a video of it, please do the same.  The moderators will deal with players who abuse glitches.
