### ISSUE TITLE
Horse lag?

### ISSUE THREAD

**Issue by Joaofelipe2502** [Wynncraft/Issues#6754] opened 2016-11-22 23:00 UTC
Wynncraft. I have been experiencing some issues with horse lag... It seems that every now and again  
my horse will kind of stop, well, I will keep going, but whenever I dismount I will be sent back a couple of blocks. Im not sure how anti-cheat works on this server, so Im not sure if thats an anti cheat thing. I tried to do a couple of tests to see if I could figure anything out, but I never notice when it happens, but I do know one thing: when it happens, mobs will hit me, but on the spot my horse froze, so it does not help when Im running away from mobs 10levels more then me to complete a quest... If somebody could tell me a way to fix this, or if they will fix it, that would be great.

**Comment by LordHelmchen98** [comment] 2016-11-22 23:07
Thats an issue with Minecraft versions. In 1.8 and below horses are server sided but in 1.9+ horses are client sided. Every time you lag only a little bit the game thinks you are standing still but your client is still riding and mobs are hitting you. You can prevent this by playing in 1.8.9. Its the version with least bugs and glitches but you won't be able to see item skins (crate rewards) or totems (you'll see a sponge block instead)

**Comment by ColinRioux** [comment] 2016-11-24 03:29
Duplicate of #6077

**Closed by ColinRioux** 2016-11-24 03:29 UTC
