### ISSUE TITLE
Guilds attacks don't work

### ISSUE THREAD

**Issue by pierrepier5** [Wynncraft/Issues#5614] opened 2016-07-29 15:23 UTC
Hi,
Yesterday, my guild (Les Sheuveaux) have started a guild attack.
Be were teleported, but no mobs were spawned and, we done "/hub" for
 try again. And we can't start a guild attack because "we are alredy in battle".

We have expected 1 hour, 2 hours ... and 1 day. But we are again in attack.

Thank to help me !

**Comment by Trixter313** [comment] 2016-07-29 15:37
Duplicate of https://github.com/Wynncraft/Issues/issues/5604

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-07-29 15:37 UTC
Labels: Duplicate
