### ISSUE TITLE
Life steal not working with assassin

### ISSUE THREAD

**Issue by opps123456789** [Wynncraft/Issues#3811] opened 2016-01-22 00:19 UTC
I'm wearing an executioner helmet with 200+ life steal and I don't get any health back when I use my multi hit. Please fix :)

**Comment by Trixter313** [comment] 2016-01-23 03:00
Duplicate of #3225

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-23 03:00 UTC
