### ISSUE TITLE
Can't create a guild.

### ISSUE THREAD

**Issue by Lafy** [Wynncraft/Issues#3499] opened 2016-01-03 11:32 UTC
I'm trying to create a guild. But whatever name I choose (using English characters) gives me this error: "Please use English characters A-Z name for your guild name."
I want to call my guild: "SleepingKnights"
Help me please.
Thank you all!

**Comment by Trixter313** [comment] 2016-01-03 11:43
Duplicate of https://github.com/Wynncraft/Issues/issues/3190

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-03 11:43 UTC
