### ISSUE TITLE
Can't complete quest

### ISSUE THREAD

**Issue by JJVDM** [Wynncraft/Issues#4296] opened 2016-02-26 18:47 UTC
I just started whit a new class, and I just was at the quest Thieving Rode. but wenever I got the wedingring, Kelri didin't accept this, at one point I got 5 ring's and 3 rustig metel, he stil did not accept this. plz fix it

**Comment by Moe-Ronickah** [comment] 2016-02-26 19:03
Duplicate of #4236 .  Please follow that issue for more information.

**Closed by Moe-Ronickah** 2016-02-26 19:03 UTC
