### ISSUE TITLE
Guild Leaving bug

### ISSUE THREAD

**Issue by SrEnderPvP** [Wynncraft/Issues#6716] opened 2016-11-17 22:25 UTC
Hello, in my guild there are all inactive, and i want to leave, but actualy i use /guild leave and type yes in the sign, then it says "[Guild] SrEnderMC has left the guild", and stole me 3 sp, but i make there twice and im still in the guild, please help.
![bug](https://cloud.githubusercontent.com/assets/21069832/20410415/80331d3a-ace2-11e6-94eb-22e825b3f4e9.png)
![bug1](https://cloud.githubusercontent.com/assets/21069832/20410416/818e76a2-ace2-11e6-83a7-307260d44337.png)

**Comment by ColinRioux** [comment] 2016-11-18 01:17
Duplicate of #3665
There is a current bug that is known that you can't leave your guild if you have changed your minecraft username while in that guild. As unfortunate as that may sound, you can't leave until this has been patched (and we don't know an ETA for that). 

There's nothing the staff can do at this time, and many other users like yourself are affected by this.

**Closed by ColinRioux** 2016-11-18 01:17 UTC
