### ISSUE TITLE
i cant leave my guild

### ISSUE THREAD

**Issue by Vydros** [Wynncraft/Issues#5026] opened 2016-05-19 12:55 UTC
# Delete this line if you've searched for a duplicate issue first
I CANT LEAVE MY GUILD HELP ME

**Comment by Odnod** [comment] 2016-05-19 17:11
Have you changed your username recently?

**Comment by Vydros** [comment] 2016-05-20 03:21
I only changed my username once

**Comment by Vydros** [comment] 2016-05-20 03:23
when i use guild chat, i type "/g hi" and the chat says 
_FlamingTiger:hi 
_FlamingTiger:hi
twice

**Comment by Vydros** [comment] 2016-05-20 03:25
i have a question, it means i have to change my username back to my old name? then only i can leave my guild?

**Comment by KrabTheScrab** [comment] 2016-05-20 08:37
Its a known bug i am sure the devs will get it fixed soon
בתאריך 20 במאי 2016 06:25,‏ "Vydros" <notifications@github.com> כתב:

**Comment by Trixter313** [comment] 2016-05-23 00:25
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-05-23 00:25 UTC
