### ISSUE TITLE
LE DISSAPEARED

### ISSUE THREAD

**Issue by Gftdcrafter56** [Wynncraft/Issues#5548] opened 2016-07-22 07:07 UTC
I RIGHT CLICKED MY LE ACCIDENTLY AND MY LE DISSAPEARED IVE TRIED RELOADING BUT ITS GONE ITS NOWHERE

**Comment by sammyvsparks** [comment] 2016-07-22 07:35
@Gftdcrafter56 Liquid Emeralds are by default a throwable item and minecraft mechanics cannot be changed in that way, thus they can and will bug when thrown occasionally. We recommend to not hold them or keep them in your hotbar so accidents cannot happen.
However Wynncraft has a strict No-Refund Policy against items in-game. Sorry for any inconveniences you may have from this.

Also please reference https://github.com/Wynncraft/Issues/issues/2703 (may count as duplicate).

**Comment by Moe-Ronickah** [comment] 2016-07-22 19:41
It is a duplicate of #2703 .

**Closed by Moe-Ronickah** 2016-07-22 19:41 UTC
Labels: Duplicate
