### ISSUE TITLE
Pelier Helm can't be enchanted?

### ISSUE THREAD

**Issue by Sync-L** [Wynncraft/Issues#2369] opened 2015-10-03 15:08 UTC
The item identifier says what he usually says when you dont right click him with a weapon or armour that's not unique, rare, or legendary. I've tried switching servers, logging off and back on, different identifiers, and changing classes. Is it just the helm or it's the pelier?

**Comment by Trixter313** [comment] 2015-10-03 15:35
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

We recommend closing the duplicate and following the original to stay up to date on the status of the issue. Thanks!

**Closed** 2015-10-04 00:07 UTC
