### ISSUE TITLE
Sister City - Sand does not spawn

### ISSUE THREAD

**Issue by Adriaanbe** [Wynncraft/Issues#4252] opened 2016-02-24 18:09 UTC
Hello,

I wanted to complete Sister City quest but couldn't find hourglass sand on Selchar.
I've checked on the tower close to the tower, around the tower and switched servers multiple times.

So is there anyone who knows what the source of this problem is?

Thank you!

adriaan_b

**Comment by Odnod** [comment] 2016-02-24 18:12
Duplicate of #4236, please put any additional comments on the original page and close this one.

**Closed** 2016-02-26 01:35 UTC
