### ISSUE TITLE
Powders Bug

### ISSUE THREAD

**Issue by Payton53** [Wynncraft/Issues#7404] opened 2017-02-20 08:56 UTC
So i have an occasional bug when I have powders in my inventory and pick up a new one, the new powder refuses to stack with the previous. This is a bug that is not just happening to me sadly, i've asked others and even seen my friend struggle through it. Sometimes trading with a person and having them stack them works, but this method is not foolproof.

**Comment by LordHelmchen98** [comment] 2017-02-20 13:05
Duplicate of #6646 
Powders from normal drops, item bombs, relics or powder imps wont stack. Sometimes you can throw them out of your inventory in order to stack them, but if that doesnt work you can still upgrade them because every powder master will give you the same type of powders.
However staff is already aware of this issue and according to #6646 they now know why this happens, but they dont know when they can push the fix.

**Closed** 2017-02-20 16:22 UTC
