### ISSUE TITLE
Quest bug

### ISSUE THREAD

**Issue by BroBroSkope** [Wynncraft/Issues#4450] opened 2016-03-05 08:29 UTC
I am a archer with lvl 68 and i am doing the quest: temple of legends. I have a few stages done but i cant get through this stage because i dont get a lightdust. i need this to finish this stage . Pls help me how i get it because ther didn't spawn anything:(

**Comment by Odnod** [comment] 2016-03-05 08:46
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Comment by BroBroSkope** [comment] 2016-03-05 08:53
But i need it and i cant wait . when is it fixed?!

**Comment by Odnod** [comment] 2016-03-05 10:26
Nobody knows quite when it will be fixed, but when it is I will notify everyone on post #4236, now please close this thread as it is a duplicate :)

**Closed** 2016-03-05 13:45 UTC
