### ISSUE TITLE
[Quest] WynnExcavation Site C - No Crystal Shards Spawning

### ISSUE THREAD

**Issue by Daaan26** [Wynncraft/Issues#4392] opened 2016-03-01 22:37 UTC
**The Issue**
I am doing the WynnExcavation Site C Quest. I started the quest at the NPC and headed into the Diamond Pickaxe Room. I spied the secret meeting, and went through a room with some aggressive high level golems. Then I spoke to the ??? NPC, who later is revealed as the traitor, and I went ahead to investigate the giant Crystal. In that cave should spawn Crystal Shards on the floor near the end (I checked it in a video of Mr. Sebbelionian doing the quest), but none were there. I stayed there for a couple of minutes, but couldn't find anything. 
As I went through the portal again, I got teleported back to the NPC where I started the quest. But I couldn't finish it since I got no Crystal Shards.

I think the spawning of the Crystal Shards is broken. Just like the sand spawning on Selchar was broken too a couple of days ago.

If hope my summary was clear enough for you to understand the issue and that you are able to fix it.

Best regards,

Daaan26

**Comment by Crafterbird2** [comment] 2016-03-01 22:46
The same thing happened to me too. I hope it gets fixed soon.

**Comment by kmo900** [comment] 2016-03-02 02:25
NO this is happening several drops quests i saw it in the spider cave and also in the suspended flowers. reading thrugh the issues i think it is the same problem with the diamond shards

**Comment by Odnod** [comment] 2016-03-02 06:52
Duplicate of #4236, please close this issue and put any additional comments on the original. Thanks!

Please know that this bug is very well known and is being worked on.

**Closed** 2016-03-02 07:46 UTC
Labels: Duplicate
