### ISSUE TITLE
Texture bow bugged

### ISSUE THREAD

**Issue by Giantboss** [Wynncraft/Issues#7440] opened 2017-02-24 19:33 UTC
> 
![2017-02-24_20 30 14](https://clou
![2017-02-24_20 30 20](https://cloud.githubusercontent.com/assets/26012414/23317807/3a536fa4-fad0-11e6-85ca-6d3473456626.png)
d.githubusercontent.com/assets/26012414/23317800/35381f74-fad0-11e6-8dc3-eb52fecb0b4f.png)
 
Like u can see here the texture for this bow is gone/bugged.
I just noticed so i reported immediately

**Comment by Pyromanical** [comment] 2017-02-24 19:40
Duplicate of #7017 
According to @ColinRioux on #7017, this issue will probably be fixed when Wynncraft updates past 1.8.9.

**Closed** 2017-02-24 19:45 UTC
