### ISSUE TITLE
Quest Item Spawn Glitch/Bug

### ISSUE THREAD

**Issue by Arrow25** [Wynncraft/Issues#4459] opened 2016-03-05 18:41 UTC
I'm trying to do Temple Of Legends quest but the Light Dust isn't spawning so I cant go any further In the quest and I want to be able to get xp from the trainers but I cant since I have no access to the temple because I cant complete the quest because the item wont spawn. Some major quest involve you getting items that spawn on the ground but if they don't spawn you cant get them and if you cant get them you cant do the quest and level up faster then just killing mobs all day that get you 100 or so xp when you need 1000's of xp to level up. I have been told it would be fixed In the next update but when will that be if its not soon can you fix it with out the next update because I don't want to wait weeks just to finish one quest.

**Comment by Odnod** [comment] 2016-03-05 19:04
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-05 20:11 UTC
