### ISSUE TITLE
Stuck in "You died yo" room

### ISSUE THREAD

**Issue by SmirrenIsMyName** [Wynncraft/Issues#7998] opened 2017-04-27 17:21 UTC
So when I took the boat from Llevigar to Selchar. His dialouge ended and then nothing happend. I tried /kill and it took me and my friend theMCslayer01 to this room where 2 other people already where in. in this room it tells you to do the command /warp ragni but theres a twist. the command doesnt work 👍 .
![2017-04-27_19 17 34](https://cloud.githubusercontent.com/assets/26552191/25495753/a9990a20-2b7e-11e7-8d1f-795122126e36.png)

**Comment by SmirrenIsMyName** [comment] 2017-04-27 17:23
doing /kill got us out of this room. but I would not like to end up there again

**Comment by PepinhoJp** [comment] 2017-04-27 17:55
This is a bug, the staff already know about it, it will probably be fixed today!

**Comment by ColinRioux** [comment] 2017-04-27 19:48
Duplicate of #7992

**Closed by ColinRioux** 2017-04-27 19:48 UTC
