### ISSUE TITLE
Compass stuck in bank!

### ISSUE THREAD

**Issue by Ligaligi** [Wynncraft/Issues#4928] opened 2016-05-01 09:38 UTC
https://cloud.githubusercontent.com/assets/15972250/11412859/5ceaaf30-939f-11e5-8ada-1eded8bb5ed1.png

This compass has been stuck in my bank since like 2 years ago and it really pisses me off because I can't make it look nice, plus it wastes space! plz help. D:

**Comment by Trixter313** [comment] 2016-05-01 14:06
Duplicate of #3147 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-05-01 14:06 UTC
