### ISSUE TITLE
Temple of the Legends

### ISSUE THREAD

**Issue by ItsYourPlay** [Wynncraft/Issues#4360] opened 2016-02-29 16:48 UTC
The light dust don't spawn/drop in the Light cave.

**Comment by ItsYourPlay** [comment] 2016-02-29 16:49
Can someon help me pls.I don't know what i must do.

**Comment by TheQuantumBro** [comment] 2016-02-29 17:43
It`s bug...Again!

**Comment by Moe-Ronickah** [comment] 2016-02-29 20:57
Duplicate of Quest Items Are Not Spawing #4236 .  Please refer all future comments to the original thread.

**Closed by Moe-Ronickah** 2016-02-29 20:57 UTC
