### ISSUE TITLE
I can't leave my Guild

### ISSUE THREAD

**Issue by YoshiiGirl16** [Wynncraft/Issues#7079] opened 2017-01-02 18:51 UTC
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by ColinRioux** [comment] 2017-01-02 20:43
Duplicate of #3665
Please click the #3665 and read what's written. You probably changed your ign while in the guild. There's a current bug that people can't leave.

**Closed by ColinRioux** 2017-01-02 20:43 UTC
