### ISSUE TITLE
Losing items since you have low SP and the texture pack is loading and then u die

### ISSUE THREAD

**Issue by CrimsonInfinity** [Wynncraft/Issues#5732] opened 2016-08-14 00:10 UTC
i lost all my items due to this and i would at least like my Olux's Prized bow back and i would like my Leggings that i got form doing an iron heart part 2 back also i would like my Anchorly i would like a scroll form each of the wynn cities and llevingar scrolls back also i would like my spectre helmet back that was in my inventory i would like a Geis chestplate back since i couldnt remenber the rare chestplante that i was wearing name and the final thing is that i would like my call of the void helmet back

**Comment by CrimsonInfinity** [comment] 2016-08-14 00:11
wait i have the spectre helmet in my bank

**Comment by CrimsonInfinity** [comment] 2016-08-14 00:13
oh if you dont belive me then i would atleast like to have my olux bow and armor back since i am only wearing my lv 30-45 set...

**Comment by ColinRioux** [comment] 2016-08-14 01:44
Wynncraft enforces a strict no refund policy. See (https://forums.wynncraft.com/threads/have-you-ever-lost-your-items-in-game-and-want-to-get-them-back.143196/). It's not that we don't believe you, this policy is put in place to maintain fairness across the player base. Although it seems counterintuitive (because the policy actually seems **unfair**), it actually keeps everyone at bay. If Wynncraft gave one person in particular back their items, then they'd have to give the rest of the player base back their items, resulting in a lot of lies and probably complaints. The administration just simply doesn't have time for that, especially if they're pushing out gameplay updates every few months. 

So believe me when I tell you, there is no refunds. I've lost my stuff before (like a few legendaries too), and you don't see me upset. 

Having low soul points is technically on you, as you should've waited it out in a town until you regained plenty of soul points.

**Comment by Trixter313** [comment] 2016-08-14 09:47
Duplicate of https://github.com/Wynncraft/Issues/issues/3565

**Closed by Trixter313** 2016-08-14 09:47 UTC
