### ISSUE TITLE
Unlocking new Enderchest slots = Loss of Items?

### ISSUE THREAD

**Issue by Vanquishir** [Wynncraft/Issues#5717] opened 2016-08-12 15:49 UTC
Hello, do I was playing on Wynncraft and I had a bunch of Jester items (3 Bracelets and 6 necklaces), I was farming along having a jolly ol' time. Until I went to my enderchest and I had farmed enough to get around 46EB. So I thought well, I had one row I haven't unlocked in my enderchest, so I do it; As I do it watch 1 bracelet and 4 Necklaces disappear. I didn't think of it I thought "Oh well it must of bugged out!" So I 1) Relog, 2) Open and close my Enderchest, 3) Goto the Forums to Report this. Since loosing around 6 Jester Items that I worked for? Who took them? The Server did. I don't know how it happened, I mean I did buy 3 of them off some people, maybe more. But that doesn't give the server admins or any right to take my items? I don't remember the exact specs on the bracelets, but I know they were pretty good. 

Thanks for taking my items that I worked for Wynncraft!

**Comment by Trixter313** [comment] 2016-08-12 15:53
Duplicate of https://github.com/Wynncraft/Issues/issues/4091

This happens because the bank upgrade gets rid of the glass panes in the bank and many accessories are retextured glass panes so it accidentally gets rid of those as well.

Wynncraft has a strict no refunds policy so we can't do anything about the items but we are working on fixing the issue so it doesn't happen any more.

**Closed by Trixter313** 2016-08-12 15:54 UTC
