### ISSUE TITLE
Falling into the void when joining a server

### ISSUE THREAD

**Issue by KingOfTheNazgul** [Wynncraft/Issues#6793] opened 2016-11-27 12:45 UTC
Hello, so I have a little bug that has started with the new patch 1.14.2 and it is about when I join a server, i don't have the class selection, i just spawn in a stone box then fall to the void, i have tried every solution, switched versions to 1.8-1.8.9-1.9-.1.10-1.10.2-1.11, even deleted my resource pack folder and let wynn download a new one, i rly miss playing wynncraft it's one of my main servers and i really want this bug to get fixed asap, pls inform me with a date of the fix, IGN: KingOfTheNazgul
Thanks :)

**Comment by ColinRioux** [comment] 2016-11-27 16:57
Duplicate of #6773

**Closed** 2016-11-28 13:35 UTC
