### ISSUE TITLE
I cant Connect

### ISSUE THREAD

**Issue by Clyenn** [Wynncraft/Issues#7702] opened 2017-04-08 10:21 UTC
I cant connect to the server i press on my Archer class and than:
![2017-04-08_12 18 15](https://cloud.githubusercontent.com/assets/23523429/24828066/f24c2334-1c55-11e7-9cdd-aab99fad60f7.png)

Ingame Name : DoomsReturns

**Comment by RLLL93** [comment] 2017-04-08 11:12
Same problem

**Comment by DerClassic** [comment] 2017-04-08 11:20
Ye me to... But only with my Mage Class

**Comment by RLLL93** [comment] 2017-04-08 11:25
I have it with my assassin class only too

**Comment by RLLL93** [comment] 2017-04-08 11:26
And I think, that your Mage class has the biggest lvl of them all, yes?

**Comment by RLLL93** [comment] 2017-04-08 11:29
and where were you when it happened?

**Comment by LordHelmchen98** [comment] 2017-04-10 00:50
Duplicate of #7680 please look there for any future information.

**Closed by LordHelmchen98** 2017-04-10 00:50 UTC
