### ISSUE TITLE
Class select errors (unsolved problem for years)

### ISSUE THREAD

**Issue by fabikong02** [Wynncraft/Issues#3182] opened 2015-12-26 14:37 UTC
Dear Wynncraft-Team,
I have an BIG problem on the Wynncraft MMORPG srever.
If i select a class, i getting an error.
The chat says : 
"There has been an error... Try again.
Select a class! Each class saved
individually across all servers, you can comeback at any time with /class and select
another class!"

I had try it again (more than 5 times) but i`m getting anytime an error.
No matter which class I select, I always get the same error.

Also, I've ever reported this error, but did not get the reaction to what I find very badly by the server team.
Now another year passed and I still have the same error.
Can you fix the error or unable to eliminate these errors for her?

And don`t close this Issue without fix the problem (if the server team do this i spam this everyday in the issues with different accounts, because i have this problem for many years!)

My Minecraft Ingamename is: Crystalkong

I hope the serverteam fix this error quickly, because I want to play on the Wynncraft-server

-Crystalkong

**Comment by Verret001** [comment] 2015-12-26 17:22
Duplicate of https://github.com/Wynncraft/Issues/issues/3139
But good statement, you don't have to close this, hopefully it will get someone's attention

**Comment by Trixter313** [comment] 2015-12-29 20:56
Duplicate of https://github.com/Wynncraft/Issues/issues/3139 I believe.

Please direct any further comments to the original issue. Thanks!

**Closed by Trixter313** 2015-12-29 20:56 UTC
Labels: duplicate
