### ISSUE TITLE
My Wand Dont have Permission?

### ISSUE THREAD

**Issue by WynnMaster69** [Wynncraft/Issues#4618] opened 2016-03-21 15:02 UTC
Okey so i got the relic wand yesterday and it worked prefect but a few hours later this happend.
https://gyazo.com/0546e3f45cd23590bf2a0739736a3ba5
so can someone please help me ? i dont know whats going on

**Comment by Odnod** [comment] 2016-03-21 16:42
This is because weapons are textured over blocks. The game thinks that you are trying to place a block and restricts your permission.

**Comment by Trixter313** [comment] 2016-03-21 21:20
Duplicate of https://github.com/Wynncraft/Issues/issues/3902

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-21 21:20 UTC
