### ISSUE TITLE
Gear Glitch

### ISSUE THREAD

**Issue by MattHei1** [Wynncraft/Issues#2422] opened 2015-10-21 04:00 UTC
When you log in in autojoin there is a time limit of 45 secondes when you can combine two items in the crafting slot (f.ex two iron boots or two bows) that crafts that item that you put in the crafting slot. You can use/wear these items in lvl 1. This glitch also works with other things like diamond armor, gold armor, leather armor, chain armor, sticks, spears/shovels and shears. Please fix this.

**Comment by ThunderRemix** [comment] 2015-10-21 04:55
Duplicate of #683

**Closed** 2015-12-25 20:39 UTC
