### ISSUE TITLE
There has been an error... Try again.

### ISSUE THREAD

**Issue by ExtremeLemonMLG** [Wynncraft/Issues#3896] opened 2016-01-28 04:32 UTC
Hello! I just wanted to discuss how whenever I go into any world of wynncraft to select my class, it will prevent me from choosing on and say "There had been an error... Try again. I have indeed tried multiple times and even logged into the multiple server ips, but it will still not me play. I heard this server is really fun and I would love to give it a try. Thanks very much for just reading this message 
-ExtremeLemonMLG (It's my gamer tag as well btw)
Update:I logged onto my friends account on the same computer i'm using, and It let him pick a class...

**Comment by Trixter313** [comment] 2016-01-28 04:37
Duplicate of https://github.com/Wynncraft/Issues/issues/3250

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-28 04:37 UTC
