### ISSUE TITLE
Missing texture for a weapon

### ISSUE THREAD

**Issue by Samattack2000** [Wynncraft/Issues#6123] opened 2016-09-12 01:08 UTC
When I identifyed a weapon, I got it, but the texture was seemingly missing: The weapon itself is Hunter and is a spear/shovel type of weapon. You can see with this screenshot:

![2016-09-11_21 04 17](https://cloud.githubusercontent.com/assets/22138639/18422025/7ca29d48-7863-11e6-807b-4aa1f1f4d705.png)

Yes I know I am playing with a minimap, but who cares? It's allowed and doesn't give me any advantage! We are talking about that slab. It is annoying to have a block as a texture for a weapon.

**Comment by Celsonic** [comment] 2016-09-12 23:06
Huh. Must be something wrong with the item tag.

**Comment by Trixter313** [comment] 2016-09-13 23:41
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

**Closed by Trixter313** 2016-09-13 23:41 UTC
