### ISSUE TITLE
cant identify some old bob's mystic items

### ISSUE THREAD

**Issue by IngYaa** [Wynncraft/Issues#6324] opened 2016-10-03 17:37 UTC
i quit wynn several month ago and many things change include item identifying things
i have 11 bob's mystic weapons(all from my friend's request) that haven't identified yet and now i cant identifying myself :/
the other items work but not these one 
oh also these all has old powder effect like sharpness II enchantment
plz fix this please

![2016-10-04_02 28 33](https://cloud.githubusercontent.com/assets/22598297/19047108/6877618a-89db-11e6-93b1-e4af1b9449e7.png)

**Comment by Trixter313** [comment] 2016-10-04 01:13
Duplicate of https://github.com/Wynncraft/Issues/issues/6171

**Closed by Trixter313** 2016-10-04 01:13 UTC
