### ISSUE TITLE
Quest: Murder Mystery

### ISSUE THREAD

**Issue by 1Entropy** [Wynncraft/Issues#3737] opened 2016-01-16 22:12 UTC
I have written up a bug report on this before but it has not resolved. When I was doing the quest Murder Mystery I could not go into the building with the entrance to the sewers in it. Whenever I got close it teleported me away and said "The stench of whiskey drives you away". I have tried re-talking to everyone in the quest and retracing my steps, but I cannot resolve the issue to enter the building. I think the problem is that my quest book did not update after talking to Rohem and I would be grateful if you could reset or fix this quest for me. I have already tried talking to Rohem again and that did not work. If you need my IGN it is: 0Entropy. thanks for reading!

**Comment by Dar-krusos** [comment] 2016-01-16 23:27
Alright, I'll get on to see if I can help.

**Comment by Troll2828** [comment] 2016-01-17 01:41
At one point, Rohem tells you that the member's have bat symbols on their houses. He also says to go look for a bat symbol at the victim's house. When you find this symbol next to the victims house, you need to press a button that activates a piston and reveals the number twelve. Maybe when you did this your quest book didn't update. Try redoing it. Otherwise, I don't have any solutions to your problem.

**Comment by Trixter313** [comment] 2016-01-17 20:05
Duplicate of https://github.com/Wynncraft/Issues/issues/3478

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-17 20:05 UTC
