### ISSUE TITLE
bug in my armor 

### ISSUE THREAD

**Issue by benyg2000** [Wynncraft/Issues#4324] opened 2016-02-28 01:02 UTC
I have the chest plate called "Dragon skin" but when i joined the game the chest plate did not work. Buy what i mean is that if did not give me the health and the tag on it is really long and the color purple. what can i do to fix it

**Comment by Trixter313** [comment] 2016-02-28 18:53
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-28 18:53 UTC
