### ISSUE TITLE
I cant connect

### ISSUE THREAD

**Issue by EpicOverKill567** [Wynncraft/Issues#2100] opened 2015-07-14 02:50 UTC
When I try to connect to Wynncraft it tell me I cant connect, it says
"Unable to find a server to connect to, Please report"
What do I do?

**Comment by Skwirch** [comment] 2015-07-14 02:53
The same thing is happening to me. I wouldn't worry because it is happening to a lot of people. At some point it will come to their attention and it should be fixed.

**Comment by tacticalsk8er** [comment] 2015-07-14 02:59
Having the same problem as well.

**Comment by Trixter313** [comment] 2015-07-14 03:31
Duplicate of https://github.com/Wynncraft/Issues/issues/2099
We recommend closing the duplicate and following the original, to keep the bug tracker de cluttered and so you can stay up to date on the status of the issue. Thanks!

**Closed** 2015-07-14 09:54 UTC
