### ISSUE TITLE
CAN'T LEAVE GUILD

### ISSUE THREAD

**Issue by Mystogen** [Wynncraft/Issues#6465] opened 2016-10-24 22:21 UTC
I've been in a guild for some time now, and no one in my guild is ever on. I have been wishing that this glitch would be fixed, but it seems it has not been fixed yet. The message comes up and everything, but when I type in yes, I lose 3 soul points, but i'm still in the guild. Please help me!

**Comment by thecoolkogut4** [comment] 2016-10-24 23:05
guilds are broken there is nothing you can do about it. your stuck in till they fix guilds

**Comment by Mystogen** [comment] 2016-10-24 23:09
Do u know when it will be fixed?

**Comment by thecoolkogut4** [comment] 2016-10-24 23:10
probably when the refractor comes out so 6months? maybe?

**Comment by Mystogen** [comment] 2016-10-24 23:11
Ooof

**Comment by Mystogen** [comment] 2016-10-24 23:11
ty

**Comment by Trixter313** [comment] 2016-10-26 00:33
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

**Closed by Trixter313** 2016-10-26 00:33 UTC
