### ISSUE TITLE
Forum Command is Broken (Failure to receive forum ranking)

### ISSUE THREAD

**Issue by ShowingGenius** [Wynncraft/Issues#3444] opened 2016-01-01 21:41 UTC
I bought a rank, and I tried to do /forum (username) and it didn't work. That simple.

**Comment by Trixter313** [comment] 2016-01-01 23:21
Duplicate of https://github.com/Wynncraft/Issues/issues/3268

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-01 23:21 UTC
