### ISSUE TITLE
Unable to battle territories

### ISSUE THREAD

**Issue by dragonfly19981** [Wynncraft/Issues#2237] opened 2015-08-22 13:35 UTC
I am captain in the End Of Nothing guild, whenever I try to battle a place it says that this terrain is already in battle, I've tried multiple locations and it all said the same.

**Comment by Trixter313** [comment] 2015-08-22 17:37
Duplicate of https://github.com/Wynncraft/Issues/issues/2227

We recommend closing the duplicate and following the original to stay up to date on the status of the issue. Thanks!

**Closed** 2015-08-23 00:55 UTC
