### ISSUE TITLE
Seaskipper passes to nemract not working

### ISSUE THREAD

**Issue by Peeves5200** [Wynncraft/Issues#6671] opened 2016-11-12 19:19 UTC
Whenever i use a pass to go to nemract (tried from selchar and mage island more than once) i get stuck on the boat and the dialogue doesnt continue so im stuck on the boat permanently. Also using /kill then spawns me at the beginning of the game which makes it more annoying

**Comment by ColinRioux** [comment] 2016-11-12 19:21
Hi can you please provide screenshots or a video (so I can attempt to reproduce the issue)?

**Comment by Moe-Ronickah** [comment] 2016-11-17 02:49
Duplicate of #6389

**Closed by Moe-Ronickah** 2016-11-17 02:49 UTC
Labels: Duplicate, Game Mechanics
