### ISSUE TITLE
boat merchants

### ISSUE THREAD

**Issue by TGNebulA** [Wynncraft/Issues#3315] opened 2015-12-29 10:21 UTC
most places in wynn seem to have no boat merchant which is incorrect on the online map. For example Zhight island which even has a house dedicated to the merchant, however he wasn't there. Even when I tried to go on 3 different servers he would not appear, meaning i had to swim back to Nemract or Llevigar to get a boat.

**Comment by jj417417** [comment] 2015-12-29 16:20
I also noticed the issue with the boat merchants missing. I was doing the Zhight island quest and the boat merchant wasn't there. It's annoying to have to swim because the boat merchants are missing. Hope this gets fixed soon!

**Comment by Trixter313** [comment] 2015-12-29 21:45
Duplicate of https://github.com/Wynncraft/Issues/issues/3243

Please direct any further comments here. Thanks!

**Closed by Trixter313** 2015-12-29 21:45 UTC
Labels: duplicate
