### ISSUE TITLE
Ice Nation Viking Drop Stuff

### ISSUE THREAD

**Issue by DirtyDoge** [Wynncraft/Issues#6071] opened 2016-09-07 02:02 UTC
![2016-09-06_20 57 37](https://cloud.githubusercontent.com/assets/21346185/18297298/1a12730c-7475-11e6-9148-e9aa63d53172.png)
You can't pick it up tho, so that's good.

**Comment by setery10** [comment] 2016-09-07 12:07
Lol

**Comment by Trixter313** [comment] 2016-09-08 00:48
Duplicate of https://github.com/Wynncraft/Issues/issues/5534

Same thing, different area. Apparently it's intended.

**Closed by Trixter313** 2016-09-08 00:48 UTC
