### ISSUE TITLE
Items instantly despawning

### ISSUE THREAD

**Issue by groo23** [Wynncraft/Issues#4157] opened 2016-02-16 20:29 UTC
My brother was playing and he was in the Pigman's Ravine. He was on one soul point and died, went back to pick up his items and they were gone. I know that there is a time delay before other players can pick up the items. But he went back to the spot he died and there were no items. Our friend witnessed everything and confirmed that the second he died the items dropped and instantly were gone. I just wanted to know if there were any way for him to get his items back by loading his previous player save or something. My friends and I just thought it was unfair that he is the only case we've heard of that has done this.

Brothers in game name: brucyboss

**Comment by Odnod** [comment] 2016-02-16 21:10
it has to do with the chunks unloading. Wynncraft has a no-refund policy, however seeing as your brother died in the pigman ravine he must have been very low leveled which should make getting items back not that huge a hassle. In the future, so not leave a city with 2 or less soul points.

**Comment by Trixter313** [comment] 2016-02-18 11:59
Duplicate of https://github.com/Wynncraft/Issues/issues/3954

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-18 11:59 UTC
