### ISSUE TITLE
Legendary Helmet Lost All Its Effects

### ISSUE THREAD

**Issue by OverFlareDX** [Wynncraft/Issues#3646] opened 2016-01-11 00:23 UTC
I had a legendary helmet that I've been using for a week or so. Then yesterday when I logged back in yesterday, instead of having a name, lore and bonuses, when I mouse over it, it only shows a long line of purple text. The text goes all the way across the screen. It basically does nothing now. 
![wynncraft helm bug](https://cloud.githubusercontent.com/assets/16639489/12225071/858d5b2e-b83c-11e5-8b11-6c339cb42445.png)

**Comment by Trixter313** [comment] 2016-01-11 00:35
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-11 00:35 UTC
