### ISSUE TITLE
Stats page never loads

### ISSUE THREAD

**Issue by Moderocky** [Wynncraft/Issues#4089] opened 2016-02-12 06:51 UTC
The stats page on the site never loads. :(

**Comment by Odnod** [comment] 2016-02-12 06:54
on the page it is broken, put your username at the end of this: https://api.wynncraft.com/public_api.php?action=playerStats&command=

**Comment by Trixter313** [comment] 2016-02-12 23:31
Duplicate of https://github.com/Wynncraft/Issues/issues/3928

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-12 23:31 UTC
