### ISSUE TITLE
Right-Clicking w/ an item prompts the msg: You do not have permission...

### ISSUE THREAD

**Issue by tolin99** [Wynncraft/Issues#3951] opened 2016-02-01 12:13 UTC
When I right-click with the relic wand (a retextured block) on the ground, it give me this message: You don't have permission for this area.

I figure this is simply because of the wand really being a block. I tried with other weapons, and it doesn't seem to happen, and regular blocks don't do it as well (such as ice or emerald blocks).

https://cloud.githubusercontent.com/assets/8350700/12717052/2719b2ae-c8b3-11e5-8476-6dcd37473aaa.png

**Comment by DarkDemonDragon** [comment] 2016-02-01 13:31
Duplicate of #3902 Please close this and follow the main one.

**Closed** 2016-02-02 11:57 UTC
