### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by RORO20002** [Wynncraft/Issues#4828] opened 2016-04-15 10:22 UTC
I have a big bug on my skill point due to update me they have not been reset then I can use my bow

**Comment by DarkDemonDragon** [comment] 2016-04-15 12:04
Is English a second language or were you rushing this? Either way could you please provide more details ?

**Comment by Trixter313** [comment] 2016-04-17 13:19
Duplicate of #4844

**Closed by Trixter313** 2016-04-17 13:19 UTC
