### ISSUE TITLE
My assassin class is buggy

### ISSUE THREAD

**Issue by Lunarhelix** [Wynncraft/Issues#3252] opened 2015-12-27 23:26 UTC
As you can see on the website about the classes about assassin skill, but
my assassin lvl: 50

1) My spin attack makes the mobs fly all over while my multihit is stunning them, my skill affects were swaped.
2) My smoke bomb isn't doing any damage at all, only particles.

This is really bothering me cause all of these only happened when the Gavel update came out. Please help, it's really hard to grind since my skills are practically limiting everything I do and killing me, i can't even defend my self through spin attack. ;-; very sad.

**Comment by Lunarhelix** [comment] 2015-12-27 23:27
My ign name is Lunarhelix
 class assassin

**Comment by RedMorcus** [comment] 2015-12-28 03:28
These are all known bugs, presumably the staff will fix them when they get back from holidays. The spin attack and multihit accidentally had their knockback values switched, while smoke bomb is the result of trying to use 1.7 mechanics in 1.8.

**Comment by SmileyAlec** [comment] 2015-12-28 04:00
Thanks for clearing that up it makes me feel alot better ^,^
Op 28 dec. 2015 04:28 schreef "RedMorcus" <notifications@github.com>:

**Comment by Verret001** [comment] 2015-12-28 21:55
duplicate of https://github.com/Wynncraft/Issues/issues/3140
Please follow up on that issue.
Use the **[Directory](https://github.com/Wynncraft/Issues/issues/3197)** to make sure your not making duplicates

**Closed** 2015-12-29 21:48 UTC
