### ISSUE TITLE
Mesarock Arch item skin bugged.

### ISSUE THREAD

**Issue by kkvkyriakos** [Wynncraft/Issues#8402] opened 2017-06-18 17:55 UTC
My legendary weapon the "Mesarock Arch" skin is bugged. When i log it i can only see a stone block. Please help me or fix this bug :)

Thanks in advance!

**Comment by ittnoraA** [comment] 2017-06-18 22:54
Duplicate of #4548 and #8115 
Here are the quotes about the bug:
`Weapons are retextured blocks but sometimes the textures are missing. The weapons still work though.
However this is known and will hopefully be fixed soon.`
`Thanks for the report, and it's passed along to Jumla, just in case he hasn't seen these, already.`

**Closed** 2017-06-20 01:30 UTC
Labels: Duplicate
