### ISSUE TITLE
Horse Glitch

### ISSUE THREAD

**Issue by AgentPanda** [Wynncraft/Issues#5259] opened 2016-06-18 21:29 UTC
Hey guys,
so today I was at the Mesa and I was riding my horse and then I died by some mobs. Somehow my horse saddle then disappeared out of my inventory and I didn't drop it.
IGN: AgentPanda_ (Yeah, I know its not required)

**Comment by Moe-Ronickah** [comment] 2016-06-19 02:12
I'm sorry, but losing items randomly happens when players die.  The admins are aware of it, and are working on it.

duplicate of #3153 .  Please follow and comment on this issue there.

**Closed by Moe-Ronickah** 2016-06-19 02:12 UTC
Labels: Duplicate

**Comment by AgentPanda** [comment] 2016-06-19 02:17
Is there any way to get my horse back?

**Comment by Trixter313** [comment] 2016-06-19 02:31
Unfortunately Wynncraft has a strict no refunds policy so we can't give you a horse back but we are working on fixing it so it doesn't happen again!
