### ISSUE TITLE
When I try to log on to one of my profiles it says that I should try again but it doesn't work

### ISSUE THREAD

**Issue by kikou513** [Wynncraft/Issues#6903] opened 2016-12-15 16:08 UTC
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by LordHelmchen98** [comment] 2016-12-15 19:19
Duplicate of #5418 
Read Moe-Ronickahs long post on the original thread for more information.

**Closed** 2016-12-21 12:32 UTC
Labels: Duplicate
