### ISSUE TITLE
can't download resource pack

### ISSUE THREAD

**Issue by LordTomJ** [Wynncraft/Issues#3288] opened 2015-12-28 18:37 UTC

**Comment by Verret001** [comment] 2015-12-28 19:13
duplicate of #3150 #3183 #3150
Please close topic

**Comment by Tama63** [comment] 2015-12-28 19:19
@Verret001 you can do this now :)

**Closed by Tama63** 2015-12-28 19:19 UTC

**Comment by Verret001** [comment] 2015-12-28 21:05
@Tama63 I know, I like to tell people to then if they don't close it after a few hours Ill close it.
