### ISSUE TITLE
Guild Gitch

### ISSUE THREAD

**Issue by Santhush** [Wynncraft/Issues#7377] opened 2017-02-14 23:03 UTC
I Have Changed My Name While In A Guild And I Am Currently Unable to leave it because of this, NO One Is Active In The Guild So Can U Force LEave Me Or Disband the guild? Please Help

**Comment by Pyromanical** [comment] 2017-02-14 23:08
No, sadly nothing can be done.  Guilds are completely broken currently, and until the code rework, you are stuck.  I have heard that changing your name back to what it was when you joined the guild, and then leaving can work, but it also could make it worse.  If you want to try that you can, but other then that, you are stuck.

**Comment by ColinRioux** [comment] 2017-02-15 01:15
This is a duplicate of #3665, and please search before creating an issue. Thanks!

**Closed by ColinRioux** 2017-02-15 01:15 UTC
