### ISSUE TITLE
connection problems

### ISSUE THREAD

**Issue by lecq4lifez** [Wynncraft/Issues#2017] opened 2015-06-20 20:50 UTC
whenever i try to join the server it says unable to find a server to connect to wht do i do

**Comment by Trixter313** [comment] 2015-06-20 21:03
Duplicate of https://github.com/Wynncraft/Issues/issues/2016

**Comment by Trixter313** [comment] 2015-06-21 03:27
The issue should be resolved now.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Closed** 2015-07-06 03:37 UTC
Labels: duplicate
