### ISSUE TITLE
Horse doesn't spawn

### ISSUE THREAD

**Issue by Krislann** [Wynncraft/Issues#4830] opened 2016-04-15 13:27 UTC
I started playing around 3 years ago, and got one of the horses at that time, im not going to go into detail, but i stopped playing for about a year. Since im an archer i dont use my horse, and approx 1.5 years ago my horse stopped spawning, i thought it was just a normal bug, and that it would work the next time i logged on, but that didnt fix it! I've recently tried a new thing "horse breeding" And managed to get a black horse (took me just 6 liquids -.-) but i can't get up on it. I atleast want to try it, but it still doesnt spawn! I am a VIP, but enabling and disabling my creeper pet doesn't have any effect at all! Please help me if you know how, i would really appreciate it! <3

**Comment by Odnod** [comment] 2016-04-15 19:20
Are you in Minecraft 1.9? Because horses are known to not work on this server in 1.9.

**Comment by Krislann** [comment] 2016-04-16 22:35
I have tried both 1.9 and 1.9.2

**Comment by Trixter313** [comment] 2016-04-16 23:02
Yes, any version of 1.9 is what Odnod was referring to.

We suggest trying 1.8.9 until the issue is fixed with 1.9. Let us know if this fixes it, thanks!

**Comment by Krislann** [comment] 2016-04-16 23:09
Hmm, switching to 1.8.9 actually fixed the problem, thank you guys! <3

**Closed** 2016-04-16 23:09 UTC
