### ISSUE TITLE
Wynncraft Excavation Site B Glitch

### ISSUE THREAD

**Issue by obliviaxel** [Wynncraft/Issues#4458] opened 2016-03-05 18:30 UTC
I was on wynncraft doing the wynncraft excavation site b quest when it glitched out. It said in the quest book to find the purple crystal shard, and when I went into the crystal room, there were no crystals. I went onto the coal blocks and it updated my quest and teleported me. It said to talk to Excavator Lykron, and when I talked to him, he didn't start a dialogue. Can someone please help me?

**Comment by Odnod** [comment] 2016-03-05 19:04
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-05 20:11 UTC
