### ISSUE TITLE
Priest's Underpants Issue

### ISSUE THREAD

**Issue by BarachielPug** [Wynncraft/Issues#3793] opened 2016-01-20 20:39 UTC
https://gyazo.com/2c4eb32500450a565704bc69adf4a0f1

At some point during the new armor textures my Priest's Underpants were glitched.

**Comment by Trixter313** [comment] 2016-01-21 11:45
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-21 11:45 UTC
