### ISSUE TITLE
I'm Stuck On Stage 2 In A Marauder's Dues

### ISSUE THREAD

**Issue by Kettlekorn** [Wynncraft/Issues#5847] opened 2016-08-29 01:19 UTC
*I already posted this, but the replies for the last post weren't helpful, and didn't fix my issue.

I'm at the beginning of stage 2 of the quest A Marauder's Dues where you have to go confront the mage on a hill. When I got to that part I climbed the mountain where the mage's tower was and tried to interact with the mage but didn't progress. Then I looked at a youtube video quest guide for the quest and walked through the path, and still didn't get any dialogue. So I looked around on the forums and found someone who had the same problem. The problem was caused from climbing the mountain directly to the tower which was "cheating." But the problem was solved for him when he left and rejoined the server. I tried that, but it's not working.

***I DID THE QUEST GUIDE VIDEO CORRECTLY STEP BY STEP, REJOINED AND SWITCHED SERVERS, AND WENT THE RIGHT PATH FOR THE DIALOGUE***

**Comment by Trixter313** [comment] 2016-08-29 01:22
Duplicate of https://github.com/Wynncraft/Issues/issues/5696

Please don't make duplicate issues, you'll receive the same responses as before. Your previous issue is still open and being worked on.

**Closed by Trixter313** 2016-08-29 01:22 UTC
