### ISSUE TITLE
Texture Pack Issue

### ISSUE THREAD

**Issue by FilezPlays** [Wynncraft/Issues#4703] opened 2016-03-30 02:48 UTC
A screenshot as myself (Mage, lvl 41) with the un-textured bow

http://i.imgur.com/dL12Ans.png

**Comment by Trixter313** [comment] 2016-03-30 03:32
Duplicate of #4548 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-30 03:32 UTC
