### ISSUE TITLE
Morph Set Skill Point Bug

### ISSUE THREAD

**Issue by m62605486** [Wynncraft/Issues#7396] opened 2017-02-18 19:04 UTC
https://forums.wynncraft.com/threads/morph-set-skill-point-bug.170023/
see orginal post

I just found out the morph set bonus is not adding sp bonus into your real status

20161217213622.png this is my morph set bonus it's add 26+20+23+23+24=116sp

I m lv 100= 198sp
so my total sp should be 198+116+314sp

but look at this  20161217213644.png  20161217213658.png 

my real sp is 48+98+49+49+50= 294sp

thats missing 20 sp which is the morph set sp bonus
20161217214245.png

**Comment by Pyromanical** [comment] 2017-02-18 19:27
Duplicate of #6283

**Closed** 2017-02-19 03:30 UTC
