### ISSUE TITLE
"Enter the Dojo" Sugar Bug/CMB not working?

### ISSUE THREAD

**Issue by Lockilocke1** [Wynncraft/Issues#7134] opened 2017-01-08 17:18 UTC
I know this Bug is already on the forums, but i just wanted to report it against because i need the sugar, in the Quest "Enter the Dojo", for the green tea you have to brew as soon as possible

**Comment by Lockilocke1** [comment] 2017-01-08 17:39
Duplicated #7130

**Comment by LordHelmchen98** [comment] 2017-01-08 18:25
Actually it's a duplicate of #7121 so yeah look there for more information.

**Closed** 2017-01-09 20:41 UTC
