### ISSUE TITLE
Guild Messages

### ISSUE THREAD

**Issue by Gundalfigus** [Wynncraft/Issues#4811] opened 2016-04-12 17:24 UTC
I just changed my Minecraft Username. Now i see all Guild Messages two times.
I hope this will get fixed soon

http://www.directupload.net/file/d/4322/tox6gmx6_png.htm

~Gundalfigus

**Comment by Yoavronen** [comment] 2016-04-14 05:11
I know that Tama is working on a fix for this. 
But there is another way I witnessed that fixes it, DO NOTE I DON'T KNOW IF IT WORKS 100%.
you can try to do "/guild leave", I still didn't see someone who did it and it hasn't worked. 
If you do try it please report the results back.

**Comment by Gundalfigus** [comment] 2016-04-15 13:03
Dont want to.. im the leader of the Guild

**Comment by thecoolkogut4** [comment] 2016-04-23 23:09
/guild leave will make you lose 2(maybe 3) soul points when you leave the guild. every time someone in my guild that has done /guild leave (when they are in the guild 2 times) lose 2 soul points and they stay in the guild. the only thing that I think you could do is just wait it out, hope that there is a fix soon.

**Comment by YunoFGasai** [comment] 2016-07-12 17:38
isn't this a duplicate of #3665 ?

**Comment by Moe-Ronickah** [comment] 2016-07-13 08:41
Yes, it is.  Now that we know that ghosting is almost certain to happen, we can just close this one out.

**Closed** 2016-07-13 08:41 UTC
Labels: Duplicate, Guilds
