### ISSUE TITLE
Loot bonus glitch?

### ISSUE THREAD

**Issue by stevemacie321556** [Wynncraft/Issues#5488] opened 2016-07-15 05:27 UTC
So I was playing on my hunter earlier today and I had to do Temple of Legends.  When I went to go grind for 64 blaze powder I noticed I wasn't getting many drops. I looked at all my armor and didn't see any negative loot bonus debuffs but when I looked at my character statistics i noticed i had -7% loot bonus.  I found it weird because everything I had only gave me positive loot bonus and no negatives. My equipment consists of Marrow(Helmet), Chaos(Chest plate), Greaves of Honor(leggings), Bad Wolf(Boots), Amethyst ring, decoder ring(+4%loot bonus),  Bejeweled bracelet(+2%loot bonus), Jester's Necklace(+12% loot bonus), and Olux's Prized Bow(+15% loot bonus).  I don't know if this is a glitch or I just did'nt know or notice anything about it.  But i found it especially odd when i took off the jester's bracelet and it changed to +6% loot bonus. Is there something I'm missing or is this a bug?

Thank you for reading'
stevemacie

**Comment by Moe-Ronickah** [comment] 2016-07-15 05:51
The Jester set needs to have IDs that are greater than their negatives in order for them to have a positive effect.  See the following issue.
Duplicate of #5359

**Closed** 2016-07-15 05:52 UTC
Labels: Duplicate
