### ISSUE TITLE
Did not give me enough emeralds for A Headless Hunt Quest Finish

### ISSUE THREAD

**Issue by IncBear101** [Wynncraft/Issues#5500] opened 2016-07-16 17:29 UTC
I am not lying, and I know there is a no refund policy, but. BUT.
I was supposed to get over 1 LE for the quest A Headless HUnt, but, ii only got forty three EB.
![2016-07-16_11 25 59](https://cloud.githubusercontent.com/assets/20328015/16896139/951741c8-4b48-11e6-85c4-8f9c615805f6.png)
![2016-07-16_11 26 02](https://cloud.githubusercontent.com/assets/20328015/16896140/9701664e-4b48-11e6-9749-11f2bd37fc31.png)

**Comment by IncBear101** [comment] 2016-07-16 17:30
THis was just now

**Comment by sammyvsparks** [comment] 2016-07-17 06:18
@IncBear101 The no refund policy still stands as it would be impossible to tell if you dropped them behind where you took the screen shot and etc.

**Comment by Moe-Ronickah** [comment] 2016-07-17 11:39
Duplicate of #3246

**Closed by Moe-Ronickah** 2016-07-17 11:39 UTC
Labels: Duplicate
