### ISSUE TITLE
Parts of Inventory Lost

### ISSUE THREAD

**Issue by sammyvsparks** [Wynncraft/Issues#5348] opened 2016-06-29 22:26 UTC
I lost 4 Pieces of armor from my inventory last night in Tower of Ascension, My Helmet, Leggings, Boots (Which we're returned with /fixquests, thankfully) and my Wolf Paw(Bracelet).

I had the required stats to wear each item and randomly looked up to die with 800 hp after the teleport to a city, I didnt drop all my items from reaching 0 Soul Points (because i still had 4 after i died) and i have no idea what happened. I would really like a answer to what happened or a small rollback on my account even to get the stuff back (I honestly dont care if i lose a little experience or a level).

EDIT: Username is xCykrix, forgot I dont use sammyvsparks anymore

**Comment by YunoFGasai** [comment] 2016-06-30 12:06
was your inventory full when you lost the items?

**Comment by sammyvsparks** [comment] 2016-07-01 00:38
Yes, and it just happened again. It randomly forces deletion of the items when im fully able to wear and use them. Im literally almost done with this crap. It happens EVERY time i farm. Just lost my XP armor now.

**Comment by YunoFGasai** [comment] 2016-07-01 06:48
Keep 4 inventory slots open
(You actually need the same number of inventory slots as your equipment that has a skill requirement)

**Comment by Moe-Ronickah** [comment] 2016-07-01 08:43
duplicate of #3153

**Closed** 2016-07-01 08:43 UTC
Labels: Duplicate
