### ISSUE TITLE
I can't leave my guild

### ISSUE THREAD

**Issue by RedHocus** [Wynncraft/Issues#7066] opened 2017-01-02 02:43 UTC
Whenever I try to leave my old guild, I lose my soul points but am still part of the guild. Please Fix

**Comment by ColinRioux** [comment] 2017-01-02 04:28
Hi,

In the future, I suggest using the search tab at the top of the issues page to search for similar issues relating to yours. It seems, that you've changed you minecraft username while in the guild. Duplicate of #3665

If this is true, well, right now you can't leave the guild. This has been going on for about a year now, and the development team are working towards new content and updating the base code instead of the code that actually involves guilds. 

The only method that **could possibly work**, not 100% sure, would be changing your username back to the username you had when you first joined the guild. Then try to leave. But no guarantee. 

In terms of being fixed, it won't be probably, until one of the developers has time.

**Closed by ColinRioux** 2017-01-02 04:28 UTC
