### ISSUE TITLE
My le Pelier can't be identified

### ISSUE THREAD

**Issue by GGMARVEL** [Wynncraft/Issues#2637] opened 2015-12-15 18:15 UTC
I got a pelier  during killing monsters. But when I tried to identify, it says it is common items such as Jungle wood bow.

**Comment by TrashcanMan** [comment] 2015-12-16 04:16
Duplicate of #1312, many items with accented characters do not identify properly. This should be fixed soon.

**Comment by Trixter313** [comment] 2015-12-22 16:45
As TrashcanMan said, this is a duplicate. We recommend closing duplicates and following the original to stay updated on the status of the issue. Thanks!

**Closed** 2015-12-25 20:35 UTC
