### ISSUE TITLE
My armor is gone.

### ISSUE THREAD

**Issue by Zorrbanner123** [Wynncraft/Issues#5181] opened 2016-06-08 02:33 UTC
when I logged on I checked my health and it said 10 but also I had no armor and lost it all I had all 12 soul points so I didn't loose my items. All my armor is gone and my health with it too. Please fix this and thank you wyncncraft. -Zorrbanner123

**Comment by YunoFGasai** [comment] 2016-06-08 05:22
duplicate of #4814 please refer all future comments to the original thread

**Closed** 2016-06-08 08:57 UTC
Labels: Duplicate
