### ISSUE TITLE
quest:sister city Hourglass tower bug

### ISSUE THREAD

**Issue by Tennhunter** [Wynncraft/Issues#4430] opened 2016-03-04 04:49 UTC
When I climb up hourglass tower at selchar it not drop Hourglass sand

**Comment by Odnod** [comment] 2016-03-04 04:55
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-05 05:27 UTC
Labels: Duplicate
