### ISSUE TITLE
Green Skinned Trouble Quest Bug

### ISSUE THREAD

**Issue by tttre** [Wynncraft/Issues#3397] opened 2015-12-31 15:24 UTC
When I'm in the cavern, I complete puzzle but when I fall in the hole in the floor, they tp me back and say me "null"

**Comment by Trixter313** [comment] 2016-01-10 22:52
Are you still having this issue?

**Comment by Dar-krusos** [comment] 2016-01-15 11:17
I think you must have missed part of the quest, such as a Quest Update/Dialogue or the tp was simply not working.

**Comment by Dar-krusos** [comment] 2016-01-15 11:23
This is also a duplicate of Issue #3339

**Closed** 2016-01-30 03:35 UTC
