### ISSUE TITLE
Capitalization issue with Quest Book Updated message

### ISSUE THREAD

**Issue by Zombie1Productions** [Wynncraft/Issues#7438] opened 2017-02-23 22:45 UTC
During the quest "Lost Soles", when you use the secret passage to get to the second floor, the "updated" in "quest book updated" is uncapitalized.
![bdf9a69f695444e4ad3b4760b4a53f02](https://cloud.githubusercontent.com/assets/17608640/23282569/a6078172-f9d6-11e6-9e6e-a549e5d7e5da.png)

EDIT: Although this has been reported before, the text is still off.

**Comment by Pyromanical** [comment] 2017-02-23 23:44
Duplicate of #7207 
According to that issue, this has been fixed on the build server, and will be pushed to the main server next map update, which will be Corkus.

**Closed** 2017-02-24 02:22 UTC
