### ISSUE TITLE
Shattered Minds bug

### ISSUE THREAD

**Issue by lagerbooost** [Wynncraft/Issues#3780] opened 2016-01-19 18:35 UTC
When i died in the temple of shattered minds quest i respawned at the very start of wynncraft-near the caravan driver.
gg to my incredibly slow internet that caused my death so i discovered this bug

**Comment by Dar-krusos** [comment] 2016-01-20 01:25
Yeah, this one is just a placement issue. For now you won't be able to do anything about it.

Duplicate of issue #3617

**Closed** 2016-01-20 02:22 UTC
