### ISSUE TITLE
Liquid emerald able to be thrown

### ISSUE THREAD

**Issue by keviny3** [Wynncraft/Issues#2824] opened 2015-12-22 04:56 UTC
In Troms I had withdrawn a Liquid Emerald bottle to trade for some armor but when I right clicked, it was thrown on the ground and disappeared. It has not reappeared in my inventory either.

**Comment by Trixter313** [comment] 2015-12-23 01:25
Duplicate of https://github.com/Wynncraft/Issues/issues/2703

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!

**Closed** 2015-12-23 01:27 UTC

**Comment by keviny3** [comment] 2015-12-23 02:10
Ok.
