### ISSUE TITLE
Bear Zoo: No Boat Merchant

### ISSUE THREAD

**Issue by EnderCraft92** [Wynncraft/Issues#5158] opened 2016-06-05 14:29 UTC
At the Bear Zoo, there appears to be no Boat Merchant. I have tried right-clicking in the positions that this dealer may appear in, but, sadly, it didn't work. I am out of boats, so (besides swimming for a long time, or letting the bears kill me) there is no way off the island. Here is a screenshot to show this error:
![2016-06-05_10 25 08](https://cloud.githubusercontent.com/assets/19761734/15806040/2f400ade-2b08-11e6-8178-2c4b7234b988.png)
If this has already been reported, or there is a fix, please notify me on the WynnCraft forums.
Thanks! :)

**Comment by Mininglover21** [comment] 2016-06-05 20:51
I don't know the issue to this problem, but you can do /kill and respawn in Selchar instead of the bears eating you. Also your coordinates could be close to a place that does have a boat merchant. (For example Mage island or somewhere near you on a random island.

**Comment by Moe-Ronickah** [comment] 2016-06-06 00:11
This merchant has a tendency to go on vacation every now and then.  You can swim to where you want to go, use a tp scroll, or switch servers.  The gms know about it, as do the admins.  For now, it's an undocumented feature, until it gets fixed.

Duplicate of #4178

**Closed by Moe-Ronickah** 2016-06-06 00:11 UTC
Labels: Duplicate
