### ISSUE TITLE
Register @ Forums not working.

### ISSUE THREAD

**Issue by Aspawin** [Wynncraft/Issues#4954] opened 2016-05-06 06:03 UTC
I can't register in the forums due to the "Minecraft" section telling me that my username is invalid.

I've tried using it with both my accounts and yes, both of them don't work.

Fix?

**Comment by Odnod** [comment] 2016-05-06 06:04
Duplicate of #4940, please close this post and direct any additional comments to the original to avoid cluttering up the github. Thanks!

**Closed** 2016-05-06 10:48 UTC

**Comment by Aspawin** [comment] 2016-05-06 14:56
:-)
