### ISSUE TITLE
Guild Problems: Leaving a Guild

### ISSUE THREAD

**Issue by CrafterTheMaster** [Wynncraft/Issues#3494] opened 2016-01-03 05:30 UTC
I can't leave my guild. Whenever the sign pops up, i cant leave the guild by typing "yes". What should I do?
![2016-01-02_21 29 14](https://cloud.githubusercontent.com/assets/16523128/12077431/0bcf70b0-b198-11e5-962c-9bd7b665235f.png)

**Comment by Trixter313** [comment] 2016-01-11 22:07
Duplicate of https://github.com/Wynncraft/Issues/issues/3405

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-11 22:07 UTC
