### ISSUE TITLE
Can't identify legendary helmet

### ISSUE THREAD

**Issue by LightningGrace** [Wynncraft/Issues#2465] opened 2015-10-28 21:07 UTC
I cannot identify my legendary helmet. The name is Pélier, here it is - http://prnt.sc/8wfhrp

https://www.youtube.com/watch?v=xRKdQxpCKu4 is a video, just showing the item not working.

If a fix could be put in, that'd be grand. Thanks! ^-^

**Comment by TrashcanMan** [comment] 2015-10-28 23:18
Known issue, items with accented characters and the Relic Dagger sometimes fail to identify.

**Comment by Trixter313** [comment] 2015-10-30 02:08
As TrashcanMan said, duplicate of #1312

We recommend closing this issue and following the original to stay updated on the status of the issue. Thanks!

**Closed** 2015-10-30 10:45 UTC
