### ISSUE TITLE
Pre-Update Item

### ISSUE THREAD

**Issue by Phuoung** [Wynncraft/Issues#4174] opened 2016-02-19 05:58 UTC
Someone who didn't witness the update here so don't be harsh. I have an old rare leather chest piece that goes by the name of "Demasse"  and has no stats in general. Was some of the items prior to the "massive" update deleted? And if so, what to do with this old chest piece?
![screenshot 2](https://cloud.githubusercontent.com/assets/17328649/13167730/b9eb0f4e-d68a-11e5-93db-6b6011230997.png)

**Comment by Phuoung** [comment] 2016-02-19 06:00
My bad, it was a leggings piece.

**Comment by TrashcanMan** [comment] 2016-02-19 06:17
All the items with accented characters are super broken right now, it should hopefully be fixed soon.

**Comment by Phuoung** [comment] 2016-02-19 06:20
Thanks for responding and telling me. I was worried because I liked the accent marks on the different items. And I'm afraid to wear it so, I'm going to live it in there.

**Comment by Trixter313** [comment] 2016-02-19 12:00
Duplicate of https://github.com/Wynncraft/Issues/issues/3161

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-19 12:00 UTC
