### ISSUE TITLE
Can't leave my guild for months!!!!

### ISSUE THREAD

**Issue by ChocolatyBear** [Wynncraft/Issues#4796] opened 2016-04-11 00:34 UTC
# Delete this line if you've searched for a duplicate issue first
I can't leave my guild!!! it's been months my name is Chocolaty_Bear and guild's name is Gystiriem NO ONE IS EVER ON PLEASE HELP ME! PLEASE KICK ME!

**Comment by Trixter313** [comment] 2016-04-11 00:52
I see that you've changed your name before, making this a duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-11 00:52 UTC
