### ISSUE TITLE
Wynnexcavation site b

### ISSUE THREAD

**Issue by Thooler33** [Wynncraft/Issues#4413] opened 2016-03-03 12:23 UTC
There is a problem in the quest "WynnExcavation Site B". In fact, when I arrive in the room where the crystal spawns, it is not. There is nothing. 
I did /fixquests but no problem. 

Thanks

I'm sorry if this subject has been already created, but just answer me if there are possibilities to repair this bug, thanks. I'll delete it after your answers ;) !

**Comment by Odnod** [comment] 2016-03-03 14:54
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on

**Closed** 2016-03-03 16:00 UTC
