### ISSUE TITLE
Leather dyed armor set arent dyed when looted from mobs

### ISSUE THREAD

**Issue by Daimont** [Wynncraft/Issues#5913] opened 2016-08-30 14:18 UTC
I dropped the snow pants from a mob but the pant is not white dyed, same problem for the ghostly pant, looted from a ghost, the item isnt purple

![2016-08-30_16 16 21](https://cloud.githubusercontent.com/assets/21339102/18092660/69149a0a-6ecd-11e6-9b71-9d54bb2d1590.png)
![2016-08-30_16 16 11](https://cloud.githubusercontent.com/assets/21339102/18092671/6f8add90-6ecd-11e6-848d-368fb74a499f.png)

**Comment by Trixter313** [comment] 2016-08-30 22:42
Duplicate of https://github.com/Wynncraft/Issues/issues/3903

**Closed by Trixter313** 2016-08-30 22:42 UTC
