### ISSUE TITLE
Water puzzle in  Water Mini Dungeon is broken

### ISSUE THREAD

**Issue by bamboobazooka** [Wynncraft/Issues#1539] opened 2015-01-22 19:12 UTC
me and a friend were trying to complete this and it sorta worked once then flat-out did not work. There is no water flow and sometimes the blocks will not move at all i feel as though this is simple redstone errors but still thought i should post this please fix this quick we are kinda stuck in there aside from doing /kill

**Comment by epicman739** [comment] 2015-01-23 04:27
This one's a known issue, it should be fixed soon.

**Comment by Jamdog** [comment] 2015-01-23 20:37
Duplicate of https://github.com/Wynncraft/Issues/issues/1445

**Closed** 2015-01-29 16:45 UTC
