### ISSUE TITLE
Boat merchants

### ISSUE THREAD

**Issue by sicklylemon** [Wynncraft/Issues#3579] opened 2016-01-07 01:47 UTC
Several boat merchants in the wynn ocean wont spawn, currently I've only seen a boat merchant at Selchar. Also the boat merchant at Selchar doesn't have the the boat icon on the wynncraft map.

**Comment by Trixter313** [comment] 2016-01-07 07:24
Duplicate of https://github.com/Wynncraft/Issues/issues/3243

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-07 07:24 UTC
