### ISSUE TITLE
Chests and buttons not working? I posted this yesterday and it seemed to be ignored and I could not find the original feed.

### ISSUE THREAD

**Issue by SpeederSam** [Wynncraft/Issues#4202] opened 2016-02-20 21:56 UTC
I had a mission to find two loot chests for 85 emerald blocks and I was unable to complete it because when I clicked on the two chests it said You do not have permission for this area. It was a rare chest also and this is not the first time it has happened. I have talked to other players and some have had the same issue. PLEASE FIX and at least tell me you are working on this problem before you close it. Thanks

**Comment by Trixter313** [comment] 2016-02-20 22:08
Duplicate of #4151

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-20 22:08 UTC

**Comment by Trixter313** [comment] 2016-02-20 22:09
Your previous post was marked as a duplicate and we linked the original thread so you could see all of the information we currently have on the issue.
