### ISSUE TITLE
quest wynn Excavation

### ISSUE THREAD

**Issue by pazzboy13** [Wynncraft/Issues#2550] opened 2015-11-24 03:49 UTC
it says that i need the tablet but im past that part and /fixquests isn't working

**Comment by SkySaito** [comment] 2015-11-25 20:39
More details please ?

**Comment by SamuelMast** [comment] 2015-11-29 22:10
I have the same problem... I started the quest Wynn excavation A and i got the paper that tesha translates. I did that then i returned it to the excavator and went in the temple did the parkour and puzzle and then got teleported out. In my quest book it still says return and talk to excavator Vade. The problem is it wants me to translate the paper again that i no longer have... Therefore I can't do anything eles in this quest?!?!?!?

**Comment by Trixter313** [comment] 2015-12-22 18:37
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Closed** 2015-12-25 20:38 UTC
