### ISSUE TITLE
Armour piece broken

### ISSUE THREAD

**Issue by Snowypvp** [Wynncraft/Issues#5625] opened 2016-07-30 22:27 UTC
My chestplate was fine I left wynn for a month or two and now it just shows text
https://gyazo.com/c4283bd90b4b1890bd059d7e0a74dab9
https://gyazo.com/4206e201cdbed0d0ae40de61fd902c31

**Comment by Moe-Ronickah** [comment] 2016-07-31 00:22
I think that you have been gone for a lot longer than a month or two.  Are you sure about that time frame?  The reason that I ask, is that this happened a lot when the Gavel update came out, last year.

**Comment by Snowypvp** [comment] 2016-07-31 21:30
It was longer then a month but when gavel came out it was fine i played for a lil and when i got on yesterday it was like that

**Comment by Moe-Ronickah** [comment] 2016-08-01 02:19
Duplicate of #3175 .  Hang on to it for a few more days, and then check it again.  If it doesn't fix itself, there is nothing that can be done about it.  I'm sorry to have to say that.

**Closed by Moe-Ronickah** 2016-08-01 02:19 UTC
Labels: Duplicate
