### ISSUE TITLE
Lost item when buying first bank slots

### ISSUE THREAD

**Issue by robertm1771** [Wynncraft/Issues#6461] opened 2016-10-24 14:57 UTC
Just started playing. I was trying to figure our the bank and tried to drop an item in the dark colored slots. Well I ended up buying the slots and the item that I dropped was lost.
1. Should not have lost item I assume.
2. Suggest different texture for the locked slots on the bank as at first they looked like empty slots to use.

Seems very polished otherwise. All but the "you don't have permissions in this area" message with my current wand. Might I suggest a different message might be more help full to new players.

**Comment by LordHelmchen98** [comment] 2016-10-24 15:00
Duplicate of #4091

**Comment by robertm1771** [comment] 2016-10-24 16:22
Did a search for bank it didn't find this one. Oh well I tried to search it.

**Comment by Surra-1** [comment] 2016-10-24 17:02
I don't believe this is a duplicate at all. @robertm1771, do you remember what item you clicked on it with?

To my understanding, he clicked on the unlock slot with an item selected. Because he had an item selected, it was lost. I don't think this has to do with the bank breaking all glass pains when expanding.

**Comment by robertm1771** [comment] 2016-10-24 17:14
It was gold leg armor not sure the name of the item.

**Comment by LordHelmchen98** [comment] 2016-10-24 23:23
@Surra-1 Better now? Also this is still related to items disappearing when you buy a bank upgrade and norefund policy strikes again.
Oh and @robertm1771 I didn't see that last sentence before. The permission error happens because your weapon is a retextured slab. The game thinks you want to place it which is not allowed. If you want to open chests, doors,... you just have to use your bare hands or another item. As far as I know this doesn't really affect the gameplay beside the fact that you can't open chests with those weapons and you chat is getting spammed so I don't think this issues has a very high priority.

**Comment by robertm1771** [comment] 2016-10-25 16:28
@LordHelmchen98 I know why I get the permission error my point was a different message might be more helpful to new players. It can cause new players to get frustrated as they cant open loot chest and game functions seem to be broken. Myself I took some time and figured it out. While others might just stop playing. So I would put this in the higher priority side of things. As I assume player retention is important to the survival of any such game. I think there is allot of information now for someone in authority to mark this as needed and pass it along if needed. If someone from the team has questions I will be happy to respond.

**Comment by Moe-Ronickah** [comment] 2017-02-08 04:48
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.

**Closed by Moe-Ronickah** 2017-02-08 04:48 UTC
