### ISSUE TITLE
Geothermal Neckplace disappeared from ender chest when I expanded????

### ISSUE THREAD

**Issue by coreynj** [Wynncraft/Issues#5805] opened 2016-08-22 15:51 UTC
I was in my Ender Chest, and I saw I could afford to buy another line. I had a Geothermal Necklace in there, saving it for when I reached the minimum level. But when I bought the next line, it COMPLETELY DISAPPEARED. Where the hell did it go???

Edit: Let me elaborate a little bit, in case this matters. It was a level 38 necklace, Unique tier. The enderchest had 3 lines, I bought the 4th line. I moved the necklace right before buying the line, so perhaps it lagged and I was still holding the necklace when I bought the new line, I have no idea if that would do anything.

**Comment by YunoFGasai** [comment] 2016-08-22 18:47
the item used for necklaces is a glass pane so when you expand your bank it gets removed with the rest of the glass panes, this is a known issue and hopefully will get fixed in the next update.
you will not get your necklace back but I might have some spare gear for you.
my ign is YunoGsai /msg me when I'm online

**Comment by coreynj** [comment] 2016-08-22 19:10
Alright, good to know. I don't need any spare gear, thanks for the offer though.

**Comment by Trixter313** [comment] 2016-08-22 19:15
Duplicate of #4091

**Closed by Trixter313** 2016-08-22 19:15 UTC
