### ISSUE TITLE
BUG on guild invite/leave

### ISSUE THREAD

**Issue by BarakaGG** [Wynncraft/Issues#4492] opened 2016-03-07 16:53 UTC
Hi, my friend leave a guild and try to join on my guild, now he cant join any guild, and whem he did a /guild leave have a message "you are not in a guild", and i invite him e have a message "ursobatata is already in a guild"

/guild join -> you were not invited to join

PLease help us!

Nick: Ursobatata

**Comment by ChiefInferno** [comment] 2016-03-07 20:27
same I've been trying to leave my guild for 6 months but never rely thought about it, now that I'm a higher level and people are inviting me to guilds its messing me up. it was due to my name change I think and my guild is inactive so I cant get some one to kick me. ever thread I've seen has been labeled as a duplicate and the original post doesn't give us an answer or help.
please help just because this is not the biggest problem on the server doesn't mean it should be put to the back it has, it has and is makes me want to quit the server for some time

**Comment by BarakaGG** [comment] 2016-03-09 15:18
nice Bug report forum, nobody try to help, or any mod...

¬¬

6 mounths with the same problems, omg!

**Comment by sammyvsparks** [comment] 2016-03-10 17:16
Same problem, It is annoying... My guild is completely locked up.

**Comment by Moe-Ronickah** [comment] 2016-03-11 04:35
BarakaGG, there is nothing that can be done at this time for this issue.  The admins are aware of the guild problems and are working on them.

ChiefInferno, same advice as above.  Name changes are known to really mess up a players guild status, but everything on guilds is still being worked on.

BarakaGG, about 8 months ago, the admins asked the player base if we would rather have Gavel worked on, or guild issues.  The vote was heavily towards Gavel.  Guild issues are being worked on.

Everyone who responds on GitHub is here voluntarily.  We all have lives.  And, if you had taken the time to have researched your issue, you would have found many duplicates of it.

Duplicate of #4320

**Closed by Moe-Ronickah** 2016-03-11 04:35 UTC
