### ISSUE TITLE
Assassin Glitches

### ISSUE THREAD

**Issue by Skipeeto** [Wynncraft/Issues#3527] opened 2016-01-04 06:50 UTC
Level: 49
Weapon: Scorpion

Bug 1: The spin attack spell causes mobs to spin around me and do damage to me rapidly. It causes a lot more harm than it helps me.  I have actually seen a few reports of this before.

Bug 2: I believe when I kill mobs with the spin attack move it does register as a kill. At first I thought this may have just been coincidence, however, I killed Phantom Twain with it and he didn't drop his journal which he is supposed to 100% of the time I'm pretty sure.  I have seen anyone post about this but if you experience the same problem let me know.

**Comment by Trixter313** [comment] 2016-01-04 06:51
Duplicate of https://github.com/Wynncraft/Issues/issues/3140

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-04 06:51 UTC
