### ISSUE TITLE
Wynncraft Exavation Cite C

### ISSUE THREAD

**Issue by Tesdro** [Wynncraft/Issues#4406] opened 2016-03-03 00:50 UTC
it doesn't drop the red shard and when I went to talk with thr Exaviator guy he says "requires shard from Cite B" and I already started the quest!

**Comment by Tesdro** [comment] 2016-03-03 00:51
It is a serious thing that I can't get over. Please help. I know that the 2nd shard of Cite B is used for Cite D

**Comment by Odnod** [comment] 2016-03-03 01:47
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-03 01:48 UTC
