### ISSUE TITLE
Relic weapons

### ISSUE THREAD

**Issue by dm6506** [Wynncraft/Issues#2039] opened 2015-06-27 14:27 UTC
Every relic weapon/armor are able to be identified but relic daggers however can not 
![8](https://cloud.githubusercontent.com/assets/13077680/8392377/209c8f1c-1cb7-11e5-8743-0b343fae2b48.png)
![9](https://cloud.githubusercontent.com/assets/13077680/8392378/209ec2d2-1cb7-11e5-9332-1acaed7767a2.png)

**Comment by Trixter313** [comment] 2015-06-27 17:26
Duplicate of https://github.com/Wynncraft/Issues/issues/1312
What we suggest doing is closing this issue and following the original to stay up to date on the status of it. Thanks and have a fun time playing Wynncraft! :)

**Comment by dm6506** [comment] 2015-06-27 18:16
ok thanks

**Closed** 2015-06-27 18:16 UTC
