### ISSUE TITLE
Pls fix that Guild Bug D:

### ISSUE THREAD

**Issue by Arreme2000** [Wynncraft/Issues#5947] opened 2016-08-31 11:33 UTC
I know this is a well-known bug, and that maybe it has been already posted on this site, but it's just getting too annoying. If you change your nickname while in a guild, sometimes things will mess really up. (Guild chat doubled and the incapability to leave the guild.) Really, I have been experiencing this for 4 months (or more) now. Hope this bug can get fixed soon.
![2016-08-31_13 31 48](https://cloud.githubusercontent.com/assets/10437636/18127244/71162298-6f7f-11e6-848d-8906c00311fb.png)
![2016-08-31_13 32 14](https://cloud.githubusercontent.com/assets/10437636/18127245/7117e8d0-6f7f-11e6-8316-dccbbcafaf68.png)
![2016-08-31_13 32 34](https://cloud.githubusercontent.com/assets/10437636/18127243/7116038a-6f7f-11e6-9a92-90cab9bf2f5d.png)

**Comment by 0x0000null** [comment] 2016-09-01 18:34
Duplicate of #3665.

Also, please turn off mob radar in your minimap mod, it is against the Wynncraft rules.

**Closed** 2016-09-03 07:19 UTC
Labels: Duplicate
