### ISSUE TITLE
Legendary item can't be identified

### ISSUE THREAD

**Issue by Alteyr** [Wynncraft/Issues#2314] opened 2015-09-20 02:40 UTC
All is in the title

Name : Pélier
Level : 42
Rarity : Legendary

https://www.youtube.com/watch?v=AGqfGcWTDMY
(sorry for the music i forgot to remove the sound and my mic on the video x) )

**Comment by Trixter313** [comment] 2015-09-20 02:42
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!

**Closed** 2015-12-25 20:40 UTC
