### ISSUE TITLE
Taproot quest broken.

### ISSUE THREAD

**Issue by Skillett** [Wynncraft/Issues#3979] opened 2016-02-04 01:10 UTC
Step: "Grab Tiek [1 Ginseng], [1 Lobelia], and [1 Vervain] from her garden"

I have all three of those items in my inventory: http://prntscr.com/9yqorz

I prompt Tiek to return the items and get "Something something Ginseng, Lebelia, Vervain. Check the graveyard"

It should move me along to next step. But nope. Tried /fixquests and nothing.

**Comment by Odnod** [comment] 2016-02-04 01:40
get the wilted variety right next to her house first

**Comment by DarkDemonDragon** [comment] 2016-02-04 04:08
@Skillett those are the wilted versions. Tiek says that they aren't strong enough so you need to get the source. I recommend checking the wiki or watching an walkthrough ( https://www.youtube.com/watch?v=JfyKkd7R-f0) if you don't understand what to do. Please close this as this is not a bug, but an intended feature of the quest.

**Comment by Skillett** [comment] 2016-02-04 04:18
She doesn't tell me that it's wilted. She is stuck on the same message.

**Comment by DarkDemonDragon** [comment] 2016-02-04 13:07
Please post a screenshot of the chat Tiek says and what your quest book says.

**Comment by Dar-krusos** [comment] 2016-02-05 23:32
There are two versions of each of those flowers. The first versions are next to the house, the second ones are found in various locations around the forest.

Tiek first asks you to bring all the first versions at once, then all the second versions at once.

**Comment by Moe-Ronickah** [comment] 2016-02-08 02:37
@Skillett , are you still having this problem, or has is it fixed?

**Comment by Skillett** [comment] 2016-02-08 04:26
Fixed.

**Closed** 2016-02-08 17:40 UTC
