### ISSUE TITLE
Drought Sand

### ISSUE THREAD

**Issue by CryingEnder** [Wynncraft/Issues#4177] opened 2016-02-19 12:47 UTC
This quest says that I need 6 water bottles and 24 mashed insects to finish it. When i click again on the NPC, it says: "I am still waiting for [24 Water Bottles] and... etc". But i finished it with only 6 water bottles  so that's just an outdated writing. That's the first issue. The second is that when I finished the quest, the reward says that it gives me access to Almuj Bank, but i had acces before doing this quest, or after starting it.

**Comment by Trixter313** [comment] 2016-02-19 21:23
I don't think the issue with the first one is that the writing is outdated, but that it didn't require the insects to continue when it should have. As for the second part, are you sure you weren't thinking about another class being able to enter but not the current one? Thanks!

**Comment by BlueThunder25** [comment] 2016-02-20 20:17
Before completing the quest he grants you temp access to the Almuj Bank, but upon completing the quest you get permanent access to the bank

**Comment by Trixter313** [comment] 2016-02-20 21:23
Ah, then there's just one issue, the quest not requiring the insects.

**Comment by Moe-Ronickah** [comment] 2016-02-21 00:33
Duplicate of  #38.

Irt: Bring me back [24 Water Bottle] and [24 Mashed Insects] as soon as you can.

The mission can be finished with only [1 water bottle] and [24 Mashed Insects].

**Closed by Moe-Ronickah** 2016-02-21 00:33 UTC
Labels: Quests
