### ISSUE TITLE
Bank Items Disappeared... TWICE!

### ISSUE THREAD

**Issue by MysticalBlaze** [Wynncraft/Issues#6219] opened 2016-09-21 14:50 UTC
So I added slots to my bank about a week ago, and when I did, my "Jester Bracelet" simply disappeared.
Of course I got mad, until yesterday I still had not been able to find another one.
  NOW, TODAY, I ran out of bank slots, so I upgraded it again. AND GUESS WHAT. THIS TIME I LOST A "MORPH-RUBY" AND A "JESTER NECKLACE".
  If it happening once was already bad enough, TWICE IS ENOUGH!

  Of course I don't have any screenshots to prove it, I would not guess it would happen again -.-
  I know Wynncraft has a "no refund policy" but i'm 100% i'm not the only one with this issue, so PLEASE FIX IT BEFORE IT HAPPENS AGAIN!!!

**Comment by TeenageCat** [comment] 2016-09-21 20:46
Yeah, I agree. I don't see how it's not fair for everyone else if refunds were allowed. If anything, it's not fair for us, because we work a very long time just for something that just disappears. How is it fair to anyone if a glitch happens which they didn't know about and they lose one or all of their hard-earned items?

**Comment by Trixter313** [comment] 2016-09-25 00:35
Duplicate of https://github.com/Wynncraft/Issues/issues/4091

**Closed by Trixter313** 2016-09-25 00:35 UTC

**Comment by Trixter313** [comment] 2016-09-25 00:37
@TeenageCat there would be no way to tell whether someone actually lost something to a glitch or if they just wanted a free item, unfortunately.
