### ISSUE TITLE
Can't open chests, do dungeons bosses, or open doors.

### ISSUE THREAD

**Issue by mayab3223** [Wynncraft/Issues#8623] opened 2017-07-19 17:49 UTC
I am constantly given the message "You do not have permission for this area" when i try to do these tasks. I first noticed this in the infested pit dungeon, when i could not warp to the boss fight using the button. When i died to be able to leave the dungeon, the glitch persisted in the rest of the world, making me unable to complete quests and open bonus chests. Screenshots: (note: i'm not doing a dungeon for nothing)
![2017-07-19_13 40 48](https://user-images.githubusercontent.com/30298226/28381416-ca60093e-6c88-11e7-92f2-8e8cc0e0b15f.png)
![2017-07-19_13 45 18](https://user-images.githubusercontent.com/30298226/28381420-cd782bd8-6c88-11e7-90f4-24b0253a3c36.png)
![2017-07-19_13 41 56](https://user-images.githubusercontent.com/30298226/28381428-cffbfc22-6c88-11e7-8197-0f3b96a9d646.png)

I can't complete the Creeper quest or go to shops with closed doors. I don't know what this is from but it first occurred because of the parkour teleport glitching in the infested pit.

**Comment by EarthTroops** [comment] 2017-07-20 00:49
Lol that's happens to me and everyone that's uses items that would otherwise be something like a slab in vanilla MC. Switch what you're holding in your inventory and it should work. Would be nice if they could fix that issue as I have a bow in my ranger account that would be a slab in vanilla. And it interprets it as me trying to place slab hence that error

**Comment by thecoolkogut4** [comment] 2017-07-20 01:44
Hey there!

This is because the item you were using is a retextured half-slab, and the game thinks you were trying to place it as a result it says you don't have permission to. To fix this right click with an empty hand or your soul point.

Duplicate of #3902

Goodluck.

**Closed** 2017-07-20 06:59 UTC
