### ISSUE TITLE
Unable to leave my current guild (Name Changed)

### ISSUE THREAD

**Issue by Historicals** [Wynncraft/Issues#7776] opened 2017-04-09 23:52 UTC
Hello, quite a while ago i've joined a guild name SqS (SquishySquad) Whilst I was in this guild i've attempted to leave it numerous times as it is an inactive & dead guild also because the owner of the guild isn't online (Last time the owner of this guild was online was in 31st of January 2016)

I have changed my name numerous times trying to leave the guild with a diffrent name but that seems to make the issue worse.

If anyone is able to help me with this issue contact my email at themysticcake@gmail.com or DM me on twitter @Operator_Fox

PS: It's been over 1-2 years that this issue has been going on for and if anyone is able to fix the guilds I would be greatful.

PCE
~Historicals

**Comment by LordHelmchen98** [comment] 2017-04-10 00:02
Duplicate of #3665 
There is no known fix for this. Unfortunately you will have to be patient until guilds get fixed.

**Closed by LordHelmchen98** 2017-04-10 00:02 UTC
Labels: Duplicate
