### ISSUE TITLE
Needing help SOON

### ISSUE THREAD

**Issue by NerrawChase** [Wynncraft/Issues#5836] opened 2016-08-28 04:01 UTC
I've ran into a bug where at class selection i continually fall through the world. I've tried every "fix" i could find on the forums as well as here still nothing. This has been going on for a little over a week now and i still can not seem to get anyone to help me. Someone on here told me its unfixable and there isn't anything you guys can do about it, I purchased VIP+ as well as Gold coins not even a full 12 hours before this glitch started to happen so i feel like it'd only be far if i got a refund or at least have my rank and coins transferred to a different account? 

I've brought this same topic up to many staff already and not a single one of them given me the time of day? It's always "can't help" or "I'm busy find someone else" or "I'll get back to you" and yet still nothing

**Comment by Trixter313** [comment] 2016-08-28 13:27
Duplicate of https://github.com/Wynncraft/Issues/issues/5785

Please do not make duplicate issues. As we said in the original thread we don't **currently** have a fix. One will be made soon.

**Closed by Trixter313** 2016-08-28 13:27 UTC
