### ISSUE TITLE
Buggofish Dungeon 

### ISSUE THREAD

**Issue by Crinji** [Wynncraft/Issues#5417] opened 2016-07-06 19:14 UTC
Oh, where to begin so first most of the mechanics for the Silverfish dungeon can get messed up in a different way on different servers and not to mention doors not opening, 2. sometimes the Boss keeps respawning over and over and you can't get out, 3. How do you go to Llevigar if you went to Almuj WHEN YOU DIE, TELL ME! Thats it all the things that happen to me and have not been able to complete the silverfish dungeon

**Comment by Moe-Ronickah** [comment] 2016-07-06 23:52
OK.
1: this one is a duplicate.
2: you have to run away to the exit.  The Boss does respawn quickly.
3: you always respawn in the nearest city to where you die.  On the map.  The real map.

Wait until you have a better weapon, or until you gain a level or two, before trying the dungeon again.  Dungeon Bosses are mean, and they love to kill the unprepared or unwary player.

**Comment by YunoFGasai** [comment] 2016-07-07 07:10
btw I really like your title

**Comment by XavierEXE** [comment] 2016-07-08 09:19
As for the second issue, killing the boss again should teleport you out. Also, doing /class or /hub then logging back in will teleport you out of the dungeon.

**Comment by Moe-Ronickah** [comment] 2016-07-09 00:56
"2:" is a dupe of #4154 .  "The Silverfish Boss has a 50% chance of respawning within seconds after it dies. It was born that way, e.g., it's not an issue, it's meant to be like that."

**Closed** 2016-07-09 00:57 UTC
