### ISSUE TITLE
Wizard Horses

### ISSUE THREAD

**Issue by Shadoweagle5098** [Wynncraft/Issues#4860] opened 2016-04-19 21:07 UTC
This is something kind of minor but hilarious that can be considered a bug. There are horses that spawn by a ranch on the Llevigar plains that are hard to miss for two reasons. Why? Well, one reason is that the place they spawn is right by the main trail through the plains. The other? When you get close enough, you will teleport. Yes, you will TELEPORT if these things get near you. Not far, only a few blocks, but these Wizard Horses have the ability to glitch the game. This is more on the useless and small problem side of things, but its still a bug.

You're a wizard, Horsey!

**Comment by Verret001** [comment] 2016-04-20 00:03
I like your humor.

**Comment by RedMorcus** [comment] 2016-04-20 00:57
I believe this is caused if you right click them, your player will attempt to mount the horse and get kicked off of it by the server.

**Comment by Trixter313** [comment] 2016-04-20 01:26
This appears to be a duplicate of https://github.com/Wynncraft/Issues/issues/3143

The issue has been determined as a game mechanic that can't really be changed by the Wynncraft team.

Please post any future replies to the original thread. Thanks!

**Closed by Trixter313** 2016-04-20 01:26 UTC
Labels: Awaiting Confirmation, Entities
