### ISSUE TITLE
You don't have permission for this area.

### ISSUE THREAD

**Issue by GabrielMoose** [Wynncraft/Issues#5123] opened 2016-06-02 00:46 UTC
When i shoot my bow it says the title in red and i think it's because the server thinks it's a block and i have a suggestion to how to stop this bug. My suggestion is to give a item identifier a glitched item and he will fixes it for free.

**Comment by Moe-Ronickah** [comment] 2016-06-02 00:51
Duplicate of #3902

**Closed by Moe-Ronickah** 2016-06-02 00:51 UTC
Labels: Duplicate
