### ISSUE TITLE
Guild defenses that I bought were assigned to another guild

### ISSUE THREAD

**Issue by Fornax96** [Wynncraft/Issues#5595] opened 2016-07-27 11:10 UTC
So I captured the Detlas suburbs and immediately bought 60 mobs for it. After I clicked "buy" I went to the bank to get some more money for mobs. When I came back 30 seconds later it told me that I should capture the territory before I could defend it. So I launched an attack and in the chat it said that there were 60 mobs defending it, when the war started I saw that it were exactly the mobs that I purchased! What a waste of emeralds.

**Comment by Moe-Ronickah** [comment] 2016-07-27 22:18
And after you launched the attack, whose mobs were defending the territory?

**Comment by Fornax96** [comment] 2016-08-01 19:10
Sorry, I forgot to reply.

I'm pretty sure I was attacking my own mobs, since they were all low level and there were more archers than warriors, just like I purchased them. And there were exactly 60, which is how many I bought.

**Comment by Moe-Ronickah** [comment] 2016-08-03 14:01
OK, just to be clear, were the mobs really assigned to another guild, or were they assigned to your guild?  In other words, did you check to see if the territory was yours?  Was this just a lag issue, or did your mobs really get assigned to another guild?

**Comment by Fornax96** [comment] 2016-08-03 19:22
When I started buying mobs the territory was still owned by my guild, but when I was done buying the mobs the territory was owned by another guild. They must have captured it back from me while I was buying defenses.

**Comment by Moe-Ronickah** [comment] 2016-08-05 07:32
Ouch.  Well, we do know that guilds are being worked on.  I'll think we'll leave this up as another guild issue to be fixed if/when guilds get revamped.

**Comment by thecoolkogut4** [comment] 2017-01-18 15:09
ok I have an explanation for this. right after you defend a territory the territory turns "red" for a minute or two. red means that you don't own it (turns red while the mobs are being bought). during the time that it's red you typed guild attack which resulted in attacking your own land. if you would have look at who owned te land right before you got tped, it most likely would if said you owned it. that's on reason for this to happen. another way (I think) is right whe you finish the war, you get tped to the normal world and type guild defend. when your in the GUI  (with currently 0 mobs placed on the territory) another guild attacks and since there is 0 mobs, it insta attacks and they auto claim it. so they have claimed the territory but you still have the defending GUI open. you buy your mobs and click confirm, but  you bought them for the other guild. 


typed this on my phone so might be a few typos or something off... if further explanation is needed feel free to contact me in game (TheDarkSoul) or on github....

**Comment by Moe-Ronickah** [comment] 2017-01-23 19:30
"right whe you finish the war, you get tped to the normal world and type guild defend. when your in the GUI (with currently 0 mobs placed on the territory) another guild attacks and since there is 0 mobs, it insta attacks and they auto claim it. so they have claimed the territory but you still have the defending GUI open. you buy your mobs and click confirm, but you bought them for the other guild."

This has been confirmed, and it will only get fixed when guild's get revamped.

**Comment by Moe-Ronickah** [comment] 2017-01-29 18:50
Duplicate of #4580

**Closed by Moe-Ronickah** 2017-01-29 18:50 UTC
Labels: Guilds
