### ISSUE TITLE
Unable to Connect. Please Report

### ISSUE THREAD

**Issue by MlgDavid** [Wynncraft/Issues#2149] opened 2015-07-28 08:33 UTC
I cant join a lobby on wynncraft and it told me to report the issue so i did/am :smiley: 
![bug](https://cloud.githubusercontent.com/assets/13535412/8926941/a80f9f42-34c8-11e5-9ea8-72086a399d85.png)

Username: DavidIsHere
Day (Australia): 28th of July, 2015

**Comment by pizzaeatster** [comment] 2015-07-28 13:30
Same problem

**Comment by Trixter313** [comment] 2015-07-28 15:50
Duplicate of https://github.com/Wynncraft/Issues/issues/2148

We recommend closing the duplicate and following the original if you'd like to stay up to date on the status of the issue. Thanks!

**Closed** 2015-07-29 06:07 UTC
