### ISSUE TITLE
Items don't drop on the ground death dispite having zero Soul Points

### ISSUE THREAD

**Issue by Pokextreme** [Wynncraft/Issues#2937] opened 2015-12-23 08:22 UTC
Hi, My In game name is Pokextreme andI fell to my death in detlas and despite having only 2 Soul Points, and I lost my items from my inventory, but they did not drop, I am not sure what block I laded on, but It might have been a stair, and gotten the Minecraft glitch where items sometimes disappear when they and on a stair. It may have also been due to me dying to fall damage. I was the first one to where I dies, so I know nobody else took it. Mainly I lost, A full set of champion armor, A 40/40 white horse named relentless, and A Bobs Mythic Wand.
Here is a Link to how I got thrown up into the air and ended up dying
https://github.com/Wynncraft/Issues/issues/2935

**Comment by Monkeysz** [comment] 2015-12-23 08:31
Um you lose your stuff when you don't have any soul points left, so it makes sense you lost all your items. Your items also don't come back to the place where you died. I myself have experienced this. People will just say you can't get back your stuff because Wynn has a strict no refund policy. Good Luck. Losing your stuff sucks.

**Comment by Pokextreme** [comment] 2015-12-23 08:35
The Website says that you drop your items on death when you have 0 soul points so they should be on the ground.

**Comment by Trixter313** [comment] 2015-12-23 16:08
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this and because it's caused by a bug in Minecraft itself there's not much that can be done to fix it either. We'd appreciate it if you closed this issue. Thanks!

**Comment by Pokextreme** [comment] 2015-12-23 18:06
I want to be sure a Mod/Admin sees this because it very well could have been caused by diving to the fall

**Closed** 2015-12-25 20:33 UTC
