### ISSUE TITLE
Bob's Tear

### ISSUE THREAD

**Issue by ExplosionHacker** [Wynncraft/Issues#5783] opened 2016-08-20 14:16 UTC
So I Killed Bob and i saw a tear drop but the tear just disappeared into the air like it just flew up and away

**Comment by Trixter313** [comment] 2016-08-20 23:27
Has this happened repeatedly or just one time? It might have just been a visual glitch because of it landing on stairs or slabs.

**Comment by Moe-Ronickah** [comment] 2016-08-21 09:25
Duplicate of #5776

**Closed by Moe-Ronickah** 2016-08-21 09:25 UTC
Labels: Duplicate
