### ISSUE TITLE
Ahsmord bug

### ISSUE THREAD

**Issue by TheMineNerf** [Wynncraft/Issues#3370] opened 2015-12-30 22:07 UTC
whenever me and my friends go to Ahsmord, it doesnt say "You are now entering Ahsmord" which prevents us from using TP scrolls to there

**Comment by Trixter313** [comment] 2016-01-30 03:23
Duplicate of https://github.com/Wynncraft/Issues/issues/3202

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-30 03:23 UTC
