### ISSUE TITLE
Le with trade glitch

### ISSUE THREAD

**Issue by Justinthepiplup** [Wynncraft/Issues#2633] opened 2015-12-14 09:31 UTC
Hello, I was showing my friend a stack and 40 LE I put the stack first then 40 and the 40 LE got deleted. I tried relogging, I tried looking around and it wasn't there. Earlier my friend has this bug with 15 LE hopefully you could fix it, if possible get me my 40 LE back ingame name: RoughmanPearl

**Comment by DarkDemonDragon** [comment] 2015-12-14 18:48
Wynncraft has a strict no-refund policy plus some definitive proof would be necessary.

**Comment by Moe-Ronickah** [comment] 2015-12-15 12:27
[DUPLICATE of #1245]
I'm sorry, Justinthepiplup, but WynnCraft has a strict no-refunds policy due to previous instances of players being less than honest. You aren't alone in having items disappear, and I know that that is no consolation to you, however, it does happen, every now and then.

Would you please close this issue? Thanks, in advance.

**Closed** 2015-12-16 10:00 UTC
