### ISSUE TITLE
Craftmas Chaos Quest

### ISSUE THREAD

**Issue by mdragonwhite** [Wynncraft/Issues#4044] opened 2016-02-08 14:11 UTC
After i talk to the Crystal Summoner, i go to the portal, start to fall than i die when i reach the ground

**Comment by Trixter313** [comment] 2016-02-08 18:25
Duplicate of https://github.com/Wynncraft/Issues/issues/3678

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-08 18:25 UTC
