### ISSUE TITLE
Unneeded quest items returned after using /fixquests command

### ISSUE THREAD

**Issue by SundoWave** [Wynncraft/Issues#3533] opened 2016-01-04 16:28 UTC
As I said I used the /fixquests commands and it gave me items that I had already used for quests(I'm already on the stage of the "WynnExcavation site D" quest where I have to kill shadow Amadel, meaning I have already given the crystals to the royal adviser Carlos). Now I'm stuck with them because I can't drop quest items.
![screenshot 2016-01-04 20 21 07](https://cloud.githubusercontent.com/assets/7979808/12094364/9f2b41d8-b321-11e5-9ab4-8235b9d3edda.png)
![screenshot 2016-01-04 20 21 18](https://cloud.githubusercontent.com/assets/7979808/12094365/9f2c8a7a-b321-11e5-97b5-6eab39cf21c6.png)
![screenshot 2016-01-04 20 20 58](https://cloud.githubusercontent.com/assets/7979808/12094363/9f285c7a-b321-11e5-8356-b74a4dfd0bff.png)
![screenshot 2016-01-04 20 21 04](https://cloud.githubusercontent.com/assets/7979808/12094366/9f328d1c-b321-11e5-85de-7485e431df86.png)

**Comment by MineJallerXD** [comment] 2016-01-04 16:49
I have the same problem with the purple crystal i can give me 2 more every time...now i have 24 of them :D

**Comment by ltvuong** [comment] 2016-01-05 01:13
There's a way to remove unneeded quest items.
1) Place unneeded quest items in the crafting slots in your inventory screen.
2) Fill up the rest of your inventory with other items such as emeralds or something.
3) Exit out of the inventory screen.
4) Gasp in wonder as the quest items leave your life forever (until you type /fixquests again)

**Comment by Smurfman254** [comment] 2016-01-05 03:37
You can also remove items using the daily rewards, just move any quest items into the chest screen when you open it.

**Comment by SundoWave** [comment] 2016-01-05 12:05
Thank you this was really helpful :)

**Comment by BlahBlah161616** [comment] 2016-01-05 23:55
You can remove items buy placing them into a new class then deleting that class. The daily rewards one may be a bug though.

**Comment by Gualdim-Pais** [comment] 2016-01-06 00:31
Full your inventory with one emerald, switch one emerald with the "quest item", close your inventory.. puff it's gone

**Comment by Trixter313** [comment] 2016-01-09 14:21
Duplicate of https://github.com/Wynncraft/Issues/issues/3311

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-09 14:21 UTC
