### ISSUE TITLE
didnt recieve translated writing from tesha in wynn excavation site a

### ISSUE THREAD

**Issue by icecreeper01** [Wynncraft/Issues#2177] opened 2015-08-06 15:10 UTC
Hi this happened a while ago but i got the ancient writing from vade but i gave it to tesha and never got it  back. when i talk to tesha she says to bring the translated writing to excavator vade but she did not give it to me. Please resolve this issue soon and allow me to complete the quest: wynn excavation site A

**Comment by TrashcanMan** [comment] 2015-08-06 22:31
Have you tried /fixquests yet? If that doesn't work I'm not sure what else you can do.

**Comment by icecreeper01** [comment] 2015-08-07 17:50
I just tried /fixquests but it says I have no missing items and to check my bank and all class inventories. I did that and didn't find it. I would really like to finish this quest so I can do Wynn excavation site b. Do you think you can get someone to check out my problem? My minecraft name is icecreeper01

**Comment by Trixter313** [comment] 2015-08-09 02:21
Duplicate of https://github.com/Wynncraft/Issues/issues/1415

We recommend closing the duplicate and following the original to stay up to date on the status of the issue. Thanks!

**Closed** 2015-08-17 07:08 UTC
