### ISSUE TITLE
keep getting kicked for flying

### ISSUE THREAD

**Issue by TheEpicCorgi** [Wynncraft/Issues#5592] opened 2016-07-26 23:24 UTC
everytime i return to the lobby it kicks me for flying and tries to put me in the lobby therefore the process repeats and wont stop

**Comment by Trixter313** [comment] 2016-07-27 02:41
What version of Minecraft are you using to play Wynncraft? We reccomend using 1.8.9 and using anything higher is at the users own risk. If you're using anything higher, please try using 1.8.9 and let us know if that resolves the issue. Thanks! =)

**Comment by Trixter313** [comment] 2016-07-29 08:05
Duplicate of https://github.com/Wynncraft/Issues/issues/5289

**Closed by Trixter313** 2016-07-29 08:05 UTC
