### ISSUE TITLE
UnderWater quest

### ISSUE THREAD

**Issue by kurisu-tofa** [Wynncraft/Issues#4670] opened 2016-03-27 14:38 UTC
When i finished the underwater quest. i never received the treasure boots.

**Comment by Trixter313** [comment] 2016-03-27 15:59
Hmm, because this isn't a quest item needed for future quests, there's not really much we can do due to Wynncraft no refunds policy. You can do the quest on another class if you really want the boots but other than that this seems to have just been a one time fluke glitch, possibly caused by lag, so I'll close the issue.

Thanks!

**Closed by Trixter313** 2016-03-27 15:59 UTC
