### ISSUE TITLE
"You don't have permission for this area" pop-up for unknown reason

### ISSUE THREAD

**Issue by bmarshall79** [Wynncraft/Issues#5565] opened 2016-07-24 05:54 UTC
Whenever i try to open a chest or press a button, red text in chat says 'you don't have permission for this area." I got stuck in the silverfish dungeon twice because of this. I have tried restarting my game multiple times, and obviously it didn't work.

**Comment by sammyvsparks** [comment] 2016-07-24 07:37
@bmarshall79 try using a empty hand, some weapons are retextured blocks which prevent usage due to WorldGuard mechanics.

**Comment by Moe-Ronickah** [comment] 2016-07-24 08:14
Duplicate of #3902 .  If you had searched for "you don't have permission", you would have found it.

**Closed by Moe-Ronickah** 2016-07-24 08:14 UTC
Labels: Duplicate
