### ISSUE TITLE
Slykaar Times Two

### ISSUE THREAD

**Issue by pogge5** [Wynncraft/Issues#8551] opened 2017-07-08 15:12 UTC
![2017-07-08_17 03 00](https://user-images.githubusercontent.com/29986359/27986531-4c25b770-6400-11e7-98b8-c037bd2be358.png)
![2017-07-08_17 03 04](https://user-images.githubusercontent.com/29986359/27986530-4c2510fe-6400-11e7-9e97-548b57a48b7a.png)
![2017-07-08_17 04 59](https://user-images.githubusercontent.com/29986359/27986532-4c2662d8-6400-11e7-8641-552b7a9604b9.png)
This is my 2nd trouble with this dungeon (I do it qutie alot because it is easy). When I was, in all happiness, playing around in Wynncraft, somehow two Slykaars spawned. I had to use dubble amount of my healing potions and stuff. Therefor I wish that future players will not have to experience this.

**Comment by thecoolkogut4** [comment] 2017-07-08 17:18
Duplicate of #6796

**Closed** 2017-07-11 07:44 UTC
