### ISSUE TITLE
Mess at the quest, Enter the Dojo

### ISSUE THREAD

**Issue by motoki317** [Wynncraft/Issues#5861] opened 2016-08-29 10:04 UTC
At 3rd stage, aka 3D puzzle thing one, when we complete it, door opens, but we can't enter the next stage by barrier block blocking it. -> We can't complete this quest ._.
![2016-08-29_19 03 13](https://cloud.githubusercontent.com/assets/18257693/18048140/6e3d996c-6e1b-11e6-9f3a-ce52e030e246.png)

**Comment by Trixter313** [comment] 2016-08-29 10:06
Duplicate of #5844

**Closed by Trixter313** 2016-08-29 10:06 UTC
