### ISSUE TITLE
Guild Glitch still after 2yrs

### ISSUE THREAD

**Issue by RockyPlayzMC** [Wynncraft/Issues#6603] opened 2016-11-06 05:22 UTC
Guild issue hasn't been fixed for over 2 yrs.  I have been part of wynncraft for a long time and an issue with guilds to where you chage your name and it doesn't let you leave the guild. I want to join other guilds and I need to be kicked or please disband this guild, something because I really want to enjoy the guild aspect of wynncraft. Last time I said something like this I was told deal with it and it's been 2yrs it's been long enough. PLEASE do fix this someone I want to join other guilds.

**Comment by LordHelmchen98** [comment] 2016-11-06 12:07
Duplicate of #3665
You are by far not the only one who got stuck and yes I think it has to be fixed as well, but it won't happen faster if you create more than one thread. Also it won't help if you lie or exaggerate here. You can't have this issue for over 2 years as guilds don't even exist for more than two years. Also this is your third thread about your problem. Staff is already aware of it and I hope this will be fixed soon.

**Closed** 2016-11-07 04:29 UTC
