### ISSUE TITLE
Nesaak scroll merchant scam

### ISSUE THREAD

**Issue by PearlescentMoon** [Wynncraft/Issues#6169] opened 2016-09-17 06:40 UTC
When you click to buy a Nesaak scroll from the scroll merchant in Nesaak, he takes your 1 EB, but does not give you the scroll.
This was on server 7 at the time, and 3 different players attempted it to ensure it was an actual glitch.

**Comment by Trixter313** [comment] 2016-09-17 09:35
Duplicate of https://github.com/Wynncraft/Issues/issues/6166

**Closed by Trixter313** 2016-09-17 09:35 UTC
