### ISSUE TITLE
Powders do not stack

### ISSUE THREAD

**Issue by MeGustaPotatos** [Wynncraft/Issues#7500] opened 2017-03-07 16:36 UTC
There have been certain moments when i obtain 2 or more powders, all of which have the same tier and same element, that do not stack. I noticed that they would not stack when they appear as ink sacs from mob drops, but appear as the regular powders in the inventory. I don't know if this is really considered a bug but nevertheless, please fix it. Thank you.

**Comment by Pyromanical** [comment] 2017-03-07 17:46
Duplicate of #5871

**Comment by thelasagnaman** [comment] 2017-05-06 02:18
I've seen this too, powders that are dropped my mobs are different from upgraded powders and these are both different from powders that come from chests. Why aren't they all the same?

**Closed** 2017-05-06 03:48 UTC
Labels: Duplicate
