### ISSUE TITLE
Lose items randomly if inventory full when connected

### ISSUE THREAD

**Issue by deblob123456789** [Wynncraft/Issues#5313] opened 2016-06-26 14:59 UTC
Sometimes, on connection I get a message like all my skills points were reset, desequiping all of my skill required armor, and accessories
It happens that my inventory is full at this moment, dropping these items on the ground
This time my items simply disappeared
Just lost a good Spectre and Jester bracelet
The thing is i cant get these items back and they are crucial for my build :/

**Comment by Trixter313** [comment] 2016-06-26 16:52
Duplicate of https://github.com/Wynncraft/Issues/issues/4120

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-06-26 16:52 UTC
