### ISSUE TITLE
Help? ToA floor 6 boss suicides no matter what

### ISSUE THREAD

**Issue by xElitaa** [Wynncraft/Issues#3789] opened 2016-01-20 11:55 UTC
I have seen previous issues where they have been closed on account of the person not doing constant damage, but for me the ToA floor 6 boss is totally broken! I have been damaging him over and over again, but he won't aggro on me, and even as I use spells like uppercut on me he starts his suicide spell!

**Comment by DarkDemonDragon** [comment] 2016-01-20 18:47
This is a place for bug reports. Like you mentioned this has been reported and closed because it is not a bug and is simply just really hard. It's recommended you go to the forums (forums.wynncraft.com) or a major city online and form a group. Please close this as this is an intended feature.

**Comment by Trixter313** [comment] 2016-01-20 19:06
Also, make sure you are in a decently sized group. I don't think one person can do this alone.

**Closed by Trixter313** 2016-01-20 19:06 UTC
