### ISSUE TITLE
Help! Bank Gone after Changing a new class that ive never done before

### ISSUE THREAD

**Issue by LoquaciouzSqonge** [Wynncraft/Issues#5167] opened 2016-06-05 23:46 UTC
Help! Bank Gone after Changing a new class that ive never done before
Hello Wynn Craft staff,friends,members! I am going to report a bug that today, I did /class and i selected the archer class. I was level 10 and When i changed back to my assasin class, I checked the bank, ALL OF MY ITEMS ARE GONE! Including Armor,weapons, ALOT OF EMERALDS. Please help me Wynn Craft staff , members.

IGN: LoquaciousSqonge
Date: 2016-06-05 - 5:40 (GMT -7:00)
Regards,
LoquaciouzSqonge

**Comment by Moe-Ronickah** [comment] 2016-06-06 12:26
severe duplicate of #4814 .  Please comment and follow this issue on that thread.

**Closed by Moe-Ronickah** 2016-06-06 12:26 UTC
Labels: Duplicate
