### ISSUE TITLE
Pelier- My helmet- is broken

### ISSUE THREAD

**Issue by Ron123456** [Wynncraft/Issues#4639] opened 2016-03-23 21:08 UTC
My helmet pelier( with a special character- Peliēr) is broken and when I put mosue over it, it jsut shows purple text and the helmet does nothing( adds hp, stats- basiclly broken)

**Comment by Trixter313** [comment] 2016-03-24 10:53
Duplicate of #3175 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-24 10:53 UTC
