### ISSUE TITLE
i cant join

### ISSUE THREAD

**Issue by wynncraftlupascu** [Wynncraft/Issues#3918] opened 2016-01-30 08:30 UTC
![2016-01-30_10 27 39](https://cloud.githubusercontent.com/assets/14152318/12694638/75e696c2-c73c-11e5-99c7-044b0e2dd5f2.png)

**Comment by Dar-krusos** [comment] 2016-01-30 08:39
Don't worry. Just wait a while, as there'a no need ti report a bug unless you can't get into the server for a few days.

Also, this report is an unnecessary duplicate of #3917.

**Closed** 2016-01-30 13:37 UTC
