### ISSUE TITLE
Guild leave issue

### ISSUE THREAD

**Issue by jonothanli8899** [Wynncraft/Issues#7931] opened 2017-04-19 05:20 UTC
Every time I leave my guild it takes the 3 soul points says I have left the guild and then proceeds to do absolutely nothing.

**Comment by LordHelmchen98** [comment] 2017-04-19 10:16
Duplicate of #3665
This happens because you changed your name while being in the guild. Unfortunately there is no known fix for this so you will have to be patient until guilds get fixed.

**Closed by LordHelmchen98** 2017-04-19 10:16 UTC
