### ISSUE TITLE
Can't select class

### ISSUE THREAD

**Issue by Leithal130** [Wynncraft/Issues#3835] opened 2016-01-24 05:02 UTC
Whenever I select a server it offers me the class selection then in red says "there has been an error... try again" and then offers the class select again

**Comment by Leithal130** [comment] 2016-01-24 05:11
#3250

**Comment by Trixter313** [comment] 2016-01-24 07:39
Yes, this is a duplicate of the issue linked above so please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-24 07:39 UTC
