### ISSUE TITLE
Guild bug

### ISSUE THREAD

**Issue by hvchvc4** [Wynncraft/Issues#6187] opened 2016-09-18 12:53 UTC
When I joined the guild everything was fine, but then I changed my ingame-name and then started to see the chat twice. I thought it's normal, but then I wanted to leave the guild and I couldn't. It's just spending my soulpoints and I died once from it. I told the guild leader to kick me, and it didn't work. Here's proof of what is going on.
![2016-09-18_15 46 53](https://cloud.githubusercontent.com/assets/20677030/18615766/c97b8748-7db7-11e6-830a-9687c5cfd89c.png)

**Comment by thecoolkogut4** [comment] 2016-09-18 16:35
if you change your name in a guild your stuck in it. There are lots of people in the same boat as you. In fact some people are in the guild three/four times. There is nothing you can do at the moment but wait.

**Comment by Trixter313** [comment] 2016-09-20 01:55
Duplicate of #3665 

Name changing causes many odd issues at times, especially with guilds.

**Closed by Trixter313** 2016-09-20 01:55 UTC
