### ISSUE TITLE
Not letting me Identify 

### ISSUE THREAD

**Issue by woooohooo** [Wynncraft/Issues#2456] opened 2015-10-27 00:31 UTC
Item identifier is not letting me identify a Legendary item.

![image](https://cloud.githubusercontent.com/assets/15333986/10746372/2919b30c-7c18-11e5-9ba4-b355e7e8315b.png)

**Comment by TrashcanMan** [comment] 2015-10-27 03:32
Known issue, most items with special (accented) characters, as well as the Relic Dagger, don't identify properly.

**Comment by Trixter313** [comment] 2015-10-30 02:02
As TrashcanMan said, duplicate of https://github.com/Wynncraft/Issues/issues/1312

We recommend closing this issue and following the original to stay updated on the status of the issue. Thanks!

**Closed** 2015-12-25 20:39 UTC
