### ISSUE TITLE
One of my classes doesnt work

### ISSUE THREAD

**Issue by DajelWynn** [Wynncraft/Issues#7758] opened 2017-04-09 10:02 UTC
I tried to log in my archer class but it doesnt work, I tried it the next day, still doesnt work, next day, still doesnt work. Have any idea what this could be?  (my IGN is Dajel)

Here is a video of it: https://youtu.be/VWKE2ZJjObk

**Comment by DPlayer234** [comment] 2017-04-09 12:09
I have the exact same issue, so it's not just an isolated case... The only difference is that my hunter doesn't work.
Something else that I noticed was that I did have _autojoin enabled_ and that the _hunter_ was the last class I used. Just mentioning it in case it might be relevant.
(IGN: DPlay)

**Comment by ColinRioux** [comment] 2017-04-09 19:04
Duplicate of #7680. Please see there for future information.

**Closed by ColinRioux** 2017-04-09 19:04 UTC
