### ISSUE TITLE
relic daggers

### ISSUE THREAD

**Issue by SteveClinton** [Wynncraft/Issues#2551] opened 2015-11-24 13:02 UTC
Is it normal that i cant indentiefie my relic daggers?

**Comment by DarkDemonDragon** [comment] 2015-11-24 13:08
Duplicate of #1312 please close this thread and follow that one.

**Comment by SteveClinton** [comment] 2015-11-24 13:21
pls i just need help i already find new ones but i cant indentifie them too -.-

**Comment by DarkDemonDragon** [comment] 2015-11-24 13:36
@SteveClinton read #1312 this is a bug that occurs on items with special characters and the Relic Dagger. They can't be IDed for some reason, so yes this is sort of normal as NO ONE can ID a Relic Dagger at the moment. This may be fixed in the future.

**Comment by SteveClinton** [comment] 2015-11-24 13:39
hm :/ the relic wand and bow can be indentified

**Comment by DarkDemonDragon** [comment] 2015-11-24 18:47
I never said anything about the other relics. For some strange bug reason the Relic DAGGER cannot be IDed. Other relics SHOULD be fine. Read #1312

**Comment by DarkDemonDragon** [comment] 2015-11-26 19:53
Please close this issue as this is a duplicate of #1312

**Closed** 2015-12-25 20:38 UTC
