### ISSUE TITLE
Weapon skill points not applying

### ISSUE THREAD

**Issue by TrashcanMan** [Wynncraft/Issues#3929] opened 2016-01-31 05:04 UTC
My wand currently gives me +5 Strength and +5 Intelligence, but neither appears to be applied when I check the Character menu, and Strength doesn't say "modified by equipment" (Intelligence has the "modified by equipment" message because my armor also gives Intelligence boosts).
![2016-01-30_21 00 44](https://cloud.githubusercontent.com/assets/6947594/12700388/f024a3f4-c794-11e5-8f87-1a348a31bf42.png)
![2016-01-30_21 00 46](https://cloud.githubusercontent.com/assets/6947594/12700389/f0279ce4-c794-11e5-8b79-540a78710a37.png)

**Comment by Dar-krusos** [comment] 2016-01-31 05:43
Try changing servers, as this usually updates it.

**Comment by Trixter313** [comment] 2016-01-31 16:42
Also someone noticed that you have to be holding the wand to receive the perks so by selecting the compass, it would most likely be removing the perks.

**Comment by TrashcanMan** [comment] 2016-01-31 20:29
Alright, thanks @Trixter313. Should I leave this one open since it's still sort of an issue?

**Comment by Trixter313** [comment] 2016-01-31 20:37
I'm not sure. Maybe close the issue and make a thread in the suggestions area or the forums suggesting that they make the weapon in the first hotbar slot always apply it's perks, even when not selected? It's up to you.

**Comment by Dar-krusos** [comment] 2016-02-01 05:23
> Also someone noticed that you have to be holding the wand to receive the perks so by selecting the 
> compass, it would most likely be removing the perks.
> - Trixter313

This is not entirely true, to what I've seen. Again, I think this is only due to lag, as some servers update while others don't. I tested this by putting two weapons in the hotbar and checked the compass after changing between the two (making sure not to hover over the weapon I did not want to view the stats on). As intended, the compass' stats updated, so this bug is either a weapon-specific problem or a result of lag.

**Comment by Moe-Ronickah** [comment] 2016-02-06 14:49
I don't believe that it is weapon-specific, and if it is, it affects a lot of weapons on various classes.

Rather than changing servers, which does work, there are at least three other options that you can try.
You can try opening the /class menu, and going back to your problem class.
You can try changing classes, then going back.
You can try attacking anything.  It doesn't matter what it is, as the game updates to whatever weapon was last used.

**Comment by TrashcanMan** [comment] 2016-02-08 05:15
I've confirmed that it's not just a visual issue, it's actually affecting gameplay.
My wand gives +5 strength.
![2016-02-07_21 08 30](https://cloud.githubusercontent.com/assets/6947594/12878835/ac279926-cddf-11e5-82c8-56709f958af2.png)
I have put 26 skill points into strength, so I should have a total of 31. The menu still displays 26.
![2016-02-07_21 08 36](https://cloud.githubusercontent.com/assets/6947594/12878837/ac2976ce-cddf-11e5-9886-5b79ad2642ce.png)
The StoneWall chestplate has a strength requirement of 30, so I should be able to wear it, but I can't.
![2016-02-07_21 12 28](https://cloud.githubusercontent.com/assets/6947594/12878836/ac27eb74-cddf-11e5-8e76-de807b39a67f.png)
So I'm pretty sure the skill point bonuses from my weapon aren't applying.

**Comment by Dar-krusos** [comment] 2016-02-08 05:24
You shouldn't rely on accessory and/or weapon stat bonuses. They are unreliable and work at random times (for now, maybe).

**Comment by TrashcanMan** [comment] 2016-02-08 07:09
;-;
But that chestplate is so good...

**Comment by DarkDemonDragon** [comment] 2016-03-06 15:57
Hey guys I explain why this happens in this video:
https://www.youtube.com/watch?v=P8MZxhy_3bc

**Comment by Moe-Ronickah** [comment] 2016-05-27 03:30
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.

**Closed by Moe-Ronickah** 2016-05-27 03:30 UTC
Labels: Game Mechanics

**Comment by DarkDemonDragon** [comment] 2016-05-29 13:32
@Moe-Ronickah I already found out what was going on in the video (https://www.youtube.com/watch?v=P8MZxhy_3bc) I mentioned. Basically weapons don't apply their effects the EXACT moment you stop holding them such as using a wand and then switching to a potion. If you need 30 STR and you are at 25, but your wand gives you +5, the moment you try to drink a potion, place a horse, or anything that would change the item in your hand from a wand to something else then you would lose the +5 immediately and the armor would pop off.
