### ISSUE TITLE
Purple And Blue Magical Fragment

### ISSUE THREAD

**Issue by CiPCheech** [Wynncraft/Issues#4281] opened 2016-02-25 22:43 UTC
I'm in the last room in the lake and I know that's where you get the magical fragments but their not dropping naturally or dropping from the mobs please help!

**Comment by Odnod** [comment] 2016-02-25 23:04
Duplicate of #4236, please close this issue and direct any additional comments to the original thread. This issue is very well known and it is being worked on.

**Comment by CiPCheech** [comment] 2016-02-26 00:09
they are not the same at all

**Comment by Odnod** [comment] 2016-02-26 00:27
@CiPCheech they are exactly the same. Issue #4236 was the first one posted about items drops not spawning for quests.

**Closed** 2016-02-26 01:43 UTC
