### ISSUE TITLE
Jungle Fever Quest LE Glitch. Lost LE

### ISSUE THREAD

**Issue by Yotam4** [Wynncraft/Issues#6342] opened 2016-10-06 12:21 UTC
So basiclly after I finished the quest, I wanted to see what he said.
And my LE vanished.
I red about the glitch afterwards and saw that if you right click him with real ones he may take them, but even so it shoulden't happen AFTER I finished it. 
I'd like to get an LE back if I can.
Thank you.
-Yotam4.

**Comment by LordHelmchen98** [comment] 2016-10-06 12:25
Wynncraft has a strict norefund-policy. You wont get back any item.
Also this is a duplicate of #2703

**Comment by Yotam4** [comment] 2016-10-06 12:29
Alright. Didn't know also

**Comment by Imaxe** [comment] 2016-10-07 22:14
Its not a bug with that NPC
Its a bug where you can accidently throw a LE like a enchanted bottle. Its when your internet connection isnt the best.
And yea, norefund.

**Closed by Imaxe** 2016-10-07 22:14 UTC
