### ISSUE TITLE
Horse glitch

### ISSUE THREAD

**Issue by TheKingOfAnimals** [Wynncraft/Issues#4566] opened 2016-03-16 21:19 UTC
When I try to out my horse on the floor, it appears for a tiny amount of time and then disappears again, also, when I get off it, it teleports me about 15 blocks from where I previously was!

**Comment by Odnod** [comment] 2016-03-16 21:38
What version of Minecraft are you running?

**Comment by DarkDemonDragon** [comment] 2016-03-17 12:24
Duplicate of #4524 Please close this and follow the original

**Closed** 2016-03-17 16:03 UTC
