### ISSUE TITLE
Specific armor not identifying

### ISSUE THREAD

**Issue by CraterHater** [Wynncraft/Issues#2265] opened 2015-08-31 11:04 UTC
I was walking trough detlas and a guy asked me to help him identifying, I thought it was another noob not knowing how to do it but he gave me his Legendary helmet and I couldn't identify it either it said the normal message that he is afraid he can't identify the armor but it was legendary so that's weird. Here are some screenshots:
![2015-08-31_13 00 31](https://cloud.githubusercontent.com/assets/13470271/9577413/c9e316ca-4fe0-11e5-9d33-fe80276352c6.png)

**Comment by Trixter313** [comment] 2015-08-31 11:09
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

We recommend closing the duplicate and following the original to stay up to date on the status of the issue. Thanks!

**Closed** 2015-12-25 20:40 UTC
