### ISSUE TITLE
Mission EXP Glitch

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#4537] opened 2016-03-12 19:38 UTC
If you have a mission that says it will give you for example 550 exp it turns out to only give you half of it. (225 exp). I find this kinda annoying and I hope that someone knows how to fix this.

Thanks.

- Nothing

**Comment by DarkDemonDragon** [comment] 2016-03-12 22:20
Duplicate of #1789 Please close this and follow the original
@Moe-Ronickah looks like it's still happening

**Closed** 2016-03-15 06:42 UTC
