### ISSUE TITLE
Glitch Quest ("Green Skinned Trouble")

### ISSUE THREAD

**Issue by TheDWPCer** [Wynncraft/Issues#7388] opened 2017-02-17 07:23 UTC
There is a glitch with the puzzle on stage 4 of the quest above... the bug is where if you complete the puzzle and go down the hole, it says "null" and tp's you up back again...
I know what null mean in java "java.lang.NullPointerExpition" but I have never gotten just "null"
I know only the Devs can fix it.

**Comment by DebugMC** [comment] 2017-02-17 14:24
@AscendedKitten knows about this i think

**Comment by ColinRioux** [comment] 2017-02-18 04:36
Duplicate of #6820

**Closed by ColinRioux** 2017-02-18 04:36 UTC
