### ISSUE TITLE
lost my items

### ISSUE THREAD

**Issue by budderfactory** [Wynncraft/Issues#5296] opened 2016-06-24 01:40 UTC
.
im not sure why this happened but I randomly lost my bracelet and 3 pieces of armor after the server restarted when I was afk from taking my dog out side and when I got back I just didn't have my 3 piece of rare armor and I don't know what happened it just disappeared now I cant get it back im not sure I can get this stuff  back as I don't have screenshots of my stuff but help If you can

**Comment by YunoFGasai** [comment] 2016-06-24 06:10
Was your fourth piece of armor a quest item/untradeable?

**Comment by budderfactory** [comment] 2016-06-24 17:19
yeah

**Comment by budderfactory** [comment] 2016-06-24 17:20
ONI helm

**Comment by budderfactory** [comment] 2016-06-24 20:57
it was so don't know what happened

**Comment by budderfactory** [comment] 2016-06-24 23:11
why did you need to know that it was  a untradable

**Comment by YunoFGasai** [comment] 2016-06-25 07:34
you probably afk'd in an unsafe place and some mobs wandered in and killed you over and over again until you dropped all of your stuff.
I'm sorry but we cant refund you your items back.
next time when you afk do it inside a house after you close the door and go up a ladder or some stairs.

**Comment by budderfactory** [comment] 2016-06-25 13:32
I didn't die I had all my other stuff that was in my inventory I also didn't move from were I afked and still had the same soul points :P and I had my emerald gold ingots my horse everything just not my armour

**Comment by YunoFGasai** [comment] 2016-06-25 14:04
was you inventory full?

**Comment by YunoFGasai** [comment] 2016-06-25 14:04
your*

**Comment by budderfactory** [comment] 2016-06-25 22:52
yeah it was

**Comment by Moe-Ronickah** [comment] 2016-06-26 00:51
Duplicate of #3153 .  Please follow the discussion of this issue, there.

**Closed by Moe-Ronickah** 2016-06-26 00:51 UTC
Labels: Duplicate
