### ISSUE TITLE
NEW (?) Bow Issue?

### ISSUE THREAD

**Issue by ZeUnlucky** [Wynncraft/Issues#8264] opened 2017-05-29 17:43 UTC
Welp, whenever I right click ANY block, and I mean any block, even buttons, with my bow, it says "You don't have permissions to do that here" as if Im trying to edit land, never happened before now, but It's kinda annoying to see and to have to switch to my horse saddle in order to press a simple button...
![2017-05-29_20 33 45](https://cloud.githubusercontent.com/assets/28901862/26558173/72f6800c-44af-11e7-8a46-e479870992fd.png)

**Comment by thecoolkogut4** [comment] 2017-05-29 17:45
Hey there!

This is because the item you were using is a retextured half-slab, and the game thinks you were trying to place it as a result it says you don't have permission to. To fix this right click with an empty hand or your soul point.

Duplicate of #3902

Goodluck.

**Closed** 2017-05-29 21:45 UTC
