### ISSUE TITLE
Missing Merchants

### ISSUE THREAD

**Issue by jgja1** [Wynncraft/Issues#2928] opened 2015-12-23 03:42 UTC
Since the update, the Boat Merchants at Selchar and Nesaak along with the Key Merchant for the Zombie Dungeon in Saints Row is missing.

**Comment by Trixter313** [comment] 2015-12-23 04:35
Duplicate of #2782 I believe.

We recommend closing the duplicate and adding any comments to the original to stay updated on the status of the issue and keep things as uncluttered as possible. Thanks!

**Closed** 2015-12-25 20:33 UTC
