### ISSUE TITLE
Guild leaving bug

### ISSUE THREAD

**Issue by RockyPlayzMC** [Wynncraft/Issues#4320] opened 2016-02-27 22:17 UTC
My username is RockyPlayzMC and km trying to create my own guild but I'm stuck in a guild and when I do /guild leave and type yes it takes my soils but doesn't kick me from guild these members don't play anymore and I want to create my own please fix this.

**Comment by Trixter313** [comment] 2016-02-28 18:49
Is the issue still occurring? Sometimes it just takes a little time for the removal to update.

**Comment by RockyPlayzMC** [comment] 2016-02-29 01:44
No I'm still in the guild

**Comment by RockyPlayzMC** [comment] 2016-02-29 01:44
Still in guild and it took my souls

**Comment by ChiefInferno** [comment] 2016-03-06 03:32
for me I think it was because of a name change ive been trying to leave my guild for months

**Comment by RockyPlayzMC** [comment] 2016-03-18 05:38
Bye the way is this Goin to be fixed soon because I want to join my friends or make my own guild. And I just want to thank the staff team recently with all the bugs, they have all been working very hard especially with the items despawning now that it's fixed. Cheers :D

**Comment by Trixter313** [comment] 2016-04-05 04:50
I see that you've changed your name in the past, meaning this is most likely a duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-05 04:50 UTC
