### ISSUE TITLE
Lost my armour

### ISSUE THREAD

**Issue by Anwon** [Wynncraft/Issues#3994] opened 2016-02-06 14:49 UTC
Hi, today when I logged into wynncraft, and i noticed there was a new update, i tried to click my armour but then they disappeared :( and im kinda mad becouse those were really valuable level 60 armour :I

**Comment by Moe-Ronickah** [comment] 2016-02-06 15:09
Is this the first time that you have been on servers since the Gavel update?  If so, then you probably had not read the announcements on the forums about the update, about leaving the first four inventory slots open because they were being re-purposed, and you did not move your armor into four slots in your in-game inventory.  If this is what happened, then you lost your armor due to the change in the game mechanics, and a bug that currently is causing dropped items to disappear.  Please let us know a little more about how you lost your items.

**Comment by Trixter313** [comment] 2016-02-09 16:04
Yes, I believe this is a duplicate of https://github.com/Wynncraft/Issues/issues/3153

Unfortunately we can't refund any lost armor but we are really hoping the admins will be able to fix the issue soon. If you ask around some nice people will probably give you some armor and pretty soon you should have armor even better than what you lost. Hopefully this isn't too much of an inconvenience!

**Closed by Trixter313** 2016-02-09 16:04 UTC

**Comment by Anwon** [comment] 2016-02-09 17:47
I logged in and i let the texture pack install itself, after that i saw my armors were weird shield looking things, i tried to took off my chestplate, then the screen said something about loading resource pack and all my armors were gone :c

**Comment by Anwon** [comment] 2016-02-09 17:48
And i tried to ask for armor but people are not even nice enough to trade armors :(

**Comment by Trixter313** [comment] 2016-02-09 17:53
Was your inventory full at the time?

**Comment by Anwon** [comment] 2016-02-09 18:03
Yes it was

**Comment by Trixter313** [comment] 2016-02-09 18:15
Then this would definitely be a duplicate of issue 3153, linked above. Try switching worlds a bit and hopefully soon someone will give you some armor.
