### ISSUE TITLE
A Grave Mistake

### ISSUE THREAD

**Issue by boredarchon** [Wynncraft/Issues#6484] opened 2016-10-28 05:37 UTC
While I was doing A Grave Mistake quest, the quest stuck while watching in game cinematic. I cannot move or escape even cinematic has ended. I am stuck in the air.

**Comment by MrRedCrack** [comment] 2016-10-28 06:58
I have reported this a while ago.

**Comment by Trixter313** [comment] 2016-10-28 10:46
Duplicate of https://github.com/Wynncraft/Issues/issues/6480

**Closed by Trixter313** 2016-10-28 10:46 UTC
