### ISSUE TITLE
Unable to connect to any server/You are already logged in

### ISSUE THREAD

**Issue by GLaDOSkiller** [Wynncraft/Issues#2167] opened 2015-08-04 19:10 UTC
This problem began after Server 10 did a restart around 6pm GMT. Attempting to reconnect to server 10 or 5 gives this error:
![2015-08-04_20 06 11](https://cloud.githubusercontent.com/assets/13647917/9069964/841c72f0-3ae4-11e5-9959-9af05b8063d2.png)

Trying any other server gives this error
![2015-08-04_20 08 58](https://cloud.githubusercontent.com/assets/13647917/9069982/aa4a3dea-3ae4-11e5-99dc-94570927affa.png)

I believe that server 10 thinks I'm still logged in not allowing me to connect. Ziggeh2 reports similar activity on his end. I have done a full comp restart to no avail. Can you please discover this error's problem and fix it please.

**Comment by Trixter313** [comment] 2015-08-04 20:19
Duplicate of https://github.com/Wynncraft/Issues/issues/2166

**Comment by GLaDOSkiller** [comment] 2015-08-04 20:35
1) the reason for the dupe is my comp restarted the second i pressed submit
2) Yes, this is still happening

**Comment by GLaDOSkiller** [comment] 2015-08-04 20:36
*Edit, It's of and on, thanks for the suggestion

**Comment by Trixter313** [comment] 2015-08-04 20:38
Are you saying your issue is fixed now? =D

**Comment by GLaDOSkiller** [comment] 2015-08-04 20:39
for the most part, yes

**Comment by Trixter313** [comment] 2015-08-04 20:45
If your issue is now resolved, we'd appreciate it if you closed this and the duplicate issue ( https://github.com/Wynncraft/Issues/issues/2166 ). If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Closed** 2015-08-04 20:55 UTC
