### ISSUE TITLE
Weapon Glitch & weird lore.

### ISSUE THREAD

**Issue by Vehico** [Wynncraft/Issues#4329] opened 2016-02-28 07:35 UTC
My main wand, Devoreuse, had randomly broken one day whilst I was lagging, so I took a break and when I logged back on, my weapon name was no longer coloured, & the lore was completely broken.

![memed](https://cloud.githubusercontent.com/assets/16617927/13378049/f304d02c-ddaa-11e5-82ba-8d7e809c2e79.png)

**Comment by Trixter313** [comment] 2016-02-28 19:07
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-28 19:07 UTC
