### ISSUE TITLE
animal dungeon boss fight warrior bug

### ISSUE THREAD

**Issue by ameliawrites** [Wynncraft/Issues#4676] opened 2016-03-27 18:27 UTC
im not entirely sure that this is a bug but just in case im posting here. In the animal dungeon boss room as a warrior if you get the boss in one of the corners and use war scream on him he will fly out of the arena and be untouchable by most attacks. If you try and walk to the other side of the arena to lure him back in he will not be able to enter back through the invisible wall meaning that you will have to go back  to the hub and rejoin one of the servers, putting you back at the entrance of the dungeon. i took a couple of screenshots for proof. hopefully this can be fixed soon. 

![2016-03-27_14 01 04](https://cloud.githubusercontent.com/assets/18103389/14066995/e15beb60-f427-11e5-9330-cdb1dbbb50ae.png)

![2016-03-27_14 03 02](https://cloud.githubusercontent.com/assets/18103389/14067000/f5070302-f427-11e5-8a45-9e63c6ecdd7c.png)

![2016-03-27_14 02 58](https://cloud.githubusercontent.com/assets/18103389/14066998/eefa87d6-f427-11e5-805c-253c8ad88f30.png)

![2016-03-27_14 02 54](https://cloud.githubusercontent.com/assets/18103389/14066997/e9bbba4c-f427-11e5-90dc-a6803348f1ea.png)

**Comment by TrashcanMan** [comment] 2016-03-28 02:28
Duplicate of #3191

**Closed** 2016-03-28 02:29 UTC
