### ISSUE TITLE
I still do not get bobs lost soul by write /fixquest plz help!!!!!!!!!!!

### ISSUE THREAD

**Issue by snowminer22** [Wynncraft/Issues#3504] opened 2016-01-03 13:56 UTC
If i do not get bobs soul I cant do tempel of legens
![wynncraft bugg](https://cloud.githubusercontent.com/assets/16511179/12079029/147a47f2-b22a-11e5-82e5-9f6fdfaac0f4.PNG)
![2016-01-03_14 53 25](https://cloud.githubusercontent.com/assets/16511179/12079032/2a03b306-b22a-11e5-81ce-d0f369c57e04.png)
![2016-01-03_14 53 34](https://cloud.githubusercontent.com/assets/16511179/12079033/2dd73ade-b22a-11e5-8d6f-94ae04b375ee.png)

**Comment by Trixter313** [comment] 2016-01-03 21:32
Duplicate of https://github.com/Wynncraft/Issues/issues/3438

Please just add comments to your original thread instead of opening another. Thanks!

**Closed by Trixter313** 2016-01-03 21:32 UTC
