### ISSUE TITLE
Life/Mana steal wont working

### ISSUE THREAD

**Issue by Equipa2** [Wynncraft/Issues#4227] opened 2016-02-22 23:17 UTC
Im a archer lvl.84 and i have 61/2s life steal and 1/2s mana steal, but when is use a arrow strom nothing appens.
Equipa2

**Comment by Odnod** [comment] 2016-02-22 23:33
Life and Mana steal no longer steal per 2 seconds but rather on a percent chance based on attack speed.

**Comment by DarkDemonDragon** [comment] 2016-03-01 18:01
Please close this as this is not a bug, but an intentional feature of the game.

**Closed** 2016-05-05 10:40 UTC
