### ISSUE TITLE
Lost items, had full soul points, please help.

### ISSUE THREAD

**Issue by Zytaria** [Wynncraft/Issues#4499] opened 2016-03-08 06:49 UTC
I was doing the quest Lord of the Clock and had just entered the hidden library when the server underwent a restart. I returned to the lobby from server seven with seven minutes to spare and logged back onto server nine. I found my helmet in my inventory and my pants and shoes completely missing. I had legendary level pants, unfortunately I can't remember the name, and decent shoes. I am an Assassin level thirty-one. Any assitance would be greatly appreciated, thank you.

**Comment by Trixter313** [comment] 2016-03-08 12:21
Duplicate of #4120 

Please direct any future comments to the original thread. Thanks! =)

**Closed by Trixter313** 2016-03-08 12:21 UTC
