### ISSUE TITLE
Donkey glitch

### ISSUE THREAD

**Issue by Apocrophon** [Wynncraft/Issues#8108] opened 2017-05-10 04:33 UTC
I was getting chests on Corkus when upon my spawning in my 16/25 Black horse, it instead spawned in a donkey @_@
It was significantly slower and jump height was less, but it did change back after I respawned it.

http://prntscr.com/f628ff

**Comment by ittnoraA** [comment] 2017-05-10 04:57
This is only a visual bug occurring in higher versions of minecraft, so it shouldn't affect speed or jump height.

**Comment by Trixter313** [comment] 2017-05-10 23:10
Duplicate of https://github.com/Wynncraft/Issues/issues/7060

**Closed by Trixter313** 2017-05-10 23:10 UTC
Labels: Duplicate

**Comment by Apocrophon** [comment] 2017-05-11 00:16
*and it happened again just now
