### ISSUE TITLE
selchar hourglass problem

### ISSUE THREAD

**Issue by Reedscraft** [Wynncraft/Issues#4432] opened 2016-03-04 13:03 UTC
I am trying to do the quest where you go to selchar and get the sand, but the sand isn't spawning. please help!

**Comment by Odnod** [comment] 2016-03-04 16:20
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-05 05:27 UTC
Labels: Duplicate
