### ISSUE TITLE
My Guild, ZephyWrath, is broken. 

### ISSUE THREAD

**Issue by NestedZephyr** [Wynncraft/Issues#7016] opened 2016-12-27 11:50 UTC
Every time i send a message or see a message it appears twice, Me and two other people are on the /guild list twice, and i am unable to kick the aforementioned doubles, and i have tried kicking them like 50 times. I attempted to add someone and it simply didn't work for about 10-15 minutes.

**Comment by LordHelmchen98** [comment] 2016-12-27 14:32
Duplicate of #3665
You are shown twice because you changed your name while being in the guild. Unfortunately there is no known solution for this so far so you have to be patient and wait until guilds get fixed.

**Closed** 2016-12-28 00:46 UTC
