### ISSUE TITLE
Identified spear of an old version

### ISSUE THREAD

**Issue by Vanderwan** [Wynncraft/Issues#4668] opened 2016-03-27 12:09 UTC
I'm a former player of Wynncraft. I stopped playing Minecraft for more than 1 year. But I wanted to play again on this beautiful server so I came back.
When I logged in for the first time since 1 year, I discovered that my old warrior character was still there. His inventory and enderchest was full of unidentified items, except one...
This one is a spear named "Fierté" and as you can see on the [screen](http://image.noelshack.com/fichiers/2016/12/1459080342-2016-03-27-13-22-33.png) she is unusable. I saw on the website that she still exists so I want it back please.
![2016-03-27_13 22 33](https://cloud.githubusercontent.com/assets/18099279/14065312/288c3bd2-f425-11e5-9614-c88407089983.png)

**Comment by DarkDemonDragon** [comment] 2016-03-27 13:26
Duplicate of #3161 The accent in item names causes them to break and not be compatible with the system. Unfortunately support for this has been dropped and the recommended thing to do is either throw it away or sell it as a collectible. If you need a weapon feel free to ask around in Detlas or on the forums, but the Wynncraft staff cannot give you anything as Wynncraft has a strict no-refunds policy.

**Closed** 2016-03-27 14:28 UTC
