### ISSUE TITLE
guild xp bug

### ISSUE THREAD

**Issue by stazrocks** [Wynncraft/Issues#2178] opened 2015-08-07 02:32 UTC
my guild have all put there /xp to 100 and where not earning xp for the guild it says we are but it does not update we should be like lvl 5 but were lvl 1 we have beat dungeons too our guild is royaldragons help us.

**Comment by Trixter313** [comment] 2015-08-07 23:10
Duplicate of https://github.com/Wynncraft/Issues/issues/2074

We recommend closing the duplicate and following the original to stay up to date on the status of the issue. Thank you!

**Closed** 2015-08-17 07:08 UTC
