### ISSUE TITLE
I cannot leave guild

### ISSUE THREAD

**Issue by UltimateScrubExE** [Wynncraft/Issues#5728] opened 2016-08-13 10:30 UTC
I tried to do /guild leave to leave my current guild, after i following the instructions which are typing yes in the sign. i left the guild. The message also says i have left the guild for twice. However when i press tab i am still in the guild. If i try to leave again, it keeps removing my souls. i can't create a guild pls help

**Comment by Trixter313** [comment] 2016-08-13 19:16
I see that you've changed your Minecraft username before, meaning this is a duplicate of #3665 

We don't currently have a fix but we are working on resolving the issue.

**Closed by Trixter313** 2016-08-13 19:16 UTC
