### ISSUE TITLE
Unidentificable rare / legendary items

### ISSUE THREAD

**Issue by Bloodpearl969** [Wynncraft/Issues#2646] opened 2015-12-17 15:51 UTC
Hello. A few days ago i tried to identify my relic daggers ( legendary lvl 65 shears ) and it says that " only unique rare or legendary items can be identified " but it is legendary .. 
I had the same problem on my knight with a lvl 66 rare spear called Ik-El-Vän , it said exactly the same thing
Thanks for reading this issue and i hope this will be solved

**Comment by DarkDemonDragon** [comment] 2015-12-17 18:42
Duplicate of #1312 please close this issue as any updates on the situation will be on there. This bug is expected to be fixed when Gavel is released (about 3 more days). There is a button on the bottom to close this issue.

**Closed** 2015-12-25 03:29 UTC
