### ISSUE TITLE
Full armor gone and didnt drop on the ground!

### ISSUE THREAD

**Issue by SirQuantumNarwal** [Wynncraft/Issues#7148] opened 2017-01-11 16:23 UTC
I was on server one wynncraft and i took my hive boots and helmet soul signal and dark channeler off outside of detlas' bank and when i went into the bank my armor was gone completly out of my inventory
Please fix this this glich also happened to my best friend a while ago and he lost hive boots and leggings please either fix this glich or help me get the items back.
My IGN is SirQuantumNarwal

**Comment by SirQuantumNarwal** [comment] 2017-01-11 16:28
After i submitted this i noticed my inventory was also acting weird then i shift clicked my armor off of my body and it went into my accesorie slots so i got a screenshot  
i will attach it
![glich](https://cloud.githubusercontent.com/assets/20782561/21856733/06645bce-d7f1-11e6-9d50-b3bc2a168c7d.png)

**Comment by SirQuantumNarwal** [comment] 2017-01-11 18:09
This was a bug although it was fixed somehow im not sure ( ͡° ͜ʖ ͡°)

**Comment by DebugingLonks** [comment] 2017-01-11 20:11
Duplicate of one of @Moe-Ronickah 's issues xD not saying that to close issue, keep it open. It needs fixed as old one never was

**Comment by DebugingLonks** [comment] 2017-01-11 20:11
Its forcing items into slots that shouldn't exist btw and nvm its not a dupe.

**Comment by DragonEngineer** [comment] 2017-01-12 00:33
This issue happened to me before. Everything just disappeared from my armour slot. I wanted to quit wynncraft at that point. Hopefully it doesn't happen to me or anyone else

**Comment by DebugMC** [comment] 2017-01-12 20:28
However you will not get items back. Please read #4120 I believe this is related.

**Comment by AscendedKitten** [comment] 2017-01-23 08:29
I am sorry for the inconvenience, but due to the no-refund policy your items can't be returned. 
Also, possible duplicate of #4120

**Closed by AscendedKitten** 2017-01-23 08:29 UTC
