### ISSUE TITLE
All quests that require you to pick blocks off the ground

### ISSUE THREAD

**Issue by RMH0131** [Wynncraft/Issues#4442] opened 2016-03-04 23:17 UTC
Sister city, you must pick sand off the ground.
Wynn excavation Site B you must pick up purple blocks from the ground.
Canyon Condor you must pick gold up off the ground.

the problem is that all quests requiring you to pick something off the ground is broken. please fix this cuz I just want to get these quests over with. I had Canyon Condor for a week now and just made it to the purple block room of Excavation Site B. It's getting annoying, so please when you can. thx :D

**Comment by Odnod** [comment] 2016-03-04 23:38
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Comment by Moe-Ronickah** [comment] 2016-03-05 05:24
Please learn to use the search function on the github, as described on the first page.  Thanks!

**Closed by Moe-Ronickah** 2016-03-05 05:24 UTC
