### ISSUE TITLE
XP Gain

### ISSUE THREAD

**Issue by CraftLord951123** [Wynncraft/Issues#3239] opened 2015-12-27 17:19 UTC
Hello, not sure if it is a bug or not yet I am going to report it anyways just in case. I completed the Death Whistle quest and it said I got 100,000 xp and it leveled me up once. I then complete The Worm Holes and got 175,000 and leveled up almost 10 times(55 1/2 to 64 9/10). I think there is a problem with that. Maybe it is not  a glitch but I thought to report it because it seems strange. Thank you.

**Comment by Trixter313** [comment] 2015-12-29 21:42
When did you do the quests? It's possible that when you did the first one it was regular XP but when you did the second one there was double XP happening. Especially with the server-wide double XP, if there was an XP bomb also in effect, that's 4x XP.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by DarkDemonDragon** [comment] 2016-01-07 18:46
This is not a bug and is why veterans complete quests when there is a xp bomb active.

**Comment by Trixter313** [comment] 2016-01-10 16:37
I'm guessing your issue is now resolved due to no response. Have a great day!

**Closed by Trixter313** 2016-01-10 16:37 UTC
