### ISSUE TITLE
Animal key's key merchant gone

### ISSUE THREAD

**Issue by Heatdude** [Wynncraft/Issues#2872] opened 2015-12-22 16:24 UTC
My friend and I have recently gotten into Wynncraft and were doing some dungeons together. We went to get keys for the animal dungeon, but when we got to the coords listed on the wynncraft wiki he wasn't there. We looked around of course, but he wasn't anywhere that we looked.
Screenshot of coords: http://i.imgur.com/eQ1J9Di.png
Where the merchant is supposed to be: http://i.imgur.com/AWQvt7U.png
Thanks for reading.

**Comment by Trixter313** [comment] 2015-12-23 02:37
Duplicate of #2782 .
We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!

**Closed** 2015-12-23 17:29 UTC
