### ISSUE TITLE
Resource Pack failing on 1.9

### ISSUE THREAD

**Issue by bobotje** [Wynncraft/Issues#5343] opened 2016-06-29 12:26 UTC
I recently went from 1.8 to 1.9 and I came across resource errors.

http://i.bobotje.com/dFz4FF.png

I hope the resource pack will be fixed for 1.9 soon :)

Sincerely
bobotje

**Comment by Trixter313** [comment] 2016-06-29 12:42
Are you using any mods or have forge loaded?

**Comment by bobotje** [comment] 2016-06-29 12:45
I was indeed using forge. But I don't have any mods that changes textures. I'm using optifine though but still I don't believe this will make textures go away because I also used it on 1.8.9 forge.

**Comment by Trixter313** [comment] 2016-06-29 12:48
This is a duplicate of https://github.com/Wynncraft/Issues/issues/5057 then.

It's something they changed in forge 1.9 that causes this.

As of right now, we reccomend using 1.8 anyway and using anything higher is at your own risk.

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-06-29 12:48 UTC
