### ISSUE TITLE
/forum not working and im VIP+

### ISSUE THREAD

**Issue by osher16** [Wynncraft/Issues#5485] opened 2016-07-14 12:32 UTC
what the title says

just please fix it :D

**Comment by ThunderRemix** [comment] 2016-07-14 14:32
Already known since forever...

**Comment by sammyvsparks** [comment] 2016-07-14 20:28
@osher16 Duplicate of https://github.com/Wynncraft/Issues/issues/3268 ; Doesn't contain any information currently though.

**Closed** 2016-07-14 22:45 UTC
Labels: Duplicate
