### ISSUE TITLE
Lossing health

### ISSUE THREAD

**Issue by Battlegrround** [Wynncraft/Issues#5265] opened 2016-06-19 10:47 UTC
I keep on losing health for no reason, I have no idea why its happening, I think I am not the only one as well. Every time I do a boss battle I get killed because half way before I get to him, I have lost all my health just by walking. please to any moderators who read this, fix it, I don't like buying more potions of health. D:  

-Digger_louis

**Comment by YunoFGasai** [comment] 2016-06-19 10:49
you probably have a negative health regen id on your armor

**Comment by Moe-Ronickah** [comment] 2016-06-20 13:45
Duplicate of #2709.  If you had searched for "losing health", you would have found it.
There have also been a few of these on the forums.
Welcome to the GitHub, Battlegrround.

**Closed** 2016-06-20 13:45 UTC
Labels: Duplicate
