### ISSUE TITLE
Canyon Condor

### ISSUE THREAD

**Issue by drizzylover** [Wynncraft/Issues#4284] opened 2016-02-26 01:35 UTC
on this quest when you need to get the gold bars for Jankan, the gold bars dont spawn where they are supposed to. i looked it up and i know that it is where it spawns(at the very bottom of the tunnel).

**Comment by Odnod** [comment] 2016-02-26 01:37
Duplicate of #4236, please close this issue and direct any additional comments to the original thread, Thanks!

This issue is very well known and the dev team is working on fixing it.

**Comment by drizzylover** [comment] 2016-02-26 01:44
thank you for responding so soon, and i appreciate that you guys are working on it

**Closed** 2016-02-26 01:44 UTC
