### ISSUE TITLE
Spawn glitch

### ISSUE THREAD

**Issue by HaydnPlayz** [Wynncraft/Issues#7380] opened 2017-02-15 14:40 UTC
I don't know if you guys have known about this glitch for a while but it involves the quest Green Skinned Trouble, If you die while fighting Greggr you respawn where you spawn as level 1, I just thought you guys might want to know about this if you didnt already
![2017-02-15_14 40 31](https://cloud.githubusercontent.com/assets/22133945/22978997/bd134464-f38c-11e6-87c9-719e056af948.png)

**Comment by LordHelmchen98** [comment] 2017-02-15 15:21
That happens because the area is off map and therefore the closest respawn point is the starting area.
Anyway this specific case is a duplicate of #4523 and the problem in general is a dupliicate of #3617 where you can find more information and some explanations why this is not fixed and probably wont be fixed very soon.
As it's a duplicate you should close this.

**Closed** 2017-02-16 01:14 UTC
