### ISSUE TITLE
Guild problems

### ISSUE THREAD

**Issue by Leg420** [Wynncraft/Issues#5681] opened 2016-08-07 20:57 UTC
Ok so people have changed their name while in my guild and now i cant kick them for new players (because theyre inactive), and i cant disband it. What can i do? (Id like to disband it)

**Comment by ColinRioux** [comment] 2016-08-07 21:59
As of write now, there is nothing you can do. This issue has been known for awhile, and we hope that in the gameplay update this issue will be resolved. 

@Moe-Ronickah will have some more advice.

**Comment by Trixter313** [comment] 2016-08-07 21:59
Duplicate of #3665 

There currently isn't anything the player can do to fix it, we just have to wait for guilds to be revamped and fix it. Guilds are fairly broken as of right now.

**Closed** 2016-08-07 21:59 UTC
