### ISSUE TITLE
Skill point book buttons disappeared

### ISSUE THREAD

**Issue by ShadoCapital** [Wynncraft/Issues#6886] opened 2016-12-12 15:30 UTC
I rejoined after not playing for a long time and decided to reset my skill points as the penalty is only two soul points now, not a LE. Also because I wanted to change my build.
However, after I reset my skill points, the "books" that I click on to add skill points disappeared, and I have tried rejoining, changing class, restarting Minecraft and the books still haven't come back.
Here's a photo of what I mean:
![15503061_10211815423171004_1381780594_o](https://cloud.githubusercontent.com/assets/24526848/21104814/b0c259f2-c0d3-11e6-8296-15768a1878bf.jpg)

**Comment by LordHelmchen98** [comment] 2016-12-12 15:46
Duplicate of #6782
I bet you are using 1.11. use a lower version to see the books again. I also heard they are shown again if you click where they should be but I'm not certain if that true.

**Closed** 2016-12-14 01:07 UTC
