### ISSUE TITLE
Guild member glitch

### ISSUE THREAD

**Issue by MechanicSlayer** [Wynncraft/Issues#5260] opened 2016-06-18 21:37 UTC
Ok so I'm having a really bad problem with my guild... It's really weird to explain but basically what happened is that, my account, for some reason, appears to not be in a guild. But it keeps telling me I am for some reason. I have tried doing the /guild leave command and it takes away my 3 soul points, but it doesn't take me away from my guild [https://i.gyazo.com/842ef648175ce5ad8b4ae1255afce10c.gif](url)
It's as if the game doesn't think I'm in a guild, but doesn't want me to leave it. The major problem though is that we have a player in our guild, that has never even been on Wynncraft in the first place, his name being Aurellis. Oh, and his player name tag basically replaced mine. [https://gyazo.com/1eebe9a44150993024ef8f878eb4ee30.png](url) [https://i.gyazo.com/6bd3c6edb42420b69f34101ff4955324.png](url)
I had tried fixing the glitch by changing my name from MechanicSlayer to IncognitoNarwhal but it didn't solve anything. I really have no idea what the problem is or how it occurred but please try and fix it because I can't do anything within my guild :(

**Comment by Moe-Ronickah** [comment] 2016-06-19 02:02
duplicate of #3665 .  Please follow this issue on that thread.

**Closed by Moe-Ronickah** 2016-06-19 02:02 UTC
Labels: Duplicate
