### ISSUE TITLE
No emeralds upon completing certain quests

### ISSUE THREAD

**Issue by RS-Mind** [Wynncraft/Issues#3955] opened 2016-02-01 22:13 UTC
I was playing Wynncraft with a friend and we completed the wedding ring quest, which is supposed to give us 20 emeralds, but it didn't. We did a different quest but got the emeralds in the same session (Underwater Quest). Just now alone on my first character I complete the confused farmer quest and I don't get the 44 emeralds. I think the issue is a bug in the reward system for certain quests. I personally don't care all that much about the lost emeralds but others might so I am submitting this bug.

**Comment by Dar-krusos** [comment] 2016-02-01 22:49
The Confused Farmer quest's 44 Emeralds are given to you by Buvale in Katoa Ranch before going to Drale.

**Comment by RS-Mind** [comment] 2016-02-01 23:06
oh, but we still didn't get the 20 from the Thieving Rodents quest.

**Comment by Dar-krusos** [comment] 2016-02-02 05:24
> oh, but we still didn't get the 20 from the 
> Thieving Rodents quest.
> - RS-Mind

Yeah, that should be a bug of some sort.

**Comment by Trixter313** [comment] 2016-02-02 12:04
Duplicate of https://github.com/Wynncraft/Issues/issues/3562

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-02 12:04 UTC
