### ISSUE TITLE
Guilds....

### ISSUE THREAD

**Issue by Bryanboyv1** [Wynncraft/Issues#7903] opened 2017-04-17 11:40 UTC
The guilds are really bugged/glitched i cant attack/defend.
The mobs will not spawn, sometimes u will not get tpped.
And my friend "KrazyKikker" cant leave his guild with /guild leave.

Can u please fix this?

**Comment by LordHelmchen98** [comment] 2017-04-17 12:39
Yeah guilds are very bugged right now, but it has already been reported.
Also the issue with KrazyKikker is a duplicate of #3665 look there for more information.
Guilds cant be fixed very easily and until they get fixed you will have to be patient.

**Closed by LordHelmchen98** 2017-04-17 12:39 UTC
Labels: Duplicate
