### ISSUE TITLE
Whetstone not spawning for ultimate weapon quest

### ISSUE THREAD

**Issue by DigitalDank** [Wynncraft/Issues#4283] opened 2016-02-26 01:25 UTC
when dodegar asks for the 50 whetstone that spawns at the waterfall. if you go there nothing is spawning. plz help me i really need to finish this quest 

:D

**Comment by Odnod** [comment] 2016-02-26 01:34
Duplicate of #4236, please close this issue and direct any additional comments to the original thread, Thanks!

This issue is very well known and the dev team is working on fixing it.

**Closed** 2016-02-26 01:50 UTC
