### ISSUE TITLE
Guild lvl and stats bug

### ISSUE THREAD

**Issue by actuallynot** [Wynncraft/Issues#3935] opened 2016-01-31 16:13 UTC
![2016-01-31_18 43 33](https://cloud.githubusercontent.com/assets/16987986/12703203/88a3a972-c84e-11e5-8da3-97d9087d5848.png)
![2016-01-31_18 43 26](https://cloud.githubusercontent.com/assets/16987986/12703205/89dd10bc-c84e-11e5-831a-5121d8fd5eb7.png)

**Comment by Trixter313** [comment] 2016-01-31 16:48
Duplicate of https://github.com/Wynncraft/Issues/issues/3799

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-31 16:48 UTC
