### ISSUE TITLE
Arrows stuck in Enderchest

### ISSUE THREAD

**Issue by GambitDarkh** [Wynncraft/Issues#5208] opened 2016-06-12 06:10 UTC
Hi I have several stacks of arrows stuck in my bank/enderchest that are immovable in every way. Help🙏🏻

**Comment by Moe-Ronickah** [comment] 2016-06-12 12:59
Duplicate of #3147 .  You can follow your issue, there.
The admins are working on this.  Don't ask "when", because we don't know, yet.

**Closed by Moe-Ronickah** 2016-06-12 12:59 UTC
Labels: Duplicate
