### ISSUE TITLE
Guilds are generally broken, guild xp being one of the other issues

### ISSUE THREAD

**Issue by CryogenicFrost** [Wynncraft/Issues#2202] opened 2015-08-13 14:46 UTC
http://i.imgur.com/K1ciYrU.png Even with guild xp 100, none of the xp goes into the guild

**Comment by Trixter313** [comment] 2015-08-13 14:49
Duplicate of https://github.com/Wynncraft/Issues/issues/2074

We recommend closing the duplicate and following the original to stay up to date on the issue. Thanks!

**Closed** 2015-08-13 19:58 UTC
