### ISSUE TITLE
i can,t go out  BUG don,t de my post ok?

### ISSUE THREAD

**Issue by asukaka** [Wynncraft/Issues#5199] opened 2016-06-10 16:25 UTC
i am asukaka i bug in world at GMblock i can,t go out class is mage lv32
when i RRR bug in block

**Comment by Trixter313** [comment] 2016-06-10 16:30
Duplicate of #5194 
Please post any future comments on the original thread. Thanks!
Also, please stop posting duplicates or we will have to ban you from the issue tracker.

**Closed by Trixter313** 2016-06-10 16:30 UTC
