### ISSUE TITLE
Rise of the Quartron quest dialouge

### ISSUE THREAD

**Issue by Skjoldsan** [Wynncraft/Issues#4159] opened 2016-02-16 23:38 UTC
![image](https://cloud.githubusercontent.com/assets/17282569/13094962/85a02864-d50e-11e5-81e4-aaca0f184c36.png)

Quest NPC tells you to get them 2 mechanical pieces after clicking them after getting told what to do.

**Comment by Dar-krusos** [comment] 2016-02-17 03:24
Yes, this is a typo and is actually part of the _An Iron Heart Part I_ quest. This issue is a duplicate of issue #3531 and will be fixed in the next patch (hopefully), because of my [typo thread](https://forums.wynncraft.com/threads/typos-in-quests.111807).

**Closed** 2016-02-18 12:03 UTC
