### ISSUE TITLE
https://gyazo.com/eb4d5f201a65fbf2c1893018bf270da5

### ISSUE THREAD

**Issue by Deltaaa** [Wynncraft/Issues#3844] opened 2016-01-24 15:47 UTC
https://gyazo.com/eb4d5f201a65fbf2c1893018bf270da5 HELP

**Comment by Trixter313** [comment] 2016-01-24 17:59
Duplicate of #3841 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-24 17:59 UTC
