### ISSUE TITLE
Losing items

### ISSUE THREAD

**Issue by zeovas** [Wynncraft/Issues#3251] opened 2015-12-27 23:00 UTC
I was going to Olux when a lag spiked happened. I was doing some spells on my bow to see if the lag stopped. It turned out to be a unexpected restart and when I logged in again I lost my bow! I would be extremely grateful if someone fixed this and got my bob's mythical bow back.

**Comment by WorseWaif** [comment] 2015-12-27 23:07
yes, i just had something happen to me too during a lag spike. i lost my staff and a health potion. i don't care about the potion obviously, but it pisses me off that my good staff just disappears

**Comment by Trixter313** [comment] 2015-12-29 21:48
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. There's no way to tell whether the lost item was caused by the server or the player simply dropping the item. We'd appreciate it if you closed this issue. Thanks!

**Comment by zeovas** [comment] 2015-12-30 01:58
Thank you for considering my offer. I got another weapon from my guild mates and it turned out to be a better weapon! I will close the issue but it would be better if these lag spikes and unexpected restarts wouldn’t happen. Thank you :)

**Closed** 2015-12-30 01:58 UTC
