### ISSUE TITLE
Unable to Sign Up for Forums

### ISSUE THREAD

**Issue by Peero11** [Wynncraft/Issues#4996] opened 2016-05-15 01:04 UTC
I am unable to sign up for forums because of a bug I believe. When I sign up, is says that my minecraft username ( _ Piro _ ) (no spaces between piro and the _'s) is invalid. I have no idea why this is happening. It may be because of the underdashes, which I have had problems with in the past, but other than that I do not know what to do. I tried my original username (pironation11) and that did not work either. It is the only problem and I have tried multiple times over multiple days. Please help if anyone knows!

**Comment by YunoFGasai** [comment] 2016-05-15 11:27
duplicate of #4940 please refer all future comments to the original thread.

**Closed** 2016-05-22 23:11 UTC
