### ISSUE TITLE
Lost things when logging in

### ISSUE THREAD

**Issue by LilyanaV** [Wynncraft/Issues#4199] opened 2016-02-20 21:15 UTC
Okay so today I had one problem about a glitch. 
Recently, I have found a legendary chest 20-24 in a chest drop in Ancient Nemract. And I had just turned level 30. But this was when the server was almost ready to restart. I went back to Deltas to sell some items and Identify the chest. I spent 100 or so gems on it and it was the Katoa's Warmth chest.
I went afk for a bit and got timed out. After awhile I came back and logged into my Assassin to play. When I came back, my chest was gone. I even put it on before I went afk and it wasn't there. This has happened to me before, and I'm starting to wonder if it's me, or is this a reoccurring issue. Unfortunately I do not have any screenshot to share that I actually had that, at the time I didn't think to screenshot it because for one I have no one to share it with. But other than that, this was a bug I found, not sure if this has happened to anyone else. 

Kinda upset I lost that chest since it was really good. And a lot of gems spent to Identify it, but things happen. besides the point, pretty sure this has happened before, fix it....?

**Comment by Trixter313** [comment] 2016-02-20 21:22
Hmm, was your inventory full when the item disappeared?

**Comment by LilyanaV** [comment] 2016-02-20 21:24
No, I sold some items before I identified the chest.

**Comment by Dar-krusos** [comment] 2016-02-21 05:45
I think this may be a result of lag. When I move items around in my bank or inventory, I click on empty slots to make sure that the item stays where it should be.

**Comment by Zebstrikal** [comment] 2016-03-30 01:42
This happened to me too!

**Comment by Moe-Ronickah** [comment] 2016-06-29 22:35
There is a common theme here that sounds to me like players are logging in, and their armor and skill points are not yet being loaded on the character.  Without armor, players are getting one-shotted.

**Comment by JackyKit123** [comment] 2016-08-05 14:14
http://i.imgur.com/bFRMNo6.png
Lost my third eye due to the same issue, my inventory is full
my armor is dropped when I log on
I got one shotted

**Comment by Moe-Ronickah** [comment] 2016-08-06 11:33
@JackyKit123 , I've passed this along to Salted. but please be aware that we cannot refund lost items that obtained in-game.  Still, thank you for grabbing the screenshot and posting the evidence.

**Comment by Moe-Ronickah** [comment] 2016-08-21 09:44
Duplicate of #4120

**Closed by Moe-Ronickah** 2016-08-21 09:44 UTC
Labels: Duplicate
