### ISSUE TITLE
Wrong text when interacting with NPC "Irt" in Almuj

### ISSUE THREAD

**Issue by Baumey** [Wynncraft/Issues#4315] opened 2016-02-27 18:48 UTC
![](http://puu.sh/nnxaR/924ab0183f.png)
Wrong text when interacting with NPC "Irt" in Almuj
X:+940 / Y:+76 / Z:-1892

**Comment by Place-Name-Here** [comment] 2016-02-27 20:18
That's a 404...

**Comment by Moe-Ronickah** [comment] 2016-02-28 03:21
Please post a screenshot of the issue.  Your link does not lead anywhere.

**Comment by Trixter313** [comment] 2016-02-28 18:57
You have to copy and paste the link instead of clicking on it, the text is correct but the hyperlinked link is broken.
Here's the image:

![](http://puu.sh/nnxaR/924ab0183f.png)

**Comment by Moe-Ronickah** [comment] 2016-05-05 11:58
Duplicate of #4177

**Closed by Moe-Ronickah** 2016-05-05 11:58 UTC
Labels: Duplicate
