### ISSUE TITLE
Armor got deleted

### ISSUE THREAD

**Issue by Martianpooper** [Wynncraft/Issues#5152] opened 2016-06-05 03:32 UTC
Ok so one of my skills randomly went down for no reason and some of my armor required a certain amount of  a skill, so they went into my inventory. Except, my inventory was full, so my armor just... deleted

Can someone possibly get my armor back or something

**Comment by TheCatArchy** [comment] 2016-06-05 04:28
Try relogging and restarting
If those don't work, Wynncraft has a no refund policy so there's no way for them to give you back what you've lost. ;-;

**Comment by Moe-Ronickah** [comment] 2016-06-05 23:57
Duplicate of #3153 .  Please address any further comments to that thread.

The admins know about it and are working on - that's why you may see them logging on and off over and over.  They are trying to duplicate it and find the source.

**Closed by Moe-Ronickah** 2016-06-05 23:57 UTC
Labels: Duplicate
