### ISSUE TITLE
Spider Cave

### ISSUE THREAD

**Issue by TiggyS** [Wynncraft/Issues#4487] opened 2016-03-06 23:23 UTC
Hello
I started playing today and i accepted the quest Spider Cave, it told me to bring 3 Saccharum. i was in the cave for 30 min, killing spiders looking all around and it wouldnt spawn.

**Comment by Trixter313** [comment] 2016-03-06 23:39
Duplicate of #4236 

Please direct any future comments to the original thread. Thanks!

**Closed** 2016-03-06 23:38 UTC
