### ISSUE TITLE
Cowfusion Dialogue Messup

### ISSUE THREAD

**Issue by Endeh** [Wynncraft/Issues#4798] opened 2016-04-11 02:21 UTC
As I completed cowfusion, instead of using the ending dialogue, it used dialogue from what the scientist says why you enter his lab.
https://gyazo.com/f493e3b0425ca02d10f3fcc4e6f816c4

**Comment by Trixter313** [comment] 2016-04-11 02:29
Duplicate of https://github.com/Wynncraft/Issues/issues/3304

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-11 02:29 UTC
