### ISSUE TITLE
I can't log in with my mage

### ISSUE THREAD

**Issue by PLutonium27** [Wynncraft/Issues#7862] opened 2017-04-14 09:31 UTC
I joined server and selected mage. and a message popped.
"there has been an error... try again."
and I can't log in with my mage. but all other classes like assassin have no problem. I couldn't play my mage for a week.

**Comment by LordHelmchen98** [comment] 2017-04-14 11:23
Duplicate of #7680 please look there for future information.

**Closed by LordHelmchen98** 2017-04-14 11:23 UTC
