### ISSUE TITLE
there is no item identifier in pirate island too  

### ISSUE THREAD

**Issue by 7asoOonyi14** [Wynncraft/Issues#4020] opened 2016-02-07 15:10 UTC
there is no item identifier in pirate island too  , ... should have said that in my old threat oh well sorry ..

**Comment by Trixter313** [comment] 2016-02-07 21:20
Duplicate of https://github.com/Wynncraft/Issues/issues/3272

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-07 21:20 UTC
