### ISSUE TITLE
Insane Glitch With Class after Selection 

### ISSUE THREAD

**Issue by FirstTyper** [Wynncraft/Issues#5751] opened 2016-08-16 23:34 UTC
Hello! I'm FirstTyper! I am helping find glitches and reporting them. Today/Yesterday I found a glitch where if I select a class after that it spawns me with 10/760 hearts and 0/20 hunger... I and many other have been experiencing this glitch/issue. It basically after I chose my class, it spawns me at 89999999990000000000 height in the air. I have tried both Play.WynnCraft.Com, and Play.WynnCraft.Net. Also I have tried ./kill but this glitch doesn't allow me to say anything and doesnt allow me to ./kill it is annoying!!

#IBeliveInWynnCraft!

Thank You! I hope you will be able to fix this issue and help me out! Also this glitch crashes the server. 

Thank You, Again!!!

**Comment by Moe-Ronickah** [comment] 2016-08-17 06:23
Dupe of #5134 .  Requires fixing by admin, and Salted has been notified.

**Comment by Moe-Ronickah** [comment] 2016-08-17 06:23
**DO NOT CLOSE UNTIL FIXED**

**Comment by Moe-Ronickah** [comment] 2016-08-17 06:33
fixed!

**Closed by Moe-Ronickah** 2016-08-17 06:33 UTC
Labels: Duplicate

**Comment by FirstTyper** [comment] 2016-08-17 09:06
Thanks So So Very much

**Comment by Moe-Ronickah** [comment] 2016-08-21 07:58
You are very welcome, and thank you for letting us know about this.
