### ISSUE TITLE
powder none stacking glitch/bug

### ISSUE THREAD

**Issue by armorpower** [Wynncraft/Issues#8552] opened 2017-07-08 16:30 UTC
so i have noticed that a lot of my powders just don't stack with each other my friend has the same problem as well and i dont get why its the same item same everything there is nothing different between them and its really annoying when it happens with every tier of powder that i have i have up to t4 powders right now and that amount of powders i throw away because i dont have the inventory room is insane i will deal with t4 not stacking since it would take me a while to get another but t1 powders are annoying if a dev of wynncraft admin mod or the owner sees this plz look into fixing it i don't know what causes it but from what i'm seeing a lot if not every player has this problem also it eats up bank slots

**Comment by thecoolkogut4** [comment] 2017-07-08 17:13
Duplicate of #5271

**Comment by gogodiego123** [comment] 2017-07-08 18:59
#5271 is about a dropped weapon, not unstacking powder

**Comment by thecoolkogut4** [comment] 2017-07-08 19:00
My bad, #5871

**Comment by Dalarn** [comment] 2017-07-08 23:19
Yep got the same problem to.

**Comment by PepinhoJp** [comment] 2017-07-09 04:55
Powders that you upgraded won't stack with the ones that you got from loot chests and there are some othef examples, it's because of NBT tags, you can read more about them here: http://minecraft.gamepedia.com/Tutorials/Command_NBT_tags

**Closed** 2017-07-09 23:18 UTC
