### ISSUE TITLE
Quest items/ Drops Again

### ISSUE THREAD

**Issue by aiazu** [Wynncraft/Issues#4361] opened 2016-02-29 16:55 UTC
Quest items etc arent spawning in any area same issue that happened the other day

**Comment by qutt** [comment] 2016-02-29 20:54
I know! they don't spawn for me either...

**Comment by Moe-Ronickah** [comment] 2016-02-29 20:57
Duplicate of Quest Items Are Not Spawing #4236 .  Please refer all future comments to the original thread.

**Closed by Moe-Ronickah** 2016-02-29 20:57 UTC
