### ISSUE TITLE
~~[Armor Deleted When Forcibly Removed While Having A Full Inventory]~~

### ISSUE THREAD

**Issue by olivenjoker** [Wynncraft/Issues#3170] opened 2015-12-26 07:51 UTC
<h1>*__Lost Items__*
<p>Me and my Sister ingame: **olivenjoker**, **LariCraft007**. We played after the big update and wanted to identify our weapons and armor . However, our inventory was almost full so beimir all get lost only the  helm didnt get lost. In LariCraft it was the same and she had only her shoes .<p/>
We have lost 2 Legendary pants and a legendary chestplate. **Pants and the chestplate were lvl 16.
The second pants were lvl . 25.**
It would be nice if you could help us and maybe even regain our lost items.

*olivenjoker*

**Comment by Matthew12133** [comment] 2015-12-26 14:14
Could I suggest _**maybe**_ getting new armour? **Almuj** would be a good place to grind and get new armour, seeing as you guys are around that level.

[Map of Almuj] (https://map.wynncraft.com/#/943/64/-1966/-2/0/0)

Hope this helps!

**Comment by Verret001** [comment] 2015-12-26 14:16
Duplicate of https://github.com/Wynncraft/Issues/issues/3166

**Comment by DarkDemonDragon** [comment] 2015-12-26 15:28
I'm sorry but Wynncraft has a strict no refund policy. Players have lost worse than those. I've seen a report of a missing Bob's Mystic Bow which was the best bow the obtain pre-Gavel. Others have lost entire sets of End-game (Legendary Lv 70+) gear, so just obtain new gear by killing mobs or ask people if they have any junk gear they are willing to spare.

**Comment by Suegerman** [comment] 2015-12-26 16:39
Same this happend with me and my brother!

**Comment by brainscript** [comment] 2015-12-26 16:46
Same this happend with me and my grandmother! *-.-*

**Closed** 2015-12-28 11:37 UTC
