### ISSUE TITLE
Hallowynn and Craftmas Respawn - Llevigar

### ISSUE THREAD

**Issue by Touta-Matsuda** [Wynncraft/Issues#5230] opened 2016-06-15 03:24 UTC
# Delete this line if you've searched for a duplicate issue first

This may be a duplicate issue considering the Craftmas quest was quite hard, but I couldn't immediately find anything.

So I'm not the best at this game. I died both in the place with the pit souls in the quest "Macabre Masquerade 'Hallowynn 2014'" and the Future Selchar in the quest "Craftmas Chaos". In both cases I respawned in Llevigar. I understand that there may not be a fix to this, as it's probably hard to change the entire map and removing Llevigar as a spawnpoint is a horrible idea, but if there's an easy fix to this issue, it would likely be appreciated by anyone else that done goof's and dies in these quests.

Thanks for reading what's probably a pointless and unfixable post, and have a wonderful day.
~ Touta_Matsuda

**Comment by Trixter313** [comment] 2016-06-15 03:32
Duplicate of https://github.com/Wynncraft/Issues/issues/3617

I made a post about it and it got some good votes so all we can hope now is that they decide to implement it.

**Closed by Trixter313** 2016-06-15 03:32 UTC
