### ISSUE TITLE
Holes to get stuck in

### ISSUE THREAD

**Issue by Lake902** [Wynncraft/Issues#3711] opened 2016-01-16 02:29 UTC
http://imgur.com/a/rWSr8

**Comment by Moe-Ronickah** [comment] 2016-02-05 13:48
The builders have been known to make those types of holes on purpose.  Usually, they are 1x1 or 1x2.  If they are any deeper, then yes, it is probably a flaw.  So, I'm going to call the upper image as an intentional trap.  I can't make out where the problem is in the lower image.

**Comment by Villageacules** [comment] 2016-04-07 01:33
Fixed, patch will be in follow up update.

**Comment by Moe-Ronickah** [comment] 2016-04-07 01:48
See above.

**Closed by Moe-Ronickah** 2016-04-07 01:48 UTC
Labels: World
