### ISSUE TITLE
Lost Items in bank upgrade

### ISSUE THREAD

**Issue by Strabismuss** [Wynncraft/Issues#4091] opened 2016-02-12 11:23 UTC
I unlocked a new row in my Bank. I had 3 jester necklaces, a jester bracelet and some other necklace in the top left corner. When I clicked on the glass pane to unlock the new row the items in the top left corner instantly dissapeared.

**Comment by DarkDemonDragon** [comment] 2016-02-12 13:12
Do you mean in your accessories slot or just in your inventory. Also what level are you?

**Comment by Strabismuss** [comment] 2016-02-12 13:18
@DarkDemonDragon They were in my bank at the time, In them top left corner of my bank. It's my level 58 Mage class.

**Comment by ingmarv2** [comment] 2016-02-21 20:52
I Hope u will get u items back i know how it feels when you'r deary items are gone .. ..

**Comment by sulkbliss** [comment] 2016-07-01 13:28
Had this occur to me as well. I lost one Jester necklace. Any chance of getting it back?

**Comment by YunoFGasai** [comment] 2016-07-01 14:32
@sulkbliss I'm sorry but wynncraft has a no refund policy, sorry.

**Comment by Moe-Ronickah** [comment] 2016-07-01 20:39
@sulkbliss , your issue is a aduplicate of #4428.

**Comment by TeenageCat** [comment] 2016-09-17 18:40
So... I can't get my stuff back? That's stupid :/

**Comment by Trixter313** [comment] 2016-09-17 21:57
As mentioned above, Wynncraft had a strict no refunds policy to keep the game fair for everyone.

**Closed** 2017-05-07 17:03 UTC
Labels: Game Mechanics
