### ISSUE TITLE
Missing texture

### ISSUE THREAD

**Issue by albe808** [Wynncraft/Issues#6653] opened 2016-11-10 22:50 UTC
Hi, I am albe808.
I randomly stumbled upon the Unique item, Hunter. It's for the Warrior/Knight class. It seems it is missing its texture. So please fix it.

**Comment by ColinRioux** [comment] 2016-11-11 04:42
Please provide screenshots?

**Comment by Rellia** [comment] 2016-11-11 11:16
There are a LOT of items that don't have a custom skin texture. Usually using the latest minecraft version helps out ton, but some items just haven't been textured yet. Such as Infinity, Meteor Arch and Relic Bow are all spruce wood plank slabs. They still function perfectly fine.

**Comment by Trixter313** [comment] 2016-11-13 15:42
Duplicate of #4548

**Closed by Trixter313** 2016-11-13 15:42 UTC
