### ISSUE TITLE
Can't leave my guild

### ISSUE THREAD

**Issue by thomasbol76** [Wynncraft/Issues#3657] opened 2016-01-11 16:22 UTC
I can't leave my guild, ./guild leave isn't working so ca kick me out the guild or fix the command

**Comment by Trixter313** [comment] 2016-01-11 22:09
Duplicate of https://github.com/Wynncraft/Issues/issues/3405

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-11 22:09 UTC
