### ISSUE TITLE
c'ant join 

### ISSUE THREAD

**Issue by Wiebedesma** [Wynncraft/Issues#6728] opened 2016-11-19 18:30 UTC
i c'ant join the server http://imgur.com/muBrjw2

**Comment by thecoolkogut4** [comment] 2016-11-19 20:33
try joining the server in 1.8, connect to play.wynncraft.com or .net

**Comment by ColinRioux** [comment] 2016-11-19 22:28
Duplicate of #6717

**Closed by ColinRioux** 2016-11-19 22:28 UTC
