### ISSUE TITLE
You cannot identify Ik-El-Vän

### ISSUE THREAD

**Issue by kakarot798** [Wynncraft/Issues#1461] opened 2015-01-04 03:33 UTC
I have a rare item named Ik-El-Vän , min lvl: 66, dam: 161-201, but I cannot identify it. Please fix this. ~Kakarot

**Comment by Jamdog** [comment] 2015-01-04 03:37
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

**Comment by AckroGaming** [comment] 2015-01-04 12:04
This is a known issue, although we would be happy if you could check the bug tracker for a similar post like the one you'd like to post.
Thank you anyway!

**Closed** 2015-01-04 12:08 UTC
