### ISSUE TITLE
Beneath the depths

### ISSUE THREAD

**Issue by ShortsLPs** [Wynncraft/Issues#4398] opened 2016-03-02 14:47 UTC
In the quest beneath the depths, you have to find a map in the cave behind the skull, but the map does not spawn...I have been through the cave 5 times and couldnt find it, looked up a youtube video to see where it should be and saw the place, but it didnt spawn there... could you please fix this?

**Comment by Odnod** [comment] 2016-03-02 14:54
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known by now and is being worked on.

**Closed** 2016-03-02 15:01 UTC
