### ISSUE TITLE
Bow Glitches

### ISSUE THREAD

**Issue by SoulEaterNatsu** [Wynncraft/Issues#4687] opened 2016-03-28 18:00 UTC
There's an issue with the bow I'm currently using on my main character. Its the bow "Infinity" and the vanilla item it was originally it a woods slab. The problem with it is, whenever I right-click, red error text appears saying "You don't have permission for this area." It doesn't affect my game-play much, but it is quite annoying. Another problem with it is that I cannot open loot chest with the bow in my hand, and that is very annoying. If this could be fixed that would be great.

**Comment by Odnod** [comment] 2016-03-28 19:05
Switching to 1.8.9 should solve some of your problems assuming you are in 1.9

**Comment by Trixter313** [comment] 2016-03-28 20:07
Duplicate of #4548 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-28 20:07 UTC
