### ISSUE TITLE
Canyon Condor Unbeatable

### ISSUE THREAD

**Issue by SwordKirby21** [Wynncraft/Issues#4467] opened 2016-03-05 21:55 UTC
I the quest Canyon Condor when Jankan tells you to get 10 gold bars from the cave, if you go into the cave the gold bars will not spawn at all.  This makes the quest impossible to beat as you cannot continue until you give Jankan the gold.

**Comment by Trixter313** [comment] 2016-03-05 22:04
Duplicate of #4236 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-05 22:04 UTC
