### ISSUE TITLE
Detlas Chunk Error

### ISSUE THREAD

**Issue by katelikesturtles** [Wynncraft/Issues#7817] opened 2017-04-12 01:24 UTC
Detlas is having multiple chunk glitches. There are spots with no blocks until a certain point, and if you land without a horse, you will die. Is this a glitch, or did a mod screw with the terrain? Either way, I'm asking for myself and other players if it can be fixed anytime soon. Please respond as soon as possible.

**Comment by LordHelmchen98** [comment] 2017-04-12 01:29
Duplicate of #7817 look there for more information.

**Closed by LordHelmchen98** 2017-04-12 01:29 UTC

**Comment by numbermaniac** [comment] 2017-04-12 01:37
> Duplicate of #7817

@LordHelmchen98 I think you just linked back to this issue. You probably meant #7816 :)

**Comment by LordHelmchen98** [comment] 2017-04-12 03:30
@numbermaniac wow didnt realize that thanks.
