### ISSUE TITLE
Az

### ISSUE THREAD

**Issue by OMGitsTomix** [Wynncraft/Issues#4658] opened 2016-03-26 15:17 UTC
Hello,

So yesterday I bought Az (mythic bow) from my friend and today I went to war with my guild but I couldn't use it! It had bugged name and ID's.I couldn't use spells and I couldn't even shoot,please fix it.

picture: http://imgur.com/xNR8qhT

**Comment by Trixter313** [comment] 2016-03-26 15:20
Duplicate of #3175 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-26 15:20 UTC
