### ISSUE TITLE
[Bug] Animal Dungeon 

### ISSUE THREAD

**Issue by KFC-Katana** [Wynncraft/Issues#5157] opened 2016-06-05 13:24 UTC
# Delete this line if you've searched for a duplicate issue first

The final boss of the dungeon Animal becomes out - zones and is untouchable .
I lost 2 key because of this bug.

Pseudo: KFC_Katana

I did not record this time but it is very unpleasant.

**Comment by Mininglover21** [comment] 2016-06-05 20:47
If the bug happens again then try moving to the opposite side of the boss. It should make it respawn and then you can fight it again. This bug has happened to me multiple times.

**Comment by Moe-Ronickah** [comment] 2016-06-06 00:07
Please learn to use the search function as explained on the first page, it will save you some work.

Duplicate of #3191 .

**Closed by Moe-Ronickah** 2016-06-06 00:07 UTC
Labels: Duplicate
