### ISSUE TITLE
Guild Name change Glitch

### ISSUE THREAD

**Issue by HackingDonor** [Wynncraft/Issues#4349] opened 2016-02-29 03:11 UTC
# Delete this line if you've searched for a duplicate issue first
What happened is. I am in a guild, my old IGN was "Kaitemi". I changed it to HackingDonor and now i am stuck in my guild, can't g leave, can't get kicked, i see chat as x2 which is very annoying. It is making me loose interest in this server because i can't play free. Now my guild probably hates me for... Not being up a lot and that they can't kick me for being inactive.. Thank you & please help me!

**Comment by ChiefInferno** [comment] 2016-03-06 16:23
I have the same problem but I changed my name back and its still isn't working and I've been looking on the forums for a month now and you guys aren't giving us any answers, your just labeling it duplicate and closing it while on the original post there is still now answer on what to do if u would please tell us what to do on this post that would be amazing

**Comment by Moe-Ronickah** [comment] 2016-03-11 05:09
We can't tell you how to fix it, because you can't fix it.  It is a game mechanic issue, and that is coded by the game admins.  There is nothing that you or I can do to fix it.  It has been reported, already, the admins are working on it, and that's why we close these reports as duplicates; because they are.

DUPLICATE OF #3665

**Closed by Moe-Ronickah** 2016-03-11 05:09 UTC
Labels: Duplicate
