### ISSUE TITLE
Tier 6 Red Powder Relic Problem

### ISSUE THREAD

**Issue by DNubltKingMinhal** [Wynncraft/Issues#5876] opened 2016-08-29 15:38 UTC
When I collected a tier 6 powder relic it gave me a tier 2 instead. That's pretty much the entire glitch.

**Comment by thecoolkogut4** [comment] 2016-08-29 16:04
it's not meant to give tier 6. there is a chance it gives tier 2-4powders (i believe its 2-4) but I know for sure it's not meant to give tier 6
duplicate of #5852

**Closed** 2016-08-30 22:32 UTC
