### ISSUE TITLE
texture pack/ salesmen

### ISSUE THREAD

**Issue by bakuscout** [Wynncraft/Issues#6579] opened 2016-11-04 21:35 UTC
so first off when i got on my favorite bow looked like a wooden slab. and secondly the shopkeeps are glitched they dont show prices and i cant even sell stuff to the treasure dude.

**Comment by LordHelmchen98** [comment] 2016-11-05 13:03
Have you tried to delete your serverresourcepack? If not go to your .minecraft folder open the serverresourcepack folder and then delete the 'legacy' file.
The price bug is a duplicate of #6575

**Comment by bakuscout** [comment] 2016-11-05 18:40
Thanks for getting back to me so soon, and sorry about making a duplicate report.

**Closed** 2016-11-05 18:48 UTC
