### ISSUE TITLE
Green Skinned Trouble Teleportation Glitch

### ISSUE THREAD

**Issue by Smurfman254** [Wynncraft/Issues#3339] opened 2015-12-30 02:41 UTC
I was trying to complete the green skinned trouble quest and had just killed the boss and got the axe of llevigar. When I went through the exit I was teleported to X -1865 Y 27 Z -4897, basically a 2x1x1 hole underground. I was stuck there and was unable to find any way to free myself. I was forced to kill myself via commands.

At the time I was also experiencing lag but stayed connected to the server the whole time.

Screenshot:
http://imgur.com/CxawQPy

**Comment by Trixter313** [comment] 2016-01-09 13:55
Are you having issues finishing the quest? If the quest is finished, it was most likely just a one time issue caused by lag.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Closed** 2016-01-17 19:09 UTC

**Comment by LordHelmchen98** [comment] 2017-09-29 23:39
In addition to Trixter's comment: Apparently switching servers should fix it.
