### ISSUE TITLE
Update and Falling Through The Void

### ISSUE THREAD

**Issue by Sorceric** [Wynncraft/Issues#5857] opened 2016-08-29 07:10 UTC
Update came, and I still fall through the void.

What would that mean for us players who still experience this problem and used every solution to try and fix it. 

Would that mean we have to wait until the problem is solved?

**Comment by Trixter313** [comment] 2016-08-29 10:02
Duplicate of https://github.com/Wynncraft/Issues/issues/5539

Yes, you'll have to wait until it is fixed if you've tried everything else.

**Closed by Trixter313** 2016-08-29 10:02 UTC
