### ISSUE TITLE
Cannot access to my warriorclass

### ISSUE THREAD

**Issue by scorixear** [Wynncraft/Issues#3628] opened 2016-01-10 12:21 UTC
Hello guys and girls, 
I have a very big problem. If I want to select my Warriorclass with lvl 36, I get an Error. The Error says: There has been an Error... Try again.
I think, the Problem ist my XP. The XP ist actually on 139% which is quit to much I think. 
Can you give me access to my class and set for example the xp on 0%?

Here are the other Infos:
minecraft-name: minecrafthaifl
Forum-name: minecrafthaifl
Class: Warrior
Level: 36
XP: 139%
Soul Points: 7
Quest Finished: 22/104

I have to Warrior-Classes, so please select the right :D
See You, Paul :)

**Comment by Trixter313** [comment] 2016-01-10 15:54
Duplicate of https://github.com/Wynncraft/Issues/issues/3250

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-10 15:54 UTC
