### ISSUE TITLE
Item Gitched

### ISSUE THREAD

**Issue by MikeTheMan909** [Wynncraft/Issues#3720] opened 2016-01-16 11:25 UTC
my chestplate got gitched. now its not working anymore. fix this please
![2016-01-16_12 23 18](https://cloud.githubusercontent.com/assets/16732265/12372108/1f560fc2-bc4c-11e5-85ae-a3bf7506e0da.png)
![2016-01-16_12 23 24](https://cloud.githubusercontent.com/assets/16732265/12372109/27b8d4ec-bc4c-11e5-81f8-7f4492f8904b.png)

**Comment by OverloadMC** [comment] 2016-01-16 14:41
This is a duplicate of https://github.com/Wynncraft/Issues/issues/3698

**Closed** 2016-01-17 19:45 UTC
