### ISSUE TITLE
Cant retune to the Hub- glitching/kicked by plugins?

### ISSUE THREAD

**Issue by robi7** [Wynncraft/Issues#6380] opened 2016-10-11 09:57 UTC
Hello there,
I need help becouse as it wrote in the title- I cant retune to the lobby after im in the world of Wynncraft.
When Im logging in I dont have any problem but if I play and after that need back to
the hub: Becouse the server restart, by commends (/hub /server and more) and one time I got there
without reason (that known to me) - My screen start to go little crazy...
At first that looks like the minecraft loading (with Wynncraft's rescure pack for dirt) after that
I see the hub but im glitching and its says in the chat and infront of my face "Flying is not enabled on this server" (i dont use any mods or hacks) and after less than seconed it back agian to loading and back to the glichy screen. This continue for between 3 - 15 mintues (i guess) untill this over and sometimes I have no choise than wait or restart minecraft cause I dont have exit from the server
when i cant click on "dissconcet" (correct me if im worng) :(.
This always happend to me but that start to get really ANNOYING. please fix it or offer me how to
end/esae this crazy bug.
robi7 (Im not english so I hope I was clear)

By the way im on 1.10.2 if this informtion will help

Heres a screenshot that I took after this happend to me for a little time (if i put the picture right)
![glitch wynncraft](https://cloud.githubusercontent.com/assets/22764252/19266327/ba217648-8fb1-11e6-9f52-d49100b0be0f.png)

**Comment by LordHelmchen98** [comment] 2016-10-11 14:10
First of all Wynncraft is coded for 1.8.9 and there will probably be bugs if you use 1.9 and above.
But I doubt this is related to you problem. It's most likely a connection problem to the lobby server. Sometimes something similar to this happens to me when I try to log in to a server.  Unfortunately I don't know how to fix this and I would like to know it as well if there is an option to fix it but I guess if you don't use /hub but directly disconnect from the entire network then join again and choose a server it might be faster.

**Comment by Trixter313** [comment] 2016-10-28 10:59
Duplicate of https://github.com/Wynncraft/Issues/issues/5289

**Closed by Trixter313** 2016-10-28 10:59 UTC
