### ISSUE TITLE
Skeleton Dungeon Fall Damage

### ISSUE THREAD

**Issue by truesurvivor9** [Wynncraft/Issues#5719] opened 2016-08-12 20:44 UTC
I know someone else has posted this months ago, but since it is still occurring, I want to mention this bug again.

When I jump into the skeleton dungeon (the pit at the entrance), I fall all the way down to the bottom blocks and take fall damage. Then, I get teleported into the dungeon with less health due to fall damage.
Here's a video: 
https://www.youtube.com/watch?v=wc92RU2UI7Q&feature=youtu.be

**Comment by Trixter313** [comment] 2016-08-12 21:05
Duplicate of https://github.com/Wynncraft/Issues/issues/2722

Dungeons are going to be revamped soon and this is most likely going to be fixed by that.

**Closed by Trixter313** 2016-08-12 21:05 UTC
