### ISSUE TITLE
Stuck in a wall

### ISSUE THREAD

**Issue by DoubleEss** [Wynncraft/Issues#4306] opened 2016-02-27 08:40 UTC
I was in the crystal room for WynnExcavation Site B and no crystals had spawned as they were meant to. I then went to exit the room so I could do some other quests whilst I waited for the issue to be fixed. When I attempted to portal out of the room I was teleported into a wall and am now stuck there.

**Comment by KeepoPrideHD** [comment] 2016-02-27 10:48
If you get into any wall, it's more like a minecraft bug. /kill is the only thing you can do. Remember to have more than **2 soul points **when doing that!

**Comment by gettodachopa** [comment] 2016-02-27 20:28
3 or more sould points? type /kill

**Comment by Moe-Ronickah** [comment] 2016-02-28 03:12
Original issue is a duplicate of #4236 .

**Closed by Moe-Ronickah** 2016-02-28 03:12 UTC
