### ISSUE TITLE
I can't leave my guild

### ISSUE THREAD

**Issue by djgunner44** [Wynncraft/Issues#6308] opened 2016-10-02 03:35 UTC
It saying I left the guild but shows i'm still in it. I can take a screenshot and show you if anyone wants to see.

**Comment by LordHelmchen98** [comment] 2016-10-02 16:10
I guess you have changed your name while being in that guild. Most players who change their name while being in a guild are stuck after the change. You have to wait until guilds get fixed which will hopefully happen with the next update.

**Comment by Trixter313** [comment] 2016-10-03 01:55
Duplicate of #3665

**Closed by Trixter313** 2016-10-03 01:55 UTC
