### ISSUE TITLE
Decrepit sewers dungeon barrier bug

### ISSUE THREAD

**Issue by Gummy56** [Wynncraft/Issues#8629] opened 2017-07-20 18:35 UTC
I went into the decrepit sewers dungeon as a level 11 mage and when i got the 18 tokens to advance to the next room, i got stuck in the sewer between the room which requires 18 tokens to advance and the next one, there is a pressure plate sound and when i hear it it says in the chat "You continue to trespass on my territory? You must have no value of your life" and there is some kind of invisible barrier in front of me that wont let me go through but other players can go through it with no problem. I tried switching servers, using /kill and then going back using a different key to get in, get the 18 tokens and then again i got stuck there but other players could still go through, i tried to change class and using a new key again to go in, get the 18 tokens and try to go through with that different class but still can't go through. I tried leaving completely the server and then going back in but didn't work either. I'm about to use /kill to get out of there because there is no other way. Please fix this, thanks for reading.

**Comment by colin350** [comment] 2017-07-21 13:45
Few things:
1. Duplicate of #6340
2. You have a few solutions:
a. Switch servers until you find one where the barriers aren't there.
b. Play on version 1.8.9 (logging out won't kick you from the dungeon unless you are in the boss room). You should play on 1.8.9 since Wynncraft is hardcoded to it, and playing on the hardcoded version will reproduce less issues. (This method is proven to work for some players)
3. We can't remove them because it's a required game mechanic at the moment. Sometimes they improperly reset. 

If things still aren't working for you, please direct all further questions to the duplicate issue: #6340. Don't make another issue.

**Closed by colin350** 2017-07-21 13:45 UTC
