### ISSUE TITLE
Beneath the Depths Issue

### ISSUE THREAD

**Issue by MiniBadBill** [Wynncraft/Issues#4026] opened 2016-02-07 19:19 UTC
Hello! So right now I'm a level 61 Mage and I'm working on the quest "Beneath the Depths". So I've done everything except defeat the boss in it and retrieve an item for the beginning NPC. I'm in the room where I'm suppose to kill the boss and I'm trying to kill him and all but it's very hard to do that because sadly the boss just glitches all over the place. It teleports (or whatever it does) around the room and sometimes it ends of in the lava, dying and unable to pick up the item because it has landed in the lava, or into a corner of the room. So with that in mind, I can't defeat the boss and complete the quest.

Please help!

-Mini

**Comment by Trixter313** [comment] 2016-02-07 21:13
Duplicate of https://github.com/Wynncraft/Issues/issues/3933

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-07 21:13 UTC
