### ISSUE TITLE
Log In Problems

### ISSUE THREAD

**Issue by TJKiira** [Wynncraft/Issues#6717] opened 2016-11-18 02:58 UTC
![image](https://cloud.githubusercontent.com/assets/23545399/20417058/f79d2bd0-ad29-11e6-943a-d48d88942b9d.png)
And Sometimes im getting disconected by flying when i log in...
Using 1.10.2 WIth Forge + Minimap + Optifine (Radar Off)

**Comment by ShaunaJade** [comment] 2016-11-18 08:48
I'm also having this issue with default, optifine and wynn enhanced. I am unable to login.

**Comment by flier66666** [comment] 2016-11-18 09:56
I'm having the same problem, optifine and just normal 1.10.2

**Comment by AkisTheAmazing** [comment] 2016-11-18 12:08
Had the same problem temporary solution:
Use their proxy ips

158.69.23.231 and 158.69.23.233 and 158.69.23.226 and 158.69.120.44 and 158.69.23.232 and 158.69.23.228 and 158.69.120.47 and 158.69.23.227 and 158.69.23.235 and 158.69.23.229 and 158.69.120.49 and 158.69.23.234 and 158.69.120.46 and 158.69.23.230 and 158.69.120.45 and 158.69.120.48

**Comment by LordHelmchen98** [comment] 2016-11-18 12:40
I guess you are using the ip play.wynncraft.com. Try to use .net or .org as alternative endings. Or switch the Minecraft version and log in once. Then switch back to your normal version.

**Comment by Rellia** [comment] 2016-11-18 15:44
I find just closing and reopening Minecraft works

**Comment by Thegamerplus1** [comment] 2016-11-18 21:45
![image](https://cloud.githubusercontent.com/assets/16379872/20447673/27d3ff74-ae45-11e6-8359-b9269f2e5b13.png)
same here. happens on enhanced, 1.11, and 1.8.9 haven't tried anything else.

**Comment by Thegamerplus1** [comment] 2016-11-18 21:47
![2016-11-19_10 42 11](https://cloud.githubusercontent.com/assets/16379872/20447756/7bd9a830-ae45-11e6-8259-68aebf9a1548.png)
Same here. happens on 1.11, 1.8.9, and wynnhanced. haven't tried anything else.

**Comment by Thegamerplus1** [comment] 2016-11-18 22:04
Completely ignored arguments: [--nativeLauncherVersion, 307]
[11:02:40] [Client thread/INFO]: Setting user: Thegamerplus1
[11:02:40] [Client thread/INFO]: (Session ID is <censored>)
[11:02:42] [Client thread/INFO]: LWJGL Version: 2.9.4
[11:02:42] [Client thread/INFO]: Reloading ResourceManager: Default
[11:02:43] [Sound Library Loader/INFO]: Starting up SoundSystem...
[11:02:43] [Thread-6/INFO]: Initializing LWJGL OpenAL
[11:02:43] [Thread-6/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[11:02:43] [Thread-6/INFO]: OpenAL initialized.
[11:02:44] [Sound Library Loader/INFO]: Sound engine started
[11:02:45] [Client thread/INFO]: Created: 512x512 textures-atlas
[11:02:53] [Client thread/INFO]: Connecting to 158.69.23.235, 25565


-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 197995224 bytes (188 MB) / 333115392 bytes (317 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R9 200 / HD 7900 Series GL version 4.5.14008 Compatibility Profile Context 21.19.137.1, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-5600K APU with Radeon(tm) HD Graphics

**Comment by Thegamerplus1** [comment] 2016-11-18 22:09
Fixed. Use Play.Wynncraft.org as opposed to .net, .com, or the one I used.

**Comment by ShaunaJade** [comment] 2016-11-19 05:21
I'm still having the issue even with changing the IP.

**Comment by archie426** [comment] 2016-11-23 17:45
Confirmed. I have this problem too
@LordHelmchen98 I'm not sure you are supposed to use that IP. From what a mod said, it causes more problems like this.

**Comment by LordHelmchen98** [comment] 2016-11-23 18:44
@archie426 You are right there are IP's that apparently shouldn't be used but that's the case if you put something random instead of the 'play' at the beginning of the IP. It is completely fine to use .org or .net at the end but you shouldn't use IP's like node7.wynncraft.com

**Comment by archie426** [comment] 2016-11-24 07:57
Ah, right, sorry

**Comment by Moe-Ronickah** [comment] 2016-11-28 04:44
There have been problems with connecting with Wynncraft, while the admins have been doing some work on the servers and making Wynn compatible with newer versions of MC.  Just bear with us, and, as LordHelmchen98 said, you can try .org, .net, and .com, and changing versions, in the mean time.

**Comment by NovaTTHC** [comment] 2016-12-27 00:50
I disconnected and reconnected the wifi (worked on optifine, normal, and forge. As well on windows and Mac)

**Closed** 2017-01-18 02:35 UTC
