### ISSUE TITLE
Gelibord Dungeon Scroll Merchant

### ISSUE THREAD

**Issue by TurtleDCLXVI** [Wynncraft/Issues#8831] opened 2017-08-24 20:12 UTC
Not sure if it's everywhere, but the Dungeon Scroll Merchant in Gelibord sells a piece of paper titled Galleons Graveyard instead of a scroll, I bought one and now just have a piece of paper titled Galleon's Graveyard(I didn't notice until after)
![screen shot 2017-08-24 at 1 11 27 pm](https://user-images.githubusercontent.com/31324072/29686440-d085ee76-88cd-11e7-8957-5a88149fb691.png)
![screen shot 2017-08-24 at 1 11 41 pm](https://user-images.githubusercontent.com/31324072/29686441-d08a4b56-88cd-11e7-83ec-1bf097100a14.png)

**Comment by PepinhoJp** [comment] 2017-08-24 21:26
Duplicate of #8074 

That is a known issue, please check for duplicates before posting a bug report. Hopefully this will be fixed with the next update.

**Closed** 2017-09-28 22:39 UTC
