### ISSUE TITLE
Reincarnation ~ Bob's Seal of Approval

### ISSUE THREAD

**Issue by TastyAero** [Wynncraft/Issues#7739] opened 2017-04-08 20:30 UTC
On **Wynncraft**, when you reach Lvl. 74 you unlock this quest known as, "Reincarnation." To do this quest, you need the power of Bob's three pets. Once you do that, you must defeat Bob.
   Now, my friends and I have defeated Bob four times. Each time, we did **NOT** get Bob's Seal of Approval. 
   Is this a bug? Or are we doing something wrong, please help.

**~
_TastyAero_
~**

**Comment by LordHelmchen98** [comment] 2017-04-08 21:41
Duplicate of #7679 
Please check for duplicates before posting here.
Anyway this should be fixed with the next map push, which will be in a few hours or so.

**Closed by LordHelmchen98** 2017-04-08 21:41 UTC
