### ISSUE TITLE
Thanos Shifty Merchant Glitch

### ISSUE THREAD

**Issue by fredesuper** [Wynncraft/Issues#3388] opened 2015-12-31 09:29 UTC
In Thanos, I wanted to buy some health potions. Level 85, to get into detail. I had 2 liquified  emeralds in my inventory when this happened. I went to the "Shifty Merchant" to make 64 emerald blocks and then to turn those into a couple of stacks of emeralds. I made them into 64 emerald blocks, this worked just fine. I started to try to make them into emeralds. I lost ALL of my 64 emerald blocks with ONE trade. All I got out of this trade was 1 emerald. I have a screenshot of the bug. And also, I just noticed, that if you want to make a liquified emerald, you have to use 64 LE to get it. I now have several screenshots.
![2015-12-31_09 43 04](https://cloud.githubusercontent.com/assets/10280751/12063100/2bd96fd2-afa9-11e5-892a-e8911f49824d.png)
![2015-12-31_10 29 56](https://cloud.githubusercontent.com/assets/10280751/12063104/31e996ae-afa9-11e5-92b6-a32501b96261.png)
If possible, can I please have my 1 LE back that I just lost? I'd be very grateful.
Have a good day, guys and thanks for reading this. I'll see you around, hopefully.
//T0ASTINAT0R

**Comment by fredesuper** [comment] 2015-12-31 09:30
Oh yeah and the first screenshot shows basically nothing. But I screenshotted it just in case of any confusement.

**Comment by superabel123** [comment] 2015-12-31 12:22
Errr sry to hear that but they have a strict no return policy
Thus,you will not be getting your stuff back even with 
evidence.However,you are thanked for reporting this
issue as it helps the mods fix the glitch so that no
other player may encounter this glitch

Superabel123

**Comment by W-Schnee** [comment] 2015-12-31 14:12
I am pretty sure that is intended. It says **Shifty** Merchant for a reason.

**Comment by DarkDemonDragon** [comment] 2015-12-31 19:25
Please close this as this is INTENTIONAL and not a bug.

**Comment by HeyloLP** [comment] 2016-01-01 01:05
you know that your kind of stupid

**Comment by Trixter313** [comment] 2016-01-01 07:30
I'm very sorry to hear that but I do believe this is intentional also, so I shall close this issue. I give you my condolences for the lost money. Don't let it get you down too much though! =)

**Closed by Trixter313** 2016-01-01 07:30 UTC
