### ISSUE TITLE
skin bug and annoyance

### ISSUE THREAD

**Issue by Misticulx** [Wynncraft/Issues#4014] opened 2016-02-07 05:39 UTC
ok im having a really annoying issue but when i join the rpg servers for wynncraft it removes my skin and leaves me with the default alex skin when i have steve selected and when im in the towns the guards attack me but cant kill me but that guard thing is just and annoyance and it wont show my armor

OH and i thought it might have been a client bug but i deleted the game files and reinstalled the game but even doing that it still dose it

**Comment by Misticulx** [comment] 2016-02-07 05:46
OK so this issue somehow got fixed dont know how or why but iv noticed that someone else has this bug so i think it would be nice if the admin can get this fixed to tell us a fix for it in this post or better yet put the fix someone ingame

**Comment by Roran27** [comment] 2016-02-07 10:45
Yesterday I had the same problem, but somehow it got fixed. Thanks to the Staff!

**Comment by Dar-krusos** [comment] 2016-02-07 11:44
If you change your skin, the servers won't receive that until a while later. Either it is random or scheduled, but just know that it usually won't update on Wynncraft worlds instantly.

**Comment by Moe-Ronickah** [comment] 2016-02-08 02:59
Duplicate of  #1640

**Closed by Moe-Ronickah** 2016-02-08 02:59 UTC
