### ISSUE TITLE
The Bear Armour set bonus bug!

### ISSUE THREAD

**Issue by FieldFuel** [Wynncraft/Issues#8733] opened 2017-08-07 16:13 UTC
I went to the **The Bear Zoo Island** today on Wynncraft and was gonna buy my self the **Bear Armour** from the **Souvenir Shop**. I bought the two pieces of armour:

![bear body](https://user-images.githubusercontent.com/30804859/29034669-558e9eca-7b99-11e7-946a-a080937a0a51.PNG)

and...

![bear mask](https://user-images.githubusercontent.com/30804859/29034677-598255da-7b99-11e7-82c9-9e2aeba97376.PNG)

Only to find out that the set wasn't complete, I didn't get the **set bonus**...
So I looked closely and found out that I wasn't wearing the "**Bear Head**". I was wearing the "**Bear Mask**" 

![bear set text](https://user-images.githubusercontent.com/30804859/29034820-ce7d3a6c-7b99-11e7-8f19-8c108e007f61.PNG)
![bear mask text](https://user-images.githubusercontent.com/30804859/29034849-ec488d4e-7b99-11e7-8328-aa1b3d70da2e.PNG)

So I thought, how do I get the **Bear Head** and not the **Bear Mask**? It isn't sold in the **Souvenir shop**.

![bear mask shop](https://user-images.githubusercontent.com/30804859/29035057-a1080548-7b9a-11e7-9ce1-92612bf8dd19.PNG)

Apperently you get the **Bear Head** from a _mob drop_, by killing the "**Bear**" mob, who's in the cage underground according to the _Wynncraft Wiki_. 

![bear head wiki](https://user-images.githubusercontent.com/30804859/29034977-544fd2d0-7b9a-11e7-98a5-8db5b9c474b2.PNG)
![bear armour wiki](https://user-images.githubusercontent.com/30804859/29034984-5aafe5de-7b9a-11e7-9931-ce75c55b4ec6.PNG)

I killed the **Bear** multiple times but never got the **Bear Head** even though it says: 

![bear armour wiki](https://user-images.githubusercontent.com/30804859/29035073-b1a8973c-7b9a-11e7-8c5b-d041d53707ca.PNG)

...on the _Wynncraft Wiki_. My guess is that the _Wynncraft Wiki_ is a bit outdated and the **set bonus** Is supposed to include the **Bear Mask** and not the **Bear Head** which is not even an item anymore. I might be wrong, the **Bear** might still drop a very rare item called **Bear Head** but if so, please tell me. I've only killed the **Bear** about 10 times. 

If that's not the case then please update the **set bonus** to include the **Bear Mask** instead of the **Bear Head** 👍 

![bear set text](https://user-images.githubusercontent.com/30804859/29035302-589922a0-7b9b-11e7-9bb7-a77e01c8aa38.PNG)

 I'm thankfull for a response! 

//FieldFuel

**Comment by thecoolkogut4** [comment] 2017-08-07 17:54
Duplicate of #7478

**Closed** 2017-08-07 17:59 UTC
