### ISSUE TITLE
Can't select Mage class

### ISSUE THREAD

**Issue by TheDuderino134** [Wynncraft/Issues#6955] opened 2016-12-21 05:57 UTC
I get an error message in chat whenever I try and select my Mage class. I've tried relogging and stuff

**Comment by LordHelmchen98** [comment] 2016-12-21 15:46
Do you get an error message after selecting your class?
If so it's a duplicate of #5418 and you should take a look on Moe-Ronickah's long post for more information.

**Closed** 2016-12-21 20:46 UTC
