### ISSUE TITLE
Flight in Distress

### ISSUE THREAD

**Issue by oscar081100** [Wynncraft/Issues#3605] opened 2016-01-08 21:42 UTC
title kinda says it. I dont know how to get out. My cords are -461 5 -10602. From what i can see there need a tripwire hook to to activate the command blocks outside. I was doing the Flight in Distress quest. I had just killed the queen and was in the escape tunnel.

OPDATE!
i did /kill and did the quest again. Now in what i think is the last part it wont let me talk to Ackbar. I click and click and nothing happening. It says "Speak to Captain Ackbar about the findings and the battles".

**Comment by Trixter313** [comment] 2016-01-17 20:18
Duplicate of https://github.com/Wynncraft/Issues/issues/3475

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-17 20:18 UTC
