### ISSUE TITLE
guild stats command (loading wrong info)

### ISSUE THREAD

**Issue by Spinner1991** [Wynncraft/Issues#7479] opened 2017-03-04 12:18 UTC
While attempting to view my own guilds stats i get the stats of the guild "Nobody" with no members, also the guild was made 3 years ago while the guild only exists for one day, so its loading info from another (dummy) guild.

http://prntscr.com/efw2e6

**Comment by CalAnders** [comment] 2017-03-04 14:02
"Nobody" happened to my guild. All it took was a couple days (Around 3 for me) to get the correct name of my guild. HOWEVER, I'm not sure if it would work at all because /guild stats are actually broken. My guild is level 26 but displays level 25.

**Comment by ColinRioux** [comment] 2017-03-04 14:52
Duplicate of #3799

**Closed by ColinRioux** 2017-03-04 14:52 UTC
