### ISSUE TITLE
I lost one of the Almuj's Liquified Emeralds on the quest Jungle Fever and now im unable to complete it

### ISSUE THREAD

**Issue by Kapuuu** [Wynncraft/Issues#7579] opened 2017-03-25 11:56 UTC
I wish somebody could help me with this bug i dont know how it disappiered it just was gone.
And I have already tried to dismiss my quest and /fixquests but none of them works

If a administrator member wants to help me my IGN: Kapuuu

**Comment by thecoolkogut4** [comment] 2017-03-25 21:04
duplicate of #5567

**Closed** 2017-03-26 05:22 UTC
