### ISSUE TITLE
The mystery of the non-existant caravan driver

### ISSUE THREAD

**Issue by NotHyper** [Wynncraft/Issues#4257] opened 2016-02-24 21:03 UTC
Just started playing Wynncraft today, few hours ago. I would be continuing to play if there wasn't one critical issue that's putting me off.
The Caravan Driver isn't there. I can't right-click on him, I can't see him. I tried getting past but it just forces me back to interact with a person that isn't there.
Saw some other beginners complaining about the issue too.
I would really love to play as this MMORPG server seems really in-depth and may force me to actually use my Macro keys on my keyboard. (Don't know if that's allowed or not.)

If there's something wrong with my computer, please tell, anything incompatible?
Specs:
Intel Core i7 4790k Quad Core
MSI R9 380 4GB GPU
TP-LINK Wireless PCI Express Adapter
Gigabyte Z97 Gaming-5 Motherboard

Pretty much it, if there's anything incompatible with the server, (probably the wireless adapter), please say it.
You can call me NotHyper.

**Comment by Odnod** [comment] 2016-02-24 21:29
Duplicate of #4254 please close this thread and put additional comments on the original

**Closed** 2016-02-24 21:35 UTC
