### ISSUE TITLE
Quest Bugs

### ISSUE THREAD

**Issue by ItsSixMonths** [Wynncraft/Issues#2832] opened 2015-12-22 06:16 UTC
I'm going to list the bugs I've encountered while attempting quests.
ANGRY VILLAGER Quest - Unable to purchase the potatoes because the merchant isn't selling them.
GREEN GLOOP Quest - Unable to obtain empty bottles because the bottles vanish once they have been used up.
That's all I know of so far, I'll let you know if I find any more.
-SixMonths

**Comment by sambam138** [comment] 2015-12-22 13:45
axacly the green gloop quest is broken pls fix

**Comment by Trixter313** [comment] 2015-12-23 02:15
You now get bottle from a merchant in Ragni. You buy water bottles then drink them to get empty bottles.

And the potato part is a duplicate of #2828 which I believe has been fixed.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Trixter313** [comment] 2015-12-23 16:21
Edit: Water bottles that a drank turn back to water bottles after a few seconds. You get empty bottles as drops from some mobs now. I know for sure the zombies near the identifier on the emerald trail drop them, I've gotten a few from them.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Closed** 2015-12-25 20:34 UTC
