### ISSUE TITLE
Reclaiming the House quest

### ISSUE THREAD

**Issue by Rastin2** [Wynncraft/Issues#3848] opened 2016-01-24 18:58 UTC
I was doing the quest: 'Reclaiming the house' and when I completed it, it said i got 6144 emeralds, which is, over 4096 which is 1 LE, though I only got 63 EB. I don't know if it's a bug or if it's supposed to be like this but a friend of mine says he got 1.5 LE from the quest.

http://imgur.com/ODwd1hq   The link to the screenshot. And yes. the emeralds in my hotbar were indeed the only emeralds I had on me. and as you can clearly see (I also swore because I was kinda mad) it says 6144 emeralds, but instead i got around 4032 emeralds, not counting the 31 I got from killing mobs.

**Comment by Rastin2** [comment] 2016-01-24 18:59
http://imgur.com/QXHIKs8   As you can see, no LE to be found, and yes. this was taken after completion of the quest.

**Comment by Trixter313** [comment] 2016-01-25 03:25
Duplicate of https://github.com/Wynncraft/Issues/issues/3562 where already having emeralds already in your inventory messes with rewards. Try to not have any emeralds, of any kind, in your inventory when finishing a quest. We have a very strict no refunds policy so nothing can be done about the already missed out on emeralds but hopefully this information prevents it from happening again.

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-25 03:25 UTC

**Comment by Rastin2** [comment] 2016-01-25 20:26
I just wantednote out that this happened to me. I don't necessarily need the emeralds. I'm good on them for a while.

**Comment by Trixter313** [comment] 2016-01-27 02:28
To get out you can type /kill with 3+ soul points and you should be teleported to the nearest visited town. =)
