### ISSUE TITLE
I stuck in my Guild and can't leave! 

### ISSUE THREAD

**Issue by GhoulKanekiKen** [Wynncraft/Issues#5267] opened 2016-06-19 18:23 UTC
# Delete this line if you've searched for a duplicate issue first
Hello , i have a Problem,and i know many people have this Bug!
I can't leave my Guild with /guild leave , it just take my soulpoints but i'am still in.
I changed my name , and some guys told me that when you change your name , you stuck forever in it.
So my Question/Hope is , that a Staff Member can kick me out of this Guild!

**Information's:**

Ingamename: lamegame03

Guildname: Black Dagger

Hope for a fast respond ;)

**Comment by Trixter313** [comment] 2016-06-19 18:34
Duplicate of #3665 

There is currently no way for us to get you out of the guild. Please follow the original thread for updates. We'll post there when it is resolved. Thanks!

**Closed by Trixter313** 2016-06-19 18:34 UTC
