### ISSUE TITLE
Problems Connecting to the Server

### ISSUE THREAD

**Issue by RealSurprisingly** [Wynncraft/Issues#8053] opened 2017-05-02 23:37 UTC
IGN: Surprisingly

Problem: I have been trying to connect to the server for the past 3 hours and this error message keeps popping up.

Proof: https://gyazo.com/0a7e89ef879d199ae9c8564e8be32b2e

If anyone could please help that would be great.

**Comment by FSKyuremYT** [comment] 2017-05-02 23:40
I am having the same problem reconnecting as well. My IGN is FSKyuremYT

**Comment by Trixter313** [comment] 2017-05-02 23:50
Duplicate of https://github.com/Wynncraft/Issues/issues/8051

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2017-05-02 23:50 UTC
