### ISSUE TITLE
Insufficent quest reward

### ISSUE THREAD

**Issue by KiRtAp2** [Wynncraft/Issues#7989] opened 2017-04-27 10:30 UTC
I just finished the "Reclaiming the house" quest. The "quest finished" chat message says the reward is 6144 emeralds, although I definitely didn't get as many, I only have a little over a stack of EB in my inventory and I had some there beforehand. I can't reproduce this because I only have one level 61 class at hand.

I have provided images of my chat log and an image of my inventory. I hope you can take my word that I didn't get rid of the emeralds.
![chat1](https://cloud.githubusercontent.com/assets/17317301/25479424/0ff7ec58-2b45-11e7-9558-0c61e6668695.PNG)
![chat2](https://cloud.githubusercontent.com/assets/17317301/25479425/0ff89cf2-2b45-11e7-9923-1ecc0ad03523.PNG)
![invo](https://cloud.githubusercontent.com/assets/17317301/25479426/0ff9f390-2b45-11e7-944a-1c357a8e762b.PNG)

(I'm using tabbychat, hope that's not a bannable offense)

**Comment by LordHelmchen98** [comment] 2017-04-27 13:46
Duplicate of #7040,
Also Wynncraft enforces a strict norefund policy. Therefore you wont get the emeralds.

**Closed by LordHelmchen98** 2017-04-27 13:46 UTC
