### ISSUE TITLE
''You don't have permission for this area.''

### ISSUE THREAD

**Issue by falconite01** [Wynncraft/Issues#5775] opened 2016-08-19 19:12 UTC
When i click the ground i get this message (''You don't have permission for this area.'') , the issue is that i can't interact with my area anymore.
-I'm unable to open loot chests.
-I can click a button, but they don't trigger.
Due to this bug I can't do the quest 'The House of Twain.'
In the quest I need to push a button to open the cellar, but due to this bug the button won't trigger, and the trapdoor to the cellar won't open.
( Sorry if there are any faults in the text, I'm normally not writing english but dutch :| )

**Comment by Trixter313** [comment] 2016-08-19 19:18
Just using an empty hand should work to interact with things.

Duplicate of https://github.com/Wynncraft/Issues/issues/3902

**Closed by Trixter313** 2016-08-19 19:18 UTC
