### ISSUE TITLE
Old Bob Mythics

### ISSUE THREAD

**Issue by IronShovel** [Wynncraft/Issues#7452] opened 2017-02-26 08:53 UTC
I used to play this game about 2-ish years ago and now I'm back, but I can't use any of my Bob Mythics because they are old and are unidentified.
When I go to an identifier, it says that I can't re-identify items that are already identified.

Btw... I still have all of the Old Bob Mythics if I need to do anything with them.

**Comment by Pyromanical** [comment] 2017-02-26 12:44
Duplicate of #6171
From that issue: "I'm sorry to say, but these items are not fixable. You can keep them as mementos, you can throw them away, or give them away, but you can't sell them to another player."

**Closed** 2017-02-26 14:50 UTC
