### ISSUE TITLE
Quest Items still not spawning

### ISSUE THREAD

**Issue by nickmathes** [Wynncraft/Issues#4476] opened 2016-03-06 12:46 UTC
As you may know there was the problem that the quest items were not spawning. I thought it has been fixed because I normally did my quests but now I have the quest "A Marauder's Dues" and one item is not spawning. I looked up videos for the quest so I found out where it was supposed to spawn. I am talking from Norstens Will that Volmor dropped into the cave. When you fall down into the pit of water in  the cave there is a grey carpet and as I have seen in videos Norstens Will is supposed to spawn there but for me it is not working. I know the old problem was not from Wynncraft but now that it has been fixed it might be something else. PS: Pls dont just say "Duplicate of (the number of the old bug)" and give me a link because the old bug has been fixed and this is new.
Ty for now, Nick

**Comment by BasicallyNothing** [comment] 2016-03-06 14:21
There's no need reporting this "issue", it's being worked on and this has been reported 80+ times already.

**Comment by Moe-Ronickah** [comment] 2016-03-06 14:46
Please, read the original thread in its entirety.
Duplicate of #4236

**Closed by Moe-Ronickah** 2016-03-06 14:46 UTC
Labels: Duplicate
