### ISSUE TITLE
Armor loss glitch+ Skin change

### ISSUE THREAD

**Issue by Trasque370** [Wynncraft/Issues#5342] opened 2016-06-29 04:58 UTC
When I was mob grinding in the jungle dungeon, the server closed. I went back on in a different world and insaintly died! No big deal, untill I look at my inventory and find that all of my armor is missing!!! And to make matters worse, my skin is changed to a skin that was in the older version of wynncraft where your skin is changed. I tryed to relog and nothing helped. I had really good armor and some of it was even legendary! I hope you fix this glitch, for I have had it happen multiple times!

**Comment by Moe-Ronickah** [comment] 2016-06-29 22:33
I believe that this is a duplicate of #4199 .  Please follow this report on that issue.

**Closed** 2016-06-29 22:33 UTC
Labels: Duplicate
