### ISSUE TITLE
Can't remove certain unobtainable items from my ender chest

### ISSUE THREAD

**Issue by Omirolf** [Wynncraft/Issues#4880] opened 2016-04-23 09:32 UTC
Somehow, during the beta, I managed to put the 'under development' character info compass, under development quest book and a stack of arrows into my ender chest. I stopped playing for a while, and when I tried to remove them after, I couldn't remove the compass or arrows, only the book. I've gotten rid of the book, but the compass and arrows are still stuck in my ender chest. Is there a way to remove them? Thanks! I've attached some screenshots.
EDIT: Forgot to add that the items won't move from their position, and will go back whenever I try to take them out or move them.
![2016-04-23_19 28 12](https://cloud.githubusercontent.com/assets/18628052/14760535/f23df73a-0989-11e6-8949-f7f24b4fccfc.png)
![2016-04-23_19 28 14](https://cloud.githubusercontent.com/assets/18628052/14760536/f288bdba-0989-11e6-9f58-9d616f5c85e6.png)

**Comment by Trixter313** [comment] 2016-04-23 13:21
Duplicate of https://github.com/Wynncraft/Issues/issues/3147

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-23 13:21 UTC
