### ISSUE TITLE
Quest Item Glitch + Life and Mana Steal

### ISSUE THREAD

**Issue by Strikefire150** [Wynncraft/Issues#4369] opened 2016-03-01 03:10 UTC
Quest Item: When going to a few quests (like Pirates Trove and Wynncraft Excavation Site C), the items don't spawn. I've changed servers and there was no items whatsoever. This is annoying as that I can't finish my quests.

Life Steal: Life and mana steal doesn't work in anyway. I've tried doing this a bunch of times, and I can't get it to work. This is also annoying as I'm an archer, and I rely on life and mana steal for quick refresher.

(This is for my sister as these things are happening to her...)

**Comment by SwisiestSix** [comment] 2016-03-01 09:27
Yes I had the same problem, not with any of your quests. But with the quest "The Ultimate Weapon", "Aldorei's Secret: Part 1" and "Purple And Blue". All those quests need a item that you can pick up. In The Ultimate Weapon you need Soft Whetstone, that doesn't spawn. In Aldorei's Secret you need the sunflowers seeds, that don't spawn. And in Purple And Blue you need to pick up the magical Crystals, that don't spawn. Really annoying to do 3 quests after each other that I can't finish. And I now can't do "Aldore's Secret: Part 2" too. PLZ Do something about it. Leveling takes so long now when I can't finish quests.

**Comment by DarkDemonDragon** [comment] 2016-03-01 13:09
@Strikefire150 Life/ Mana Steal have been NERFED. They no longer work as they used to and are very ineffective now, especially with archer. I'll give you a brief summary, but you should check out the forums for further details.

Steal BEFORE
Per Melee hit
Per-Some Spell Hit depending on the spell
Per Poison Dmg

Steal NOW
Chance based Melee hit that calculates based off the weapon speed. Basically it'll work around every 2 seconds or so if you constantly hit enemies.
Does NOT work with Spell
Does NOT work with Poison

Hopefully this helped explaining how Life/Mana Steal works now. As for the quest item, this is a duplicate of #4236 Please close this issue as the 1st part is a duplicate of an already made issue and the 2nd part is an intentional game mechanic.

**Closed** 2016-03-01 13:43 UTC
