### ISSUE TITLE
Identifier deletes item when you have full inventory

### ISSUE THREAD

**Issue by 0Patrick0** [Wynncraft/Issues#3484] opened 2016-01-02 23:19 UTC
Earlier today, I was identifying some items. I had a full inventory and paid in Emerald Blocks. When paid for, the EB are turned into emeralds, and any not used are put into the inventory, using up a slot that used to hold one of the items. Once identified, and taken out of the GUI, the last items taken out gets deleted due to there being no space in your inventory. The Identifier says that he dropped the items on the floor, but clearly that doesn't happen. This has happened twice to me so far, the first time being about 2 days prior to today. I remember when this was working, but for some reason it does not anymore. I don't care too much for the items, and the refund policy prevents me from getting them back anyway, but just please fix this issue so that it doesn't happen to people that don't know about it. Thank you.

**Comment by Trixter313** [comment] 2016-01-30 04:18
Duplicate of https://github.com/Wynncraft/Issues/issues/3153 where items are delted instead of dropped on the ground.

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-30 04:18 UTC
