### ISSUE TITLE
Horse lagg

### ISSUE THREAD

**Issue by MaerPerx** [Wynncraft/Issues#5331] opened 2016-06-28 11:44 UTC
http://cs636131.vk.me/v636131368/16880/FA9tR00CM6k.jpg (my friend see me)
http://cs633230.vk.me/v633230752/32140/vEYRPa2h6-o.jpg (me)

**Comment by Trixter313** [comment] 2016-06-28 13:13
Duplicate of https://github.com/Wynncraft/Issues/issues/5188

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-06-28 13:13 UTC
