### ISSUE TITLE
Respawn issues in Llevigar Plains.

### ISSUE THREAD

**Issue by feedonswords** [Wynncraft/Issues#3516] opened 2016-01-03 22:00 UTC
If you die in the parkour part of the quest "Green Skinned Trouble", you respawn in the area in which you start the game. (The place before Ragni)

**Comment by SioN-wynncraft** [comment] 2016-01-05 16:12
I died inn boss fight and it took me there too

**Comment by meatloaf4311** [comment] 2016-01-21 00:33
Wow, that would really stink, but I believe that if the game does not log you ever going to LLevinger, that is the closest spawn location

**Comment by Trixter313** [comment] 2016-01-21 11:56
Duplicate of https://github.com/Wynncraft/Issues/issues/3617

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-21 11:56 UTC

**Comment by NyanCatZ06** [comment] 2016-05-02 22:36
I died while doing a quest in Llevigar Plains and got teleported there too
