### ISSUE TITLE
Olux's Prized Bow spams a message when used on nearby blocks

### ISSUE THREAD

**Issue by enderbiscuit** [Wynncraft/Issues#7922] opened 2017-04-18 01:36 UTC
Olux's Prized Bow spams a message when I right-click blocks while holding it.  The message is as follows:
"You don't have permission for this area."
This message does not show up when I hold other bows while right-clicking blocks.  Please fix this, it's really annoying when I'm shooting at bugs (or any small ground mob) or opening a door/fence gate while holding it.  My chat gets filled with this message after just a few seconds of doing any of the previously mentioned actions.

**Comment by thecoolkogut4** [comment] 2017-04-18 01:37
It is because the item you were using is a retextured half-slab, and the game thinks you were trying to place it, so it says you don't have permission to. To fix this right click with a empty hand or your soul point.

**Comment by enderbiscuit** [comment] 2017-04-18 01:41
I right-clicked with an empty hand and a soul point, but when I use the bow on a block again the message shows up again.  I should mention that the message only gets spammed when I'm right-clicking.  It stops when I stop.

**Comment by enderbiscuit** [comment] 2017-04-18 01:42
And I know that it's a wooden slab.

**Comment by thecoolkogut4** [comment] 2017-04-18 01:43
duplicate of #3902

**Comment by enderbiscuit** [comment] 2017-04-18 01:44
You could have said that first...

**Closed** 2017-04-18 01:45 UTC
