### ISSUE TITLE
Stuck in a 2x1 hole (2 blocks deep)

### ISSUE THREAD

**Issue by Beast-Raptar** [Wynncraft/Issues#8496] opened 2017-06-30 17:58 UTC
Hi. I was exploring, doing some parkour, near the gate of Ragni. Like, the very first gate, where you enter at the beginning of the game. I climbed up the mountain, and fell into this hole next to a huge tree. There's no way of getting out, since I don't have a teleportation scroll or anything that can get me out.

Tried doing /hub then going back in (dk why I thought that would work) and now I'm stuck in the floor of this hole, can't even move.

As you can probably deduce, a very annoying bug. I know you'll be trying your best to fix it.

![2017-06-30_20 57 05](https://user-images.githubusercontent.com/29802929/27748114-c929480c-5dd6-11e7-9728-04684b2e39c6.png)
![2017-06-30_20 57 03](https://user-images.githubusercontent.com/29802929/27748115-c93853b0-5dd6-11e7-97fb-3eff9df39073.png)
![2017-06-30_20 56 53](https://user-images.githubusercontent.com/29802929/27748116-c943df64-5dd6-11e7-89a4-d52ae494f181.png)

I also know the pics are pretty much useless, but they should give a certain sense of credibility.

**Comment by PepinhoJp** [comment] 2017-06-30 18:51
Duplicate of #88
Please check for duplicates before posting a thread.

Report holes here:
https://forums.wynncraft.com/threads/community-project-filling-holes-open-0-closed-103.123931/

**Comment by LordHelmchen98** [comment] 2017-07-03 17:28
If you are still stuck you can do `/kill`.

**Closed by LordHelmchen98** 2017-07-03 17:28 UTC
