### ISSUE TITLE
Flight in Distress error

### ISSUE THREAD

**Issue by NatsuSchultz** [Wynncraft/Issues#3545] opened 2016-01-05 05:17 UTC
After killing the Pirate Queen and going down the escape hatch, I arrived to a strange black box with a completely useless tripwire inside, I do not think this is part of the quest, mind fixing?

**Comment by Jenoma** [comment] 2016-01-05 15:13
i got that error too, i did /kill but quest is broken now

**Comment by NatsuSchultz** [comment] 2016-01-05 16:32
A bit upsetting since I /kill (ed) and went all the way back through the extremely colorful, but inconvenient quest instances to arrive to the same box :/. Anyways, hope I'll be notified when its fixed.

**Comment by Trixter313** [comment] 2016-01-17 20:16
Duplicate of https://github.com/Wynncraft/Issues/issues/3475

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-17 20:16 UTC
