### ISSUE TITLE
Weapon Fierté having incorect lore.... (Fierté not working)

### ISSUE THREAD

**Issue by Mooshy** [Wynncraft/Issues#3856] opened 2016-01-25 14:09 UTC
My Fierte has a glich that it only has a lore thats purple and it looks like this: https://gyazo.com/67bd17392e2b444ad2b88c658f0e4a63 (could not fit everything in one picture...)
My username is: MooshyCreeper
please fix this the item will be in my inventory...

**Comment by Odnod** [comment] 2016-01-25 16:00
This is a known issue caused by symbols in the name. Similar examples can be seen in other items such as Montefiore. The is no way to fix it at the moment.

**Comment by Dar-krusos** [comment] 2016-01-25 23:54
Duplicate of #3175

**Comment by DarkDemonDragon** [comment] 2016-01-26 13:18
All items with special characters are bugged. Reminiscent of a REALLY old bug that I can't believe hasn't been fixed yet.

**Closed** 2016-01-27 02:25 UTC
