### ISSUE TITLE
ARMOR WONT SHOW TRIED EVERYTHING

### ISSUE THREAD

**Issue by Kirito728** [Wynncraft/Issues#3862] opened 2016-01-25 22:19 UTC
I am writing this because this is very annoying. I want to see my armor because i want to look beast but  i cant see it and neither can other people i am really mad because i thought the armor is cool with the custom textures. PLEASE HELP!!!!! PLEASE!!!!

**Comment by Dar-krusos** [comment] 2016-01-25 23:57
Are you using the latest version of minecraft? You need this to be able for them to show. If this is not the problem, try checking if you have turned off overlay in the Skin Customization menu [ESC > Options > Skin Customization]

**Comment by DarkDemonDragon** [comment] 2016-01-26 13:21
Who in the world gets so angry over cosmetics? o.O

**Comment by mickymaster24** [comment] 2016-01-30 14:48
DarkDemonDragon Beauty Gurus xD

**Comment by Trixter313** [comment] 2016-01-31 16:58
Are you still experiencing the issue? There has been a patch since you reported the issue and it might have fixed the issue.

**Comment by Trixter313** [comment] 2016-01-31 17:10
Duplicate of https://github.com/Wynncraft/Issues/issues/3739

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-31 17:10 UTC
Labels: Duplicate, Game Mechanics
