### ISSUE TITLE
Lost Archer ;-;

### ISSUE THREAD

**Issue by MaPaJe** [Wynncraft/Issues#4401] opened 2016-03-02 17:31 UTC
I'd a lvl 26 archer the next morning i logged on it wasnt there. Please anwser back ;-;

**Comment by Odnod** [comment] 2016-03-02 18:23
Is there a chance that you unintentionally deleted it?

**Comment by MaPaJe** [comment] 2016-03-02 18:53
No No there's not

**Comment by MaPaJe** [comment] 2016-03-02 18:54
All my Classes were gone execpt for Assassian

**Comment by DarkDemonDragon** [comment] 2016-03-02 19:55
There are 2 probably scenarios:
1) Someone else has access to your Minecraft account
Either someone hacked in or you let someone use your account and that person deleted the classes.

2) You have more than 1 Minecraft account
Make sure that you're checking the right account if you have alt accounts or have access to other accounts.

Unfortunately once your classes have been deleted it will be nearly impossible to recover. Since it was only level 26 just start fresh or with your assassin and move on from there. If you feel that Wynncraft was somehow related to this and that this was the cause of a major bug feel free to add some details of the situation. However, if this is an outside matter there is nothing more that Wynncraft staff can do for you and you'll be asked to close this issue as this is not a bug, but a matter not directly related to Wynncraft.

**Comment by MaPaJe** [comment] 2016-03-02 20:39
I lost 2 of my other classes no 1 has my account i only have 1 account

**Comment by liual1** [comment] 2016-03-05 09:05
So i had the same problem, i played wynncraft yesterday until midnight with my lvl 54 archer account, logged off. And the next morning the account is gone!!!! and no, i did not delete it... I just logged off as normal and now its gone. pls help me .. its my main account.

**Comment by Trixter313** [comment] 2016-03-05 16:22
Unfortunately Wynncraft has a strict no refunds policy so there's nothing we can do to get back the lost classes. I'd suggest changing your Minecraft and the associated email's passwords because the only explanation for this that I can think of is that your Minecraft account was hacked and someone else logged on as you and deleted the class. Hopefully that prevents this from happening again!

**Closed by Trixter313** 2016-03-05 16:22 UTC

**Comment by MaPaJe** [comment] 2016-03-13 17:01
Trixter Nothing of what u said had happened WynnCraft its just not prefect. Why dont u say that instead of kying to me mate

**Comment by DarkDemonDragon** [comment] 2016-03-13 17:03
I'm sorry @MaPaJe but what's your proof that this is Wynncraft's fault?

**Comment by MaPaJe** [comment] 2016-03-13 17:11
Look i dont care about my archer the only thing i wanted was an apoligize and u finally gave me 1 thanks DDD

**Comment by MaPaJe** [comment] 2016-03-13 17:13
Or yes for 11 days ago i did but now i just'd stop playing on it and stop telling more ppl about it cuz i dont want em to lose theres class  as well
