### ISSUE TITLE
Guild Creating PRoblums

### ISSUE THREAD

**Issue by edmundsa** [Wynncraft/Issues#3372] opened 2015-12-30 22:34 UTC
so when i tryed to make a Guild Called http://prntscr.com/9kg0so or even if i try http://prntscr.com/9kg11b it just keeps saying http://prntscr.com/9kg1bm

**Comment by Trixter313** [comment] 2015-12-30 23:40
Duplicate of https://github.com/Wynncraft/Issues/issues/3190

Please direct any further comments to the original thread. Thanks!

**Closed by Trixter313** 2015-12-30 23:40 UTC
