### ISSUE TITLE
Seasail Message Glitch

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#7111] opened 2017-01-05 19:29 UTC
I was at Llevigar, I bought a boat pass to Pirate Cove. I went onto the V.S.S Seaskipper and threw it into the hopper. For some reason a message showed up in the chat four times in a row.
Screenshot: http://imgur.com/a/9Nhnm

PS. I only tried the Boat Pass once, I don't know if this is a one time thing,

- Annoying

**Comment by DebugingLonks** [comment] 2017-01-05 19:34
Duplicate of #6407 #6684 please avoid duplicates. No fix is available at this time.

**Closed** 2017-01-05 19:52 UTC
