### ISSUE TITLE
Completely unable to leave my guild  (the guild is called Deluxe

### ISSUE THREAD

**Issue by Ilgynoth** [Wynncraft/Issues#7019] opened 2016-12-27 15:52 UTC
so i cant leave my guild, when i type /leave and type yes into the sign, it takes away my soul points but it doesnt let me leave, can a staff member kick my old usernames from the guild? (also i think im the only active player in this guild) you might have to kick me from the guild twice actually, when i do guild list one of my past usernames (CelestialScythe) appears twice

**Comment by Ilgynoth** [comment] 2016-12-27 15:53
and im thinking about opening a guild with my friends, but the game doesnt allow me to start one because of this guild bug

**Comment by thecoolkogut4** [comment] 2016-12-27 16:14
since you changed your name while being in a guild, your stuck. currently there is nothing you can do to get out of the guild. the devs are working on  this issue and it should be fixed in the next coupple of months.

**Comment by Trixter313** [comment] 2016-12-28 00:45
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

**Closed by Trixter313** 2016-12-28 00:45 UTC
