### ISSUE TITLE
Quest reseting

### ISSUE THREAD

**Issue by CreamPnada** [Wynncraft/Issues#2028] opened 2015-06-23 06:16 UTC
I finished searching the tomb in the WynnExvacation Site A and found the egg thingy. When I talk to Vade it's telling me to translate the paper still. When I didn't know what to do while searching the tombs I talked the Vade and he said bla bla bla Get out of here or something. What do I do, I tried reseting and talking to the person who translates that paper and went back. Nothing.

**Comment by Moe-Ronickah** [comment] 2015-06-23 16:37
This is a duplicate of #1415 .

Please read that report and follow the advice there.  If it works for you, would you please close this issue?
Thanks.

**Closed** 2015-06-27 14:21 UTC
