### ISSUE TITLE
Skill points

### ISSUE THREAD

**Issue by OMGitsTomix** [Wynncraft/Issues#4292] opened 2016-02-26 15:20 UTC
Hello,today I loged to wynncraft and In chat i saw a message about that i dont have enought skill points to wear my armor,lost my crystal leggings.I only found my bracelet and someone found my chestplate and gave it back to me.Fix it,I dont want to lose my armor again. http://i.nahraj.to/f/1mJY.png

**Comment by Odnod** [comment] 2016-02-26 15:49
Duplicate of #4120, please close this topic and direct any additional comments to the original post. Thanks!

**Closed** 2016-02-28 17:38 UTC
Labels: Duplicate
