### ISSUE TITLE
got 0 skill points as level 80 and lost my armor

### ISSUE THREAD

**Issue by Hayamaka** [Wynncraft/Issues#4567] opened 2016-03-16 22:03 UTC
# Delete this line if you've searched for a duplicate issue first
http://imgur.com/8NtygZW here's a screenshot if you dont believe me

**Comment by Trixter313** [comment] 2016-03-17 01:03
Duplicate of #4120 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-17 01:03 UTC
