### ISSUE TITLE
About the Quest : Crop Failure

### ISSUE THREAD

**Issue by Nagisa-Blue** [Wynncraft/Issues#3855] opened 2016-01-25 09:52 UTC
![2016-01-25_17 45 35](https://cloud.githubusercontent.com/assets/16876998/12547606/423b3d90-c38c-11e5-91c7-4727613a3efc.png)
![2016-01-25_17 50 51](https://cloud.githubusercontent.com/assets/16876998/12547605/423847ac-c38c-11e5-8186-123dc7492cac.png)
Well,after im finish the quest Crop Failure,i notice that the chat said it will give me 640 emeralds,but in my inv and hotbar,there is only 6 Emerald blocks...so I want to see if I can get a refund(?) or the server team can fix it,thank you
Minecraft Player Name : Nagisa_Blue
Date:25/1/2016(Asia Time,Hong Kong)

**Comment by Trixter313** [comment] 2016-01-27 02:25
Duplicate of https://github.com/Wynncraft/Issues/issues/3562
Having emeralds in your inventory can mess with any quest rewards.
Please direct any further comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-27 02:25 UTC
