### ISSUE TITLE
Relic Dagger can't identify's

### ISSUE THREAD

**Issue by skay159357** [Wynncraft/Issues#2165] opened 2015-08-04 17:37 UTC
Hey WynnCraft
I cant identify my Relic Dagger it just says " I'm afraid I can't identify this item! Only weapons and armours with a unique, rare, legendary, and speacial tags can be identified" i dont get this message bc the Relic dagger is a Legendary item so why cant i just identify it? 

-SkayTheMan

**Comment by Trixter313** [comment] 2015-08-04 20:22
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

We recommend closing the duplicate and following the original to stay up to date on the status of the issue. Thanks!

**Closed** 2015-08-17 07:08 UTC
