### ISSUE TITLE
lost ALL my items for no reason

### ISSUE THREAD

**Issue by Microbuilder1** [Wynncraft/Issues#5056] opened 2016-05-22 15:11 UTC
I was walking in a town or hut place and I had 2 soul points so then I didnt want to play anymore and I got off then my friend jasmineann told me get back on I got back on but then I noticed something my stuff was all gone I was like wtf I was not getting attacked by anything I didnt die when I logged off so I would like if u guys can refund all my stuff back I dont know how you are gonna do it but it would mean alot to me to check and try to get my stuff back . BTW I have proof if you search up Kamcord it is a streaming service I have a video on me streaming your server and I had all my gear BTW if you wanna see proof a video just search my name : Alphagear1 Thanks guys hope I can get my stuff back.

**Comment by YunoFGasai** [comment] 2016-05-22 19:54
This is a duplicate of #4814 please refer all future comments to the original thread. 
Wynncraft has a no refund policy, sorry for your stuff.
I'm sure some people in WC1 would be glad to sell you some new gear.

**Closed** 2016-05-22 23:09 UTC
