### ISSUE TITLE
Guild capture/defense problems

### ISSUE THREAD

**Issue by ConSavvy** [Wynncraft/Issues#6451] opened 2016-10-23 21:05 UTC
Our guild, The Mythic Squad captured the Llevingar entrance and got the captured message, but we couldn't place down defenses because we "didn't capture it". Anyone know what is going on?

**Comment by thecoolkogut4** [comment] 2016-10-24 03:50
llivigar enterance is glitched, currently no one can claim it and hold it.

**Comment by Trixter313** [comment] 2016-10-26 00:37
Duplicate of https://github.com/Wynncraft/Issues/issues/6050

**Closed by Trixter313** 2016-10-26 00:37 UTC
