### ISSUE TITLE
Entire inventory lost after disconnecting from server.

### ISSUE THREAD

**Issue by robdb** [Wynncraft/Issues#5328] opened 2016-06-27 23:22 UTC
NOTE: May be a duplicate of this #4814 

Issue is stated here: https://forums.wynncraft.com/threads/my-entire-inventory-deleted-need-moderator.133875/

While traveling from Nemracht I climbed up a tower, disconnected. At the time I had max soul points. I rejoin two hours later to an empty inventory and back in Nemracht.

**Comment by Moe-Ronickah** [comment] 2016-06-28 03:58
It is a duplicate of #4814 , as you suspected.  However, I've got a few questions.

Did you leave your game open when you left?
Is it possible that someone else used your player while you were gone?
The tower that you went up in Nemrackt, was there a guard in it?
Were you playing on any version of MC 1.9 or 1.10?

**Closed** 2016-06-28 03:58 UTC
Labels: Duplicate
