### ISSUE TITLE
Beneath The Depths

### ISSUE THREAD

**Issue by yairkaraso** [Wynncraft/Issues#3981] opened 2016-02-04 13:39 UTC
The last boss ALLLL the time teleport to Lava Why is that???? and all the place is full of lava Pls help

**Comment by Trixter313** [comment] 2016-02-05 18:29
Duplicate of https://github.com/Wynncraft/Issues/issues/3933

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-05 18:29 UTC
