### ISSUE TITLE
Stone Slab Wand?

### ISSUE THREAD

**Issue by CaptainCheese55** [Wynncraft/Issues#4871] opened 2016-04-22 03:07 UTC
Not sure if this is an error on my part, but this wand I found called Kelight's Toothbrush appears as a stone slab in my inventory. I appreciate any help that can be given.
![2016-04-21_22 01 07](https://cloud.githubusercontent.com/assets/18607047/14730566/51c4d80a-080d-11e6-8cb6-bec4c6f8dfdd.png)

**Comment by nont43** [comment] 2016-04-22 05:31
nevermind just kinda resourcepack glitch. try refresh your network router then join again.

**Comment by Trixter313** [comment] 2016-04-22 10:57
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-22 10:57 UTC
