### ISSUE TITLE
Hub Glitch

### ISSUE THREAD

**Issue by ImASandwich** [Wynncraft/Issues#6477] opened 2016-10-27 23:21 UTC
Whenever I do /hub to return to the server hub, and when I log on to the server sometimes, I receive the message "Flying not allowed on this server." It then gives me a loading screen for a few seconds, then repeats without end. When it does this it is very hard to log off of the server, as I'm only allowed about a half-second to interact with the game before the load screen takes over; sometimes I have to alt+f4 and close the game entirely. The same thing happened to my friend once, so I'm sure this is not a rare thing

My client is not hacked or modded in any way, except with Optifine, nor am I using any other method to gain unauthorized abilities or permissions in multiplayer servers.

**Comment by MrRedCrack** [comment] 2016-10-28 03:47
That happens to players who have bad connection to the server.

**Comment by Trixter313** [comment] 2016-10-28 10:57
Duplicate of https://github.com/Wynncraft/Issues/issues/5289

**Closed by Trixter313** 2016-10-28 10:57 UTC
