### ISSUE TITLE
The maiden tower quest bug

### ISSUE THREAD

**Issue by finlayj123** [Wynncraft/Issues#2834] opened 2015-12-22 07:04 UTC
I am attepting the new quest "The Maiden Tower" in the Gavel update. I have completed the puzzle in the catacombs and have killed the Cursed Warlock who drops a chainmail helmet named "Dark Veil", which you must bring to the NPC by the tower, Erlard. However Erlard will not take the helmet and informs you that you need to go and get it which has already been done. I think this might be because the item is a normal item as opposed to a quest item.
![2015-12-22_18 02 20](https://cloud.githubusercontent.com/assets/11471605/11949762/5e56ac6a-a8d6-11e5-8a74-615749173e04.png)
This is a screenshot of said helmet.
Thank you for looking into this.
-Finlay

**Comment by mirajhall** [comment] 2015-12-22 08:39
This is not a bug, all you have to do is put on the "veil" and you can enter the tower.

**Comment by finlayj123** [comment] 2015-12-23 01:22
Thank you very much, I din't even think of that.

**Comment by mirajhall** [comment] 2015-12-23 01:22
No problem, don't forget to close the issue :)

**Closed** 2015-12-25 20:34 UTC
