### ISSUE TITLE
Texture Issue (Percision and Harpoon)

### ISSUE THREAD

**Issue by SilverWolfeh** [Wynncraft/Issues#6589] opened 2016-11-05 16:48 UTC
Both Bows have turned into textured wood slabs, Precision is spruce and Harpoon is Oak

**Comment by Trixter313** [comment] 2016-11-05 21:24
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

**Closed by Trixter313** 2016-11-05 21:24 UTC
