### ISSUE TITLE
Item Bug and quest that can't be done

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#4415] opened 2016-03-03 14:19 UTC
[I've discovered a glitch/bug on the WynnCraft server which makes multiple quests impossible to do.
Quests:
1. Spider Cave | Saccharum Plants doesn't drop at the bottom of the cave.
2. Sister City | Hourglass Sand doesn't spawn in Selchar.
3. Suspended Flowers | Aerolia flowers doesn't spawn.] DUPLICATE OF #4236 

An other thing is that the quest where you have to talk to The Assistant at Black Road is impossible.
He says he wants 3 x Potion of Healing I. Potion of Healing I doesn't exist anymore, and when you try with the worst type of Healing potion it appears to be the wrong item.

**Comment by Odnod** [comment] 2016-03-03 14:53
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

Also I have done that quest twice since Gavel was released, just use the worst tier you can find in Detlas.

**Comment by BasicallyNothing** [comment] 2016-03-04 15:01
Its a new bug, it didnt come with the gavel expansion. It came a few days ago.

**Comment by Odnod** [comment] 2016-03-04 17:12
@BasicallyNothing, the first bug is very recent and has been reported over 70 times now. The second one is not a bug, but rather a mistake in the writing. Just take the lowest tier of healing potion you can find in Detlas.

**Comment by BasicallyNothing** [comment] 2016-03-04 21:25
Yes, I understand, but I have the lowest tier of Healing Potions, it still wont work. I dont get that part.

**Comment by BasicallyNothing** [comment] 2016-03-04 21:25
And what can you do about the Item bug?

**Comment by Moe-Ronickah** [comment] 2016-03-05 05:40
I'd like some confirmation on this please, such as a screen cap.

**Comment by McSeed** [comment] 2016-03-05 23:35
You can buy Potion of Healing I in Ragni at the potion shop. They are those who gave you 10 healing point.

The others problem are common. They try to fix them.

**Comment by BasicallyNothing** [comment] 2016-03-05 23:43
McSeed, it's fixed now, but I tried what you just said and it wouldn't work because that item had another name. It was updated, unlike the quest.

**Comment by BasicallyNothing** [comment] 2016-03-05 23:44
Moe-Ronickah I can't give a screenshot about items not dropping, after all it's been reported about 80 times already and they're working on it. Screencap of that wouldn't help it out by a bit.

**Comment by Moe-Ronickah** [comment] 2016-03-06 14:41
I edited and separated your original post, separating the duplicate from the issue concerning the potions.
As the potion issue is now fixed, I'm closing this issue.

**Closed by Moe-Ronickah** 2016-03-06 14:41 UTC
Labels: Quests

**Comment by BasicallyNothing** [comment] 2016-03-07 13:53
Okey
