### ISSUE TITLE
Some Bug with the "Grave Digger" Quest.

### ISSUE THREAD

**Issue by SpriteDew** [Wynncraft/Issues#4781] opened 2016-04-09 17:20 UTC
When you talk to the priest in the quest, he'll say that you need 24 rotten flesh to access the tomb. But if you click on him again after he says that, he'll say:
![2016-04-09_09 52 30](https://cloud.githubusercontent.com/assets/16402018/14405141/aecc6c96-fe3c-11e5-9c6f-e13e4bd3e388.png)

**Comment by Trixter313** [comment] 2016-04-09 17:45
Duplicate of https://github.com/Wynncraft/Issues/issues/4638

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-09 17:45 UTC
