### ISSUE TITLE
 Decrepit Sewers

### ISSUE THREAD

**Issue by SharonMoshe** [Wynncraft/Issues#8214] opened 2017-05-23 15:44 UTC
inside the  Decrepit Sewers after i open the first door ther a text coming up whits say
 you continue to trespass my territory? you must have no value for your life
end i cant go thru ther it stops me end i see other players go thrue

**Comment by ThePewPewLayzr** [comment] 2017-05-23 16:09
#6340

**Comment by ThePewPewLayzr** [comment] 2017-05-23 16:10
Duplicate of #6340

**Closed** 2017-05-28 15:31 UTC
