### ISSUE TITLE
Jester Set Bonus Broken

### ISSUE THREAD

**Issue by ohyeah1357** [Wynncraft/Issues#3787] opened 2016-01-20 01:24 UTC
The Jester Accessory set bonus is broken if 2 or more pieces are present. To prove this, get a full set of jester gear and wear 2 pieces or more. You will notice that the XP reduction is gone, and you will not have health bonuses/negatives.

[Imgur](http://i.imgur.com/W8S3mdZ.png)

**Comment by Dar-krusos** [comment] 2016-01-20 02:17
I'm pretty sure that this is how it is supposed to be. It would make sense if it is supposed to be that, if you don't have the full set, your stats will be hindered.

**Comment by ohyeah1357** [comment] 2016-01-20 05:54
Quoted from Dar-krusos
>I'm pretty sure that this is how it is supposed to be. It would make sense if it is supposed to be that, if you don't have the full set, your stats will be hindered.

>Please provide screenshots, as pictures do speak more than 1000 words and are immensely helpful.

First off, I will say it's not how it's supposed to be, and will provide screenshots like requested. I believe you misread my description of the bug. When wearing 2 or more pieces, the entire set bonus is cancelled.
Also, I believe screenshots alone will not prove the bug. It will take another user who has a full jester set to reproduce the bug, most who have the set should know this. The set is not particularly rare.

**Comment by DarkDemonDragon** [comment] 2016-01-20 13:11
@ohyeah1357 I can confirm this is an issue. I think players have begun to notice this as there has been a recent rise in Jester trading. Even only wearing the necklace only may sometimes provide just the buffs and not the de-buffs though this isn't as consistent. 

@Dar-krusos the way the Jester set is supposed to work is that each stage of wearing gives different set bonuses.
 
1/3 Jester Set bonus: -35% Loot Bonus -35% Xp bonus
2/3 Jester Set Bonus (don't remember some values so I use "x"):
-75% Loot Bonus
-75% Xp bonus
+200 Melee Damage
+ X Hp
- X Walking Speed

I don't know 3/3 Jester Set bonus.

These "Set Bonuses" are to balance the Jester Set as it is merely Unique yet can have very unusually high IDs. A good Jester Necklace gives 50+ Loot Bonus 50+ Xp Bonus and 2/2 Mana Steal. The Jester Ring gives 2-4 in FOUR skills and a good one gives 30+ in both Loot and XP. This is a very powerful set even with the Debuffs. It's perfect for Lv 100s as the main debuffs are in Loot and XP with some minor debuffs in Spell Dmg and Walking Speed.

**Comment by DarkDemonDragon** [comment] 2016-01-20 18:44
Sorry I just realized this is a duplicate of #3687 Please close this issue and follow that one.

**Closed** 2016-01-20 19:05 UTC
