### ISSUE TITLE
Can't select my Mage Class

### ISSUE THREAD

**Issue by DerClassic** [Wynncraft/Issues#7705] opened 2017-04-08 11:03 UTC
Hey there, I can't select my Mage Class. Every other class is working as normal but since this morning I can't select my Mage Class anymore. I need help to fix this. Thank you
![ss 2017-04-08 at 12 59 10](https://cloud.githubusercontent.com/assets/27062675/24828367/932ef650-1c5b-11e7-9253-edfb2842a88c.jpg)

**Comment by RLLL93** [comment] 2017-04-08 11:11
I have the same problem with my 55lvl Assassin
Mabye it is with the place where you've logged of, can you tell me the place?

**Comment by DerClassic** [comment] 2017-04-08 11:21
I was in LLevigar...

**Comment by RLLL93** [comment] 2017-04-08 11:28
Me too
or somewhere near

**Comment by numbermaniac** [comment] 2017-04-08 11:39
#7702

**Comment by WindShadow22662** [comment] 2017-04-08 14:56
I can't log into my mage as well its lvl 78 and i wanted to play

**Comment by WindowsEXE** [comment] 2017-04-09 06:58
The class may possibly be corrupted... same thing with my warrior at level 21

**Comment by ColinRioux** [comment] 2017-04-09 19:05
Duplicate of #7680. Please see there for future updates.

**Closed by ColinRioux** 2017-04-09 19:05 UTC
