### ISSUE TITLE
Cowfusion Cutseen

### ISSUE THREAD

**Issue by opps123456789** [Wynncraft/Issues#4112] opened 2016-02-13 17:40 UTC
During the cowfusion quest, after I make my way through the cave after exploding tnt into the wall, I end up in a cutseen but the cutseen doesn't seem to work. I've had to do /kill many times and it's a pain. PLEASE FIX

![2016-02-13_09 39 24](https://cloud.githubusercontent.com/assets/16432130/13029047/b6947c6c-d235-11e5-85a2-307d0bfa2896.png)
It's stuck

**Comment by Trixter313** [comment] 2016-02-13 18:06
Duplicate of https://github.com/Wynncraft/Issues/issues/4108

Please direct any future comments to the original thread. Thanks!

**Closed** 2016-02-13 18:06 UTC
Labels: Duplicate
