### ISSUE TITLE
Mage meteor ability bug

### ISSUE THREAD

**Issue by jensiwaa** [Wynncraft/Issues#3448] opened 2016-01-01 23:31 UTC
There currently is a bug where the meteor ability of the mage class causes a freeze every time you cast it inside any floor of Tower of Ascension. The server then doesn't respond for 1-2 seconds. Everybody in my party has it when I cast the meteor ability but I don't know if everybody in the server has it. By the way, I'm not talking about a fps drop but about the server not responding.

**Comment by HeyloLP** [comment] 2016-01-01 23:36
there is already a thread about it so please close this

**Comment by Trixter313** [comment] 2016-01-02 03:17
Duplicate of https://github.com/Wynncraft/Issues/issues/3337

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-02 03:17 UTC
