### ISSUE TITLE
losing Armour and accessorys when you have a full inventory and skill points gltich.

### ISSUE THREAD

**Issue by DragonOfRedstone** [Wynncraft/Issues#4737] opened 2016-04-02 16:25 UTC
i had my inventory filled with emeralds because i was helping people do the tower of ascension but the server was restarting so we switched worlds but my skill points glitched making me take off a bracelet and three pieces of my armour but since my inventory was full they just disappeared! they were valuable armour too, lvl 82-83 diamond armour :/

**Comment by DarkDemonDragon** [comment] 2016-04-02 18:57
Duplicate of #4120 Please close this issue and read the main one to understand what happened to you.

**Closed** 2016-04-02 19:37 UTC
