### ISSUE TITLE
Can't give Guild Xp

### ISSUE THREAD

**Issue by RubixTitan** [Wynncraft/Issues#3936] opened 2016-01-31 16:44 UTC
Help me please, I try and do /guild xp 50 it does not give any xp in the guild list when i do /guild list. I do not know what to do about it, i think it is loading the xp but it is taking a long time. I am not so sure, i think you can help me out. Thank you.

From Rubix_Titan

**Comment by Trixter313** [comment] 2016-01-31 16:50
The stats aren't instant and take a little time to update. If it hasn't changed after a few hours, comment back on this issue and let me know.

**Comment by Trixter313** [comment] 2016-02-02 12:13
I see that you are still experiencing this even after 2 days. That is definitely longer than normal so this appears be a bug that's more than just lag in the information. Hopefully it will be fixed soon!

**Comment by RubixTitan** [comment] 2016-02-03 13:23
Please tell salted or someone else about this as soon as possible. Thank you

**Comment by Blocktopia9** [comment] 2016-03-02 19:38
Setting your guild xp sets the percent you donate when you earn it, it doesn't donate it right then and there.

**Comment by DarkDemonDragon** [comment] 2016-03-17 12:29
@Trixter313 I think there was a misunderstanding of guild xp mechanics. @Blocktopia9 has the right idea. This is NOT a bug. @RubixTitan probably things doing /guild 50 gives 50 xp to the guild. I've been changing my guild xp a bunch over the past week and had no issues whatsoever.

**Comment by Trixter313** [comment] 2016-03-17 16:03
Ah, that does seem like a misunderstanding.

**Closed by Trixter313** 2016-03-17 16:03 UTC
