### ISSUE TITLE
Can't identify item

### ISSUE THREAD

**Issue by jkGALAKTUS** [Wynncraft/Issues#2396] opened 2015-10-15 14:41 UTC
Ik-El Vän can't be identified it says : I'm afraid I can't identify this item! Only weapons and armours with a unique, rare, legendary and special tags can be identified. 
Thank you for your time, I hope you will fix this.

**Comment by Chewsterchew** [comment] 2015-10-15 14:48
Have you enchanted your weapon? Once a weapon is enchanted, it can't be identified.

**Comment by jkGALAKTUS** [comment] 2015-10-15 14:52
I has enchanted it but could not identify it before.


---------- Původní zpráva ----------

Od: Chew <notifications@github.com>

Komu: Wynncraft/Issues <Issues@noreply.github.com>

Datum: 15. 10. 2015 16:48:52

Předmět: Re: [Issues] Can't identify item (#2396)


"

Have you enchanted your weapon? Once a weapon is enchanted, it can't be 
identified.

—

Reply to this email directly or view it on GitHub
(https://github.com/Wynncraft/Issues/issues/2396#issuecomment-148409092). 





"=

**Comment by Chewsterchew** [comment] 2015-10-15 14:52
Hmm, I have that weapon, I will try to see if I can identify it.

**Comment by jkGALAKTUS** [comment] 2015-10-15 15:18
ok




---------- Původní zpráva ----------

Od: Chew <notifications@github.com>

Komu: Wynncraft/Issues <Issues@noreply.github.com>

Datum: 15. 10. 2015 16:53:09

Předmět: Re: [Issues] Can't identify item (#2396)


"

Hmm, I have that weapon, I will try to see if I can identify it.

—

Reply to this email directly or view it on GitHub
(https://github.com/Wynncraft/Issues/issues/2396#issuecomment-148410220). 





"=

**Comment by Trixter313** [comment] 2015-10-15 16:04
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!

**Closed** 2015-12-25 20:40 UTC
