### ISSUE TITLE
Not able to kick 1 person from my guild

### ISSUE THREAD

**Issue by theunderminer64** [Wynncraft/Issues#6271] opened 2016-09-27 17:55 UTC
Iv owned my own guild on wynncraft for about 6 months now and kicking some of the people on it and theres 1 person with there name in the guild twice and i can not kick them from the guild, this guys name it UltimateStranger and unable to be kicked

**Comment by LordHelmchen98** [comment] 2016-09-27 18:20
That guy changed his ingamename while he was in the guild. Now he is stuck in your guild and neither you can kick him nor can he leave himself. Unfortunately you cant do anything until guilds get fixed which will hopefully happen in the next update.

**Comment by theunderminer64** [comment] 2016-09-27 19:10
erm no he has not changed his name because it says he was last online 10 days ago

**Comment by LordHelmchen98** [comment] 2016-09-27 19:27
Yes he did. He joined your guild on April 5th (http://fb.jurnace.com/guild.php?g=TheIvoryWolves) and changed his name on June 6th (https://de.namemc.com/profile/UltimateStranger/1ab02d98). So he changed his name when he already was in your guild.

**Comment by theunderminer64** [comment] 2016-09-27 21:09
erm i think you missed 1 big detail the year and when the guild was made 
he joined when his name was UltimateStaranger and has not changed since learn to read the dates

**Comment by LordHelmchen98** [comment] 2016-09-27 21:29
Hmm on the namemc page it clearly says that he changed his name to UltimateStranger on June 6th 2016 which is after he joined the guild. Also following the namemc page when he joined the guild his name should have been NyanNinja69. Also I got the unedited post via email and I have no idea how that can match what you are saying that his name was always UltimateStranger. Also the date when a guild was made doesnt matter. And uhh well yeah I can read dates ;)

**Comment by theunderminer64** [comment] 2016-09-27 21:30
well never mind that, but i just want to kick him from the guild since hes not contributing to it at all, but it will not kick him because of the name change

**Comment by LordHelmchen98** [comment] 2016-09-27 21:33
Well as I said above you are not able to kick him and I heard that not even admins are able to remove glitched player from guilds. Also I saw that your guild is level 22 which means you have 26 player slots. That is enough for a bunch of other players.

**Comment by theunderminer64** [comment] 2016-09-27 21:35
Makes sense, but im one who kicks from a guild or clan if they dont contribute, and i see your point.

**Comment by ICHIGOunserscore** [comment] 2016-10-02 01:56
Can you please close this issue now you got your answer

**Comment by Trixter313** [comment] 2016-10-03 01:45
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

**Closed by Trixter313** 2016-10-03 01:45 UTC
