### ISSUE TITLE
Everytime joining a world as my warrior class it crashes the world

### ISSUE THREAD

**Issue by andrewzhengmc** [Wynncraft/Issues#5562] opened 2016-07-23 20:57 UTC
My in game name is Legacy_Andrew and Every time I try to join a world as my warrior class it crashes the world completely with the people in it. Im not sure if it is my fault or if something bugger my class but I know it is only my class because I tried joining a world with a new class I made and It had succeeded in letting me play, but my warrior is still bugged.

**Comment by sammyvsparks** [comment] 2016-07-23 21:54
andrewzhengmc, does this occur on all worlds? or only some. Because several worlds have been crashing and may not be caused by you.

**Comment by Trixter313** [comment] 2016-07-23 23:39
Also try using /kill as fast as possible after you login to the class. That character might be in an out of bounds area that causes it to crash and getting it back to a town in bounds would fix it.

**Comment by Mininglover21** [comment] 2016-07-24 03:17
If this is the same as issue #5134 there is currently no fix to your problem, if it spawns you at a very high number it  crashes the world because spawning a player at a very high height can crash a world. If you could take a screenshot or just describe it that would help people understand what you mean by this.

**Comment by andrewzhengmc** [comment] 2016-07-24 14:33
Trixter313 if you are watching this I cant perform the /kill command because the server crashes right away and I get teleported back to the hub.

**Comment by andrewzhengmc** [comment] 2016-07-24 14:36
Mininglover21 your right I check the coordinates and I spawn about 200 blocks above where I spawn and that could cause what is going on.

**Comment by Moe-Ronickah** [comment] 2016-07-25 13:22
That is the core of the problem - your spawn point is way too high.  Mininglover21 guessed it correctly, this is a duplicate of #5134 .

**Closed by Moe-Ronickah** 2016-07-25 13:22 UTC
