### ISSUE TITLE
Whats up with this Galleons key?

### ISSUE THREAD

**Issue by Twerk4Twinkies** [Wynncraft/Issues#8071] opened 2017-05-05 15:35 UTC
Hi all! i got a key from a quest with a name i cant remember and after i found out it says EM in the box under the name ill leave a picture..
![2017-05-05_17 22 07](https://cloud.githubusercontent.com/assets/28448418/25752658/3775adb8-31b9-11e7-969c-d17cbfe4d6b9.png)

**Comment by PepinhoJp** [comment] 2017-05-05 16:14
Are you using any additional texture packs?

**Comment by LordHelmchen98** [comment] 2017-05-06 18:52
Duplicate of #5994
This happens to keys from the quest 'Beneath the Depths' if you change classes or servers. As this key can still be used you should either use that one first or throw it away.

**Closed by LordHelmchen98** 2017-05-06 18:52 UTC
