### ISSUE TITLE
Bug With The "Enter The Dojo" Quest

### ISSUE THREAD

**Issue by LightAuura** [Wynncraft/Issues#5860] opened 2016-08-29 09:56 UTC
So basically i did 2 trials and completed the 3rd, the door opened but i cant go in because there is invisible blocks. So im stuck in it, can  you please fix that asap.

**Comment by Trixter313** [comment] 2016-08-29 09:59
Duplicate of #5844 

You can use /kill to get out for now until it's fixed.

**Closed by Trixter313** 2016-08-29 09:59 UTC
