### ISSUE TITLE
stuck on a quest.:    Canyon Condor

### ISSUE THREAD

**Issue by SoulAyce** [Wynncraft/Issues#4294] opened 2016-02-26 17:12 UTC
So in the quest canyon condor you gonna talk to svin in rymek about killing a bird etc. 
But theres one part of the quest that makes this impossible 
You need to find 10 gold bars for Old Man Yankan, at the end of the cave, where the gold bars should be, nothings here. the mobs doesnt drop, noting lying on the ground.

Because of this i cant continue the quest, Can some one help me`?

**Comment by Odnod** [comment] 2016-02-26 17:29
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

This issue is very well known and it is being worked on.

**Closed** 2016-02-26 17:32 UTC
