### ISSUE TITLE
My Character Got Deleted Without Me Even Telling It To

### ISSUE THREAD

**Issue by SwiftySkills** [Wynncraft/Issues#5455] opened 2016-07-11 01:41 UTC
Hello, i am here to talk about my missing Character, i remember for a fact that i clicked on it, then it asked if i wanted to delete it, So i must've clicked it by accident. So i immediately clicked ESC. I never clicked Yes or No, i had a lvl 29 Assassin. Please help me i worked so hard on it.

**Comment by Moe-Ronickah** [comment] 2016-07-11 06:14
ESC should have worked exactly the same as "No".  If you ever have an interactive box, again, be certain to pick the option that you really want, don't just "Esc", just to be safe.

I'm sorry, but WynnCraft has a no-refunds policy on classes and items that are obtainable in-game and not purchased with real-world currency.

I'm holding this issue open until the ESC option can be tested.

**Comment by sammyvsparks** [comment] 2016-07-11 19:50
@Moe-Ronickah using ESC does count as "No", it does not confirm the deletion (tested on assassin and warrior).

**Comment by SwiftySkills** [comment] 2016-07-11 23:28
I was an assassin and didn't click no. Is it possible I can somehow get my
horse back? Or a weapon or something?

**Comment by sammyvsparks** [comment] 2016-07-12 02:14
@SwiftySkills as @Moe-Ronickah said:

"I'm sorry, but WynnCraft has a no-refunds policy on classes and items that are obtainable in-game and not purchased with real-world currency."

**Comment by Moe-Ronickah** [comment] 2016-07-12 13:16
@SwiftySkills , could someone else have had access to your account, like a friend, or brother or sister?  Did you leave your account open somewhere, like at a school?

**Comment by SwiftySkills** [comment] 2016-07-12 17:53
No, I am completely positive that the delete comfirmation window came up,
and I hit esc. I then played for like 30 minutes, got off, came back on to
find it was gone

**Comment by sammyvsparks** [comment] 2016-07-12 18:42
@SwiftySkills that would mean your account was accessed after you played, as you cannot use a character that is pending deletion. Perhaps you should secure your account?

**Comment by SwiftySkills** [comment] 2016-07-12 19:11
Okay

**Comment by Moe-Ronickah** [comment] 2016-07-13 08:47
I am not certain, at this time, that someone else accessed his account.  I still need to do some more testing with a new character.

**Comment by XavierEXE** [comment] 2016-07-13 09:36
shit, this again
this has happened before, lemme find the other issues

**Comment by XavierEXE** [comment] 2016-07-13 09:37
https://forums.wynncraft.com/threads/account-help.115908/
https://forums.wynncraft.com/threads/lost-my-warrior-class.112611/
https://forums.wynncraft.com/threads/this-bug-deleted-my-class.108516/
https://github.com/Wynncraft/Issues/issues/3904
https://forums.wynncraft.com/threads/my-warrior-is-randomly-gone.124444/

**Comment by Moe-Ronickah** [comment] 2016-07-14 06:30
DUPLICATE OF #5266 .

**Closed by Moe-Ronickah** 2016-07-14 06:30 UTC
Labels: Duplicate

**Comment by Moe-Ronickah** [comment] 2016-08-08 18:21
**Tested and proven to be an issue.  Using ESC on the deletion box, instead of clicking on the NO option, sometimes deletes the class.**
