### ISSUE TITLE
Bug for wynncraft

### ISSUE THREAD

**Issue by BoggeyBang** [Wynncraft/Issues#4846] opened 2016-04-17 15:49 UTC
Hey wynncraft team!

So my friend told me a bug that was cool but i am feeling dirty because it's a little cheating so i have now decided to say it.

So the bug is if you have an unidentefied item and you throw out the item you got then the real texture will show like if you throw out a unidentefied bow then it will show the texture and then you know wich element it is before you you go to the identefier.

Hope you guys will fix this.
-_Sansy/CoalGames

**Comment by Trixter313** [comment] 2016-04-17 15:51
Duplicate of https://github.com/Wynncraft/Issues/issues/3318

Please direct any future comments to the original thread. Thanks! =)

**Closed by Trixter313** 2016-04-17 15:51 UTC
