### ISSUE TITLE
Bugs everywhere!

### ISSUE THREAD

**Issue by TheDerpyMan** [Wynncraft/Issues#3261] opened 2015-12-28 05:40 UTC
Sometimes, it happens that on Assassin, the first ability, Spin Attack gets me freezed. Instead of freezing only the enemy, it freezes me too, but no I take no damage.
Assassin's 3rd ability, Multihit cannot move mobs, only players (Sometimes) By moving, I mean when I move my head left and right.

The Assassin is so weak right now that it's almost unusable.
The Archer can deal up to 50k damage with the lvl 68 Jungler's Artifact and lvl 84 Oktavist bows. This damage is higher than the endgame Bow, Qira's shit.
The game is unbalanced now, that Asssassin can deal 5k with Multihit, being at the same level with the Archer, while it can deal 50k just as showed above.

Jungler's Artifact is a very-slow bow, but that doesn't affect the Archer's most important and most used abilties, Bomb Arrow and Arrow Storm. It's interesting that having low attack speed on somebody like Archer is OK, it doesn't really affect that much the gameplay, but the Damage a low attack speed item gives it's a HUGE buff to that class. The Assassin cannot deal the same damage, because the Smoke Bomb is bugged, and it's dealing only 600% damage over 5 seconds, while Arrow Storm deals 1800% damage in only 2 seconds. 

WTF, BALANCE! Having Vanish, a good ability doesn't balance the fact that the Archer can deal up to 10 times Assassin's damage at the same level.

Salted, Jumla, this is real bullshit right now.

**Comment by SioN-wynncraft** [comment] 2015-12-28 21:27
Agreed assasin/ninja needs a buff Or change of skills. He is tooo bugged right now.

**Comment by Verret001** [comment] 2015-12-28 22:01
duplicate of https://github.com/Wynncraft/Issues/issues/3140
Please follow up on that issue.
Use the **[Directory](https://github.com/Wynncraft/Issues/issues/3197)** to make sure your not making duplicates

**Closed** 2015-12-28 22:02 UTC
