### ISSUE TITLE
an item can't be itentified

### ISSUE THREAD

**Issue by Nolmin02** [Wynncraft/Issues#1802] opened 2015-04-11 10:25 UTC
Damassé rare pant for lvl 2 can't be identified. Normally u can hv spell dam 2% and xp bonus 3% that writing on the site. Can u do something pls

**Comment by SkySaito** [comment] 2015-04-11 12:44
What does the Identifier say ?

**Comment by Trixter313** [comment] 2015-04-11 15:16
Thats a long standing issue that has to do with the special character é in it.
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

**Comment by epicman739** [comment] 2015-04-12 02:48
The strange thing is, sometimes items with special charecters will identify, and sometimes they don't.

**Closed** 2015-04-17 15:23 UTC
