### ISSUE TITLE
Loot Crates

### ISSUE THREAD

**Issue by Omnireg** [Wynncraft/Issues#6698] opened 2016-11-15 20:01 UTC
I got on to open my daily loot crate, and when I tried opening it, it queued.. it had 2 godly items, and then I right clicked the chest to stop it, and it slowed down a bit, and then just disappeared. All items gone, chest gone, only the green pointer was left.

Lost my chance to get 2 godlys.. didnt get to open ANY crate today and by my luck this will happen to me again.

Screenshots (if required for refund.. it happened on Server15 at 9pm German Time Zone):
http://i.imgur.com/2U6v9gW.png
http://i.imgur.com/kePn72L.png

Please fix :/
(And maybe refund one crate.. that'd be lovely.. it was T1)

**Comment by Rellia** [comment] 2016-11-15 20:25
Yeah this has happened to a lot of people in the last 24 hours. I got an epic shears skin, then it disappeared. Did it leave a floating green arrow too?
They won't refund. No one gets a refund, no exceptions

**Comment by LordHelmchen98** [comment] 2016-11-15 20:27
@Rellia You could just look at the screenshots and the text you know? Yes there was a green arrow left.

@Omnireg But unfortunately Rellia is right you wont get any refunds.

**Comment by Rellia** [comment] 2016-11-15 20:53
You don't need to be sarcastic... I didn't see that part... conditions... but yes, the green arrow is common

**Comment by LordHelmchen98** [comment] 2016-11-15 20:58
Im sorry but often if someone has a problem its better to read the entire text and tbh Im annoyed of people who just read the first two lines although its explained in the following lines.

**Comment by thecoolkogut4** [comment] 2016-11-15 21:12
duplicate of #6691

**Comment by Rellia** [comment] 2016-11-15 21:36
@LordHelmchen98 I read the actual problem, I just didn't read "a visual glitch", so calm down and stop being impatient

**Comment by LordHelmchen98** [comment] 2016-11-15 21:49
You maybe noticed im trying to help as well....
Please dont feel insulted. You are not the first one and you will not be the last one missing information from the original post. Its just a tip for the future to read carefully as it might be explained in the original post (especially in a well designed one like this).
Also "have a lot to do"? Nobody forces you and I think its better not to rush over the threads but to read the entire thread. But thats just my opinion.

**Comment by Moe-Ronickah** [comment] 2016-11-17 03:13
It may be more than "just visual".  Please follow issue #6691

**Closed by Moe-Ronickah** 2016-11-17 03:13 UTC
Labels: Duplicate
