### ISSUE TITLE
Falling into void

### ISSUE THREAD

**Issue by Skrypted** [Wynncraft/Issues#3682] opened 2016-01-14 01:13 UTC
Whenever I try to join a server from the hub I keep falling into the void through the blocks during the class selection menu. I cannot do /class and it keeps happening.

**Comment by Dar-krusos** [comment] 2016-01-14 22:22
When you are in the class selection screen, you cannot do any command other than /hub. When in this menu, you must choose a class. If you the menu does not pop-up, try right-clicking to bring it up.
If the issue still persists, please reply back here.

**Comment by am987ab** [comment] 2016-01-16 02:43
I think I am experiencing the same issue.  Right-clicking does absolutely nothing.

**Comment by Trixter313** [comment] 2016-01-24 07:37
Duplicate of https://github.com/Wynncraft/Issues/issues/3521

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-24 07:37 UTC
