### ISSUE TITLE
entering the dojo glitch!

### ISSUE THREAD

**Issue by dragonslayer478** [Wynncraft/Issues#7132] opened 2017-01-08 11:37 UTC
when  the nature room i cant get the sugar when i press the button! wynncraft please fix this cuz i cant go anywhere else on my pro account cuz i am afraid i am going to start over and start on the lesson 1.
![2016-12-22_13 33 12](https://cloud.githubusercontent.com/assets/24987728/21749475/0c4433f6-d59f-11e6-9650-79b55d9b076b.png)

**Comment by Numbermaniac** [comment] 2017-01-08 11:55
#7130

**Comment by almendris** [comment] 2017-01-08 12:15
Hay alguna solucion?

**Comment by LordHelmchen98** [comment] 2017-01-08 13:17
Duplicate of #7121 
Please avoid duplicates and post on the original thread.

**Closed** 2017-01-09 20:40 UTC
