### ISSUE TITLE
Continuously kicked for flying in lobby after exiting server

### ISSUE THREAD

**Issue by SSentrie** [Wynncraft/Issues#5409] opened 2016-07-06 01:50 UTC
Sometimes after I switch servers by using /server, /hub, or /lobby, I will be spawned mid-air or something in the lobby and it will keep on kicking me for flying. It doesn't disconnect me from the server; it just makes me reconnect then the issue happens again, and this keeps repeating. I don't have any lag issues.

**Comment by Moe-Ronickah** [comment] 2016-07-06 05:27
1: Delete your Wynncraft IP from the MC server list.  Close and restart MC.  Put the Wynncraft IP back in.
2: If you don't have the resource pack set to automatically download, do that.
3: If you are using any version of MC greater than 1.8.9, go back to 1.8.9.
4: Make certain that your MC launcher is the latest launcher.
5: The nuclear option - delete and reinstall MC.

**Comment by XavierEXE** [comment] 2016-07-08 09:23
I've also found that switching the IP you use to connect can fix this.
Make sure to try play.wynncraft.net, play.wynncraft.com, and play.wynncraft.org.
As a last resort, you can also connect directly to a node, with the IP node7.wynncraft.com. After you connect to the node and the issue gets fixed, however, we recommend you exit the server and change the IP back to the normal one as connecting directly to nodes can put extra stress on the servers.

**Comment by Trixter313** [comment] 2016-07-29 08:05
Appears to be a duplicate of https://github.com/Wynncraft/Issues/issues/5289

**Closed by Trixter313** 2016-07-29 08:05 UTC
