### ISSUE TITLE
Staff dont get accepted as staff

### ISSUE THREAD

**Issue by napster1** [Wynncraft/Issues#3633] opened 2016-01-10 15:04 UTC
I am a mage lvl 45, i have a staff named: "dévoreuse" and it was a really good staff (the best i had so far) but after you turned on the server cause of the issue with the low amount of servers, this staff is like a unidentified item again cause i cannot use it. Chat says nothing, i can't do any spell, doesn't do damage and has the texture of a regular unidentified staff/stick....
Restarting game don't work, playing without/with texture pack dont work, other servers dont work...
Can you plz fix my staff.

I.G.N: Napster1

ps. i used my 2 monitors to make this picture 
![wynncraft](https://cloud.githubusercontent.com/assets/9511135/12222143/d85bd152-b7b3-11e5-8859-2f42fc33c195.png)

Napster1, Mage lvl 45

**Comment by Trixter313** [comment] 2016-01-10 16:02
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread and try out the suggestions in it. They may help!

**Closed by Trixter313** 2016-01-10 16:02 UTC
