### ISSUE TITLE
Old Man Jankan's Cave not spawning Golden Bars

### ISSUE THREAD

**Issue by norepinephrine** [Wynncraft/Issues#4420] opened 2016-03-03 21:15 UTC
Title says it all, I have been on multiple accounts and multiple servers but the cave behind Old Man Jankan in the Canyon Condor quest does not spawn the Golden Bars needed to advance in the quest.

**Comment by Odnod** [comment] 2016-03-03 22:24
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-05 05:32 UTC
Labels: Duplicate, Quests
