### ISSUE TITLE
Attack Effects

### ISSUE THREAD

**Issue by Locky1110** [Wynncraft/Issues#6810] opened 2016-11-30 21:05 UTC
A few days ago i bought VIP+ and one of the crates i opened contained an attack effect. i clicked it but now i cant shut it off. is there a command that can do it?

**Comment by LordHelmchen98** [comment] 2016-11-30 21:38
I think it should be possible to just click it again in order to turn it off.

**Comment by LordHelmchen98** [comment] 2016-11-30 21:53
Nvm I just got an attack effect (didnt have one so far as I got vip+ only two days ago) and it doesnt work for me as well.

**Comment by Moe-Ronickah** [comment] 2017-02-19 09:20
Your issue is a duplicate of #6623  .  You can follow your issue on that thread.

**Closed by Moe-Ronickah** 2017-02-19 09:20 UTC
Labels: Duplicate
