### ISSUE TITLE
Wynncraft Excavation site A Quest not working!?

### ISSUE THREAD

**Issue by Lazzuu** [Wynncraft/Issues#5368] opened 2016-07-02 15:08 UTC
Well, i started the quest... Vade said go talk to Tesh or something. My Quest Book said go talk to Tesh. I did, but he didnt give me anything, he just said "Take this to Vade, and don't read it" And when i tried talk to vade, he didnt say anything. And my Quest Book was still telling me that i need to talk with Tesh, but Tesh says only "Take this to Vade, and don't read it"

**Comment by Trixter313** [comment] 2016-07-03 20:21
You can try the command /fixquests but unfortunately most people stuck at this part are still stuck because we haven't found a solution yet.

**Comment by Moe-Ronickah** [comment] 2016-07-03 20:51
duplicate of #3351 

Sooner or later, someone is going to remember exactly what they did that is triggering this.

**Closed by Moe-Ronickah** 2016-07-03 20:51 UTC
Labels: Duplicate
