### ISSUE TITLE
Hight limit building bug

### ISSUE THREAD

**Issue by Mr-Recalculate** [Wynncraft/Issues#2603] opened 2015-12-07 04:08 UTC
I actually first discovered this bug before the ocean update. Anyway there is a double-sided waterfall connecting the area directly east of Rani to the village inside Pigmen's ravines. I say connected because you can use it to bypass Pigmen's ravines to get to Thomas in the quest, "Creeper Infiltration". The hight limit is too high to block you from passing though the lake at the top.
![2015-12-06_19 39 36](https://cloud.githubusercontent.com/assets/16183605/11618644/6ff84d88-9c52-11e5-965d-553c3cd8c0f1.png)
![2015-12-06_19 40 58](https://cloud.githubusercontent.com/assets/16183605/11618650/82183366-9c52-11e5-901c-12971228b066.png)
![2015-12-06_19 39 25](https://cloud.githubusercontent.com/assets/16183605/11618651/821e2ab4-9c52-11e5-8d0c-dc96a976ff43.png)
![2015-12-06_19 39 42](https://cloud.githubusercontent.com/assets/16183605/11618652/822163fa-9c52-11e5-81b6-772b714e7ebf.png)
![2015-12-06_19 40 08](https://cloud.githubusercontent.com/assets/16183605/11618653/82247842-9c52-11e5-8181-3ead9b6bb84e.png)

**Comment by ThunderRemix** [comment] 2015-12-07 08:14
I believe that this was intended.

**Comment by GamerGamerFTW** [comment] 2015-12-07 12:54
Yeah when i tried it didnt work.

**Comment by Trixter313** [comment] 2015-12-22 18:18
Is the issue still occurring since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Closed** 2015-12-22 20:03 UTC
