### ISSUE TITLE
Dying in the fast villager room of the "Shattered Minds" Strange Temple teleports you to the tutorial area before Ragni.

### ISSUE THREAD

**Issue by toad180** [Wynncraft/Issues#4103] opened 2016-02-13 04:54 UTC
While playing the "Shattered Minds" quest, during the Strange Temple in the fast villager room, I died, and was seemingly teleported back to the tutorial area. A tad odd, at least I have a Llevigar teleportation scroll.

**Comment by Trixter313** [comment] 2016-02-13 04:56
Duplicate of https://github.com/Wynncraft/Issues/issues/3617

Please direct any future comments to the original thread. Thanks!

**Closed** 2016-02-13 04:57 UTC
Labels: Duplicate
