### ISSUE TITLE
Wynncraft quest / Green Skinned trouble

### ISSUE THREAD

**Issue by Pinomo** [Wynncraft/Issues#8813] opened 2017-08-20 12:18 UTC
(i'm french ^^)

So, I think there is a bug in this quest.
When you must enter the lake, you ave a test. (Move with the light)
![2017-08-20_14 19 02](https://user-images.githubusercontent.com/31181978/29494816-9d561aa8-85b2-11e7-98cd-b4b770e038d7.png)

After "moving", I can't fall in the hole. It's say:

"null"
"null"
"null"
...
![2017-08-20_14 20 43](https://user-images.githubusercontent.com/31181978/29494825-e844c2a8-85b2-11e7-806d-13a0872bb690.png)

Help plz !

**Comment by LordHelmchen98** [comment] 2017-09-29 23:40
Duplicate of #3339

**Closed by LordHelmchen98** 2017-09-29 23:40 UTC
Labels: Duplicate
