### ISSUE TITLE
I keep spawning in a black cube

### ISSUE THREAD

**Issue by nerohecklp** [Wynncraft/Issues#4053] opened 2016-02-09 10:47 UTC
When i join any server i spawn in a black cube. i`m at -977 62 -1692

**Comment by Dar-krusos** [comment] 2016-02-09 10:58
Duplicate of [issue #4052](https://github.com/Wynncraft/Issues/issues/4052/)

**Comment by nerohecklp** [comment] 2016-02-09 11:44
i solved the problem by killink myself (/kill) thanks to all admins for their good support.....

**Closed** 2016-02-09 14:40 UTC
