### ISSUE TITLE
guild bug 

### ISSUE THREAD

**Issue by InDieDingelings** [Wynncraft/Issues#4910] opened 2016-04-29 18:51 UTC
i will leave my guild and then i lost my 3 soulpoints but i am in the guild the will kick me a leader from this guild but i am still in the guild D:

**Comment by InDieDingelings** [comment] 2016-04-29 18:51
sorry for my bad english xD

**Comment by thecoolkogut4** [comment] 2016-04-29 19:27
its a bug that happens when you change your IGN, there's nothing that you can do at the moment. there's a bunch of other people that have the same problem. just wait for the devs to fix it.

**Comment by InDieDingelings** [comment] 2016-04-29 20:09
ok thanks for this info :D

**Comment by Trixter313** [comment] 2016-04-30 07:13
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-30 07:13 UTC
