### ISSUE TITLE
Can't connect to server, please report.

### ISSUE THREAD

**Issue by Moderocky** [Wynncraft/Issues#3846] opened 2016-01-24 17:13 UTC
It has been happening continually for a while now.

**Comment by SaturnHD** [comment] 2016-01-24 17:21
Yeah same here

**Comment by Trixter313** [comment] 2016-01-24 18:04
Duplicate of https://github.com/Wynncraft/Issues/issues/3830

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-24 18:04 UTC
