### ISSUE TITLE
Monsters not hostile

### ISSUE THREAD

**Issue by Sandertv** [Wynncraft/Issues#4452] opened 2016-03-05 12:40 UTC
The second point is sometimes monsters are not hostile and don't attack me at all. When i relog the monsters usually attack me again, but it's weird.

**Comment by Trixter313** [comment] 2016-03-05 16:02
The first part is a duplicate of https://github.com/Wynncraft/Issues/issues/3902

Could you go into more detail about the second part? Thanks!

**Comment by Sandertv** [comment] 2016-03-05 16:06
Oh I'm sorry
Sometimes when I join a server, I walk up to some monsters, and they just keep doing their thing and walking around, while they are supposed to go after me and kill me. When I rejoin the game, they usually become hostile again and start attacking me when i get close.

**Comment by Trixter313** [comment] 2016-03-05 16:15
Hmm, what class do you play as? Some classes have to ability to 'blind' mobs, making them not be able to attack or follow players and some classes can become invisible temporarily so that mobs can't track or attack them.

Also, would you say this mostly happens freshly after logging in, or have you also experienced this after being logged in for a while? It's possible that players have a sort of invincibility when first logging in to account for downloading the resource pack or just slow loading computers.

**Comment by Sandertv** [comment] 2016-03-05 19:33
I'm playing as a mage, but they already don't attack me from when I join. It starts after I just join a server.

**Comment by Sandertv** [comment] 2016-03-05 19:44
Oh and when this happens, I can just attack the monsters, use spells, I get xp when I kill them and sometimes they drop emeralds and items.

**Comment by DarkDemonDragon** [comment] 2016-03-08 12:46
Is this for ALL mobs? Even bosses? Also, does this last forever until you relog?

**Comment by Sandertv** [comment] 2016-03-08 17:06
Yep it is for every monster, even bosses. It stays like that until I relog yes.

**Comment by Moe-Ronickah** [comment] 2016-03-11 04:55
Would you try reinstalling your Minecraft and let us know what happens?

**Comment by Sandertv** [comment] 2016-03-11 06:11
Sure, I'll try

**Comment by Sandertv** [comment] 2016-03-12 07:06
After re-installing I haven't had the problem so far.

**Comment by Moe-Ronickah** [comment] 2016-03-15 06:08
OK!  I'm going to close this.  I'm glad that it's fixed.

**Closed by Moe-Ronickah** 2016-03-15 06:08 UTC
