### ISSUE TITLE
Wiki: Cookies not enabled?

### ISSUE THREAD

**Issue by GAsplund** [Wynncraft/Issues#3571] opened 2016-01-06 19:16 UTC
This is a problem regarding the wiki. I couldn't find any other place to post it so I will post it here. I can't log in to my account because I am met by the error "Wynncraft Wiki uses cookies to log in users. You have cookies disabled. Please enable them and try again." 

I have tried using three different browsers including Edge, Internet Explorer and Chrome. I have checked that cookies are enabled and they are.
Image: http://i.imgur.com/KOHIrBr.png

**Comment by Trixter313** [comment] 2016-01-09 13:01
Duplicate of https://github.com/Wynncraft/Issues/issues/3415

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-09 13:01 UTC
