### ISSUE TITLE
Im stuck in the block at the sewers in Llevigar please im stuck and can't use my scrolls.

### ISSUE THREAD

**Issue by TheKillersAce** [Wynncraft/Issues#7641] opened 2017-04-02 21:45 UTC
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by Trixter313** [comment] 2017-04-02 21:46
Duplicate of https://github.com/Wynncraft/Issues/issues/7640

You can use the command /kill to get out.

**Closed by Trixter313** 2017-04-02 21:46 UTC
