### ISSUE TITLE
Broken Weapon

### ISSUE THREAD

**Issue by Elhae** [Wynncraft/Issues#3591] opened 2016-01-07 21:50 UTC
Hello! Today I logged onto Wynncraft after the server shutdowns, I noticed my Fiertè is broken, it has fast attack speeds and only deal about 10-21 Damage, and I cannot execute any skills with it, here is my proof: 
![2016-01-07_14 46 22](https://cloud.githubusercontent.com/assets/16600483/12183735/efce845a-b54d-11e5-888a-6b04074d8c4a.png)

**Comment by Trixter313** [comment] 2016-01-09 12:59
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-09 12:59 UTC
