### ISSUE TITLE
Powder Won't stack

### ISSUE THREAD

**Issue by CrapotteQc** [Wynncraft/Issues#5899] opened 2016-08-30 00:11 UTC
I can't stack green powder 1 on green powder 1... I tried with yellow and red too... Not working!

**Comment by coreynj** [comment] 2016-08-30 01:02
It would seem that the NBT values for powders obtained from Relics and powders obtained from chests are different, so they refuse to stack together.

**Comment by 0x0000null** [comment] 2016-08-30 01:07
The NBT data is the same, which is why they seem to stack client-side, but for some reason the server refuses to allow them to stack.

**Comment by ninja2003** [comment] 2016-08-30 15:45
They got to fix this. it is sooooo annoying

**Comment by Trixter313** [comment] 2016-08-30 22:34
Duplicate of https://github.com/Wynncraft/Issues/issues/5871

**Closed by Trixter313** 2016-08-30 22:34 UTC
