### ISSUE TITLE
Skill Point Glitch

### ISSUE THREAD

**Issue by TwinShadeless** [Wynncraft/Issues#4304] opened 2016-02-27 06:53 UTC
# Delete this line if you've searched for a duplicate issue first
I don't know if this has happened to anyone else, but I'm going to mention it anyway.
I was grinding at the Temple of Legends and the server crashed, so I logged back on when it re-opened. When I got on, all my armor had disappeared. I looked at my skill points, and it had all reset, saying I had 0 for every skill and 0 skill points left. My inventory had been full at the time, so my armor was automatically deleted. In addition, for some reason, I can no longer use any spells. So now, I am armorless, have no skill points, and I can't use spells. Please help.

![2016-02-26_22 38 48](https://cloud.githubusercontent.com/assets/17509495/13371457/73c73496-dcdb-11e5-9580-f2840edc08b6.png)

![2016-02-26_22 37 23](https://cloud.githubusercontent.com/assets/17509495/13371467/94d8134e-dcdb-11e5-9113-35c59f810862.png)

**Comment by TwinShadeless** [comment] 2016-02-27 07:00
An update on this:my skill points fixed themselves, but my armor is still gone.

**Comment by xXKhyXx** [comment] 2016-02-28 21:22
I'm honestly glad I'm not the only one experiencing this. It seems as though re-logging is enough to fix the Skill Points problem, but not the missing items.

**Comment by the4bestgame** [comment] 2016-02-29 22:04
Yep, happened to me, Luckily empty inventory but still

**Comment by Trixter313** [comment] 2016-03-06 16:30
Seems to be a duplicate of https://github.com/Wynncraft/Issues/issues/4120

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-06 16:30 UTC
