### ISSUE TITLE
Guild Attacks not working

### ISSUE THREAD

**Issue by CoolZakCZ** [Wynncraft/Issues#3290] opened 2015-12-28 18:54 UTC
I do /guild attack

The chat says "This territory has 1000 mobs protecting it
Are you sure you want to launch an attack?"

The sign appears, I type "yes" and hit done, but it does nothing. Instead it tells me "battle cancelled"

**Comment by Trixter313** [comment] 2015-12-28 21:04
Confirmed here also =)

**Comment by Trixter313** [comment] 2015-12-29 21:43
Duplicate of https://github.com/Wynncraft/Issues/issues/3230

Please direct any further comments to the original issue. Thanks!

**Closed by Trixter313** 2015-12-29 21:43 UTC
Labels: duplicate
