### ISSUE TITLE
Mountain invisible block glitch

### ISSUE THREAD

**Issue by MichaelKimTime** [Wynncraft/Issues#3755] opened 2016-01-18 02:27 UTC
I am mage and I was teleporting to the mountain in r something village and now I am stuck into the wall of invisible wall help

**Comment by Trixter313** [comment] 2016-01-18 03:02
Duplicate of https://github.com/Wynncraft/Issues/issues/3752

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-18 03:02 UTC
