### ISSUE TITLE
Bob the zombie

### ISSUE THREAD

**Issue by Dagovrek222** [Wynncraft/Issues#3658] opened 2016-01-11 17:52 UTC
I am doing the quest bob's lost soul and I have to find Bob's tear. The only way to get that is by killing bob the zombie very often. The problem is that It doesn't spawn that much in Ragni and since Gavel, It is getting killed by guards very often, which makes it almost impossible to get the tear.

**Comment by DarkDemonDragon** [comment] 2016-01-11 18:40
Unfortunately this is intended and if you find it impossible to obtain the tear, players typically sell the tear on the forums from 10-20 EB. Please close this as this is not a bug, but an intended feature.

**Closed** 2016-01-11 19:02 UTC
