### ISSUE TITLE
Death Drops

### ISSUE THREAD

**Issue by lecq4lifez** [Wynncraft/Issues#5220] opened 2016-06-13 19:29 UTC
So i kinda did TOA With 1 soul point and died and lost my stuff it didn't drop
i want my stuff back they are suppose to drop and i had all legendaries and some extra legendaries in my inv plz fix it i want back my stuff

**Comment by Trixter313** [comment] 2016-06-13 19:34
Duplicate of https://github.com/Wynncraft/Issues/issues/3954

Unfortunately Wynncraft has a strict no refunds policy. All we can recommend is to try and be more careful with your soul points.

**Closed by Trixter313** 2016-06-13 19:34 UTC

**Comment by Moe-Ronickah** [comment] 2016-06-13 19:57
@lecq4lifez , right now, there have been several reports of problems with soul points.  We don't recommend that you even go out of a city with less than 4sp, and that you never AFK in a city, unless you are way up high.

**Comment by lecq4lifez** [comment] 2016-06-14 20:25
that sucks but whatever

**Comment by lecq4lifez** [comment] 2016-06-14 20:25
and there is this connection problem for lobby 1

**Comment by Trixter313** [comment] 2016-06-14 20:42
Use the search feature to see if your second issue has been reported or not
