### ISSUE TITLE
Guild problem

### ISSUE THREAD

**Issue by SteveClinton** [Wynncraft/Issues#2560] opened 2015-11-25 19:16 UTC
We just want to start attacks. Then there was a fallback server thing.. and now we cant attack anymore! It says: your guild is already in a battle......

**Comment by SteveClinton** [comment] 2015-11-25 19:19
can we end this battle with a command???

**Comment by SkySaito** [comment] 2015-11-25 20:22
Guild are broken at the moment. Please wait for the next update before doing something else with your guild.
And have fun playing on Wynncraft !

**Comment by Moe-Ronickah** [comment] 2015-11-25 21:02
As has been said, guilds are broken at this time.  This is a duplicate of #2204.  Please close this issue.

You might want to read the forums, guilds subforum, before taking the time to post a bug report.  The problem with guilds is well known and well discussed.

**Comment by SteveClinton** [comment] 2015-11-26 15:58
now i can attack again but if we try that we dont get teleportet xDD

**Comment by Syltan-Adam** [comment] 2015-11-27 00:14
...


This is a duplicate of #2204. **Please close this issue.**

**Closed** 2015-12-25 20:38 UTC
