### ISSUE TITLE
Dropping all your items issue

### ISSUE THREAD

**Issue by Rozar8702** [Wynncraft/Issues#3946] opened 2016-01-31 23:33 UTC
So, I had 3 soul points, if I died I was going to go afk for a bit to get them back, I went to do my quest, all is well, but oh no! I died. Instead of dropping to 1 Soul Point, I lost all my shit, 10/10 would lose all my shit to BS again.

**Comment by Trixter313** [comment] 2016-02-01 02:13
Duplicate of https://github.com/Wynncraft/Issues/issues/3821

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-01 02:13 UTC
