### ISSUE TITLE
Texture bug - Mesarock Arch (bow)

### ISSUE THREAD

**Issue by TheMorriganOP** [Wynncraft/Issues#7496] opened 2017-03-06 18:57 UTC
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
 I just got this new bow and when i identifyed it i realized that it has no texture. Hope you fix this soon and have a nice day.
https://gyazo.com/2db3385ac7f9e1fe34e131c4938c297a

**Comment by Pyromanical** [comment] 2017-03-06 19:23
Duplicate of #7017 
Quoting @ColinRioux on this: "This is very known, and will hopefully be patched when Wynncraft is upgraded from 1.8.9."

**Comment by LordHelmchen98** [comment] 2017-03-06 21:08
Originally a duplicate of #4548 @Pyromanical

**Closed** 2017-03-06 22:14 UTC
