### ISSUE TITLE
Falling thru the void in tower of ascension

### ISSUE THREAD

**Issue by icecreeper01** [Wynncraft/Issues#5473] opened 2016-07-12 20:49 UTC
Hi, Recenty i was grinding on floor 3 level 2 of the tower of ascension because they mobs there are high level, low damage, and very slow plus they swarm up but basically i was going onto my horse to group them up for meteor and sometimes when i got off my horse i would be pushed through the floor into the void. I died 3 times from it so far all on different servers. I have lost 6 soul points from trying to grind there so far. I think an easy fix would be to put two-three layers of blocks under the tower of ascension rooms so you won't go into the void. Please fix this as it removes enjoyment from trying to level up on wynncraft

**Comment by sammyvsparks** [comment] 2016-07-12 21:07
Duplicate of https://github.com/Wynncraft/Issues/issues/5015 - That issue may contain some using information. Our recommendation is to not use the horse as it is un-needed and very easy to get around a small room without the horse.

**Closed** 2016-07-13 08:52 UTC

**Comment by YunoFGasai** [comment] 2016-07-13 11:05
@icecreeper01 there is a sign in the front of every room on two fence blocks, aim your crosshair on the redstone lantern directly above the fence blocks and teleport, you will fall on the fence blocks and the mobs wont be able to hit you.
if the mobs do have a range attack you can tp on top of the redstone lamps above the entrance.
