### ISSUE TITLE
Help! Lost all my items on my mage!?!?!?!?!

### ISSUE THREAD

**Issue by RTHyped** [Wynncraft/Issues#5138] opened 2016-06-03 22:42 UTC
When I logged on Wynncraft, Friday 6/3/16 around 3:41 pm, I found out that my mage was missing all of its items. Please help me!
It apparently said that I lost and gained 13 soul points, All my items on my other classes are ok including my bank, but my mage has lost all of its items?!?!?

**Comment by YunoFGasai** [comment] 2016-06-04 07:59
did you afk anywhere?

**Comment by RTHyped** [comment] 2016-06-04 13:54
No I did not afk

**Comment by YunoFGasai** [comment] 2016-06-04 15:04
duplicate of #4814 please refer all comments to the original thread.

**Closed** 2016-06-04 20:55 UTC
Labels: Duplicate
