### ISSUE TITLE
I Cant leave my wool prison room

### ISSUE THREAD

**Issue by CreamyBagels** [Wynncraft/Issues#2558] opened 2015-11-25 15:57 UTC
![2015-11-25_09 53 55](https://cloud.githubusercontent.com/assets/16019588/11401896/cae40208-9349-11e5-8f63-99eb9cd4016d.png)

SO there you have it I hadn't played on this server in about 4 months and I was going to check all my classes I checked this one first and was happy that it had the best stuff I went to Nemract and decided to use my archer for something.

I then logged into my archer finished what I was doing and I came back to my mage who was trapped in a wool room I looked for a exit path but I found none I am still stuck in the room with no clear time of escape

**Comment by SkySaito** [comment] 2015-11-25 20:26
Try /kill

**Comment by Moe-Ronickah** [comment] 2015-11-25 20:52
Duplicate of #1595.  Please close this issue.

**Closed** 2015-12-25 20:38 UTC
