### ISSUE TITLE
Acolyte of the Order Item Drops

### ISSUE THREAD

**Issue by Hasteful** [Wynncraft/Issues#3759] opened 2016-01-18 13:05 UTC
While doing the quest "Eye of the Storm", I killed an Acolyte of the Order in the pit.  It dropped all of its equipped armor and the gold hoe it had equipped.  None of the items were obtainable (I waited to be entirely certain).  While waiting, I killed some more of the Acolytes.  I managed to recreate the problem, and it just so happened to be at the exact location of the original occurrence.  Either there's a bug with one particular mob, or perhaps it was just strange luck.  Here's two
 images, complete with coords.

![acolyte1](https://cloud.githubusercontent.com/assets/16406717/12392074/4080f0bc-bdba-11e5-8b0d-3df47381579c.png)

![acolyte2](https://cloud.githubusercontent.com/assets/16406717/12392087/48489034-bdba-11e5-8d71-28cb6b4c3b62.png)

**Comment by DarkDemonDragon** [comment] 2016-01-20 18:40
Wow that's really strange. Fortunately you can't pick the items up or this would much more serious. Just be patient and wait for a staff to look at this so the issue will be remedied.

**Comment by Trixter313** [comment] 2016-01-30 15:14
Duplicate of https://github.com/Wynncraft/Issues/issues/3313

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-30 15:14 UTC
