### ISSUE TITLE
Horse BUG

### ISSUE THREAD

**Issue by Kapeltetha** [Wynncraft/Issues#6048] opened 2016-09-05 16:42 UTC
Hey
whenever I press the right mouse button, I ride on my horse, even I do not have a horse! And I can even change the horse's skin, change between a donkey and a white horse.

I have died many times in the dungeons because instead of using the skill, my horse appears.

**Comment by ColinRioux** [comment] 2016-09-05 17:12
Do you perhaps have a pet? If so, can you ride your pet?

**Comment by Kapeltetha** [comment] 2016-09-05 19:08
@ColinRioux Hi! "Kapeltetha" is my Alt Account;

Yes, I've the Silverfish and Creeper, both from VIPs package.
Plus, I got the Skeleton and Zumbi skin to Horses, but I don't have any horse since i'm lvl 34.

**Comment by Kapeltetha** [comment] 2016-09-05 21:32
@ColinRioux I tried using my Silverfish pet, and somehow the horse appeared again.

**Comment by Kapeltetha** [comment] 2016-09-06 20:55
Bump

**Comment by ColinRioux** [comment] 2016-09-06 22:15
In the future, please don't "bump" a request. I've simply been busy. 

When you ride your pet, it displays as a horse that can change skins (even though to other players, you are riding a pet). So if your pet is following you and you "right click" good chance when you do so you start riding your pet. If you want it to stop, just despawn your pet.

**Comment by Trixter313** [comment] 2016-09-08 00:59
Appears to be a duplicate of https://github.com/Wynncraft/Issues/issues/3783

**Closed by Trixter313** 2016-09-08 00:59 UTC
