### ISSUE TITLE
Guild Xp bug?

### ISSUE THREAD

**Issue by Epicdolphinator** [Wynncraft/Issues#8181] opened 2017-05-20 01:40 UTC
Im in a guild with my friend Sentrack and there is a glitch/bug? which the player names double.
Normally this is no big issue but past a certain point when my friend Sentrack gives xp to the guild it doesnt update/progress even after a couple of days it didnt update. Here are some screenshots...
![proof 1](https://cloud.githubusercontent.com/assets/21965827/26271963/88455554-3cdb-11e7-95be-9686f27023ac.jpg)
and this...
![proof 2](https://cloud.githubusercontent.com/assets/21965827/26271971/ae2126e0-3cdb-11e7-96d4-bc8040a73334.jpg)
Finally this...
https://cdn.discordapp.com/attachments/315291235520610304/315301803128258560/image.jpg
Please help, its weird

**Comment by Trixter313** [comment] 2017-05-20 15:29
Have you made sure that their guild XP isn't set to 0%?

**Comment by thecoolkogut4** [comment] 2017-05-20 15:36
Last time I checked, if someone's glitched in the guild (changes their name while in the guild) they can't give xp. All they can do is war, take up 2 guild spots, and talk.

**Comment by Epicdolphinator** [comment] 2017-05-20 17:38
Sentracks Xp was set to 25% and yes he did indeed change his name is their a way to fix it?

**Comment by thecoolkogut4** [comment] 2017-05-20 17:48
Currently there is no way to fix it. The devs are also working to fix this issue

**Comment by Epicdolphinator** [comment] 2017-05-20 23:58
alright thanks for the help anyway 👍

**Comment by Trixter313** [comment] 2017-05-21 05:14
Duplicate of https://github.com/Wynncraft/Issues/issues/7408

**Closed by Trixter313** 2017-05-21 05:14 UTC
