### ISSUE TITLE
can't pick class (Dark Wizard) 

### ISSUE THREAD

**Issue by HEWNRY** [Wynncraft/Issues#6416] opened 2016-10-18 16:07 UTC
When i try to pick my Dark Wizard, the selection screen disappears and the chat says: "There has been an error... Try again.". Since the main thread for this issue is closed and doesnt provide any solution im making this one (hope i didnt overlook anything and this isnt a duplicate)

**Comment by LordHelmchen98** [comment] 2016-10-19 18:17
Duplicate of #5418 

I hope the advices on that thread help you otherwise Im afraid you have to use another class :/

**Closed** 2016-10-19 18:43 UTC
