### ISSUE TITLE
Can not identify bobs wand

### ISSUE THREAD

**Issue by unusualphysics** [Wynncraft/Issues#6348] opened 2016-10-07 21:15 UTC
![2016-10-07_15 12 08](https://cloud.githubusercontent.com/assets/22690207/19205572/8c3a650a-8ca0-11e6-838f-65ca2352a383.png) 
![2016-10-07_15 14 10](https://cloud.githubusercontent.com/assets/22690207/19205601/bd4a8bf2-8ca0-11e6-9466-00ef201583a9.png)

**Comment by Imaxe** [comment] 2016-10-07 22:06
This is a known bug, and its being worked on. It's not that simple to solve apparently

**Comment by unusualphysics** [comment] 2016-10-08 02:17
Thanks, Imaxe 👍

**Comment by Moe-Ronickah** [comment] 2016-10-09 18:27
How old is that wand?  Did you just obtain it or is it from pre-Gavel?

**Comment by Trixter313** [comment] 2016-10-10 10:48
Duplicate of https://github.com/Wynncraft/Issues/issues/6171

**Closed by Trixter313** 2016-10-10 10:48 UTC
