### ISSUE TITLE
I Keep getting kicked for killing mobs

### ISSUE THREAD

**Issue by TheToastLegacy** [Wynncraft/Issues#5079] opened 2016-05-24 14:48 UTC
# Delete this line if you've searched for a duplicate issue first
Internal Exception: io.netty.handler.codec.DecoderException: Unknown serializer type 16
This message comes up when I shoot a mob on wynncraft with a bow it only start happening recently but keeps happening now so I need help to try and fix this cos it annoys me and my only good class is my hunter.

**Comment by Odnod** [comment] 2016-05-24 18:05
What version of Minecraft are you using?

**Comment by Trixter313** [comment] 2016-05-24 22:25
Duplicate of https://github.com/Wynncraft/Issues/issues/5017

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-05-24 22:25 UTC
