### ISSUE TITLE
Armor getting deleted

### ISSUE THREAD

**Issue by Lulon27** [Wynncraft/Issues#3548] opened 2016-01-05 11:15 UTC
When you try to equip armor that is above your level and your inventory is full, it gets deleted.

How to recreate:
- Make sure that your inventory is full and you have an armor piece above your level in it.
- Throw an item stack on the ground and stand on it.
- Open your inventory and pick the armor piece above your level, so that the stack you just threw on         the ground fills the new slot, and equip the armor.

**Comment by Trixter313** [comment] 2016-01-06 09:17
Duplicate of https://github.com/Wynncraft/Issues/issues/3153

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-06 09:17 UTC
