### ISSUE TITLE
I know the Dungeons are being re-worked, but come on.

### ISSUE THREAD

**Issue by Bluey2328** [Wynncraft/Issues#5768] opened 2016-08-18 14:04 UTC
This is probably the most crap Ive see on this server. Please put a little more effort into making sure this doesnt happen :P 
![2016-08-18_10 02 57](https://cloud.githubusercontent.com/assets/21105021/17776527/fdf3a4e2-652a-11e6-8826-248b08ac9355.png)
^Terrible Screenshot
(Animal Dungeon Boss is stuck outside of the barrier thingys)

(Update: Somehow as I was writing this, I beat the dungeon O.o)

**Comment by Trixter313** [comment] 2016-08-18 15:56
Duplicate of #3191

**Closed by Trixter313** 2016-08-18 15:56 UTC
