### ISSUE TITLE
Mixed Feelings quest bug

### ISSUE THREAD

**Issue by SS12121** [Wynncraft/Issues#7709] opened 2017-04-08 13:39 UTC
I tried talking to the NPC, but after being TPed the first time, the NPC did not talk. 
Tried changing servers, but that didn't work as well, killing myself did not work as well.
Is it possible for a mod/admin/GM to restart my quest to see if it works?
Edit: This was at the beginning of the quest, my IGN is SS121

**Comment by AscendedKitten** [comment] 2017-04-08 14:00
Duplicate of #7703; I aware of the issue and working on it, sorry for the inconvenience!

**Closed by AscendedKitten** 2017-04-08 14:00 UTC
