### ISSUE TITLE
"À" appears in dungeon names and other places

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#5851] opened 2016-08-29 01:45 UTC
What look like spaces in the dungeon names are actually a bunch of À's. You can't see this when using the Wynncraft resource pack, because the À will become invisible, but if you don't use the resource pack you can see it.

<img width="489" alt="bug1" src="https://cloud.githubusercontent.com/assets/16504771/18038640/718b4154-6d4f-11e6-8706-e0ea132b0b6a.png">|<img width="385" alt="bug2" src="https://cloud.githubusercontent.com/assets/16504771/18038638/71870396-6d4f-11e6-9264-dba0657e7ee8.png">
:---:|:---:

<img width="856" alt="bug3" src="https://cloud.githubusercontent.com/assets/16504771/18038639/7187db5e-6d4f-11e6-8c65-2449469b82b1.png">

Maybe it's just my OCD.

**Comment by KillerBee524** [comment] 2016-08-29 01:50
It Happens With The Resource Pack In Troms, Right Here:
![2016-08-28_18 19 24](https://cloud.githubusercontent.com/assets/21299339/18038709/35ca5c94-6d50-11e6-8984-16e45c0c50e7.png)

**Comment by Trixter313** [comment] 2016-08-29 01:58
Duplicate of https://github.com/Wynncraft/Issues/issues/5845

**Closed by Trixter313** 2016-08-29 01:58 UTC
