### ISSUE TITLE
I LOST MY ETHEREAL (bug)

### ISSUE THREAD

**Issue by endgameXp** [Wynncraft/Issues#3238] opened 2015-12-27 16:49 UTC
About 30 minutes ago, I was on Server16 I think, and it was very laggy at me. I was doing the "Lazarus Pit" quest, at the basement at the code. Then I tried to switch the servers to a clear server, it was Server5, and I realize that I haven't got my Ethereal anymore. Btw. my Server was clear, and desperately I tipp all slots in my Inventory, but I found no wand there. Maybe I dropped the wand at Server16, so I went to this Server back, and I didn't found him. 
Guys. Although I have the Bob's Mythic Wand, but I need some reasons why the Ethereal is glitched out. Just write down some ideas for me. Thanks.
:(
LG endgame

**Comment by Equipa2** [comment] 2015-12-27 17:53
It appened the same thing but with my LE

**Comment by Verret001** [comment] 2015-12-27 21:12
Duplicate of all of these 
#3205 #3216

**Closed** 2015-12-27 21:55 UTC
