### ISSUE TITLE
Just got a new IGN

### ISSUE THREAD

**Issue by nathannck** [Wynncraft/Issues#1589] opened 2015-02-04 16:37 UTC
Hi, I've just got a new InGame-Name and i don't own the guild The Illuminati. My name was changed from: nathannck to G3tR3ktByNathan. Can you please fix this? Thank you =D

-nathannck

**Comment by vogelmet** [comment] 2015-02-04 17:25
nice bug dude ;) please post this in the forum and not here. this is the bug and issue forum. 
Maybe post this in the "guilds" forum

**Comment by Jamdog** [comment] 2015-02-05 01:04
Duplicate of https://github.com/Wynncraft/Issues/issues/1588

@vogelmet: This **is** a bug.  

Mojang have recently begun allowing players to change their IGN, but after doing so, the player retains the same Unique User ID (UUID).  Some servers will correctly use the UUID when dealing with player informaton, but Wynncraft uses the Username, and so when a player changes their IGN with Mojang, they currently lose all their character/inventory details and have to restart.

Using the Mojang API, you can get your UUID - @nathannck , [here's yours](https://api.mojang.com/users/profiles/minecraft/G3tR3ktByNathan).

**Comment by epicman739** [comment] 2015-02-05 03:25
So @Jamdog if we change our username it will reset our Wynncraft stuff?

**Comment by Jamdog** [comment] 2015-02-05 08:20
Seems that not everything will reset, as I can see that many players have already changed their IGN without having to restart, I think I just mis-read Issue https://github.com/Wynncraft/Issues/issues/1588.  There are still some issues in Wynncraft caused by a name-change, though.
Current known problems include:
* Guilds not recognising the new name, and members not being able to use guild chat
* VIP and VIP+ status not recognised in Lobby ( https://github.com/Wynncraft/Issues/issues/1590 )

**Closed** 2015-02-07 20:43 UTC
