### ISSUE TITLE
Persisting Class Selection Glitch

### ISSUE THREAD

**Issue by Scrambleking** [Wynncraft/Issues#3663] opened 2016-01-11 23:47 UTC
Even after the pervious fix to the Class Selection Glitch I still permanently fall on servers after I spawn, it may be teleporting me one block lower than it means to, but I continue to fall under the box for an indefinite amount of time, and do not get the selection screen

-Scrambleking

PS: I can still /hub and /lobby but nothing else

**Comment by RubberDuckyNinja** [comment] 2016-01-11 23:52
Please post screenshots? Also duplicate pls!

**Comment by Scrambleking** [comment] 2016-01-12 00:17
Video: https://youtu.be/_ZLB8tSh04c

**Comment by Scrambleking** [comment] 2016-01-12 00:25
![2016-01-11_17 22 52](https://cloud.githubusercontent.com/assets/16635570/12250971/454e23b2-b888-11e5-8a7f-e103fb2d8452.png)

**Comment by Scrambleking** [comment] 2016-01-12 00:25
still falling from the vid

**Comment by Trixter313** [comment] 2016-01-12 00:55
Duplicate of https://github.com/Wynncraft/Issues/issues/3636

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-12 00:55 UTC
