### ISSUE TITLE
Guilds (making) PLEEEEAS FIX

### ISSUE THREAD

**Issue by TGNebulA** [Wynncraft/Issues#3404] opened 2015-12-31 22:22 UTC
Ok i've checked with friends etc and i'm pretty sure i can claim that the guild master in Cinfras is pretty damn fussy and selective of what you can call you guild. Which is apparently nothing at all!!!

It seems whatever combination of letters you type for a name to call your guild. The master will always repeat the same message: please use characters within A-Z in English. This guy must be pretty damn stupid if he thinks i'm typing in bloomin' Arabic coz im not!
Please attempt to fix this at least because i'm gonna start to believe that the guild master hit his head and got brain damage on the way from Troms to Cinfras!!!
![2015-12-31_22 15 22](https://cloud.githubusercontent.com/assets/16475006/12068764/9f56382e-b00c-11e5-8fce-7665d72c967b.png)
![2015-12-31_22 15 47](https://cloud.githubusercontent.com/assets/16475006/12068766/a438fb60-b00c-11e5-9f69-a00c612a522a.png)
![2015-12-31_22 16 11](https://cloud.githubusercontent.com/assets/16475006/12068773/e8328fb6-b00c-11e5-85d2-99a875963bd9.png)

**Comment by TGNebulA** [comment] 2015-12-31 22:27
all i want is a guild :( *cries*

**Comment by Joshytron** [comment] 2015-12-31 22:39
you used a space

**Comment by vboyswag** [comment] 2016-01-01 00:15
He is pretty Damn Selective -.-

**Comment by Trixter313** [comment] 2016-01-01 07:25
Duplicate of https://github.com/Wynncraft/Issues/issues/3190

Please direct any further comments to the original thread. Thank you very much! =)

**Closed by Trixter313** 2016-01-01 07:25 UTC
