### ISSUE TITLE
Kelight's Toothbrush no permission

### ISSUE THREAD

**Issue by Greenthing4444** [Wynncraft/Issues#4161] opened 2016-02-17 06:22 UTC
So I recently got this item and then when I was trying to open a door then a chest it said you have no permission for this area. I am not able to interact with anything with it and have to switch to an open hand to open anything.

![2016-02-16_22 02 38](https://cloud.githubusercontent.com/assets/17287026/13101465/bbf88392-d4fb-11e5-8ae9-a78b051fc860.png)

**Comment by TrashcanMan** [comment] 2016-02-17 15:02
It's not just Kelight's Toothbrush, it appears to be broken for everything. This should be fixed soon.

**Comment by Trixter313** [comment] 2016-02-18 12:05
Duplicate of https://github.com/Wynncraft/Issues/issues/3902

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-18 12:05 UTC
