### ISSUE TITLE
Quest not working.

### ISSUE THREAD

**Issue by AThao1** [Wynncraft/Issues#4425] opened 2016-03-04 00:12 UTC
In the quest Canyon Condor. When you meet Jankan in front of the mine. He asks you to go into the mine and get him 10 golden bars. After I went into the mine and discovered nothing at the end I decided to look it up on the WynncraftWiki. I even found videos on it that show that I am in the right spot. But the Gold is not spawning where it's suppose to be spawning. I can't complete this quest without the gold.

**Comment by Odnod** [comment] 2016-03-04 00:47
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-04 00:52 UTC
