### ISSUE TITLE
Glitched Mixed Feelings quest

### ISSUE THREAD

**Issue by DominikGamer** [Wynncraft/Issues#7713] opened 2017-04-08 15:32 UTC
I started the quest, it teleported me, then i stuck in a small  barrier room in front of Javen. Nothing happened, so i killed myself. Now if i right click on the npc it doesn't say anything, and i can't do anything about this glitch, but the quest book say that "Talk to Javen to find out more about what happened"

**Comment by Marhzy** [comment] 2017-04-08 19:36
I have the same issue.

**Comment by AscendedKitten** [comment] 2017-04-08 21:02
Duplicate of #7703, should be fixed once the new patch is applied!

**Closed by AscendedKitten** 2017-04-08 21:02 UTC
