### ISSUE TITLE
No Permission Bug - Spirit Bow

### ISSUE THREAD

**Issue by TimeThunder** [Wynncraft/Issues#4901] opened 2016-04-27 12:06 UTC
When you have the Spirit Bow Level 40 equipped and you right click any block, it will say "You don't have permissions for this area!".

**Comment by Trixter313** [comment] 2016-04-27 12:10
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

If you look at the comments, it will explain the no permission message.

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-27 12:10 UTC
