### ISSUE TITLE
Blue Mask not rendering

### ISSUE THREAD

**Issue by SuperArcher** [Wynncraft/Issues#1964] opened 2015-06-05 02:37 UTC
Blue mask helmet is not rendering! As in I cannot see it in inventory or f5, other helemets render in, but blue mask does not, this only happens to me: StoryStudio (IGN) All my skin settings are fine, I reinstalled minecraft completely, no results, I am on 1.8.6 using no mods, I play as archer no other player can see the blue mask that Im wearing either, however, they can see rest of armour, this skin armour thing-not rendering is driving me nuts, I am really bumed out that the helmet is not rendering pls help ):

**Comment by Moe-Ronickah** [comment] 2015-06-05 05:21
Possible dupe of #1909 ?

**Comment by SuperArcher** [comment] 2015-06-05 13:10
No, I have no clue why its not working, I got the blue mask way before 1.12 maybe that affects it, also before it was rendering just fine...

**Comment by Moe-Ronickah** [comment] 2015-06-05 21:51
Me, personally?  No, I'm not staff, in any way, shape, or form.

**Comment by SuperArcher** [comment] 2015-06-06 03:54
can't you contact staff though?

**Comment by epicman739** [comment] 2015-06-06 17:34
Well, staff members do go through the Github every so often. They're bound to notice this sooner or later, then it's just a matter of time until it's fixed.
Also I've had this issue before with a different helmet, but it started rendering again after a while. I think it was due to some transparency issues on my skin file, because once I fixed that and re-uploaded my skin, it started working.

**Closed** 2015-07-06 03:37 UTC
Labels: duplicate
