### ISSUE TITLE
Can't Identify this Helmet

### ISSUE THREAD

**Issue by ZERORN** [Wynncraft/Issues#2244] opened 2015-08-23 22:44 UTC
This is a Legendary Chainmail Helmet, named "Pelier" (I don't know how to type that kind of e)
Def: 51
Lv. min: 42
Clean, no Enchants 

I am unable to Identify this Legendary item no matter what I try. I have relogged, used it on different class, and it still doesn't work. I got it through Mob Loot or Loot Chests.

![2015-08-23_12 32 26](https://cloud.githubusercontent.com/assets/13934970/9430515/83d4c9a0-4994-11e5-9621-4ca686e12f7f.png)

**Comment by Trixter313** [comment] 2015-08-23 22:45
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!

**Closed** 2015-09-11 19:58 UTC
