### ISSUE TITLE
I stuck in my guild

### ISSUE THREAD

**Issue by CracotteFX** [Wynncraft/Issues#4656] opened 2016-03-26 13:12 UTC
Hi.I need help i can't leave my guild with my friend.Can you disband this pls ? (Name of the guild : KryJeKtion)
Thank you for your help

**Comment by Trixter313** [comment] 2016-04-05 04:48
Could you give us a little more detail? What happens when you try to leave? Are there any messages in chat about it? Etc. Thanks!

**Comment by Trixter313** [comment] 2016-04-05 04:58
Assuming your username is the same as your Github, it appears that you've changed your name in the past, meaning this is a duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-05 04:58 UTC
