### ISSUE TITLE
Armor not working like it should

### ISSUE THREAD

**Issue by ThisLittleGirl** [Wynncraft/Issues#3823] opened 2016-01-23 15:20 UTC
Hello, 

I've been playing wynncraft for a long time now and I have never seen this before.
Since I can't use my armor anymore I can't use other items either.
I hope this can be fixed in some way because I don't have anything to replace it with and I can't go far from cities now.

ThisLittleGirl
 
![yfbfhof](https://cloud.githubusercontent.com/assets/16853504/12530882/3db2270c-c1ed-11e5-8a1f-ae68562a14cf.png)

**Comment by Dar-krusos** [comment] 2016-01-23 16:56
This is a duplicate of issue #3175, so please reply there (with this image if you want).

**Closed** 2016-01-23 16:58 UTC
