### ISSUE TITLE
Unban glitch

### ISSUE THREAD

**Issue by parsakarami03** [Wynncraft/Issues#6320] opened 2016-10-03 00:09 UTC
@colinrioux I have waited 2 days for my ban as that was the wait time I got but the problem is I can go into hub but I can't access of the servers/worlds I do have a image to show what I mean 

Thank you for your help

**Comment by Trixter313** [comment] 2016-10-03 02:04
Dupe of https://github.com/Wynncraft/Issues/issues/6297

**Closed by Trixter313** 2016-10-03 02:04 UTC
