### ISSUE TITLE
Disapeared class

### ISSUE THREAD

**Issue by teuntheman** [Wynncraft/Issues#7104] opened 2017-01-05 11:59 UTC
I logged in the server todat and i chose a world but when the class menu opened my warrior class of level 37 kust wasn't there and i did not delete last time i came on the server but what do i do now?

**Comment by DebugingLonks** [comment] 2017-01-05 14:35
You prob right clicked it. But, as we have said on the others post like this: 

Unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

Duplicate of: 

#7096 
#6981 

And many others. Please don't post duplicates! Thanks!

**Comment by teuntheman** [comment] 2017-01-06 16:38
I did not right click it

**Comment by ColinRioux** [comment] 2017-01-06 18:44
Instead of creating a new issue, comment on one of the duplcates @DebugingLonks listed. Thank you.

**Closed** 2017-01-06 18:43 UTC
