### ISSUE TITLE
Not all guild members are teleported to war

### ISSUE THREAD

**Issue by Arreme2000** [Wynncraft/Issues#3934] opened 2016-01-31 14:45 UTC
Hello, I know that the attack-defend feature of Guilds is recent and is still in beta, but I'd like to inform about a big error that happends often:

When we attack on others territories, sometimes when the count gets to 0, we can't join the war world, just like nobody had been in there. Also, when we capture a territory, it also happends that we can't `put mobs and we have to change server.
As a final thing, the guild HUD on the top is a bit bugged to, sometimes doesn't show the territory you are in,
Thanks for your time, 
Arreme

**Comment by Trixter313** [comment] 2016-01-31 16:47
Could you post screenshots of the bugs? Thanks!

**Comment by Arreme2000** [comment] 2016-01-31 18:39
Done! Hope this bug finally is fixed as is completely annoying 
http://imgur.com/a/NXvrL
Photo 1: I was ACTUALLY inside the territory and I didn't get tp
Photo 2: As you can see, there is no "Guild bar" On the top. Well, right now, at least for me, starts flashing, so is constantly disappearing. Also, very often, the territories are not displayed.
Photo 3: As you can see, the bar is there now.
Photo 4: "The Battle will begin in 0 sec" and as you can see some of the people didn't get Tp
Photo 5: Continuation of Photo 4
Photo 6: They kept trying and nothing.
Photo 7: Continuation of 6
Photo 8-9: Just more examples of trying to enter to the guild war.
Hope I helped with all of this! Thanks for all your time.
P.D. Do you know when the /forum command will be fixed too D:?

**Comment by Trixter313** [comment] 2016-01-31 19:23
Thank you for the wonderful screenshots. =)

As for the bar at the top, they use boss health bars for this and boss health bars are buggy in general, even in vanilla MInecraft so I don't believe much can be done about that.

The part where some don't get teleported seems to be a fixable issue.

No clue when /forum will be fixed, whenever they can figure out how to fix it. Hopefully soon.

**Comment by Dar-krusos** [comment] 2016-02-01 05:20
This is most likely due to lag. To workaround this (until they find a way to fix it, if there even is a way), just change servers. Once you find one that teleports you to war, constantly use that one. Remember to track the ones that didn't work, so you don't have to check those ones (freshly-restarted servers tend to work, as they have less lag).

**Comment by Odnod** [comment] 2016-02-01 07:38
I have been noticing this for a while. Make sure that all of your guild members are on the server (one that you have confirmed to work) before attacking the territory. A while ago only server 2 worked to attack territory and I have no idea what causes it.

**Comment by redxdev** [comment] 2016-02-04 02:25
Hey, next time this happens let us know the exact time. It is possible it might be a bug with the way we spin up war servers, but I can't check without knowing the time.

Actually, see if you can write down the time that you started the attack (ie the time you ran the guild attack command). That's when we start creating the server, so it'll let me check our logs to see if something went wrong.

**Comment by Moe-Ronickah** [comment] 2017-01-29 18:44
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds are on hold until guild mechanics are re-written, at which time ALL current guild issues will closed.  Current guild issues are being left open for reference purposes.

**Comment by Moe-Ronickah** [comment] 2017-05-07 17:02
UPDATE:
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds will closed.  If you want to know if your guild issue has been reported already, please go back and do a search on "guilds".  From there, you will see all of the guild issues and you can check to see if your issue is known.
Only ONE current guild issue is being left open for reference purposes.  #3665

**Closed by Moe-Ronickah** 2017-05-07 17:02 UTC
Labels: Game Mechanics, Guilds
