### ISSUE TITLE
Wynnexcavation Site B, No Purple Crystal Shard.

### ISSUE THREAD

**Issue by BrianMcFluffy** [Wynncraft/Issues#4247] opened 2016-02-24 12:29 UTC
I just did the Wynnexcavation Site B quest, but when i reached the purple crystal, there was no "purple crystal shard" lying on the ground. I've tried changing servers, reconnecting, using the fixquest command but nothing helped (actually the fixquest command gave me back the slime scooper ._.). What am I supposed to do? Thanks for taking the time to read this post, hoping to see an answer soon. :)

**Comment by trickstini** [comment] 2016-02-24 12:32
I think the whole server is bugged with falling objects, Bc I'm on "beneath the depths" and maps are supposed to fall but they aren't falling. So I'm not sure what is going on right now...

**Comment by BrianMcFluffy** [comment] 2016-02-24 12:46
Okay, then i'll just wait for the  admins to fix it.
(Thanks for answering btw :))

**Comment by DarkDemonDragon** [comment] 2016-02-24 13:19
Are you sure you are at the right location? Also there have been reports of other areas where items are supposed to spawn not spawning, so this is probably a major issue that the admins are aware of and are working on. Check in again in a few hours or so.

**Comment by DarkDemonDragon** [comment] 2016-02-24 13:25
Duplicate of #4236 Please close this and follow the original.

**Closed** 2016-02-24 16:42 UTC
