### ISSUE TITLE
Is this even possible ???

### ISSUE THREAD

**Issue by ra3yvtc** [Wynncraft/Issues#6370] opened 2016-10-10 05:47 UTC
Im in world 1, I went out of my room for few minutes came back and saw this in the picture attached below....
![wither](https://cloud.githubusercontent.com/assets/22724246/19227721/84f7cd98-8ece-11e6-85f7-c9eca2398d8a.png)

Is it even possible or whats going on??? The wither was somehow Spawned

**Comment by Trixter313** [comment] 2016-10-10 11:00
(Assuming you're talking about the boss bar) Duplicate of https://github.com/Wynncraft/Issues/issues/6359

Wynncraft uses boss bar to display region info and guild XP, but it is currently having issues.

**Closed by Trixter313** 2016-10-10 11:00 UTC
