### ISSUE TITLE
Guild not showing correctly in /guild stats and /guild leaderboard + xp not getting tracked properly

### ISSUE THREAD

**Issue by CodenBeast** [Wynncraft/Issues#3998] opened 2016-02-06 17:29 UTC
I created a guild yesterday. I called it The Immortals [TiO]
The problem is that it shows as a guild called Nobody [None] which i though was very weird. It shud not do this and it shud be inpossible to have [None] considerring that is 4 letters.
Now other things that i have notised is that it says we are lvl 26 with 0 members which is even weirder. The members i have in the Guild right now is CodenBeast (Me) and Eragon1112 and soon ComputingMonster.

I Think this might be a causing factor for the /guild xp command not working, which also is a problem in my guild.
So far Eragon1112 can give xp from killed mobs but i cant.
This is weird and i would be very happy if you could respond to this and maybe come up with a fix.
Thank you in advance.

![](https://cloud.githubusercontent.com/assets/17100063/12868108/dc0432d4-ccff-11e5-8b30-34960004f41f.png)

Edit: ComputingMonster's xp gain is also showing up. I have notised that while it doesnt show up in the /guild list mu guild still gets the xp i harvest, and the guild levels up. Which would indicate that the /guild xp command does work. Just very boring not getting to show that the leader of the quild is aqually doing something... I dont know if you can fix that small bug. We still have the bug off being shown as Nobody [None]

![2016-02-06_22 11 22](https://cloud.githubusercontent.com/assets/17100063/12869392/95e1628a-cd1e-11e5-8c15-310d76494077.png)

Edit: I Think i found the problem. In my wynncraft account it still says that i am kennel1, i changed my name to CodenBeast a good while ago. Can you guys confirm this? That it still says kennel1
I know im asking for alot but... please

**Comment by CodenBeast** [comment] 2016-02-06 17:31
I forgot to add the picture
![2016-02-06_18 24 00](https://cloud.githubusercontent.com/assets/17100063/12868108/dc0432d4-ccff-11e5-8b30-34960004f41f.png)

**Comment by Trixter313** [comment] 2016-02-07 00:43
Duplicate of https://github.com/Wynncraft/Issues/issues/3799

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-07 00:43 UTC
