### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by Chri630** [Wynncraft/Issues#3298] opened 2015-12-28 21:53 UTC
This bug goes on and off for me but its still very irritating. When I leave the game and try to rejoin it won't let me join for 5 minutes plus. It just says "Disconnected" or its in online mode or something. And sometimes it says "Timed out" also. ATM this issue has gone on for 10 minutes plus. Sometimes the server wont even ping.
![2015-12-28_16 53 52](https://cloud.githubusercontent.com/assets/16396890/12026106/a1a8e22e-ad83-11e5-80f8-00f61618a5e5.png)
![2015-12-28_16 55 11](https://cloud.githubusercontent.com/assets/16396890/12026116/c75882ae-ad83-11e5-9cc6-294abff3fbe5.png)

![2015-12-28_16 50 37](https://cloud.githubusercontent.com/assets/16396890/12026083/71cbe998-ad83-11e5-802b-4f29431810cb.png)
![2015-12-28_16 50 59](https://cloud.githubusercontent.com/assets/16396890/12026084/71cd8ef6-ad83-11e5-8d44-72768ca41512.png)

**Comment by Verret001** [comment] 2015-12-28 22:03
Following Info from @meatloaf4311 
If you are using any mod like optifine, Update. I had that issue the other day.
Simple solution is to Restart Minecraft
If that didn't work then try Toggling your internet on/off
If that didn't work then try restarting your computer
If that didn't work then try updating Java
If that didn't work then something is probably broken on Wynncrafts end

**Comment by DivisionGaming** [comment] 2015-12-29 02:58
I am also facing this problem.
I have tried the above solutions with no success. Help would be greatly appreciated.
Thanks (:

**Comment by Chri630** [comment] 2015-12-29 18:59
Ya I tried everything up there, updated java, went to 1.8.9, everything. I do believe this is something on wynncraft's end because all other servers work fine for me.

**Comment by ltvuong** [comment] 2015-12-30 02:15
This happened to me also but I found away to temporarily bypass the problem.
https://forums.wynncraft.com/threads/all-possible-ips.100486/
That forum link above contains the different ips of Wynncraft. Usually, when that error happens I switch back and forth between those ips until it works. 
Another method is that when you are in the server selection menu, delete Wynncraft from your server list and then readd it.
ANOTHER method is when you first start up Minecraft, change the Minecraft version in your file. I'm not talking about reverting back to 1.5.2, but changing from "Use latest Version" to the exact version of Minecraft you are using currently. All this does is essentially stop the auto updating of Minecraft, but this change should not affect anything and be changed back in an instant.

**Comment by Trixter313** [comment] 2015-12-30 21:01
If Itvuong's suggested fixes your issue, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by HeatBlade** [comment] 2016-01-09 17:56
i have tried every single thing u guys said and nothing worked now i will never get to play wynncraft again :'(

**Comment by ltvuong** [comment] 2016-01-09 18:01
The server is down for maintenance. That's why the fixes did not work. I suggest you try again in a couple of hours or something.

**Comment by HeatBlade** [comment] 2016-01-09 18:05
ok thanks
but... it show 100/100 players on

**Comment by ltvuong** [comment] 2016-01-09 18:11
Probably, just content team members stress testing the server. Just wait until the server comes back online.

**Comment by HeatBlade** [comment] 2016-01-09 18:23
thanks! for the help

**Comment by Trixter313** [comment] 2016-01-10 16:39
Are people still having these issues since the server was down yesterday?

**Comment by Trixter313** [comment] 2016-01-24 07:24
I'm assuming the issue is resolved as no one responded to my last comment and shall close the issue.

**Closed by Trixter313** 2016-01-24 07:24 UTC
Labels: Connection issues
