### ISSUE TITLE
Pulling Back Bow/Arrow in Inventory Glitch

### ISSUE THREAD

**Issue by Darkdragon902** [Wynncraft/Issues#2183] opened 2015-08-08 18:13 UTC
So I was messing around in Detlas today and I saw this. I am an archer and I was able to pull back my bow and had an arrow in my inventory. The arrow disappeared in a second after it happened and I can't pull the bow back again. It just shoots the arrow like normal. As you can see from the top of the picture below, this is modern Wynn. After the 1.12 update.
![2015-08-08_14 04 33](https://cloud.githubusercontent.com/assets/12682634/9151637/885cb2c6-3dd7-11e5-9ad9-1e359ff84103.png)

**Comment by Trixter313** [comment] 2015-08-09 01:24
I'm not sure what the issue is here, didn't it solve itself for you? The staff already programmed the game to take arrows away as you experienced in case this ever happened. One-time issues usually don't need to be reported.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Closed** 2015-08-17 07:08 UTC
