### ISSUE TITLE
Potion Of Wisdom texture

### ISSUE THREAD

**Issue by Ninjakamsonic** [Wynncraft/Issues#5622] opened 2016-07-30 13:01 UTC
Hello.
I found a texture bug.
When im throwing potion of wisdom, his texture is a normal water bottle.
http://imgur.com/a/3V4AH
And when im picking it up. It's a normal texture.
http://imgur.com/a/g3Zgl

**Comment by Moe-Ronickah** [comment] 2016-07-31 00:11
Are you using MC 1.8 or MC 1.9 or above?
If you are using MC 1.9 or above, this is a duplicate of #4548 .

**Closed** 2016-09-10 19:15 UTC
