### ISSUE TITLE
Enderchest

### ISSUE THREAD

**Issue by hEYgUYZ** [Wynncraft/Issues#5222] opened 2016-06-14 00:02 UTC
(I'm posting this issue for my friend)

EXACT QUOTES
"EWRJEWOIRJEOIWFWE I was ganna make my outer layer of my echest into a rainbow (jester items) i had them on the last row (the bottom row) and i bought another row and they disappeared"
So she had stuff on the very bottom row of her enderchest, upgraded the space with eb, and everything on the bottom row disappeared
https://gyazo.com/b6ea16517beeaf4a6787038b4bcf5ccf

**Comment by Trixter313** [comment] 2016-06-14 00:23
Duplicate of https://github.com/Wynncraft/Issues/issues/4091

Please direct any future comments to the original thread. Thanks!

Unfortunately Wynncraft has a strict no refunds policy so we can't refund the items but we are working hard to resolve the issue so it doesn't happen again.

**Closed by Trixter313** 2016-06-14 00:23 UTC
