### ISSUE TITLE
WynnExcavation Site A Quest Bug

### ISSUE THREAD

**Issue by Tontschii** [Wynncraft/Issues#3907] opened 2016-01-29 20:33 UTC
I was doing the quest "WynnExcavation Site A" and as I came out of the tombs I was instructed to clear my inventory before speaking to Excavator Vade again to finish the quest. When I came back to him with free space in my inventory, he said "Have you translated that text yet? I told you, take it to the tent up there and give it to Tesha!". After I went to her and she told me "Take that to vade, and don't read it!", he told me the same thing again.. 
thanks beforehand

**Comment by Trixter313** [comment] 2016-01-30 00:14
_Try_ the command /fixquests but it most likely won't help. Other than that this will need some admin intervention so just wait until an admin sees this!

**Comment by Trixter313** [comment] 2016-01-30 03:13
Duplicate of #3351

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-30 03:13 UTC
