### ISSUE TITLE
Lava cow boss in animal dungeon

### ISSUE THREAD

**Issue by Nyxxaa** [Wynncraft/Issues#4004] opened 2016-02-06 22:07 UTC
We were running the animal dungeon. Made it to the boss. Masterdeadpoolio the assassin used spin attack. The lava cow was forced outside the invisible wall. Finally he respawned after having walked into the lava. When he respawned we began again to kill him. We got him down to 100 health then he respawns again at full health. We tried multiple time. I had completed this dungeon previously so I am uncertain what happened. Any further information you need let me know.

**Comment by Trixter313** [comment] 2016-02-09 02:43
Duplicate of https://github.com/Wynncraft/Issues/issues/3191

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-09 02:43 UTC
