### ISSUE TITLE
No saccharum spawning in the Spider Cave

### ISSUE THREAD

**Issue by HesusKristus** [Wynncraft/Issues#4423] opened 2016-03-03 23:15 UTC
Self explanatory, been waiting around for 10 minutes and nothing has spawned.

**Comment by Odnod** [comment] 2016-03-04 00:47
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Comment by TheLegendaryJohn** [comment] 2016-03-04 19:49
Indeed!

**Closed** 2016-03-05 05:31 UTC
Labels: Game Mechanics, Quests
