### ISSUE TITLE
Wynncraft Suspenden Flower.. No flowers!

### ISSUE THREAD

**Issue by zauberbart** [Wynncraft/Issues#4382] opened 2016-03-01 16:07 UTC
# Delete this line if you've searched for a duplicate issue first
I visited the cave of suspended flower and at the position aren't spawning flowers. Pls help!

zauberbart

**Comment by Trixter313** [comment] 2016-03-01 17:48
Duplicate of https://github.com/Wynncraft/Issues/issues/4236

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-01 17:48 UTC
