### ISSUE TITLE
Server Glitched and I lost my armor

### ISSUE THREAD

**Issue by Christinel8** [Wynncraft/Issues#4229] opened 2016-02-23 05:02 UTC
Can you roll back the server about 30 minutes from this time right now? When the server crashed, or whatever happened, i logged in and my armor was gone. Please roll it back, this is not fair. I have heard that this happens to other players as well. Please please please bring my armor back on my archer. Christinel8 is my IGN. PLEASE I'm begging u :(

**Comment by Dar-krusos** [comment] 2016-02-23 05:12
I'm sorry, but that is out of the admins' policies. You won't be able to get back any of your items, and I'm afraid you'll have to try and buy or farm for new ones.

**Comment by DarkDemonDragon** [comment] 2016-02-23 13:23
@Christinel8 do you remember what was said in the chat when you logged in? Was it something like:
"Armor requires a dexterity of 25"
in red text for each of your armor pieces?

**Comment by time5415** [comment] 2016-02-24 00:19
I actually lost my armor because of the red text!

[15:37:55] [Client thread/INFO]: [CHAT] Loading the WynnPack...
[15:37:55] [Client thread/INFO]: [CHAT] Select a class! Each class is saved individually across all servers, you can come back at any time with /class and select another class!
[15:37:55] [Client thread/INFO]: [CHAT] Thank you for using the WynnPack. Enjoy the game!
[15:37:59] [Client thread/INFO]: [CHAT] Venison requires your strength skill to be at least 20.
[15:37:59] [Client thread/INFO]: [CHAT] Nesaak's Shadow requires your agility skill to be at least 10.
[15:37:59] [Client thread/INFO]: [CHAT] Kratke requires your strength skill to be at least 10.
[15:37:59] [Client thread/INFO]: [CHAT] SandStorm Walker requires your strength skill to be at least 5.
[15:37:59] [Client thread/INFO]: [CHAT] Twist Band requires your agility skill to be at least 10.
[15:38:16] [Client thread/INFO]: [CHAT] [Info] You can look up all of your class information and future spells by visiting wynncraft.com/classes
[15:38:22] [Client thread/INFO]: [CHAT] Venison requires your strength skill to be at least 20.

I logged back on and I lost my Nesaak's Shadow, Kratke, and SandStorm because my armor popped into the inventory, and the band.

**Comment by DarkDemonDragon** [comment] 2016-02-24 04:28
Hmm this is very troublesome. The admins REALLY need to fix this issue. This is a combination of 2 very annoying bugs that when combined can be horrible. The first bug is that when a character loads there is some lag. If you are unlucky the armor will load BEFORE your stats do. When this happens the server does not register your skillpoints causing your character to not meet the armor requirements. Then the 2nd bug hits. Whenever the server forcibly places an item into the inventory and there is no room, the item(s) will be deleted. Honestly, you deserve to get your items back and you're free to apply to Salted or Grian, but unfortunately Wynncraft has a strict no refund policy. Feel free to try though. I'll make a thread on the forums about this.

**Comment by DarkDemonDragon** [comment] 2016-02-24 04:45
Here's the thread: https://forums.wynncraft.com/threads/this-bug-needs-to-be-aknowledged.113507/

Also, this is a duplicate of #4120 After you're done reading over things, please close this issue and follow the main issue.

**Comment by DarkDemonDragon** [comment] 2016-02-24 13:07
Issue has been confirmed to be resolved by Salted in the above thread.

**Closed** 2016-02-28 16:50 UTC
