### ISSUE TITLE
Cant connect to a server . please report?

### ISSUE THREAD

**Issue by sonicrush** [Wynncraft/Issues#3845] opened 2016-01-24 16:27 UTC
It says that could not fine a server to connect too, please report. Please help!
 this has been happening since yesterday 
![image](https://cloud.githubusercontent.com/assets/16866100/12537445/8a100baa-c28d-11e5-8e7d-2f64e2943bff.png)

**Comment by Trixter313** [comment] 2016-01-24 18:00
Duplicate of #3841 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-24 18:00 UTC
