### ISSUE TITLE
Haven't received the Liquified Emerald at the end of the quest

### ISSUE THREAD

**Issue by xPanduz** [Wynncraft/Issues#5300] opened 2016-06-24 12:38 UTC
Hello there,
want to report a bug: as soon as i finished the quest "Lost Royalty", it says that i gained +4096 emeralds (1LE), but there isn't any Le in my inventory :/
![schermata 2016-06-24 alle 14 35 37](https://cloud.githubusercontent.com/assets/19982429/16337929/58176054-3a19-11e6-950a-060d81863977.png)
![schermata 2016-06-24 alle 14 35 38](https://cloud.githubusercontent.com/assets/19982429/16337930/5846b3fe-3a19-11e6-97f0-b18a93726298.png)

**Comment by Trixter313** [comment] 2016-06-24 15:31
Duplicate of #3562 

Please direct any future comments to the original thread. Unfortunately Wynncraft has a soft no refunds policy

**Closed by Trixter313** 2016-06-24 15:31 UTC
