### ISSUE TITLE
Nice pointer to Deltas city... (Probably MHF_ fail)

### ISSUE THREAD

**Issue by LordDestroyer** [Wynncraft/Issues#1801] opened 2015-04-11 01:32 UTC
This is another one thing I've found:

![2015-04-10_18 04 16](https://cloud.githubusercontent.com/assets/11894763/7099709/e8f9a066-dffa-11e4-9dad-9dd9488708b5.png)

Well... The arrow there is nice, isn't it?

Steps to reproduce:
1) Use wrong MHF_something
2) Use it instead of th actual arrow

I don't remember coordinates, but I guess that it's (based on the dynmap) x:108; -1586.

EDIT: Nevermind, the coordinates are on the screen...

**Comment by LordDestroyer** [comment] 2015-04-11 01:32
"I don't remember coordinates" nevermind, just looked at the screen...

**Comment by Trixter313** [comment] 2015-04-11 01:49
The issue is most likely client side and not server side but there are so many possibilities of what went wrong. The skin servers could have been down when you started your Minecraft or some network firewalls block skins from working or it could have been a Minecraft version issue with all of the 1.8.x's and the server still technically being 1.7.10. I'll log on and see if the appropriate texture appears for me or not.

**Comment by Trixter313** [comment] 2015-04-11 02:01
Ok, the head is Steve for me also so it could be a server side issue because I saw other heads that are arrows and they worked fine.

**Comment by LordDestroyer** [comment] 2015-04-11 11:01
I can see every other arrow correctly. And yes, I'm running 1.8.3, maybe it uses different format for MHF_ heads... I don't know...

**Comment by LordDestroyer** [comment] 2015-04-11 11:02
I colsed it? How?

**Comment by LordDestroyer** [comment] 2015-04-11 11:02
Should

**Comment by LordDestroyer** [comment] 2015-04-11 11:03
... I just accidentaly closed something ...

I just tried to say that I also can see all other arrows fine, but I don't know if 1.8.3 (Which I'm running) handles the MHF heads in different way...

**Comment by AckroWynn** [comment] 2015-04-11 23:21
I will try to take a look at the issue and if possible, fix it.
If I do fix it on the build server, it will require a map update in order for it to be fixed on the public servers.

**Comment by AckroWynn** [comment] 2015-04-18 16:09
This is actually completely fine according to the build server, so I suppose it should be fine for you too soon.

**Closed** 2015-04-28 17:11 UTC
