### ISSUE TITLE
Corrupted Chunks at Nesaak

### ISSUE THREAD

**Issue by RPGcrafter** [Wynncraft/Issues#7822] opened 2017-04-12 03:19 UTC
The chunks at Nesaak seem to be corrupted and they look like worldedit bugs.

Screenshots:
![screenshot 20](https://cloud.githubusercontent.com/assets/27326135/24939724/e16ecd72-1f71-11e7-8e00-66cae1a27916.png)
![screenshot 21](https://cloud.githubusercontent.com/assets/27326135/24939730/e6c7abb8-1f71-11e7-8138-bdf7dce9e793.png)

**Comment by LordHelmchen98** [comment] 2017-04-12 03:29
Duplicate of #7817 look there for more information.

**Closed by LordHelmchen98** 2017-04-12 03:29 UTC
