### ISSUE TITLE
I Cannot Leave My Guild

### ISSUE THREAD

**Issue by BenOrBes** [Wynncraft/Issues#5691] opened 2016-08-08 19:21 UTC
I can't leave my guild whatever I do.
1. My minecraft username is BenOrBes
2. I cannot leave the guild "DeathReapers" or "DxR"
3. I have been kicked once (did not work).
4. I have left 7 times (none worked).
5. All evidence is in the screenshot:
![2016-08-08_15 19 08](https://cloud.githubusercontent.com/assets/20912503/17492819/9a67fd12-5d7b-11e6-9f36-6fc8c3fafd89.png)

*Also, this is over the course of months I have tried.
I only bring this issue up now because there is a different guild that I would like to join, as there wasn't in the past so I did not consider it a big enough problem to submit a report for.

**Comment by Trixter313** [comment] 2016-08-08 23:03
Duplicate of #3665 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-08-08 23:03 UTC
