### ISSUE TITLE
Why world, WHY?!

### ISSUE THREAD

**Issue by PerfectCobra7111** [Wynncraft/Issues#4905] opened 2016-04-28 13:32 UTC
Everytime I leave my guild, it doesn't let me leave, but this isn't your everyday guild glitch, my friends say they can leave their guilds, and everytime I leave, it says I left TWICE and takes my soul points, and whenever I talk in the /g chat, it says I talked TWICE, HELP ME, I NEED TO DANG LEAVE THIS GARBAGE OF A GUILD erm, no offence guild owner.

**Comment by YunoFGasai** [comment] 2016-04-28 14:04
This is your every day guild glitch, guilds weren't made to work with name changes. 
I presume you changed your ign recently. There isn't any way I know of to fix this.

**Comment by thecoolkogut4** [comment] 2016-04-28 22:22
As yuno said above me, if you change your name this will happen to you. You will get stuck in the guild. (changing your name back won't fix it). Just wait until they fix it. Nothing much you can do :/

**Comment by Trixter313** [comment] 2016-04-30 07:12
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-30 07:12 UTC
