### ISSUE TITLE
Issues with connecting to Wynncraft

### ISSUE THREAD

**Issue by CrazySmokerDude** [Wynncraft/Issues#4666] opened 2016-03-27 01:40 UTC
https://youtu.be/R-JecP5fBC0

Video shows it all.

What have I tried to fix the problem:

1. Reinstalled full game
2. Tried with diffrent versions to login
3. Tested another servers and they worked normal / tested my internet aswell
4. Tried reseting my internet router

**Comment by DarkDemonDragon** [comment] 2016-03-27 13:21
Wynncraft was probably being laggy. If you tried waiting a few minutes you'd be put into the game. Where do you live because you might just have really bad ping which we can't really do much about.

**Comment by CrazySmokerDude** [comment] 2016-03-27 17:08
I've been trying 5 hours :P *crying, lost night of farming gg*, however problem is fixed now... I have a question though, is Wynncraft an US server ?

**Comment by DarkDemonDragon** [comment] 2016-03-27 20:16
I'm not sure. The staff team is split between using American English and British English which is seen in the spelling of words in the lore of items.

**Comment by CrazySmokerDude** [comment] 2016-03-27 20:19
Ok I have another problem , maybe u can help me out to not open another thread. I can't open www.wynncraft.com , the error message is "Unexpected error" and when I manage to refresh it enough I get this: http://postimg.org/image/n20a5fvh3/ 
Also I tried connecting through android phone but same problem, and on PC I tried using diffrent browser... I can't get to wynncraft main page and wynncraft store, however forum and wiki are working fine.

**Comment by DarkDemonDragon** [comment] 2016-03-29 01:01
@CrazySmokerDude that would be a duplicate of #4228 If the original issue has been resolved please close this.

**Closed** 2016-03-29 01:06 UTC
