### ISSUE TITLE
Santas skin is missing on craftmas chaos.

### ISSUE THREAD

**Issue by siddo0sidddo** [Wynncraft/Issues#5029] opened 2016-05-20 01:44 UTC
Santas skin is just the default skin.

**Comment by Trixter313** [comment] 2016-05-23 00:20
Is the skin still broken for you? Also, what do you mean by the default skin? Steve or Alex? Or the colorful box skin? Thanks!

**Comment by Moe-Ronickah** [comment] 2016-05-23 02:17
Dupe of #4003 .  Please follow the instructions for finding issues on our front page.

**Closed by Moe-Ronickah** 2016-05-23 02:17 UTC
Labels: Duplicate
