### ISSUE TITLE
No Item Identifier?

### ISSUE THREAD

**Issue by Fiireburner** [Wynncraft/Issues#3988] opened 2016-02-05 19:24 UTC
Idk if the staff hasnt gotten to put him here yet but there isnt one in Pirate Town..
![2016-02-05_14 17 26](https://cloud.githubusercontent.com/assets/17088890/12856695/225a92f6-cc14-11e5-95b6-caa22149d51c.png)

and btw.. the reason why im here at lvl 28 was for the item identifier xD

**Comment by Trixter313** [comment] 2016-02-05 19:33
Duplicate of https://github.com/Wynncraft/Issues/issues/3272

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-05 19:33 UTC

**Comment by Fiireburner** [comment] 2016-02-08 23:34
oops i didnt know sry :C

**Comment by Trixter313** [comment] 2016-02-09 02:45
It's fine =) No big deal
