### ISSUE TITLE
Logged on another location?

### ISSUE THREAD

**Issue by ChunkerBunker** [Wynncraft/Issues#8054] opened 2017-05-02 23:44 UTC
I haven't given any of my new details to anyone yet I cant log onto my account I don't know it has been hacked into or what. Can a staff member check when I was last logged in last I was logged in was around 4 pm PST after that I haven't been able too.

**Comment by Trixter313** [comment] 2017-05-02 23:52
Other users are experiencing connection issues like this, so I wouldn't be too worried about your account being compromised but if you'd like, you can change your Minecraft account password. That won't fix your connection issue but it will help the security of your account.

Duplicate of https://github.com/Wynncraft/Issues/issues/8051

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2017-05-02 23:52 UTC
