### ISSUE TITLE
website not loading?

### ISSUE THREAD

**Issue by yeeaah** [Wynncraft/Issues#4228] opened 2016-02-23 01:46 UTC
The website and stuff hasn't been loading for a while. It looks like background dirt stuff. Please help. Thanks

**Comment by Odnod** [comment] 2016-02-23 01:51
they are up for me, could you post screenshots or give more detail about what is wrong?

**Comment by DarkDemonDragon** [comment] 2016-02-23 13:03
@yeeaah sometimes the site goes down temporarily either for maintenance or an update. Just check again in 10-15 mins and it should be up again. If the site works fine for you now, please close this issue. If not please post a screenshot of what is happening.

**Comment by yeeaah** [comment] 2016-02-23 20:43
still broken, has been like this for a week, image link - http://imgur.com/jDhgI6N

**Comment by Odnod** [comment] 2016-02-23 21:04
Are you sure you are just connecting to wynncraft.com , wynncraft.net , or wynncraft.org ?

**Comment by yeeaah** [comment] 2016-02-23 22:05
wynncraft.com

**Comment by DarkDemonDragon** [comment] 2016-02-24 04:11
Oh you meant the site, I thought you meant the forums. The site is actually pretty useless since stats are unavailable and the item guide is incomplete. All news and announcements can be found on the forums. You'd really only need the site if you need to purchase something, but I think there's a direct link for that.

**Comment by yeeaah** [comment] 2016-02-25 01:37
o okie closed for now

**Comment by DarkDemonDragon** [comment] 2016-03-05 16:42
Site works find for me. I think it might just be what browser people are using.

**Comment by Trixter313** [comment] 2016-03-05 16:57
What browser are you using @DarkDemonDragon ? I've tried Chrome and Edge and neither work for me. Every once in a while it will load but the website will be broken in some places and there's no news, teamspeak, tweets etc.

**Comment by DarkDemonDragon** [comment] 2016-03-05 17:50
Really? Just checking we're talking about Wynncraft.com right? I use Chrome and everything works, but stats which was confirmed by Tama to be broken.

**Comment by DarkDemonDragon** [comment] 2016-03-05 17:55
Weird tried it on my phone and Latest News was broken, but the site isn't compatible with my phone (I can only see the left side and can't scroll horizontally so I couldn't check if Tweets were working) so that could be the issue. I'll try again at home and record it to show it's working for me.

**Comment by Corneille198** [comment] 2016-03-29 20:15
Hello, I got the same Problem, I tried in on my Phone, iPhone and Laptop from different wifi connections. Also asked friends and they say they have the same issue.
There are two possible probrlems I can with Chrome.
Issue-1: http://imgur.com/RFLv3JW
Issue-2: http://imgur.com/u9ul8cj
I have Windows 10(Don't think that matters) and I tried it on Chrome, Microsoft Edge, Internet Explore, Firefox and Safari. All the same issue.

**Comment by Corneille198** [comment] 2016-03-30 11:18
Hello, I got the same Problem, I tried in on my Phone, iPhone and Laptop from different wifi connections. Also asked friends and they say they have the same issue.
There are two possible probrlems I can with Chrome.
Issue-1: http://imgur.com/RFLv3JW
Issue-2: http://imgur.com/u9ul8cj
I have Windows 10(Don't think that matters) and I tried it on Chrome, Microsoft Edge, Internet Explore, Firefox and Safari. All the same issue.

**Comment by CrazySmokerDude** [comment] 2016-03-31 22:38
I have the same problem like Corneille198 and DarkDemonDragon, the direct link also to purchase is still the same issue like the main website, and yes I wanna purcahse GC so someone should find a solution for this issue...

**Comment by Corneille198** [comment] 2016-04-01 04:43
The forums are just working fine for me, same for the map.

**Comment by DarkDemonDragon** [comment] 2016-04-01 12:16
@CrazySmokerDude it's difficult since some people like me can still access wynncraft.com and I'm using Chrome although on Windows 7. I can't really figure out what decides whether someone can view the site or not. People still buy bombs so obviously plenty of people have been using the site with no issues.

**Comment by Corneille198** [comment] 2016-04-01 13:06
@DarkDemonDragon Could it be the place where people are living?

**Comment by CrazySmokerDude** [comment] 2016-04-01 16:48
@DarkDemonDragon oki well, some mod gave me direct link to store and it worked, but u relise I tried from diffrent internet providers, diffrent laptops / computers / phones I tried at my family too, maybe it's because of Country then xD however fuck it, i dont care anymore, ty for answering anyway <3

**Comment by yeeaah** [comment] 2016-04-01 17:14
it works for me chrome windows 10 east coast usa

**Comment by Corneille198** [comment] 2016-04-01 21:50
I live in West Europe in the Netherlands, could that be it?

**Comment by DarkDemonDragon** [comment] 2016-04-01 22:27
I'm also East Coast USA

**Comment by CrazySmokerDude** [comment] 2016-04-06 19:58
Yes, it works for US people, but I am EU from Croatia.

**Comment by Corneille198** [comment] 2016-04-08 06:07
@CrazySmokerDude Seems like it's working for me now. and Stats are also working again.

**Comment by CrazySmokerDude** [comment] 2016-04-11 16:12
Yes it does, it works for me now too.

**Comment by Moe-Ronickah** [comment] 2016-05-05 11:00
Unbeknown to us, a new website team was working on the website, and may have been in the middle of testing the new site, without having all of the compatibility switches set.  I'm closing this issue.  If it comes back up, please open a NEW issue, because the website has been updated.

**Closed by Moe-Ronickah** 2016-05-05 11:00 UTC
Labels: Website
