### ISSUE TITLE
Dexterity problem

### ISSUE THREAD

**Issue by wietse2001** [Wynncraft/Issues#4040] opened 2016-02-08 12:10 UTC
I was doing the "An iron heart part II" quest when out of no where my armour went off and my dexterity level had become 0 and i had no skill points left. when I tried to put the armour back on it said this:
![18f4183f50ec0d1ca559fcffc1420f64](https://cloud.githubusercontent.com/assets/7292396/12885274/eb002fb6-ce64-11e5-98b9-49d04b1c8cb6.png)
these are my skills :
![92f736ca57bfacaf247c7c56843d9891](https://cloud.githubusercontent.com/assets/7292396/12885294/1eb3e410-ce65-11e5-9f21-2ff1d860905a.png)
I hope some one can help me.
bye

**Comment by DarkDemonDragon** [comment] 2016-02-08 15:42
See that 0? That's your dexterity. There was a bug where armor with a dexterity requirement didn't require it. So if an armor needed 10 Dex, but you have 0 you could still wear it because of the bug. That bug was fixed so now you need dexterity. Please close this as this is NOT a bug, but an intended feature.

**Closed** 2016-02-08 16:11 UTC
