### ISSUE TITLE
Can't Log Into Any Worlds 2 and Glitched BAD

### ISSUE THREAD

**Issue by builderJP** [Wynncraft/Issues#6136] opened 2016-09-14 01:58 UTC
I don't know how to unclose a conversation so that's why I'm making this. Here's the original article: https://github.com/Wynncraft/Issues/issues/6135#event-788477364. In a nutshell, I disconnected, and I can't log back on no matter what. I restarted, did everything, nothing worked. Someone told me to wait for 5 minutes it's normal. Waited for over 5 minutes, still "Loading terrain."  Then, I am writing this, and I join a world, but I'm in a blackish brownish void. I took a screenshot (included, and then everything starting going fast. I tried doing /hub, /class, and tried to /msg someone for help, but I couldn't do everything. The chat was spamming blank stuff, and every now and then alerts like "So and so's xp bomb expired" and "Server restarting in 10 minutes." In between each of them was blank spam. At one point my /class command came through and I tried picking my class, but the server restarted. I'm joining a world as I type. I'll try and keep updated.

The Screenshot:
![2016-09-13_18 51 17](https://cloud.githubusercontent.com/assets/10580377/18497539/f5eda52c-79e3-11e6-8a28-4b8783780635.png)

**Comment by builderJP** [comment] 2016-09-14 01:59
Also, my aim kept on snapping back to this position.

**Comment by Markles123** [comment] 2016-09-14 02:16
Yea same, except mine doesn't even load at all. It just says Loading terrain infinitely. But, i joined the nether server and it worked sorta. The bracelet was broken and unidentified and glitchy, and anything i did at all was super laggy and buggy as heck. Teleport didn't take effect till 2 minutes afterwards.

**Comment by builderJP** [comment] 2016-09-14 02:17
Is this happening to everyone?

**Comment by Markles123** [comment] 2016-09-14 02:17
Update, I managed to log into a server. Except about ten minutes of music was collapsed into a single 10 second stretch with nothing rendering besides what was in my inventory. I was flying in my screen.

**Comment by builderJP** [comment] 2016-09-14 02:18
Ikr Markles123, everything goes so fast. Wonder what's happening...

**Comment by Markles123** [comment] 2016-09-14 02:19
I have no idea. I wouldn't mind waiting if it was a bug fix perhaps, but what really saddens me is that i'm going to lose about 20 day's worth of consecutive Daily Rewards Chest's :')

**Comment by builderJP** [comment] 2016-09-14 02:20
IKR! ;( Did you read my original article? 99% XP! >:(

**Comment by fizzle54** [comment] 2016-09-14 02:23
I am having the exact same problem. I have not been able to log in to the Wynncraft servers and I am stuck in the "Loading Terrain" stage indefinitely. I'm just glad to know that I'm not alone with this issue.

**Comment by Markles123** [comment] 2016-09-14 02:25
This is so weird. Hope the issue's only temporary though. I can login to
the hub and no one seems to have issues but me. So... Strange to say the
least.

**Comment by builderJP** [comment] 2016-09-14 02:26
Is it just us 3?

**Comment by Markles123** [comment] 2016-09-14 02:28
That would be weird if it was

**Comment by fizzle54** [comment] 2016-09-14 02:28
I also can only log into the lobby. I'll post a screenshot and tell me if this is happening to you Markles123.

![issue1](https://cloud.githubusercontent.com/assets/22185475/18498047/6fadcd48-7a01-11e6-9e24-db390095f931.PNG)

**Comment by fizzle54** [comment] 2016-09-14 02:29
I'm in Windows 10 and using 1.10.2
Are you both in 1.10.2?

**Comment by builderJP** [comment] 2016-09-14 02:30
1.10.2 On Mac. MA
![2016-09-13_19 29 10](https://cloud.githubusercontent.com/assets/10580377/18498076/858d8e32-79e8-11e6-8319-7d5d8fad7671.png)
de it in!

**Comment by builderJP** [comment] 2016-09-14 02:31
Don't know how. Just waited.

**Comment by Markles123** [comment] 2016-09-14 02:32
Using my sisters computer, it's a very updated Mac, and i got in, but I
spawned INSIDE the deltas bank, as in, above the area where you cash in
your emeralds. Its inside the building's infrastructure. This is so strange

**Comment by fizzle54** [comment] 2016-09-14 02:32
I've had no success even reverting back to version 1.10.1

I really don't know what's going on. I still have the Loading Terrain screen and the only way to get out of it is to close Minecraft. Hopefully it will be fixed for me soon.

**Comment by Markles123** [comment] 2016-09-14 02:36
Try just waiting. Go on YouTube and watch videos for the time being.

**Comment by fizzle54** [comment] 2016-09-14 02:44
Well, it took just under 3 and a half minutes, but I'm in finally.

**Comment by Markles123** [comment] 2016-09-14 02:54
Awesome xD

**Comment by Markles123** [comment] 2016-09-14 02:54
Its not much better online, it's laggy as HELL

**Comment by ColinRioux** [comment] 2016-09-14 02:58
In the future, please try being patient and see if the issue resolves itself. To no prevail, you're welcome to post an issue here, but anything connection related will generally be on your end unless the server itself is down / being DDoSed. 

@Moe-Ronickah please close.

**Comment by Markles123** [comment] 2016-09-14 03:08
But the wifi and connect was stable on our end. If it was on our end, we
wouldn't ve complaining we would be restarting the router or checking for
internet connection issues and solutions online. That's why we talked about
it here on GitHub. Even now for me it's super laggy, but my home situation
and connect hasnt changed in the slightest for months. So it's not me, that
I know for sure.

**Comment by ColinRioux** [comment] 2016-09-14 03:27
Except, I have been and am not having any connection issues. And haven't been for the last week or two. 

You, as you claim, may be exploring all options, but some people don't explore all options before posting an issue. Also you may not have changed your connection, but your internet service provider could have as well. Have you tried using Free Public Wifi (or another wifi/ethernet connection) and logging in? That said, there could be many things wrong with the whole situation. Until there are more than 3 people having this issue, then we don't really know which end it is on. 

Either way, let's just drop it.

**Comment by Trixter313** [comment] 2016-09-14 03:41
We recommend using 1.8.9 to play, just fyi. It seems the issue is fixed now though. =)

**Closed by Trixter313** 2016-09-14 03:41 UTC

**Comment by builderJP** [comment] 2016-09-14 03:45
Are you serious? My internet is fine. Don't go blaming people about how they didn't read the posting rules. Be nice about it. Don't be so snarky. (Not you Trixter313, just ColinRioux.)

**Comment by builderJP** [comment] 2016-09-14 03:46
Are you serious? My internet is fine. Don't go blaming people about how they didn't read the posting rules. Be nice about it. Don't be so snarky. (Not you Trixter313, just ColinRioux.)
