### ISSUE TITLE
Item Model Bug

### ISSUE THREAD

**Issue by TheBlobMiner** [Wynncraft/Issues#5278] opened 2016-06-21 22:06 UTC
When you have a certain model in your hand (weapon), and when you right click a block with it, it says in red, "You don't have permission to edit this area" or something like that.

you can talk to Quest NPC, but you can't press buttons and open loot chests while holding that model.

The model I'm currently on is the model for the weapon Infinity and Olux's Prized Bow.

**Comment by GlitchDoesMC** [comment] 2016-06-21 22:38
The game thinks you are trying to place a block. To solve this issue, just right click with your soul point or empty hand to press buttons/loot chests.

**Comment by Trixter313** [comment] 2016-06-21 23:06
Duplicate of https://github.com/Wynncraft/Issues/issues/3902

**Closed by Trixter313** 2016-06-21 23:06 UTC
