### ISSUE TITLE
bow missing textures

### ISSUE THREAD

**Issue by kdbarnes** [Wynncraft/Issues#6687] opened 2016-11-14 05:40 UTC
bows that are a retextured spruce slab are missing their textures such as jungle artifact, relic bow, or olux's prized bow
![2016-11-13_21 39 23](https://cloud.githubusercontent.com/assets/23445288/20254476/da006d78-a9e9-11e6-8227-99798a960656.png)

**Comment by Rellia** [comment] 2016-11-14 15:06
And infinity, Meteor Arch... yeah there are plenty but this isn't really a bug. There are a lot of weapons...

**Comment by kedamono** [comment] 2016-11-14 19:28
I'm running into the same problem as well. One of my bows shows up as a slab.

**Comment by Rellia** [comment] 2016-11-14 20:19
Yes. There are some bows that are spruce slabs. They still function perfectly fine, the only issue is the spam of: "You do not have permissions in this area" when you right click to fire too close to a block. If you really can't handle this, buy a bow skin from the store

**Comment by ColinRioux** [comment] 2016-11-14 22:44
Hi @Rellia this is considered a bug because it's regarding the resource pack, and it's not functioning properly. 

@kdbarnes I am leaving this open as a result, but please be patient, and aware that it is low on the developer's agendas.

**Comment by Rellia** [comment] 2016-11-15 14:25
Oh okay then. Yeah a lot of bows

**Comment by Moe-Ronickah** [comment] 2016-11-17 02:58
duplicate of #4548

**Closed by Moe-Ronickah** 2016-11-17 02:58 UTC
Labels: Duplicate, Resource Pack
