### ISSUE TITLE
Tower of Ascension xp Bug

### ISSUE THREAD

**Issue by Leosuper99** [Wynncraft/Issues#6330] opened 2016-10-04 16:45 UTC
Hey, i completed the Tower of Ascension and got only 1 lvl,.
My question is : When will the bug fixxed,and can I get the xp again?

**Comment by Leosuper99** [comment] 2016-10-04 16:48
https://gyazo.com/f7e643fbe3a44283df1106b7f162eb7e

**Comment by TeenageCat** [comment] 2016-10-04 22:48
What's the problem?

**Comment by Leosuper99** [comment] 2016-10-05 08:19
I got not the right experience from the tower of ascension

**Comment by Moe-Ronickah** [comment] 2016-10-09 18:07
Duplicate of #6312

**Closed by Moe-Ronickah** 2016-10-09 18:07 UTC
Labels: Duplicate
