### ISSUE TITLE
Class Has No Permissions

### ISSUE THREAD

**Issue by GOden02** [Wynncraft/Issues#4724] opened 2016-04-01 17:58 UTC
Yeah, so I have a problem. When I try to right click the ground, or I try to open a loot chest, it says "You have no permissions for this area.". It's really quite annoying, because I use loot chests for a big source of my emeralds, aside from grinding. My class currently is a level 61 Archer, and the weapon I use is Infinity, if that matters at all.

**Comment by TrashcanMan** [comment] 2016-04-01 18:28
This has been around for a while, you can open loot chests with an empty hand though. The problem is that all the weapons are retextured blocks, so when you right-click the game thinks you're trying to place it.

**Comment by Trixter313** [comment] 2016-04-01 18:30
Duplicate of https://github.com/Wynncraft/Issues/issues/3902

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-01 18:30 UTC

**Comment by GOden02** [comment] 2016-04-01 19:06
Uh, I can't click buttons either, so I should use my hand for that as well?

**Comment by TrashcanMan** [comment] 2016-04-02 23:19
Yeah, you can't use your weapon for anything at all really. Just use an empty hand or a non-weapon item, eg emeralds or junk items.
