### ISSUE TITLE
The Black Road (WC3)

### ISSUE THREAD

**Issue by CheesepuffMC** [Wynncraft/Issues#6946] opened 2016-12-20 21:52 UTC
Whilst on my way to Nemract, I encountered a long path of obsidian going out into the ocean, I followed the path, wondering if it went anywhere, but after a good 10 minutes of walking, i ended up at just a dead end in the middle of the ocean. I think it may have been a hacker trying to go to gavel without doing the quests/leveling up, but it could be something else. I also believe it is specific to WC3, but if it isnt, i will be stranded in the ocean.

![2016-12-20_16 46 48](https://cloud.githubusercontent.com/assets/19506185/21369391/babb680c-c6d4-11e6-828e-9e974263f714.png)
![2016-12-20_16 43 40](https://cloud.githubusercontent.com/assets/19506185/21369398/be5f1486-c6d4-11e6-9b27-1575c168c482.png)

**Comment by CheesepuffMC** [comment] 2016-12-20 22:20
Update, its on multiple servers
![2016-12-20_17 19 22](https://cloud.githubusercontent.com/assets/19506185/21370201/971863ba-c6d8-11e6-85d1-9e2631d7a5ab.png)

**Comment by Trixter313** [comment] 2016-12-20 22:29
Duplicate of https://github.com/Wynncraft/Issues/issues/6936

**Closed by Trixter313** 2016-12-20 22:29 UTC
