### ISSUE TITLE
Incorrect Elemental Defense Calculations

### ISSUE THREAD

**Issue by DigitoriiX** [Wynncraft/Issues#5529] opened 2016-07-20 13:58 UTC
Armor that affects Elemental Defense in any way seems to be completely inaccurate. Many of the defense totals are far lower than they should be, while occasionally they are higher. Some totals get reduced even with no defense-reducing equipment of that element.

[Incorrect Elemental Defense Total Examples](http://i.imgur.com/bOYjd2y.png)

With all of my current gear, the difference between the expected results and in-game results are massive:
Fire Defense: +40 --> -30
Air Defense: -45 --> -20
Earth Defense: -20 --> -40
Thunder Defense: +25 --> +25
Water Defense: -30 --> -70

Thunder Defense seems to be the only element that is properly calculated across my testing of various items (and combinations).

**Comment by YunoFGasai** [comment] 2016-07-20 19:41
the compass is incorrect when it comes to a lot of things, I advise you to do the calculations by yourself.

**Comment by Moe-Ronickah** [comment] 2016-07-20 21:00
Duplicate of #3179

**Closed by Moe-Ronickah** 2016-07-20 21:00 UTC
Labels: Duplicate
