### ISSUE TITLE
2 Same Member in a guild (Photo)

### ISSUE THREAD

**Issue by llamabrine** [Wynncraft/Issues#5444] opened 2016-07-10 08:05 UTC
I know this glitch had been reported before, but it seems to get worse.
This bug occurs if a guild member changed their minecraft username.
There will be two same people in 1 guild.
The problem is the member will fill two member slots.
I tried to leave the guild, but the bug messed up the system and not letting me leave the guild.
I saw other people reporting this bug, claiming this bug could not be fixed in any way possible.
As I mentioned, **the bug is getting worse** cause my guild (Stormers of Wynn) have 3 people already changed their name (including me) and all of them have this bug! (please view the photo)
![guild_bug](https://cloud.githubusercontent.com/assets/20379080/16712347/593aa536-46b7-11e6-99c3-56f6235f3757.jpeg)
Please fix this bug ASAP, thank you.

p.s. the guild owner is my friend, and he seems to be very mad at me right now (concurring two member space, not able to add new member). I do not want to loose one of my best friends, so please fix this bug. Thank you.

**Comment by YunoFGasai** [comment] 2016-07-10 09:23
duplicate of #3665 please follow the issue on the original thread

**Closed** 2016-07-10 21:06 UTC
Labels: Duplicate
