### ISSUE TITLE
Potion Merchant On Black Road Basement

### ISSUE THREAD

**Issue by sammyvsparks** [Wynncraft/Issues#2125] opened 2015-07-21 02:55 UTC
The basement for the Potion Merchant's trap (as far as I can tell) requires you to /kill yourself to escape.

![image](https://cloud.githubusercontent.com/assets/12182390/8792183/1310ccd6-2f19-11e5-8f12-84256354bb65.png)

Nothing Opens Inside the exit area, nor the way you entered

**Comment by TrashcanMan** [comment] 2015-07-21 04:04
This one is a known issue, it should be fixed the next time the map is updated. For now, just stay away from that area.

**Comment by Trixter313** [comment] 2015-07-21 11:30
Duplicate of https://github.com/Wynncraft/Issues/issues/2077
We recommend closing the duplicate and following the original to stay up to date on the issue. Thanks!

**Closed** 2015-08-17 07:09 UTC
