### ISSUE TITLE
API isn't working well

### ISSUE THREAD

**Issue by LookPvP** [Wynncraft/Issues#7552] opened 2017-03-19 00:04 UTC
Recently a player reported an issue about the wynncraft map on reddit so I went to investigate what's happenning.
Before I start explaining I saw an open issue by 0x0000null, it kinda explains what's going on.
So, basically the 250 requests per IP are also affecting the wynncraft website(map, leaderboards, stats, etc), which shouldn't be happenning. If the api is really limiting requests up to 2 per ip, that's bad.
The error output on map.wynncraft.com is `Failed to load resource https://api.wynncraft.com/public_api.php?action=mapLocations: the server responded with a status of 429 ()` which basically means 'Too many requests'.

EDIT: This is console log over wynncraft.com/stats
`Initialising core JavaScript...`

`Tooltips fired...`

`Bootstrap 3 modal hacks done...`

`Stats core loaded.`

`https://api.wynncraft.com/public_api.php?action=statsLeaderboard&type=guild&timeframe=alltime Failed to load resource: the server responded with a status of 429 ()`

`Setup SWF for IP copy button`

`https://api.wynncraft.com/public_api.php?action=statsSearch&search=Look Failed to load resource: the server responded with a status of 429 ()`

`https://api.wynncraft.com/public_api.php?action=statsSearch&search=LookPvP Failed to load resource: the server responded with a status of 429 ()`

**Comment by 0x0000null** [comment] 2017-03-19 04:36
Duplicate of #7277

**Closed** 2017-03-19 11:19 UTC
