### ISSUE TITLE
Kelight's ToothBrush Texture Bug

### ISSUE THREAD

**Issue by Trempaille** [Wynncraft/Issues#5209] opened 2016-06-12 09:53 UTC
I identified my Staff and i found Kelight's ToothBrush, but the texture is a stone brick slab ...
Help please

**Comment by Moe-Ronickah** [comment] 2016-06-12 13:01
Duplicate of #4548 .  Please follow and comment, if necessary, on the issue there.

**Closed by Moe-Ronickah** 2016-06-12 13:01 UTC
