### ISSUE TITLE
Quest: A Marauder's Dues - Not Dropping Norsten's Gem

### ISSUE THREAD

**Issue by Skillett** [Wynncraft/Issues#4367] opened 2016-02-29 23:11 UTC
I searched for a duplicate issue and the only one I found was redirected to the item drop bug that (i thought) was fixed. 

After jumping off the wizard's fire tower and into the water, I was dropped into a cave and the area the arrows are pointing to does NOT drop the Gem needed for the quest. 

[http://i.imgur.com/EOTf0ep.png](url)

We activated all the quest markers on the hill and talked to Volmer. 

My questbook says " Return the gem from the chasm and return it to norstem"

**Comment by Zellnotronus** [comment] 2016-03-01 01:38
I get the same problem, Skillett. I even tried switching servers and that didn't work.

**Comment by kmo900** [comment] 2016-03-02 02:27
this is happening with several drops spider cave suspended flowers diamond shards aparently also have this problem.

**Comment by Odnod** [comment] 2016-03-02 06:51
Duplicate of #4236, please close this issue and put any additional comments on the original. Thanks!

Please know that this bug is very well known and is being worked on.

**Closed** 2016-03-02 07:51 UTC
Labels: Duplicate
