### ISSUE TITLE
Texture Bug

### ISSUE THREAD

**Issue by Mar3kCz** [Wynncraft/Issues#6566] opened 2016-11-03 21:41 UTC
When i join to WynnCraft, I'm scared of lost my Relic bow. Now i see spruce slab, what is this? My Relic bow ._.  
![2016-11-03_22 37 22](https://cloud.githubusercontent.com/assets/22253258/19986487/3e770a76-a217-11e6-8ea6-b300e5952999.png)

**Comment by thecoolkogut4** [comment] 2016-11-04 00:59
join version 1.9 to fix some textures, to break horses, and to break others textures. OR you can stay in 1.8 with some broken textures. which that is your decision to make

**Comment by LordHelmchen98** [comment] 2016-11-04 09:32
Open your .minecraft folder, then open the server resourcepack folder and try if you can fix it by deleting the 'legacy' file.

**Comment by Trixter313** [comment] 2016-11-05 19:04
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

**Closed by Trixter313** 2016-11-05 19:04 UTC
