### ISSUE TITLE
Ice snakes spell not freezing

### ISSUE THREAD

**Issue by Sandertv** [Wynncraft/Issues#3824] opened 2016-01-23 15:44 UTC
The ice snake spell is not working the way it is supposed too... The spell just deals small damage, but freezes nor slows.

**Comment by Dar-krusos** [comment] 2016-01-23 16:53
Yeah, I've noticed this, but I'm not sure if it's intentional or not.

**Comment by Trixter313** [comment] 2016-01-23 21:55
Duplicate of https://github.com/Wynncraft/Issues/issues/3241

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-23 21:55 UTC
