### ISSUE TITLE
Ahmsord Not Registering As Town

### ISSUE THREAD

**Issue by TheSnowGolem** [Wynncraft/Issues#4841] opened 2016-04-17 04:52 UTC
I saw a duplicate issue of this, but it was closed without a solution.

I am a level 29 Archer who made it to Ahmsord a few weeks ago, I never got the "You are now entering" message and when I died (I was threeish blocks away from Ahmsord when I did so) I spawned in the city closest to Ahmsord, but not in it. I have since returned to Ahmsord, but I still have no confirmation and when I try to use scrolls to it, I get the "You've never been in this town" message. Help?
![screen shot 2016-04-16 at 9 51 14 pm](https://cloud.githubusercontent.com/assets/18509358/14585122/69c02fca-041d-11e6-9fe7-4da644180872.png)

**Comment by Yoavronen** [comment] 2016-04-17 06:17
I have been there and got the welcoming message, I think the area the message plays in is a bit off. try coming from Kendon Beda to Ahmsor. that's the path I took and I got the message.

**Comment by Trixter313** [comment] 2016-04-17 13:16
Let us know if Yoavronen's suggestion helps. Thanks!

**Comment by Yoavronen** [comment] 2016-04-17 15:44
I just checked it myself in game, the Kendon Beda - Ahmsord route gives you the welcome to Ahmsord message. 
gonna check the other gates and main town square.

**Comment by Yoavronen** [comment] 2016-04-17 15:50
according to your screenshot you are in the item identifier room, that room is 100% inside of the Ahmsord territory. @Trixter313 my advice wont help him.
@TheSnowGolem  try relogging or running around the town.
if that doesn't work try to go to Kendon Beda, check if you get a welcome message there.

**Comment by YunoFGasai** [comment] 2016-05-04 17:27
I cant seem to recreate this issue, @TheSnowGolem can you check if you're still not getting a welcome message?
I have no idea what's going on there, you are clearly in Ahmsord territory and it doesn't recognize it, either it was just a server that glitched or the issue is specific to you.
I'll try to find him in game and ask him if the issue is still happening.

**Comment by YunoFGasai** [comment] 2016-05-08 14:02
When I asked around in game more people said that the ahmsord scrolls have not worked for them.
Because there is nothing to do there most people ignore it and throw the scroll.
Need to check if it is still happening.

**Comment by YunoFGasai** [comment] 2016-05-17 12:35
just checked this in game, while being in Ahmsord the chat displays the "you are already in that town..." message which is what probably happened to you.
when outside of Ahmsord territory it teleports me to the spawn point and removes one soulpoint.
I guess we can close this issue now.

**Closed** 2016-05-22 23:23 UTC
Labels: World
