### ISSUE TITLE
Bug Concerning Name-Changes in Relation to Guilds

### ISSUE THREAD

**Issue by Submonsterine** [Wynncraft/Issues#3908] opened 2016-01-30 01:01 UTC
Hello. One of my guild members, OryxMC, recently changed his minecraft username to Zelefant.

Today, I logged on and had a little conversation with him over /g. He claims that the messages are being sent to him twice. Taking a look at the guild list, it appeared that he was being shown twice on the guild menu. I assumed that this was a result of his name-change, keeping his original OryxMC account but changing the name, then keeping his new name as well.

![](http://i.imgur.com/7ZyRLIr.png)
![](http://i.imgur.com/qis9jL4.png)

To try and solve this, I tried to kick his original account, OryxMC, but he "wasn't a member of the guild". Oryx suggested for me to kick his current account and re-invite him into the guild. This dialogue summarizes what occurred:

![](http://i.imgur.com/4POhiQm.png)

Later, he tried to leave the guild on his own, and it ate his soul points, yet he was still in the guild. 

Steps to Replication:

1. Be in a guild.
2. Change name.
3. Attempt to leave guild.
4. Look in guild menu and ask a fellow guild member to speak.

**Comment by TrashcanMan** [comment] 2016-01-30 01:38
Yeah, name changes are known to cause many problems with guilds, a fix should be out "Soon".

**Comment by Trixter313** [comment] 2016-02-20 21:01
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-20 21:01 UTC
Labels: Game Mechanics
