### ISSUE TITLE
Wasted Double XP!!! Stuck in Silverfish Dungeon Glitch

### ISSUE THREAD

**Issue by duncster2000** [Wynncraft/Issues#5325] opened 2016-06-27 21:14 UTC
My friends and I wanted to do the silverfish to farm XP. I bought a Double XP and we headed into the dungeon on world 19. First problem was the puzzle where we had to put items on the 3 pressure plates did not open the door and was clearly glitched. After a while it somewhat opened, enough for us to get through, but it was still glitched... Then at the end of the bridge where you drop down into the silverfish room, the door to drop down into the silverfish room would not open. So 20 mins of double XP was wasted. I was wondering if you could fix this and if I could get another double XP. I have a Youtube video of the entire incident that I have linked. 

My IGN is Duncster2000

Youtube: https://www.youtube.com/watch?v=zMo-Gz9xvkU&feature=youtu.be

**Comment by Moe-Ronickah** [comment] 2016-06-28 03:45
Duplicate of #5101

**Closed** 2016-06-28 03:45 UTC
Labels: Duplicate
