### ISSUE TITLE
The Code into Mummy´s Tomb isn´t working

### ISSUE THREAD

**Issue by Huhn360** [Wynncraft/Issues#1712] opened 2015-03-16 17:40 UTC
I entered the Code: 63814275 into the tomb but the door doesn´t open. I´m sure that this must be the right code! An other player said the same so it must be a glitch.

**Comment by Trixter313** [comment] 2015-03-16 19:29
Duplicate of https://github.com/Wynncraft/Issues/issues/1705
For future reference, if you have a bug to report, check to make sure that it hasn't already been reported and if it has, just post on that same thread or watch that thread. Another post about it is unnecessary and causes clutter. Thanks!

**Closed** 2015-03-21 18:24 UTC
Labels: duplicate
