### ISSUE TITLE
Lava Cow in Animal Dungeon.

### ISSUE THREAD

**Issue by LazyHoovy** [Wynncraft/Issues#5575] opened 2016-07-24 20:18 UTC
Hello, Im LazyHoovy. Theres been a bug in the Animal dungeon while fighting the Lava Cow ^^. Basically you can push the Boss out of the arena which makes it almost impossible to hit. Getting it back in isnt easy too. Only the Warrior can push it into lava with Uppercut to get it back in. Thanks for reading this and have a nice day ! ^^

**Comment by Moe-Ronickah** [comment] 2016-07-25 13:36
If you had searched for "animal dungeon boss", you would have found 40 issues.  One is still open.

Duplicate of #3191 .  Please follow this issue there, if you want to.

**Closed by Moe-Ronickah** 2016-07-25 13:36 UTC
Labels: Duplicate
