### ISSUE TITLE
Changed my name, can't leave my guild

### ISSUE THREAD

**Issue by Chrocomoker** [Wynncraft/Issues#4930] opened 2016-05-01 14:03 UTC
Why can't I leave my guild?? Can you kick me from the console? please try to do something!! I am stucked at a non-online ppls guild. thanks...

**Comment by NuKl3aRz** [comment] 2016-05-01 14:14
I have the same problem

**Comment by Trixter313** [comment] 2016-05-01 14:41
Is your Minecraft username also Chrocomoker?

**Comment by Syndicatez** [comment] 2016-05-01 14:55
I have the same problem :/
Minecraft username : Syndicate_z

**Comment by thecoolkogut4** [comment] 2016-05-02 18:48
if you change your mc name, you get stuck in your guild. i dont think there is anything you can do at the moment besides wait it out.

**Comment by DarkDemonDragon** [comment] 2016-05-03 12:36
"wait it out" @thecoolkogut4 people have literally been waiting months to years.

**Comment by thecoolkogut4** [comment] 2016-05-03 12:48
I've also been waiting for that long too. There's hundreds of people in the same spot as you. The devs need to fix it and for them to fix it we just need to wait for them

**Comment by ChocolatyBear** [comment] 2016-05-05 00:53
I've been stuck in my guild for literally 6 months. It's annoying but I understand the coding is difficult for the server. Keep working on it though please :P Thanks!

**Comment by thecoolkogut4** [comment] 2016-05-05 01:14
ive had people stuck in my guild, for who knows how long. its annoying for you and its also annoying for the owner.

**Comment by ChocolatyBear** [comment] 2016-05-09 04:13
I have the same problem with my guild. The guild name is Gystiriem. My name is Chocolaty_Bear. Can someone please kick me??

**Comment by Deaftig** [comment] 2016-05-12 13:59
I've got the same problem, i've got an user in my guild 2 times, cant kick him

**Comment by Vydros** [comment] 2016-05-13 03:13
I cant leave my guild too :'(

**Comment by Moe-Ronickah** [comment] 2016-05-27 02:02
Duplicate of #3665 .  Please follow the discussion in that issue.

**Closed by Moe-Ronickah** 2016-05-27 02:02 UTC
Labels: Duplicate, Guilds

**Comment by Moe-Ronickah** [comment] 2016-05-27 02:07
You opened issue #4912 concerning this very same thing.  Please, do not create duplicate issues.
