### ISSUE TITLE
Class Duplicating... Kinda

### ISSUE THREAD

**Issue by tolin99** [Wynncraft/Issues#5490] opened 2016-07-15 14:47 UTC
I have a level 96 archer and a level 41 hunter. I was in Rodoroc with the level 96, and switched classes to the level 41 hunter, which I kept as a bank class in the gavel "transition room". But the hunter had been teleported to Rodoroc, with all of the items that it had held deleted and all of the items from the archer duplicating to it. This didn't happen when I switched to any other classes, and it did not affect the 96 archer.

**Comment by sammyvsparks** [comment] 2016-07-15 16:05
Duplicate of https://github.com/Wynncraft/Issues/issues/4790 | Try to look there for more information on the issue.

**Closed** 2016-07-15 17:12 UTC
