### ISSUE TITLE
Excavation site d; I don't have a yellow or pink shard

### ISSUE THREAD

**Issue by hockeyloverkid** [Wynncraft/Issues#6962] opened 2016-12-21 20:12 UTC
please help me staff I don't have a pink or yellow shard in my inv or my echest. It is very annoying because I can't do excavation site d

**Comment by hockeyloverkid** [comment] 2016-12-21 20:14
Btw /fixquests does not work

**Comment by thecoolkogut4** [comment] 2016-12-21 20:14
if you did the wynn site that gives the color of shards and you previously had them type /fixquests and you should get them back

**Comment by thecoolkogut4** [comment] 2016-12-21 20:16
you posted at the same time as me, did you do wynn site a b and c? or your just starting at d

**Comment by hockeyloverkid** [comment] 2016-12-21 20:16
I don't , can u just give me the shards

**Comment by thecoolkogut4** [comment] 2016-12-21 20:17
i dont? do you mean you didint do the quests?

**Comment by hockeyloverkid** [comment] 2016-12-21 20:18
I have the shard from c but not from a and b but I did a b and c

**Comment by hockeyloverkid** [comment] 2016-12-21 20:19
I did all of them up to c but I only have the red shard

**Comment by hockeyloverkid** [comment] 2016-12-21 20:19
I did do a b and c

**Comment by thecoolkogut4** [comment] 2016-12-21 20:20
if /fixquests wont work, and if you dont have the shards on another class then you just need to wait for them to fix the command as it does not work for everyone every time.

**Comment by hockeyloverkid** [comment] 2016-12-21 20:44
![img_0587](https://cloud.githubusercontent.com/assets/24689643/21405509/4e15e392-c794-11e6-838b-0c55783e5d8b.JPG)

**Comment by hockeyloverkid** [comment] 2016-12-21 20:44
![img_0588](https://cloud.githubusercontent.com/assets/24689643/21405524/606f00c8-c794-11e6-883a-9d5f9c9f3758.JPG)

**Comment by LordHelmchen98** [comment] 2016-12-21 20:56
Duplicate of #6830

**Closed** 2016-12-22 16:15 UTC
