### ISSUE TITLE
WynnExcavation C Red Crystal

### ISSUE THREAD

**Issue by ZeBaconator** [Wynncraft/Issues#4408] opened 2016-03-03 02:47 UTC
I've been into the cave and out but the red crystal within the volcano that spawns on the ground prior to the exit is not spawning. I've tried visiting multiple servers but to no avail. There's no way to finish the quest without being able to grab the nonexistent red crystal, so that would be nice. Thanks!

**Comment by Odnod** [comment] 2016-03-03 03:06
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-03 21:34 UTC
