### ISSUE TITLE
Lost a near max slider

### ISSUE THREAD

**Issue by Huntsman25w** [Wynncraft/Issues#7472] opened 2017-03-02 21:11 UTC
Hello, so today on Wynncraft my friend lost his slider do to swapping classes. He swapped back and it was gone, Yes he could just go get another, but he had one that was better then almost any out there by far. And i have proof it is real and he did infect lose it.

he tried everything we could think of to get it to re-spawn in his inventory but nothing worked.
His name is JDiggity22, here is the picture proof that it is his.
http://imgur.com/4iBAkqc

Please, if there is any way he can get it back it would be amazing.

**Comment by JD1ggity22** [comment] 2017-03-03 02:35
Hello. If their is any way this could be fixed it would mean the world to me. If you need anything from me just ask. Thanks!

**Comment by ColinRioux** [comment] 2017-03-03 03:29
Hi, Wynncraft enforces a strict no-refund policy. What this means is that you won't be getting your item back from us. If you want a replacement, you'll have to find another either from players or loot chests/grinding.

The policy may seem unfair, but this is how we keep the game genuine. There are many issues with giving people back items, and it's very abusable. That's why this policy is put in place. It does sound unfair, but it actually maintains fairness among all players.

In terms of swapping classes, I'd be more careful next time- try not to have a full inventory and don't press q while in the class menu (or promptly after typing /class) 

Also your photographic evidence is confusing. Did you pick up his item? Is that an old picture? Is that the new item? Or is that a picture of his inventory so he can try and receive a duplicate of the item.

**Closed by ColinRioux** 2017-03-03 03:29 UTC
