### ISSUE TITLE
ToA

### ISSUE THREAD

**Issue by LavaWarriorBoy** [Wynncraft/Issues#1854] opened 2015-05-01 06:23 UTC
Help! when i go behind tho Floor Master, it will not teleport me, i gived the Floor Master 10 Items and it's says You May Proceed... But when i go behind the floor master it doesn't teleport me to the next Lv It's Floor 1 Level 1, The Enemy is Winter Ram (Sheep) Lv 41

**Comment by Trixter313** [comment] 2015-05-01 10:42
Duplicate of https://github.com/Wynncraft/Issues/issues/1774

**Closed** 2015-05-19 19:00 UTC
