### ISSUE TITLE
Can't Identify Relic Shears

### ISSUE THREAD

**Issue by gizmosarousrex21** [Wynncraft/Issues#2123] opened 2015-07-21 01:00 UTC
I am gizmosarousrex21 lvl 44 and while trying to identify the Relic Shears i got a notice saying i can't because of the fact it is not unique or better (but its legendary)...
![2015-07-20_19 53 54](https://cloud.githubusercontent.com/assets/13426669/8790968/f1c8cf00-2f19-11e5-91b9-25b2c30b7307.png)

**Comment by Trixter313** [comment] 2015-07-21 01:03
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

We recommend closing the duplicate and following the original to say up to date on the issue. Thanks! =)

**Closed** 2015-07-24 14:19 UTC
