### ISSUE TITLE
ARMOR NOT WORKING!

### ISSUE THREAD

**Issue by Hayamaka** [Wynncraft/Issues#2627] opened 2015-12-12 16:59 UTC
y isnt my armor working. i always look jealously at other peoples armor wishing one day i too can shine in glistening armor. y isnt me armor working?

**Comment by Krallorddark** [comment] 2015-12-13 10:24
What is the issu? Is it not protecting you or not Identifying etc.?

**Comment by Hayamaka** [comment] 2015-12-14 01:05
it is not appearing on my skin @Krallorddark

**Comment by DarkDemonDragon** [comment] 2015-12-15 13:19
Check your character info on your compass. It will show whether your armor is providing any defense or ID boosts. Sometimes due to skin lag armor will just not load but most of the time it still works in terms or defense and stats. Please close this if your issue was resolved.

**Comment by bretonhoover** [comment] 2015-12-15 14:22
pause menu, options, skin customization, turn everything on. please close this as it is not a bug.

**Closed** 2015-12-15 17:40 UTC
