### ISSUE TITLE
Wrong describtion on quest

### ISSUE THREAD

**Issue by PhilipJohnsen** [Wynncraft/Issues#4762] opened 2016-04-06 13:53 UTC
"No one may enter aldorei without speaking to Elrund first, he is at the eastern gate." Which isn't true, he is at the western gate, this confused me for a good 10 minutes and then i looked at coords for him which were true

This is just a minor thing but would smooth the experience with aldorei's secret part 1

Thanks already

**Comment by Odnod** [comment] 2016-04-06 15:07
Duplicate of #3280, thanks for the report, but it has already been reported. please close this thread and direct any additional comments to the original so as to not clog up the github.

**Closed** 2016-04-07 02:01 UTC
