### ISSUE TITLE
Potential bug on halfmoon

### ISSUE THREAD

**Issue by Ribcage52** [Wynncraft/Issues#6095] opened 2016-09-10 13:40 UTC
im not to familiar with the island so im not sure if this is a bug or not, but im getting this message of 
'You dont have permission for this area." when opening loot chests and buttons.
![2016-09-10_09 32 32](https://cloud.githubusercontent.com/assets/22117372/18410920/8a3afa10-773a-11e6-9cf2-70a896a0aad7.png)

**Comment by Trixter313** [comment] 2016-09-10 13:59
This can happen in any area and is caused because Wynncraft weapons are retextured blocks and the game doesn't allow block placing.

You can use an empty hand and it should work normally.

Duplicate of https://github.com/Wynncraft/Issues/issues/3902

**Closed by Trixter313** 2016-09-10 13:59 UTC

**Comment by Ribcage52** [comment] 2016-09-10 14:12
oh well dont i feel stupid now cx
