### ISSUE TITLE
pirate island

### ISSUE THREAD

**Issue by RedNightDragon** [Wynncraft/Issues#4404] opened 2016-03-02 20:36 UTC
I understand we are supposed to post with previous related posts but the one I found for this is really old and when I look to see if it is visible I don't find it unless I search for it specifically. On pirate island the item identifier and the emerald merchant are both MIA. Also (I know you are already working on this but I might as well put it in) the map will not spawn for beneath the depths.

**Comment by DarkDemonDragon** [comment] 2016-03-03 13:20
Both of these bugs haven been reported.
No ID or Emerald NPC #3272 
Map not spawning #4236 

Please close as this is a duplicate of 2 issues. Please follow the originals as any future news on the issues will be posted there.

**Closed** 2016-03-03 19:41 UTC

**Comment by RedNightDragon** [comment] 2016-03-03 19:43
i don't know how to change it to duplicate. also that previous post is really old so I didn't know if whoever can fix it would see it and think it still relevant.

**Comment by DarkDemonDragon** [comment] 2016-03-03 21:28
There aren't supposed to be duplicates. Staff will tag posts as duplicates for organization purposes, but if there is already an open issue on the topic then do not make another issue. Feel free to post about it on the forums if it's an issue that's been around for awhile and you want to make staff aware about.

**Comment by RedNightDragon** [comment] 2016-03-04 02:16
ok. what should I do to bring attention to an issue? can staff see when new comments come on closed issues? if I can't make a new one and the old one is old how can I bring attention to it? thanks for your help.

**Comment by DarkDemonDragon** [comment] 2016-03-04 12:01
Like I said there's always the forums. The reason we don't want duplicates here is that it becomes too congested and messy for staff to look through. Thank you for understanding :)

**Comment by RedNightDragon** [comment] 2016-03-04 16:48
Your welcome. But where on the forums do I post? On the forums the bug reports go here so do I just have to hope a mod is on and tell them about it? Or is there somewhere else I can post?

**Comment by DarkDemonDragon** [comment] 2016-03-04 19:32
Make a thread in the Wynncraft section
