### ISSUE TITLE
Armour drawing not working

### ISSUE THREAD

**Issue by lecq4lifez** [Wynncraft/Issues#2032] opened 2015-06-24 23:49 UTC
i don't know why but drawing my armour does not work i was on for over an hour and armour did not draw on my mage i put on relic gear and it drew but when i got on my archer it didn't and now armour doesn't draw at all

**Comment by Trixter313** [comment] 2015-06-24 23:51
Duplicate of https://github.com/Wynncraft/Issues/issues/1909
We recommend closing this issue and following the original to stay up to date on the status of it. Thanks and have a wonderful day! :)

**Closed** 2015-07-06 03:37 UTC
Labels: duplicate
