### ISSUE TITLE
WynnExcavation Site B, Crystals not dropping!

### ISSUE THREAD

**Issue by MikeBlackburn** [Wynncraft/Issues#4275] opened 2016-02-25 18:14 UTC
# Delete this line if you've searched for a duplicate issue first
The Purple Cristals from the Wynnexcavation Site B Quest are not dropping, making the quest uncompletable!

**Comment by Odnod** [comment] 2016-02-25 18:17
Duplicate of #4236. Please close this issue and direct any additional comments to the original post. Thanks!

**Closed** 2016-02-25 18:18 UTC
