### ISSUE TITLE
Lost all my Skill Points/Skill Levels and Spells are not working

### ISSUE THREAD

**Issue by Matt10y** [Wynncraft/Issues#4536] opened 2016-03-12 18:26 UTC
When I hopped on my lvl 49 Mage to play, 3/4 of my armor was removed off my character and into my inventory, I lost all my skill levels, I lost all my skill points (I had 4 to spend), I spawned with like 19 health (out of about 400), and I grabbed a normal wand to heal myself with heal spell but nothing happened!!

PLEASE FIX THIS HUGE ISSUE

**Comment by Matt10y** [comment] 2016-03-12 18:31
I went into hub and into a different server, now it is fixed... but it should still be checked out

**Comment by Creecreeprs** [comment] 2016-03-12 18:35
Its a bug who appairs frequently. Becearful to take always some space in you'r inventory beacause if you full and this bug apened when you have armor who needs skill point, you will lose it :/

**Comment by DarkDemonDragon** [comment] 2016-03-12 22:21
Duplicate of #4120 Please close this and follow the original.

**Closed** 2016-03-13 16:57 UTC
Labels: Duplicate
