### ISSUE TITLE
Item Glitches - Something Like Entity Clear?

### ISSUE THREAD

**Issue by SATMC** [Wynncraft/Issues#5527] opened 2016-07-20 13:05 UTC
My name is SATMC (IGN) and I experienced a bug which occurred when a player called DalarnRagei dropped 5 Liquid Emeralds at my feet. In 5 seconds or so, it disappeared without getting into my inventory or his, I also experienced this bug with a white horse I had. 

Anway the point is, I think there should be a failsafe or someway to get back the items you lost, i'm not sure if I have much proof of what happened, but there is this photo of my inventory right after the incident to prove that I did not pick it up, and this is not a fraud issue for me to get free items or money. 

https://gyazo.com/c5068dbd1c63fb540a899e38d9399fce <-- Photo.

Thank you for reading.

**Comment by YunoFGasai** [comment] 2016-07-20 13:29
Duplicate of #2703 please follow the issue on the original thread

**Closed** 2016-07-20 14:02 UTC
Labels: Duplicate
