### ISSUE TITLE
Loseing Armour Bug

### ISSUE THREAD

**Issue by Slaten6** [Wynncraft/Issues#3831] opened 2016-01-24 03:01 UTC
Hello there,
     I logged into wynncraft today with all of my Armour in all there goodness but when I loot a chest and exit out of it it updates my skin for Armour skins. which is fine but what isnt is the fact that it deleted my chest plate and helmet and I had a full inventory so it didn't appear in my inventory and it never fell on the floor either I lost Third Eye and Libra. I know there is a strict no refund policy I've played this game long enough and I'm not asking for a refund  at all. I just want this bug fixed so no one else suffers like I did. That is all thanks for reading

**Comment by Trixter313** [comment] 2016-01-24 07:22
Duplicate of https://github.com/Wynncraft/Issues/issues/3153

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-24 07:22 UTC
