### ISSUE TITLE
Can't put on armour, can't identify item

### ISSUE THREAD

**Issue by Aviee** [Wynncraft/Issues#2706] opened 2015-12-21 12:26 UTC
So I identified the helpmet 'Granite Helm' and it said I needed 5 defense skill so I went on my compass and put in 5 defence skill and it wouldn't let me put them on and it was just saying that I don't have any defence skill. I tried making my defence skill to 15 but that did nothing. Also theres an item that I can't identify it just says that it has to be unique, rare, legendary etc. the item is a rare chestplate as you can see in the video.

Video: https://drive.google.com/file/d/0BxpqpjsMHbfDLU0wOElONjBHNlU/view

It's still downloading to google drive so it might take a while

**Comment by Aviee** [comment] 2015-12-21 12:28
I don't know how but I managed to get my helmet on by adding more skill points to defence so if anyone of you's are getting this problem just add more skill points to that skill that its telling you you don't have enough of.

**Comment by Trixter313** [comment] 2015-12-22 20:58
Does the helmet work if you use a regular, working chestplate? If so, it seems the issue is caused by the chestplate, which would make this a duplicate of #2679

We recommend closing the duplicate and instead adding any comments the the original issue. Thanks!

**Closed** 2015-12-25 02:51 UTC
