### ISSUE TITLE
Hunter message (i dont have a good name for the bug)

### ISSUE THREAD

**Issue by TheMineNerf** [Wynncraft/Issues#1907] opened 2015-05-19 14:31 UTC
ik this is a VERY minor bug but... when my friend logged in as a hunter class it said the following:
[username] logged in into WC[number] as AN Hunter and not as A Hunter. i know this is minor but just wanted to point it out :)

**Comment by Trixter313** [comment] 2015-05-19 15:03
Duplicate of https://github.com/Wynncraft/Issues/issues/1338

**Closed** 2015-05-19 18:57 UTC
Labels: duplicate
