### ISSUE TITLE
Disappearing items

### ISSUE THREAD

**Issue by DoctorFryder** [Wynncraft/Issues#4560] opened 2016-03-15 16:50 UTC
Hi. I logged on Wynncraft 2 days ago and like sometimes my "skills" werent on, mean like I have 0 to all. So my items that I had on got off me. So I relogged again but after it some of my items were missing. My Leggins and Ring and Bracelet werent in my inventory. I dont know how this can happen. Next time when I logged it it was same, I didnt had items in my inventory. And I know it disappear because when I have all items on me I had 3300+HP and now I have 2500. What I can do you? Please help if here is some. Have a nice day :)

**Comment by Tom886** [comment] 2016-03-15 18:28
There is a no-refund policy, so sadly you cannot get you items back.

That being said, if this is to ever happen again, the items that don't fit into your inventory will drop to the ground. Make sure to pick the up, because they will vanish if you re-log

As a partial fix to this, ALWAYS keep open slots for all your items. Take into account accessories also.

**Comment by Trixter313** [comment] 2016-03-15 20:53
Duplicate of https://github.com/Wynncraft/Issues/issues/4120

 Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-15 20:53 UTC
