### ISSUE TITLE
Guild Glitch

### ISSUE THREAD

**Issue by ManicMelon** [Wynncraft/Issues#6952] opened 2016-12-21 04:34 UTC
For some reason when I try to leave my guild it lets me type yes and takes away my soul points but keeps me in the guild. I am confused plz help.

**Comment by Trixter313** [comment] 2016-12-21 05:50
I see that you've changed your Minecraft username recently, making this a duplicate of https://github.com/Wynncraft/Issues/issues/3665

**Closed by Trixter313** 2016-12-21 05:50 UTC
