### ISSUE TITLE
Bugged Items

### ISSUE THREAD

**Issue by DRedDogPE** [Wynncraft/Issues#4493] opened 2016-03-07 19:22 UTC
![Bugged Item](http://i.imgur.com/Ve3NaNl.png)
The item is bugged and wont give any effects. It is a legendary item so i kinda want it fixed.

**Comment by Trixter313** [comment] 2016-03-07 23:35
Duplicate of #3175 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-07 23:35 UTC
