### ISSUE TITLE
cannot log in with my mage

### ISSUE THREAD

**Issue by PLutonium27** [Wynncraft/Issues#7872] opened 2017-04-15 06:59 UTC
I can't log in with my mage for a week. when I select mage, it says that there has been an error and I cannot play it. but other classes don't have any problem. please help me..
nickname:PLutonium27

**Comment by LordHelmchen98** [comment] 2017-04-15 07:55
Duplicate of #7680 please look there for future information.

**Closed by LordHelmchen98** 2017-04-15 07:55 UTC
