### ISSUE TITLE
/kill in silverfish dungeon brought me to Olux?!?

### ISSUE THREAD

**Issue by bmarshall79** [Wynncraft/Issues#5566] opened 2016-07-24 06:07 UTC
Following my last report, i was stuck in the silverfish dungeon because of "access issues" (see previous report,) and so i did /kill to get out. when my game loaded, "You are now entering Olux" filled my screen and there i was (or am at the moment.) This is literally two bugs in a row, (potentially linked?) so this needs to be addressed. (Although, it might make a good travel glitch if it's repeatable.)

**Comment by sammyvsparks** [comment] 2016-07-24 07:38
Some dungeons teleport you in a area far from the map which collective respawning is not quite perfected yet and Olux would be the nearest city I would guess. If they can fix that they have choose not to yet.

**Comment by Moe-Ronickah** [comment] 2016-07-24 08:15
Duplicate of #3617 .

**Closed by Moe-Ronickah** 2016-07-24 08:15 UTC
Labels: Duplicate
