### ISSUE TITLE
Texturepack bug (Tormenter) (1.10.2)

### ISSUE THREAD

**Issue by dometheunicorn** [Wynncraft/Issues#6561] opened 2016-11-03 11:42 UTC
In 1.10.2, the bow "Tormenter" has a wooden slab texture.
![2016-11-03_12 38 34](https://cloud.githubusercontent.com/assets/23236811/19964585/d54c3e30-a1c2-11e6-8281-7163c5eb0028.png)

**Comment by LordHelmchen98** [comment] 2016-11-03 11:50
Unfortunately bugs like that happen sometimes. If you want to prevent that you should play in 1.8.9. However you wont be able to see the new item skins in 1.8.9. Maybe you can also do it if you delete the wynncraft serverresourcepack. Therefore you have to go into your .minecraft folder and open serverresourcepacks then delete the 'legacy' file.

**Comment by thecoolkogut4** [comment] 2016-11-03 12:04
switching to 1.8.9 will just give you pick axes, shoves etc as weapons. best thing to do is to delete the pack as lord said and hope it fixes.

**Comment by LordHelmchen98** [comment] 2016-11-03 13:03
Well the pickaxes arent directly related to this and what is shown as pickaxes and shovels is shown as false item skins in higher versions which is as annoying imo.

**Comment by thecoolkogut4** [comment] 2016-11-03 13:11
yeah but if your trying to fix a broken texture, youll have in any version. no point in really changing anymore after the update. just depends what you want to see vs what u don't. personal preference. if the goal for him is to remove the slab, your gonna be adding in shovels and pick axes and more lmao

**Comment by Trixter313** [comment] 2016-11-05 21:23
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

**Closed by Trixter313** 2016-11-05 21:23 UTC
