### ISSUE TITLE
Life Steal only seems to work from Poison Damage

### ISSUE THREAD

**Issue by Johnneh** [Wynncraft/Issues#3225] opened 2015-12-27 05:45 UTC
I have some equipment that reduces my health over time. It has life steal, and the life steal (on a chestplate and 2 rings) does NOT work with my fist, a weapon without poison or a weapon when I don't have poison on any of my armor. When I do have poison, it DOES work, but only from the poison damage. If I keep hitting (preventing the poison damage from starting) I don't regain health, and I continue to lose health. Only when I hit once then let the poison will I regain health. (In my case, 20 hp per hit of poison over 3 seconds. There are 4 hits of poison so I regain 80 health if I just hit a mob then stop).

This is clearly bugged - Life steal should work on all hits, not just poison.

**Comment by W-Schnee** [comment] 2015-12-27 10:06
I can confirm this. I have armor with life steal. Life steal only works when there is poison damage. It doesn't work when the weapon itself has life steal but there is no poison damage.

**Comment by DarkDemonDragon** [comment] 2015-12-27 14:45
Ehh life steal really only works with certain attacks. I've tested Life Steal on a pointblank Arrow Storm attack (pushed a villager into a corner and did it right in front of him) and it sort of works, but it's not practical in actual combat as it's difficult to do that on aggressive mobs with the new AI, so Life Steal really shouldn't be based off a constant stream of dmg every 2-4 seconds. However, I don't know if this is a bug or not as Grian did say Life Steal would be nerfed.

**Comment by Johnneh** [comment] 2016-01-26 12:58
This is still an issue that needs resolving.

**Comment by DarkDemonDragon** [comment] 2016-01-26 13:03
I honestly don't know if this is a balancing mechanic or now at this moment. The admins did say that life/mana steal would be balanced. Warrior's war scream and Archer's arrow storm both life steal successfully but Warrior works every hit while arrow storm works every 4-6 arrows.

**Comment by DarkDemonDragon** [comment] 2016-02-09 15:37
From the latest update it appears that Warrior's war scream getting lifesteal in one hit was simply a bug and has been fixed as of lately.

**Comment by ecwarriorz** [comment] 2016-02-10 10:23
Hi. I'm an archer, and I'm using Nivla's Arch, which deals damage with poison. I wear Helm of the Dead, which has life steal on it. Life steal was working a few days ago - when I shot a monster with Nivla's Arch, every time it got hurt, I would regenerate health. But, starting today, that hasn't happened. Instead, I just regenerate health every 5 seconds, and poisoning or just dealing plain damage does nothing to my health. Is life steal no longer working, or have I done something wrong?

**Comment by Dar-krusos** [comment] 2016-02-10 12:28
Someone will have to post something on the forums to try and get an answer from Salted.

**Comment by DarkDemonDragon** [comment] 2016-02-10 13:13
@ecwarriorz some worlds occasionally bug and life and mana steal both won't work. If this happens try switching worlds.

**Comment by ecwarriorz** [comment] 2016-02-11 06:15
@DarkDemonDragon I have tried switching to multiple different worlds, and they all don't work.

**Comment by DarkDemonDragon** [comment] 2016-02-11 13:12
Yea now all worlds don't work. Most likely what they use as the base for all the worlds was updated and this broke mana/life steal. All the worlds have now reset and the new world was applied making all of them have the bug. Hopefully the Admins will notice this and fix this.

**Comment by ecwarriorz** [comment] 2016-02-16 01:44
Hi. Not trying to rush y'all or anything, but any idea when it will be fixed? Life steal's pretty important cuz my health regenerates relatively slowly.

**Comment by Dar-krusos** [comment] 2016-02-16 05:29
I have attained information that this was part of a recent patch, so it is intentional. Life and Mana Steal now only work on a per hit basis that does not include spell hit. Basically, only basic attacks will trigger steal.

**Comment by DarkDemonDragon** [comment] 2016-02-16 19:37
@Dar-krusos it's not a per hit basis, but chance based that changes with your attack speed. Basically if you have a 100/2 lifesteal then averagely you'll steal 100 hp every 2 seconds.

**Comment by Dar-krusos** [comment] 2016-02-17 03:16
No, I think they changed it last week or the week prior. In war, Life and Mana steal worked abundantly, as there are tens of mobs at once. Now, Life and Mana Steal only work when you shoot them with basic attacks, and even then, only works with poison.

**Comment by ecwarriorz** [comment] 2016-02-18 05:12
I don't think it's working at all. My health regenerates every 5 seconds, but I don't think it's lifesteal, since I regenerate health without hurting mobs (which is supposed to happen).

**Comment by DarkDemonDragon** [comment] 2016-02-20 22:04
@ecwarriorz what's your lifesteal?

**Comment by ecwarriorz** [comment] 2016-02-21 05:03
@DarkDemonDragon  65/2s

**Comment by DarkDemonDragon** [comment] 2016-02-21 14:46
In that case it'd be really hard to notice unless your max hp is under 1000. Remember that you gain 65 every 2 seconds which is a very slow rate. Lifesteal and Manasteal have been heavily nerfed so don't rely on them anymore.

**Comment by ecwarriorz** [comment] 2016-02-26 10:05
Wait, but no matter how slow the rate of my lifesteal, I should still see it happening.

**Comment by DarkDemonDragon** [comment] 2016-02-26 13:11
@ecwarriorz like I said this is hard to notice during combat. I recommend fighting some mobs you're comfortable fighting with and that can damage you somewhat so you can show regen and recording this. Then you can look back on it and see if you are regening or not. Someone did this on the forums and still didn't notice that his life steal was working until an Admin pointed out all the places in the video that the regen happened. The reason why Life Steal is hard to see is that it **looks** exactly like when normal regen is happening. However, the numbers on the bottom will show it.

**Comment by Moe-Ronickah** [comment] 2016-02-26 14:00
To get a better idea of how Life Steal works, now, please watch the video on [this thread](https://forums.wynncraft.com/threads/why-life-steal-isnt-viable.112950/), and read Salted's notes on the video.  Let us know if this resolves your issue.

**Comment by DarkDemonDragon** [comment] 2016-03-02 03:29
Since Life Steal DOESN'T work with Poison Damage anymore I think it's time to close this issue.

**Comment by Moe-Ronickah** [comment] 2016-03-05 06:21
Me too.

**Closed by Moe-Ronickah** 2016-03-05 06:21 UTC
Labels: Game Mechanics
