### ISSUE TITLE
Horse Lag Back

### ISSUE THREAD

**Issue by firefox0809** [Wynncraft/Issues#6701] opened 2016-11-16 01:29 UTC
I have noticed a problem in 1.9 or higher where u would get on a horse and it would sometimes move weirdly(I can't tell if it's just me or it affects everyone). And when you dismounted, you would be teleported back. I have concluded based on what my friends have seen is that your screen/side registers you as moving on a horse. But the servers register you as either stuck in a wall. I could tell because I would have cloud particles on and wybels following me, and suddenly the particle would be stuck on something or floating to my left, right, behind, or in front of you. It gets really annoying because if you don't notice it, chunks stop loading and you would be teleported back to where you supposedly got stuck.

In this picture, the cloud particle is where I am according to the server but for my screen, I was not there. And when I would dismount, I would be teleported there instead. I would really like a fix for this bug.

![2016-11-15_17 27 20](https://cloud.githubusercontent.com/assets/23468916/20331216/d5f92fd8-ab58-11e6-8d8a-c581f1b66e22.png)

**Comment by thecoolkogut4** [comment] 2016-11-16 02:35
horses are broken/glitchy in 1.9+ i recommend playing in version 1.8 to fix horses (1.8 breaks some textures and the wither bar)

**Comment by ColinRioux** [comment] 2016-11-17 03:04
Duplicate of #6077

**Closed by ColinRioux** 2016-11-17 03:04 UTC
