### ISSUE TITLE
Gert hunger part 1 escaping the cell

### ISSUE THREAD

**Issue by war-master-9** [Wynncraft/Issues#5748] opened 2016-08-16 00:39 UTC
i cant escape the cell (stage 13), i know the puzzle to escape but it wont let me this is what i get when i try too escape

![image](https://cloud.githubusercontent.com/assets/20957893/17684257/4c6eab32-6317-11e6-992b-29c2ace6aaa3.png) also if u cant see the screeny in white text it says sum txt in white

**Comment by Trixter313** [comment] 2016-08-16 01:07
What does it say in your quest book? Also, try walking around the cell, it might trigger a quest update.

**Comment by ColinRioux** [comment] 2016-08-16 14:15
I'm told you have to walk to the back of the cell area. When you see `[Quest Book Updated]` then you'll know you triggered it.

**Comment by Moe-Ronickah** [comment] 2016-08-21 07:53
Duplicate of #5434

**Closed by Moe-Ronickah** 2016-08-21 07:53 UTC
Labels: Duplicate
