### ISSUE TITLE
Weapon Not Textured

### ISSUE THREAD

**Issue by truesurvivor9** [Wynncraft/Issues#5698] opened 2016-08-10 00:57 UTC
The wand named Dark Needle is not textured. The item is just a stone slab.
Screenshots: 
![2016-08-09_17 54 33](https://cloud.githubusercontent.com/assets/18035613/17538495/c514b192-5e5a-11e6-96bf-898da293d46c.png)
![2016-08-09_17 54 37](https://cloud.githubusercontent.com/assets/18035613/17538497/c696d702-5e5a-11e6-8654-ea834ee60da7.png)

**Comment by ColinRioux** [comment] 2016-08-10 01:57
@Villageacules

**Comment by Trixter313** [comment] 2016-08-10 02:03
Appears to be a duplicate of https://github.com/Wynncraft/Issues/issues/4548

If you search for slab and look at the closed issues you'll see quite a few items affected by this.

**Closed by Trixter313** 2016-08-10 02:03 UTC
