### ISSUE TITLE
Legendary Unidentified Helmet lost stats and everything now named "Piyyylier"

### ISSUE THREAD

**Issue by Frostwulfe** [Wynncraft/Issues#3412] opened 2016-01-01 03:14 UTC
My legendary h

**Comment by Frostwulfe** [comment] 2016-01-01 03:16
Legendary Helmet was unidentified lvl 40-48 i think and I was so excited to find it, then when i made it to the item identifier it was renamed "Piyyylier" or something. I tried relogging and everything but it wont fix. Please help. Screenshots: https://gyazo.com/c04fb338caec6171716361793f4aa29d
dont have a screenshot of before it happened though.

**Comment by Trixter313** [comment] 2016-01-01 07:37
I believe this is a duplicate of https://github.com/Wynncraft/Issues/issues/3175 and soon should turn into some code, possibly after a relog.

Please refer comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-01 07:37 UTC
