### ISSUE TITLE
Legendary helmet Pélier lost it's stats

### ISSUE THREAD

**Issue by Vamury** [Wynncraft/Issues#3409] opened 2016-01-01 01:10 UTC
Posted this 9 days ago, but forgot to follow up on it after I went to bed. 

Like I posted last time the only thing my legendary helmet Pélier does now is increase my armor rating.
I can put it on, but nothing else. It's name is now the code for the helmet not actually Pélier. 

![2016-01-01_02 03 24](https://cloud.githubusercontent.com/assets/16404229/12069386/9b2b1830-b02c-11e5-8422-a16ec9261eaf.png)

However when I hold it in my hand, I can see something similar to it's original name: 

![2016-01-01_01 59 22](https://cloud.githubusercontent.com/assets/16404229/12069390/b509862e-b02c-11e5-9a15-1c125dc3f2c1.png)

I have no clue what happened to it...

**Comment by Vamury** [comment] 2016-01-01 01:11
https://github.com/Wynncraft/Issues/issues/2879
Link for the last entry I made

**Comment by Frostwulfe** [comment] 2016-01-01 02:41
SAME THING HAPPENED TO ME and also in llevigar i need help. i shouted out and people said relogging or change servers neither worked!!

**Comment by Trixter313** [comment] 2016-01-01 07:35
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please refer any future comments to the original open thread. Thanks!

**Closed by Trixter313** 2016-01-01 07:35 UTC
