### ISSUE TITLE
Fierte is broke

### ISSUE THREAD

**Issue by Creecreeprs** [Wynncraft/Issues#4605] opened 2016-03-20 11:17 UTC
I don't know if someone post this in github, so here it is :
Fiertè: https://i.imgur.com/tNaZocT.jpg
I heard it's the same thing for Ik-El-Ván 
If this is ardly post here, I will close this post.

**Comment by Trixter313** [comment] 2016-03-20 16:08
Duplicate of #3175 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-20 16:08 UTC
