### ISSUE TITLE
Jester rings

### ISSUE THREAD

**Issue by lesliep3579** [Wynncraft/Issues#3806] opened 2016-01-21 16:19 UTC
Currently, wearing a second jester ring doesn't apply to the set bonus. I believe this is a bug? And if it isn't, it should probably be fixed.

**Comment by Dar-krusos** [comment] 2016-01-21 23:03
Duplicate of #3787. Please see that issue are respond there.

**Comment by DarkDemonDragon** [comment] 2016-01-22 13:06
A set bonus is a SET bonus. It gets applied as a set not per item. All the items get you the total bonus not each item. Therefore, this is completely intentional so please close this issue as this is not a bug.

**Comment by lesliep3579** [comment] 2016-01-30 14:59
yes i understand that it is a SET bonus, which is applied for wearing multiple SET items. I find it weird that the second ring does't apply to the TOTAL bonus, while the first one does. This allows for people to cheat out the negative jester SET bonus by wearing a second ring, because it doesn;t apply.

**Comment by Dar-krusos** [comment] 2016-01-30 16:22
Oh. Yeah, you phrased your issue wrong.
Yes, that is a bug and I'm pretty sure they're going to fix that in the next few updates.

**Comment by DarkDemonDragon** [comment] 2016-01-30 23:12
It's not a bug it's how set works. Say for instance there's a poop set that has a -300% walk speed set bonus. It requires a helm, chest, leggings, and boots. Wearing all **four** items gives you **one** -300%, not a total of -1200% walking speed.

**Comment by Dar-krusos** [comment] 2016-01-31 03:42
Yes, leslie understands this. What leslie is trying to say is that there is not set bonus for a second ring. The first ring will change the set bonus, but the second will not affect it, meaning that you can get an insanely high stat boost when wearing two jester rings.

**Comment by DarkDemonDragon** [comment] 2016-01-31 20:35
Well I think that's intentional. This is why most people wear only rings and necklace to take the fullest advantage of the set. This could be a bug, but you'd honestly have to ask the admins about it since this could just be how they intended things to be. In my opinion it's fine, but it's up to the staff to decide if this needs to be balanced. They just nerfed the Jester set, so I assumed they'd notice this and decided not to modify, but it could have been an oversight.

**Comment by Trixter313** [comment] 2016-02-07 21:33
Is this still occurring? A recent patch supposedly fixed some set related issues. (https://forums.wynncraft.com/threads/gavel-patch-14-0-8.109965/) Thanks!

**Comment by Trixter313** [comment] 2016-02-20 21:06
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!

**Closed by Trixter313** 2016-02-20 21:06 UTC
Labels: Game Mechanics, Items
