### ISSUE TITLE
Armor bug

### ISSUE THREAD

**Issue by Drulle19** [Wynncraft/Issues#4509] opened 2016-03-09 18:18 UTC
when i joined world 4 at wynncraft my skill points bugged and I lost my:
chestplate (Dravarden) helmet (granite helm) shoes (abysso galoshes(quest item))
and two rings (sessanta and Ozoth's Breath)

![2016-03-09_18 24 57](https://cloud.githubusercontent.com/assets/17748906/13644443/230cb2ac-e626-11e5-9b58-d025ee61c88f.png)
![2016-03-09_18 24 33](https://cloud.githubusercontent.com/assets/17748906/13644445/2415df84-e626-11e5-9e54-d3849cbe11b6.png)

**Comment by Odnod** [comment] 2016-03-09 18:20
Duplicate of #4120, please close this thread and direct any additional comments to the original one. Thanks!

**Comment by Drulle19** [comment] 2016-03-09 18:40
I will have my items refunded

**Comment by BlahBlah161616** [comment] 2016-03-09 18:43
Wynncraft has a strict no refund policy.

**Comment by Drulle19** [comment] 2016-03-09 18:44
but the quest item

**Comment by Drulle19** [comment] 2016-03-09 18:51
I will have my quest item refunded

**Comment by BlahBlah161616** [comment] 2016-03-09 18:53
/fixquests, if this doesn't work ur doomed

**Comment by Odnod** [comment] 2016-03-09 21:29
Yes. /fixquests will give you back your Abyssso Galoshes.

**Comment by Moe-Ronickah** [comment] 2016-03-11 04:00
For now, do not log out with a full inventory.

**Closed by Moe-Ronickah** 2016-03-11 04:00 UTC
Labels: Duplicate
