### ISSUE TITLE
Dungeon Keys

### ISSUE THREAD

**Issue by rmcar17** [Wynncraft/Issues#6197] opened 2016-09-19 02:06 UTC
Mobs outside Ragni still drop the skeleton dungeon key whilst the relative key merchant only accepts the decrepit sewers key. So mobs still drop the wrong dungeon keys.

**Comment by ColinRioux** [comment] 2016-09-20 00:10
I'm pretty sure that that is known, and you can trade Skeleton keys for Decrepit Sewers keys at the key conversion merchant in Detlas.

**Comment by rmcar17** [comment] 2016-09-20 00:45
That is true but the game was intended for mobs post update to drop the new keys. They are still dropping the old keys.

**Comment by Trixter313** [comment] 2016-09-20 01:33
Duplicate of https://github.com/Wynncraft/Issues/issues/5968
It was closed as fixed so most likely it will be fixed in the next minor update or patch but I'll wait for @Moe-Ronickah to confirm.

**Comment by rmcar17** [comment] 2016-09-20 01:34
Okay thanks, didn't see the other post

**Closed** 2016-09-25 22:28 UTC
Labels: Duplicate
