### ISSUE TITLE
What is happening

### ISSUE THREAD

**Issue by EpicOverKill567** [Wynncraft/Issues#2229] opened 2015-08-20 15:25 UTC
It says server can hold 1 person and it is bugging out...

**Comment by EpicOverKill567** [comment] 2015-08-20 21:17
Okay thats gone but I still cant connect

**Comment by Trixter313** [comment] 2015-08-21 20:32
The issue is fixed, correct?

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Closed** 2015-08-21 20:33 UTC
