### ISSUE TITLE
Untextured Blocks

### ISSUE THREAD

**Issue by Kryminal1** [Wynncraft/Issues#6344] opened 2016-10-06 21:04 UTC
Ok hi, I snooped around a bit and found not much about this and if im wrong well sorry.
![2016-10-06_16 53 57](https://cloud.githubusercontent.com/assets/19760814/19170448/795070c0-8be6-11e6-90f8-632f9be4747c.png) That happened, the problem has been caused by installing JEI and Forge, i fixed it with not using those, but hate to change around all the time. Obviously this is only inconvenient and doesn't need fixed, just bringing up the attention.

**Comment by LordHelmchen98** [comment] 2016-10-06 21:25
You just have to search for 'forge' and you will see this is a duplicate of #5057.
This is a known problem with forge on 1.9. I dont think there is a way to fix that in 1.9. You either have to use forge with 1.8.9 or use 1.9 without forge.

**Comment by Kryminal1** [comment] 2016-10-07 19:56
ok Sorry for duping a thread, thanks.
Please Close.

**Closed** 2016-10-07 19:56 UTC
