### ISSUE TITLE
Pélier Broken?

### ISSUE THREAD

**Issue by TOX1KDEFTON3** [Wynncraft/Issues#3754] opened 2016-01-18 01:55 UTC
So, I had just gotten myself a Pélier, and I log off about a half hour later. When I come back on ten minutes later, it's broken and looks like this:
![2016-01-17_17 53 42](https://cloud.githubusercontent.com/assets/16727738/12381659/7a617f08-bd43-11e5-8e2c-06635929b28b.png)
Please please PLEASE help me as I had an auction going for this item!!

**Comment by Trixter313** [comment] 2016-01-18 02:03
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-18 02:03 UTC
