### ISSUE TITLE
Lost my le when thrown on ground

### ISSUE THREAD

**Issue by DannyTheScoob** [Wynncraft/Issues#5489] opened 2016-07-15 08:31 UTC
i threw my 39 liquid emerald on ground while moving inventory and it disappeared 
this bug happened between 2:00 A.M. and 2:30 A.M. MDT 
if possible i would like a refund

**Comment by sammyvsparks** [comment] 2016-07-15 08:37
@DannyTheScoob Where did you drop it at and how far away did you get from it? Its also possible if you didn't notice for ~20 seconds that someone else may of picked them up.
However Wynncraft has a strict no refund policy but we can at least help you figure out what happened exactly.

**Comment by DannyTheScoob** [comment] 2016-07-15 08:42
@sammyvsparks I dropped it in detlas right outside of the bank, and it was missing within at least 5 seconds of dropping the item (i would go as far as saying it disappeared as soon as i dragged it out and clicked) i do not get what you mean by how far away did you get from it? 
I am very disappointed that i can not get a refund in fact i am kind of angry

**Comment by sammyvsparks** [comment] 2016-07-15 09:13
@DannyTheScoob How far away being 10, 20 blocks. But seeing as it was a few seconds I cant picture you getting that far too fast. What place we're you at when you dropped them? Its possible a hopper grabbed them and deleted it if you we're in a bank.

**Comment by DannyTheScoob** [comment] 2016-07-15 09:18
@sammyvsparks i did not get anywhere i noticed it as soon as it happened because of a small 1 second at most lag spike and exited the inventory menu and looked all around i am sure a hopper did not grab it because i was at least 10 blocks away not facing that derection

**Comment by Moe-Ronickah** [comment] 2016-07-15 13:50
Sorry, but this is a duplicate of #2703.  Don't throw LE.  Don't drop LE.  Be careful with LE.

**Closed by Moe-Ronickah** 2016-07-15 13:50 UTC
Labels: Duplicate

**Comment by DannyTheScoob** [comment] 2016-07-16 00:45
@Moe-Ronickah WELL I DID NOT DO THE FRICKIN RIGHT CLICK THROW I THREW IT FROM MY INVENTORY BY DRAGGING IT OUT

**Comment by Moe-Ronickah** [comment] 2016-07-16 13:24
@DannyTheScoob , and your point is?  In case you have not noticed, this is a duplicate of #2703.  It does not matter how you removed the LE from your inventory, whether you dropped it or threw it or dragged it out, LE is quirky once it is out of your inventory and in the world.  Also, there is a destruction hopper in the front corner of the Detlas bank.  Yes, it is walled off on three sides, however, MC sometimes ignores those walls, sometimes not.  The bottom line is, LE is quirky.  Don't let it out into the world.

I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency.
