### ISSUE TITLE
lightdust cavern no drop

### ISSUE THREAD

**Issue by natourod1** [Wynncraft/Issues#4376] opened 2016-03-01 09:48 UTC
hi, I do the quest temple of the legends, but the lightdust no drop in the lightdust cavern ...
Can someoine help? thanks! ^^

**Comment by Moe-Ronickah** [comment] 2016-03-01 13:40
Duplicate of #4236 . Please, use the search instructions on the front page so that you don't post duplicates, but, rather, add to the original issue. Thank you.

**Closed by Moe-Ronickah** 2016-03-01 13:40 UTC
Labels: Duplicate
