### ISSUE TITLE
Fire Wire doesn't work in Guild Wars!

### ISSUE THREAD

**Issue by MWINS01** [Wynncraft/Issues#5185] opened 2016-06-09 15:49 UTC
![2016-06-09_16 34 45](https://cloud.githubusercontent.com/assets/19840913/15936120/18be600c-2e6a-11e6-9433-ba6ba8d9a242.png)

**Comment by Trixter313** [comment] 2016-06-09 16:06
Duplicate of https://github.com/Wynncraft/Issues/issues/5088

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-06-09 16:06 UTC
