### ISSUE TITLE
BUG on Beneath the Depths

### ISSUE THREAD

**Issue by BarakaGG** [Wynncraft/Issues#4417] opened 2016-03-03 18:22 UTC
The item map dont drop at the room
i try to get him on 4 servers!

Name in game: BarakaGG
Level/class: Mage/60

**Comment by Odnod** [comment] 2016-03-03 18:54
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-05 05:35 UTC
Labels: Duplicate, Quests
