### ISSUE TITLE
Cannot use my Mage class

### ISSUE THREAD

**Issue by Ewaszczypior1** [Wynncraft/Issues#3470] opened 2016-01-02 18:05 UTC
I have not played Minecraft for a while and decided to reenter Wynncraft server after a long pause. Sadly, for some reason I cannot use my Mage class that I have 56 levels on. I read on in the forums that there was a major update on Wynncraft and I know that I left the server before the update, maybe 3 weeks after the tower on ice location was added? I want to play Wynncraft but I don't want a totally new class before I finish Mage. If any info about reaching my Mage class again is available please answer here.
Thank you for your attention
Ewaszczypior1

Edit: I played a bit on the server and figured out some things that might cause the error- 1. I always hold items like armor and the most important things on the slots that are now reserved for rings etc. 2. I wear unidentified items. 3. My inventory was probably full which means that my character can't move these items on spare slots in the inventory and therefore preventing me from playing.

If any moderator is willing to help me with this issue I would be thankful. So far people I met on the server have no idea what to do or just simply ignore me. Thanks for reading

**Comment by Trixter313** [comment] 2016-01-02 22:00
Are there any error messages that appear when you try selecting Mage? Also, if your inventory is full it deletes some items (although it's supposed to just drop them) to make room so that shouldn't be an issue.

**Comment by Verret001** [comment] 2016-01-03 14:45
Is this what happened to you?
https://github.com/Wynncraft/Issues/issues/3250

**Comment by Ewaszczypior1** [comment] 2016-01-03 22:27
The only message shown is "There was an error.. try again" and it turns me back itno the class selection window.
And the issue is similar to the #3250 but I don't see any wool, I just get a black screen altogether.

**Comment by Trixter313** [comment] 2016-01-03 23:23
Duplicate of #3250 

The wool is black and very dark so it can look like just a black screen at times but you're probably in the same spot and even if you aren't, it's the same error message and general issue so I'd say just because they might be different locations doesn't mean they are different issues. Please refer any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-03 23:23 UTC
