### ISSUE TITLE
Jungle Fever (Maybe a bug?)

### ISSUE THREAD

**Issue by BobbyWood** [Wynncraft/Issues#6317] opened 2016-10-02 19:44 UTC
Im a level 60 Archer and just finished Jungle Fever. I was rushing through the quest and couldn't have cared less about the dialog at the end. I was spamming right click to go through the dialog quicker, I had 1 spot in my hot bar open that did NOT have an item in it, this was the hotbar slot I was using. As you know you use right click to throw items in regular minecraft, without the texture on LE its some sort of throwable item, ( It may be a XP bottle, not sure ) Once again I was spamming right click and then I got my reward. But ended up throwing my LE,  I didnt worry to much since you're not able to completely throw it. But I didn't get it back. I waited around 20 minutes trying out different things, still no luck. 

  I don't know if this is a common bug or even a bug at all, yet I don't think its necessarily fair that I lost an entire LE due to a glitch or bug.

**Comment by LordHelmchen98** [comment] 2016-10-02 21:49
Agreed this is not really fair but due to wynncrafts no refund policy I dont think you will get it back.

**Comment by Moe-Ronickah** [comment] 2016-10-03 02:42
Duplicate of #2703

**Closed by Moe-Ronickah** 2016-10-03 02:42 UTC
Labels: Duplicate
