### ISSUE TITLE
Item glitched (long purple name, how to fix this?) 

### ISSUE THREAD

**Issue by MCJoeri** [Wynncraft/Issues#4514] opened 2016-03-10 14:28 UTC
My mage weapon has glitched out.

This happend before but it fixed it self after 5 minutes. Now it has been 3 days and still hasent fixed it selfs yet.
<img width="422" alt="displayglitch" src="https://cloud.githubusercontent.com/assets/17765868/13672813/9f9b07a0-e6d6-11e5-88a3-29a93edf867d.png">

name of the weapon: Dévoreuse.

**Comment by DarkDemonDragon** [comment] 2016-03-10 15:44
Weapons with accents are easily broken. To try to fix it go into a NPC GUI like a Emerald NPC at a bank. Then hover over the wand for 5 seconds. Exit the GUI and then check the wand for a few seconds and see if it reverts. If 10 seconds pass and nothing happens then it may be permanently broken :/

**Comment by MCJoeri** [comment] 2016-03-10 16:39
Sadly, it didnt work :/.

**Comment by Moe-Ronickah** [comment] 2016-03-11 03:54
This is similar to #3175 , however, that particular issue was long fixed.

**Comment by DarkDemonDragon** [comment] 2016-03-11 04:25
@Moe-Ronickah was there confirmation that it was fixed? I think most people in that issue just gave up on their items and moved on.

**Comment by Moe-Ronickah** [comment] 2016-03-11 04:43
Supposedly, all of the names with accented characters were fixed, and, as his wand was working, it almost certainly is a new  Dévoreuse, but it may an old one.  In any event, it WAS working, which makes this most likely a new issue since the Gavel update.  The old issue was items NOT updating.  His is either new, or it updated.  It most certainly is not a duplicate of #3175  because of those reasons, but it may be an issue related to #3175 ..

**Comment by DarkDemonDragon** [comment] 2016-03-11 05:03
Or perhaps the bug returned ;-; Well whatever the case is, this is definitely related to #3175

**Comment by BlahBlah161616** [comment] 2016-03-11 17:24
Weapons do that whenever you exit from a merchant menu, I'll look more into it when I fix my resource pack.

**Comment by atz775** [comment] 2016-03-12 23:56
Normally after a few secs it goes back to normal or when I close my inventory. If it still isn't working try that!

**Comment by DarkDemonDragon** [comment] 2016-03-13 00:03
Entirely different bug guys.

**Comment by Moe-Ronickah** [comment] 2016-03-15 06:34
@MCJoeri , a patch was pushed through, in the past 12 hours.  Is your item fixed?

**Comment by Trixter313** [comment] 2016-03-22 22:28
So why isn't this a duplicate of 3175? What you're describing sounds like https://github.com/Wynncraft/Issues/issues/3161 to me, we believe that is fixed for and post-Gavel items and only affected pre-Gavel items. I don't see that in 3175's thread though. Maybe you have them mixed up? This looks like a duplicate to me but maybe there's more information on the forums or other places =)

Just wondering, thanks!

**Comment by DarkDemonDragon** [comment] 2016-03-23 02:56
This might not be a duplicate because this wand might be post-Gavel.

**Comment by Trixter313** [comment] 2016-03-24 10:44
But why would that make a difference for 3175? I thought 3161 was the only one that was basically resolved because it only affected pre-Gavel items. I don't remember 3175 only affecting pre-gavel items.

**Comment by DarkDemonDragon** [comment] 2016-03-24 11:42
3175 happened immediately after Gavel. While it's hard to say for the multitude of other broken items linked to the original issue, the original item with the original post is definitely pre-Gavel. This is 100% post-Gavel because 

> This happend before but it fixed it self after 5 minutes

Since the item name bug did not exist at all pre-Gavel, this means that this weapon was working post-Gavel and then broke.

**Comment by Trixter313** [comment] 2016-03-25 00:00
So why does that make it not a duplicate though? They seem like the exact same issue to me. Sorry I'm so confused about this.

**Comment by DarkDemonDragon** [comment] 2016-03-25 20:57
Because one issue was simply due to the item themselves bugging out because of the Gavel Update. This issue shows an item that was obtained after Gavel but then suddenly bugging out. They have different circumstances and different causes.

**Comment by Moe-Ronickah** [comment] 2016-05-20 23:16
Too old and no new information.

**Closed by Moe-Ronickah** 2016-05-20 23:16 UTC
Labels: Items
