### ISSUE TITLE
No permission to enter Llevigar

### ISSUE THREAD

**Issue by GlynOw** [Wynncraft/Issues#3891] opened 2016-01-27 19:35 UTC
Whenever I try to use a Llevigar teleport scroll, I am told that "You do not have permission to enter this area" but I still lose an SP and am blinded for a few moments.

Also, when I fell to 0 health near Llevigar, the "You do not have permission to enter this area" message appeared. I lost 2SP and my health was restored but I was not teleported from the spot where I hit 0 health.

Lastly, my Ninja character is currently in Llevigar. However when I try to select my charcter, I am simply given my items and remain in the class selection box.

Edit: I escaped the box by doing /kill and respawned in Ragni. Which is unideal

**Comment by DarkDemonDragon** [comment] 2016-01-28 13:28
Duplicate of #3878 Please close this issue and follow the original.

**Closed** 2016-01-29 23:50 UTC
