### ISSUE TITLE
Dévoreuse having a corrupted name and no lore

### ISSUE THREAD

**Issue by HesitantRay2** [Wynncraft/Issues#3772] opened 2016-01-19 01:14 UTC
![](http://i.imgur.com/ouGVD3t.png)

I was killing orcs near Llevigar. This dropped. I picked it up. The name of the wand is corrupted, although do note it seems similar to Dévoreuse. So I assume they are the same. And there's also no lore. I don't know if it is at all possible to reproduce this issue, I had thought it was fixed earlier...

**Comment by Trixter313** [comment] 2016-01-19 01:57
Duplicate of #3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-19 01:57 UTC
