### ISSUE TITLE
Dungeon boss glitch

### ISSUE THREAD

**Issue by wtank** [Wynncraft/Issues#3321] opened 2015-12-29 16:32 UTC
Could a second layer of invisible wall be added to the dungeons i was in the animal dungeon and i had the boss in a corner and when i used my first combo as archer he glitched through the wall and was stuck out of the arena and now i lost a key because i had to exit and rejoin pleas fix i'm sure this has happened to other people as well.

**Comment by Trixter313** [comment] 2015-12-29 22:23
Duplicate of https://github.com/Wynncraft/Issues/issues/3191

Please direct any further comments the the original issue. Thanks!

**Closed by Trixter313** 2015-12-29 22:23 UTC
