### ISSUE TITLE
Fallback Server - Lobby Bug

### ISSUE THREAD

**Issue by PixelKiller4000** [Wynncraft/Issues#5012] opened 2016-05-17 08:37 UTC
If you join in a lobby you cant connect to a server or to the nether!!! Please help!

**Comment by YunoFGasai** [comment] 2016-05-17 10:54
try using /server 1 or /server 2, this will change your lobby (it is possible that only one lobby is bugged)

**Comment by ThunderRemix** [comment] 2016-05-18 06:01
That is the fallback server. It's bugged. :/

**Comment by Moe-Ronickah** [comment] 2016-06-03 15:04
This is my "copy and paste" answer, and it's all that I have for now.

If play.wynncraft.com isn't working for you, then try play.wynncraft.net and play.wynncraft.org.They are exactly the same server, but, for some reason, they seem to be handled differently by the main server.  It's also possible that while one isn't working NOW, it will work in 5 min.  If you are still having trouble, shut down Minecraft, wait 5 min., then try again. Sometimes, it takes 2 or 3 tries to get in, sometimes more, but you will get in.

**Comment by Moe-Ronickah** [comment] 2016-06-03 15:26
**Obviously, the game admins know about these issues and are working on them.**
**Per admin**: "Ending up on the fallback server is not a bug. Just connect to a game server like normal. If you are unable to connect to a game lobby, that's a bigger deal."  In other words, getting on the fallback server isn't a problem, it's supposed to be there.  You should be able to /server or /lobby to get to a normal game server.  The issues are that sometimes it takes a long time to get out of the fallback server and sometimes the commands to get out of there just aren't working, either.

**Comment by redxdev** [comment] 2016-06-05 05:12
Anyone having this issue, please post what version of minecraft you are using.

**Comment by redxdev** [comment] 2016-06-09 05:36
Quick update on this: still unsure what is causing it. We have made a change so the server simply disconnects you if you end up on the fallback server, instead of having you get stuck in the lobby.

**Comment by Moe-Ronickah** [comment] 2016-06-09 17:46
OK, so we should expect to see a spate of disconnection issues, and no more fallback server issues for a while.  Let's leave this issue open for a day or two and see how things go before we close it.

**Comment by redxdev** [comment] 2016-06-09 21:10
The issue still exists, it just looks different.

**Comment by redxdev** [comment] 2016-06-20 16:37
We have pushed out an update which should hopefully at least mitigate the problem. If you continue to see errors about not being able to connect to the fallback server, please let me know.

**Comment by Moe-Ronickah** [comment] 2016-06-20 17:09
:relieved:
OK, everyone, keep your fingers crossed!

**Comment by Moe-Ronickah** [comment] 2016-09-10 17:25
RESOLVED

**Closed by Moe-Ronickah** 2016-09-10 17:25 UTC

**Comment by DebugMC** [comment] 2017-02-15 15:35
@Moe-Ronickah happens to me still.
