### ISSUE TITLE
Can't Join my main class.

### ISSUE THREAD

**Issue by supermaty01** [Wynncraft/Issues#6757] opened 2016-11-23 00:51 UTC
I stopped playing minecraft like a year ago, but know I want to play again in the server.
I can join all the classes except for the archer,my main class.

When I'm at the dark box to select the class and I try the archer, It says 'There has been an error... Try again.'

(I've been trying like 30 minutes)

**Comment by LordHelmchen98** [comment] 2016-11-23 15:57
Duplicate of #5418 
Unfortunately theres no fix for that except to wipe your account. For more information read Moe-Ronickah's long post on the original thread.

**Closed** 2016-11-24 03:28 UTC
