### ISSUE TITLE
Craftmas Chaos portal entering death

### ISSUE THREAD

**Issue by Crushifix** [Wynncraft/Issues#4090] opened 2016-02-12 09:41 UTC
THIS POST SPOILS THE QUEST ''Craftmas Chaos'' YOU HAVE BEEN WARNED (sorry for caps but I think it's alright in this case :3)

When I enter the portal after killing the crystal I get teleported to the weird room where you're going to land on water. However when I land on the water I die of fall damage. I do press my space bar when I'm hitting the water, which might bug it out a bit but I have died to the same thing twice now so you might wanna fix that somehow. Thanks

Edit: I have now confirmed that even if I don't press anything, I die of fall damage

**Comment by Dar-krusos** [comment] 2016-02-12 10:51
Right... Yeah I don't think there's any water there. You're just supposed to get teleported to Future Selchar. This issue seems to be a recurring problem which doesn't teleport the player properly at times. They usually just have to patch it up (I'm not even sure if previous cases of "fixing itself" are actually patches).

**Comment by DarkDemonDragon** [comment] 2016-02-12 13:09
This is a duplicate but the original has 0 information. There's a way to deal with this depending on your class. 
With Mage spam teleport downwards to reduce the amount of blocks you actually fall. 
With Archer time an escape with the final left click when you're a block away from the ground and you'll shoot back up after that you'll be good as Archer's escape negates all fall dmg. 
With Warrior make sure you have resistance prior to teleporting and similar to Mage use charge to reduce the amount of of blocks you fall. 
With Assassin... take off all mods, but Optifine and reduce the quality of EVERYTHING and hope you don't lag when you fall... (RIP You're screwed ;-;)

**Comment by Odnod** [comment] 2016-02-12 15:01
The way this works, you are meant to be teleported away right before hitting the mouth. In moments of server lag, this does not always work and will just kill you with fall damage.

**Comment by DarkDemonDragon** [comment] 2016-02-12 15:46
I really don't get why fall damage made a comeback since many events like this all work on the basis that you don't sustain fall damage.

**Comment by Trixter313** [comment] 2016-02-12 23:18
Duplicate of https://github.com/Wynncraft/Issues/issues/3678

Please post any further replies to the original thread. Thanks!

**Closed by Trixter313** 2016-02-12 23:18 UTC
