### ISSUE TITLE
Stuck in a room near Ragni

### ISSUE THREAD

**Issue by FinnAminiKacke** [Wynncraft/Issues#7992] opened 2017-04-27 14:06 UTC
I spawned in a lobby with signs saying "yo, you died use /warp ragni" but /warp ragni is an invalid command. please help

**Comment by thecoolkogut4** [comment] 2017-04-27 14:21
Lobby as in the hub? What happens when you log out and log back in? Can you use the compass in your inventory to join a world?

**Comment by PepinhoJp** [comment] 2017-04-27 16:14
This is a bug, mods already know, will probably be fixed today!

**Comment by ColinRioux** [comment] 2017-04-27 19:49
Duplicate of #7991

**Closed by ColinRioux** 2017-04-27 19:49 UTC
