### ISSUE TITLE
Guild kick/de-ranking players

### ISSUE THREAD

**Issue by Novastar66** [Wynncraft/Issues#5467] opened 2016-07-12 14:40 UTC
If someone from a guild changes there username, the owner and or themselves can not leave the guild  with both commands /guild kick [name]  or /guild leave 

![2016-07-12_07 39 53](https://cloud.githubusercontent.com/assets/20421859/16770996/dcf1fba2-4803-11e6-908a-4bc31998a12a.png)
![2016-07-12_07 39 45](https://cloud.githubusercontent.com/assets/20421859/16771012/e847eff2-4803-11e6-9b25-2a4c470d1a3b.png)

**Comment by YunoFGasai** [comment] 2016-07-12 17:23
duplicate of issue #3665 please follow the original issue on the linked thread.

**Closed** 2016-07-13 08:27 UTC
Labels: Duplicate
