### ISSUE TITLE
"Unknown serializer type 16" disconnect when shooting mobs with bow

### ISSUE THREAD

**Issue by Andriyasdf** [Wynncraft/Issues#5038] opened 2016-05-20 23:18 UTC
When shooting a mob with a bow, I get disconnected with this error: Internal Exception: io.netty.handler.codec.DecoderException: Unknown serializer type 16. I haven't been able to figure out why it does that, but it doesn't do it every time. This started when I created a new Archer class.

**Comment by YunoFGasai** [comment] 2016-05-22 04:55
Try switching to 1.8

**Comment by Moe-Ronickah** [comment] 2016-05-22 14:36
I'm not certain that anyone knows, just yet, what the issue is, but there are several issues with spells and weapons that are come and go.  The admins know about it, and we will just have to wait until they can find the cause, and fix it.

**Comment by Trixter313** [comment] 2016-05-23 00:38
Duplicate of https://github.com/Wynncraft/Issues/issues/5017

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-05-23 00:38 UTC
Labels: Game Mechanics
