### ISSUE TITLE
Personal Bank Arrow Bug

### ISSUE THREAD

**Issue by goldenlord52** [Wynncraft/Issues#6301] opened 2016-10-01 08:45 UTC
![2016-10-01_09 38 52](https://cloud.githubusercontent.com/assets/22557947/19012961/8254b6e2-87bb-11e6-972d-3ff023fbd916.png)

In my enderchest you can see three stacks of arrows. When the archer class needed arrows in their inventory to use the class, I was shift clicking things into my inventory and accidentally put them in too. For some reason, they stayed in my inventory, but some were also created in the ender chest. Now, they won't come out. I try to remove them and they just reappear. It's taking up three spaces of my chest that I would like to use. Is there anything that can be done?

**Comment by Trixter313** [comment] 2016-10-03 01:32
Duplicate of https://github.com/Wynncraft/Issues/issues/3147

**Closed by Trixter313** 2016-10-03 01:32 UTC
