### ISSUE TITLE
Galleon's Graveyard key

### ISSUE THREAD

**Issue by mahmut4200** [Wynncraft/Issues#7267] opened 2017-01-26 17:11 UTC
one of my Galleon's Graveyard key's is different from the others, it has a strange symbol on it instead of the normal symbol (idk what you call it in english  >  '  <  )

i havent tried to use it but i'am pretty sure that it wont work
(sorry for my bad english) ( not sure if bug or if it's normal)

https://gyazo.com/ba94160868fd1d39b0011a9bc3053932

https://gyazo.com/efcd7ae195dee34c9b5f02f4ab5a9b09

**Comment by DebugMC** [comment] 2017-01-26 17:38
Duplicate of #5994 (I think I can't click the links at school) but please check for duplicates in the future!

If its not tell me tho. If you mean it says a bunch of  ໥ ໥ ໥ ໥'s(Thats intentionaly a box) or ÄÄÄ´s thats diffirent.

**Comment by Pyromanical** [comment] 2017-01-26 17:40
The broken key is the key from Beneath the Depths, but yeah, this is a dupe issue
The apostrophe is not the normal one, it's is some special character

**Comment by mahmut4200** [comment] 2017-01-26 17:46
so should i just throw it away? and can i still use it?
and yes it's the same as #5994 @DebugMC

**Comment by DebugMC** [comment] 2017-01-26 20:07
No keep it, is it usable?

**Comment by mahmut4200** [comment] 2017-01-26 20:20
that's the real question. is it usable? xD i need to check it tomorrow i dont have time now.
but thanks for the help, i'll give feedback when i try it out
again (sorry for my bad english)

**Comment by Numbermaniac** [comment] 2017-01-27 03:53
It comes from Beneath the Depths quest. I still have mine, I should try using it and see if it works.

**Comment by DebugMC** [comment] 2017-01-27 14:51
k

**Comment by Numbermaniac** [comment] 2017-01-28 00:45
Yep, the Key Collector accepted it.

**Comment by Moe-Ronickah** [comment] 2017-05-07 18:43
Your issue is a duplicate of  #5994 .  You can follow your issue on that thread.

**Closed by Moe-Ronickah** 2017-05-07 18:43 UTC
Labels: Duplicate
