### ISSUE TITLE
Small bug 

### ISSUE THREAD

**Issue by NutuCamataru** [Wynncraft/Issues#4232] opened 2016-02-23 15:34 UTC
When you enter a merchant GUI your weapons names go crazy. Like : 
![2016-02-23_17 29 01](https://cloud.githubusercontent.com/assets/17433223/13256431/68025f12-da53-11e5-8a83-367b1a29f05f.png)
![2016-02-23_17 29 03](https://cloud.githubusercontent.com/assets/17433223/13256436/6cc0db50-da53-11e5-8151-01263a758893.png)
![2016-02-23_17 29 04](https://cloud.githubusercontent.com/assets/17433223/13256441/6eff49f6-da53-11e5-89f6-d0af6142ebea.png)
 
   And (I don't have a screenshot for this) when you have an unidentified item in inventory it show you the name of the item.

**Comment by DarkDemonDragon** [comment] 2016-02-23 15:54
Duplicate of #4059 Please close this issue and follow the original.

**Closed** 2016-02-24 13:05 UTC
