### ISSUE TITLE
Broke Coding of Weapon, I have no weapon to use now.

### ISSUE THREAD

**Issue by BeeplBoop** [Wynncraft/Issues#3399] opened 2015-12-31 17:37 UTC
This has happened to me 2 times now.
![2015-12-31_11 35 00](https://cloud.githubusercontent.com/assets/16503465/12066740/88a1c224-afb2-11e5-9328-08d438b8f7de.png)
It tends to happen when I reconnect, after leaving/going to a different server.

**Comment by Trixter313** [comment] 2016-01-01 07:20
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please refer any further comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-01 07:20 UTC
