### ISSUE TITLE
Weapons can already be half identifyed without the identifyer.

### ISSUE THREAD

**Issue by ttykox59** [Wynncraft/Issues#3828] opened 2016-01-24 01:59 UTC
If you drop an item and pick it back up, the item will regain its after identification 3d model so if you know what has that model and is that level range, you know the weapon.

**Comment by Trixter313** [comment] 2016-01-24 02:35
Duplicate of https://github.com/Wynncraft/Issues/issues/3318

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-24 02:35 UTC
