### ISSUE TITLE
Duel Heal

### ISSUE THREAD

**Issue by LarryRULEZ1** [Wynncraft/Issues#2710] opened 2015-12-21 13:47 UTC
Basically, when you duel someone and lose, it puts you back to full health. So, for example, if you had one heart, dueled someone and lost, you would then have full health, not one heart.

**Comment by DarkDemonDragon** [comment] 2015-12-21 13:57
This is how they intended it to be. Please close this issue as this is not a bug.

**Closed** 2015-12-21 15:59 UTC
