### ISSUE TITLE
Health doesn't regen

### ISSUE THREAD

**Issue by DeputyMooMoo** [Wynncraft/Issues#4073] opened 2016-02-10 23:46 UTC
My health doesn't regenerate. I didn't have this problem before and i didn't switch armor or weapons or anything. I first noticed this yesterday. Please help me.

**Comment by Moe-Ronickah** [comment] 2016-02-11 01:09
Have you tried logging off, closing MC, waiting 5 minutes, then logging back on?  It usually works.

**Comment by DeputyMooMoo** [comment] 2016-02-11 01:11
Yes this happened yesterday... and it happened today so it didn't help

**Comment by Dar-krusos** [comment] 2016-02-11 06:00
What armor are you using?

**Comment by DarkDemonDragon** [comment] 2016-02-11 13:07
Check your character stats as you may have 0 or even negative health regen.

**Comment by DeputyMooMoo** [comment] 2016-02-11 15:09
But I didnt change any armor or weapons! And this didnt happen before! This just randomly happened and now my health wont regenerate. I tried wearing armor that has lots of health regen, but it doesnt help

**Comment by Trixter313** [comment] 2016-02-12 23:38
So what does it say your health regen is in the character stats, located in the compass?

**Comment by Trixter313** [comment] 2016-02-20 21:19
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!

**Closed by Trixter313** 2016-02-20 21:19 UTC

**Comment by WizKid101** [comment] 2016-03-03 13:44
ah same here too i checked my stats -12 health regen thats why im losing health or not..

**Comment by WizKid101** [comment] 2016-03-03 13:47
dang its my pants

**Comment by WizKid101** [comment] 2016-03-03 13:48
this issue really helped thanks :)
