### ISSUE TITLE
Texturepack broken.

### ISSUE THREAD

**Issue by Moogly49** [Wynncraft/Issues#3150] opened 2015-12-26 01:08 UTC
Hello, Wynn GM(s)

Today I've been having an occurring issue, whenever I log onto any of your servers the custom TP will not load. Before you say, 'Make sure your TP is enabled'/Try restarting, I've tried restarting MC, deleting your server, then re-adding it. (And it's been enabled every time.) 
Not sure what is going on or if you could fix it, but if you could, that'd be awesome.

Thanks for the help, Asplia (My IGN)

**Comment by vboyswag** [comment] 2015-12-26 01:09
I completely agree. This is a serious problem. Admins Fix it

**Comment by ToasterAmol** [comment] 2015-12-26 01:23
Yep, we already have a problem thread for this, and there are even more people with this problem. The admins are probably enjoying Christmas, but hopefully tomorrow they can fix this.

**Comment by ToasterAmol** [comment] 2015-12-26 01:26
IGN: minecraftthe1st
Just in case

**Comment by Marianol24** [comment] 2015-12-26 01:43
Try going into your .minecraft folder, and delete everything in server-resource-packs, then log back in

**Comment by Moogly49** [comment] 2015-12-26 01:46
I'll try, thanks.

**Comment by Moogly49** [comment] 2015-12-26 02:04
Nothing happened, still have the exact same problem. I'll just wait for the DEV(s).

**Comment by ToasterAmol** [comment] 2015-12-26 02:07
same here

**Comment by Moogly49** [comment] 2015-12-26 02:47
All's good. You can function w/o the texturepack, just no where near as fun.

**Comment by ToasterAmol** [comment] 2015-12-26 02:54
well it is still pretty fun, just more fun with sticks bows shovels and shears because they look like the item they are supposed to be. But if your using a unique, rare or legendary, have fun playing with a block of stone as your "wand" or "bow" etc.

**Comment by Verret001** [comment] 2015-12-26 03:00
Have you tried changing versions of minecraft?
ex. changing from 1.8 to 1.8.5

**Comment by Moogly49** [comment] 2015-12-26 03:01
Have not, I'll give it a try.

**Comment by ToasterAmol** [comment] 2015-12-26 03:15
Did not work for me

**Comment by Verret001** [comment] 2015-12-26 14:23
duplicate of https://github.com/Wynncraft/Issues/issues/3146

**Comment by ToasterAmol** [comment] 2015-12-26 15:01
Close, it works now I believe, if it still does not then go ahead and keep it open. IT works for me, so im happy :)

**Closed** 2015-12-27 21:51 UTC

**Comment by Chillydog117** [comment] 2015-12-28 15:07
I have the same problem with my resource/texture pack. I've also tried everything.

IGN: chillydog117
