### ISSUE TITLE
I'm stuck at the beginning area where you get your class and can't leave(screenshot provided)

### ISSUE THREAD

**Issue by enderzombie921** [Wynncraft/Issues#2562] opened 2015-11-26 17:22 UTC
![2015-11-26_12 21 33](https://cloud.githubusercontent.com/assets/16036463/11428334/46c31050-9438-11e5-8336-d6f5103a8a54.png)

**Comment by DarkDemonDragon** [comment] 2015-11-26 19:51
Duplicate of #1595 Please close this issue.

**Closed** 2015-11-26 20:33 UTC
