### ISSUE TITLE
Stuck in guild

### ISSUE THREAD

**Issue by Froritzic** [Wynncraft/Issues#7781] opened 2017-04-10 07:29 UTC
https://gyazo.com/bac17e98f152b50d8c8cbb8d3617b0d3 My Friend has been stuck in a guild for a very Long time

**Comment by numbermaniac** [comment] 2017-04-10 08:57
If he's changed his name, he's stuck in the guild until guilds are fixed. It's a known bug, duplicate of #3665.

**Comment by LordHelmchen98** [comment] 2017-04-10 09:49
I'm going to assume it was the name change bug as numbermaniac said, but according to the stats page both of you are not in a guild anymore so I guess the guild got disbanded. In case you create a new one you should leave the guild before changing your name and rejoin after the change.

**Closed by LordHelmchen98** 2017-04-10 09:49 UTC
