### ISSUE TITLE
Lost all armour!!!!!!!!

### ISSUE THREAD

**Issue by atz775** [Wynncraft/Issues#4541] opened 2016-03-12 23:54 UTC
So, one day I logged in. My Inventory was full. For some reason my skill points glitched and since I needed the stats for my armour, my armour was kicked off of me and disappeared. I had multiple legendaries. I forgot to take pics of my armour so it's all gone. If even though it was like 2 months ago anyone knows how I can get my stuff back _**PLEASE**_ tell me, I was working on the character for a long time!

**Comment by Troll2828** [comment] 2016-03-13 13:41
You can't get them back, Wynncraft has a strict no refund rule. You juts have to grind for more items or go on the forums and buy armor there.

**Comment by Moe-Ronickah** [comment] 2016-03-15 07:02
Duplicate of #4120 .  Please follow that issue, and comment on it, for this bug.

I'm sorry to have to tell you this, but the only way that you can get your stuff back is to either find new items, or buy replacement items.  There just is no other way.

**Closed by Moe-Ronickah** 2016-03-15 07:02 UTC
Labels: Duplicate
