### ISSUE TITLE
Decrepit Sewers Bug

### ISSUE THREAD

**Issue by MillieTheKitty** [Wynncraft/Issues#6422] opened 2016-10-19 18:56 UTC
The server restarted while we were doing the Decrepit Sewers Dungeon in WC9. We joined back on WC10 and now only one person can get through. I'm stuck in the dungeon currently on WC10.

**Comment by MillieTheKitty** [comment] 2016-10-19 19:04
I did /kill, but the bug is still present. It was after the first hopper. In the tunnel, I was stuck there.

**Comment by LordHelmchen98** [comment] 2016-10-19 19:13
Although apparently there is no solution yet this is a duplicate of #6340

**Comment by MillieTheKitty** [comment] 2016-10-19 19:14
Sorry, I didn't see the previous one. Should I take this one down?

**Comment by LordHelmchen98** [comment] 2016-10-19 19:24
No need I guess just close it. And maybe post on the other thread.

**Closed** 2016-10-19 19:35 UTC
Labels: Duplicate
