### ISSUE TITLE
Keep falling in the void and can't use commands

### ISSUE THREAD

**Issue by RiesvGeffen** [Wynncraft/Issues#4085] opened 2016-02-11 20:24 UTC
I basicly keep falling deeper and deeper in the void and I can't use any commands. So the only way to get out of here is by teleporting me on the ground! please help me! And fix this bug so noone gets it.

**Comment by Odnod** [comment] 2016-02-11 22:35
I am familiar with this bug, I do not know the exact cause but I think it happens when the server has no idea where to spawn you. It has occurred for me and I was able log into the nether and create a new class in order to fix it. No promises whether or not it work work for you though.

**Comment by DarkDemonDragon** [comment] 2016-02-12 13:15
Duplicate of #3785 Please close this and post any further comments in the original

**Closed** 2016-02-12 23:26 UTC

**Comment by TimThePvpMaster** [comment] 2016-02-18 12:05
Tried to go to the nether, wouldn't let me in. I am having this same problem.

**Comment by TimThePvpMaster** [comment] 2016-02-18 12:12
Alright, I got inside the nether, toggled the autojoin, and yet it still puts me in the box.... UGH.
