### ISSUE TITLE
Broken Wand

### ISSUE THREAD

**Issue by TheChampion879** [Wynncraft/Issues#3750] opened 2016-01-17 21:11 UTC
[img]http://i.imgur.com/dxXIxQS.png?1[/img]
What am I looking at?

**Comment by Trixter313** [comment] 2016-01-17 21:35
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-17 21:35 UTC
