### ISSUE TITLE
Cant leave my guild [GDN] Guardian

### ISSUE THREAD

**Issue by Frostlyy** [Wynncraft/Issues#8425] opened 2017-06-21 04:06 UTC
so ive asked alot of ppl and they all said to change my name back to what it was when i joined, so i did changed my name from Frostlyy -> firechainZ

but then it just wont let me leave the guild even tho i alredy have changed my name. Please help me so i can leave the guild.

**Comment by Trixter313** [comment] 2017-06-21 08:08
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

There is currently no solution, we have to wait for guilds to be revamped.

**Closed by Trixter313** 2017-06-21 08:08 UTC
