### ISSUE TITLE
Craftmas Chaos Santa Skin Broken

### ISSUE THREAD

**Issue by xXK1NGxR3APERXx** [Wynncraft/Issues#4104] opened 2016-02-13 05:10 UTC
The Santa in the christmas quest is set to the template skin that minecraft.net gives you

**Comment by Odnod** [comment] 2016-02-13 05:37
yeah it has been that way for a really long time

**Comment by Trixter313** [comment] 2016-02-13 09:37
Duplicate of https://github.com/Wynncraft/Issues/issues/4003

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-13 09:37 UTC
