### ISSUE TITLE
Item glitched?

### ISSUE THREAD

**Issue by EJCrusher** [Wynncraft/Issues#4319] opened 2016-02-27 22:04 UTC
![screenshot_24](https://cloud.githubusercontent.com/assets/17520054/13376615/80f75368-dd8e-11e5-999f-a0905e1a3fc0.png)
So yeah, this item is glitched with a thing? id code messed up, just dont know what to do honestly and it doesnt add anything and this was my only chestplate that I had? help?

**Comment by TrashcanMan** [comment] 2016-02-28 00:57
Screenshot?

**Comment by benyg2000** [comment] 2016-02-28 01:03
same thing happen to me on my chest plate called "Dragon skin"

**Comment by Moe-Ronickah** [comment] 2016-02-28 03:34
Duplicate of #3175

Please direct any future comments to the original thread. Thanks!

**Closed by Moe-Ronickah** 2016-02-28 03:34 UTC
Labels: Duplicate
