### ISSUE TITLE
Armour Disappeared

### ISSUE THREAD

**Issue by Abstertales** [Wynncraft/Issues#4529] opened 2016-03-12 08:25 UTC
# Delete this line if you've searched for a duplicate issue first
I haven't been able to find another problem like this but when I finished the House of Twain quest it lagged and I had to log out, when I came back on I had lost my chest plate and leggings

**Comment by DarkDemonDragon** [comment] 2016-03-12 23:28
When you came on was there red text saying something like:
"Chestplate requires a Dexterity of 10"
"Leggings requires an Intelligence of 15"

If you are not sure then please check your logs. If you are not sure what I mean by that check out the Logs section of my Evidence thread.
LINK: https://forums.wynncraft.com/threads/evidence-ban-reports-bug-reports-etc.116166/

**Comment by Abstertales** [comment] 2016-03-13 03:20
It does have that, is there anyway of getting them back though? Do I just have to get the right amount of skill points

**Comment by DarkDemonDragon** [comment] 2016-03-13 13:51
Sorry once you've lost an item there's nothing that can be done. Wynncraft has a strict no-refunds policy. All you can do is be aware of bugs so that you know how to deal with them and make sure to take the necessary precautions. I actually have a thread all about bugs here that I'm working on at the moment. Feel free to check it out to familiarize yourself with bugs. 

Anyways since it did have the text than this is a duplicate of #4120 Please close this issue a follow the original.

**Comment by Moe-Ronickah** [comment] 2016-03-13 16:23
duplicate of #4120

**Closed by Moe-Ronickah** 2016-03-13 16:23 UTC
