### ISSUE TITLE
Endlessly falling to the void

### ISSUE THREAD

**Issue by ghoster25** [Wynncraft/Issues#3834] opened 2016-01-24 04:33 UTC
I make it to the hub then i try to connect so i can pick my character and i glitch threw the floor and fall endlessly and i can not select my character.

**Comment by Trixter313** [comment] 2016-01-24 07:38
Duplicate of https://github.com/Wynncraft/Issues/issues/3521

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-24 07:38 UTC
