### ISSUE TITLE
cant get to bugged chest

### ISSUE THREAD

**Issue by yairkaraso** [Wynncraft/Issues#3287] opened 2015-12-28 18:26 UTC
I found a chest close to almuj that u cant reach in house but u can see the effects of the little stars that jump when loot chest, i checked top from inside and from outside.
![2015-12-28_20 23 04](https://cloud.githubusercontent.com/assets/16417060/12023337/2532bc74-ada1-11e5-8c83-ef4bc0f6164f.png)
![2015-12-28_20 22 04](https://cloud.githubusercontent.com/assets/16417060/12023338/2dcb44f0-ada1-11e5-9993-e4c8832c9bbc.png)
![2015-12-28_20 21 37](https://cloud.githubusercontent.com/assets/16417060/12023347/3457a49e-ada1-11e5-9187-eb14dae47e74.png)

**Comment by Verret001** [comment] 2015-12-28 18:38
duplicate of https://github.com/Wynncraft/Issues/issues/3192

**Closed** 2015-12-28 19:19 UTC
