### ISSUE TITLE
The Ultimate Weapon

### ISSUE THREAD

**Issue by felipeargoll27** [Wynncraft/Issues#4353] opened 2016-02-29 13:04 UTC
I've tried for a long time to get the 50 soft whetstones necessary for the quest, but it seems that the spawn of them is in trouble . I've already tried changing server.
 Here is some images:
![2016-02-29_09 55 15](https://cloud.githubusercontent.com/assets/17198072/13395145/af019136-decb-11e5-9e95-12d3e2dca7f6.png)
![2016-02-29_09 55 44](https://cloud.githubusercontent.com/assets/17198072/13395148/b6bc871e-decb-11e5-9edf-c0a9f0aec2db.png)
![2016-02-29_09 56 09](https://cloud.githubusercontent.com/assets/17198072/13395151/bcb9492c-decb-11e5-9bb3-fd5c76102620.png)
 Note: The axe in my hands is the bloodied hatchet

**Comment by Moe-Ronickah** [comment] 2016-02-29 21:04
Duplicate of Quest Items Are Not Spawing #4236 .  Please refer all future comments to the original thread.

**Closed by Moe-Ronickah** 2016-02-29 21:04 UTC
Labels: Duplicate
