### ISSUE TITLE
Из-за проблем с интернетом 

### ISSUE THREAD

**Issue by cobbbros** [Wynncraft/Issues#5273] opened 2016-06-21 14:00 UTC
Due to problems with the Internet when I get off the horse I was kicked from server for flying

**Comment by Trixter313** [comment] 2016-06-21 14:02
Duplicate of https://github.com/Wynncraft/Issues/issues/5234

Phase follow the instructions given to you there.

**Closed by Trixter313** 2016-06-21 14:02 UTC
