### ISSUE TITLE
I can't indentifi my itens anymore

### ISSUE THREAD

**Issue by Kacyqui** [Wynncraft/Issues#3599] opened 2016-01-08 05:41 UTC
![2016-01-08_03 40 02](https://cloud.githubusercontent.com/assets/16604983/12191258/98d65c60-b5b9-11e5-806d-8378ab847aad.png)
![2016-01-08_03 40 15](https://cloud.githubusercontent.com/assets/16604983/12191259/9cd22e2a-b5b9-11e5-83e2-afbf504556ac.png).
It appers this,

**Comment by TrashcanMan** [comment] 2016-01-08 07:27
Yeah, it's a known issue of some sort, it should be sorted out very soon.

**Comment by Trixter313** [comment] 2016-01-09 13:12
Duplicate of https://github.com/Wynncraft/Issues/issues/3594

Please direct any further comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-09 13:12 UTC
