### ISSUE TITLE
V.S.S Seaskipper Boat Pass is Bugged

### ISSUE THREAD

**Issue by Quike100** [Wynncraft/Issues#6684] opened 2016-11-14 00:35 UTC
My **seasail boat pass** is not working. When I buy a pass to go to selchar and I drop it in the hopper, I get teleported into the boat but then the dialogue doesn't appear and I am not teleported to Selchar, I think that is bugged (considering other people have no issues.

**Comment by Rellia** [comment] 2016-11-14 20:15
click the button under the clock

**Comment by Quike100** [comment] 2016-11-14 20:49
still not working, i click it but nothing happens, i think that the bug is
in the captain, because he didn't say me nothing when i try to talk with him

2016-11-14 21:15 GMT+01:00 Rellia <notifications@github.com>:

**Comment by Moe-Ronickah** [comment] 2016-11-17 02:53
Duplicate of #6389

**Closed by Moe-Ronickah** 2016-11-17 02:53 UTC
Labels: Duplicate
