### ISSUE TITLE
soul points

### ISSUE THREAD

**Issue by mybutt** [Wynncraft/Issues#4198] opened 2016-02-20 20:01 UTC
i had 11 soul points then i died in the skeleton dungeon then i lost all my stuff plz help me get my stuff back or something about plz

**Comment by Trixter313** [comment] 2016-02-20 20:54
Duplicate of https://github.com/Wynncraft/Issues/issues/3821

Unfortunately due to Wynncraft's strict no refunds policy, there's nothing we can do about the lost items but we are working on fixing the issue that items are dropped even when they shouldn't be. Ask around and some people might be willing to give you some items.

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-20 20:54 UTC

**Comment by mybutt** [comment] 2016-02-20 20:58
Ok
