### ISSUE TITLE
Strange Death

### ISSUE THREAD

**Issue by Arrow25** [Wynncraft/Issues#4144] opened 2016-02-15 19:09 UTC
I had 5 soul points and I went after a loot chest and died, I lost all my items and went back to find them but they weren't there  when I checked to get them and I spent a lot of time to get the items that I lost and I don't think it was fair to lose items when I shouldn't of lost them in the first place. I have a recent screen shot of my items luckly

**Comment by GlitchDoesMC** [comment] 2016-02-15 20:35
We're sorry, but Wynncraft has a strict no-refund policy. If you were a low level, you can get your items back easily.

**Comment by ecwarriorz** [comment] 2016-02-16 01:36
Wait, you lost all 5 soul points after dying once?

**Comment by HeyloLP** [comment] 2016-02-16 08:51
Duplicate of #3821 

Please direct any future comments to the original thread. Thanks!

**Comment by Arrow25** [comment] 2016-02-17 23:55
The Divide is not a easy weapon to get back, thanks for the information though

**Closed** 2016-02-18 12:07 UTC
