### ISSUE TITLE
Hourglass sand not spawning

### ISSUE THREAD

**Issue by iceswordluma** [Wynncraft/Issues#4264] opened 2016-02-25 05:35 UTC
The hourglass sand in Selchar does not spawn, rendering the sister city quest impossible. When you go to the hourglass, no sand spawns anywhere on any server.

**Comment by iceswordluma** [comment] 2016-02-25 06:01
Nor do the sunflower seeds seem to be spawning for Aldorei's Secret Part I in Aldorei valley.

**Comment by Odnod** [comment] 2016-02-25 06:12
duplicate of #4236, please close this post and put and additional comments on the original topic.

**Closed** 2016-02-25 06:18 UTC
