### ISSUE TITLE
Hub Glitch

### ISSUE THREAD

**Issue by GraGra008** [Wynncraft/Issues#5609] opened 2016-07-29 07:56 UTC
There is a large glitch in  the lobby, I don't know wether it is personal or for many people, but I have not seen a report on this. However it is a glitch and it is that the sever reports me for flying in the hub and then reloads my minecraft to put me back on the sever again reapting this process again and again. This glitch is lagging my computer and, unless I use Ctrl Alt delete it just will continue forever. Another thing is usualy happens again when I use the task manager to close itand then open minecraft again and retry. But this is happening more often now and now I can almost never got onto my favorite server. 
Please fix this glitch soon so I can play again.
GraGra008

**Comment by Trixter313** [comment] 2016-07-29 08:05
What version of Minecraft are you using to play Wynncraft? We recommend 1.8.9 right now and using anything higher is at the user's own risk.

Also, this appears to be a duplicate of https://github.com/Wynncraft/Issues/issues/5289

**Closed by Trixter313** 2016-07-29 08:05 UTC
