### ISSUE TITLE
Guild Xp is not working.

### ISSUE THREAD

**Issue by RubixTitan** [Wynncraft/Issues#3962] opened 2016-02-02 09:13 UTC
I am the leader of a guild called Crimson Shield. Recently an admin told me it takes time for the xp to come but it hasn't came for 2 days. I am not so sure if it gives xp to the guild but just does not show up or if it is completely broken for me. Please help me be able to see the xp I have donated, all it says is zero even when I contribute on 100% guild xp it would say 0. Please help.

From Rubix Titan.

**Comment by Trixter313** [comment] 2016-02-02 12:11
Duplicate of https://github.com/Wynncraft/Issues/issues/3936

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-02 12:11 UTC
