### ISSUE TITLE
Arrows stuck in enderchest

### ISSUE THREAD

**Issue by helldwarfskid** [Wynncraft/Issues#4918] opened 2016-04-30 07:26 UTC
I have 2 stacks of arrows stuck in my enderchest from when the archer class had them in their inventory, how can I get rid of them. There is still code that doesn't let me move them and so if anyone could help I would be grateful.

**Comment by helldwarfskid** [comment] 2016-04-30 07:26
![2016-04-27_18 26 46](https://cloud.githubusercontent.com/assets/18748785/14934594/36086eb4-0ead-11e6-9033-d49a83631b85.png)

**Comment by Trixter313** [comment] 2016-04-30 07:32
Duplicate of https://github.com/Wynncraft/Issues/issues/3147

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-30 07:32 UTC
