### ISSUE TITLE
Animal Dungeon boss stuck out of boundaries

### ISSUE THREAD

**Issue by Arthur1221000** [Wynncraft/Issues#5564] opened 2016-07-24 04:04 UTC
I was doing the animal dungeon, and whenever I got to the boss fight and killed the boss he respawned, I killed him 5x and nothing, by the 6th time I recorded him out of boundaries (lost a crap ton of potions for those 5 kills lol)
https://www.youtube.com/watch?v=xyqVW_PO2Co

**Comment by sammyvsparks** [comment] 2016-07-24 07:35
This is a known issue by many people that he can glitch out of the walls, try to keep him out of corners or and don't hit him into walls.

**Comment by Moe-Ronickah** [comment] 2016-07-24 08:10
Duplicate of #3191 .  A search for "animal dungeon boss" would have found the first report.

**Closed by Moe-Ronickah** 2016-07-24 08:10 UTC
Labels: Duplicate
