### ISSUE TITLE
grave mistake stuck

### ISSUE THREAD

**Issue by trey1029** [Wynncraft/Issues#7395] opened 2017-02-18 04:02 UTC
when  twain wants to show me wht he saw i get stuck in front of the house, i wanted to know if this was only me and if someone could get me unstuck

**Comment by trey1029** [comment] 2017-02-18 04:12
i just b/ killed but it could still bug out

**Comment by ColinRioux** [comment] 2017-02-18 04:40
Duplicate of:
#6730
#7373

Based on what you are describing, your issue is very similar to the issues #6730 and #7373. Frankly, the whole system needs to be reworked.

**Closed by ColinRioux** 2017-02-18 04:40 UTC
