### ISSUE TITLE
Guild Bug

### ISSUE THREAD

**Issue by NightyIO** [Wynncraft/Issues#6506] opened 2016-10-29 17:51 UTC
So, I started to play WynnCraft again. After some Time my friend created a Guild and I tried to join and failed because of my old Guild. I tried to leave the Guild about 4 Times. Every Time it didn't succeeded. I joined the Guild before the Gavel Update. with my old Name (HyperionGames). It would be nice if you could delete me from the Guild.

With kindly regards,
NightyIO

**Comment by ColinRioux** [comment] 2016-10-29 19:25
If you changed your name while in your guild, unfortunately you will be unable to leave. It's a current known bug, and unfortunately it hasn't been prioritized. Sorry for the inconvenience.

**Comment by Trixter313** [comment] 2016-10-30 04:08
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

**Closed by Trixter313** 2016-10-30 04:08 UTC
