### ISSUE TITLE
Upsetting new Update.

### ISSUE THREAD

**Issue by DeliciousPiggey** [Wynncraft/Issues#5285] opened 2016-06-23 03:52 UTC
So this prntscr should show my issue: http://prntscr.com/bjuiyl

That being said the moderator is no longer a moderator and I still need help with my problem.

**Comment by Trixter313** [comment] 2016-06-23 04:12
The skill points part is in the forums, in the news section. It's best if when coming back after a break you read up on the changes made to prepare yourself.

The items disappearing is a duplicate of #3153 

Unfortunately Wynncraft has a strict no refunds policy so we can't reset your points or give you items. We are working on fixing the armor issue so it doesn't happen again but until we do, try to keep enough empty inventory spots to hold your armor in case it pops off again. It only disappears when there's no more room.

As for the points, you can either get lower level armor that you can use and build up enough soul points to wear your current armor or you can get a skill reset scroll by doing the quest, ”Tower of Amnesia”

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-06-23 04:12 UTC
