### ISSUE TITLE
I cant freaking leave my guild i lost 10 sp now 

### ISSUE THREAD

**Issue by WynnMaster69** [Wynncraft/Issues#4576] opened 2016-03-17 15:50 UTC
Hey i joined a guild but then a few days later me and my friend though pf making our own guild so i went to Cinfras and talked to the "Guild Master" and he says "You need to leave your current guild before making a new one Type /guild leave" So i typed /guild leave then this sign comes up like "Type yes to confirm that your leaving the guild" so im like ok i typed yes and lost 3 soul points but i didnt leave the guild so i tried again and i still lost soul points but i didnt leave it. So if someone can move me out of that guild or something that would be great.

**Comment by Trixter313** [comment] 2016-03-17 16:05
Have you changed your name recently? =)

**Comment by WynnMaster69** [comment] 2016-03-17 17:18
No dont think so i bought this account a few days ago

**Comment by Odnod** [comment] 2016-03-21 17:43
Did you just buy minecraft premium a few days ago? or did you buy the account from someone else. Also you seem kind of unsure whether or not you changed your name. When you first got the account, was the username the same as it is now? Sorry about the blunt question, but this bug is being caused by name changes while in a guild and it would be important to know if it is being caused by something else as well.

**Comment by DarkDemonDragon** [comment] 2016-03-23 12:30
How did you make an account a few days ago, find Wynncraft, make friends, join a guild, and then have enough resources to start your own guild? o.O

**Comment by Trixter313** [comment] 2016-04-05 04:56
I checked [here](https://namemc.com/s?WynnMaster69) and it does apper that the name on that account has been changed quite a bit, making this a duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-05 04:56 UTC

**Comment by WynnMaster69** [comment] 2016-04-07 16:23
What do you mean?

2016-03-23 13:30 GMT+01:00 DarkDemonDragon <notifications@github.com>:

**Comment by Xzyle5** [comment] 2016-04-12 08:41
Does it Work if i Change it back to the Original Name?

**Comment by Trixter313** [comment] 2016-04-12 10:47
You can try that but there's no guarantee. If you do try it, please report back here whether it works or not to help others in this situation. Thank you!

**Comment by Xzyle5** [comment] 2016-04-13 07:27
okay i will try it

**Comment by Xzyle5** [comment] 2016-04-14 09:38
It doesn't work
