### ISSUE TITLE
Assassin Spin Attack

### ISSUE THREAD

**Issue by Ninjazzzzzz** [Wynncraft/Issues#5936] opened 2016-08-31 03:01 UTC
So when using the assassin spin attack twice in succession, it will give the effects onto you.
It's hard to explain, so here's a gif.
[link](https://i.gyazo.com/a86eb07156496cc859bb84da825e1c88.gif)

**Comment by Trixter313** [comment] 2016-09-03 13:45
Duplicate of https://github.com/Wynncraft/Issues/issues/5750

**Closed by Trixter313** 2016-09-03 13:45 UTC
