### ISSUE TITLE
Guild Issue

### ISSUE THREAD

**Issue by maple3142** [Wynncraft/Issues#6909] opened 2016-12-16 13:49 UTC
[myguild](https://wynncraft.com/stats/guild/LogHorizon)
My id is **"maple3142"**, I am a member in this guild.
But I **can't see myself in the guild list** and I can't see guild chat(/g), but I still have permission to use guild command(list,stats......).
And **"Aragorn3019"**  use 2 space in guild.
**"Lunatic_Steve"** couldn't be kicked.

**Comment by LordHelmchen98** [comment] 2016-12-16 14:16
What happens if you do /guild leave?
The issue with Aragorn is well known and caused because he has changed his name while being in the guild. Also Duplicate of #3665.
For Lunatic_Steve I dont know. He has changed his name today. Also are you related to him in any way? Before he changed his name to Lunatic_Steve, his name was maple3142 as well and he had some names ending with 3142 just like you.

**Comment by maple3142** [comment] 2016-12-16 15:17
I do **/guild leave** and I lost 3 soul, but I couldn't leave the guild to rejoin.
**Lunatic_Steve** is my friend's account, before change to **miku3142** he can't be kicked by GuildLeader, so he try to change id for test.

**Comment by LordHelmchen98** [comment] 2016-12-16 15:42
There is a chance to fix it by changing the name to the one he had when he joined the guild. But apparently he joined with the ign Lunatic_Steve so I don't know what's the issue for him.
However guilds are very broken and will hopefully be fixed soon.
Until they are fixed I'm afraid you have to accept your situation and be patient as there are lots of other players with the same problem or similar problems and so far nobody found a solution for it. :/

**Comment by thecoolkogut4** [comment] 2016-12-16 19:34
everytime you change your name in a guild, is a extra message in chat and one step farther from leaving them guild. with the issue you posted there is nothing that you or anyone else can currently do to fix it

**Comment by maple3142** [comment] 2016-12-17 01:08
Isn't wynncraft guild system use **UUID**?

**Comment by LordHelmchen98** [comment] 2016-12-17 10:21
HonestlyI have no idea if they are using UUIDs and why it's not working, I just can tell guilds are broken terrifically and you are not alone with your issue. Unfortunately you have to be patient until guild get fixed.

**Closed** 2016-12-17 13:41 UTC
