### ISSUE TITLE
Ocean mini-dungeon door not opening

### ISSUE THREAD

**Issue by Bathysmal** [Wynncraft/Issues#2087] opened 2015-07-12 13:28 UTC
Hey, I recently discovered the ocean mini-dungeon at -600x / -3400z and I was really intrigued because the spawn rates are great so it's a very nice place to grind, but the door at the end (the door to get into the room before the boss (kraken)) NEVER opens. On average, after I input the correct combination (allowing the water to get to the ice), it takes anywhere from 15-100 tries to get the door open. This issue is extremely annoying and it would be great if you guys could fix it somehow. (I was going to record myself trying to open the door un-successfully, but now I received the glitch where I can't join any worlds, so no recording today...)

**Comment by Moe-Ronickah** [comment] 2015-07-12 15:32
This is a duplicate of #1783 .  The redstone circuit system that the puzzle relies upon, is not stable and does not always work.  At least some of the staff is aware of this, and, hopefully, it will be fixed, *soon*.

Would you kindly close this, as it is a duplicate?  Thanks!  Enjoy playing WynnCraft.

**Closed** 2015-07-12 16:26 UTC
