### ISSUE TITLE
Bob's Tomb Falling through floor.

### ISSUE THREAD

**Issue by Godoiiz** [Wynncraft/Issues#7823] opened 2017-04-12 03:42 UTC
I was in Bob's Tomb waiting for a friend. The part where Batelu is.. My friend doesn't join to help me defeat bob so i log out and come back the next day. I get stuck in the ground so i decide to pull my horse out and sit on it but instead of getting above the ground me and my horse fall straight into the void. Please fix! I know its not much of a bug but you still loose Soul Points!
![2017-04-12_04 34 03](https://cloud.githubusercontent.com/assets/27326862/24940274/0c41cbc2-1f3a-11e7-98fa-0080c5d696ed.png)
Its not a clear image because you cant see the bottom of the tomb but i did fall out. Now i have to find someone else to help me open the tomb which is wasting someones time :( Thanks anyways!

**Comment by numbermaniac** [comment] 2017-04-12 08:36
Duplicate of #7816. Large holes are currently present everywhere due to chunk errors. See that issue for more info.

**Comment by LordHelmchen98** [comment] 2017-04-12 15:17
From the picture I cant really see if thats actually related to #7816 and as you said you were falling into the void I assume not. However you will still have to do `/kill`. If you can manage to find people who can help you get into the tomb you may ask me if you see me ingame. Ign is `Lord_He1mchen`.

**Closed by LordHelmchen98** 2017-04-12 15:17 UTC
