### ISSUE TITLE
Old Weapon bug?

### ISSUE THREAD

**Issue by Navilence** [Wynncraft/Issues#3684] opened 2016-01-14 07:04 UTC
With the new update and all, I understand that weapons and armors now have to be reidentified in order to be used to there full potential. I got everything identified, except my old spear Fierte. I looked it up in the item guide and it still seems to be an item, now with new stats, yet it still has the sprite of a regular spear, it shows the old stat format on it, and I cannot identify it, as the identifier claims it isn't a legendary weapon. It pretty much isn't a weapon if I try to use it, I can't even use skills while holding it.

https://gyazo.com/76c15940e7c645141ee0b2ee3a9fb3f7

**Comment by TrashcanMan** [comment] 2016-01-14 07:05
Known issue (though I forget which one it's a duplicate of), all weapons with accented characters are really broken right now.

**Comment by stangefall** [comment] 2016-01-14 18:05
it is broken since the rollback that the server did
![2016-01-10_17 38 08](https://cloud.githubusercontent.com/assets/16395360/12332962/9930c316-bad8-11e5-9158-0e52bb0db49c.png)
![2016-01-10_17 40 16](https://cloud.githubusercontent.com/assets/16395360/12332961/992a34c4-bad8-11e5-8930-4192455e11c7.png)
![2016-01-10_18 05 55](https://cloud.githubusercontent.com/assets/16395360/12332963/99315592-bad8-11e5-936f-0990188e75be.png)

**Comment by stangefall** [comment] 2016-01-14 18:12
i just go on and found this other weapon that is corrupted
![2016-01-14_16 09 00](https://cloud.githubusercontent.com/assets/16395360/12333135/962aae88-bad9-11e5-8773-b27147dcaf48.png)
![2016-01-14_16 09 02](https://cloud.githubusercontent.com/assets/16395360/12333134/9627f7e2-bad9-11e5-946f-9aaecb084f8b.png)

**Comment by Dar-krusos** [comment] 2016-01-14 22:19
Yeah, like the person said above, all items with accented (and other special) characters in their name are bugged right now. These include items such as Montéfioré, Ik-El-Vän and Fiertè.

Accent (including umlauts, etc.): a symbol above or below a letter

**Comment by Trixter313** [comment] 2016-01-15 01:53
Duplicate of https://github.com/Wynncraft/Issues/issues/3161

**Closed by Trixter313** 2016-01-15 01:53 UTC
