### ISSUE TITLE
Am... impossible pants

### ISSUE THREAD

**Issue by KartfahrerLP** [Wynncraft/Issues#3761] opened 2016-01-18 14:36 UTC
I became pants which are impossible because 
1. thery Name is Damassýy+"(impossible Y)ýy+(impossible Y)
2. i can only see their Name if i wanna use them/Holding in my Hand
3. the Picture... and if i wear them they do nothing

Thanks
![2016-01-18_15 34 57](https://cloud.githubusercontent.com/assets/16760714/12393949/253fc5fa-bdf9-11e5-892b-a659d042e34d.png)
![2016-01-18_15 35 03](https://cloud.githubusercontent.com/assets/16760714/12393948/2536291e-bdf9-11e5-9f94-4adda1431b76.png)

**Comment by Trixter313** [comment] 2016-01-18 15:47
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-18 15:47 UTC
