### ISSUE TITLE
1.8.9 Texture Bugs

### ISSUE THREAD

**Issue by RedLogicP** [Wynncraft/Issues#7411] opened 2017-02-20 23:52 UTC
Most people seem to experience bugs when they play the server in 1.9+, however, in 1.8.9 I experience texture bugs such as Gear Skins not working: 
![2017-02-20_18 48 29](https://cloud.githubusercontent.com/assets/24531217/23145618/b48dfcb6-f79d-11e6-9729-7069bc7a45f5.png)
![2017-02-20_18 48 16](https://cloud.githubusercontent.com/assets/24531217/23145622/bb703ddc-f79d-11e6-9a20-5d2e53597591.png)

**Comment by Pyromanical** [comment] 2017-02-21 00:06
Gear skins don't work in 1.8.9.  Nothing can be done about it, that is just how Minecraft works.  If you want to see the gear skins use 1.9+
Also, this is a duplicate of a ton of issues.

**Comment by ColinRioux** [comment] 2017-02-21 01:32
This isn't really an issue, gear skins are a feature for minecraft versions 1.9 or higher. Until the rest of Wynncraft is ported up to 1.8.9, gear skins and other exclusive 1.9+ features will not function properly.

**Closed by ColinRioux** 2017-02-21 01:32 UTC
