### ISSUE TITLE
Purple And Blue

### ISSUE THREAD

**Issue by felipeargoll27** [Wynncraft/Issues#4356] opened 2016-02-29 13:56 UTC
I don't get the Magical Fragment when I entered in the purple and blue meteor cave, probably because my inventory was full (or maybe not). Please help

**Comment by Jenoma** [comment] 2016-02-29 15:23
Got the same bug. Every item that should fall , is not falling to the ground

**Comment by Moe-Ronickah** [comment] 2016-02-29 21:01
Duplicate of Quest Items Are Not Spawing #4236 .  Please refer all future comments to the original thread.

**Closed by Moe-Ronickah** 2016-02-29 21:01 UTC
Labels: Duplicate

**Comment by Sonicmaster418** [comment] 2016-03-01 15:51
They must fix it

**Comment by Sonicmaster418** [comment] 2016-03-01 15:51
I literally can't do any quest
