### ISSUE TITLE
Missing Quest Item! Fix Quests command doesn't give it back!

### ISSUE THREAD

**Issue by Gu1n3a** [Wynncraft/Issues#5743] opened 2016-08-15 16:09 UTC
So yesterday, I was doing to "The Lost" quest. That is the one you have to deliver the letters to the people who got separated in the group. When I started the quest, I only got four letters. I am missing the fifth one. Forget who's letter but I know where the guy is. Of course, I said ok, no big deal, I will just do /fixquests but that only gave me 2 purple shards from the wynncraft excavation quest series. For some reason, I got like 35 of those now. Different issue. But anyways, I am missing a letter for someone special and /fixquests isn't giving it to me so I can't finish this quest. Please, any help is appreciated.

**Comment by Trixter313** [comment] 2016-08-16 02:31
What does it say in your quest book for the quest?

**Comment by Gu1n3a** [comment] 2016-08-16 02:46
It says find the last missing member of Dejol's crew. I have lready found him but since I don't have his letter for some reason, I can not progress in the quest. When I go to him he says to try to look up to find the flags.

**Comment by Moe-Ronickah** [comment] 2016-08-17 06:05
Duplicate of #5237

**Closed by Moe-Ronickah** 2016-08-17 06:05 UTC
Labels: Duplicate

**Comment by Gu1n3a** [comment] 2016-08-18 02:16
Ok, now I know that. Thank you! I guess I will sit back, relax, and let Salted take his course!
