### ISSUE TITLE
Won't let me join my friend's guild..

### ISSUE THREAD

**Issue by Doolys** [Wynncraft/Issues#4972] opened 2016-05-11 22:05 UTC
Whenever my friend invites me to the guild it gives them a message saying 'Doolys is already in a guild'  when i'm not in one.. I was in a guild before then I left to join theirs. I've been waiting for about 3 weeks now (maybe it needed to update or something) but it still gives the same message. Today I created a new guild and then left it to see if that fixed the problem, which it didn't. I don't know what the problem is but this is getting very annoying. If anyone has any info on how to fix this it'd be greatly appreciated.
(Also I haven't changed my name in 3-4 months so that probably has nothing to do with it.)
![guild1](https://cloud.githubusercontent.com/assets/19315188/15197984/8fb33216-17a2-11e6-9966-7b411635d80c.png)
![guild2](https://cloud.githubusercontent.com/assets/19315188/15197987/92c65b86-17a2-11e6-9de9-ae921357716d.png)

**Comment by Trixter313** [comment] 2016-05-12 11:16
I see that you've changed your name on March 8th, making this a duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-05-12 11:16 UTC
