### ISSUE TITLE
I'm stuck in the ground

### ISSUE THREAD

**Issue by Mrtenz** [Wynncraft/Issues#4531] opened 2016-03-12 13:24 UTC
I used the teleporter after collecting a purple crystal shard for the quest WynnExcavation Site B, now I'm stuck in the ground.

Would be great if someone could help me to get out of here:
![Help](http://g2f.nl/00plns1)

In game name is Mrten.

**Comment by DarkDemonDragon** [comment] 2016-03-12 23:18
Duplicate of #4512 
Thanks for the picture mind reposting that on the original and then closing this?
Also, if you're still stuck there just do /kill and you'll be sent to the nearest town.

**Closed** 2016-03-13 00:36 UTC
