### ISSUE TITLE
quest bug 

### ISSUE THREAD

**Issue by Jolerty** [Wynncraft/Issues#4262] opened 2016-02-25 00:29 UTC
When In quest progress minecraft just crash and quest bug. I can abandon this quest and clear him again ? 

![image](https://cloud.githubusercontent.com/assets/17461446/13305872/d4971448-db6f-11e5-937f-88af12b9ff4d.png)

![image](https://cloud.githubusercontent.com/assets/17461446/13305880/de61fcb8-db6f-11e5-8964-d4f55ee4dcb3.png)

**Comment by Odnod** [comment] 2016-02-25 01:27
Go to the nearby hive of rats and give him the golden ring.

**Comment by Jolerty** [comment] 2016-02-25 16:04
I cant give him golden ring i have 3

**Comment by Odnod** [comment] 2016-02-25 16:11
Did you go into the nearby cave and kill the giant rat?

**Comment by Jolerty** [comment] 2016-02-26 01:43
all right i clear him but i have new problem I cant drop  saccharum from spider cave

**Comment by Moe-Ronickah** [comment] 2016-02-26 02:04
Your new issue is a duplicate of #4236.  Please follow this issue there.

**Closed by Moe-Ronickah** 2016-02-26 02:04 UTC
Labels: Duplicate
