### ISSUE TITLE
WynncraftExcavation Cite B Bug

### ISSUE THREAD

**Issue by skyguy6626** [Wynncraft/Issues#4474] opened 2016-03-06 06:33 UTC
The dude right before the crystals keeps repeating his dialogue then there is no crystals spawning.

**Comment by Odnod** [comment] 2016-03-06 07:28
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-06 07:48 UTC
