### ISSUE TITLE
Server restart makes armor glitch out

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#4469] opened 2016-03-05 23:48 UTC
I had a little "accident" when the servers restarted. I was selling items, and when the servers opened again my chestplate and leggings weren't on, like they were before the restart. This glitch made me sell my Evalach golden leggings, which is really sad. I managed to save my chestplate. I hope someone could give me those leggings back and fix that glitch. Thanks for reading this.

**Comment by Trixter313** [comment] 2016-03-06 20:58
Duplicate of https://github.com/Wynncraft/Issues/issues/4120

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-06 20:58 UTC
