### ISSUE TITLE
WynnExavation Side C Quest

### ISSUE THREAD

**Issue by ItsYourPlay** [Wynncraft/Issues#4271] opened 2016-02-25 15:04 UTC
I do the Quest WynnExcavation Side C and i go through the portal behind the giant red crystal and as i want to finish the quest Excavator Placardus say: The Purple Crystal Shard from WynnExavation Side B is required to start the Quest, but i stardet it for 2-5 minutes and i can't finish the Quest pls help me i don't know what i can do

**Comment by ItsYourPlay** [comment] 2016-02-25 15:04
And in my Quest book is written down Report back to Exavator Placardus

**Comment by ItsYourPlay** [comment] 2016-02-25 15:05
Here is a screen shot 
![2016-02-25_15 12 04](https://cloud.githubusercontent.com/assets/17165969/13323400/95883286-dbd9-11e5-88d1-814ea0cd8a8d.png)

**Comment by Odnod** [comment] 2016-02-25 15:46
Try going back through the whole quest.

Sometimes when doing a quest, you can jump over or miss major regional checkpoints, which can cause this issue.

**Comment by Moe-Ronickah** [comment] 2016-02-26 02:04
From the Wiki:
"Stage 7
    Explore the depths of the volcano
Stage 8
    Escape the volcano with the crystal shard"
Do you have the crystal shard from the volcano?

**Comment by Dar-krusos** [comment] 2016-02-26 05:50
You should have the _Red_ Crystal Shard to complete the quest, not the Purple Shard. Recently, we've been getting complaints about people not being able to complete the quest, when it all it was was that they had the wrong shard.

**Comment by ItsYourPlay** [comment] 2016-02-26 13:21
The Red Crystal Shards don't spawn/drop.

**Comment by Moe-Ronickah** [comment] 2016-02-26 14:02
Duplicate of #4236 .  Please follow that issue for further information.

**Closed by Moe-Ronickah** 2016-02-26 14:02 UTC
Labels: Duplicate
