### ISSUE TITLE
Kelight's Toothbrush wand

### ISSUE THREAD

**Issue by ZeeLeoNardo** [Wynncraft/Issues#4683] opened 2016-03-28 00:32 UTC
The Kelight's toothbrush wand dose not have a texture could you please fix it :D ? it looks cooler to play with a wand not a half stone brick haha. Thank you

**Comment by Trixter313** [comment] 2016-03-28 02:25
Duplicate of #4548 
Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-28 02:25 UTC
