### ISSUE TITLE
for some reason when i pick my mage class i spawn in the black thing where u pick ur character and i cant get out

### ISSUE THREAD

**Issue by sonamars05** [Wynncraft/Issues#2220] opened 2015-08-18 21:20 UTC

**Comment by Trixter313** [comment] 2015-08-18 22:02
Duplicate of https://github.com/Wynncraft/Issues/issues/2221

We recommend closing the duplicate and following the original. Thanks!

**Closed** 2015-09-11 19:57 UTC
