### ISSUE TITLE
Guild Leave

### ISSUE THREAD

**Issue by Syniz** [Wynncraft/Issues#7430] opened 2017-02-22 15:56 UTC
When i changed my minecraft name, I can't leave guild. I want to leave the Fuq(Kangronomicon) guild.
[https://youtu.be/S1admGoi7Pc](url)

IGN : Syniz_

**Comment by DebugMC** [comment] 2017-02-22 16:21
Guilds are broken right now and will be reworked Soon™. No one can help you with this though, all you can try to do is change your name back to your name you had when joining guild. This doesn't always work however, and the admins will not remove you from your guild (They say it only makes it worse)

**Comment by DebugMC** [comment] 2017-02-22 16:22
Also duplicate of #6755 #6837 #7117 #7066 #7079 and so on.

**Comment by thecoolkogut4** [comment] 2017-02-22 21:59
You can try to message an admin to remove you, (they have only done it once from what I'm aware of). Don't change your name again, or else you have the possibility of being in the guild three times (even changing back to the original name could triple you). The only known way to get out of the guild is if the guild gets disbanded which i don't think Fuq will be disbanded anytime soon.

**Closed** 2017-02-23 00:47 UTC
