### ISSUE TITLE
trap in nilvla woods

### ISSUE THREAD

**Issue by PeterP06** [Wynncraft/Issues#8521] opened 2017-07-05 06:24 UTC
I got trapped in -191,71,-1501. Plz help!
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by PepinhoJp** [comment] 2017-07-05 09:38
Duplicate of #88, just /kill to leave the area or use a teleport scroll, check for duplicates before posting a bug report, follow readme and delere the big line.

**Closed** 2017-07-07 14:11 UTC
