### ISSUE TITLE
Aldorei's secret part one sunflower patch not dropping 

### ISSUE THREAD

**Issue by Inamicusatto** [Wynncraft/Issues#4242] opened 2016-02-24 04:07 UTC
piecing things together, I know i have to get sunflower seeds from the patch behind kaeli's house, but the problem is that they dont drop any. this mean the quest is broken and cant be complete. I tried relogging and changing servers but have found no drops at all. 
![image](https://cloud.githubusercontent.com/assets/17444534/13275342/f05f41da-da81-11e5-9b7e-e4f7be34125c.png)

**Comment by Odnod** [comment] 2016-02-24 04:16
Duplicate of #4236 please put any additional comments on the original post :)

**Closed** 2016-02-26 01:33 UTC
