### ISSUE TITLE
Beneath the depths

### ISSUE THREAD

**Issue by RedNightDragon** [Wynncraft/Issues#4371] opened 2016-03-01 06:12 UTC
Recently I have been trying to do this quest but the map does not seem to be spawning in. I have tried servers 2 and 3 and neither worked. I am assuming it is like that for all of the servers. I hope that this gets fixed soon and if it is not broken then... damn I feel stupid. lol but thanks

**Comment by RedNightDragon** [comment] 2016-03-01 06:18
also it appears and if the item identifier npc and the emerald merchant are missing.

**Comment by ZzJarnozZ** [comment] 2016-03-01 10:22
I have the same problem to im trying to do it too but not spawning for me either

**Comment by Moe-Ronickah** [comment] 2016-03-01 13:42
Duplicate of #4236 . Please, use the search instructions on the front page so that you don't post duplicates, but, rather, add to the original issue. Thank you.

**Closed by Moe-Ronickah** 2016-03-01 13:42 UTC
Labels: Duplicate
