### ISSUE TITLE
The door in the mummy's tomb isn't working!!!

### ISSUE THREAD

**Issue by lmbest** [Wynncraft/Issues#1706] opened 2015-03-14 12:51 UTC
I did the password for the door and it didn't work! i try different servers but it still didn't work, i hope you would please look into this. Thanks

**Comment by Trixter313** [comment] 2015-03-14 19:16
Duplicate of https://github.com/Wynncraft/Issues/issues/1705

**Closed** 2015-03-21 18:24 UTC
Labels: duplicate
