### ISSUE TITLE
potion seller's dungeon exit

### ISSUE THREAD

**Issue by GriffinFitzsimons** [Wynncraft/Issues#1956] opened 2015-06-03 15:17 UTC
The exit to the mini-area below the potion seller's house on the emerald trail is blocked off. Once you click the button, to reveal the exit, it doesn't go to the waterfall -- it goes to a 1x3x2 blocked off area, that you are then stuck in until some other player can get you out.

Somehow the waterfall has been bricked up, and players cannot get out.

**Comment by Moe-Ronickah** [comment] 2015-06-03 20:02
Is this a dupe of #1951 ?

**Comment by GriffinFitzsimons** [comment] 2015-06-03 21:51
well shoot I guess it is; I did a couple of searches and didn't turn anything up. although I wouldn't think "just use /kill" is the best answer since part of the map is legitimately effed.

**Closed** 2015-06-04 12:58 UTC
