### ISSUE TITLE
cant log in

### ISSUE THREAD

**Issue by applefile** [Wynncraft/Issues#8052] opened 2017-05-02 23:36 UTC
can't log in after game shut off randomly

**Comment by applefile** [comment] 2017-05-02 23:37
says I'm already logged in

**Comment by applefile** [comment] 2017-05-02 23:38
This happened about 5 min ago

**Comment by Trixter313** [comment] 2017-05-02 23:50
Duplicate of https://github.com/Wynncraft/Issues/issues/8051

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2017-05-02 23:50 UTC
