### ISSUE TITLE
Incorrect Map Link

### ISSUE THREAD

**Issue by HeyItsMeTom** [Wynncraft/Issues#5345] opened 2016-06-29 16:42 UTC
When you start off and talk to the king of Ragni for the first time, he tells you to use "wynncraft.com/map" if you get lost. This is the wrong link - it should be map.wynncraft.com.

**Comment by Trixter313** [comment] 2016-06-29 17:06
Duplicate of https://github.com/Wynncraft/Issues/issues/4316

The issue has been fixed internally but hasn't been pushed to the play server yet. Hopefully it is done soon!

**Closed by Trixter313** 2016-06-29 17:06 UTC
