### ISSUE TITLE
Unable to find a server to connect to.

### ISSUE THREAD

**Issue by Skwirch** [Wynncraft/Issues#2101] opened 2015-07-14 02:50 UTC
This happened. The image is pretty self-explanatory. I am running Minecraft 1.8.7 on Windows 8. 
![bug](https://cloud.githubusercontent.com/assets/13325381/8665380/5c4d7f74-2998-11e5-8271-d855dc533656.PNG)

**Comment by Trixter313** [comment] 2015-07-14 03:31
Duplicate of https://github.com/Wynncraft/Issues/issues/2099
We recommend closing the duplicate and following the original, to keep the bug tracker de cluttered and so you can stay up to date on the status of the issue. Thanks!

**Closed** 2015-07-14 09:54 UTC
