### ISSUE TITLE
Level 50 Player w/ Access to ToL

### ISSUE THREAD

**Issue by Fyloket** [Wynncraft/Issues#2116] opened 2015-07-19 03:41 UTC
I was farming in the ToL Training area when a level 50 archer walks in... This struck me as a bit odd, considering you need to be a level 68 who has completed the ToL quest, unless there's another method of getting in which I have not heard of. After confronting him, he just claimed it was a glitch.

![glitch](https://cloud.githubusercontent.com/assets/10426637/8764420/a891ce18-2d9d-11e5-8047-50e0e332e128.PNG)

**Comment by BateauSD** [comment] 2015-07-19 07:19
Glitch bannable, please exit in Temple.

**Comment by Trixter313** [comment] 2015-07-19 10:57
What he might have done is waited for lag then entered, passing the point
where it checks to see if you did the quest and then being stuck in there.

**Comment by BateauSD** [comment] 2015-07-19 11:54
./kill

**Comment by Trixter313** [comment] 2015-07-19 11:56
@Fyloket isn't stuck, he is the correct level, he's saying he saw someone else (aaxm in his username) in there who is under level.

**Comment by Fyloket** [comment] 2015-07-19 15:10
I probably should specify that I am the level 73 here and aaxm is the level 50 who got into the temple.

**Comment by TrashcanMan** [comment] 2015-07-19 17:43
This should be enough evidence to file a player report, if you want to.

**Comment by Trixter313** [comment] 2015-07-20 12:32
Oh yeah, I completely forgot that this has been reported already.

Duplicate of https://github.com/Wynncraft/Issues/issues/2102

We recommend closing the duplicate and following the original to stay up to date on the status of the issue. Thanks!

**Closed** 2015-08-17 07:09 UTC
