### ISSUE TITLE
Animal Dungeon Boss Broken

### ISSUE THREAD

**Issue by NeonJungleTiger** [Wynncraft/Issues#5294] opened 2016-06-23 18:33 UTC
I was doing the Animal Dungeon w/ a friend and we got it stuck in a wall and annoyed the 4 other players in the boss room. We used Uppercut and Bash (Warrior Class), and it got pushed into the lava outside the barriers. It re-spawned in the middle like it's supposed to, but then it got stuck in a wall outside the barriers and wouldn't re-spawn. I've heard this will happen if the boss is locked on to you, and seems like a major bug.

**Comment by Trixter313** [comment] 2016-06-23 18:44
Duplicate of #3191 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-06-23 18:44 UTC
