### ISSUE TITLE
Life Steal isn't working

### ISSUE THREAD

**Issue by samwj02** [Wynncraft/Issues#4050] opened 2016-02-09 08:06 UTC
I'm wearing armour with life steal and mana steal on, but they aren't working. I've tried relogging, switching lobbies and taking the armour off, but they still don't work.

**Comment by Dar-krusos** [comment] 2016-02-09 09:34
Note: As of the Gavel Update, Life and Mana Steal only work effectively with poison.

**Comment by DarkDemonDragon** [comment] 2016-02-09 13:35
This was to balance things as Life/Mana steal were very OP as they worked every time you hit a mob meaning that it was impossible for players to die and they could spam spells for days. As @Dar-krusos suggested using poison works well as Life/Mana steal work by seconds now, not by hits which is compatible with poison which applies every 2 seconds. If you are an Archer/Hunter using Arrow Storm up close is a decent method to Life/Mana Steal if in a 1v1 fight, but poison is super effective against a group if you combine it with an AoE attack as poisoning multiple enemies allows you to Life/Mana steal a lot at once for a period of time.

**Comment by KeepoPrideHD** [comment] 2016-02-09 14:04
I have the same problem. I have a very bad regeneration and I am used not to needing any potions because I have huge poison, mana steal and life steal thanks to my weapon and armour. Today they stopped working, though the poison works as it should. Notice: a few days ago my lifesteal and mana steal worked but poison didn't ._.

**Comment by Trixter313** [comment] 2016-02-09 14:44
Duplicate of https://github.com/Wynncraft/Issues/issues/3225

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-09 14:44 UTC
Labels: Game Mechanics

**Comment by KeepoPrideHD** [comment] 2016-02-09 15:14
Rather than copying the same messages saying that this thread was a duplicate of one posted a year ago or something, you actually could help by provinding us with information. I've never seen you posting anything else than this notice with different thread numbers.

**Comment by DarkDemonDragon** [comment] 2016-02-09 15:36
@KeepoPrideHD he's just trying to organize all the issues so that the github isn't too cluttered for the Admins/GMs to look at. If any official information from an Admin will be released on the topic, it will be posted on the original.

**Comment by Trixter313** [comment] 2016-02-09 15:37
That's the point of marking duplicates and linking the original thread, all the information we have is located in the original thread.

**Comment by DarkDemonDragon** [comment] 2016-02-09 15:45
@Trixter313 off topic, but I just PMed on the forums about something. Also you prefer being contacted by e-mail or forum PM?
