### ISSUE TITLE
Mage (Teleporation Issue?)

### ISSUE THREAD

**Issue by Strikefire150** [Wynncraft/Issues#4427] opened 2016-03-04 02:15 UTC
So I'm not sure if this is suppose to be a bug or not, but the teleporation is suppose to hit enemies when going through them... but it doesn't seem to work on players. (Duel, Nether, name it.)

**Comment by Trixter313** [comment] 2016-03-05 15:50
Duplicate of https://github.com/Wynncraft/Issues/issues/4070

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-05 15:50 UTC
Labels: Game Mechanics
