### ISSUE TITLE
Unaccesible Mage account

### ISSUE THREAD

**Issue by maroons78** [Wynncraft/Issues#7795] opened 2017-04-10 22:18 UTC
I have a mage account, that I cannot activate, and I am unsure as to why. Recently I have changed my name so that could be it. Or not.

**Comment by DebugMC** [comment] 2017-04-10 22:21
#7185

**Comment by LordHelmchen98** [comment] 2017-04-11 00:08
Duplicate of #7680 please look there fore future information.

**Closed by LordHelmchen98** 2017-04-11 00:08 UTC
