### ISSUE TITLE
About Assassin

### ISSUE THREAD

**Issue by ShaGZCl1** [Wynncraft/Issues#3836] opened 2016-01-24 08:42 UTC
I think assassin's skill have many problems

(Spin Attack) =>true spend:6 hungry
This skills meanings is [Attack all the enemies around you.]
But It can Increase running speed of monster.
This problem let me die many times.

(Vanish)=>true spend:follow time to reduce
LV.2
30% damage bonus while vanished and 15% defense bonus
but whan I use Attack button the invisible are Removed.
and it spend mana is follow time reduced not stable.

(Multihits)=>true spend:10 hungry
This skills problem like spin attack
It can be monster fly over around(speed very fast) and monster can attack you on sky
then you can't do any thing to attack monster.

(smoke bomb)=>true spend:8 hungry

**Comment by Gualdim-Pais** [comment] 2016-01-24 09:23
Level up the intelligence

**Comment by Dar-krusos** [comment] 2016-01-24 12:40
(Spin Attack): Yes, this spell is bugged, but it doesn't increase running speed, instead it flings mobs around you.

(Vanish): When you attack, you are supoosed to exit out of Vanish, otherwise you can just keep attacking in Vanish mode eithout any consequences. This also allows for a quick termination of Vanish.

(Multihit): Some people have reported that this sometimes causes mobs to fly, but I have not seen this problem myself (my Assassin is lv.84, so I would've noticed by now)

(Smoke Bomb): There's nothing wrong with this spell...

About the mana costs, that is intentional and will doubtfully be changed. You have to lower your mana costs by putting Skill Points into Intelligence, or increase your mana regen. Decreasing the base mana cost will only make the game too easy.

The biggest problem I see is just the Spin Attack, so din't worry about the other spells.

**Comment by ShaGZCl1** [comment] 2016-01-24 14:17
Thank you Dar-krusos

And I noticed spin attack is can be monster quickly run to terget

**Comment by Trixter313** [comment] 2016-01-24 17:57
Duplicate of https://github.com/Wynncraft/Issues/issues/3140

Please direct any further comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-24 17:57 UTC
