### ISSUE TITLE
i stuck in a block

### ISSUE THREAD

**Issue by bar8484** [Wynncraft/Issues#8517] opened 2017-07-04 11:07 UTC
i played on your server i switched server from 12 to 2 and then i lagged and now i am stack in a block i went afk that you will be able to teleport me to somewhere normal please help me!!!

**Comment by PepinhoJp** [comment] 2017-07-04 23:31
Duplicate of #88 

Just /kill with +6 soul points to leave the area or use a teleport scroll, mods don't tp people out from places.

**Comment by colin350** [comment] 2017-07-07 13:29
[Example Duplicate Search](https://github.com/Wynncraft/Issues/issues?utf8=%E2%9C%93&q=stuck%20in%20block)

**Closed by colin350** 2017-07-07 13:29 UTC
