### ISSUE TITLE
Glass bottles aren't dropping near Ragni

### ISSUE THREAD

**Issue by 1rd** [Wynncraft/Issues#6039] opened 2016-09-05 00:50 UTC
I've been near Ragni and the Emerald Trail killing mobs for about 15 minutes and none have dropped a single glass bottle. Have they changed to what mob drops glass bottles, did the drop chance increase, or is there something else going on?

**Comment by Trixter313** [comment] 2016-09-05 13:20
Duplicate of https://github.com/Wynncraft/Issues/issues/5970

**Closed by Trixter313** 2016-09-05 13:20 UTC
