### ISSUE TITLE
Helm of Darkness glitch

### ISSUE THREAD

**Issue by Cotey** [Wynncraft/Issues#3289] opened 2015-12-28 18:43 UTC
So two of my classes have one, and they both have the same issue, so I'm assuming that this isn't an isolated incident. You're not able to identify the item, the game doesn't recognize it as a rare item anymore, although it still has the tag for it. And it still has the same stats as it should have, like gavel didn't interfere with it at all. I hope this is helpful if you didn't already know about it!!

**Comment by Trixter313** [comment] 2015-12-28 21:07
Could you please provide screenshots of the issue of possible? Thanks!

**Comment by Verret001** [comment] 2015-12-28 21:22
Or try using the **[directory](https://github.com/Wynncraft/Issues/issues/3197)** to identify if this is problem someone already had.

**Comment by Trixter313** [comment] 2015-12-29 22:00
Duplicate of https://github.com/Wynncraft/Issues/issues/3161

Please direct any further comments to the original issue. Thanks!

**Closed by Trixter313** 2015-12-29 22:00 UTC
