### ISSUE TITLE
Armor gone after not playing for a while

### ISSUE THREAD

**Issue by SuperBlockboy10** [Wynncraft/Issues#4887] opened 2016-04-24 20:47 UTC
I recently got back onto Wynncraft after not play for ~6 months, only to discover that my armor was gone and my fully identified bob's mythic spear was unidentified. I don't care much about the spear and I started identifying it again, but all of my armor was gone. I wanted to come play for a bit to see the changes since I stopped, but I can't do that now.

**Comment by Trixter313** [comment] 2016-04-24 20:48
Was your inventory full when you logged in?

**Comment by SuperBlockboy10** [comment] 2016-04-25 03:08
Yes, I believe that it was full.

**Comment by Trixter313** [comment] 2016-04-25 03:22
Ah, then this is a duplicate of #3153 

Wynncraft has a strict no refunds policy so unfortunately there's nothing we can do about the already lost items but we are working on getting the issue resolved so it doesn't happen again.

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-25 03:22 UTC
