### ISSUE TITLE
some loot chests are not working

### ISSUE THREAD

**Issue by chesters31** [Wynncraft/Issues#3652] opened 2016-01-11 10:27 UTC
i have noticed that when i open a loot chest most times it is now empty with nothing in it not even a emerald i have noticed this in different lvl chests also if this is a bug can this please be fixxed

**Comment by Trixter313** [comment] 2016-01-11 11:47
Duplicate of https://github.com/Wynncraft/Issues/issues/3530

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-11 11:47 UTC
