### ISSUE TITLE
"You Do Not Have Permission For this Area"

### ISSUE THREAD

**Issue by Andy0132** [Wynncraft/Issues#4881] opened 2016-04-23 11:12 UTC
Several of the weapons in the game are textured as wooden slabs. This creates an issue, as when you right-click anything with them, an error message is produced. Furthermore, this issue prohibits you from using chests with these weapons. Given how during fights, the right mouse button tends to be used, this produces spam very quickly.

Weapons I've had the issue with:

Relic Wand (Wooden Slab)
Olux's Prized Wand (Wooden Slab)
Arakadicus' Leg (Wooden Slab)

The issue appears to occur only with the wooden slab items, no other ones.

**Comment by Trixter313** [comment] 2016-04-23 13:18
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-23 13:18 UTC
