### ISSUE TITLE
Unopenable loot chest at 327, 80, -1666

### ISSUE THREAD

**Issue by ArthurLB** [Wynncraft/Issues#5616] opened 2016-07-29 17:01 UTC
There's a loot chest in the attic of a house in Detlas Suburbs that can't be opened because it's connected to another chest next to it with a block on top.

**Comment by Trixter313** [comment] 2016-07-29 17:35
Duplicate of https://github.com/Wynncraft/Issues/issues/5559

Remember to check for duplicates in the closed issues area next time, please. =)

**Closed by Trixter313** 2016-07-29 17:35 UTC
