### ISSUE TITLE
Mummy's Rag Attack Tier Bug part 2

### ISSUE THREAD

**Issue by riptidecraft** [Wynncraft/Issues#4744] opened 2016-04-02 23:55 UTC
Since my previous post has been buried too far down and no one is replying to it anymore, I'm making another post. I was saying in that post is that there is a glitch with the Mummy's Rag chesplate where the +2 attack tier part of it isn't working, and I do have screenshots on this.
![2016-04-01_17 18 25](https://cloud.githubusercontent.com/assets/18203684/14229813/8b57f828-f8f3-11e5-87c4-1b4feac74661.png)
![2016-04-01_17 18 49](https://cloud.githubusercontent.com/assets/18203684/14229814/8d48a2d6-f8f3-11e5-922a-a2e1d58d1ad6.png)
![2016-04-01_17 19 13](https://cloud.githubusercontent.com/assets/18203684/14229815/8e98c33c-f8f3-11e5-923e-d1c898eb4a7d.png)

**Comment by DarkDemonDragon** [comment] 2016-04-03 03:16
Please do not make duplicates of your own issues. Wait patiently until an official staff member can get to you.

**Comment by Moe-Ronickah** [comment] 2016-04-03 15:59
Dupe of #4719

**Closed by Moe-Ronickah** 2016-04-03 15:59 UTC
Labels: Duplicate
