### ISSUE TITLE
Evil deathlike glitch that is horrible and needs to be fixed at detlas

### ISSUE THREAD

**Issue by tecnojet** [Wynncraft/Issues#4735] opened 2016-04-02 15:23 UTC
So basicly, at 5:25 AM this morning I was grinding at the zombie dungeon then finished playing wynncraft and went to bed, afterwards I got up at 16:02 (Don't Judge) but I logged on and I was in detlas but.... All of my skill points reset, my items were throwen all over the floor, My legendary wepon wasn't there, all of my emeralds were being picked up by other players and my soul points were still at 9. That means I didn't die but something happened that made me loose all of my items and im probably not going to go on wynncraft 'till its fixed (and I get my stuff back (18 HOURS OF GRINDING (HELP ME))) .... ;-; I cri every tim ;-;

**Comment by DarkDemonDragon** [comment] 2016-04-02 18:55
Duplicate of #4120 Please close this issue and read the main one to understand what happened.

**Closed** 2016-04-03 16:13 UTC
Labels: Duplicate
