### ISSUE TITLE
Fallback server and server joining

### ISSUE THREAD

**Issue by WazieMcDizzle** [Wynncraft/Issues#5233] opened 2016-06-15 15:44 UTC
for me and all my friends it is taking us about and hour to log on because we got an error where that says something along the lines of "Could not connect to fallback server" and then once we do get on we click the "Quick Connect doesn't show any available servers

**Comment by Moe-Ronickah** [comment] 2016-06-16 02:35
DUPLICATE of #5012

**Closed** 2016-06-16 02:35 UTC
Labels: Duplicate
