### ISSUE TITLE
Chestnut Horse Reward Incorrect

### ISSUE THREAD

**Issue by setery10** [Wynncraft/Issues#6026] opened 2016-09-04 17:43 UTC
When I used the Corrupted Decrepit Sewers reward of a 35 Chestnut Horse it just took my Corrupted Witherhead's Ribs and made it a 30 Chestnut Horse.
![2016-09-04_13 40 57](https://cloud.githubusercontent.com/assets/8347065/18232801/8b40f048-72a5-11e6-9006-cb940e96b5e9.png)
![2016-09-04_13 40 59](https://cloud.githubusercontent.com/assets/8347065/18232802/8b411dd4-72a5-11e6-89ee-da64a264515b.png)
![2016-09-04_13 41 02](https://cloud.githubusercontent.com/assets/8347065/18232800/8b404cc4-72a5-11e6-895d-9afe54da9c21.png)

**Comment by Trixter313** [comment] 2016-09-04 19:02
Wynncraft has a no refunds policy so we can't give you the updated horse but if it is an issue that happens all the time we will work to fix it so you can eventually upgrade your horse.

**Comment by setery10** [comment] 2016-09-04 20:03
Yeah I knew about the no refund, I just want it fixed also can others test this?

**Comment by Moe-Ronickah** [comment] 2016-09-04 22:58
@Villageacules , could you take a look at this, please?

**Comment by setery10** [comment] 2016-09-09 16:05
Is this still being looked into, I'm confused.

**Comment by Trixter313** [comment] 2016-09-09 21:44
@setery10 yes, the issue is still open and being worked on. =)

**Comment by Moe-Ronickah** [comment] 2016-09-10 23:55
@AckroWynn , eh, what's up, doc?

**Comment by Trixter313** [comment] 2016-09-17 09:27
Appears to be fixed in latest patch: https://forums.wynncraft.com/threads/double-xp-weekend-patch.153715/#post-1720639 =)

**Closed by Trixter313** 2016-09-17 09:27 UTC
