### ISSUE TITLE
No bankers in pirate island ..

### ISSUE THREAD

**Issue by 7asoOonyi14** [Wynncraft/Issues#4019] opened 2016-02-07 15:08 UTC
there is no bankers in pirate island bank to exchange stack of emerald with an block ..

**Comment by Trixter313** [comment] 2016-02-07 21:20
Duplicate of https://github.com/Wynncraft/Issues/issues/3272

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-07 21:20 UTC
