### ISSUE TITLE
Old Items

### ISSUE THREAD

**Issue by deadrakilla** [Wynncraft/Issues#3867] opened 2016-01-26 14:48 UTC
I have an old weapon for my mage, he is level 47 and after a long while of not playing the game i got on randomly but his weapon doesn't work its a Devoruse and its the only weapon i have, please help fix it because i can't do much of anything until then

**Comment by Trixter313** [comment] 2016-01-27 02:44
Duplicate of https://github.com/Wynncraft/Issues/issues/3161

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-27 02:44 UTC
