### ISSUE TITLE
Bug report disapearing items in bank

### ISSUE THREAD

**Issue by 5hamanKing** [Wynncraft/Issues#7320] opened 2017-02-04 11:24 UTC
i wanna report a bug, this is what happend, i leveld up to lv 50, and wanted to unlock a new row in back ( i had 2 neclaces inside my bank) (1 gernalds amulet and 1 jetster necklace) the moment i unlockd the row for lv 50. those 2 items dissapeard (probaly beacuse they also have the TAG glass pane as item and so does the items blocking the row before u unlock it.  ( is there a way for me to get my items back , since they where both at the better side of the identifaction ) and can this please be fixd? that if u upgrade ur bank. the amulets / necklases who are glass panes dont dissapear aswell . cus this sux realy bad. with kind regards 5haman (ingame name).

**Comment by LordHelmchen98** [comment] 2017-02-04 11:55
Duplicate of #4091
Unfortunately you wont get back any items because Wynncraft enforces a strict norefund policy.

**Comment by forrester-marc** [comment] 2017-02-04 12:09
Also unfortunately, the only way to replace Gernald's Amulet is to create a new character and do all the quests again.  Chances are you were going to do that anyway though.

**Closed** 2017-02-04 15:21 UTC
