### ISSUE TITLE
I cant join a server for some reason

### ISSUE THREAD

**Issue by MrSoKarbonkel** [Wynncraft/Issues#5615] opened 2016-07-29 16:38 UTC
![2016-07-29_18 30 30](https://cloud.githubusercontent.com/assets/20728307/17255925/81601c18-55bb-11e6-8fb8-6fa821377001.png)

i dont know what to do i wanted to join like a year ago but i could not join but i did not wanted to play but now my friends play and i just want to join but i cant. I just cant join for some reason and i tryed again like 20 times

**Comment by Trixter313** [comment] 2016-07-29 17:33
Does using the command /kill help at all?

This is a duplicate of https://github.com/Wynncraft/Issues/issues/5418

Read all of the comments there and see if any of them help you.

**Closed by Trixter313** 2016-07-29 17:33 UTC

**Comment by MrSoKarbonkel** [comment] 2016-07-29 17:37
i cant do any commands

**Comment by Trixter313** [comment] 2016-07-29 17:39
Ah, I figured but wanted to make sure. Just try all of the suggestions in the other thread and see if they help. We've had issues like this in the past and they can be tricky to fix.

**Comment by MrSoKarbonkel** [comment] 2016-07-29 17:40
ok maby delete my player profile? or my player file on the server if you can cause i think that will solve the problem but i dont know if you can at all or not

**Comment by MrSoKarbonkel** [comment] 2016-07-29 17:46
nope does not work for me
ive tried some in the past and some just now but no it just does not work

**Comment by MrSoKarbonkel** [comment] 2016-07-29 17:46
i just think my player data is corrupted

**Comment by Trixter313** [comment] 2016-07-29 17:47
We usually save resetting someone as a last resort because it's difficult to get an admin free to do it. Hopefully one of those suggestions will work so we don't have to go to that step.

**Comment by MrSoKarbonkel** [comment] 2016-07-29 17:48
well i'll try them all again but i dont think that works

**Comment by MrSoKarbonkel** [comment] 2016-07-29 17:51
yes i tried them all again but still nothing works :(

**Comment by Trixter313** [comment] 2016-07-29 17:51
If none of those work and you would like us to just try resetting your data we will have to try and get someone who can. I'll try and see if I can speed up the process and notify someone. Until someone is free, there's not much that we can do. Just sit tight and soon someone should be able to help. =)

**Comment by MrSoKarbonkel** [comment] 2016-07-29 17:56
ok
should i just keep online in the server or should i just be online here on the form? or both because i realy want to play with some of my friends

**Comment by Trixter313** [comment] 2016-07-29 18:00
I'd say waiting offline of the server would probably be best. When someone gets a chance to help they should comment here and we can go from there.

**Comment by MrSoKarbonkel** [comment] 2016-07-29 18:03
okay is good

**Comment by sammyvsparks** [comment] 2016-07-29 18:24
Trixter313 you could try tagging AckroWynn on some things. He is fairly active.

**Comment by MrSoKarbonkel** [comment] 2016-07-30 15:03
when do you think a admin is gonna fix this?

**Comment by Trixter313** [comment] 2016-07-30 15:28
We have no time frame; whenever someone is available is the only answer I have right now.

**Comment by MrSoKarbonkel** [comment] 2016-07-30 16:28
okay

**Comment by MrSoKarbonkel** [comment] 2016-07-30 17:16
I hope someone is comming soon :)

**Comment by Moe-Ronickah** [comment] 2016-07-31 00:17
@MrSoKarbonkel , just to be certain, you can join the lobby, however, you cannot join a game server, correct?

If you can join the lobby, have you tried to use the 2-block high structure, close to where you land, to join the nether?

You have 'automatically download server resource pack' set to accept for WynnCraft, correct?

You don't have autojoin turned on, correct?

You are using MC 1.8.9 or lower, correct?

**Comment by MrSoKarbonkel** [comment] 2016-07-31 08:50
all correct

**Comment by MrSoKarbonkel** [comment] 2016-07-31 08:53
but i cant join the nether to

**Comment by MrSoKarbonkel** [comment] 2016-07-31 08:53
the same exact message

**Comment by MrSoKarbonkel** [comment] 2016-07-31 16:59
to bad they already hit lvl 20 xd

**Comment by MrSoKarbonkel** [comment] 2016-08-02 11:59
when do you think i can join the server?

**Comment by Moe-Ronickah** [comment] 2016-08-03 14:09
Well, I tried to tp another player with this issue to me, I'm a moderator, however, it did him no good.  The admins are aware of this issue, and right now, we are just waiting to find out what else can be done about it.  In short, I don't have an answer for you, but it is something that is being worked on.

**Comment by MrSoKarbonkel** [comment] 2016-08-03 21:56
Sure i will wait for a admin

**Comment by MrSoKarbonkel** [comment] 2016-08-04 16:34
if you have the power to make them come sooner than ill be happy

**Comment by Moe-Ronickah** [comment] 2016-09-26 00:12
This is a generic message, to everyone affected by these issues.
I've discussed this with the admins, and it turns out, after a lot of investigation, that the 
problem lies within the saved data file created by Minecraft.  The data is corrupted.  For some
of you, your character data files are so badly corrupted that you cannot login and play on any
classes.  For some of you, only one, or maybe two, of your classes, are corrupted.

Well, here is what we can do, and you need to think seriously about the options that I am going
to tell you about, and what they mean.  First, our only possible fix for this is to WIPE your
character.  That means that ALL of your classes will be gone, along with ALL of your information.
That means EVERYTHING will be gone.  Any pets that you purchased, any unused item bombs, any
unused XP bombs, and any GC that you may have left, will be gone.  There is NO way that we
can recover that information before the wipe, so once it happens, there is absolutely no way
to go back and get it, either.  It just cannot be done.  The data file is corrupt.  We can,
however, go back through the store and recover your rank, if you have purchased one.  Your
VIP/VIP+ rank can, and will, be recovered.

So, here is your decision to make.  If you want to keep waiting to see if Minecraft ever will
make a tool to recover lost character information, and they haven't yet made one to recover
lost or corrupted worlds, you can keep on waiting.  Seriously, it's not a problem for us, as
it requires that we simply do nothing to your game account.  For those of you who have lost one
or two classes, the decision to wipe EVERYTHING means that you have to accept the fact that
you will lose ALL of your classes, ALL of your pets, if you purchased any, any bombs that
you may have, and any GC that you may have.  None of this is recoverable if your account is
wiped, however, you will be able to start over on all of your classes.

For those of you who cannot play on any class, you have the same decision to make for yourself.
  You can wait to see if Minecraft will ever make a tool to recover lost character data, with
the same considerations as above.  Minecraft has never made one, and there is nothing that
we have heard of to say that they ever will.  Or, you can choose to have all of your character
data wiped, with the same losses as explained, above, and we can, and will, recover your VIP/VIP+
rank.

So, for each of you, individually, let me know what you want us to do, and I'll pass along your
decisions to the admin, at the end of this week (Friday or Saturday).
