### ISSUE TITLE
armour skins

### ISSUE THREAD

**Issue by wynncraftlupascu** [Wynncraft/Issues#3882] opened 2016-01-27 12:52 UTC
it dose not show the armour skins

**Comment by DarkDemonDragon** [comment] 2016-01-27 13:01
Please provide information or this issue will be closed by staff.

**Comment by wynncraftlupascu** [comment] 2016-01-27 17:33
help me

**Comment by DarkDemonDragon** [comment] 2016-01-27 20:08
.

**Comment by Trixter313** [comment] 2016-01-31 17:11
Duplicate of https://github.com/Wynncraft/Issues/issues/3739

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-31 17:11 UTC
