### ISSUE TITLE
Item Bugged (Dragon Skin Chestplate)

### ISSUE THREAD

**Issue by Vyst** [Wynncraft/Issues#4190] opened 2016-02-20 14:32 UTC
My chestplate (Dragon Skin) got bugged out. There's no stats assigned to it.

http://prntscr.com/a5punw

**Comment by Alexicon1** [comment] 2016-02-20 14:35
That happens when you are in a merchant screen, items seem to revert to what they were before the stat change. Its ok, it should fix itself

**Comment by Vyst** [comment] 2016-02-20 14:54
Nope, I've relogged, wore it and took it off. It doesn't change back.

**Comment by Trixter313** [comment] 2016-02-20 16:56
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-20 16:56 UTC
