### ISSUE TITLE
Loot chests can't be opened

### ISSUE THREAD

**Issue by joelalejandro** [Wynncraft/Issues#3945] opened 2016-01-31 22:53 UTC
Many chests found throughout Ternaves, Nesaak, Detlas, Almuj and Bremminglar cannot be opened. The message `You don't have permission for this area` appears every time I try to open one of them.

**Comment by Dar-krusos** [comment] 2016-02-01 05:16
Yeah, they must have changed something in the coding, so various things are making that text pop up. I'm pretty sure it will 100% work to open chests if you have an empty hand, though.

**Comment by Johnneh** [comment] 2016-02-01 05:30
This is a recent issue, but it can be avoided if you open the chest with an empty hand or at least a non-block item. All weapons are modeled using blocks, so don't right click the chest with your weapon.

What I find strange, though, is that some chests (different areas or different servers? Not sure) work OK with your weapon.

**Comment by Dar-krusos** [comment] 2016-02-01 05:47
> What I find strange, though, is that some chests (different areas or different servers? Not sure) work 
> OK with your weapon.
> - Johnneh
It depends on the area, not the server.

**Comment by DarkDemonDragon** [comment] 2016-02-01 13:20
Modify the title to "Loot Chests can't be open with weapon in hand" unless you actually can't even open then with an empty hand. (Although I think someone has already reported this)

**Comment by DarkDemonDragon** [comment] 2016-02-01 13:30
Yea this is a duplicate of #3902 Please close this issue and follow the main one.

**Closed** 2016-02-02 11:56 UTC
Labels: Game Mechanics
