### ISSUE TITLE
Guild leaving ISSUE

### ISSUE THREAD

**Issue by Dr4zy** [Wynncraft/Issues#8575] opened 2017-07-12 18:14 UTC
I cant leave my own guild, and this issue is caused because of i changed name while in a guild.
This Guild issue has been going on for alot of time and its one of the biggest complains.
Can you devolopers please fix this in the next patch, its really annoying because i want to create a guild with my friend from the ground.
Also my name is doubled whenever i type in the guild chat or do any commands in the guild.

**Comment by ittnoraA** [comment] 2017-07-12 18:24
This has been known of since the dawn of time, and the developers are already working on fixing it. You are aware of the fact that this has been reported several times before, so making new issues about the subject is pointless, as it won't make the update come any sooner. 

Duplicate of dozens of other issues.

**Comment by Dr4zy** [comment] 2017-07-12 18:37
ittnoraA i am well aware of that, i am just writing that i have the same issue .-.

**Comment by ittnoraA** [comment] 2017-07-12 18:44
Sorry, I just don't see a reason why you would have the need to mention it without any specific purpose.

**Comment by colin350** [comment] 2017-07-15 05:00
What we mean by duplicates is that you should instead comment on exisiting open issues (#3665) instead of creating a new one. 

You are not the first and certainly not the last to beg here for it to be fixed. It'll be fixed when it is fixed.

**Closed by colin350** 2017-07-15 05:00 UTC
