### ISSUE TITLE
Border at the top of the world

### ISSUE THREAD

**Issue by RadDudesme** [Wynncraft/Issues#5353] opened 2016-06-30 18:50 UTC
You can teleport up mountains as a wizard or dark mage. I have found out that you can get trapped inside the world border if you teleport to high. Please raise the world border or put some barriers to block this.

**Comment by Moe-Ronickah** [comment] 2016-07-01 01:21
Duplicate of #5156 .  Don't go up there, because if you go out, you could get banned.

**Closed by Moe-Ronickah** 2016-07-01 01:21 UTC
Labels: Duplicate
