### ISSUE TITLE
Guild War bug (mobs are not spawning/we don't get tped to the war server)

### ISSUE THREAD

**Issue by FighterZ** [Wynncraft/Issues#8618] opened 2017-07-18 19:23 UTC
I'm pretty sure everyone have gotten this problem when they want to attack a certain territory.  I tried attacking a couple of times on different places and different servers and the result is still the same. When the timer to start the guild war reached 0, i either don't get tped to the war server or when i got tped there, no mobs spawning. This issue has been bothering me for quite some time now and i hope the wynncraft team could fix this issue as soon as possible. thank you.

**Comment by RubbrDucky** [comment] 2017-07-18 19:55
Guilds are broken right now, wait like the rest of us for a guild code
rewrite from the devs.

**Comment by thecoolkogut4** [comment] 2017-07-18 22:01
Duplicate of #6054 and many more

**Closed** 2017-07-19 07:52 UTC
