### ISSUE TITLE
Craftmas Chaos Insta-Death

### ISSUE THREAD

**Issue by Jaguar11891** [Wynncraft/Issues#3819] opened 2016-01-23 06:47 UTC
There is a part in the quest Christmas Chaos where you give a crystal shard to a summoner and you go out an exit behind him. You get teleported to an image of you falling into Santa's mouth and you die. I went in with my warrior with 745 HP at level 30 (which is about the health a level 30 would have) and I can't complete the next part of the quest due to fall damage. Is there a way to fix this?

**Comment by Dar-krusos** [comment] 2016-01-23 08:14
Try changing servers because this could be a result of lag or a glitch, as you should be teleported before you hit the ground.

**Comment by DarkDemonDragon** [comment] 2016-01-26 13:06
lol this is why I don't get why fall dmg was readded as this complicated a ton of quest teleportation sequences.

**Comment by Trixter313** [comment] 2016-01-30 15:49
Duplicate of https://github.com/Wynncraft/Issues/issues/3678

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-30 15:49 UTC
