### ISSUE TITLE
Underice

### ISSUE THREAD

**Issue by IIFennecII** [Wynncraft/Issues#5917] opened 2016-08-30 17:02 UTC
Well I've seen this adressed but not solved. Simply the Underice quest wants you to kill a mob t ogain the "bait" but the mob is just not spawning. restartes, relogs, other servers. nothing is working

**Comment by Trixter313** [comment] 2016-08-30 19:12
Duplicate of #5873

Please don't post duplicate issues, if you have anything to add you can comment on the already open issue. Thanks!

**Closed by Trixter313** 2016-08-30 19:12 UTC
