### ISSUE TITLE
Issues With Leaving Guilds

### ISSUE THREAD

**Issue by PeriodicGamer** [Wynncraft/Issues#3584] opened 2016-01-07 07:32 UTC
I created my guild back in late 2014, when guilds were first implemented. For the most part, everything seemed to work fine until now, just after the Gavel update. I felt my guild could use a new name, and a new start with the new province and all. I go to leave my guild, and for whatever reason, it just won't let me. I have maximum soul points, and no one else in my guild. My hope is that either this issue gets fixed, or there is a guild disbanding command, which would make this process much easier.
IGN: PeriodicGamer_
Guild: Heroes of Wynn

**Comment by PeriodicGamer** [comment] 2016-01-07 07:32
IGN: PeriodicGamer_
Guild: Heroes of Wynn

**Comment by DarkDemonDragon** [comment] 2016-01-07 12:53
What commands have you attempted to use?

**Comment by PeriodicGamer** [comment] 2016-01-08 11:57
/guild leave, /guild kick PeriodicGamer_ (I know that isn't meant to work), and /guild rank PeriodicGamer_ Chief and then leave (I know that isn't meant to work either. I'm desperate.).

**Comment by Trixter313** [comment] 2016-01-17 19:27
When you type /guild leave, does a sign at least come up for you to type in?

**Comment by PeriodicGamer** [comment] 2016-01-18 03:20
Yes, it does. Doesn't do anything, though.

**Comment by Trixter313** [comment] 2016-01-18 03:42
Ah, then this is a duplicate of https://github.com/Wynncraft/Issues/issues/3405

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-18 03:42 UTC
