### ISSUE TITLE
It deleted my items.

### ISSUE THREAD

**Issue by MiniProzac** [Wynncraft/Issues#4012] opened 2016-02-07 05:00 UTC
So I'm an old user from awhile back, my UN is MiniProzac(used to be pkmnmastert123).  I bought vip because I loved the server.  I just got on today, and I saw the new update.  When I took off my old adventure's armor to get it identified again, it deleted all but my boots.  I really don't know why this happened, but i won't play on this server again until it is fixed somehow.

Thank you.

**Comment by Dar-krusos** [comment] 2016-02-07 11:01
Was your inventory full during the time you tried to take off your armor?

**Comment by salamaFIN** [comment] 2016-02-07 11:36
Same here But It Was Like Month Ago Or Something ,, All My adventurers armor just dissapeared when i clicked it ps. I've Been Tweetting This To Grian Emailing To Wynncraft Tweeting to Wynncraft AND Everything I can To get My Armor Back!

**Comment by Dar-krusos** [comment] 2016-02-07 11:45
> Same here But It Was Like Month Ago Or Something ,, All My adventurers armor just dissapeared when i clicked it ps. I've Been Tweetting This To Grian Emailing To Wynncraft Tweeting to Wynncraft AND Everything I can To get My Armor Back
> - salamaFIN

> Was your inventory full during the time you tried to take off your armor?
> - Dar-krusos

**Comment by salamaFIN** [comment] 2016-02-07 11:57
Yes It Was I Think?

**Comment by salamaFIN** [comment] 2016-02-07 11:57
Oh I got my boots

**Comment by ImRyan17** [comment] 2016-02-07 12:39
Same happened to me, I lost a pair of legendary boots :/

**Comment by salamaFIN** [comment] 2016-02-07 13:14
No I lost chestplate leggings helmet

**Comment by Dar-krusos** [comment] 2016-02-07 13:39
Various armor pieces require a certain amount of Skill Points to be able to wear them. If you take off one armor piece, it updates the rest, so if you are wearing any armor you aren't supposed to, taking one off will take off all the ones you are not eligible to wear.

If your inventory is full and this happens, your items will disappear and will (unfortunately) not drop on the ground like it does with Item Identifiers. As Wynncraft does not allow refunds or giving items back, you will just have to find new items. Sorry for any convenience caused.

I believe this issue will need to be addressed by making the items drop to the ground.

**Comment by salamaFIN** [comment] 2016-02-07 13:40
FOR FUCK SAKES

**Comment by salamaFIN** [comment] 2016-02-07 13:40
I CAN'T FIND A NEW ADVENTURERS ARMOR

**Comment by MiniProzac** [comment] 2016-02-07 15:05
Sorry, my email is being gay.  It sometimes loads😕  but eh, what can ya do.


Sent from Outlook Mobile






On Sun, Feb 7, 2016 at 5:41 AM -0800, "salamaFIN" <notifications@github.com> wrote:





I CAN'T FIND A NEW ADVENTURERS ARMOR


---

**Comment by Trixter313** [comment] 2016-02-07 21:24
Duplicate of https://github.com/Wynncraft/Issues/issues/3153

Please direct any future comments to the original thread. Thanks!

Unfortunately due to Wynncraft's strict no refunds policy we can't return any already lost items but we are hoping the admins will be able to fix it soon to prevent it from happening again.

**Closed by Trixter313** 2016-02-07 21:24 UTC

**Comment by salamaFIN** [comment] 2016-02-07 21:34
Really? REALLY ??? I SPEND MONEY ON THIS SERVER AND YOU GUYS CANT DO ANYTHING FOR ME?? FUCK

**Comment by MiniProzac** [comment] 2016-02-07 21:55
Yeah, it really is stupid.  I paid for VIP for a fuck8n reason!


Sent from Outlook Mobile






On Sun, Feb 7, 2016 at 1:34 PM -0800, "salamaFIN" <notifications@github.com> wrote:





Really? REALLY ??? I SPEND MONEY ON THIS SERVER AND YOU GUYS CANT DO ANYTHING FOR ME?? FUCK

---

**Comment by salamaFIN** [comment] 2016-02-07 21:57
Fuck sake gimme my armor back! THE VIP COST AND WE DONT GET ANY RESPECT FROM YOU GUYS!!!! YOU JUST COPY PASTE THE SAME MESSAGE AS YOU ANSWERED FOR THE LAST PERSON THAT SAID SAME

**Comment by Trixter313** [comment] 2016-02-07 22:04
When you buy VIP, you get all of the perks listed on the site and support the server. That is the incentive. Having the policies that affect everyone not affect you isn't in that list. Whether you donated or not, everyone receives the same support and follows the same rules. Hopefully it isn't too much of an inconvenience but with just a little time you should get armor much better than the ones you lost. Thanks!

**Comment by salamaFIN** [comment] 2016-02-07 22:07
You  really cant get armor when you die to ragnis zombie for 4 hits
