### ISSUE TITLE
Broke Items

### ISSUE THREAD

**Issue by DireFire112** [Wynncraft/Issues#3927] opened 2016-01-30 22:56 UTC
i have a few broken items and i dont want to trow them away cause i paid for them before gavel but i ws wondering if there is a way to get them fixed?

**Comment by Odnod** [comment] 2016-01-31 08:18
I assume that you are talking about items like Fierte, Montefiore, and Devorousse. And they are working on fixing that bug. For now just keep playing with different items.

**Comment by Trixter313** [comment] 2016-01-31 16:43
Duplicate of https://github.com/Wynncraft/Issues/issues/3161

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-31 16:43 UTC
