### ISSUE TITLE
House of twain helmet

### ISSUE THREAD

**Issue by striker608** [Wynncraft/Issues#5931] opened 2016-08-30 22:51 UTC
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
its unidentified and I cant put it in identifier

**Comment by Trixter313** [comment] 2016-08-30 22:52
Duplicate of https://github.com/Wynncraft/Issues/issues/5911

**Closed by Trixter313** 2016-08-30 22:52 UTC
