### ISSUE TITLE
I cannot buy vip or vip+ or any gold coins because when i click on buy it sends me to www.google.com

### ISSUE THREAD

**Issue by zephlee1** [Wynncraft/Issues#3426] opened 2016-01-01 11:59 UTC
i cant buy vip pls help

**Comment by HeyloLP** [comment] 2016-01-01 23:44
try reloading the page

**Comment by Trixter313** [comment] 2016-01-02 03:22
Is the issue still occurring? Many issues fix themselves over time and it works fine for me. 

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by zephlee1** [comment] 2016-01-02 08:31
I can only buy VIP on my phone but its glitched and I can't put my  card number because my phone is too small

**Comment by HeyloLP** [comment] 2016-01-02 22:58
@zephlee1 then try a different browser

**Comment by Trixter313** [comment] 2016-01-10 22:56
Can you still not do it? I'd hope it would be fixed by now.

**Comment by Trixter313** [comment] 2016-01-30 03:46
I'm assuming the issue is now resolved due to no response in 20 days. If not, simply comment below and I'll reopen. Thanks!

**Closed by Trixter313** 2016-01-30 03:46 UTC
