### ISSUE TITLE
Old Key Drop

### ISSUE THREAD

**Issue by NitroStarman** [Wynncraft/Issues#6011] opened 2016-09-03 20:21 UTC
I was around the Detlas area slaying zombies and one of them dropped a Skeleton Key. After the recent update, I understand that this should not be happening any more. I also understand that in the next update that the Key Exchanger will no longer exist. If this rare drop continues to exist then it will be outdated and a nuisance for players or even confuse some players about where and how one obtains a dungeon key. This was found near the Detlas Suburb.

**Comment by Trixter313** [comment] 2016-09-03 20:52
Duplicate of https://github.com/Wynncraft/Issues/issues/5968

**Closed by Trixter313** 2016-09-03 20:52 UTC
