### ISSUE TITLE
Guild

### ISSUE THREAD

**Issue by GarBro** [Wynncraft/Issues#3849] opened 2016-01-24 19:01 UTC
I can't contribute xp to my own guild but my members can.
When I do /guild stats it shows a guild names nobody lvl 26
It doesn't show my own
Can someone help me?

**Comment by Trixter313** [comment] 2016-01-25 03:26
What is the name of the guild?

**Comment by DarkDemonDragon** [comment] 2016-01-26 13:15
Duplicate of #3799 for the Nobody bug.

For xp what command are you using?

**Closed** 2016-01-31 16:52 UTC
