### ISSUE TITLE
You don't have permission for this area.

### ISSUE THREAD

**Issue by Sigurdthebro** [Wynncraft/Issues#6751] opened 2016-11-22 19:48 UTC
After doing the grave mistake quest almost every time I right click( Im an archer ) It says in chat You dont hava permission for this area!
![2016-11-22_20 43 57](https://cloud.githubusercontent.com/assets/23664961/20539366/080c1f7a-b0f5-11e6-92d9-62f7191c5ded.png)
I cant open doors and can barely shoot! Help!?

**Comment by LordHelmchen98** [comment] 2016-11-22 19:51
Thats just because of your weapon. As you can see its a halfslab. Normally it should be retextured but apparently you are another one facing that issue with weapons that stay being a halfslab. However the game thinks you want to place it (dont ask me why) and you are not allowed to place blocks. Thats why you get those messages. There is no fix for this. If you want to open chests or doors etc. you just have to use your bare hands or another weapons that is not a slab.

**Comment by Sigurdthebro** [comment] 2016-11-22 19:53
Thanks But apparently its only for the first bow the other one (which is relic bow) I can open and close doors but with the first one thats called Meteorich Arch it happens?!

**Comment by Sigurdthebro** [comment] 2016-11-22 19:55
BTW will all bows be retextured like that?
And is it possible to retexture the resource pack?

**Comment by LordHelmchen98** [comment] 2016-11-22 19:56
I dont know if thats correct but I think once a weapon started to give me this messages when I accidentally threw it out of my inventory and then picked it up again.

**Comment by Sigurdthebro** [comment] 2016-11-22 19:56
Damn

**Comment by Sigurdthebro** [comment] 2016-11-22 19:58
im an idiot xD I was going to test if its to so I threw my other bow and picket it up agin and now its happening with that to!  xD

**Comment by Sigurdthebro** [comment] 2016-11-22 20:00
Do you think it will be fixed?

**Comment by LordHelmchen98** [comment] 2016-11-22 20:12
eww rip xD well at least now I know thats what causes it :p
but I think if they dont find an easy solution it wont be fixed in the near future as its only a visual bug, annoying but nonetheless visual, and not really gameplay changing (except the stuff with chests and doors)

**Comment by ColinRioux** [comment] 2016-11-24 03:32
Duplicate of #4548

**Closed by ColinRioux** 2016-11-24 03:32 UTC
