### ISSUE TITLE
Mesarock Arch Bow, does not have bow texture, it looks like a normal block

### ISSUE THREAD

**Issue by Nauthive** [Wynncraft/Issues#8115] opened 2017-05-11 22:48 UTC
![image](https://cloud.githubusercontent.com/assets/28637020/25975071/3bcee26a-367a-11e7-9062-89362836d9d2.png)
![image](https://cloud.githubusercontent.com/assets/28637020/25975091/4df4dc38-367a-11e7-9b9b-00aecbfb3c82.png)

**Comment by LordHelmchen98** [comment] 2017-05-11 23:00
Duplicate of #4548 
Weapons are retextured blocks but sometimes the textures are missing. The wepaons still work though.
However this is known and will hopefully be fixed soon.

**Closed** 2017-05-11 23:00 UTC
Labels: Duplicate
