### ISSUE TITLE
/guild leave bug

### ISSUE THREAD

**Issue by GaPoiVN** [Wynncraft/Issues#4857] opened 2016-04-19 11:33 UTC
I cant do /guild leave , it took me 3 soul points and Im still in my guild . And I cant kick myself since Im a owner , can someone help me with this ?

**Comment by Odnod** [comment] 2016-04-19 17:39
Have you changed your username recently?

**Comment by ChiefInferno** [comment] 2016-04-27 23:31
I have also been experiencing this, i changed my name in January and switched it back in February, but right now i have the old username back. I see that even though I have changed my name back it is stilled bugged but I have made a couple reports on here and to the support email (most nice but a couple rude) and i have learned it is trying to be fixed but i'm just seeing if its still trying to be fixed because it was a while ago i posted those, also i wondered if there's a way for a staff member/admin that could kick me from it(P.S. My guild is inactive so i cant get some one to try and kick me, (My IGN Is PierceTheVeil_)

**Comment by KrabTheScrab** [comment] 2016-04-28 19:53
lol ga hey

**Comment by Trixter313** [comment] 2016-04-30 07:12
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-30 07:12 UTC
Labels: Guilds
