### ISSUE TITLE
Mesarock Arch has no custom texture

### ISSUE THREAD

**Issue by Tridon3** [Wynncraft/Issues#7400] opened 2017-02-19 22:32 UTC
https://gyazo.com/12c545c19479a63a6a4317c8cec0c467

**Comment by Pyromanical** [comment] 2017-02-19 22:55
Duplicate of #7017

**Comment by ColinRioux** [comment] 2017-02-20 02:29
This is very known, and will hopefully be patched when Wynncraft is upgraded from 1.8.9.

**Closed by ColinRioux** 2017-02-20 02:29 UTC
