### ISSUE TITLE
Item Not Adapted to the New Update?

### ISSUE THREAD

**Issue by Pikachu118811** [Wynncraft/Issues#3775] opened 2016-01-19 06:45 UTC
As you can see, I have a glitched Fierte that is not adapted to the new item update, thus having the old stats. It seems to be rendered unusable as it doesn't give the attack speed it is supposed to give. It cannot be sold either.
![2016-01-19_17 23 01](https://cloud.githubusercontent.com/assets/16696795/12411547/d44e4578-bed3-11e5-9b5f-00f9cec330db.png)

**Comment by Pikachu118811** [comment] 2016-01-19 06:46
Any Ideas why does this happen?

**Comment by Dar-krusos** [comment] 2016-01-19 10:41
This is different for each situation and is just random bad luck. Sorry, mate, but you'll have to chuck it out, unless I'm mistaken and you are allowed to swap it for a new one.

**Comment by Trixter313** [comment] 2016-01-19 11:44
Duplicate of #3161

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-19 11:44 UTC
