### ISSUE TITLE
MY armor skin thingy wont work

### ISSUE THREAD

**Issue by BlackPanderz** [Wynncraft/Issues#4365] opened 2016-02-29 21:32 UTC
when i log on i have the normal minecraft armor not the skin texture armor

**Comment by Moe-Ronickah** [comment] 2016-02-29 21:43
Please use the search functions.
Duplicate of  Armor Skins #4345 .  Please refer to the original thread for an explanation.

**Closed by Moe-Ronickah** 2016-02-29 21:43 UTC
