### ISSUE TITLE
Cannot open the wynncraft website

### ISSUE THREAD

**Issue by shireburgo** [Wynncraft/Issues#4424] opened 2016-03-03 23:54 UTC
I've been having a lot of fun on wynncraft lately and I wanted to check out the website and maybe purchase a rank but I cannot seem to get on the website. Down below you will see a picture of what loads in when I go to the website, I have tried it multiple times, on multiple devices and the same thing only happens. For some reason it only loads in the background picture and nothing else. Any help would be appreciated thank you!
![wynncrafthelp](https://cloud.githubusercontent.com/assets/17628015/13513741/05432ae4-e158-11e5-9864-ad6a3785e200.png)

**Comment by Moe-Ronickah** [comment] 2016-03-05 05:30
Try clearing your browser cache, and see if that helps.

**Comment by Trixter313** [comment] 2016-03-05 16:04
Duplicate of https://github.com/Wynncraft/Issues/issues/4228

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-05 16:04 UTC
Labels: Website
