### ISSUE TITLE
Powder Stacking issue

### ISSUE THREAD

**Issue by mario132567** [Wynncraft/Issues#5927] opened 2016-08-30 22:21 UTC
You are unable to stack lvl 2/ higher powders of the same magic together

**Comment by Trixter313** [comment] 2016-08-30 22:22
How many slots does the weapon you're trying to apply the powder to have?

**Comment by Trixter313** [comment] 2016-08-30 22:30
Oops, read your issue wrong.

Duplicate of https://github.com/Wynncraft/Issues/issues/5899

**Closed by Trixter313** 2016-08-30 22:30 UTC
