### ISSUE TITLE
I just lagged out  leading to loss of character

### ISSUE THREAD

**Issue by dakurisu** [Wynncraft/Issues#5011] opened 2016-05-17 04:50 UTC
I just lagged out in the spider boss room, after re-connecting my character was reset and now back to the basic skinned archer lady with none of my items but the beginner bow? I had 3 souls points left on my character so i now i didn't loss my gear but? why was i reset back to the beginning character model as well?

**Comment by Trixter313** [comment] 2016-05-17 11:04
Are you talking about your skin being reset to the default steve/alex design? If so, this is most likely temporary and _should_ resolve itself within a few hours. Let us know if doesn't though. Thanks!

**Comment by dakurisu** [comment] 2016-05-17 12:19
The Alex design. But i can't change it anymore on that character regardless of my Armour/minecraft changing skins. After re-logging on it a few times and selecting that character my levels went back to normal (26) but all the gear and such are still gone. I don't know if this was a bug do to maybe some data getting shifted while i was in the dungeon and essentially logged out? Although i am bummed about losing all my gear i decided to start a new archer/hunter anyway. I thought it might be a good idea to at least give the heads up about it as to avoid anyone else from getting the same issue. The exact thing that happened was that my internet craped out on me for about 30 seconds during the spider dungeon boss fight after reconnecting and re-selecting that character it now has a perma alex skin, temporarily lost all levels, and per-ma lost items.(had a friend check the dungeon with me for any drops of the such... nothing sadly.)

**Comment by YunoFGasai** [comment] 2016-05-17 12:33
I guess what happened was that while your internet was acting up you died a couple of times and lost your items, after your internet went back to normal you logged on and saw your class at the same level without the items as they dropped in the spider dungeon which is physically very far away.
the moment you died there was no player in the dungeon therefore the chunks unloaded and all items were deleted which was why your friend didn't find anything.

**Comment by dakurisu** [comment] 2016-05-17 17:45
That sounds fairly close to what i think happened but when i first reconnected and selected my character i was back to level 1, and outside the spider dungeon. Normally if you die I'm pretty sure you get sent back to the nearest town  or is that different when your in a dungeon? And how can i die multiple times in the same life?

**Comment by QFluff** [comment] 2016-06-04 13:42
i got an error (idk what the name was, btw 14 soulpoints). re-log, select my lv 63 assasine, spawn in detlas with no items but still lv 63 and a alex skin... do /class... slect my lv 84 archer... same shi**. i checked every class everything is gone just my enderchest and my quest items are still there wtf is this?

**Comment by QFluff** [comment] 2016-06-04 13:59
im sure u dont now how to handle this... i will simply quit this game if my items are still gone 2 days after.

**Comment by Moe-Ronickah** [comment] 2016-06-04 14:24
@QFluff , open a separate issue.

**Comment by Moe-Ronickah** [comment] 2016-06-04 14:42
@dakurisu , when your internet crashes, and you are in-game, some strange things can happen, especially if you are close to dying.  When your internet crashed, you got killed by the boss, because as far as the server was concerned, you were still there, hence -2sp.

When you reconnected outside the spider dungeon, there is a chance that you died there, too, although you should have been sent to the nearest town.  This is one issue, and may or may not be related to your internet crashing.

Sometimes, when someone dies at 3sp, something strange happens, and they lose their other sp.  This is another issue, and the problem with this issue is that it is rare, and hard to reproduce.

This has to be related to #4039, so I'm closing it as a duplicate, but, please, if you have more information, comment in that thread.

**Closed by Moe-Ronickah** 2016-06-04 14:42 UTC
Labels: Duplicate
