### ISSUE TITLE
When I logged In My legendary leggs, unique ring and bracelett were gone from my armor spots. (got proof)

### ISSUE THREAD

**Issue by Grandoni7** [Wynncraft/Issues#4207] opened 2016-02-21 11:47 UTC
On 21-2-2016 , around 12:00 (dutch time) I had to logg off for maybe 1-3minutes because I had to go and help my mom, then when I logged back In I Noticed chat said I had to have certain skill points like 20 agility to wear my gear, this Is wierd because I've used that armor the last few days without a problem.
My inventory was full of stuff because I was farming XP at the corrupted ores, but when I tried to look for my armor I couldn't find it, It was NOT In my inventory or on the ground.

I think It got deleted because wynncraft tried place It into my inventory, but when It noriced my inventory was full It decided to DELETE my LEGENDARY gold pants and UNIQUE bracelett and ring, these items were realy good.

I've made some screenshots of the Chat saying I didn't have High enough skill points, and I've talso included a screenshot of the say before what clearly show's I have around 390 more health (thats the amouth the lost items added) .
Ive added a screenshot with a burning horse on it, but if you look closly on that screesnhot at my health you will see i had 1700 health, that was with those Lost items

I would realy like it if I could get these Items refunded because The lost of these items Isn't my fault in any other way.

[http://imgur.com/a/X9gQ7](url)

**Comment by Grandoni7** [comment] 2016-02-21 11:48
the link thing didn't work, please use this...I'm realy sorry.

http://imgur.com/a/X9gQ7

**Comment by Odnod** [comment] 2016-02-21 11:53
I'm sorry for your loss, but wynncraft has a strict no-refund policy. This is also a duplicate of #4120

**Comment by Odnod** [comment] 2016-02-21 11:54
My best guess is that it happens because of lag.

**Comment by treeyo** [comment] 2016-02-21 12:14
Something similar happens to me when I log in, except I can still wear them. My bracelet, necklace, leggings and boots come off when I log in but I just plop them back on.

**Closed** 2016-02-21 14:43 UTC
