### ISSUE TITLE
Rideable pet bug.

### ISSUE THREAD

**Issue by Miiiikkel** [Wynncraft/Issues#6084] opened 2016-09-09 14:09 UTC
I wanna report this bug beacues i think it can be used against the rules in many ways.

It's easier if i explain the method beacuse thats actually the bug:

1. Take out your sliverfish pet.
2. "Right Click" It until your on it and it look like horse.
3. Ride around jump and actually just everything you can do on a horse.
4. Theres then a like 50/50 chance of you getting teleported under ground as far as you rode the horse.

EDIT: It actually sometimes happen when you jump off players heads too.

!I didn't use this bug on purpos my self, but did it one more time to see if it actually would happen again!
Hope it will help you. and it will be fixed.

**Comment by Trixter313** [comment] 2016-09-09 21:48
Where in the map were you when this happened to you? Also, what version of Minecraft are you using? We currently recommend 1.8.9 as using other versions causes issues with horses.

**Comment by Miiiikkel** [comment] 2016-09-09 23:38
Im using 1.8.9 i have been more than one place when it happend also in the new "???" Quest.
And i had to do /kill beacuse it bugged me out to flat world... And NO! it wasnt on purpos.

**Comment by ThunderRemix** [comment] 2016-09-09 23:56
Dupe of #2806

**Comment by Trixter313** [comment] 2016-09-10 11:56
@ThunderRemix I don't think those are the same issues.

@Miiiikkel when this happened to you did you dismount your horse in a small or low ceiling area? And are you sure you're being teleported under ground and not just into a wall? Thanks!

**Comment by Miiiikkel** [comment] 2016-09-10 12:45
Its like i get teleportet like 5-7 blocks under ground.
In the "???" area i dont know how many blocks there i under me, i just know that i got teleportet out in the air, and fell like 20 blocks after... Then i was stuck in a flat world.. and had to do /kill

**Comment by Miiiikkel** [comment] 2016-09-10 12:48
@Trixter313 And when it happend when i rode a player, i was like i only got into the floor and then fell down on a little platform, i then managde to get back into the room but jumping with my horse, i can't explain how this works.. i know this sound silly, but the only way would be for you to try it yourself. :)
Thanks for the responses so far :D

**Comment by Trixter313** [comment] 2016-09-11 14:23
I haven't been able to reproduce the issue, is it possible for you to post a recording of the bug?

**Comment by Miiiikkel** [comment] 2016-09-11 17:48
I will look into it :)
Should i just post a Youtube link afterwards of the video? :)

**Comment by Trixter313** [comment] 2016-09-11 17:54
Yes, that would be appreciated.

**Comment by Imaxe** [comment] 2016-09-27 10:54
Since the pet riding feature is no longer in game, I'll close this

**Closed** 2016-09-27 10:54 UTC
