### ISSUE TITLE
EXTREMELY ANNOYING GLITCH - Jungle Fever

### ISSUE THREAD

**Issue by judeclark** [Wynncraft/Issues#6915] opened 2016-12-17 23:03 UTC
In jungle fever, you receive 64 quest item LE when going through the almuj guards. but as I was right-clicking them, (out of pure boredom). one of them disappeared, giving myself 63 quest LE. AND FOR THIS REASON, I CANNOT DO THE QUEST!

HELP MODS & ADMINS!!!!

**Comment by thecoolkogut4** [comment] 2016-12-18 01:15
type `/fixquests` that might give you back the 1le.

**Comment by judeclark** [comment] 2016-12-18 08:57
it doesn't work..

 "You have no missing quest items... check your bank and other class inventories"

**Comment by Rellia** [comment] 2016-12-19 14:36
next time you get a daily chest, put the 63 le in the chest. Then try fixquests, or talk to the same person again

**Comment by Moe-Ronickah** [comment] 2016-12-21 18:50
DUPLICATE OF #5567. Follow the advice in there.
Oh, and you obviously took out an LE thinking that you could get a free LE and then found that you couldn't put it back in with the other 63 QUEST LE - the nbt data changed the moment that you tried to cheat Worid out of his "cure".

**Closed by Moe-Ronickah** 2016-12-21 18:50 UTC
