### ISSUE TITLE
Assassin skills

### ISSUE THREAD

**Issue by Lunarhelix** [Wynncraft/Issues#3220] opened 2015-12-27 00:41 UTC
While playing on wynncraft, I always liked assassin. I used its spin attack as a good stunner to prep for multi hit or smokebomb but I believe ever since the gavel update ( may be before but it didnt happen for me before) that the spin attack now makes the mobs go wild which was supposed to be the job of the multihit while multihits seems to stun them. Please fix I can't fully enjoy assassin when I play and notice issues with gameplay.

**Comment by Verret001** [comment] 2015-12-27 02:13
duplicate of https://github.com/Wynncraft/Issues/issues/3140
Make sure to use the **[directory](https://github.com/Wynncraft/Issues/issues/3197)** to make sure your not making duplicates.

**Closed** 2015-12-27 21:56 UTC
