### ISSUE TITLE
Cant join guild

### ISSUE THREAD

**Issue by BlueyMonster** [Wynncraft/Issues#5360] opened 2016-07-01 04:53 UTC
So I've been a victim of the glitches and bugs of Wynn

The story is that a few days ago... Me and my friends decided to quit a guild.
So one of my friends (ShadowLapiz), kicked me so #NoSoulPointsHarmed. 
Then he tried to invite me to his guild but he couldn't because it said I am in a guild.
But I am NOT in a guild and guildless...
So developers or admins or people who know codes...
Please fix this bug or glitch for me and the other people of Wynn
To make a better Wynn for you and us...

#KeepUpTheGoodWorkDevelopers

;)

**Comment by BlueyMonster** [comment] 2016-07-01 04:56
Oh yea forgot my IGN: Bluey_Monster

#GoodLuckDevelopers ;)

**Comment by YunoFGasai** [comment] 2016-07-01 06:52
The coder team is working on a fix for guilds, hopefully it will get fixed in the near update.

**Comment by Moe-Ronickah** [comment] 2016-07-01 08:56
Duplicate of #4245 .  As Yuno said, this is a well known problem with guilds and it is being worked on.  There is nothing that anyone can do about it, until the coding is fixed.

**Closed** 2016-07-01 08:56 UTC
Labels: Duplicate
