### ISSUE TITLE
I cant finish The Quest: The Lost!

### ISSUE THREAD

**Issue by Lukaros** [Wynncraft/Issues#5843] opened 2016-08-28 12:55 UTC
When I logged in all the letters that you need was gone. I tryd to talk to everybody that I need to talk to
but It did not work and in the quest book it just says: Find the last missing member of the crew
I tryd /fixquests but that would not work eighter 
What should I do???

**Comment by Moe-Ronickah** [comment] 2016-08-30 22:37
Duplicate of #5237

**Closed by Moe-Ronickah** 2016-08-30 22:37 UTC
Labels: Duplicate
