### ISSUE TITLE
Silverfish Dungeon out of the map glitch [MAGE TELEPORT]

### ISSUE THREAD

**Issue by iCeDaNoSH** [Wynncraft/Issues#1811] opened 2015-04-13 14:07 UTC
I found a glitch yesterday and it happened to me today as well.
At the first parkour On the left when you've walked along the hallway in the silverfish dungeon. There when you stand on the first block and use teleport to go up to the end of the parkour. By teleporting twice using the above part of the door and then teleporting up to the pressure plate, by teleporting against the wall. Sometimes you land in a halfslab. When you walk forward you walk out of the map. You can find minor pieces of redstone and basically just an area where there's no escaping but killing  yourself. I think this can be fixed by filling up the room or putting blocks around the slab. I found this really annoying because I lost several keys this way. IGN: iCe_DaNoSH

**Comment by AckroWynn** [comment] 2015-04-14 14:53
The instructions to reproduce it are a bit unclear, but I will try my best to try and solve this issue!
Thanks for noticing!

**Comment by AckroWynn** [comment] 2015-04-14 15:20
According to what it says here, I think the issue is now fixed on the build server.

**Comment by AckroWynn** [comment] 2015-04-14 21:23
Just to be very clear, please post a couple of pictures of how you do this, and what happens.

**Closed** 2015-04-17 15:23 UTC
