### ISSUE TITLE
Server says I am already logged in error

### ISSUE THREAD

**Issue by SaucySalad** [Wynncraft/Issues#8051] opened 2017-05-02 23:29 UTC
I'm logged off and now that I try to log in it says I'm already logged in when I'm not. I've already completely closed it and tried three times and it still doesn't work. Send help  S.O.S. -SaucySalad

**Comment by Trixter313** [comment] 2017-05-02 23:54
Duplicate of https://github.com/Wynncraft/Issues/issues/8050

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2017-05-02 23:54 UTC
Labels: Connection Issues
