### ISSUE TITLE
The spear called "Hunter" has no texture.

### ISSUE THREAD

**Issue by CerberucVic** [Wynncraft/Issues#6195] opened 2016-09-18 23:55 UTC
Today I was playing and found a spear. This spear has no texture, so I think that might be a bug. If someone had the same inssue, or if there is a way to fix that please answer me below. 
![2016-09-18_20 56 25](https://cloud.githubusercontent.com/assets/22283069/18620106/7d72c890-7de2-11e6-8657-2111f23fc0fa.png)

**Comment by Celsonic** [comment] 2016-09-19 20:07
Try reidentifying it. Might fix it.

**Comment by Trixter313** [comment] 2016-09-20 01:40
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

**Closed by Trixter313** 2016-09-20 01:40 UTC
