### ISSUE TITLE
Seeing Certain items while in the shops Before you Identify them

### ISSUE THREAD

**Issue by facepoke** [Wynncraft/Issues#4471] opened 2016-03-06 00:31 UTC
When i was interacting with the shops, there were items, that seems to be named such as the legendary chest plate called Blessed Warppings.

http://imgur.com/XNY1n0H

**Comment by RMH0131** [comment] 2016-03-06 00:42
shut up that's useful don't fix it please

**Comment by Odnod** [comment] 2016-03-06 01:16
Duplicate of #4059, please close this post and direct any additional comments to the original thread. Thanks!

**Comment by Moe-Ronickah** [comment] 2016-03-06 15:06
facepoke, do you remember which shop this happened in?

**Comment by facepoke** [comment] 2016-03-07 03:11
Well it happened in any of the shops

**Comment by DarkDemonDragon** [comment] 2016-03-07 12:37
Then this definitely is a duplicate of #4059

**Comment by Moe-Ronickah** [comment] 2016-03-11 04:52
@RMH0131 , please don't be rude.

**Closed by Moe-Ronickah** 2016-03-11 04:52 UTC
Labels: Duplicate
