### ISSUE TITLE
Skills not showing up

### ISSUE THREAD

**Issue by Dovahkiev** [Wynncraft/Issues#6966] opened 2016-12-22 01:23 UTC
Well there is this glitch that is happening to my character. Whenever I try to re-do my skill points they just go away. Not the points but the things I can use them on (Dexterity, Intelligence, etc). Plz fix!

**Comment by ColinRioux** [comment] 2016-12-22 02:27
Duplicate of #6782

**Closed by ColinRioux** 2016-12-22 02:27 UTC
