### ISSUE TITLE
Clicking in inventory will sometimes remove haste/mining fatigue

### ISSUE THREAD

**Issue by 0x0000null** [Wynncraft/Issues#7563] opened 2017-03-20 19:01 UTC
When you click anything in your inventory (even an empty slot), the haste or mining fatigue potion effect may randomly be removed or added back. This is annoying because when the potion effect is removed the whole inventory moves over, causing you to click on the wrong item if you're not careful.

**Comment by LordHelmchen98** [comment] 2017-03-20 19:17
Duplicate of #6844

**Closed** 2017-03-20 21:52 UTC
