### ISSUE TITLE
I get kicked when i do /dismiss

### ISSUE THREAD

**Issue by AndriX3S** [Wynncraft/Issues#6957] opened 2016-12-21 12:01 UTC
If i get a mision and i want to dismiss it and i type / dismiss it kicks me from the server.
![2016-12-21_12 03 56](https://cloud.githubusercontent.com/assets/24697187/21388671/99492fde-c77d-11e6-8e06-d21b66753ab9.png)

**Comment by Moe-Ronickah** [comment] 2016-12-21 12:37
The admin team is aware of this. It will stay open, even with no activity, until it is fixed.

**Comment by Trixter313** [comment] 2016-12-21 20:36
@Moe-Ronickah isn't this a duplicate of https://github.com/Wynncraft/Issues/issues/6938 ?

**Comment by Moe-Ronickah** [comment] 2017-01-03 00:58
Yes, it is a duplicate.
Missions have been disabled until this is resolved.

**Closed by Moe-Ronickah** 2017-01-03 00:58 UTC
Labels: Duplicate
