### ISSUE TITLE
Cant Leave A Guild

### ISSUE THREAD

**Issue by DeciDu** [Wynncraft/Issues#6837] opened 2016-12-04 23:47 UTC
I joined a guild a bit ago and my leader left and no one gets on. So i tried to leave but it just took the soul points. Any Fix or Solution?

**Comment by legoman724** [comment] 2016-12-05 12:45
You can try contacting wynncraft support but guilds are quite bugged at the moment in general so they may or may not help you

**Comment by LordHelmchen98** [comment] 2016-12-05 14:49
You have changed your name while being in the guild. Unfortunately this messes up some information and you get stuck in the guild. Probably there are hundreds of players who are stuck in their guilds and you won't get help by staff members. 
Also duplicate of #3665

**Closed** 2016-12-06 17:41 UTC
