### ISSUE TITLE
Ragni Guard.

### ISSUE THREAD

**Issue by Shucklee** [Wynncraft/Issues#4195] opened 2016-02-20 18:26 UTC
One of the Ragni's guard keep attacking ppl all the time (including me). Can u fix that Issue/problem?
![2016-02-20_19 10 41](https://cloud.githubusercontent.com/assets/17361035/13198385/cbce2cae-d807-11e5-9108-7c6a8b7fa3e8.png)

**Comment by Odnod** [comment] 2016-02-20 18:50
This has been an issue as long as Gavel has been out. It is an issue with the AI and cannot be resolved too simply.

**Comment by TrashcanMan** [comment] 2016-02-21 01:05
@Odnod Actually I think it should be pretty easy to fix, it appears that they just assigned it the wrong AI (hostile AI instead of friendly AI).

**Comment by HaveThomeCandy** [comment] 2016-02-21 08:00
they usually stop if you leave Ragni

**Comment by Shucklee** [comment] 2016-02-21 12:47
He will follow you until you are out of his range. :)
21. feb. 2016 09:05 skrev "HaveThomeCandy" <notifications@github.com>:

**Comment by AckroWynn** [comment] 2016-02-22 07:40
@TrashcanMan
Actually, whenever it's a Guard or Ally, it receives a blue name, which means it is not a GM's fault. There is something wrong with this one particular mob's AI, which can only be solved by Jumla.

**Comment by DarkDemonDragon** [comment] 2016-02-22 13:12
@TrashcanMan it happens randomly. In Ragni Outskirts where there are a bunch of guard NPCs roughly 1 out of 5 will become hostile if you attack them. Considering that most players are under lv 3 at this point that can be deadly. I'm not sure if specific mobs have a messed up AI or the AI in general is broken, but it's not a simple issue.

**Comment by Blocktopia9** [comment] 2016-04-13 19:32
I think it's because they're neutral mobs

**Comment by Moe-Ronickah** [comment] 2016-05-05 02:48
Just a note: the issue is still going on.

**Comment by XavierEXE** [comment] 2016-07-22 04:15
This is still an issue, but the guards don't seem to do any damage to the player.

**Comment by Moe-Ronickah** [comment] 2016-07-22 05:11
Now, if they would just leave Bob's ghost alone.

**Closed** 2016-10-23 17:31 UTC
Labels: Entities
