### ISSUE TITLE
/guild xp

### ISSUE THREAD

**Issue by guillau213** [Wynncraft/Issues#2288] opened 2015-09-12 21:23 UTC
Hey, I farm for 2 hours near Lusuco, it says that I won guild XP... and I didn'T won any... Example: 0 xp and 97 guild xp. I do /guild info and it says nothing... After 1 month. Please fix it!

**Comment by TrashcanMan** [comment] 2015-09-13 02:33
Duplicate of #2074. The staff is working on this one, just be patient.

**Closed** 2015-12-25 20:40 UTC

**Comment by Kidgib5** [comment] 2016-02-05 23:17
Is this a 5 month repair process? Still an issue.
