### ISSUE TITLE
Duplication bug/ Inventory loss?

### ISSUE THREAD

**Issue by gardendread4050** [Wynncraft/Issues#5346] opened 2016-06-29 18:04 UTC
I think this is new, but when I did /class to my mage, my mage's inventory got duplicated on to my mage (meaning that everything inside the inventory was the same as my warrior's, everything originially on my mage was lost (including armor and accessories)). But the level of my mage and the spells and the mechanics were still intact.

**Comment by Trixter313** [comment] 2016-06-29 18:08
I only remember it being reported one other time, here https://github.com/Wynncraft/Issues/issues/4790

**Comment by gardendread4050** [comment] 2016-06-29 18:09
Just as to say what I lost and what I gained, I lost 2 27% loot and 26% loot bonus rings, and Kayde with 9% xp bonus, a Altium Spacium with the ID's 12% reflection and 18% xp bonus, A 41% xp bad wolf with +90 regen, a Jera with 40% loot bonus and 7% xp bonus, a Changeling chestplate with 16% xp bonus and a Restored Ancient helmet with 17% xp bonus. I gained everything in my warriors inventory, which is a full inventory of rare and legendary armor (bank class). Thanks for reading

**Comment by gardendread4050** [comment] 2016-06-29 18:11
If there is a way to get my stuff back it would be greatly appreciated!

**Comment by gardendread4050** [comment] 2016-06-29 22:45
Just to add on I also had a 34% spell damage ethereal with 2/4 mana regen

**Comment by Moe-Ronickah** [comment] 2016-06-29 22:52
"If there is a way to get my stuff back it would be greatly appreciated!"
I'm sorry, but we have no way to refund items, nor does anyone else.  Wynncraft has a no-refunds policy, so, even if someone could, they wouldn't be allowed to, anyone.

This issue is a duplicate of #4790 .  Please follow the issue on that thread.

**Closed by Moe-Ronickah** 2016-06-29 22:52 UTC
Labels: Duplicate

**Comment by gardendread4050** [comment] 2016-06-29 23:27
Okay. Thanks for replying!
