### ISSUE TITLE
Quest not possible to complete (Potion making)

### ISSUE THREAD

**Issue by etoinedevries** [Wynncraft/Issues#2854] opened 2015-12-22 13:55 UTC
Hi everyone, since the Gavel update you can't get 'potion of healing I' potions anymore. You need these potion for the quest "Potion making" though, so I can't finish that quest. 
Thanks for reading this!

**Comment by Trixter313** [comment] 2015-12-23 02:17
Duplicate of #2725

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!

**Closed** 2015-12-25 20:34 UTC
