### ISSUE TITLE
Can't Leave Guild

### ISSUE THREAD

**Issue by ElitePlayer** [Wynncraft/Issues#4496] opened 2016-03-08 02:00 UTC
I tried to do /guild leave and typed yes in the sign mutilple times. All that happened is I lost 3 soul points but I'm still in the guild? Is the a bug?

**Comment by Moe-Ronickah** [comment] 2016-03-11 04:36
Yes, it is a bug.
Duplicate of #4320 .

**Closed by Moe-Ronickah** 2016-03-11 04:36 UTC
