### ISSUE TITLE
There has been an error... Try again

### ISSUE THREAD

**Issue by Lixy12** [Wynncraft/Issues#4087] opened 2016-02-11 22:13 UTC
I haven't been able to play on my account because there is a problem with "New players"
When you select a class (any class) it says There has been an error... Try again in the chat. It is not a simple problem like "Oh fix your internet" Its the server. This needs to be fixed ASAP. Your players are being lost because of this problem, This is the oldest and growing problem on Wynn craft. This is not a duplicate of any other. This is the most "Well" explained one of this problem. I still have this server on my server list after 3 months. And nothing has changed. Well done Wynn craft.

                  
                                                            Your reporter, friend and truly.
                                                                                                        -Lixy

**Comment by DarkDemonDragon** [comment] 2016-02-12 13:17
@Dar-krusos I think you're familiar with this old issue.

**Comment by Trixter313** [comment] 2016-02-12 23:24
Duplicate of https://github.com/Wynncraft/Issues/issues/3139

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-12 23:24 UTC
