### ISSUE TITLE
Quest items doesn't drop

### ISSUE THREAD

**Issue by Fapsik** [Wynncraft/Issues#4461] opened 2016-03-05 19:43 UTC
My friend do quest WynnExcavation Site C and when he go pick some crystals, crystals doesn't spawn... can you repair this bug ? Thx :)

**Comment by Trixter313** [comment] 2016-03-05 20:12
Duplicate of #4236 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-05 20:12 UTC
