### ISSUE TITLE
Glitched Mooington

### ISSUE THREAD

**Issue by Crazysickmonkey** [Wynncraft/Issues#6215] opened 2016-09-20 21:21 UTC
Alright so i am doing the quest Bob's Reincarnation and when i started it it told me to go and find 3 items 1 of those items being mooingtons leather and when i reach skeins island i search for it when i find him it shows me to drop a key into the hopper so i kill a warden get the key drop it into a hopper and then nothing happens i dont think i am the only person who have delt with this problem please help i want to do this quest

**Comment by SrT3J4S** [comment] 2016-09-21 15:11
I have the same problem.... Staff Please fix this.... I need that bobs wand

**Comment by Trixter313** [comment] 2016-09-23 11:04
Duplicate of https://github.com/Wynncraft/Issues/issues/6172

**Closed by Trixter313** 2016-09-23 11:04 UTC
