### ISSUE TITLE
Stuck in an inactive guild

### ISSUE THREAD

**Issue by RealStrafeZ** [Wynncraft/Issues#5457] opened 2016-07-11 16:46 UTC
So,i'm stuck in this inactive guild ( literally no one has entered for 4 months ) and whenever I try to leave,well,i cant.My name is Strafeeeee and please kick me out of this guild.The guilds name is Outcasts/OTC.Please mods,make me proud <3

**Comment by sammyvsparks** [comment] 2016-07-11 19:47
@RealStrafeZ It can take a few tries to leave. How many times have you tried? I've had to do it over 5 times before.

**Comment by Moe-Ronickah** [comment] 2016-07-12 13:05
@RealStrafeZ , is your current MC name GoldenLife?

**Comment by IncBear101** [comment] 2016-07-12 17:16
You're so active Moe_Ronickah

**Comment by YunoFGasai** [comment] 2016-07-12 17:28
@IncBear101 moe is asst. admins, he better be active.

**Comment by RealStrafeZ** [comment] 2016-07-13 09:35
Moe,i said in the post that my name is STRAFEEEEE ( 5 of e )

**Comment by Moe-Ronickah** [comment] 2016-07-14 07:01
@RealStrafeZ , at no time, in this issue, have you said that.  In any event, you've changed your MC name four times this year.

Duplicate of #3665

**Closed by Moe-Ronickah** 2016-07-14 07:01 UTC

**Comment by Moe-Ronickah** [comment] 2016-07-14 14:26
Strange, I don't remember seeing your name in the post, yesterday.  Maybe I overlooked it.  Let's just chalk it up to my reading your post to fast, and too late at night.

**Comment by IncBear101** [comment] 2016-07-15 16:26
Who's Nathan stolov? My email from GitHub issues say its from Nathan

**Comment by sammyvsparks** [comment] 2016-07-15 16:44
@IncBear101 Nathan is Moe-Ronickah

**Comment by IncBear101** [comment] 2016-07-15 16:48
Oka

**Comment by Radiantal** [comment] 2017-05-28 11:20
Could you help me as well, my username is Radiantal
