### ISSUE TITLE
Hourglass sand not Spawning!

### ISSUE THREAD

**Issue by MrBeanyGuy** [Wynncraft/Issues#4359] opened 2016-02-29 16:48 UTC
When I go to Selchar to retrieve 12 Hourglass Sand, it won't spawn.
I've looked in the Wiki on how to complete the quest (Sister City), thinking I'm doing something incorrect. But the sand just won't spawn.

**Comment by Moe-Ronickah** [comment] 2016-02-29 20:58
Duplicate of Quest Items Are Not Spawing #4236 .  Please refer all future comments to the original thread.

**Closed by Moe-Ronickah** 2016-02-29 20:58 UTC
Labels: Duplicate
