### ISSUE TITLE
All Items Reset

### ISSUE THREAD

**Issue by Weymere** [Wynncraft/Issues#2085] opened 2015-07-11 23:45 UTC
I already opened a post on this, but for some reason it was pegged as duplicate and closed any solution working, or any reason for this. I am horribly disappointed in this, as well as the fact that my email to Wynncraft Support was never replied to. It has been several weeks, so this is just horrid. Anyway, all of my items were reset and I was sent back to the regular start zone with nothing, but the start gear and all my levels and quest progress for some reason. /fixquests doesn't work and I would really appreciate a response, but if this gets closed again for no reason, I will be very sad and quit the server :( Also, I searched related keywords to find a thread that mine was "duplicating", but found nothing. Please give me a response, but if need be, I would be okay with completely resetting all of my characters, as this problem happened to all of my classes. Thank you.

**Comment by Moe-Ronickah** [comment] 2015-07-12 04:26
I don't know what happened, but perhaps this is a duplicate of #996, and you are the victim of a server rollback?

**Comment by Trixter313** [comment] 2015-07-16 12:14
Are you actually stuck there, or can you go to Ragni and get out? If you're stuck, typing /kill might get you out. If not, as a last resort, you can try typing /fixquests . The last command isn't likely to do anything but it's worth a try.

**Closed** 2015-08-17 07:08 UTC
