### ISSUE TITLE
The Guild Master Eats all my emeralds

### ISSUE THREAD

**Issue by MrWifiman** [Wynncraft/Issues#3273] opened 2015-12-28 13:26 UTC
Well.... I know theres no refund policy in Wynncraft but this is really pissing me off. Whenever I hold my 5 LE in my inventory and click on the Guild Mater it will ask me to type my guild name on the sign while when I press ESC and try to cancel it and it never does and keep popping back in for like few seconds. Then I access my bank enderchest and put back my LE hopefully I can stop it and After putting it back the sign pop up again and all my LE is gone.... I had 4X LE and all gone right now i'm depressed :( Can anyone suggest anything that I can do :/

**Comment by Verret001** [comment] 2015-12-28 22:44
Try joining a differn't server. If that doesn't work there isn't much you can do.
There is also a possiblility that you droped it

**Comment by Trixter313** [comment] 2015-12-29 21:57
Duplicate of https://github.com/Wynncraft/Issues/issues/3190

Please direct any further comments to the original issue. Thanks!

**Closed by Trixter313** 2015-12-29 21:57 UTC
Labels: duplicate
