### ISSUE TITLE
Can not finish quest-The Lost due to a bug

### ISSUE THREAD

**Issue by frasonia** [Wynncraft/Issues#7072] opened 2017-01-02 09:59 UTC
I was doing The Lost quest and I just gave the last lost cannyon explorer the message (the one on the tower) but at the same time the server crashed or lagged out. For a few seconds everything was frozen then we all got disconnected on that specific server. Now i dont have any of the messages and whenever I talk to to any of the NPCs they say I have one more to find.

**Comment by thecoolkogut4** [comment] 2017-01-02 15:18
what does your quest book say?

**Comment by ColinRioux** [comment] 2017-01-02 17:15
Duplicate of #6670

**Comment by frasonia** [comment] 2017-01-02 19:13
Its telling me to find the last member

**Closed** 2017-01-18 23:03 UTC
Labels: Duplicate
