### ISSUE TITLE
Quest: beneath the depths

### ISSUE THREAD

**Issue by Lorigami** [Wynncraft/Issues#4393] opened 2016-03-01 23:18 UTC
The map in the skull cave isn't spawning. I went through the thing twice, plus a third time on another server. Im not sure if it's a personal glitch or a faulty spawn, but if an mod or GM or something could help that would be lovely

**Comment by Crafterbird2** [comment] 2016-03-01 23:38
The same thing happened to me as well. This also happened with the WynnExcavation Site C with the Fire Crystal drop.

**Comment by Lorigami** [comment] 2016-03-01 23:38
Its rather annoying. Just want it fixed

**Comment by Odnod** [comment] 2016-03-02 06:52
Duplicate of #4236, please close this issue and put any additional comments on the original. Thanks!

Please know that this bug is very well known and is being worked on.

**Closed** 2016-03-02 07:45 UTC
Labels: Duplicate
