### ISSUE TITLE
Cannot leave guild

### ISSUE THREAD

**Issue by Dubinzi** [Wynncraft/Issues#7928] opened 2017-04-19 01:04 UTC
I have tried four times over the past few days to leave my guild. Each time, it says that I have left the guild, but when I try to join a new guild, I am given an error message that says "You must leave your current guild to join a new guild". I also noticed that after I tried to leave the guild, using /g [message] would show my message twice.

**Comment by thecoolkogut4** [comment] 2017-04-19 01:09
this is because you have changed your name while you were in the guild. *on the rare occasion you dont have to change your name* and this results in you being in the guild twice which explains the double chat. you will not be able to leave the guild intill they update guilds. there are 100's of people in your situation.

**Comment by LordHelmchen98** [comment] 2017-04-19 02:02
Also duplicate of #3665

**Closed by LordHelmchen98** 2017-04-19 02:02 UTC
