### ISSUE TITLE
Temple Of Legends (Quest)

### ISSUE THREAD

**Issue by GodlySkull** [Wynncraft/Issues#4248] opened 2016-02-24 15:30 UTC
# Delete this line if you've searched for a duplicate issue first
So there is a part where you have to get ligning dust. it does not spawn at the place it should be.

**Comment by Odnod** [comment] 2016-02-24 15:42
Duplicate of #4236 please close this and put any additional responses on the original thread, thanks.

**Closed** 2016-02-24 15:44 UTC

**Comment by DarkDemonDragon** [comment] 2016-02-24 15:54
Duplicate of #4236 Please close this and follow the original
