### ISSUE TITLE
My Twain Journal Is Missing!

### ISSUE THREAD

**Issue by minecrafthouse62** [Wynncraft/Issues#3439] opened 2016-01-01 19:47 UTC
My twain journal is missing, and to my understanding I need a quest item from that quest for the temple of legends, I have not finished the house of twain! Help!

**Comment by DarkDemonDragon** [comment] 2016-01-01 19:58
To prove that you actually had the journal, please explain how you obtained the journal. The reason I'm asking is because this is not a bug related issue due to how the journal is normally obtained. If you answer incorrectly I will ask a staff to close this as you are asking for a refund for an object that doesn't need to be refunded if you've obtained it already.

**Comment by Trixter313** [comment] 2016-01-01 20:00
The journal isn't one of the required items for the Temple of Legends and I don't think you're supposed to get the journal after you're done so if you did the quest but don't have the journal everything is fine and working as intended.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Closed** 2016-01-01 20:40 UTC
