### ISSUE TITLE
not getting dungeon reward

### ISSUE THREAD

**Issue by STMElmo** [Wynncraft/Issues#3276] opened 2015-12-28 14:36 UTC
I don't know if this is consistant or not but i have had it happen twice in 10 minutes.
sometimes after beating the boss of a dungeon i will be teleported back without getting any of the rewards. no XP, no falling emeralds and no Key to the next dungeon.
i hope this will be fixed

**Comment by DarkDemonDragon** [comment] 2015-12-28 15:15
Yea I've been experiencing this a bunch too. Try to go on servers without heavy lag. While you don't receive the next key or drops, you do receive xp.

**Comment by STMElmo** [comment] 2015-12-28 20:36
thx, i do thnk i had a lot of lagg on that server

**Comment by Verret001** [comment] 2015-12-28 21:49
It is not lag.
Is this what happened to you?
https://github.com/Wynncraft/Issues/issues/3246
Or #3227 #3242

**Comment by DarkDemonDragon** [comment] 2015-12-29 00:51
@Verret001 are you on the wrong issue? He's talking about a dungeon (Skeleton. Spider, Animal, etc.) not a quest.

**Comment by WorseWaif** [comment] 2015-12-29 17:40
This just happened to me with the zombie dungeon, and has happened to me a few times with the other dungeons as well. its very aggravating to know i just wasted time and the key for nothing.

**Comment by Trixter313** [comment] 2016-01-24 07:31
Is this issue still occurring?

**Comment by Trixter313** [comment] 2016-01-30 02:41
I just tested and got the correct things every time after about an hour of constant dungeons, 3 different dungeons so I believe the issue is now fixed. If anyone still experiences this, just comment below and I'll reopen the issue. Thanks!

**Closed by Trixter313** 2016-01-30 02:41 UTC
Labels: Game Mechanics, Items

**Comment by Simonomi** [comment] 2016-07-07 17:21
i did the zombie dungeon and got nothing on a server with only 35 or so people on pease help

**Comment by Moe-Ronickah** [comment] 2016-07-08 00:27
@Simonomi , this issue was closed almost 5 months ago.  Please open a new issue, and refer to this one, if this is still happening to you.
