### ISSUE TITLE
Can't join the server anymore

### ISSUE THREAD

**Issue by xPanduz** [Wynncraft/Issues#5287] opened 2016-06-23 12:37 UTC
Dear administrators, i'd like to post this issue due to the error that appears me everytime i try to join the world. Here it is the image of the error.
![schermata 2016-06-23 alle 14 34 41](https://cloud.githubusercontent.com/assets/19982429/16303232/f2026c56-394f-11e6-86f4-c0d779f5c0a1.png)

**Comment by Trixter313** [comment] 2016-06-23 12:42
Duplicate of https://github.com/Wynncraft/Issues/issues/5280

Wynncraft reccomend you use 1.8 to play. Anything else, we can't help you because it isn't officially supported yet.

Let us know of downgrading helps. Thanks!

**Comment by xPanduz** [comment] 2016-06-23 12:43
Oh sorry i looked for the posts but didn't see that one... Thank you, i'll play with 1.8!

**Closed by Trixter313** 2016-06-23 12:42 UTC
