### ISSUE TITLE
Assassin Spin Attack on Frozen Ice Snake Mobs Glitch

### ISSUE THREAD

**Issue by PhungMaster** [Wynncraft/Issues#5788] opened 2016-08-21 01:59 UTC
So I frequently play with my brother who is a mage and we grind together. But the problem is that when he ice snakes, which freezes the enemies, then I use spin attack on the frozen enemies I get frozen because of me stealing the enemies effects. The problem is is that I should only be taking the positive effects and not the negative ones like freezing which is really weird.

**Comment by Trixter313** [comment] 2016-08-21 02:12
Duplicate of https://github.com/Wynncraft/Issues/issues/5750

**Closed by Trixter313** 2016-08-21 02:12 UTC
