### ISSUE TITLE
WynnExcavation Site B plz reed updated

### ISSUE THREAD

**Issue by MrMaggen** [Wynncraft/Issues#4276] opened 2016-02-25 20:07 UTC
I was doing quest and wanted to do Site B quest I used the yello crystal and ran down the mine to the man that punched me down a hole and got down walked to the man that talks about how to get in to the crystal got in to the crystal but there were no littel ones so I thoght I was lagging and ran out the back i accidently clicked the first man and then he said "Hello there! We are working very hard here at this Excavation site! We have one in Almuj as well, I think you should check i out!" and then my quest book said what I had to speak to him but then I did it he said the same thing and then I got down to the crystal it still did not drop and and the quest npc did not work it does not fix it when I relog or do /fixguest plz help me I have No Idea and I want to do the quest :(

**Comment by Odnod** [comment] 2016-02-25 20:09
Please add content?

**Comment by MrMaggen** [comment] 2016-02-25 20:23
Here you can see I have the crystal and it says I have to talk to him and it does not work

![2016-02-25_21 22 13](https://cloud.githubusercontent.com/assets/17232865/13333186/0bce424c-dc06-11e5-8ad7-eba065d66f92.png)

**Comment by Odnod** [comment] 2016-02-25 20:25
Duplicate of #4236, please close this thread and direct any additional comments to the original thread. Thanks!

**Closed** 2016-02-25 21:25 UTC
