### ISSUE TITLE
Hole with missing ladders at Maro Peaks

### ISSUE THREAD

**Issue by RealNeuhier** [Wynncraft/Issues#5235] opened 2016-06-15 17:06 UTC
I found a hole at the cave where Baab is found
http://puu.sh/ptMSe/78b6fddda2.png
Some ladders are missing, you can't get out there without being an Archer

**Comment by Moe-Ronickah** [comment] 2016-06-16 02:38
DUPLICATE of #4041

**Closed by Moe-Ronickah** 2016-06-16 02:38 UTC
Labels: Duplicate
