### ISSUE TITLE
Before update chestplate

### ISSUE THREAD

**Issue by Spike71137** [Wynncraft/Issues#3864] opened 2016-01-26 03:29 UTC
I have a chestplate that looks like it was made before the gavel expansion.

**Comment by meatloaf4311** [comment] 2016-01-26 04:04
Well, what is it?

**Comment by Spike71137** [comment] 2016-01-26 04:07
It's called montefiore

**Comment by Dar-krusos** [comment] 2016-01-26 07:51
This is a duplicate of #3175. Please see [the directory](https://github.com/Wynncraft/Issues/issues/3197) before posting an issue so that there are no duplicates. If you have items that have this problem that no-one has posted yet, post it there.

**Closed** 2016-01-27 02:29 UTC
