### ISSUE TITLE
Horse gets stuck but character keeps traveling

### ISSUE THREAD

**Issue by DaCreeperBusters** [Wynncraft/Issues#5310] opened 2016-06-26 08:47 UTC
Upon riding on a horse in [(1.8.4);(1.9.2);(1.9.4);(1.10);(1.10.2)], the horse will hit a block and get stuck, but you can keep riding the horse as if it didn't. However, your character will be stuck on the block, where mobs can hurt you, and if you dismount the horse, you will end up where you got stuck. It gets pretty annoying over longer rides.

**Comment by Trixter313** [comment] 2016-06-26 16:47
Duplicate of https://github.com/Wynncraft/Issues/issues/5188

Try using 1.8.9. This has only been reported as an issue with Minecraft versions higher than 1.8 so it's odd that 1.8.4 is doing it for you but trying 1.8.9 out wouldn't hurt. As for the later versions, we reccomend using 1.8 for Wynncraft and if you use anything higher it is at your own risk. For support with issues, make sure you are using nothing higher than 1.8.

Let us know if trying 1.8.9 out helps at all. Thanks!

**Closed by Trixter313** 2016-06-26 16:47 UTC
