### ISSUE TITLE
Dune Beast Drop cant be picked up?

### ISSUE THREAD

**Issue by Ecstatics** [Wynncraft/Issues#6154] opened 2016-09-16 06:14 UTC
I killed the Dune Beast in the sand swept tombs and instead of getting a gold coin i got his hammer dropped. It wont allow me to pick it up. Everything has been cleared from time but the hammer remains.

**Comment by Ecstatics** [comment] 2016-09-16 06:16
![screen shot 2016-09-15 at 8 03 05 pm](https://cloud.githubusercontent.com/assets/22232005/18576906/3cc36d44-7b81-11e6-8ee3-73eb6e8a7b02.png)

**Comment by Ecstatics** [comment] 2016-09-16 06:55
![screen shot 2016-09-15 at 8 17 54 pm](https://cloud.githubusercontent.com/assets/22232005/18577651/c66b2b0e-7b86-11e6-88c7-829e50dca1cd.png)

**Comment by Trixter313** [comment] 2016-09-16 10:49
Appears to be a duplicate of https://github.com/Wynncraft/Issues/issues/5534

This is intended behavior.

**Closed by Trixter313** 2016-09-16 10:49 UTC
