### ISSUE TITLE
A hole in Wynncraft Excavation site C

### ISSUE THREAD

**Issue by GaPoiVN** [Wynncraft/Issues#4752] opened 2016-04-04 09:59 UTC
I found a hole in Wynncraft Excavation site C at the beggining , Its reval the redstones stuff 
Here is the picture : http://imgur.com/qMUQyoP
bad english sry :P

**Comment by TrashcanMan** [comment] 2016-04-04 23:05
Is it there on all servers? Sometimes one or two servers will have glitches while the rest are fine.

**Comment by BlueThunder25** [comment] 2016-04-05 18:39
Please close this issue if the problem is resolved

**Comment by Verret001** [comment] 2016-04-09 19:55
No replies in 4 days. Please repost if this is still a issue

**Closed by Verret001** 2016-04-09 19:55 UTC
