### ISSUE TITLE
Wrong Username?

### ISSUE THREAD

**Issue by NinjaMaster909** [Wynncraft/Issues#4956] opened 2016-05-06 20:46 UTC
This bug isn't really associated with the server itself, it's a forum bug. So I tried changing my custom title, and when I tried saving it, it said my username was incorrect, which was weird, because the username slot had my username in it already. So I try deleting the username and retyping it. It still doesn't work. Could someone please help me with this? I don't want to be forever known as a "Newbie Adventurer"

**Comment by Trixter313** [comment] 2016-05-06 22:31
Duplicate of https://github.com/Wynncraft/Issues/issues/4940

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-05-06 22:31 UTC
