### ISSUE TITLE
WynnExcavation Site C Glitch With Crystals

### ISSUE THREAD

**Issue by MC-Tr0ll3r** [Wynncraft/Issues#4456] opened 2016-03-05 15:24 UTC
So when I was doing the _WynnExcavation Site C_ quest and got to the bottom of the volcano there were no crystals, And to make sure someone wasn't just there I went server hoping and still nothing spawned but the mobs.

**Comment by Trixter313** [comment] 2016-03-05 15:59
Duplicate of https://github.com/Wynncraft/Issues/issues/4236

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-05 15:59 UTC
