### ISSUE TITLE
Can't log into my main 

### ISSUE THREAD

**Issue by BaconPai** [Wynncraft/Issues#6518] opened 2016-10-30 22:59 UTC
Hey I haven't played Wynncraft in like a year and I wanted to try it again. Sadly this happened: https://www.youtube.com/watch?v=XDxFzgTlwWo&feature=youtu.be. Please help :)

**Comment by Surra-1** [comment] 2016-10-31 15:08
Duplicate of #5418

Go to that page for a full explanation on what bug you are experiencing.

**Closed** 2016-11-05 18:52 UTC
