### ISSUE TITLE
Class Screen Bug

### ISSUE THREAD

**Issue by Pyromanical** [Wynncraft/Issues#6693] opened 2016-11-15 02:26 UTC
On my level 101 warrior, the /class screen says I have finished 113/113 quests, however, I haven't finished two quests.  This only happened after I reached 101, on 100 it  was 111/113.
![screen shot 2016-11-14 at 8 23 48 pm](https://cloud.githubusercontent.com/assets/21978993/20290906/a12caaec-aaa8-11e6-8f3c-29208221ff43.png)
![screen shot 2016-11-14 at 8 24 07 pm](https://cloud.githubusercontent.com/assets/21978993/20290908/a46a8dfa-aaa8-11e6-8897-a0b1189bd874.png)

**Comment by thecoolkogut4** [comment] 2016-11-15 02:39
that counts quests that you have started. you have 111/113 quests done and 2 quests started that = 113/113.

**Comment by Pyromanical** [comment] 2016-11-15 03:20
I'm almost certain when I wasn't on 101, and had started those quests it said 111/113, but I could be wrong.  Also, that wouldn't make sense, why would unfinished quests count to the finished quest number?

**Comment by thecoolkogut4** [comment] 2016-11-15 13:16
I know it doesint make sense but that's how it is :/

**Comment by Moe-Ronickah** [comment] 2016-11-17 03:07
Duplicate of #2906, but not high on the fixit list.

**Closed by Moe-Ronickah** 2016-11-17 03:07 UTC
Labels: Duplicate
