### ISSUE TITLE
Wynncraft Soul Points Bug

### ISSUE THREAD

**Issue by RussellTheEndbringer** [Wynncraft/Issues#5354] opened 2016-06-30 21:26 UTC
Hi everyone,
I'm new to the forums here, but not to Wynncraft itself. I lost seven soul points on death and lost all of my items. If you all want any other information, I died in the Dark Forest in gavel. I lost my lvl 40-49 armor and my other items (not my Waves Raiser for some reason.) Anything I can do about this would be helpful, thanks!

**Comment by Moe-Ronickah** [comment] 2016-07-01 01:23
Duplicate of #4039.  Unfortunately, this issue is still alive.
Please follow this issue on the original post.

**Closed** 2016-07-01 01:23 UTC
Labels: Duplicate
