### ISSUE TITLE
Shop Bug?

### ISSUE THREAD

**Issue by AyyItsSteven** [Wynncraft/Issues#6593] opened 2016-11-05 20:43 UTC
Ok So i don`t know if this is me or the server, it`s been happening since yesturday, when i go to a merchant like for example scroll merchant it shows the item but it doesn`t show the price for the item, or sometimes it says mc12 in purple i really don`t know what`s going on. and it`s happening in all cities detlas, selchar, nessak, everywhere. i`ll show a screenshot so you know what i mean.
![2016-11-05_16 38 51](https://cloud.githubusercontent.com/assets/23284059/20033446/e4f7a472-a376-11e6-8bfb-29b2a227c6e8.png)

**Comment by Trixter313** [comment] 2016-11-05 20:46
Duplicate of https://github.com/Wynncraft/Issues/issues/6575

It should be fixed on all servers within a few hours by the recent patch.

**Closed by Trixter313** 2016-11-05 20:46 UTC
