### ISSUE TITLE
Powder Relic Shrines

### ISSUE THREAD

**Issue by PhungMaster** [Wynncraft/Issues#5920] opened 2016-08-30 19:51 UTC
For some reason the shrines don't give the relic tier it's supposed too. I don't know if this is supposed to be normal for the new update but can somebody pls confirm

**Comment by Trixter313** [comment] 2016-08-30 22:33
Duplicate of https://github.com/Wynncraft/Issues/issues/5852

**Closed by Trixter313** 2016-08-30 22:33 UTC
