### ISSUE TITLE
When I try to log on my assassin I get an error message

### ISSUE THREAD

**Issue by RLLL93** [Wynncraft/Issues#7693] opened 2017-04-08 07:26 UTC
![2017-04-08_09 23 50](https://cloud.githubusercontent.com/assets/27051481/24826752/4aabf518-1c3d-11e7-8575-9d7998468167.png)

**Comment by WindowsEXE** [comment] 2017-04-09 07:00
#7705

**Comment by ColinRioux** [comment] 2017-04-09 20:13
Duplicate of #7680. Please see #7680 for future updates.

**Closed by ColinRioux** 2017-04-09 20:13 UTC
