### ISSUE TITLE
My Bank has never worked

### ISSUE THREAD

**Issue by ImaMusicGeek** [Wynncraft/Issues#2076] opened 2015-07-07 18:55 UTC
I am unable to take items out of my bank. I have tried pretty much everything and nothing worked. I accidently put my creeper mask in there and I cannot get it out and I know that I will need it for a later quest. please help me!

**Comment by epicman739** [comment] 2015-07-08 00:33
What methods of fixing the issue have you tried so far?

**Comment by ImaMusicGeek** [comment] 2015-07-08 00:49
I have restarted my minecraft, redownload minecraft, deleted wynncraft.not sure what else. the only other people with this problem all have music in their name so im not sure if that has something to do with it.

**Comment by HiddenMusician** [comment] 2015-07-10 12:52
I have had this same problem. I cannot take anything out of my bank. But I have found that if you have a stackable item in the bank, you can double right click with the same item already in your inventory forces the item to come out. Luckily I can store emeralds in my inventory. My in game name is HiddenMusician so your comment got me thinking.If somehow the username having music in it, maybe doing a name change might help. I hope we can get to the bottom of this problem.

**Comment by ImaMusicGeek** [comment] 2015-07-10 23:22
I do too, I hope that someone out there can help

**Comment by Moe-Ronickah** [comment] 2015-07-11 20:15
This is a duplicate of #824 .  How the problem was fixed at that time, is not noted.  It sounded then as if any name that had "Music" in it had the same problem of removing anything from an Enderchest.  Perhaps, if someone who was around then and remembers how this was fixed, would sing out, it would help.

**Comment by HiddenMusician** [comment] 2015-07-11 20:42
I am going to try changing my minecraft username to something without "music" in it and I will report back after using a couple tests. Hope this works!

**Comment by ImaMusicGeek** [comment] 2015-07-11 20:59
Please report back what you find out!

**Comment by HiddenMusician** [comment] 2015-07-11 22:32
IT WORKS!!! I changed my name from HiddenMusician to xxHMGamingxx and my bank now works! I am not 100% sure it will work for you but it is always possible!

**Comment by ImaMusicGeek** [comment] 2015-07-11 23:59
IT WORKED! I changed my name to ImaMuzicGeek and know I can use my bank! thanks for the tip HiddenMusician.

**Closed** 2015-07-12 00:00 UTC

**Comment by TrashcanMan** [comment] 2015-07-13 21:01
@Tama63 you might want to have a look at this one, the "music" in the username thing is probably not a coincidence.
