### ISSUE TITLE
Indentification Bug

### ISSUE THREAD

**Issue by banditguy123** [Wynncraft/Issues#1991] opened 2015-06-12 02:18 UTC
My Helmet Named Pelier is not able to be indentified, i believe this is a bug with this helmet only

**Comment by Trixter313** [comment] 2015-06-12 02:31
Duplicate of https://github.com/Wynncraft/Issues/issues/1312
If you believe that this issue is the same as yours, it would be great if you would close this one and follow it instead. Thanks!

**Closed** 2015-06-12 05:25 UTC
