### ISSUE TITLE
Decrepit Sewers WTF

### ISSUE THREAD

**Issue by garlicy** [Wynncraft/Issues#8380] opened 2017-06-15 17:18 UTC
When i try to open the door right before the Witherhead boss there..... just look at screenshots...
![2017-06-15_20 09 30](https://user-images.githubusercontent.com/29414200/27193499-b6a3847a-5207-11e7-8f0f-2d8d2a424a73.png)
![2017-06-15_20 09 32](https://user-images.githubusercontent.com/29414200/27193500-b6a819cc-5207-11e7-889e-526c30acab4f.png)
![2017-06-15_20 09 34](https://user-images.githubusercontent.com/29414200/27193503-b6b45d68-5207-11e7-86e8-0bb2c16d2236.png)
![2017-06-15_20 09 37](https://user-images.githubusercontent.com/29414200/27193501-b6ab2e14-5207-11e7-9ff8-de7f2e139e6a.png)
![2017-06-15_20 09 39](https://user-images.githubusercontent.com/29414200/27193502-b6ae85f0-5207-11e7-9882-c47d6314c8b7.png)
![2017-06-15_20 09 48](https://user-images.githubusercontent.com/29414200/27193504-b6ba015a-5207-11e7-94dd-d896b25c9d12.png)
![2017-06-15_20 09 49](https://user-images.githubusercontent.com/29414200/27193505-b6c5eba0-5207-11e7-9975-046afcaf5cd7.png)

**Comment by garlicy** [comment] 2017-06-15 17:23
I've tried already a bunch of times and i'm not going to kill 26 mobs again

**Comment by garlicy** [comment] 2017-06-15 17:37
Okay maybe just one more time...

**Comment by garlicy** [comment] 2017-06-15 18:01
And then tis issue appears: https://github.com/Wynncraft/Issues/issues/6340 Great! 1 dungeon 2 bugs. I give up

**Comment by FreeProGamer** [comment] 2017-06-15 18:46
Try joining to another world

**Comment by ittnoraA** [comment] 2017-06-15 20:10
Duplicate of #8351 and several others. This happens because the server is creating client side glitched blocks on the door on versions between 1.9 and 1.12. Just log in using any 1.8 version and you should be fine.

**Closed** 2017-06-16 15:52 UTC
