### ISSUE TITLE
Can't Join a World

### ISSUE THREAD

**Issue by truesurvivor9** [Wynncraft/Issues#5018] opened 2016-05-18 03:25 UTC
I can't seem to join any world. I don't even have a clock in my inventory in the lobby, so I can't switch lobbies. Whenever I open my compass and click a world, nothing happens. I can attach screenshots if necessary.

**Comment by YunoFGasai** [comment] 2016-05-18 05:53
everyone had this issue a couple of hours ago, it seems to be fixed now.

**Comment by Devdiablooper** [comment] 2016-05-19 08:34
nope it's still not fixed

**Comment by Devdiablooper** [comment] 2016-05-19 08:35
i tried joining, won't work.

**Comment by Odnod** [comment] 2016-05-19 17:12
it seems you are stuck in the 'falback' server. I was stuck there for a bit and got out by changing the ip to "play.wynncraft.net" or "play.wynncraft.org"

**Comment by Moe-Ronickah** [comment] 2016-05-22 14:49
The fastest way out of the fallback server issue is to completely exit Minecraft, wait 5 minutes, and try again.  It may take two or three tries, however, it's always worked for me.

**Closed by Moe-Ronickah** 2016-05-22 14:49 UTC

**Comment by Devdiablooper** [comment] 2016-05-22 20:15
uhm do you think i haven't tried that?

**Comment by YunoFGasai** [comment] 2016-05-22 21:43
I heard that the node ip can bypass this, no idea what it is tho

**Comment by Moe-Ronickah** [comment] 2016-06-03 15:05
duplicate of #5012
