### ISSUE TITLE
A Grave Mistake quest is broken

### ISSUE THREAD

**Issue by shellbertt** [Wynncraft/Issues#7373] opened 2017-02-14 06:45 UTC
In the scene in a grave mistake where you are teleported to a church. nothing is happening. I'm stuck. I cant teleport out. sad face.

**Comment by GoodmanGaming** [comment] 2017-02-14 12:39
mine to..... i was at the last part of the quest when you saw the big door open when the server restarted.... every time i log on any server and i choose archer, im stuck in the air. my IG is Super2me

**Comment by Pyromanical** [comment] 2017-02-14 15:20
Duplicate of #6730 
To fix your problem @shellbertt do /kill, this will respawn you in the nearest town, then just try again.  If you are using a version other than 1.8.9, try using that version, as the server is designed for that version.  However, you are just going to have to keep trying and /killing until it works, it usually takes me 10+ tries for the cutscene to work.

**Comment by DebugMC** [comment] 2017-02-17 21:25
But /kill takes 2SP... 10 tries = 20SP, SP Max isn't 20 ._.

**Comment by ColinRioux** [comment] 2017-02-18 04:38
Closing due to this being a duplicate.

**Closed by ColinRioux** 2017-02-18 04:38 UTC
