### ISSUE TITLE
"You are not permitted to enter this area."

### ISSUE THREAD

**Issue by Jonplae** [Wynncraft/Issues#3887] opened 2016-01-27 18:08 UTC
Hello!
I have a big issue and a lot of other people have it to. We/I can't enter Llevigar with teleportation scrolls or use Mage class to teleport there it just comes in the chat "You are not permitted to enter this area." If you walk you are able to go inside Llevigar but I logged out and now I am just stuck in the black place where you can pick classes because I am not permitted to go to Llevigar.

**Comment by wynncraftlupascu** [comment] 2016-01-27 19:02
yes
in llevigar

**Comment by wynncraftlupascu** [comment] 2016-01-27 19:03
and wen u do /kill
and use tp scroll

**Comment by wynncraftlupascu** [comment] 2016-01-27 19:03
![2016-01-27_21 00 33](https://cloud.githubusercontent.com/assets/14152318/12624768/6d972144-c539-11e5-83ef-5cf8db5454c1.png)
and after it tps u at the spawn
![2016-01-27_17 07 42](https://cloud.githubusercontent.com/assets/14152318/12624774/77de9d08-c539-11e5-926c-c05c37446b19.png)

**Comment by DarkDemonDragon** [comment] 2016-01-28 13:29
Duplicate of #3878 Please close this issue and follow the original.

**Closed** 2016-01-28 13:38 UTC
