### ISSUE TITLE
Poison + Manasteal bug

### ISSUE THREAD

**Issue by ThePiggu** [Wynncraft/Issues#4588] opened 2016-03-19 00:05 UTC
Hello, I haven't played wynncraft for around 2 months now, and I have finally come back. Only to realise my manasteal + poison build wasn't working properly. Now, I don't know if this was a bug and that it has been fixed, but manasteal used to take effect on each poison tick, and it no longer does. This was my primary way of getting mana, so therefore, I wanted to check if this was actually a bug or not. 

Example:
https://www.youtube.com/watch?v=bo4pJsX3duA

Notice how the manasteal looks like it has no effect whatsoever? It used to fill 16 mana with 1 hit + 3 ticks of poison, but now it only seems to fill around 6 mana and the poison ticks don't even seem to matter.

**Comment by Creecreeprs** [comment] 2016-03-19 09:00
I think poison is not bug, but for the manasteal (and it's the same thing for the lifesteal) work strangely since some months. I heard some where it's normal and it's for a future update.

**Comment by ThePiggu** [comment] 2016-03-19 13:04
Oh, well it sucks that my build no longer works I guess. :/ Oh well.

**Comment by Trixter313** [comment] 2016-03-19 14:20
Duplicate of https://github.com/Wynncraft/Issues/issues/4065

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-19 14:20 UTC
