### ISSUE TITLE
Legendary Item - Pélier Helmet, not being identified 

### ISSUE THREAD

**Issue by WexterMV** [Wynncraft/Issues#2567] opened 2015-11-28 20:00 UTC
For some unknown reason I cant identify my helmet, (IT SAYS LEGENDARY!!!!) and when I try to identify it the npc says, I'm afraid I can't identify this item! Only weapons and armours with a Unique, Rare, Legendary, and Special tags can be identified.

**Comment by DarkDemonDragon** [comment] 2015-11-28 22:59
Duplicate of #1312

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!

**Closed** 2015-11-28 23:28 UTC
