### ISSUE TITLE
Treasure spawns over the water in Underwater quest

### ISSUE THREAD

**Issue by WInf9Kieran** [Wynncraft/Issues#6829] opened 2016-12-03 19:16 UTC
So, when you do the Underwater quest, the treasure also spawns over the water.
Video here: https://youtu.be/yPgs8q_WhkI

**Comment by LordHelmchen98** [comment] 2016-12-03 23:51
Duplicate of #6038

**Comment by WInf9Kieran** [comment] 2016-12-04 00:13
nice

**Comment by Imaxe** [comment] 2016-12-04 19:55
This should now be fixed!

**Closed by Imaxe** 2016-12-04 19:55 UTC
