### ISSUE TITLE
chestplate bugged

### ISSUE THREAD

**Issue by Rentokraft** [Wynncraft/Issues#3698] opened 2016-01-15 08:38 UTC
![2016-01-15_15 36 43](https://cloud.githubusercontent.com/assets/16392627/12348904/fede2b98-bb9d-11e5-8653-ddfac979a1df.png)

**Comment by alfredchi** [comment] 2016-01-15 09:56
I got the same problem with it, plus its a chestplate named "montefiore" i wish it helps

**Comment by Dar-krusos** [comment] 2016-01-15 10:04
This is a recurring bug that occurs with chestplates that contain special letters and characters in their name, which causes them to be like this. A similar glitch happened with identifying them prior to the Gavel Expansion and they fixed that one. This bug should be fixed accordingly.

**Comment by DarkDemonDragon** [comment] 2016-01-15 13:17
Duplicate of #3175

Please close this issue and direct any future comments to the original thread. Thanks!

**Closed** 2016-01-17 19:24 UTC
