### ISSUE TITLE
Lots Of Glitched Chunk Errors

### ISSUE THREAD

**Issue by Steviegt6** [Wynncraft/Issues#7819] opened 2017-04-12 02:28 UTC
Umm...

There's lots of glitched out chunks all over the Province Of Wynn (And probably in Corkus and Gavel too)

![2017-04-11_19 14 17](https://cloud.githubusercontent.com/assets/27323911/24938582/f53e687e-1eec-11e7-844f-3a5c11176679.png)
![2017-04-11_19 14 22](https://cloud.githubusercontent.com/assets/27323911/24938585/f7ea7ff4-1eec-11e7-84a7-6ad6b4f2d563.png)
![2017-04-11_19 14 25](https://cloud.githubusercontent.com/assets/27323911/24938586/f98ea07e-1eec-11e7-81c7-6318f89d9de1.png)
![2017-04-11_19 14 30](https://cloud.githubusercontent.com/assets/27323911/24938588/fc0980b2-1eec-11e7-9be6-6e2c445c7f91.png)
![2017-04-11_19 23 26](https://cloud.githubusercontent.com/assets/27323911/24938590/0044b264-1eed-11e7-9ddc-342812a03db0.png)
Those are some screenshots I took for proof. :D

**Comment by Steviegt6** [comment] 2017-04-12 02:29
Oops xD Don't pay attention to the last one.

**Comment by LordHelmchen98** [comment] 2017-04-12 02:35
Duplicate of #7817 look there for more information.

**Closed by LordHelmchen98** 2017-04-12 02:35 UTC
