### ISSUE TITLE
Members glitching into guild list that we did not invite 

### ISSUE THREAD

**Issue by Killerfishy** [Wynncraft/Issues#3957] opened 2016-02-02 00:36 UTC
So we were kicking people to make room for more active members in the guild.

However, there are multiple glitches that occurred when doing this. There are members that duplicate over the guild list, and there are members that we know we did not invite.

![guild](https://cloud.githubusercontent.com/assets/8465848/12735998/82eda90c-c91a-11e5-9954-adf1993598dd.PNG)

As you can see, xStrafeFTW is a member of the guild who duplicates twice of the guild list. He is also a member that we know we did not invite, and we checked with our recruiters to make sure they did not invite him. 

![bug](https://cloud.githubusercontent.com/assets/8465848/12736055/07981732-c91b-11e5-8288-0a88a63591ae.PNG)

As you can see, I tried kicking him multiple times. However, He still appears on the guild list after those kicks.

**Comment by Odnod** [comment] 2016-02-02 06:24
they may be someone who has changed their name recently. Try using namemc.com to find out.

**Comment by Trixter313** [comment] 2016-02-02 12:09
Duplicate of https://github.com/Wynncraft/Issues/issues/3665 or https://github.com/Wynncraft/Issues/issues/3908

**Closed by Trixter313** 2016-02-02 12:09 UTC
