### ISSUE TITLE
"Out of my Mind" Qeust Not Giving Full Emerald Reward

### ISSUE THREAD

**Issue by CMWizard** [Wynncraft/Issues#5297] opened 2016-06-24 02:05 UTC
Chat says reward is 32 emerald blocks, or 2048 emeralds. I recieved 4 emerald blocks, or 256 emeralds. Here are snapshots, using the gyazo application. 

![](https://i.gyazo.com/5ba9176edd13236e3a1a19c47b7e36fe.png)

![](https://i.gyazo.com/b7adf1ce9c8eebacd577fd9a820152c0.png)

**Comment by Trixter313** [comment] 2016-06-24 02:09
Duplicate of #3562 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-06-24 02:09 UTC
