### ISSUE TITLE
Decrepit sewers barrier bug 

### ISSUE THREAD

**Issue by Steropes** [Wynncraft/Issues#8632] opened 2017-07-21 02:19 UTC
I cant progress to the parkour section of decrepit sewers due to barrier blocks that wont go away. They're in the tunnel between the first slay section and parkour section. Switching servers does nothing and i dont wanna loose soul points from a suicide. why are the barriers even there just remove them.

**Comment by colin350** [comment] 2017-07-21 13:43
Few things:
1. Duplicate of #6340
2. You have a few solutions:
a. Switch servers until you find one where the barriers aren't there.
b. Play on version 1.8.9 (logging out won't kick you from the dungeon unless you are in the boss room). You should play on 1.8.9 since Wynncraft is hardcoded to it, and playing on the hardcoded version will reproduce less issues.
3. We can't remove them because it's a game mechanic. Sometimes they improperly reset.

**Closed by colin350** 2017-07-21 13:43 UTC
