### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by DragonbornTheWolf** [Wynncraft/Issues#5057] opened 2016-05-22 15:41 UTC
When I logged in to a server, the resource pack loads in and all I could see is these missing textures

![2016-05-22_10 39 10](https://cloud.githubusercontent.com/assets/19388638/15454867/b033cfcc-2009-11e6-9331-2f06d3bd09a8.png)

**Comment by Odnod** [comment] 2016-05-22 19:41
If you are in 1.9 try switching to 1.8.9

**Comment by TurretBud** [comment] 2016-05-23 23:28
Problem occurs with Forge, doesn't occur with normal 1.9 for some reason. Forge 1.8.9 works fine.

**Comment by Moe-Ronickah** [comment] 2016-05-26 00:12
@TurretBud , are you certain that this is a Forge 1.9.x issue?

**Comment by TurretBud** [comment] 2016-05-26 00:42
@Moe-Ronickah Fairly certain, I was playing on 1.9.2 vanilla and wasn't getting the issue, only happened after I put on a 1.9.2/4 Forge client, 1.8.9 Forge works fine.

**Comment by DragonbornTheWolf** [comment] 2016-05-26 01:25
So, I can confirm that using Forge will give the missing textures as I just checked on 1.9 vanilla
![2016-05-25_20 22 38](https://cloud.githubusercontent.com/assets/19388638/15560977/bd67989a-22b6-11e6-96e2-413d31e8b5b5.png)

**Comment by CharlieDowns** [comment] 2016-05-30 06:29
This happens because the server texturepack (v0.1 2015.12.19) has a pointer file 'tall_grass.json' in 'blockstates' which tries to load 'tallgrass.json' and 'tallgrass.json' inside 'models\block' which do not exist.
Normally Vanilla does not seem to care about this, but the lastest version of Forge will complain if your texturepack is incorrect.

Deleting or recreating the files will fix this incorrection.
Also it should be noted that forge shall never fix issues that occur from a faulty texture pack.

For reference:

blockstates\tall_grass.json
```
{
    "variants": {
        "normal": [
		{ "model": "tall_grass" },
		{ "model": "tall_grass_small" },
		{ "model": "tall_grass_medium" },
		{ "model": "tall_grass_tall" },
		{ "model": "tall_grass_tallest" }
		]
    }
}
```
Missing files \/

models\block\tall_grass.json
```
{
    "parent": "block/tallgrass",
    "textures": {
        "cross": "blocks/tallgrass"
    }
}
```

models\block\tall_grass.json
```
{
    "ambientocclusion": false,
    "textures": {
        "particle": "#cross"
    },
    "elements": [
        {   "from": [ 0.8, 0, 8 ],
            "to": [ 15.2, 16, 8 ],
            "rotation": { "origin": [ 8, 8, 8 ], "axis": "y", "angle": 45, "rescale": true },
            "shade": false,
            "faces": {
                "north": { "uv": [ 0, 0, 16, 16 ], "texture": "#cross", "tintindex": 0 },
                "south": { "uv": [ 0, 0, 16, 16 ], "texture": "#cross", "tintindex": 0 }
            }
        },
        {   "from": [ 8, 0, 0.8 ],
            "to": [ 8, 16, 15.2 ],
            "rotation": { "origin": [ 8, 8, 8 ], "axis": "y", "angle": 45, "rescale": true },
            "shade": false,
            "faces": {
                "west": { "uv": [ 0, 0, 16, 16 ], "texture": "#cross", "tintindex": 0 },
                "east": { "uv": [ 0, 0, 16, 16 ], "texture": "#cross", "tintindex": 0 }
            }
        }
    ]
}
``.

**Comment by Moe-Ronickah** [comment] 2016-05-31 00:45
Wow!  Thank you, @CharlieDowns , for that analysis.  I've passed it along to admins.

**Comment by CharlieDowns** [comment] 2016-06-16 12:25
Hello Moe, sorry for resurrecting this issue, but the resourcepack has not been replaced and hence still has the bug with Forge.

The issue exists in archive file with name '0b88c016c0b811591eac6045e66c5fbadb64928c'.
SHA1 Hash is '275B08B7E66D49DA44041FB1F39DEB6128D6F1D3'.

Even though I do not play with this mod, others may experience issues when using Forge, even though the server version itself is not fully 1.9+ compatible.
Reference: https://imgur.com/LCHM350

**Comment by Moe-Ronickah** [comment] 2016-06-20 16:33
Charlie, it's not "resurrected", I just forgot to add a comment to it.

The admin team is aware of this. It will stay open, even with no activity, until it is fixed.

**Comment by AckroWynn** [comment] 2016-07-22 10:41
As far as I am aware, Energyxxer (a resource pack developer) fixed this issue. 
@Moe-Ronickah The thing is, 1.9+ is fixed on GM RP-wise, but I would recommend keeping this open for a while longer, until it is confirmed to be fixed on the main servers.

**Comment by Fornax96** [comment] 2016-07-23 09:01
How long does it usually take before changes are applied to the main servers? I want to use journeymap so I don't have to peek in the debug menu every time I want to do a quest.

**Comment by YunoFGasai** [comment] 2016-07-23 09:49
@Fornax96 updates usually take a long time but we have an update coming out in a couple of weeks

**Comment by Moe-Ronickah** [comment] 2016-09-10 17:29
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.

**Closed by Moe-Ronickah** 2016-09-10 17:29 UTC
Labels: World

**Comment by coolgi3000** [comment] 2016-09-26 18:23
this is still an issue and that does not happen on non wynncraft servers for me. It would be nice to Beable to play with journeymap in 1.10 but it's not gamebreaking.

**Comment by macserv** [comment] 2016-11-06 22:01
Quoting above... "It will stay open, even with no activity, until it is fixed."  It is not fixed; could it be re-opened?

**Comment by NaturalHate** [comment] 2016-11-12 10:39
Yeah, why is this closed now?  
The issue is still there, and fixing the resource pack shouldn't be too much of an issue either.
