### ISSUE TITLE
Beneath the Depths BUG 

### ISSUE THREAD

**Issue by onbekendegozer** [Wynncraft/Issues#4378] opened 2016-03-01 13:16 UTC
This mission has a bug.
no spawn Javier's maps
and I can not do this mission :( please fix this!

**Comment by Moe-Ronickah** [comment] 2016-03-01 13:37
Duplicate of #4236 . Please, use the search instructions on the front page so that you don't post duplicates, but, rather, add to the original issue. Thank you.

**Closed by Moe-Ronickah** 2016-03-01 13:37 UTC
Labels: Duplicate
