### ISSUE TITLE
I lost 2 emerald blocks!

### ISSUE THREAD

**Issue by 21harrisont** [Wynncraft/Issues#8043] opened 2017-05-02 00:19 UTC
2 emerald blocks in my inventory got replaced by bone meal! Help pls I just lost so many emeralds!
In game name: Htoa

**Comment by thecoolkogut4** [comment] 2017-05-02 00:19
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by Trixter313** [comment] 2017-05-02 01:19
Duplicate of https://github.com/Wynncraft/Issues/issues/8044

**Closed by Trixter313** 2017-05-02 01:19 UTC
