### ISSUE TITLE
guild name

### ISSUE THREAD

**Issue by RedEagleGames** [Wynncraft/Issues#3760] opened 2016-01-18 13:12 UTC
i tried to make a guild name but the guild master keeps saying use english letters A-Z  
and relogging and switching world doesnt fix it   

 i cant interact with the guild master now

**Comment by Trixter313** [comment] 2016-01-18 15:47
Duplicate of https://github.com/Wynncraft/Issues/issues/3190

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-18 15:47 UTC
