### ISSUE TITLE
TO MANY BUGS TO PLAY!

### ISSUE THREAD

**Issue by stormblade282** [Wynncraft/Issues#4340] opened 2016-02-28 20:18 UTC
HELP! THIS SERVER HAS TO MANY BUGS!

Okay, I have a LOOONG (not very, actually kinda) list of bugs that need fixing IMMEDIATELY.

-The First bug I am naming is the armour not loading bug, it is happening to like EVERYONE, its where your level of armour shows up above your hearts, and even if you remove a peice of armour, and try to replace it with another, it still doesnt load like normal. And it also doesnt load with a custom texture. Please fix this.

- Also, Another bug is with guilds this time. You see, when you do /guild stats, nothing happends. It doesnt say anything in chat, or anywhere. It simply doesnt work. And It's the same with /guild leaderboard, Please fix this, for it is really annoying.

-Another one is skill points bugging out, This is where you log on and your skill points reset without you wanting them to.

Thats all for now!

Please fix these!

**Comment by Moe-Ronickah** [comment] 2016-02-29 21:31
"Okay, I have a LOOONG (not very, actually kinda) list of bugs that need fixing IMMEDIATELY."
Trying being polite.

"armour not loading"  Armour is being updated.  No idea when the process will be completed.

"/guild stats": Duplicate of  Guild Stats Command #3529 . Please refer all future comments to the original thread.

"skill points bugging out, " You can switch classes, or change hubs.  Duplicate of:  Skill Point Glitch #4304 .  Please refer all future comments to the original thread.

**Closed by Moe-Ronickah** 2016-02-29 21:31 UTC
Labels: Duplicate

**Comment by stormblade282** [comment] 2016-03-01 15:57
Umm.. Sorry about politeness at the start, but the /guild stats, i looked at the thread which didnt help atall, i dont see any duplicate commands... and you didnt reply to the /guild leaderboard.
