### ISSUE TITLE
Resource Pack Glitch

### ISSUE THREAD

**Issue by Snickaaman** [Wynncraft/Issues#6068] opened 2016-09-07 00:15 UTC
I have a weapon: Kelights Toothbrush, and it still appears as a stone half slab. The rest of the texture pack is working, as far as I know.

**Comment by Trixter313** [comment] 2016-09-08 00:51
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

**Closed by Trixter313** 2016-09-08 00:51 UTC
