### ISSUE TITLE
Glitched Pelier

### ISSUE THREAD

**Issue by Lionkingx999x** [Wynncraft/Issues#4969] opened 2016-05-10 14:06 UTC
My Pelier (Chain helmet) is glitched because its from older days :yum: 
http://imgur.com/wkhdtC2

**Comment by Lionkingx999x** [comment] 2016-05-10 14:07
Just like my Devourese http://imgur.com/UmOElN5

**Comment by Trixter313** [comment] 2016-05-10 19:25
Duplicate of https://github.com/Wynncraft/Issues/issues/3161

Please direct any future comments to the original thread & read the whole thread. Thanks!

**Closed by Trixter313** 2016-05-10 19:25 UTC
