### ISSUE TITLE
Boatlag

### ISSUE THREAD

**Issue by LaszloHun** [Wynncraft/Issues#5491] opened 2016-07-15 16:19 UTC
If I use a boat, it's very often a lag drops me back.... Or.... I don't call it a dropback.
I describe everything. It begins with the music (the noteblock music) mutes. If I'm in a river, and there are zombies, they hit the place where I was when the lag beginned, and I hurt. And after it, the lag drops me back. If I leave the boat, it drops me back too..... You should fix it........

**Comment by YunoFGasai** [comment] 2016-07-15 20:38
what version of minecraft are you using?

**Comment by sammyvsparks** [comment] 2016-07-15 20:53
This happens to me as well using 1.8.9, though it doesn't bother me much but my VIP Flame Particles either lag behind or in front of me which is how I notice. It will jump to where ever the particles are after the server notices (I would guess that is what happens).

**Comment by sammyvsparks** [comment] 2016-07-15 22:33
![2016-07-15_22 32 11](https://cloud.githubusercontent.com/assets/12182390/16890215/2e7d45e8-4ab2-11e6-9235-193e0a95bb7e.png)

**Comment by LaszloHun** [comment] 2016-07-16 08:21
I use 1.8.8

2016-07-16 0:33 GMT+02:00 Samuel Voeller <notifications@github.com>:

**Comment by Moe-Ronickah** [comment] 2016-07-16 13:02
Duplicate of #3070.  Not a WynnCraft issue.  Inherent in current Minecraft.

Boat mechanics are buggy. I suggest that you move in a boat for a count of 7 seconds, then drift for 4 seconds, and repeat this all the way to your destination.

**Closed** 2016-07-16 13:02 UTC
Labels: Duplicate
