### ISSUE TITLE
I'M GLITCHED

### ISSUE THREAD

**Issue by DogPlayz** [Wynncraft/Issues#5190] opened 2016-06-10 01:33 UTC
I am about 10000000000000000000000000000000000 blocks in the air! When i join a server as my mage it instantly crashes everyone on the server!
I will provide screen shot if necessary.

**Comment by Trixter313** [comment] 2016-06-10 01:39
Duplicate of https://github.com/Wynncraft/Issues/issues/5134 . We currently don't have a fix.

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-06-10 01:39 UTC
