### ISSUE TITLE
Guild Bug

### ISSUE THREAD

**Issue by AironeAMV** [Wynncraft/Issues#6085] opened 2016-09-09 15:02 UTC
When you create a guild and your change your minecraft username, the guild didn't recognize you like a member but you can participate and use the commands like the chiefs.
And i can't watch the level of my guild !!

Sorry for my english because i'm french and thanks to fix that or if you have a hint for me i'm ok ^^

**Comment by Trixter313** [comment] 2016-09-09 21:46
Duplicate of #3665 

Guilds and name changing are pretty broken right now. I believe they are supposed to be getting worked on for a later update.

**Closed by Trixter313** 2016-09-09 21:46 UTC
