### ISSUE TITLE
tower of ascention teleportation

### ISSUE THREAD

**Issue by tiduseleven** [Wynncraft/Issues#1808] opened 2015-04-12 15:15 UTC
the teleportation in the tower of ascention (to pass from level 1 to level 2, level 2 to level 3...) is not good coded and the mobs kill me and my friends.

**Comment by Trixter313** [comment] 2015-04-12 17:53
Duplicate of https://github.com/Wynncraft/Issues/issues/1774
Jumping (especially with speed boost) seems to work eventually. So just keep jumping at the teleport spot and it will teleport you eventually.

**Closed** 2015-04-29 06:40 UTC
