### ISSUE TITLE
Untextured Wand: Kelight's Toothbrush

### ISSUE THREAD

**Issue by 19chanas3** [Wynncraft/Issues#5193] opened 2016-06-10 12:59 UTC
![2016-06-10_20 56 37](https://cloud.githubusercontent.com/assets/14016651/15965033/1cc0d8d0-2f4e-11e6-913b-8472ab4e86c6.png)

Textured as a slab, even to other players

**Comment by Trixter313** [comment] 2016-06-10 13:30
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-06-10 13:30 UTC
