### ISSUE TITLE
Can't Choose my class

### ISSUE THREAD

**Issue by R4zorF4ng** [Wynncraft/Issues#6696] opened 2016-11-15 16:31 UTC
Hello, I can't log in to my Warrior for some reason and i think its a Bug/Glitch and That's the only character that's high leveled Please help.

**Comment by LordHelmchen98** [comment] 2016-11-15 16:42
If you constantly get an error message thats a duplicate of #5418 
Salted wrote in the changelog for the store update it should be fixed. However obviously it isnt. Read the long text by Moe-Ronickah in the original thread for more information.

**Comment by R4zorF4ng** [comment] 2016-11-15 17:12
And where does that exist if i may ask?

**Comment by LordHelmchen98** [comment] 2016-11-15 17:37
If you are asking where the original thread is just click the number.

**Comment by R4zorF4ng** [comment] 2016-11-15 17:52
Doesnt work i give up...

**Comment by LordHelmchen98** [comment] 2016-11-15 18:05
you cant click it?
well if you cant click links copy this: https://github.com/Wynncraft/Issues/issues/5418

**Comment by R4zorF4ng** [comment] 2016-11-15 18:06
No i can't fix it and i don't want to WIPE

**Comment by LordHelmchen98** [comment] 2016-11-15 18:28
Well then Im afraid you have to use another class until this annoying bug can be fixed.

**Closed** 2016-11-17 00:32 UTC
