### ISSUE TITLE
Item identification not working (even when not identified yet)

### ISSUE THREAD

**Issue by Monkeysz** [Wynncraft/Issues#1911] opened 2015-05-20 23:27 UTC
When i traded for an legendary item. I tried to identify it, but it says this item is not any type but normal. Even when my item is labeled lagendary. (I have never identified this item so) Its name is pelier it has a accented e.

**Comment by Trixter313** [comment] 2015-05-21 00:52
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

**Closed** 2015-06-04 12:53 UTC
