### ISSUE TITLE
Potion Making

### ISSUE THREAD

**Issue by WackyWaldo** [Wynncraft/Issues#7336] opened 2017-02-05 21:20 UTC
I have 8 red mushrooms and when I go to turn them in the Assistant will not acknowledge that I have any red mushrooms. I cannot continue the quest :-:.

-WackyWaldo

**Comment by LordHelmchen98** [comment] 2017-02-05 21:24
You probably already gave him the mushrooms but unfortunately the Assistant will always tell you this text while doing the quest. You have to enter the house kill Essren and return to the Assistant with Essrens Dusty Coat.

**Comment by ColinRioux** [comment] 2017-02-06 01:26
Duplicate of #6437

**Closed by ColinRioux** 2017-02-06 01:26 UTC

**Comment by isaacdare** [comment] 2017-03-26 00:57
I have a similar problem, expect Essren does not spawn inside his house.
