### ISSUE TITLE
Drought Sand Quest Glitch?

### ISSUE THREAD

**Issue by CoolBlueDragon** [Wynncraft/Issues#4775] opened 2016-04-09 03:33 UTC
![wynnglitch](https://cloud.githubusercontent.com/assets/16386561/14401462/17bf4210-fdc9-11e5-92e4-1562b8674fbd.PNG)
![wynnglitch2](https://cloud.githubusercontent.com/assets/16386561/14401463/1a87993e-fdc9-11e5-9889-7b50d17a2058.PNG)
The Wiki tells me to bring 6 water bottles, but in-game its 24? Not sure which is correct and which is not.

**Comment by Trixter313** [comment] 2016-04-09 03:49
Duplicate of #38 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-09 03:49 UTC
