### ISSUE TITLE
Can't login to my Assassin class?!

### ISSUE THREAD

**Issue by Eliasbl75** [Wynncraft/Issues#7801] opened 2017-04-11 07:07 UTC
Hi Wynn Staff, i have a plroblem loging in to my assassin class. Its been like this for some days now. Please help me!

![2017-04-11_08 56 57](https://cloud.githubusercontent.com/assets/27270899/24896670/33643e64-1e96-11e7-8490-86970e36b5cc.png)

![2017-04-11_08 57 01](https://cloud.githubusercontent.com/assets/27270899/24896678/38c602d4-1e96-11e7-8779-1fe3d37b2240.png)

**Comment by LordHelmchen98** [comment] 2017-04-11 10:26
Duplicate of #7680 please look there for more information.

**Closed by LordHelmchen98** 2017-04-11 10:26 UTC
