### ISSUE TITLE
Skill points dropped

### ISSUE THREAD

**Issue by wizardcheetah55** [Wynncraft/Issues#4443] opened 2016-03-04 23:23 UTC
I was out on the island just on the other side of the Ghost Ship. I went offline shortly after reaching Level 76. 
When I returned, I was attacked and I started to fight back and cast spells . . . except that a message came on saying my intelligence level had to be at least 60. It has been 63 for several weeks. 

I went offline and returned to find that my intelligence level at 63 had returned. But my armor was off and other levels were down. 

Please check - or if there is something in the game that arbitrarily reduces your skill points, please let me know. 

Thank you.

ps. I restored the other levels with points I had in reserve so that I could put my armor back on.

**Comment by TrashcanMan** [comment] 2016-03-05 02:41
Do you have any equipment with negative intelligence boosts?

**Comment by wizardcheetah55** [comment] 2016-03-05 02:57
Not that I know of

Stan Emert
206-250-9839
Skype: stan.emert

**Comment by Trixter313** [comment] 2016-03-05 15:56
Mouse over your skill points and look for a message on each category that says they are being modified by your armor to see whether it's caused by your armor or not.

**Comment by Moe-Ronickah** [comment] 2016-03-11 04:58
Duplicate of #4120

**Closed by Moe-Ronickah** 2016-03-11 04:58 UTC
