### ISSUE TITLE
Skeleton Key (Old) dropped by Zombie.

### ISSUE THREAD

**Issue by Blezian** [Wynncraft/Issues#6214] opened 2016-09-20 15:26 UTC
I just killed a zombie and it dropped an old Skeleton Key. I don't know if this is still possible, but I think it's a bug since we just had new dungeons//keys.
![2016-09-20_17 16 51](https://cloud.githubusercontent.com/assets/22325243/18676875/66885962-7f57-11e6-8846-c331f0f80269.png)

**Comment by LordHelmchen98** [comment] 2016-09-20 17:38
Duplicate of #5968 
Dude you are supposed to search for duplicates. This is the second post about this in two days and there are at least two other posts.

**Closed** 2016-09-25 00:28 UTC
