### ISSUE TITLE
My Guild Is totely gliched, please someone help me!

### ISSUE THREAD

**Issue by Collor** [Wynncraft/Issues#7232] opened 2017-01-22 10:01 UTC
My guild is glitched to the point that the chat Dubbel's and nobody can leave or get kicked, we cannot attack or defend areas.
So if anyone just told me how to and then what it would be nice.
Annoyed regards 
Velil/Collor

**Comment by LordHelmchen98** [comment] 2017-01-22 10:03
Duplicate of #3665
Guilds a very bugged right bow. There's no known fix for your issue. Unfortunately you will have to wait until guilds get fixed which will hopefully happen soon.

**Closed** 2017-01-22 21:21 UTC
