### ISSUE TITLE
Jester Set Bonuses Not Working

### ISSUE THREAD

**Issue by Okuupls** [Wynncraft/Issues#3718] opened 2016-01-16 09:03 UTC
I've tried with both the 2/3 and the 3/3 set, neither seem to have an effect on damage in game or in my stats menu, they've also seemed to somewhat reduce my Water damage as well, the changes to Loot Bonus/XP Bonus also do not apply

**Comment by DarkDemonDragon** [comment] 2016-01-16 13:56
Yea I've been messing around with them and they're a bit slow. You have to either /class or if you have SP to spare do /kill and it'll update.

**Comment by DarkDemonDragon** [comment] 2016-01-16 13:57
Also note that the Jester set has a debuff if you don't have the whole set so check for that.

**Comment by Okuupls** [comment] 2016-01-16 21:57
I've done /class multiple times and nothing, and I know about the debuffs already

**Comment by DarkDemonDragon** [comment] 2016-01-17 13:50
Like I said they're finicky. I usually have to spend like 5 mins swapping around stuff but they finally work.

**Comment by DarkDemonDragon** [comment] 2016-01-20 18:44
Sorry I just realized this is a duplicate of #3687 Please close this issue and follow that one.

**Closed** 2016-01-20 19:04 UTC
