### ISSUE TITLE
WynnExcavation Site C crystal BUG

### ISSUE THREAD

**Issue by onbekendegozer** [Wynncraft/Issues#4377] opened 2016-03-01 12:24 UTC
Crystal bug there is no drop crystals and I need to fix it you do for that mission

**Comment by Moe-Ronickah** [comment] 2016-03-01 13:39
Duplicate of #4236 . Please, use the search instructions on the front page so that you don't post duplicates, but, rather, add to the original issue. Thank you.

**Closed by Moe-Ronickah** 2016-03-01 13:39 UTC
Labels: Duplicate
