### ISSUE TITLE
Wynncraft "WynnExcavation site B"

### ISSUE THREAD

**Issue by halo33** [Wynncraft/Issues#4457] opened 2016-03-05 15:31 UTC
My quest is stuck at talk to excavator lykron even though I was at the point of "collecting the shard" even though none spawned. I do believe this quest is bugged out for me. Everytime I speak to Excavator lykron he always says "Hello there! We are working very hard here at this excavation site! We have one at almuj as well, I think you should check it out!" I did the first quest and this one seems bugged out and unfinishable for me.

Minecraft name: Halo3

**Comment by Trixter313** [comment] 2016-03-05 15:58
What does it say in your questbook and what happens when you try typing /fixquests? Thanks!

**Comment by Sandertv** [comment] 2016-03-05 16:08
I think it's supposed to be like that, make sure you have the crystal with you.

**Comment by halo33** [comment] 2016-03-05 16:31
Like I stated above. None of the purple crystals ever spawned. And just speaking to him says the same thing. /fixquests only returned quest items to me that have nothing to deal with this quest.

**Comment by Trixter313** [comment] 2016-03-05 16:55
Ah, then this would be a duplicate of https://github.com/Wynncraft/Issues/issues/4236

Please direct any future comments to the original thread. Thansk!

**Closed by Trixter313** 2016-03-05 16:55 UTC
