### ISSUE TITLE
Ghostly Boots Chestplate?

### ISSUE THREAD

**Issue by Ghost88788** [Wynncraft/Issues#5688] opened 2016-08-08 14:03 UTC
So I am farming in the house of Twain for the Entire Armor Set and since I already own the helmet and boots in my bank, all I need was a tunic and leggings... After around 10 minutes of farming there, a leather tunic dropped from a haunted painting and it said Set! Then, when I went to Indentify it, I said Ghostly Boots... Can someone tell me what happened to the Ghostly Tunic being a Ghostly Boots? 
![2016-08-08_08 56 40](https://cloud.githubusercontent.com/assets/11810672/17482351/ff39b634-5d46-11e6-9685-da1b14f49797.png)

**Comment by Ghost88788** [comment] 2016-08-08 14:07
I don't have that much time at this moment right now, so I am going to go back there and try to get another ghostly set item and see if it happens again, but until then, that is all I got.

**Comment by Trixter313** [comment] 2016-08-08 17:10
Duplicate of https://github.com/Wynncraft/Issues/issues/4747

**Closed by Trixter313** 2016-08-08 17:10 UTC
