### ISSUE TITLE
Commands in guild not working

### ISSUE THREAD

**Issue by Thecommer** [Wynncraft/Issues#4145] opened 2016-02-15 19:31 UTC
So in my guild there are 2 commands that does not work.

/guild stats and /guild leaderboard

I asked my friend who we're in another guild and it did work for that guild. but in the guild i'm in the commands does not work.

When i do /guild stats it says
Nobody
Guild since: 11/19/2014
Owner:

Guild lvl 26 
needed xp:
Guild rank #77 [3052 total guilds]
Members 0 [Maximum 30]

And When i do /guild leaderboard it says

#77 Nobody [None] Level 26 [19m xp] - 0 members

My guilds real name is Eternal Legacy and it's current guild level is 41
The member count is: 18 Including me

**Comment by Dar-krusos** [comment] 2016-02-16 04:56
Duplicate of issue #3779.

**Comment by Thecommer** [comment] 2016-02-16 10:14
Oh i didnt know that

**Closed** 2016-02-16 10:18 UTC
