### ISSUE TITLE
Spell Cast Issue

### ISSUE THREAD

**Issue by IntSerErr** [Wynncraft/Issues#5332] opened 2016-06-28 14:25 UTC
When I cast a spell, say "Left-Right-Right" - It will rename the item to "Left-Right-Right" without casting the spell. I usually have to do this a good three times for it to work.

A moderator on this issue tracker said "You just have to get used to timing your mouse clicks for slow weapons so that they work." - Sadly, you can't really "get used to it" because you can't; it's completely random when it happens. Sometimes the spells cast just fine and other times I have to repeat them.

I really hope you can fix this because it can get really annoying and after all... spells are a big focus on WynnCraft's gameplay.

**Comment by Moe-Ronickah** [comment] 2016-06-29 01:36
It's an unavoidable game mechanic, unless the admins decide to change the speed of "slow attack" weapons. You just have to get used to timing your mouse clicks for slow weapons so that they work.

This is a combination of Minecraft game mechanics and spell speed.  It is not avoidable, and there is nothing that we can do about it.  The admins know about it, and they probably won't change it.  It's also affected by the ping time between your computer and the servers.  You have no choice but to get used to it, nor does anyone else.  It's up to you to find a click speed that works for you.

**Comment by Moe-Ronickah** [comment] 2016-06-29 01:37
Duplicate of #5229

**Closed** 2016-06-29 01:37 UTC
Labels: Duplicate
