### ISSUE TITLE
Expanding bank has deleted some items

### ISSUE THREAD

**Issue by JamezBladze** [Wynncraft/Issues#4677] opened 2016-03-27 20:17 UTC
Well, I'd been collecting some accessories lately and managed to get together four Joker Necklaces, which I quickly placed in my bank to avoid accidentally dropping or selling. So long story short, these items still in my bank, I purchase a bank expansion, from four lines to five, and upon doing so all four of my necklaces have vanished. It does not seem to affect other items, as they all remained, but I believe a fifth item may have been lost, but am unsure of what it was. To make sure of what just happened I upgraded my bank once again to six slots, and lost no more items, directing me to believe it may be a problem with the Joker Necklace itself and if another item had truly been lost, that item as well.

**Comment by Odnod** [comment] 2016-03-27 21:08
Because necklaces are glass panes, and the unexpanded bank is restricted by glass panes, expanding your bank can/will delete any necklaces in it. The only way to really fix this is to hold your necklaces when you expand your bank. Sorry for the inconvenience.

**Comment by Ben7615** [comment] 2016-05-03 20:28
This has also happened to me

**Comment by Trixter313** [comment] 2016-06-14 00:21
Duplicate of https://github.com/Wynncraft/Issues/issues/4091

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-06-14 00:21 UTC
Labels: Game Mechanics
