### ISSUE TITLE
Guild leave bugged

### ISSUE THREAD

**Issue by Dontdocoinflips** [Wynncraft/Issues#8682] opened 2017-07-28 17:09 UTC
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by Dontdocoinflips** [comment] 2017-07-28 17:10
I cant leave my guild help pls

**Comment by colin350** [comment] 2017-07-28 17:25
Duplicate of #3665. Please read its entirety.

**Closed by colin350** 2017-07-28 17:25 UTC
