### ISSUE TITLE
A Grave Mistake

### ISSUE THREAD

**Issue by ForbiddenHell** [Wynncraft/Issues#6485] opened 2016-10-28 06:58 UTC
During the Quest , All 4 Houses(buildings) Cinematic Scenes all Bugged/Glitched out for me
Bcuz of this i kept having to do /kill

**Comment by ForbiddenHell** [comment] 2016-10-28 07:00
I say REMOVE THIS QUEST
How many people do u think this quest has Ticked off as a result of them losing their valuables -_-

**Comment by MrRedCrack** [comment] 2016-10-28 07:42
erm, I dont get why everybody is repeating this bug, I have already reported it and there is now so many duplicates :P

**Comment by Trixter313** [comment] 2016-10-28 10:46
Duplicate of https://github.com/Wynncraft/Issues/issues/6480

**Closed by Trixter313** 2016-10-28 10:46 UTC
