### ISSUE TITLE
Can't get on?

### ISSUE THREAD

**Issue by DarkMaster98** [Wynncraft/Issues#6456] opened 2016-10-24 03:21 UTC
When I try to get on, it freezes for a moment, then goes back to the loading screen. When it comes back on, it freezes again, with the server message "Flying is not enabled on this server", then goes back to the loading screen. At this point, it gets stuck looping the loading screen and the server message, and I can only get out of the loop by closing Minecraft completely. Rebooting the game just starts the issue again half of the time. This issue has been happening for a while, mainly when I attempt to use /lobby and/or when a server is going to close soon. Please help, it's getting annoying.

**Comment by RapidzGaming** [comment] 2016-10-24 04:36
try /kill

**Comment by DarkMaster98** [comment] 2016-10-24 05:35
I can't, it doesn't even let me open chat

**Comment by Trixter313** [comment] 2016-10-28 10:58
Duplicate of https://github.com/Wynncraft/Issues/issues/5289

**Closed by Trixter313** 2016-10-28 10:58 UTC
