### ISSUE TITLE
Bug with Floor 5 boss in ToA

### ISSUE THREAD

**Issue by Goliaith513** [Wynncraft/Issues#3598] opened 2016-01-08 05:23 UTC
The issue with the boss on ToA floor 6 is that it uses it's ability every time it spawns.
This causes him to commit suicide seconds after spawning.
This prevents anyone from sustaining enough damage to kill him, even with a small group.

**Comment by HeyloLP** [comment] 2016-01-09 20:16
that's his special move not a bug so please close this thread

**Closed** 2016-01-09 21:23 UTC
