### ISSUE TITLE
LifeSteal Bug

### ISSUE THREAD

**Issue by Danthegitman** [Wynncraft/Issues#3926] opened 2016-01-30 19:32 UTC
Apparently lifesteal and manasteal don't work. So far I only know that it's broken for assassin, and it only works if you're an assassin with poison.

What I mean, is I only gain life with lifesteal when an enemy is hurt by my poison.

Other people have been having this problem: https://forums.wynncraft.com/threads/is-life-steal-broken.107049/

Thanks. 
- Danthecakeman

**Comment by Dar-krusos** [comment] 2016-01-31 02:49
This is the same for all other classes in that it only works when poison applies.

**Comment by Trixter313** [comment] 2016-01-31 16:34
Duplicate of https://github.com/Wynncraft/Issues/issues/3225

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-31 16:34 UTC
