### ISSUE TITLE
Pirate Island quest

### ISSUE THREAD

**Issue by RockyPlayzMC** [Wynncraft/Issues#4282] opened 2016-02-26 00:46 UTC
Maps are not spawning in the quest at the spot I am level 60 trying to level pls fix soon

**Comment by Odnod** [comment] 2016-02-26 00:52
Duplicate of #4236, please close this issue and direct any additional comments to the original post. This issue is very well known by now and it is being worked on.

**Closed** 2016-02-26 01:50 UTC
