### ISSUE TITLE
Corrupted character?

### ISSUE THREAD

**Issue by survivalmonkney** [Wynncraft/Issues#3322] opened 2015-12-29 16:39 UTC
I logged on to the Wynncraft server, joined the game, and it logged me into my fairly low level mage. OK, so I typed in /class to get onto my level 53 archer. I click the icon and it says 'there's been an error... please try again' I try it again, it says it again. I've tried it on multiple servers, none work. I can get into my other classes fine, it's just this one level 53 archer. I've tried relogging, restarting minecraft, restarting my computer, nothing works. I've also noticed that in the stats it says the archer has 112% xp? I have no idea what this is or how to fix it.

I haven't played Wynncraft for a few months, so it might've been an update that messed something up.

**Comment by Trixter313** [comment] 2015-12-29 22:25
Duplicate of https://github.com/Wynncraft/Issues/issues/3139

Please direct any further comments to the original issue. Thanks!

**Closed by Trixter313** 2015-12-29 22:25 UTC
