### ISSUE TITLE
Terroritry bug

### ISSUE THREAD

**Issue by SirKiddo** [Wynncraft/Issues#4441] opened 2016-03-04 21:19 UTC
I recently have had an issue with guilds whereas I attempt to attack land, and it gets all the way to the countdown finish where you are suppose to be teleported to the war server, and then it pauses. After a few seconds, it says nobody showed up for the battle despite my guild members being in the terroritry

**Comment by BlahBlah161616** [comment] 2016-03-11 17:25
It shouldn't shock you that guilds are broken they're broken a lot, we expect a new guild system in the future, so it will likely be fixed soon.

**Comment by Moe-Ronickah** [comment] 2016-03-15 06:05
Duplicate of #3934

**Closed by Moe-Ronickah** 2016-03-15 06:05 UTC
Labels: Duplicate
