### ISSUE TITLE
Name Changes do not Work in Guilds.

### ISSUE THREAD

**Issue by Matt10y** [Wynncraft/Issues#5404] opened 2016-07-05 21:21 UTC
Yeah, so my name was Matt10y then I changed it to Minecraft_Stinks, but it glitches out a lot. I can't leave my guild, get promoted, and when I talk it appears twice. I just changed my name back to Matt10y but it still won't work. PLEASE FIX THIS GLITCH

**Comment by Moe-Ronickah** [comment] 2016-07-05 22:21
Please do a search for "guild" and tell us which of the 23 issues most closely matches you issue.

**Comment by YunoFGasai** [comment] 2016-07-10 09:28
the talking twice and overall "stuck" you describe points to this being a duplicate of #3665 please close this issue and follow the original on linked thread.

**Comment by Villageacules** [comment] 2016-07-26 01:18
This is a one of the very well known swaths of guild errors. Closing this (because of countless duplication and its popularity)

**Closed by Villageacules** 2016-07-26 01:18 UTC
Labels: Duplicate
