### ISSUE TITLE
TOA crashes world

### ISSUE THREAD

**Issue by RaymondZGames** [Wynncraft/Issues#3377] opened 2015-12-31 00:24 UTC
every time me and my friends do toa the world starts to lag, then it crashes

**Comment by kirby5098** [comment] 2015-12-31 00:40
I wrote a bug report on this too. The issue is that, if you cast meteor, the Wynncraft server crashes.

**Comment by RaymondZGames** [comment] 2015-12-31 11:36
oh

**Comment by ImSickPT** [comment] 2015-12-31 14:06
@kirby5098 cast the meteor where ? in TOA ?

**Comment by DarkDemonDragon** [comment] 2015-12-31 19:28
@RaymondZGames please close this as this is a duplicate as mentioned above.

**Closed** 2016-01-01 07:24 UTC
