### ISSUE TITLE
[BUG] Losing Item when skill glitch

### ISSUE THREAD

**Issue by KokeCacao** [Wynncraft/Issues#4619] opened 2016-03-21 18:51 UTC
Yes. I know this glitch is hard to fix.
But you can make this glitch more "comfortable"...
Because when my inventory is full... I can not receive any my armor and they disappeared.
You can do this:

if (isInventoryFull(player)) {
  spawnItem(player.getLocation(), getItems());
}
getItems(): Item that will drop.
spawnItem(Location loc, ItemStack item): use Entity Item to give back items to player

**Comment by Trixter313** [comment] 2016-03-21 21:22
Duplicate of #4120 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-21 21:22 UTC
