### ISSUE TITLE
Potion Making

### ISSUE THREAD

**Issue by FantasticTuna** [Wynncraft/Issues#2755] opened 2015-12-21 19:42 UTC
The Quest "Potion Making" is not possible, due to the new potions.

**Comment by Trixter313** [comment] 2015-12-22 22:06
Duplicate of https://github.com/Wynncraft/Issues/issues/2725

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!

**Closed** 2015-12-25 20:35 UTC
