### ISSUE TITLE
Questbug WynnExcavation Site B

### ISSUE THREAD

**Issue by iSythEX** [Wynncraft/Issues#4436] opened 2016-03-04 15:23 UTC
# Delete this line if you've searched for a duplicate issue first
The giant purple crystal don't drops the quest item. :(

**Comment by Odnod** [comment] 2016-03-04 16:20
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-04 22:42 UTC
