### ISSUE TITLE
Arrow Storm Isn't Working

### ISSUE THREAD

**Issue by MythikiX** [Wynncraft/Issues#2891] opened 2015-12-22 19:44 UTC
My Arrow Storm spells worked in the update room. But ever since I left that room, I wasn't able to use the spell since then. It simply just drains my mana whenever I use the click combo. Thankfully Jumbla responded to me and said that he will look into it. But I just want to post it here just in case there are other people who can figure out what is wrong.

If it helps, I can tell you that I do know that it has something to do with the bows and not my client. Before it was just my main bow, but I recently got a secondary bow just to use the spell. When I spammed it on a boss mob, I wasn't able to use Arrow Storm on that bow as well.

**Comment by TheNightRanger** [comment] 2015-12-22 19:51
I have been having the exact same problem. My arrow storm  was working yesterday but earlier today when I levelled up my arrow storm stopped working. I went from lvl 35 to 36 so if may have been caused by the upgrade of my other spells but I see no reason why that should affect it.

**Comment by ResistanceGaming** [comment] 2015-12-22 23:35
Same here, thhere is a rumor going around hat this is due to dropping our bows.  My playstyle as archer REVOLVES around Arrow Storm, I can bareley play without it.  Other bows are working, but without my Mythic and Maelstrom, I cant keep up on damage output as well as I would like to.

**Comment by Trixter313** [comment] 2015-12-23 04:08
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Closed** 2015-12-23 16:44 UTC
