### ISSUE TITLE
Bank Space Bug

### ISSUE THREAD

**Issue by cosplayftw** [Wynncraft/Issues#5282] opened 2016-06-22 21:55 UTC
I just bought more bank space (5th line) and I lost 12 jester necklaces I had in there.  It left me with only one. I also lost 1 Call of the Void helm, I had 2.  I was wondering if this was something to do with the fact they were the same item, because my stacked/single items did not get deleted. It also deleted 1 stack of EB but left the other stack of 7 EB.

**Comment by Trixter313** [comment] 2016-06-22 23:34
Duplicate of #4677 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-06-22 23:34 UTC
