### ISSUE TITLE
Not able to play my main class

### ISSUE THREAD

**Issue by demo64738** [Wynncraft/Issues#6525] opened 2016-10-31 16:53 UTC
Hi, i have played Wynncraft last time 2 years ago. If i want to play my Archer class lvl 50 it says:  There has been an error... Try again ingame name: Demo64738

**Comment by Surra-1** [comment] 2016-10-31 16:57
Duplicate of #5418

Read the long post on that page. It will explain the bug, and tells you the options to resolve it.

I would suggest playing on a different class while you wait.

**Closed** 2016-11-05 18:52 UTC
