### ISSUE TITLE
Emerald Merchant in Almuj

### ISSUE THREAD

**Issue by GaPoiVN** [Wynncraft/Issues#4573] opened 2016-03-17 08:01 UTC
I found a Emerald Merchant in Almuj called "emerald Merchant"
I think he should named "Emerald Merchant"
Here is a picture about it : http://imgur.com/k7mKqdC

**Comment by Trixter313** [comment] 2016-03-17 10:20
Duplicate of https://github.com/Wynncraft/Issues/issues/3389

Please direct any future comments to these original thread. Thanks!

**Closed by Trixter313** 2016-03-17 10:20 UTC
