### ISSUE TITLE
/fixquests broken.

### ISSUE THREAD

**Issue by Omnireg** [Wynncraft/Issues#3943] opened 2016-01-31 21:24 UTC
I had to do /fixquests due to me losing my "Clearsight Spectacles", and it gave me "Healing Water" from the "Grand Youth" quest, which I had completed already, and 2 purple crystal shards, from the Wynn Excavation quests, which I had all already completed. I then tried to do /fixquests on other classes to hopefully get the helmet, but no, it did the same, gave me "Healing water" and 2 "purple crystal shards"

VIDEO of Bug:
https://youtu.be/Dtp5hi_G5IY

**Comment by Trixter313** [comment] 2016-01-31 22:59
Duplicate of https://github.com/Wynncraft/Issues/issues/3311

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-31 22:59 UTC
