### ISSUE TITLE
starting quest bug 

### ISSUE THREAD

**Issue by Jolerty** [Wynncraft/Issues#4258] opened 2016-02-24 21:09 UTC
I can't see quest giver Caravan Driver  
![image](https://cloud.githubusercontent.com/assets/17461446/13301038/0f57e7ea-db54-11e5-8474-fe0e47d08376.png)

**Comment by Jolerty** [comment] 2016-02-24 21:10
where to find him ?

**Comment by Odnod** [comment] 2016-02-24 21:30
Duplicate of #4254 please close this issue and direct additional responses to the original.

**Closed** 2016-02-24 21:40 UTC
