### ISSUE TITLE
Potion Making quest

### ISSUE THREAD

**Issue by PineappleEcho** [Wynncraft/Issues#2799] opened 2015-12-22 01:10 UTC
[Potion making] Because of the potion system I cant get the required ingredients for the quest [3 potion of healing 1]

**Comment by Trixter313** [comment] 2015-12-23 01:01
Duplicate of #2725

We recommend closing the duplicate and following the original to stay updated on the status of the issue. Thanks!

**Closed** 2015-12-24 05:23 UTC
