### ISSUE TITLE
Floating chest

### ISSUE THREAD

**Issue by ShadowMage1** [Wynncraft/Issues#7441] opened 2017-02-24 19:41 UTC
Found a floating chest at Mage Island at the same height as Rayshyroth's house.
![2017-02-24_13 40 27](https://cloud.githubusercontent.com/assets/25521684/23318166/fe9ff0e2-fa96-11e6-87b2-f8498fd689de.png)

**Comment by thecoolkogut4** [comment] 2017-02-24 20:45
@ColinRioux

**Comment by DebugMC** [comment] 2017-03-04 19:14
Duplicate of my issue #7154

**Comment by Villageacules** [comment] 2017-03-22 01:02
I've fixed it, thank you for reporting this, I'm not sure why this was fixed earlier to be honest. It was a very quick fix.

**Closed by Villageacules** 2017-03-22 01:02 UTC
