### ISSUE TITLE
Stuck on the beginning of a quest

### ISSUE THREAD

**Issue by geri202** [Wynncraft/Issues#3554] opened 2016-01-05 16:10 UTC
I was doing the WynnExcavation Site A when every one and me has been disconnected. It's okay but when I rejoined I've stuck there:
Excavation Vade: Have you translated the text yet? I told you, take it to the tent up here and give it to Tesha. (Of course there was nothing in my inventory what Tesha could translate.)

Tesha: Take that to Vade, and don't read it!

Anything what could I do is running between them and asking, searching in my inventory for something paper-like thing. And I didn't found anything.
So, what do I do now?

**Comment by MalouPlays** [comment] 2016-01-08 20:08
I have the same thing, i did not get any items and i cant finish this quest or the B & C ones.
Someone should really look at this bug

**Comment by Dar-krusos** [comment] 2016-01-15 10:38
Please try doing /fixquests. If this does not return your lost Quest Item, please reply back here.

**Comment by Trixter313** [comment] 2016-01-30 03:11
Duplicate of https://github.com/Wynncraft/Issues/issues/3351

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-30 03:11 UTC
