### ISSUE TITLE
can interact with items or loot chests.

### ISSUE THREAD

**Issue by catfish909** [Wynncraft/Issues#8250] opened 2017-05-28 00:28 UTC
whenever i try to press o button, open a loot chest, or even clikck on a block in the world, it always displays a message saying i don't have permisson.
![2014-08-27_17 49 17](https://cloud.githubusercontent.com/assets/29007763/26525116/0dd499a6-431b-11e7-8560-df9b4de0e15c.png)

**Comment by catfish909** [comment] 2017-05-28 00:29
wrong pic!
heres the right one
![2017-05-27_20 27 42](https://cloud.githubusercontent.com/assets/29007763/26525122/30c861a4-431b-11e7-84fb-765171242958.png)

**Comment by thecoolkogut4** [comment] 2017-05-28 00:36
Hey there!

This is because the item you were using is a retextured half-slab, and the game thinks you were trying to place it as a result it says you don't have permission to. To fix this right click with an empty hand or your soul point.

Duplicate of #3902

Goodluck.

**Comment by catfish909** [comment] 2017-05-28 00:52
thanks!!!!!!!!!!!!!!!!

**Closed** 2017-05-28 15:27 UTC
