### ISSUE TITLE
button does not work on the quest craftmas Chaos

### ISSUE THREAD

**Issue by RojerKlass** [Wynncraft/Issues#5311] opened 2016-06-26 11:29 UTC
button does not work on the quest craftmas Chaos on the stage to kill Santa. When I click the button, writes - you dont have permission for this area. Help, please.
![2016-06-26_14 15 54](https://cloud.githubusercontent.com/assets/20151198/16361990/3e0a108e-3baa-11e6-97c4-5af79ae9c3ab.png)
![2016-06-26_14 16 00](https://cloud.githubusercontent.com/assets/20151198/16361991/3e0dbe00-3baa-11e6-9bea-b19d6643a4de.png)

**Comment by Trixter313** [comment] 2016-06-26 16:48
Try pressing the button with an empty hand.

Duplicate of https://github.com/Wynncraft/Issues/issues/3902

**Closed by Trixter313** 2016-06-26 16:48 UTC
