### ISSUE TITLE
Can't talk ik guild chat

### ISSUE THREAD

**Issue by Collor** [Wynncraft/Issues#6992] opened 2016-12-25 13:34 UTC
I changed my user name and now I cannot talk with /g and some other commands also don't work.

**Comment by LordHelmchen98** [comment] 2016-12-25 13:41
Duplicate of #3665
There are plenty of other players who are facing the same issue. When you change your username while being in a guild you get stuck/bugged. Unfortunately there is no known way that guarantees you to get out of the guild. You could try to change your name back to the previous one but that's also not a 100% safe way to get you out of the guild.

**Closed** 2016-12-26 05:02 UTC
