### ISSUE TITLE
Able to get out of map/border

### ISSUE THREAD

**Issue by IncBear101** [Wynncraft/Issues#5782] opened 2016-08-20 03:37 UTC
In the realm of light, and the quest, It is possible to get out of the entire map, onto superflat land. Do not ban me for this as I saw this was bannable, to get out, screenshots below:
![2016-08-19_21 34 22](https://cloud.githubusercontent.com/assets/20328015/17828640/0d0f460e-6655-11e6-9a3f-692b37aa0f20.png)
![2016-08-19_21 34 32](https://cloud.githubusercontent.com/assets/20328015/17828641/104b9b7e-6655-11e6-88c4-950bcb8b5264.png)
![2016-08-19_21 34 35](https://cloud.githubusercontent.com/assets/20328015/17828642/1584267e-6655-11e6-9a02-7e388a4cf46e.png)
![2016-08-19_21 34 39](https://cloud.githubusercontent.com/assets/20328015/17828643/18e80812-6655-11e6-93b2-dc6eb700df6e.png)

**Comment by Trixter313** [comment] 2016-08-20 04:05
Duplicate of https://github.com/Wynncraft/Issues/issues/3801

The issues has been internally and will be pushed to the play servers in the next map update.

**Closed by Trixter313** 2016-08-20 04:05 UTC
