### ISSUE TITLE
A non-updated item.

### ISSUE THREAD

**Issue by kristo457** [Wynncraft/Issues#3631] opened 2016-01-10 14:12 UTC
A level 64 rare diamond chestplate called Montefiore (though with fancy french "e" 's) has no new Gavel-stats and has only "Def: 65". I did not need to even identify it.

My guess is that you guys just forgot to update this needle in a haystack, but nonetheless I'd like to use it and the way it is now makes it look fairly worthless. cx

Thank you.

**Comment by Trixter313** [comment] 2016-01-10 15:59
Duplicate of https://github.com/Wynncraft/Issues/issues/3161

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-10 15:59 UTC
