### ISSUE TITLE
Emerald merchant grammatical error

### ISSUE THREAD

**Issue by korczoczek** [Wynncraft/Issues#3498] opened 2016-01-03 10:49 UTC
![2016-01-02_19 25 38](https://cloud.githubusercontent.com/assets/16525015/12078385/025a0a86-b210-11e5-924b-27c846200a20.png)

**Comment by Trixter313** [comment] 2016-01-03 11:26
Duplicate of https://github.com/Wynncraft/Issues/issues/3389

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-03 11:26 UTC
