### ISSUE TITLE
Cant Leave Guild

### ISSUE THREAD

**Issue by AethanoxClockwork** [Wynncraft/Issues#8404] opened 2017-06-19 00:53 UTC
Well, I was playing Wynncraft today and decided I wanted to leave the guild Dark Denials and make my own. I try to leave and I have wasted probably up to 30 soul points trying to leave. It wont let me leave and I do not know why.
![2017-06-18_17 52 02](https://user-images.githubusercontent.com/29527813/27265763-fc56dba4-544e-11e7-8c07-1d5855cd08cd.png)
![2017-06-18_17 52 15](https://user-images.githubusercontent.com/29527813/27265762-fc55f7a2-544e-11e7-888e-46b5a51f3b8f.png)

**Comment by thecoolkogut4** [comment] 2017-06-19 00:55
This is because you changed your name while in the guild. (There are other causes but this is the most popular one) There is currently no fix and you'll have to wait for the devs to update guilds. (They are currently reworking the guild system)

**Comment by Trixter313** [comment] 2017-06-20 01:43
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

**Closed by Trixter313** 2017-06-20 01:43 UTC
