### ISSUE TITLE
Mage Class Login Error

### ISSUE THREAD

**Issue by AuburnTigerFan55** [Wynncraft/Issues#6309] opened 2016-10-02 04:10 UTC
I've never had an issue I've had to report before, this is my first one. I haven't played Wynncraft for about 8 months until I went today to play it. Whenever I did I selected my level 49 mage class, my primary class. It would not load and kept saying, "Error, please try again later". I've saw many other people have this problem also, and they haven't received an answer on how to fix it. I love Wynncraft and I really do not want to have to restart my class. Is there any way I and everyone else can fix this? Or is the team working on a way to fix this bug?

**Comment by Trixter313** [comment] 2016-10-03 01:50
Duplicate of https://github.com/Wynncraft/Issues/issues/5418

Unfortunately there's nothing that the player can do about it, it is up to the admins to fix. There is currently no estimated time for a fix.

**Closed by Trixter313** 2016-10-03 01:50 UTC

**Comment by AuburnTigerFan55** [comment] 2016-11-05 03:59
I logged in today and the issue was fixed for me. I have no idea why this occurred ,but I am happy and thankful it did.

**Comment by Trixter313** [comment] 2016-11-05 19:04
Glad to hear!
