### ISSUE TITLE
WynnExcavation Site C 

### ISSUE THREAD

**Issue by TursedTomb** [Wynncraft/Issues#4267] opened 2016-02-25 11:11 UTC
At the end of quest there is no eny red crystal shards.

**Comment by ItsYourPlay** [comment] 2016-02-25 14:08
I do the Quest WynnExcavation Side C and i go through the portal behind the giant red crystal and as i want to finish the quest Excavator Placardus say: The Purple Crystal Shard from WynnExavation Side B is required to start the Quest, but i stardet it for 2-5 minutes and i can't finish the Quest pls help me i don't know what i can do

**Comment by ItsYourPlay** [comment] 2016-02-25 14:09
And in my Quest book is written down Report back to Exavator Placardus

**Comment by ItsYourPlay** [comment] 2016-02-25 14:13
Here is a screen shots 
![2016-02-25_15 12 04](https://cloud.githubusercontent.com/assets/17165969/13321936/4e8dbb64-dbd2-11e5-83f4-556aedd606e1.png)

**Comment by Odnod** [comment] 2016-02-25 15:00
Duplicate of #4236, please close this topic using the button to do so and redirect any additional comments to the original thread. Thanks!

**Comment by Odnod** [comment] 2016-02-25 15:01
Also @ItsYourPlay make your own issue post.

**Closed** 2016-02-26 01:45 UTC
