### ISSUE TITLE
problem with "The Hunger of the gerts Part 2"

### ISSUE THREAD

**Issue by SolsticeDragon** [Wynncraft/Issues#8439] opened 2017-06-23 07:59 UTC
Im at the part with the captured gert and the quest book says to speak with him but whenever I try to he only says "Human! come closer gert hunger gert eat human" and no matter what I do he wont say the quest stuff, Ive tried switching worlds and I have my mask on pls help.

**Comment by colin350** [comment] 2017-06-23 17:30
Please read the final comment of: #6964

Also duplicate of #6964

**Closed by colin350** 2017-06-23 17:30 UTC

**Comment by PoweradePlayz** [comment] 2017-07-05 19:32
that happend to me to
