### ISSUE TITLE
Could not find a Server to connect, please report.

### ISSUE THREAD

**Issue by KnuddelCreeper** [Wynncraft/Issues#3841] opened 2016-01-24 14:53 UTC
Could not find a Server to connect to, please report.

Picture:

http://prntscr.com/9u77cq

**Comment by SageSlay** [comment] 2016-01-24 15:06
I'm having the same problem as well.

**Comment by Danthegitman** [comment] 2016-01-24 15:18
I was going to report this but it looks like someone already has. Hope this gets fixed ;_;

**Comment by Trixter313** [comment] 2016-01-24 18:03
Duplicate of https://github.com/Wynncraft/Issues/issues/3830

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-24 18:03 UTC
