### ISSUE TITLE
Untradable armor pieces not shown on skin

### ISSUE THREAD

**Issue by Forcellrus** [Wynncraft/Issues#3703] opened 2016-01-15 16:38 UTC
As the title says, in my armor set, I can only see boots on my skin, nothing else. Everything else is not drawn on my skin.
Check out screenshots here, notice that only boots are tradable: http://imgur.com/a/NfwJI

**Comment by ohyeah1357** [comment] 2016-01-15 21:16
It's usually items from quests in general that don't show. However, some exceptions to this are the Mummy's Rag and Champion Armour.

**Comment by Trixter313** [comment] 2016-01-17 19:32
Duplicate of https://github.com/Wynncraft/Issues/issues/3697

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-17 19:32 UTC
