### ISSUE TITLE
chrashes

### ISSUE THREAD

**Issue by ninjamaster330** [Wynncraft/Issues#4096] opened 2016-02-12 21:10 UTC
my game crashes several times and my armor doesn't load

**Comment by Trixter313** [comment] 2016-02-12 23:15
Could you give us some more information like what MC version you're using, where you character is, etc? Thanks!

**Comment by ninjamaster330** [comment] 2016-02-13 01:13
I use 1.8.9

**Comment by ninjamaster330** [comment] 2016-02-13 01:14
and what do you mean where is your character?

**Comment by Trixter313** [comment] 2016-02-13 01:21
Where is the class that you are trying to login as? Could you give us coords or some nearby landmarks? Thanks!

**Comment by ninjamaster330** [comment] 2016-02-13 01:27
I tried all the classes

**Comment by ninjamaster330** [comment] 2016-02-13 01:43
its at ragni

**Comment by Trixter313** [comment] 2016-02-13 03:30
Hmm, could you paste the crash log on a website such as http://pastebin.com/ and post the link here? That might help us determine the problem. I'm not the best at reading crash logs but it could help. Thank you!

**Comment by ninjamaster330** [comment] 2016-02-13 18:20
ok

**Comment by Moe-Ronickah** [comment] 2016-02-19 11:15
Just a reminder, ninjamaster, if this is still going on, would you post a crash log, please?  And if it's fixed, would you close this issue?  Thanks, in advance.

**Comment by DarkDemonDragon** [comment] 2016-03-10 13:14
@ninjamaster330 please respond if this issue is still bothering you, so that we can remedy it. If the issue is not longer persisting please close this.

**Closed** 2016-05-23 00:09 UTC
