### ISSUE TITLE
Name Bug

### ISSUE THREAD

**Issue by Cyranos** [Wynncraft/Issues#3270] opened 2015-12-28 12:18 UTC
I honestly don't know what to say but here's the link to the screen shot
![2015-12-28_04 13 39](https://cloud.githubusercontent.com/assets/16463091/12018613/03a726e4-ad1a-11e5-9145-1b450bbc9cbb.png)

**Comment by Verret001** [comment] 2015-12-28 21:14
Duplicate of these.
#3175 #3209
Follow up on them, Thank you

**Closed by Verret001** 2015-12-28 21:14 UTC
