### ISSUE TITLE
Animal Dungeon

### ISSUE THREAD

**Issue by BrutusGunn** [Wynncraft/Issues#5432] opened 2016-07-08 10:25 UTC
When i go to fight the Boss in the Animal Dungeon, i get a few hits in and then it pushes the boss behind the barrier and now i cant hit him at all.

**Comment by XavierEXE** [comment] 2016-07-08 10:35
This is a known bug, for now doing /class while on the boss room should teleport you out of the room. You can also try to kill it with weapons and spells that do no knockback, or by hitting it with spells that go through walls.

**Comment by Moe-Ronickah** [comment] 2016-07-09 01:16
duplicate of #3191

**Closed by Moe-Ronickah** 2016-07-09 01:16 UTC
Labels: Duplicate
