### ISSUE TITLE
Guild Broken

### ISSUE THREAD

**Issue by Moderocky** [Wynncraft/Issues#7489] opened 2017-03-05 14:42 UTC
Hi,
My guild (Name: Cartel / Tag: KIx) is completely broken.

Nobody can /g (message)
There are three of every player in it.
<img width="579" alt="screen shot 2017-03-05 at 14 37 09" src="https://cloud.githubusercontent.com/assets/14147477/23588177/84b8d826-01b1-11e7-9542-6d05fce2dd86.png">
<img width="504" alt="screen shot 2017-03-05 at 14 37 18" src="https://cloud.githubusercontent.com/assets/14147477/23588178/84e4bd56-01b1-11e7-8b2e-d8afa34a5c46.png">

You can't kick people who are in the guild twice.
Now I can't kick ANYBODY (no message comes up)
I can't change anybody's ranks.
I can't invite anybody.

The guild is now two slots over capacity due to every person now being in three times.

![2017-03-05_14 41 20](https://cloud.githubusercontent.com/assets/14147477/23588204/ea37dbde-01b1-11e7-8674-7afeb36888ba.png)

Exp I gain is not logged.

**Comment by LordHelmchen98** [comment] 2017-03-05 16:21
The problem with one player being in the guild twice or thrice is a duplicate of #3665 
Unfortunately there is no known fix for your problem which is caused due to the name changes of the glitched players.
Originally the problem with the xp is a duplicate of #5349 (not much information there) but in all likelihood related to #3665 as well.
However right now nobody can use guild chat and direct messages only if both are on the same server. Thats not related to name changes but for everyone I guess. At least it happens for me as well and im not glitched in my guild.

**Comment by Moderocky** [comment] 2017-03-05 17:59
Are any of these going to be fixed?

**Comment by Pyromanical** [comment] 2017-03-05 18:35
They will be fixed eventually, but no one knows when.

**Comment by AscendedKitten** [comment] 2017-03-05 22:44
A fix will most likely come after the code refactor is done, but in order to do it properly it'll take some time. For now, there sadly is no solution.

**Closed by AscendedKitten** 2017-03-05 22:44 UTC
