### ISSUE TITLE
Meteoric arch skin problem

### ISSUE THREAD

**Issue by SioN-wynncraft** [Wynncraft/Issues#6600] opened 2016-11-06 03:38 UTC
![2016-11-06_05 35 00](https://cloud.githubusercontent.com/assets/16464117/20035200/2455e2d4-a3e3-11e6-9aea-37d35ae9c078.png)

IGN: _SioN_

Ask if any info is needed

**Comment by LordHelmchen98** [comment] 2016-11-06 03:54
Duplicate of #4548 
Try if it works when you delete the 'legacy' file in your serverresourcepack folder inside the .minecraft folder. If that doesn't work try to use 1.8.9 as it's the version with least bugs and glitches, however you won't be able to see the new item skins in 1.8.9

**Comment by SioN-wynncraft** [comment] 2016-11-06 04:06
ok thanks I dont use it + I found same bug on another item.

**Closed** 2016-11-07 04:30 UTC
