### ISSUE TITLE
Lava Cow Boss Sucks

### ISSUE THREAD

**Issue by Narwhal1** [Wynncraft/Issues#3614] opened 2016-01-09 05:24 UTC
The Lava Cow Boss getting hit outside of the arena because out of our group me and my friend are warriors so we do earth damage. The earth damage seems to somehow have a knock back on him so he just goes outside the arena where no one can hit him nor can he hit us. The only way we can get to him is either somehow getting him to die in the lava so he re-spawns or using our 1 archer to use there magic attack to slowly attack it. But even still it regens almost the same amount they can do so it takes a very long time for them ALONE to kill it. Please fix this because not only is it annoying it is a problem with the server.

**Comment by slendersir739** [comment] 2016-01-09 05:33
Will Bash work?

**Comment by Trixter313** [comment] 2016-01-09 13:30
Duplicate of https://github.com/Wynncraft/Issues/issues/3191
For now, just try and not use spells that knock the boss out.
Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-09 13:30 UTC
