### ISSUE TITLE
[Quest]The Ultimate Weapon

### ISSUE THREAD

**Issue by OJGold** [Wynncraft/Issues#4388] opened 2016-03-01 21:24 UTC
I need 50 soft whetstones for complete the quest The Ultimate Weapon..and whetstones are random-dropping item.. but It's not dropping again.. T_T maybe It's error again? how can I do?.. or just wait for fixing?

**Comment by Odnod** [comment] 2016-03-02 06:50
Duplicate of #4236, please close this issue and put any additional comments on the original. Thanks!

Please know that this bug is very well known and is being worked on.

**Closed** 2016-03-02 07:48 UTC
Labels: Duplicate
