### ISSUE TITLE
Quest Item glitch

### ISSUE THREAD

**Issue by TheQuantumBro** [Wynncraft/Issues#4352] opened 2016-02-29 12:51 UTC
![2016-02-29_16 46 01](https://cloud.githubusercontent.com/assets/17495010/13395956/568adfd6-df0b-11e5-8b33-1b8f945066b0.png)
![2016-02-29_16 46 55](https://cloud.githubusercontent.com/assets/17495010/13395957/56f45e0c-df0b-11e5-8bac-2608961be3c7.png)

Gems for A Marauder's Dues quest didn`t spawn in the cave.FIx it plz!
Of course I change server!

**Comment by Moe-Ronickah** [comment] 2016-02-29 21:05
Duplicate of Quest Items Are Not Spawing #4236 .  Please refer all future comments to the original thread.

**Closed by Moe-Ronickah** 2016-02-29 21:05 UTC
Labels: Duplicate
