### ISSUE TITLE
Problem with the Ghostly Set

### ISSUE THREAD

**Issue by MyNameIsArtifax** [Wynncraft/Issues#5598] opened 2016-07-27 22:32 UTC
Hey guys, so I just completed house of twain and I was killing some mobs around the House of Twain and I got a set chestplate. I identified it and it said : Ghostly Boots. You heard me right, chestplate into ghostly boots. Here's the image if you want to see it yourself. The item is clearly a chestplate but named boots. I am not sure if this is the case with all the items for the ghostly set but yeah can you please fix this soon?
![2016-07-27_15 30 07](https://cloud.githubusercontent.com/assets/20450277/17194883/5d521ce8-540f-11e6-8ff2-1210dfcc1bde.png)

**Comment by MyNameIsArtifax** [comment] 2016-07-27 22:34
Also isn't the chestplate supposed to be Purple?

**Comment by MyNameIsArtifax** [comment] 2016-07-27 22:35
Also it has worse stats then the helmet. Just wondering if that was also switched

**Comment by sammyvsparks** [comment] 2016-07-28 04:00
This is a known issue and a duplicate of 2 open and 1 closed issue when searching for "ghostly boots"
Duplicate of: https://github.com/Wynncraft/Issues/issues/4747

**Closed** 2016-07-28 06:52 UTC
