### ISSUE TITLE
The Lost quest bug (someone fix please grinding is taking too much time)

### ISSUE THREAD

**Issue by Exoltic** [Wynncraft/Issues#8854] opened 2017-08-28 15:02 UTC
I have delivered all of the letters to the members of Dejol's crew, but when I go back to him he asks if I delivered all the letters yet. There are no letters in my inventory and I delivered them all.
![inked2017-08-28_11 09 35_li](https://user-images.githubusercontent.com/31330596/29779779-96fc9ed6-8be1-11e7-94f1-e409f1e47a54.jpg)
I also did /fixquests and no letters returned, so there has to be something wrong with the quest. I even went back to each member and they tell me to find the last member too. I checked the wiki and it said nothing

**Comment by Slime1480** [comment] 2017-08-28 18:31
What does the quest book says?
It is always right.

**Comment by Exoltic** [comment] 2017-08-28 21:30
It says to find the last member, but I already found and talked to all the members and went back again, and I have no remaining letters.
![2017-08-28_17 29 24](https://user-images.githubusercontent.com/31330596/29794596-9dee1d8e-8c16-11e7-8e14-f135dd35b47f.png)

**Comment by Exoltic** [comment] 2017-08-28 21:46
I just went and talked to everyone again, and got the same answer.

**Comment by Slime1480** [comment] 2017-08-29 09:45
Or you are missing someone, or the quest is bugged or something like that. Try to ask a staff, i don't know how to help you now.

**Comment by Exoltic** [comment] 2017-08-29 11:11
I'm not missing someone, I literally went to the wiki and went to everyones coords and talked to them. But thank you for taking the time to respond, I appreciate it :)

**Comment by Exoltic** [comment] 2017-09-02 15:29
I talked to one of the staff members and they said they couldn't do anything (What great staff) and basically tat I just have to deal with it. 10/10 staff helpfulness would n̶o̶t̶ ask again

**Comment by Slime1480** [comment] 2017-09-02 15:41
Well, it was a mod or a CMD?

**Comment by Exoltic** [comment] 2017-09-02 16:37
Well I emailed the support team and Pretzule responded

**Comment by LordHelmchen98** [comment] 2017-09-28 22:10
I bet you lost one of the letters somehow. Sadly /fixquest doesnt return the letters if you are missing one. Thats why lots of people cant proceed this quest. Grinding in higher levels takes even longer btw.
Anyway this is a duplicate of #6032

**Closed by LordHelmchen98** 2017-09-28 22:10 UTC
