### ISSUE TITLE
fierty (legendary spear) staff plz

### ISSUE THREAD

**Issue by wwgaming** [Wynncraft/Issues#3317] opened 2015-12-29 15:18 UTC
I've heard this happen quite a lot but havnt really done anything, it's now happened to me i just got and identified my legendary spear fierty from a naga and relogged now it's just coding on a regular spear, has the same name and what not but it's just coding , don't believe me check the inventory of ww_gaming his spear named fierty is a regular spear in purple coding help me plz

**Comment by Trixter313** [comment] 2015-12-29 20:25
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please refer any future comments to this issue. Thanks!

**Closed by Trixter313** 2015-12-29 20:25 UTC
Labels: duplicate
