### ISSUE TITLE
MASSIVE BUG!!! Logging in crashes wynncraft!

### ISSUE THREAD

**Issue by ittnoraA** [Wynncraft/Issues#5712] opened 2016-08-11 17:32 UTC
Every time I try to log in to a world on my main class the whole world crashes and shuts down. (Notice the extremely high Y coordinate in the picture) My IGN is Aarontti, if you're interested.
This is when I join a world: https://s10.postimg.org/6b3hy5dyh/2016_08_11_20_14_15.png
This is a few seconds later: https://s10.postimg.org/846emgz55/2016_08_11_20_14_31.png

**Comment by ColinRioux** [comment] 2016-08-11 18:56
Have you tried `/kill`

**Comment by ittnoraA** [comment] 2016-08-11 18:58
I have tried, but the server crashes instantly, so I don't have the chance to use it

**Comment by ColinRioux** [comment] 2016-08-12 03:24
Have you tried playing with default minecraft?

**Comment by Moe-Ronickah** [comment] 2016-08-12 05:58
This is a duplicate of #5134 , and has been passed to Salted.

**Closed by Moe-Ronickah** 2016-08-12 05:58 UTC

**Comment by Moe-Ronickah** [comment] 2016-08-12 07:31
@ittnoraA , Salted fixed your position, you should be fine, now.  If you are using any version of MC greater than 1.8.9, please go back to 1.8.9 or lower.  Thanks.
