### ISSUE TITLE
item bug ( no effect )

### ISSUE THREAD

**Issue by dryter97** [Wynncraft/Issues#3645] opened 2016-01-10 22:59 UTC
hi aaron9737 have got an leggins gliched they have looted him they say. this item was leggins pant's whit no effect the screen there i'm not sure but that can be probable other item looted can appear in the game ut is not usefull..,. ( sorry i talking french )

http://www.hostingpics.net/viewer.php?id=90029620160110175237.png

<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="http://img15.hostingpics.net/pics/90029620160110175237.png" border="0" alt="Hebergeur d'image" /></a>

**Comment by trollunderbridg** [comment] 2016-01-10 23:00
I got these too and it happened

**Comment by 63502** [comment] 2016-01-10 23:55
I have the same glitch, but on a legendary spear.

**Comment by oij92** [comment] 2016-01-11 06:15
Me too with my fierté and my pélier (legendary spear and helmet)

**Comment by lXetnosl** [comment] 2016-01-11 13:47
I have that on a mage wand

**Comment by DarkDemonDragon** [comment] 2016-01-12 13:05
Please take a screenshot of it while holding it in your hand showing the name of the item. When you hold something in your hand for a brief second the item name will appear above the hotbar. This will allow staff to identify if this issue is for all items with this name or this is just specific to the item you have.

**Comment by Trixter313** [comment] 2016-01-30 05:21
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-30 05:21 UTC
