### ISSUE TITLE
Can't Access loot chests :(

### ISSUE THREAD

**Issue by Kupopon** [Wynncraft/Issues#4840] opened 2016-04-17 02:33 UTC
Whenever i try to open a loot chest it says "you don't have permission for this area"

I cant even go into the boss room of a dungeon :(

**Comment by Trixter313** [comment] 2016-04-17 02:36
Duplicate of https://github.com/Wynncraft/Issues/issues/3902

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-17 02:36 UTC

**Comment by Yoavronen** [comment] 2016-04-17 06:15
@Kupopon the issue is a known one, it happens because your weapon is a block (retextured) so when you click chests, doors and buttons it thinks you're trying to place them, to prevent this just click those with an empty hand.
