### ISSUE TITLE
Bank glitch

### ISSUE THREAD

**Issue by imedial** [Wynncraft/Issues#4848] opened 2016-04-17 16:28 UTC
I recently upgraded my bank to the 5th line, and all setnitems inside were remove could someone explain to me why this happened

**Comment by Trixter313** [comment] 2016-04-17 16:37
Duplicate of https://github.com/Wynncraft/Issues/issues/4677

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-17 16:37 UTC
