### ISSUE TITLE
Dungeon Glitch

### ISSUE THREAD

**Issue by xGamerFantasy** [Wynncraft/Issues#7503] opened 2017-03-08 03:22 UTC
I was doing a dungeon with my friend and when we opened the door we walked through a walk way and a
Mystery person said 
 Continue to trespass on my territory? you must have no value for you life"
Then we were supposed to pass the barrier blocks but my friend passed though it instead of me now I am stuck in it and can't get out!
![2017-03-07_20 21 23](https://cloud.githubusercontent.com/assets/26266232/23688785/b612dc32-0373-11e7-9b8e-02d43dd9be6b.png)
Do I have to restart?

**Comment by Pyromanical** [comment] 2017-03-08 03:42
Duplicate of #6340

**Comment by ColinRioux** [comment] 2017-03-09 00:23
No date on when this will be fixed, but our hypothesis is minecraft version. If you can reproduce this issue playing on version 1.8.9 (Wynncraft's native version), then please report so at #6340.

**Closed by ColinRioux** 2017-03-09 00:23 UTC
