### ISSUE TITLE
Guild Leave/Join/Create bug

### ISSUE THREAD

**Issue by Meowlegend** [Wynncraft/Issues#6104] opened 2016-09-11 05:09 UTC
![2016-09-11_00 05 53](https://cloud.githubusercontent.com/assets/16465515/18415336/c1bd8c68-77b3-11e6-9e1d-7a81f3ab4a11.png)
If you look in the chat, you see that I leave my guild, but it doesn't allow me to create a new one

**Comment by ZeeLeoNardo** [comment] 2016-09-11 12:05
Yea Having same problem here..

**Comment by Celsonic** [comment] 2016-09-11 15:53
Did you change your ign recently?

**Comment by Moe-Ronickah** [comment] 2016-09-14 01:11
Meowlegend has been changing names every 30 days.  This is a duplicate of #3665 .  You can follow the issue, there.

**Closed by Moe-Ronickah** 2016-09-14 01:11 UTC
Labels: Duplicate
