### ISSUE TITLE
Scroll Merchant Robber!

### ISSUE THREAD

**Issue by Sewnadgy** [Wynncraft/Issues#4718] opened 2016-04-01 03:21 UTC
I was at the Scroll Merchant and i bought ONE Teleportation Scroll. And he sold me 28 scrolls and took almost all of my emeralds! (6 remaining) I had 4 stacks. Please help!!

**Comment by DarkDemonDragon** [comment] 2016-04-01 12:21
4 stacks of....? Please also include Name of the Teleportation Scroll.

**Comment by Sewnadgy** [comment] 2016-04-02 21:20
emeralds

**Comment by DarkDemonDragon** [comment] 2016-04-03 02:26
So... you lost 4 EB? o.O That's not exactly game breaking. Also, name of the Teleportation scroll please.

**Comment by Moe-Ronickah** [comment] 2016-04-03 16:30
When you clicked on the merchant, how long did you hold down your mouse button?
Is your mouse programmable, and if it is, is it programmed to rapid fire?

**Comment by Sewnadgy** [comment] 2016-04-05 02:46
My mouse isn't on rapid fire. I only clicked it normally.

**Comment by Moe-Ronickah** [comment] 2016-04-07 02:26
OK.  As Dragon said, what's the name of the scroll?

**Comment by Sewnadgy** [comment] 2016-04-07 21:27
well, it was the one that teleprts you to...er...raegis...? ragigi?
whatever it was called

**Comment by DarkDemonDragon** [comment] 2016-04-08 01:33
Ragni?

**Comment by Sewnadgy** [comment] 2016-04-08 14:29
yea! thats what it was (i honestly had no idea...)

**Comment by Verret001** [comment] 2016-04-09 20:21
could it of been a connection issue?

**Comment by Sewnadgy** [comment] 2016-04-09 21:48
Maybe...

**Comment by DarkDemonDragon** [comment] 2016-04-10 13:51
I am now testing this bug and will let you know if I can replicate the effects.

**Comment by DarkDemonDragon** [comment] 2016-04-10 13:57
Bug has been tested. If you double click you may buy an extra scroll however it is impossible for all your emeralds to be consumed. Furthermore, since scroll merchants selling scrolls for E are incompatible with Emerald blocks it is impossible for someone to lose a lot of money. Also, since you receive the amount of scrolls you pay for then no loss really happens. Anyway I could not confirm the validity of the bug. Due to nearly no  negative consequences from this bug I feel that it should be closed if it cannot be replicated within a few days.

**Comment by Sewnadgy** [comment] 2016-04-13 01:05
oh, i see. but what will happen when it closes?

**Comment by Trixter313** [comment] 2016-04-13 04:47
All it does is mark the issue as closed, nothing else really. It helps keep the issue tracker uncluttered. As this does seem to have been a one time weird glitch, possibly caused by lag, I'm going to close it. Thanks!

**Closed by Trixter313** 2016-04-13 04:47 UTC
