### ISSUE TITLE
Leaf chestplate un identivieable

### ISSUE THREAD

**Issue by PingasGaming** [Wynncraft/Issues#2144] opened 2015-07-26 11:50 UTC
So I was buying and Identefying a leaf set for anotherclass (lvl 1) and I found out that you cant Identify the chestplate!
![2015-07-26_13 43 53](https://cloud.githubusercontent.com/assets/12382958/8893735/413e19e6-339d-11e5-969f-1201017c48a8.png)

**Comment by Trixter313** [comment] 2015-07-26 12:19
Duplicate of https://github.com/Wynncraft/Issues/issues/1312

Someone already commented this issue there. What we recommend doing is closing the duplicate and following the original if you'd like to stay up to date on the status of your issue. Thanks! =)

**Closed** 2015-07-26 13:20 UTC
