### ISSUE TITLE
Guild leaving

### ISSUE THREAD

**Issue by vbn5202** [Wynncraft/Issues#5572] opened 2016-07-24 15:34 UTC
I joined a guild and changed my username.
Now I cant leave the guild and when I type in guild chat it says the message twice

**Comment by Moe-Ronickah** [comment] 2016-07-25 13:26
A search for "can't leave guild", as described on the front page, would have saved you some time.  This is a duplicate of #3665 .  You can follow the discussion, there, for more information.

**Closed by Moe-Ronickah** 2016-07-25 13:26 UTC
