### ISSUE TITLE
Guild Leave Bug

### ISSUE THREAD

**Issue by Camillerir1** [Wynncraft/Issues#4561] opened 2016-03-15 16:59 UTC
![bug](https://cloud.githubusercontent.com/assets/17856486/13786393/a4580aae-ead7-11e5-8aee-bb2791c26ce2.PNG)
Why ken`t I leave the guild Pls fix it as fast as you ken

**Comment by Tom886** [comment] 2016-03-15 18:19
Did you change your name when you were in the guild? People who do this show up twice in guild tab, and cannot be kicked or leave.

**Comment by Ziggeh2** [comment] 2016-03-29 02:37
@Tom886 s there any way to fix this? I have the same problem.

**Comment by Dar-krusos** [comment] 2016-03-31 05:18
Try getting someone to kick you. If you've waited some time after, and this doesn't work, there's really nothing you can do :/

**Comment by Trixter313** [comment] 2016-04-05 04:53
I see that you've changed you name before, making this a duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-04-05 04:53 UTC
