### ISSUE TITLE
Weapon Bug

### ISSUE THREAD

**Issue by mono2338** [Wynncraft/Issues#5819] opened 2016-08-24 17:20 UTC
I attack with my bow to the ground and it pop out a sentence said"You don't have permission for this area"

**Comment by YunoFGasai** [comment] 2016-08-25 09:38
that's because your bow is actually a block cant really be fixed

**Comment by mono2338** [comment] 2016-08-25 09:52
but there nothing happen before

**Comment by Trixter313** [comment] 2016-08-25 11:02
Duplicate of https://github.com/Wynncraft/Issues/issues/3902

**Closed by Trixter313** 2016-08-25 11:02 UTC

**Comment by Moe-Ronickah** [comment] 2016-08-30 20:43
Not all bows are retextures of the same items.
