### ISSUE TITLE
Is It Just Me?

### ISSUE THREAD

**Issue by LegoCollecter14** [Wynncraft/Issues#6753] opened 2016-11-22 20:49 UTC
https://gyazo.com/5ce9bbe3f5d3f96626557192bc98a29e
Attempted To Log In Today And This Happens.
Restarted Computer And MC Issues Not Happening With Other Servers

**Comment by LordHelmchen98** [comment] 2016-11-22 21:30
I assume you are using the ip play.wynncraft.com. Try .net or .org instead. If that doesnt work go to 1.8.8 and try all ips there. Most of the time that fixed the issue for the players who faced that issue and normally you can then switch back to your preferred version.

**Comment by LegoCollecter14** [comment] 2016-11-23 18:32
Okay Thanks

**Comment by ColinRioux** [comment] 2016-11-24 03:33
Duplicate of #6717

**Closed by ColinRioux** 2016-11-24 03:33 UTC
