### ISSUE TITLE
Weapon texture bug

### ISSUE THREAD

**Issue by PlayerHardcoreBR** [Wynncraft/Issues#6367] opened 2016-10-10 02:06 UTC
Hi Wynncraft !

Note: I'm brazilian. My English isn't very good.

Today I recently see this bug : http://imgur.com/a/hbw0b 

Hope I hav Helped .. See ya !

**Comment by Trixter313** [comment] 2016-10-10 11:03
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

**Closed by Trixter313** 2016-10-10 11:03 UTC
