### ISSUE TITLE
Barrier in Decrepit Sewers

### ISSUE THREAD

**Issue by RandomFangamer** [Wynncraft/Issues#7288] opened 2017-01-29 17:45 UTC
Hi!
In the tunnel between the Fight Challenge and the Parkour Challenge there is a barrier that prevents players from going farther.
More specifically, the barrier is right after the walls speak "You continue to trespass..."
Is this to prevent players from entering a unfinished area? Or is it an error?
Thanks for reading!
Creeper100000

**Comment by AscendedKitten** [comment] 2017-01-29 18:10
I am quite sure the barrier should disappear once the dialogue finishes, would you mind checking it again on a different world / different playthrough?

**Comment by DebugMC** [comment] 2017-01-29 19:20
I just did it myself, its only on one side of the room to stop you from skipping text. Barrier is only above water

**Comment by RandomFangamer** [comment] 2017-01-29 21:23
I moved left and right and even let the dialogue play 10+ times, it wont go away

**Comment by AscendedKitten** [comment] 2017-01-29 22:23
Oh, that probably was the cause. Since Wynncraft didn't really upgrade versions yet there might be some bugs occuring, and I am sorry that you had to experience them. I'll close the issue now, if the problem persists feel free to open a new one.

**Closed by AscendedKitten** 2017-01-29 22:23 UTC

**Comment by DebugMC** [comment] 2017-01-30 20:46
This doesn't happen on 1.8... Tried it :P 1.8-1.11 no errors, however I do want to note you all should just remove the barrier and make the tripwire go across completly.

**Comment by DebugMC** [comment] 2017-02-16 17:26
#6340

**Comment by CloudyBogdan** [comment] 2017-02-27 17:06
I have the same issue! I spent all my decrepit 🔑
