### ISSUE TITLE
Alex head ??? quest

### ISSUE THREAD

**Issue by BrownFriend16** [Wynncraft/Issues#6066] opened 2016-09-06 22:39 UTC
So I was doing the '???' quest with a friend (I saw the instructions on the forums.
And I got the mechanical chip to throw into the yellow flower which didn't work so I switched servers and it turned into an alex head I then as I know the alex heads dont register as normal quest items like in dungeons if you turn the gold block heads into an alex head it wont work.

So I go to the place where you get it and it doesnt spawn, I relog switch servers and everything (yes I used a minecart.) I dont know a way to get another mechanical chip... Maybe im just dumb but im pretty sure it wont work.

**Comment by Trixter313** [comment] 2016-09-08 00:56
Duplicate of https://github.com/Wynncraft/Issues/issues/6019

**Closed by Trixter313** 2016-09-08 00:56 UTC
