### ISSUE TITLE
Creating a guild

### ISSUE THREAD

**Issue by ThePixelPony** [Wynncraft/Issues#3421] opened 2016-01-01 08:16 UTC
When I enter a name, no matter what it is, I get the error "You can only use A-Z characters in your name".
(If the name is under 3 chars, the length error comes up.)

**Comment by Trixter313** [comment] 2016-01-01 10:16
Duplicate of https://github.com/Wynncraft/Issues/issues/3190

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-01 10:16 UTC
