### ISSUE TITLE
cant finish the animal dungeon

### ISSUE THREAD

**Issue by deathsbreath** [Wynncraft/Issues#5674] opened 2016-08-07 05:47 UTC
in the animal dungeon if u r a mage u could get to boss out of the area u should fight him and cant kill it.

**Comment by Moe-Ronickah** [comment] 2016-08-07 12:59
Duplicate of #3191 .  It's fixed on the build server and will be fixed in-game when the next map update comes out.

**Closed by Moe-Ronickah** 2016-08-07 12:59 UTC
Labels: Duplicate
