### ISSUE TITLE
Still Arrows in my Enderchest

### ISSUE THREAD

**Issue by Seamair** [Wynncraft/Issues#5336] opened 2016-06-28 15:34 UTC
I noticed that I still have 2x 64 Stacks of Arrows in my Enderchest and I can't get them out of my chest.
Not sure where to go with that so I thought I should ask here for some help.
I found it kinda annoying because that two Arrow stacks take two of my Enderchest Slots that I really wish to use for something else since you don't need these arrows anymore.

**Comment by Trixter313** [comment] 2016-06-28 16:24
Duplicate of https://github.com/Wynncraft/Issues/issues/3147

Please direct any future contents to the original thread. Thanks!

**Closed by Trixter313** 2016-06-28 16:24 UTC
