### ISSUE TITLE
The helmet "Pelier" will not Id correctly at item identifier.

### ISSUE THREAD

**Issue by TheMeade** [Wynncraft/Issues#1807] opened 2015-04-12 06:10 UTC
Pretty much just what the title says, I got a legendary helmet named Pelier, brought it to an item identifier and it wouldn't identify it. I think I saw someone else post this and thought I saw it said it was fixed, maybe I just read it wrong or misinterpreted it, so forgive me but it continues to be an issue apparently so I am posting the issue again.

**Comment by Trixter313** [comment] 2015-04-12 06:11
Duplicate of https://github.com/Wynncraft/Issues/issues/1312
This is a very odd and touchy bug that seems to sometimes occur but sometimes not.

**Closed** 2015-04-16 17:33 UTC
