### ISSUE TITLE
Guild bug

### ISSUE THREAD

**Issue by crzyWoWgamer** [Wynncraft/Issues#6588] opened 2016-11-05 15:20 UTC
im in a guild called kaboomboom i switched my mc name and its duplicated my name into the guild i am not being able to give xp to the guild and i cant leave the guild PLEASE FIX THIS WYNNCRAFT

**Comment by LordHelmchen98** [comment] 2016-11-05 15:45
Duplicate of #3665
You are by far not the only one who got stuck and there is nothing that can be done right now until staff fixes guilds.

**Closed** 2016-11-05 18:50 UTC
