### ISSUE TITLE
Horses

### ISSUE THREAD

**Issue by Monkey1miner** [Wynncraft/Issues#5438] opened 2016-07-08 23:32 UTC
Horses are super glitchy sometimes you will be on it and your horse will still move but you won't hear the horse moving sound and you won't be moving so when you get off you can be 30 Blocks off with your horse trying to move into a wall and they sometimes will just kick you off and it's really annoying.
IGN: _NovaPvP

**Comment by XavierEXE** [comment] 2016-07-08 23:56
If you're using 1.9 or 1.10, try playing on 1.8.9. Horses are buggy enough as it is and playing in a version the server doesn't fully support doesn't help.

**Comment by Moe-Ronickah** [comment] 2016-07-09 01:41
duplicate of #4809

**Closed** 2016-07-09 01:41 UTC
Labels: Duplicate
