### ISSUE TITLE
Ice Snake not slowing?

### ISSUE THREAD

**Issue by BudderBiscuit** [Wynncraft/Issues#3384] opened 2015-12-31 04:12 UTC
I've noticed that my Ice Snake for my mage no longer slows or freezes things. is this intentional?

**Comment by TrashcanMan** [comment] 2015-12-31 04:40
No, it's a bug, though it has been reported before.

**Comment by Trixter313** [comment] 2015-12-31 05:06
Duplicate of https://github.com/Wynncraft/Issues/issues/3241

Please direct any further comments to the original thread. Thanks!

**Closed by Trixter313** 2015-12-31 05:06 UTC
