### ISSUE TITLE
Galleons graveyard bug

### ISSUE THREAD

**Issue by liual1** [Wynncraft/Issues#7618] opened 2017-03-31 16:16 UTC
Me and my friend were doing the Galleons Graveyard dungeon, and after we went into the door with the cannon guy we would get stuck between barrier blocks and the door who would after a while, close. This really sucks, please fix this
![image](https://cloud.githubusercontent.com/assets/17669282/24559163/01791a24-163e-11e7-8535-949034881c27.png)

**Comment by liual1** [comment] 2017-03-31 16:19
also wanted to point out that when i went to a boat afterwards this happened
![image](https://cloud.githubusercontent.com/assets/17669282/24559331/a22aa83e-163e-11e7-9721-acb2b2491628.png)

**Comment by Trixter313** [comment] 2017-03-31 17:37
Duplicate of https://github.com/Wynncraft/Issues/issues/7616

The dungeon currently has some issues that have been fixed in the build server and will be fixed for the public when the next map push happens.

As for the second issue, it appears to be the same as what is happening in issue https://github.com/Wynncraft/Issues/issues/7008 but for Pirate Cove

**Closed by Trixter313** 2017-03-31 17:37 UTC

**Comment by numbermaniac** [comment] 2017-04-01 01:20
@Trixter313 I think this is actually an instance of the message being printed 4 times, not getting stuck. In that case, it's related to #6977.

**Comment by Trixter313** [comment] 2017-04-01 01:32
Ah, sorry, I thought they were one in the same issue.
