### ISSUE TITLE
Death by fire

### ISSUE THREAD

**Issue by aramaril** [Wynncraft/Issues#4042] opened 2016-02-08 13:35 UTC
not sure if this was intended but it seams to me that any time i catch fire by accident it either kills me outright or brings me down to next to death. I'm level 56 archer with around 2150 hp and i honestly dont think that falling into lava or walking over a fire pit by accident should be that punishing especially since fire never used to do any damage what so ever. I was just this morning finishing the quest the angry village which is supposed to be a level 27 quest. I being over twice the minimum level for the quest should not have to die by fire 3 times due to lag induced miss jumps on the parkour challenge.

**Comment by DarkDemonDragon** [comment] 2016-02-08 15:40
Unfortunately this is an intended feature. Fire damage was buffed after Gavel, but if you feel strongly about this issue go here (https://forums.wynncraft.com/threads/nerf-the-damn-fire-and-lava.110239/) to support a nerf for fire damage. Please close this issue as this is not a bug, but completely intentional.

**Closed** 2016-02-08 18:21 UTC
