### ISSUE TITLE
Logins

### ISSUE THREAD

**Issue by MrMcWalrus** [Wynncraft/Issues#3338] opened 2015-12-30 01:37 UTC
I can enter a world my other classes but not my mage, it says 'there has been an error please try again'. If someone could respond quickly that would be awesome since the mage is my main.

**Comment by Trixter313** [comment] 2015-12-30 02:39
Duplicate of https://github.com/Wynncraft/Issues/issues/3139

Please direct any further comments to the original thread. I hope your issue gets resolved soon. Thanks!

**Closed by Trixter313** 2015-12-30 02:39 UTC
Labels: duplicate
