### ISSUE TITLE
Rodoroc's Scrolls for past towns not working?

### ISSUE THREAD

**Issue by Pikachu118811** [Wynncraft/Issues#6168] opened 2016-09-17 05:25 UTC
![2016-09-17_15 21 59](https://cloud.githubusercontent.com/assets/16696795/18606162/90246ff0-7cea-11e6-9605-c6f3f271ec7a.png)

The scroll merchant in Rodoroc seems to have some issues with scrolls from past towns. Even though it looks like it is selling scrolls from Cinfras, Llevigar etc, when purchasing them they do not appear in your inventory, and you emerald blocks are still taken from your inventory. 

Do note that the scroll in my inventory is a Rodoroc scroll. The Rodoroc scroll merchant still sells the Rodoroc tp scroll without a problem, its just the tp scrolls to past towns.

Is anyone else experiencing this issue?

**Comment by ThunderRemix** [comment] 2016-09-17 06:20
Someone said that this is happening with the scrolls in Troms.

**Comment by TheNeonUmbreon** [comment] 2016-09-17 07:32
It is a problem with the server, some of the servers seem to take your money but not give you a scroll, I recommend stay of server 4 until this bug is fixed

**Comment by Trixter313** [comment] 2016-09-17 09:35
Duplicate of https://github.com/Wynncraft/Issues/issues/6166

**Closed by Trixter313** 2016-09-17 09:35 UTC
