### ISSUE TITLE
Guild Problem

### ISSUE THREAD

**Issue by dragonknight889** [Wynncraft/Issues#5075] opened 2016-05-24 05:23 UTC
There is a wierd glitch with my guild...
I changed my name and there is now 2 of me. Google my guild in the wynncraft website.. and u will find 2 of me. When i type in guild chat 2 of my messages come up.

IGN: dragonknight889
Guild: DumPhucBrudahod

https://wynncraft.com/stats/guild/DumPhucBrudahod

**Comment by YunoFGasai** [comment] 2016-05-24 05:38
this is a duplicate of @4847
please refer all future comments to the original thread.
thanks.

**Closed** 2016-05-24 22:17 UTC
