### ISSUE TITLE
Issue with picking my Warrior class!

### ISSUE THREAD

**Issue by xIwer** [Wynncraft/Issues#7886] opened 2017-04-16 09:36 UTC
Hey!

I have issue with logging in with one of my classes. When I select it it says "There has been an error... Try again". Is there something I can do because I really like to play on Wynncraft :)

/xIwer

**Comment by LordHelmchen98** [comment] 2017-04-16 10:42
Duplicate of #7680 please look there for more information.

**Closed by LordHelmchen98** 2017-04-16 10:42 UTC
