### ISSUE TITLE
Stuck in guild its been this way for a year! IGN mycoalthemonkey

### ISSUE THREAD

**Issue by sukiplays** [Wynncraft/Issues#5746] opened 2016-08-15 20:28 UTC
This is an annoying glitch where even after logging in and out waiting weeks and pming mods it still will not let me leave my guild no matter what I do. After I type yes into the sign that pops up when leaving a guild I hit tab and it still shows the guild on the tab and when I do ./g message it still shows up to my guild in the chat. Please manually remove me from this guild it is not owned by me I am just a recruit and am sick of the people in it making fun of me because I am not able to leave this hell. IGN mycoalthemonkey PLEASE get me out of the guild Dark Horizon
Proof that I am really mycoalthemonkey and that I consent to being removed from my guild. 
https://gyazo.com/93d6faee62c66ba919a7732aee972945 As you can see its unedited and freshly taken by myself and screenshotted onto my pc
Proof I can not leave the guild 
https://gyazo.com/57d389453ca436895b28719d1f5b4651
I have tried to leave it so many times over the time spand of the last 8-9 months and would really appreciate the manual removel of me from the guild. All proof is unedited and legitimate

**Comment by Trixter313** [comment] 2016-08-16 01:45
I see that you've changed your Minecraft username before so that would make this a duplicate of #3665

**Closed by Trixter313** 2016-08-16 01:45 UTC

**Comment by sukiplays** [comment] 2016-08-16 15:49
Well can you please remove me from it that's the only reason I came here because this is where you get help with bugs i think.

**Comment by Trixter313** [comment] 2016-08-16 16:23
There is currently nothing we can do to fix this issue. You can follow the original issue for updates on the status of the issue.
