### ISSUE TITLE
Aldorei's Secret Part1 issue.

### ISSUE THREAD

**Issue by mantyker** [Wynncraft/Issues#4407] opened 2016-03-03 01:02 UTC
# Delete this line if you've searched for a duplicate issue first
So, as I was going to get the sunflower seeds required for the quest, I discovered that they do not spawn. I searched around the area, and even talked to the NPC that owns the sunflowers, but I could not find any. I hope this bug can be fixed as soon as possible so I can continue on with the quest.

**Comment by Odnod** [comment] 2016-03-03 01:47
Duplicate of #4236, please close this issue and direct any additional comments to the original post. Thanks!

Please know that this issue is very well known and is being worked on.

**Closed** 2016-03-05 05:49 UTC
Labels: Duplicate
