### ISSUE TITLE
Armour skins not working

### ISSUE THREAD

**Issue by AndrosKim** [Wynncraft/Issues#2021] opened 2015-06-21 06:53 UTC
I am level 62 archer. I recently put on two new pieces of armour and in the chat, it tells me that they are drawing my new armour. However, even after a long time, the armour skin does not get applied. I have tried relogging and reconnecting but it does not seem to work. I really want to see my new armour skin.
![2015-06-21_14 51 09](https://cloud.githubusercontent.com/assets/12985242/8270764/504a9e7a-1825-11e5-8e6e-03de79bdfd06.png)

**Comment by Trixter313** [comment] 2015-06-21 17:26
Duplicate of https://github.com/Wynncraft/Issues/issues/1909
What we suggest doing is closing this issue and following the original to stay up to date on the status of the issue. Thanks and have a nice day!

**Closed** 2015-07-06 03:37 UTC
Labels: duplicate
