### ISSUE TITLE
Wrath of the mummy

### ISSUE THREAD

**Issue by Toufloux** [Wynncraft/Issues#4266] opened 2016-02-25 09:27 UTC
Hi, I make a Let's play for the quest on your server, but the quest Wrath of the mummy is bugged, I don't see the Achper PNJs, I try to change server but nop, the place show on the wiki is wrong, the PNJ is not here...

**Comment by Odnod** [comment] 2016-02-25 15:02
Duplicate of #4254 please close this issue and put any additional comments on the original thread.

Also, I believe this bug has been fixed.

**Comment by Moe-Ronickah** [comment] 2016-02-26 01:44
This bug has been fixed at this time.

**Closed by Moe-Ronickah** 2016-02-26 01:44 UTC
