### ISSUE TITLE
I LOST MY ARMOR  PLEASE HELP !!!

### ISSUE THREAD

**Issue by Henrique143** [Wynncraft/Issues#2692] opened 2015-12-21 09:48 UTC
when gavel came out i was excited , entered an world , with the new resource pack , then i knew that i need to identifie my armor and weapon , so i was wearing an unidentified armor , when i picked the helmet { my armor was end game armor } my leggens armor and boot dispared , and in the chat it said with red color { YOU cant use stuff that arent identified } OK OK , but my ARMOR , i spent alot of le to get it , and worked hard ! , what i think it should have done is to put my armor in my inventory , BUT my inventory was full , so it didnt DROP my armor , it just removed them ! , and some how now i only have my chest plate and helmet , please give me back my Stalagmites and the leggings , i forgot what its name !

**Comment by 7asoOonyi14** [comment] 2015-12-21 10:23
i wrote that not you

**Comment by EnderStar1203** [comment] 2015-12-21 11:47
I have the same problem with my Mummy's rag i got from a quest, i'm really upset about losing this armor since it's overpowered. I do hope that they will fix this

**Comment by EnderStar1203** [comment] 2015-12-21 12:03
Not only that, they also said i couldn't wear my helmet and boots because my defense skills aren't high enough, that's kind of ridiculous since i am level 40!

**Comment by Trixter313** [comment] 2015-12-22 20:52
Unfortunately Wynncraft has a strict no refund policy so not much can be done. We'd appreciate it if you closed this issue. Thanks!

Also, @EnderStar1203 the defense skills that is referring to is the one in your compass, not your level.

**Comment by Trixter313** [comment] 2015-12-22 21:11
Um, duplicate of https://github.com/Wynncraft/Issues/issues/2688 ??

**Closed** 2015-12-24 20:58 UTC
