### ISSUE TITLE
Can't see myself on a map

### ISSUE THREAD

**Issue by CloudyBogdan** [Wynncraft/Issues#7613] opened 2017-03-30 03:58 UTC
Hi. Just now I started having a problem with seeing myself on a Wynn Map. I simply can't see myself. I could see myself about 20 mins ago. Thanks. Just know that I linked my MC account with my Wynn forums account.

**-Thanks**

**Comment by numbermaniac** [comment] 2017-03-30 04:31
On the online map? If you could see yourself about 20 minutes ago but not now, it's likely just Wynncraft throwing a "too many requests" error (it does this more than it should). Could you open your browser console (open the browser's menu and look for developer tools), and see if it says something like "the website returned an error 429"?

If you are, there's nothing much you can do it about it, except close the map, wait at least 5-10 minutes, then try opening it again.

**Comment by CloudyBogdan** [comment] 2017-03-30 04:46
Yep Online map. Im still not seeng myself. No errors though.

**Comment by Pyromanical** [comment] 2017-03-30 12:59
This along with guild chat and messaging just breaks sometimes.  I saw on Discord that Salted knows, so this can probably be closed.

**Comment by ColinRioux** [comment] 2017-03-30 13:52
Duplicate of #7491

**Closed by ColinRioux** 2017-03-30 13:52 UTC
