### ISSUE TITLE
Cant leave guild

### ISSUE THREAD

**Issue by yorimtschgi** [Wynncraft/Issues#3702] opened 2016-01-15 16:05 UTC
Im trying to leave my guild now for like 2 days or so, but the sign never works,can you help me please 😁

**Comment by Trixter313** [comment] 2016-01-17 19:28
Duplicate of https://github.com/Wynncraft/Issues/issues/3405

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-17 19:28 UTC
