### ISSUE TITLE
My guild is so glitched, I have two owners. 

### ISSUE THREAD

**Issue by TimThePvpMaster** [Wynncraft/Issues#5401] opened 2016-07-05 17:43 UTC
Well, i think the title says enough... My guild is so glitched out, Myself and enough member can not leave it. And when you go on https://wynncraft.com/stats/guild/New%20Brotherhood , it says I have two owners. UM? Is there a way an admin or mod can kick me out of my own guild? I am the owner sadly, and no one can kick me or my friend. It just takes my usuall soul points, says i left, but then i can still use guild chat and pratically i'm still in it. Is there any possible way at all this can be fixed? If so, can anyone help?? Thank you so much!!! I'm know that guilds are so glitchy right now, but please, how the world do I have two owners?! thanks guys...

Users of myself and my friend:
TimThePvpMaster
Vuex

**Comment by Moe-Ronickah** [comment] 2016-07-05 22:15
" I'm know that guilds are so glitchy right now,"  Guilds are a mess and there is nothing we can do except wait for the code to be fixed.

**Comment by Moe-Ronickah** [comment] 2016-07-05 22:17
duplicate of #4982 and #4099

**Closed by Moe-Ronickah** 2016-07-05 22:17 UTC
