### ISSUE TITLE
Guild bug

### ISSUE THREAD

**Issue by RealNeuhier** [Wynncraft/Issues#5096] opened 2016-05-27 17:58 UTC
We got a bug on our guild Firestone, our Owner poppy655986 is taking 2 slots cause of a namechange.

Would be kind if you could remove the first one or at least give us a tip how to fix it.

**Comment by Trixter313** [comment] 2016-05-27 23:25
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

The issues are being caused by the same thing and as of right now there isn't a solution but we are working in getting it fixed. Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-05-27 23:25 UTC
