### ISSUE TITLE
Broken Wizard Staff called Devoreuse

### ISSUE THREAD

**Issue by MythicFX** [Wynncraft/Issues#3666] opened 2016-01-12 08:17 UTC
I just got this wand that has a huge lore and i was thinking it was good for my lvl 8 mage when it gets to a high level and didnt think it was broken here's some screenshots
![2016-01-12_16 17 17](https://cloud.githubusercontent.com/assets/16662823/12258225/f90291da-b947-11e5-84a8-8115f56d3dfa.png)
![2016-01-12_16 17 28](https://cloud.githubusercontent.com/assets/16662823/12258228/fdb1f8f6-b947-11e5-8989-53102942194b.png)

**Comment by DarkDemonDragon** [comment] 2016-01-12 13:03
Duplicate of #3175 

Please direct any future comments to the original thread. Thanks!

**Closed** 2016-01-15 01:27 UTC
