### ISSUE TITLE
 My Bobs Mythic Bows is Broken

### ISSUE THREAD

**Issue by MadDog1238** [Wynncraft/Issues#6185] opened 2016-09-18 05:10 UTC
G'day, Can someone plz help me, im having trouble with my "Bobs Bow" i used to play alot and i have started again, but i tried to identify my "Bobs Bow" and it says the item cant be identified again.... can someone plz help me, i spent so much time getting that bow and now i cant even use it

-MAD_DOG1238

**Comment by ThunderRemix** [comment] 2016-09-18 06:07
Yet another item falls to this issue.

**Comment by MadDog1238** [comment] 2016-09-22 05:17
Can Someone plz help me with this! its been 4 days since i posted the last comment!!

**Comment by AckroWynn** [comment] 2016-09-22 12:38
Please post a picture of it.

**Comment by legoman724** [comment] 2016-09-24 13:32
You can't re-identify a bobs mythic because it has set stats which you get when you buy it

**Comment by Moe-Ronickah** [comment] 2016-09-25 22:21
Without a picture, there is little to nothing that we can tell you.

**Comment by Trixter313** [comment] 2016-10-10 10:49
Appears to be a duplicate of https://github.com/Wynncraft/Issues/issues/6171

**Closed by Trixter313** 2016-10-10 10:49 UTC
