### ISSUE TITLE
Horse Bug

### ISSUE THREAD

**Issue by TheWiseDisorder** [Wynncraft/Issues#2968] opened 2015-12-23 13:46 UTC
Hey idk if u noticed but the horses seem to be buggy... pls fix :3

**Comment by Trixter313** [comment] 2015-12-23 19:26
A little more description would be nice but I'm assuming you're talking about them not moving very fast and being kinda jittery. These are caused by lag so once the servers start dying down and becoming less crowded it should go away but there will always be lag so this won't ever be fully fixed until it's fixed in Minecraft itself.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Closed** 2015-12-23 20:03 UTC
