### ISSUE TITLE
Guild /leave bugs

### ISSUE THREAD

**Issue by Zevys** [Wynncraft/Issues#3514] opened 2016-01-03 21:12 UTC
I did /guild leave and it pops up a sign where it tells me to say yes or no to leave the guild. I type yes and i'm still in this guild. 

Staff please help IGN: Zevys | VIP  |

**Comment by OhZeltar** [comment] 2016-01-04 08:53
Same problem with me.
IGN: OhZeltar

**Comment by CrafterTheMaster** [comment] 2016-01-05 00:31
Me too. IGN: CrafterTheMaster

**Comment by Trixter313** [comment] 2016-01-11 22:08
Duplicate of https://github.com/Wynncraft/Issues/issues/3405

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-11 22:08 UTC
