### ISSUE TITLE
Kicked for flying repeatedly

### ISSUE THREAD

**Issue by TheEpicCorgi** [Wynncraft/Issues#5576] opened 2016-07-24 22:13 UTC
Whenever a server restarts i get put in the lobby, But becuase of the lag that happens i get stuck in the air for a second. the game registers it as flying and kicks me back to another lobby. the process continues to repeat until i find a way to close minecraft

**Comment by Moe-Ronickah** [comment] 2016-07-25 13:40
This is a duplicate of #5409 .  You can follow our discussion, there, and see if we can help you, also.

**Closed by Moe-Ronickah** 2016-07-25 13:41 UTC
Labels: Duplicate
