### ISSUE TITLE
spider cave saccharum

### ISSUE THREAD

**Issue by chrisko131** [Wynncraft/Issues#4246] opened 2016-02-24 12:26 UTC
idk y,there is no saccharum spawning at da pit of da spider cave.

**Comment by DarkDemonDragon** [comment] 2016-02-24 13:17
Please provide screenshots as you may be at the wrong location. If no saccharum spawn then I recommend switching worlds.

**Comment by NeyRisson** [comment] 2016-02-24 14:39
I have the same problem,([this is the right place](http://www.noelshack.com/2016-08-1456324375-minecraft-1-8-24-02-2016-15-19-06.png))
I switch worlds many times but nothing

**Comment by DarkDemonDragon** [comment] 2016-02-24 15:54
Duplicate of #4236 Please close this and follow the original

**Closed** 2016-02-26 01:33 UTC
