### ISSUE TITLE
Guild stats are incorrect

### ISSUE THREAD

**Issue by crazydud24** [Wynncraft/Issues#4131] opened 2016-02-14 19:04 UTC
So I started a new guild today and called it forge dragons but whenever I type /guild stats it tells me about a Lv 26 guild called nobody with no members even though every thing else is correct,xp, tab shows the proper members and I even tried attacking. Every thing went well until I died. But the weird thing is that the first time I used /guild stats it gave me the correct info.

**Comment by Dar-krusos** [comment] 2016-02-15 00:39
Yeah, this is a long-standing [issue](https://github.com/Wynncraft/Issues/issues/3799). Check out that one and comment there if you have information we don't have yet.

**Comment by DarkDemonDragon** [comment] 2016-02-15 04:50
As mentioned this is a duplicate of #3799 Please close this issue and follow the original

**Closed** 2016-02-15 16:28 UTC
