### ISSUE TITLE
Permission Thing

### ISSUE THREAD

**Issue by omintrevor** [Wynncraft/Issues#5695] opened 2016-08-09 05:18 UTC
when i kill a mob near a wall or something it says "you don't have permission for this area" and its getting annoying cause i get spamed with it.I think its because the bow is a block and i am not allowed to place it?

**Comment by Trixter313** [comment] 2016-08-09 05:26
Is there a chest nearby?

**Comment by omintrevor** [comment] 2016-08-09 05:33
no

**Comment by Moe-Ronickah** [comment] 2016-08-11 04:10
Duplicate of #4548 .

**Closed by Moe-Ronickah** 2016-08-11 04:10 UTC
Labels: Duplicate
