### ISSUE TITLE
As if server crashes weren't enough...(Item bugs/corruption)

### ISSUE THREAD

**Issue by SpitfiresThunder** [Wynncraft/Issues#3647] opened 2016-01-11 01:02 UTC
I thought that server crashes were the end of my problems when it came to losing my items. In hindsight, I should have figured that Wynncraft would find another way to screw me over.

I have no idea what causes this, but it almost seems to spread like some sort of virus. When the update had first came out, I spent most of my time identifying old items. One of these was a Legendary Dislocator (Assassin Weapon). A few days after identifying it and putting it in a storage class, I came back to it to find that it became a pair of normal shears, lost it's legendary color, and when moused over presented an extremely long line of script;
![2016-01-10_19 55 50](https://cloud.githubusercontent.com/assets/16551534/12225244/3dfcec06-b7d4-11e5-9415-c8a7228ac694.png)
![2016-01-10_19 55 54](https://cloud.githubusercontent.com/assets/16551534/12225245/40d97cb4-b7d4-11e5-8acd-96e3defce8de.png)

I haven't been playing my assassin class, so I just kind of let it go, assuming Wynncraft would fix it. Naturaly, it has remained this way up to this day. Recently, it happened to another item: A Rare Montefiore (Chestplate). I had been saving it up in by bank for my main Mage class, and low an behold, it has done the same thing. Only difference is that it retained the Rare color.
![2016-01-10_19 57 58](https://cloud.githubusercontent.com/assets/16551534/12225270/f71b0f74-b7d4-11e5-8886-896c573c69cd.png)
![2016-01-10_20 01 33](https://cloud.githubusercontent.com/assets/16551534/12225271/f9e45ee0-b7d4-11e5-867c-ab4f6a08843d.png)

**Comment by Trixter313** [comment] 2016-01-11 05:45
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-11 05:45 UTC
