### ISSUE TITLE
guild member

### ISSUE THREAD

**Issue by Ricardo65432** [Wynncraft/Issues#4847] opened 2016-04-17 16:15 UTC
# Delete this line if you've searched for a duplicate issue first
somehow one of my guild members [who hasnt been on in a long time] appears twice in the tab list, due to that, kicking him wont work

**Comment by Odnod** [comment] 2016-04-19 17:55
This is due to a current bug that occurs when you change your username whilst in a guild. Glitched players cannot leave the guild by any means, receive chat messages twice and appear twice in the guild tab. Unfortunately there is nothing anyone can do until this glitch is fixed.

**Comment by aira1101** [comment] 2016-04-21 04:42
Same issue here , dunno how to fix it :(

**Comment by Trixter313** [comment] 2016-05-24 22:16
Duplicate of https://github.com/Wynncraft/Issues/issues/3665

Please direct any future comments to the original thread. Thansk!

**Closed by Trixter313** 2016-05-24 22:16 UTC
Labels: Guilds
