### ISSUE TITLE
Lava Cow [Animal Dugeon]

### ISSUE THREAD

**Issue by Sindricus** [Wynncraft/Issues#4047] opened 2016-02-08 21:44 UTC
My character is an Archer. After pinning the Cow into a corner I loaded into him over and over
at about half health he popped outside of the border.
I was unable to shoot him and he was unable to shoot me so I restarted my game.
Please Fix. Lost a key.

**Comment by Troll2828** [comment] 2016-02-09 00:04
you can just do /class and the boss will reset

**Comment by Sindricus** [comment] 2016-02-09 01:13
That will make you exit the dugeon.

**Comment by Trixter313** [comment] 2016-02-09 02:44
Duplicate of https://github.com/Wynncraft/Issues/issues/3191

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-09 02:44 UTC
