### ISSUE TITLE
When I logged in my "crystal necklace" and my ring was gone from my armor slots!

### ISSUE THREAD

**Issue by ErikC17** [Wynncraft/Issues#4209] opened 2016-02-21 13:09 UTC
# Delete this line if you've searched for a duplicate issue first

**Comment by Trixter313** [comment] 2016-02-21 14:45
Duplicate of https://github.com/Wynncraft/Issues/issues/4120

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-21 14:45 UTC
