### ISSUE TITLE
Bob the Zombie not spawning

### ISSUE THREAD

**Issue by BaitUnderscore** [Wynncraft/Issues#4714] opened 2016-03-31 11:01 UTC
Hi there

so I started the Bob's Lost Soul quest

and Wedyf told me to get Bob's Tear

so I went to Ragni to find Bob's zombie form

I couldn't find him

Did he get removed?

**Comment by DarkDemonDragon** [comment] 2016-03-31 12:14
No he is just semi-rare to find. The problem is that only one "Bob the Zombie" can spawn in Ragni so if he spawns somewhere weird and can't move around then you'll never find him. I suggest 2 methods:
Method 1
1. Find a world with no one at Ragni (pick worlds with low player counts)
2. Go to the center of Ragni 
3. Skim around for Bob.
4. If Bob cannot be seen then go back to center and do /class and wait 5-10 seconds before reselecting your character
      *This reloads the area and cause mobs to respawn which means Bob will be in another location
5. Repeat 3 and 4 until tear is obtained

Method 2
1. Go on the forums and head to the trade market. 
2. Find a seller or place a buy offer
3. Buy it.

**Closed** 2016-03-31 17:07 UTC
