### ISSUE TITLE
The Hidden City airship bug

### ISSUE THREAD

**Issue by Kroko64** [Wynncraft/Issues#5862] opened 2016-08-29 10:11 UTC
If you complete the puzzle to get out of the cell of the airship it says that you dont have the permission to use this command in the chat and you are stuck in there

**Comment by TheLMiffy1111** [comment] 2016-08-29 12:14
duplicate, can confirm

**Comment by Muddykipper** [comment] 2016-08-29 18:38
Also happened with me.

**Comment by Dystinct** [comment] 2016-08-29 19:33
Here is my screenshot for proof.
![2016-08-29_14 27 49](https://cloud.githubusercontent.com/assets/17397791/18064547/8a5e973e-6df5-11e6-951a-a909a2a2b71c.png)

**Comment by siphsky** [comment] 2016-08-29 20:53
me too :/

**Comment by Trixter313** [comment] 2016-08-30 23:07
Duplicate of https://github.com/Wynncraft/Issues/issues/5855

**Closed by Trixter313** 2016-08-30 23:07 UTC
