### ISSUE TITLE
Complete Armor and Assecoirs dropped

### ISSUE THREAD

**Issue by TheRealfanibu** [Wynncraft/Issues#4335] opened 2016-02-28 17:24 UTC
After I joined a Server, I got attacked by a Monster and I went back to hub while the Monster was attacking me. Then I joined another Server and there were my armor and Assecoirs dropped on the ground like I would have died in Singleplayer, but my inventory didn't drop. Then there came an other Monster and attacked me and oneshotted me, because my armor dropped. After I wanted to go to the place where I died (Olux Forest), but the items weren't there anymore. And now I lost my whole armor and accesoires. So could you set my inventory to the 27.02.2016 please (Yesterday)? Would be nice :)

P.S: My Ingamename is "fanibu"

**Comment by Trixter313** [comment] 2016-02-28 19:23
Duplicate of https://github.com/Wynncraft/Issues/issues/4304

Your soul points probably all got temporarily reset to 0, causing all of the armor & accessories to pop off. Unfortunately Wynncraft has a strict no refund policy so there's nothing we can do about the already lost items but we are working on fixing the issue that skill points get set to 0 temporarily, to prevent this from happening again.

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-28 19:23 UTC
