### ISSUE TITLE
Not able to join Wynncraft servers

### ISSUE THREAD

**Issue by Derysed** [Wynncraft/Issues#5521] opened 2016-07-19 13:00 UTC
So... 2 days ago i was playing on wynncraft as i usually do... after i took a break and went to play on cs:go i returned on minecraft and i couldn't enter wynncraft anymore... plz help i tried everything but i still can't get in... i miss wynncraft so much even if i didn't play it for only 2 days

**Comment by sammyvsparks** [comment] 2016-07-19 14:29
@Derysed can you give more detail? What does the server do/say? Does it show offline or not let you connect?

**Comment by Derysed** [comment] 2016-07-20 12:43
ok it just says can't connect to server and i don't know why cause i was playing normally before... when i try and go in the server it give me an internal exception

**Comment by Moe-Ronickah** [comment] 2016-07-20 14:00
Duplicate of #4552.  Please read the comments on that issue for further assistance.

**Closed** 2016-07-20 14:00 UTC
Labels: Duplicate
