### ISSUE TITLE
Quest Items Are Not Spawing (Not a Wynn Issue)

### ISSUE THREAD

**Issue by trickstini** [Wynncraft/Issues#4236] opened 2016-02-24 00:58 UTC
SIGH yet another bug and yet another quest.

on this part of the quest, maps are supposed to fall and drop for you to pick up for the quest, but it isnt -.-

![2016-02-23_18 57 29](https://cloud.githubusercontent.com/assets/17256464/13272126/619afb5a-da5f-11e5-9ca6-6440d4b30d4e.png)

**Comment by Troll2828** [comment] 2016-02-24 01:14
you can switch the server, this might be caused by lag.

**Comment by trickstini** [comment] 2016-02-24 01:18
not to be rude, but dont you think i would try that ;/

**Comment by Inamicusatto** [comment] 2016-02-24 06:28
was told to post here on matters similar to this post. On the quest purple and blue, the magical fragment does not spawn to be picked up.

**Comment by DarkDemonDragon** [comment] 2016-02-24 13:23
This is a widespread issue affecting ALL items that are supposed to spawn. The Admins are aware of the situation are are currently working on it. Check again in a few hours or so.

**Comment by trickstini** [comment] 2016-02-24 15:48
I feel popular, everyone is being redirected to my post ;D nevertheless should I close this since the admins are aware and working on it? Or keep it open so if anyone else post you can redirect them here?

**Comment by Odnod** [comment] 2016-02-24 16:21
Trick we do have confirmation from a moderator that this issue is being worked on, but it is up to you whether or not you want to close it.

**Comment by Azeyk** [comment] 2016-02-24 16:28
Il y a aussi une quête à Selchar la tour ne donne plus de block de sable !

**Comment by Azeyk** [comment] 2016-02-24 16:28
![2016-02-24_17 28 28](https://cloud.githubusercontent.com/assets/17456650/13292428/fde01b00-db1b-11e5-9ef3-76bdb3f22286.png)

**Comment by trickstini** [comment] 2016-02-24 16:30
I'll keep it up, Bc it looks like people are continually ousting about this without actually looking for other posts -_-

**Comment by Azeyk** [comment] 2016-02-24 16:33
Ou veut tu aller alors tu sais ?

**Comment by Azeyk** [comment] 2016-02-24 16:37
Bref, sinon où peut on en trouver ?

**Comment by trickstini** [comment] 2016-02-24 17:06
^ yo mate lets umm... Use English plz

**Comment by trickstini** [comment] 2016-02-24 17:11
Bonjour compagnon , je serais très heureux si vous pouviez utiliser l'anglais sur ce post . Je vous remercie. En outre, ils sont corriger le bug en ce moment , donc s'il vous plaît soyez patient.

PS . cela est translate si mon français est mauvaise , je suis désolé

**Comment by FryBai** [comment] 2016-02-24 18:22
![2016-02-24_17 47 01](https://cloud.githubusercontent.com/assets/17458006/13296021/720da8ec-db23-11e5-8731-be5767ad5f6c.png) The Aerolia Flower was not spawning ;-;

**Comment by Odnod** [comment] 2016-02-24 18:22
@FryBai yup, thankfully this issue is being worked on as we speak.

**Comment by FryBai** [comment] 2016-02-24 18:23
oh ok, hope it gets fixed ;)

**Comment by TheIvyX** [comment] 2016-02-24 19:31
Is this affecting NPCs as well? Rynver isn't spawning for me and switching servers doesn't seem to help. http://i.imgur.com/IDGjQBz.png

**Comment by Odnod** [comment] 2016-02-24 19:44
@TheIvyX that might be something different, not sure.

**Comment by Azeyk** [comment] 2016-02-24 20:49
Okay trickstini thanks for your information, I expect the problem to be solved at thanks !

**Comment by TheIvyX** [comment] 2016-02-25 12:35
NPCs are spawning again. They weren't spawning when the servers were lagging but you could enter them anyway. When looking at how many players each server had, they were all at 0/60, but you could still enter and play around.

**Comment by trickstini** [comment] 2016-02-25 13:33
ewh.. Fiora..

**Comment by natourod1** [comment] 2016-02-25 15:33
so... it's normal? i have the same bug with wynnexcavation site B , no purple crystal drop :/

**Comment by trickstini** [comment] 2016-02-25 15:35
It's not normal, it's being fixed right now

**Comment by MikeBlackburn** [comment] 2016-02-25 18:19
The Crystals in WynnExcavation Site B are still not dropping.

**Comment by Place-Name-Here** [comment] 2016-02-25 18:22
Gold bars also won't spawn in Jankans mine. :/

**Comment by mdragonwhite** [comment] 2016-02-25 20:44
the sand in the sister city quest is not spawning

**Comment by mdragonwhite** [comment] 2016-02-25 21:03
this doesn't help at all

**Comment by Odnod** [comment] 2016-02-25 21:03
@mrdragonwhite The issue is being worked on, please have patience.

**Comment by mdragonwhite** [comment] 2016-02-25 21:14
ok thx,when it get fixed someone will post here ?

**Comment by MrMaggen** [comment] 2016-02-25 21:24
I was doing quest and wanted to do Site B quest I used the yello crystal and ran down the mine to the man that punched me down a hole and got down walked to the man that talks about how to get in to the crystal got in to the crystal but there were no littel ones so I thoght I was lagging and ran out the back i accidently clicked the first man and then he said "Hello there! We are working very hard here at this Excavation site! We have one in Almuj as well, I think you should check i out!" and then my quest book said what I had to speak to him but then I did it he said the same thing and then I got down to the crystal it still did not drop and and the quest npc did not work it does not fix it when I relog or do /fixguest plz help me I have No Idea and I want to do the quest :( 

Here you can see I have the crystal and it says I have to talk to him and it does not work
![2016-02-25_21 24 49](https://cloud.githubusercontent.com/assets/17232865/13334887/8c66ed5c-dc0e-11e5-8008-dc126ddb5538.png)

**Comment by MrMaggen** [comment] 2016-02-25 21:27
just a question do someone think it can be fixed or am i gonna need to start over to do the quest plz I worked very hard

**Comment by MrMaggen** [comment] 2016-02-25 21:30
btw I lost one then I did it the first time can I plz get a new one if an admin seis this?

**Comment by Odnod** [comment] 2016-02-25 22:27
Ayy @MrMaggen welcome to the club of getting screwed over by this quest.

There is no word on when exactly it will be fixed, but it is being worked on. When it is fixed, I will alert everyone on this post.

**Comment by MrMaggen** [comment] 2016-02-25 22:37
THANKS YOU VERY MUCH FOR SAYING SOMETHING

**Comment by MikeBlackburn** [comment] 2016-02-25 22:48
Do we have an estimated time before the issue is fixed. Also, is the depressing Item porblem being looked at?

**Comment by Odnod** [comment] 2016-02-25 23:03
@MikeBlackburn I can not give an answer to either if those questions, however this one will likely be fixed soon.

**Comment by MrMaggen** [comment] 2016-02-25 23:50
Is it today or in a week or in a month or in a year or when I die :(

**Comment by TrashcanMan** [comment] 2016-02-26 04:57
@MrMaggen the bug will be fixed "soon".
In all seriousness though they're probably working really hard on this right now, just be patient. I'm guessing within a month since it's such a major bug but I don't know.
Fortunately I grabbed about 40 faded maps before this happens so I'm set for multiple lives.

**Comment by natourod1** [comment] 2016-02-26 09:49
the bug concerned all the drop item in quest?

**Comment by MrMaggen** [comment] 2016-02-26 12:05
It is not fixed jet :(

**Comment by trickstini** [comment] 2016-02-26 12:37
guys plz, for the love of god shut up and calm down! IT IS BEING WORKED ON! now go do something else while this is being fixed and stop posting here complaining about it, it will not help it get fixed any faster!

**Comment by MrMaggen** [comment] 2016-02-26 14:03
![2016-02-26_15 03 36](https://cloud.githubusercontent.com/assets/17232865/13354258/1aa45768-dc9a-11e5-9723-9dd50b94cce7.png)

**Comment by MrMaggen** [comment] 2016-02-26 14:24
Just did relic leggings and it is pretty stupid becouse when you have taken the relic and go out of the end exit you just fall down from 100 blocks and dies plz do something

**Comment by DarkDemonDragon** [comment] 2016-02-26 15:42
@MrMaggen those posts are 100% unrelated to this topic. Please remove your posts and create a separate issue. Also, if you are stuck in any area simply use a scroll or /kill if you have enough Soul Points.

**Comment by MrMaggen** [comment] 2016-02-26 17:15
Fine :dancer:

**Comment by DarraghWynn** [comment] 2016-02-26 17:29
Concerning this topic, I'm wondering if anyone who is willing to help out another player by giving them the item if they have it, for example. If the player has 12 Hourglass sand for the Sister City quest. If someone needs them items and cannot obtain them because of this bug, please feel free to offer the players the item or at least offer and charge them emeralds. I know this bug is probably going to be fixed soon but please do use this alternative solution for the moment

**Comment by MikeBlackburn** [comment] 2016-02-26 17:33
Sadly that might not work so well because alot of those items a untradable items....

**Comment by DarraghWynn** [comment] 2016-02-26 17:33
Oh yeah.. Completely forgot about that

**Comment by mdragonwhite** [comment] 2016-02-26 18:21
Kappa (im posting to make everyone remember that this exist)

**Comment by Josh-Sturgeon** [comment] 2016-02-26 22:56
Not seen this referenced anywhere else, so I'll add it in case it aids in the fixing of the problem. The quest: 'A Marauder's Dues' is also affected by this bug in that you can't obtain the gem item from inside the chasm.

**Comment by SoulAyce** [comment] 2016-02-27 10:56
The Canyon Condor quest got  finally fixed

**Comment by MikeBlackburn** [comment] 2016-02-27 15:02
WynnExcavation site B is fixed!!!

**Comment by SoulAyce** [comment] 2016-02-27 15:25
Does any one know if its a glitch or bug that the star thief quest, the thief, isnt dropping the star

**Comment by SoulAyce** [comment] 2016-02-27 15:29
NVM

**Comment by Odnod** [comment] 2016-02-27 20:08
Alright it seems that this bug has been fixed @trickstini @Troll2828 @Inamicusatto @DarkDemonDragon @Azeyk @Josh-Sturgeon @DarraghWynn @mdragonwhite @MrMaggen @natourod1 @Place-Name-Here @TheIvyX @FryBai

**Comment by Place-Name-Here** [comment] 2016-02-27 20:20
YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS THANKYOU ODNOD!!!!!!!!!!!!

**Comment by Moe-Ronickah** [comment] 2016-02-29 20:55
It has returned.

**Comment by duclong889** [comment] 2016-03-01 04:33
![image](https://cloud.githubusercontent.com/assets/17551875/13417775/6efbf726-dfa1-11e5-862e-6db60e811972.png)
no faded map is spawning

**Comment by atsku8788** [comment] 2016-03-01 09:22
In guest Sister city hourclass sand doesnt drop

**Comment by Sonicmaster418** [comment] 2016-03-01 15:48
Purple and Blue quest magical crystal not spawning.

**Comment by EJCrusher** [comment] 2016-03-01 22:28
7 whole days, damn.

**Comment by kmo900** [comment] 2016-03-02 02:37
its back since starting quest cave spider and also suspended flowers :(
HELP plz

**Comment by lemonpillow207** [comment] 2016-03-02 10:13
hourglass sand still not dropping

**Comment by atsku8788** [comment] 2016-03-02 11:51
still not hourglass sand

**Comment by RelativeThinking** [comment] 2016-03-02 12:22
same issue here. No faded map drop at the skull cave as of 12pm gmt.

**Comment by WizKid101** [comment] 2016-03-02 19:32
now that i read all of this stuff im gonna take down my post

**Comment by DikkeHenk1989** [comment] 2016-03-03 10:56
What is the status of all this? Any progress?

**Comment by Odnod** [comment] 2016-03-03 18:55
@DikkeHenk1989 nothing yet, I will probably do another mass response once it is fixed again.

**Comment by McSeed** [comment] 2016-03-03 19:00
Nada. Me to. The problem is still persistent.

**Comment by TimThePvpMaster** [comment] 2016-03-03 20:40
@Trixter313 @trickstini @DarkDemonDragon @Odnod  Guess what I found.

Secret of Aldorei part 1, Purple & Blue, And The ultiment Weapon quests DO NOT drop their stinkin items as supposed to. I am trying to hard to rankup, but that bug is keeping me from around 3-4 quests I should have down by now! I am level 78 archer, and my quests (those 3) are levels super lower... Please fix, this, I am so tired of grinding temple of legends.

**Comment by DarkDemonDragon** [comment] 2016-03-03 21:29
Unfortunately there is nothing we can do other than hope that the admins are on it.

**Comment by DikkeHenk1989** [comment] 2016-03-04 07:41
@DarkDemonDragon We dont hear anything at all, thats the sad part.

**Comment by RockyPlayzMC** [comment] 2016-03-04 09:16
Items did spawn and now they don't this is a wierd  bug like they fixed it but then they stopped spawning when the server crashed that's pretty much what happened. When this bug appeared that was when the server crashed and then the administration fixed most of the quests, (beneath the depths) for example but then the server crashed again and they stopped spawning. You probally already know this but I'm just putting it out there.

**Comment by Troll2828** [comment] 2016-03-04 20:28
Um is this bug fixed or not because light dust isn't spawning and I need it for ToL

**Comment by natourod1** [comment] 2016-03-04 20:32
yes me too

**Comment by mdragonwhite** [comment] 2016-03-04 20:34
me 2

**Comment by destroyerdj135** [comment] 2016-03-04 21:05
10 days this glitch has gone on and no fix and wynncraft expects me to spend more money on there perks.....

**Comment by Troll2828** [comment] 2016-03-04 21:21
I have done other quests where you need to pick up drops and they worked but this one desn't

**Comment by BasicallyNothing** [comment] 2016-03-04 21:27
It's not any reason to post this bug again. It's been reporting over 70 times already and it's being worked on after all. Instead of complaining, just be thankful that they are doing something about the bug that everyone is annoyed of.

**Comment by DarkDemonDragon** [comment] 2016-03-05 02:55
@BasicallyNothing not sure if you are aware but this was originally posted TEN days ago and was the 1st report.

**Comment by Jamieverse** [comment] 2016-03-05 06:02
Still waiting........... I need to finish Tol...

**Comment by BroBroSkope** [comment] 2016-03-05 08:50
I need the light dust!!!! can you give me it?

**Comment by pRizeD** [comment] 2016-03-05 19:25
I mean, one way they can make this so much simpler is make it a mob that drops said item... then this problem will never happen.

**Comment by TrashcanMan** [comment] 2016-03-05 23:32
Guys, calm the hell down. This is going to get fixed soon, I'm sure the developers are working hard on it. Asking when it's going to be fixed and complaining that you can't do the quests won't make them work any faster. Just be patient, do some grinding or whatever in the meantime.

**Comment by TimThePvpMaster** [comment] 2016-03-05 23:47
I took some initiative and ranked my guild up a bit... But seriously, just make the items freeckin lvl 0 mobs wynn! Thanks!

**Comment by mrmalteser** [comment] 2016-03-06 00:58
guys its down to the server hosts not wyncraft itself  so god knows how long this is going to take to get fixed i cant do 4 quests because of this but we will have to wait and see how long it takes

**Comment by baconLovertoo** [comment] 2016-03-06 02:37
I made a account for this specific reason, and i'm just hoping it get fixed in a couple days because I need to finish 3 quests

**Comment by 9XxDar-xX9** [comment] 2016-03-06 02:43
Yeah, Apparently this is happening everywhere... I too was screwed over by this glitch.

**Comment by baconLovertoo** [comment] 2016-03-06 02:48
What I did was just skip the quest and go to a different one

**Comment by TheCatArchy** [comment] 2016-03-06 02:57
Yeah, I'm experiencing this right now also. I'm at the crystal room for WynnExcavation Site C and none of the orange shards are spawning.

**Comment by Deraklich** [comment] 2016-03-06 21:59
That's crazy, developpers are stuck on this bug like 12 days now ... Please do something ! We are waiting for your help !! :)

**Comment by Frostwulfe** [comment] 2016-03-06 22:00
I agree with you Dera

**Comment by halo33** [comment] 2016-03-07 03:03
Its quite pathetic that they can't fix the bug. I mean simply make a mob to spawn and drop the item instead of just having items drop on the ground. Like they have done with the mushrooms/clocks/keys. Now I respect that they might be busy, but its been nearly 2 weeks and its still here.

**Comment by Endeh** [comment] 2016-03-07 03:49
It's been 2 weeks, I still can't finish Wynn Excavation site C! It's the only quest I can do and I'd rather not grind!

**Comment by DarkDemonDragon** [comment] 2016-03-07 13:20
This has been said to have been fixed. Someone confirm this.

**Comment by Moe-Ronickah** [comment] 2016-03-07 14:10
I would really like to get confirmation that this was fixed.  This wave of issues is/was a server host problem, with the host dropping packets.  It had nothing to do with WynnCraft's mechanics, or code.

**Comment by RelativeThinking** [comment] 2016-03-07 14:21
can confirm that the issue is now fixed for the faded map, unsure about others but most likely.

**Comment by Odnod** [comment] 2016-03-07 14:51
Alright it seems that this bug has been fixed again.

**Comment by Trixter313** [comment] 2016-03-07 16:41
Good to hear! Cross your fingers this doesn't happen again...!

**Closed by Trixter313** 2016-03-07 16:41 UTC
Labels: Game Mechanics

**Comment by Odnod** [comment] 2016-03-07 19:00
Going to tag all of the people who have commented once more. @Endeh @halo33 @Frostwulfe @Deraklich @TheCatArchy @baconLovertoo @9XxDar-xX9 @mrmalteser @TimThePvpMaster @pRizeD @BroBroSkope @Jamieverse @Troll2828 @destroyerdj135 @mdragonwhite @natourod1 @RockyPlayzMC @DikkeHenk1989 @McSeed @WizKid101 @atsku8788 @WizKid101 @lemonpillow207 @kmo900 @EJCrusher @Sonicmaster418 @duclong889 Hope you all can finish your quests!

**Comment by Deraklich** [comment] 2016-03-07 20:17
Thank you !! :D

**Comment by TimThePvpMaster** [comment] 2016-03-09 15:12
Oh my goodness thank you!!! I ranked up over those 3 quests and now I am taking on the Qira hive at level 80! And I just soloed the fire division.... Anyone wanna help with Qira???

**Comment by Odnod** [comment] 2016-04-04 02:33
The bug is back as of the most recent update, hopefully it will be fixed soon. Please reopen this for the time being @Moe-Ronickah @Trixter313 @trickstini

**Comment by Odnod** [comment] 2016-04-04 05:17
And never mind, as it is fixed once more.
