### ISSUE TITLE
Stuck in a broken lobby

### ISSUE THREAD

**Issue by Astralgames** [Wynncraft/Issues#5127] opened 2016-06-02 18:07 UTC
Some other people and I are stuck in a broken lobby where we can't join any lobbies or servers. There was a person there saying he has been there for days and it hasn't been resolved. We can't do any commands like /server and stuff like that to get out of there. Were stuck there. We just want to play wynncraft :(

**Comment by Odnod** [comment] 2016-06-02 18:25
This is the Fallback server, and some people have been able to get out in the past by changing the ip to play.wynncraft.net or play.wynncraft.org

Try this, and if it doesn't work try playing on another server for a while. If that doesn't work I don't know if there is any way.

**Comment by AtlessGrimm** [comment] 2016-06-02 22:29
it still didn't work for my friend and he even deleted minecraft and downloaded it again still in a backup lobby so what do we do

**Comment by Moe-Ronickah** [comment] 2016-06-03 07:53
This is my "cut and paste" answer.  I'm sorry, but until this is fixed on the server, it's all that I've got.

If play.wynncraft.com isn't working for you, then try play.wynncraft.net and play.wynncraft.org.They are exactly the same server, but, for some reason, they seem to be handled differently by the main server.  It's also possible that while one isn't working NOW, it will work in 5 min.  If you are still having trouble, shut down Minecraft, wait 5 min., then try again. Sometimes, it takes 2 or 3 tries to get in, sometimes more, but you will get in.

**Comment by Moe-Ronickah** [comment] 2016-06-03 15:10
duplicate of #5012

**Closed by Moe-Ronickah** 2016-06-03 15:10 UTC
Labels: Duplicate
