### ISSUE TITLE
0 stats at lvl 52

### ISSUE THREAD

**Issue by HazelThyme** [Wynncraft/Issues#4241] opened 2016-02-24 03:35 UTC
I was walking around in troms then it randomly tried to download terrain, which failed and resulted in a time out. That was fine, but when I relogged I found out that all my stats are now set to 0 and gears no longer give me stats. This caused some of my gear to pop off and become deleted.

Images
![2016-02-23_22 34 28](https://cloud.githubusercontent.com/assets/17444170/13274954/b8d06360-da7d-11e5-9b9c-0e6dc5e4ac52.png)
![2016-02-23_22 34 38](https://cloud.githubusercontent.com/assets/17444170/13274955/b8d135e2-da7d-11e5-9d97-478f85b5ecb6.png)

**Comment by Crazyj704** [comment] 2016-02-24 03:47
It happens to me as well. Don't worry. Just rejoin.

**Comment by Odnod** [comment] 2016-02-24 06:11
yeah just type /class or rejoin and the issue should fix itself. If this issue has been solved, you should close it.

**Comment by HazelThyme** [comment] 2016-02-24 07:31
okay but items are still lost... anyway to recover those?

**Comment by DarkDemonDragon** [comment] 2016-02-24 13:28
Duplicate of #4120 Please close this and follow the original. Also this was just recently fixed by Salted. On the forums: https://forums.wynncraft.com/threads/this-bug-needs-to-be-aknowledged.113507/
Unfortuantely this issue was fixed 5 hours ago, but your issue happened 10 hours ago :/ I'm sorry that this happened to you. As for your items you can attempt to apply to get your items back, but Wynncraft has a strick no-refunds policy.

**Closed** 2016-02-25 01:40 UTC
