### ISSUE TITLE
[Map Design] Found a hole up in the mountains (Screenshots provided)

### ISSUE THREAD

**Issue by DarkDemonDragon** [Wynncraft/Issues#2538] opened 2015-11-21 16:02 UTC
So I found a hole that fortunately didn't end up going into the void but does drop down into an inescapable crevice (which is actually kinda realistic in as snowy mountains do have crevices but I think this was unintentional). I was on my archer so I did a bit of parkour with my escape and got out, but other classes would probably be out of luck and have to /kill or use a scroll.
![2015-11-21_09 11 45](https://cloud.githubusercontent.com/assets/15721340/11319278/48ab8c0a-903f-11e5-981a-edf80723a44d.png)
![2015-11-21_09 11 47](https://cloud.githubusercontent.com/assets/15721340/11319281/48adf6b6-903f-11e5-96bc-2fda02c86617.png)
![2015-11-21_09 12 03](https://cloud.githubusercontent.com/assets/15721340/11319279/48ac5482-903f-11e5-8082-4dc79dfa7b63.png)
![2015-11-21_09 12 23](https://cloud.githubusercontent.com/assets/15721340/11319276/48ab2558-903f-11e5-93b8-033fae82076b.png)
![2015-11-21_09 12 32](https://cloud.githubusercontent.com/assets/15721340/11319277/48ab43f8-903f-11e5-88f7-a1af50514dc0.png)
![2015-11-21_09 12 40](https://cloud.githubusercontent.com/assets/15721340/11319280/48add190-903f-11e5-8bdd-02f9bc895029.png)
![2015-11-21_09 12 57](https://cloud.githubusercontent.com/assets/15721340/11319282/48b3212c-903f-11e5-847e-2155f3877bae.png)

**Comment by Moe-Ronickah** [comment] 2015-11-22 02:46
I have confirmed this.  I'm surprised that it hasn't been noticed already.

**Comment by arneturuc** [comment] 2015-11-23 22:06
Someone reported this one already in #2433, this thread has better screenshots though.

**Comment by DarkDemonDragon** [comment] 2015-11-24 03:33
@arneturuc yea I noticed it yesterday while searching around, but it never got any staff response.

**Comment by Trixter313** [comment] 2015-12-22 18:58
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by DarkDemonDragon** [comment] 2015-12-22 22:43
Yes, I checked this after the update and it's still there.

**Comment by Trixter313** [comment] 2015-12-23 04:04
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.

**Closed** 2015-12-25 20:38 UTC

**Comment by DarkDemonDragon** [comment] 2015-12-25 21:31
@Tama63 I realize that you've done a mass close because the issues were piling up, but please revisit this as this issue still persists. Post-Gavel evidence has been provided recently too, so please look into this.

**Comment by Sage33** [comment] 2015-12-30 00:06
Resolved!

**Comment by Trixter313** [comment] 2015-12-30 02:33
Awesome! Thanks Sage33 =)

**Comment by DarkDemonDragon** [comment] 2015-12-30 15:40
@Sage33 is the best! :smile:
