### ISSUE TITLE
Can't Leave Guild

### ISSUE THREAD

**Issue by DarraghWynn** [Wynncraft/Issues#8761] opened 2017-08-13 09:19 UTC
Okay so I'm currently in a guild where I'm the only active member so I was going to leave. I answered "yes" to confirm leaving the guild, it takes my three souls points, and yet I'm still in the guild. I've tried to leave three times now so I'm guessing I just need to be manually removed.

**Comment by thecoolkogut4** [comment] 2017-08-13 13:48
Duplicate of #3665

**Closed** 2017-08-18 05:59 UTC
