### ISSUE TITLE
#HELP# my weapon not using ,broken #HELP#

### ISSUE THREAD

**Issue by how8570** [Wynncraft/Issues#3627] opened 2016-01-10 11:50 UTC
![2016-01-10_19 43 54](https://cloud.githubusercontent.com/assets/16633155/12221362/fa31e50e-b7d2-11e5-9183-bc0d431f69a2.png)

help me
game id:how8570
PS: l live in East Asia so maybe have Time difference (UTC+8:00)

**Comment by Trixter313** [comment] 2016-01-10 15:53
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please read this thread fully and try all of the suggestions there. They may help! Alss, please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-10 15:53 UTC
