### ISSUE TITLE
Headless Hunt glitch still happening.

### ISSUE THREAD

**Issue by Venemian** [Wynncraft/Issues#7128] opened 2017-01-07 19:23 UTC
So, I've made this issue before and I sent a recording of it through Github and the response I got never fixed it.

I'm just getting back into Wynncraft trying to **_destroy the lost spirits to free them_** but even after dying. and doing /kill and going back into the place under durhans mansion or whatever, I kill the lost souls, pick up the white powder drop, and a sound plays. But there are no messeges or dialogue in the chat box, and no visual of a door opening or closing, and I get stuck in the room. I have to die or kill myself to respawn in the nearby town but I can't progress past that point.

https://www.youtube.com/watch?v=AfUQu-KZD80

**Comment by LordHelmchen98** [comment] 2017-01-08 13:06
Duplicate of #6819 
In your previous thread about this I told you that there is no chat message that is supposed to pop up once you defeated the Lost Spirits. On one side of the guillotine where you are standing on, there are coal blocks. You will get teleported if you are walk into that 'portal'.

**Comment by Venemian** [comment] 2017-01-08 14:44
Ok, I finally found it! It was almost invisible to me sorry =/

**Closed** 2017-01-19 06:11 UTC
Labels: Duplicate
