### ISSUE TITLE
Spider cave

### ISSUE THREAD

**Issue by Amminate** [Wynncraft/Issues#4383] opened 2016-03-01 16:23 UTC
No Saccharum!

**Comment by Trixter313** [comment] 2016-03-01 17:45
Have you tried switching to another world? It might just be a temporary issue on one world.

**Comment by kmo900** [comment] 2016-03-02 02:25
NO this is happening several drops quests i saw it in the spider cave and also in the suspended flowers. reading thrugh the issues i think it is the same problem with the diamond shards

**Comment by Odnod** [comment] 2016-03-02 06:50
Duplicate of #4236, please close this issue and put any additional comments on the original. Thanks!

Please know that this bug is very well known and is being worked on.

**Closed** 2016-03-02 07:49 UTC
Labels: Duplicate
