### ISSUE TITLE
The Animal Dungeon Boss glitches very often

### ISSUE THREAD

**Issue by xxxblackspider** [Wynncraft/Issues#4842] opened 2016-04-17 06:07 UTC
There was another ticket submitted about this issue 21 days ago, but I am posting this one because the dungeon is almost not playable. I did the dungeon 4 times with a group tonight and 3 out of the four times the boss glitched out of the containing area and we were unable to kill him. It happened when our warrior shouted him out and when our archer used arrow storm.

**Comment by Trixter313** [comment] 2016-04-17 13:11
Duplicate of https://github.com/Wynncraft/Issues/issues/3191

The issue had been marked as fixed, so I'm assuming it will be fixed when they send out the next map update. Once I know that for sure or know what else is happening, I'll update you on that issue. Thanks!

**Closed by Trixter313** 2016-04-17 13:11 UTC
