### ISSUE TITLE
Can't Leave Guild

### ISSUE THREAD

**Issue by tomisdaman27** [Wynncraft/Issues#5676] opened 2016-08-07 08:41 UTC
BUG: Stuck in my guild as the leader, cannot pass on leadership to others in order to leave. /guild leave takes my 3 soul points but keeps me in Guild. Guild name; Fishers of Wynn. Please disband the guild, thank you. Also, some names in the guild show up twice.

**Comment by Moe-Ronickah** [comment] 2016-08-07 13:05
Duplicate of #3665 .  Please read and follow that issue for more information.

**Closed by Moe-Ronickah** 2016-08-07 13:05 UTC
Labels: Duplicate

**Comment by tomisdaman27** [comment] 2016-08-10 10:25
3665 is unsolved, my report is unsolved and still awaiting an email from support. I just need my guild disbanded.

**Comment by Moe-Ronickah** [comment] 2016-08-11 04:36
Yes, we know that guilds are still broken.  Read #3665.  All of it.
