### ISSUE TITLE
Wand is glitched and can't use

### ISSUE THREAD

**Issue by CelestialStorm25** [Wynncraft/Issues#3209] opened 2015-12-26 22:23 UTC
My wand was working a couple minutes ago and now it turned into this (refer to picture below). Tried relogging to many servers but no luck. I now do not have a wand that I can use (I have higher leveled wands)

![2015-12-26_14 21 44](https://cloud.githubusercontent.com/assets/15953108/12008129/02236146-abdc-11e5-9afc-fd33631aff35.png)

**Comment by Verret001** [comment] 2015-12-26 22:28
duplicate of https://github.com/Wynncraft/Issues/issues/3175

**Closed** 2015-12-26 22:31 UTC
