### ISSUE TITLE
Shop Prices not Displaying

### ISSUE THREAD

**Issue by NinjaPiggy** [Wynncraft/Issues#6586] opened 2016-11-05 12:55 UTC
The amount of emeralds that items cost is not displaying in the shop window.
The items still cost their normal amount, just that the prices are invisible.
![2016-11-05_08 49 16](https://cloud.githubusercontent.com/assets/17673269/20030145/855d71ae-a335-11e6-8a9b-f74ecad0e257.png)
![2016-11-05_08 50 08](https://cloud.githubusercontent.com/assets/17673269/20030146/868a25e0-a335-11e6-9d64-600831432fbf.png)
![2016-11-05_08 50 10](https://cloud.githubusercontent.com/assets/17673269/20030147/886d73b2-a335-11e6-93b5-b98df15f1dc1.png)
![2016-11-05_08 50 51](https://cloud.githubusercontent.com/assets/17673269/20030148/8a8f0408-a335-11e6-9708-93f494f17eb0.png)

**Comment by LordHelmchen98** [comment] 2016-11-05 13:04
Duplicate of #6575

**Comment by ggroggs** [comment] 2016-11-05 13:54
Came here to report the same issue.

It's not just prices in emeralds (though I see that too): I just did a dungeon for the first time and was unable to see any of the boss token / shard prices in the custom dungeon shop either, and the Selchar treasure merchant doesn't show what it's buying for any of the many choices there.

**Closed** 2016-11-05 18:50 UTC
