### ISSUE TITLE
Items gone

### ISSUE THREAD

**Issue by CorvetteLegend** [Wynncraft/Issues#4817] opened 2016-04-13 01:25 UTC
I logged off a few nights ago got on yesterday all my stuff is gone and my skin is Alex on the worlds except for the hub but i know i was not hacked is my stuff just not loading? or something else all i have in my inventory is a oak wood stick

**Comment by CorvetteLegend** [comment] 2016-04-13 01:30
or could it be i died a few times?

**Comment by IArePolar** [comment] 2016-04-13 01:59
This has happened to multiple people including me. They told me I could have been hacked but I know for sure it didn't happen. I posted the same problem. Multiple people are having this problem and i think it might be a server problem

**Comment by YunoFGasai** [comment] 2016-05-13 11:46
this is a duplicate of #4814 please refer any and all comments to the original thread

**Closed** 2016-05-21 00:56 UTC
Labels: Duplicate
