### ISSUE TITLE
I CANT USE MY ARCHER CLASS

### ISSUE THREAD

**Issue by chicagogrand** [Wynncraft/Issues#3580] opened 2016-01-07 03:28 UTC
everytime i try to use my lvl 60 archer class it sais error try again but no matter how many times i retry it never works..
![2016-01-06_18 44 54](https://cloud.githubusercontent.com/assets/16586336/12161539/087dda5e-b4b4-11e5-9572-f567b7daafba.png)

**Comment by Trixter313** [comment] 2016-01-07 07:23
Duplicate of https://github.com/Wynncraft/Issues/issues/3139

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-07 07:23 UTC
