### ISSUE TITLE
Cannot Open Doors, Chests, Or Fences, Or Push Buttons

### ISSUE THREAD

**Issue by Lightwavers** [Wynncraft/Issues#8209] opened 2017-05-23 03:57 UTC
I am reporting this because it is very difficult to play without being able to do these things. It is also impossible to go the the dungeon boss room or go to the sewers. I was able to do these things last night, but now I can't. Please help.

**Comment by ittnoraA** [comment] 2017-05-23 05:09
Try doing all of those things while not holding your weapon

**Comment by Lightwavers** [comment] 2017-05-23 07:31
Thanks, it works! I still think this is an issue though.

**Comment by Trixter313** [comment] 2017-05-23 11:00
Duplicate of https://github.com/Wynncraft/Issues/issues/8113 and many others.

**Closed by Trixter313** 2017-05-23 11:00 UTC
