### ISSUE TITLE
My player was stuck

### ISSUE THREAD

**Issue by Chrissdroid** [Wynncraft/Issues#8528] opened 2017-07-05 17:47 UTC
hi my Chrissdroid, my main classe (Mage) was stuck in a block, i cannot use scroll teleportations, and i see anything

![2017-07-05_19 47 23](https://user-images.githubusercontent.com/29927270/27877410-c94bd54c-61ba-11e7-8c13-1f52300ebc58.png)

![2017-07-05_19 44 50](https://user-images.githubusercontent.com/29927270/27877344-89620abe-61ba-11e7-982b-f266a17df8cf.png)

pls unstuck me ;-;

**Comment by PepinhoJp** [comment] 2017-07-05 20:19
Duplicate of #88
Please check for duplicates before posting a bug report.

To leave the area, /kill with +6 soul points or use a teleport scroll, mods don't teleport people out.

**Comment by colin350** [comment] 2017-07-07 13:24
[Example duplicate search](https://github.com/Wynncraft/Issues/issues?q=stuck+in+block+is%3Aclosed)

**Closed by colin350** 2017-07-07 13:24 UTC
