### ISSUE TITLE
Animal Dungeon boss stuck

### ISSUE THREAD

**Issue by luuko** [Wynncraft/Issues#3374] opened 2015-12-30 23:02 UTC
The animal boss is tuck behind a invisble wall we cannot leave or do anything.
![2015-12-30_23 59 27](https://cloud.githubusercontent.com/assets/4983434/12058892/ac919b20-af51-11e5-8f17-d71c6d681441.png)

**Comment by Trixter313** [comment] 2015-12-30 23:41
Duplicate of https://github.com/Wynncraft/Issues/issues/3191

Please direct any further comments to the original thread. Thanks!

**Closed by Trixter313** 2015-12-30 23:41 UTC
