### ISSUE TITLE
What???

### ISSUE THREAD

**Issue by KawaiiCrafter7** [Wynncraft/Issues#4970] opened 2016-05-10 15:12 UTC
I just turned lvl 60 and I got a new quest! So I came to the Pirate island and there are no NPCs here only villagers

**Comment by YunoFGasai** [comment] 2016-05-10 15:14
did you check the cords given in the book?

**Comment by KawaiiCrafter7** [comment] 2016-05-10 17:51
yes and it said Pirate island

**Comment by KawaiiCrafter7** [comment] 2016-05-10 17:51
and there were no NPCs

**Comment by KawaiiCrafter7** [comment] 2016-05-10 17:55
No bank,indentifier...

**Comment by thecoolkogut4** [comment] 2016-05-10 19:01
try to switch servers? are you sure your at the right Y cord?

**Comment by Trixter313** [comment] 2016-05-10 19:28
Duplicate of https://github.com/Wynncraft/Issues/issues/3272

Please direct any future comments to the original thread and read it all. Thanks!

**Closed by Trixter313** 2016-05-10 19:28 UTC
