### ISSUE TITLE
broken weapon (fierté)

### ISSUE THREAD

**Issue by stangefall** [Wynncraft/Issues#3640] opened 2016-01-10 19:40 UTC
when i logged in my spear got gliched and i tried in diferents servers and still the same
![2016-01-10_17 40 16](https://cloud.githubusercontent.com/assets/16395360/12223517/2770b156-b7c1-11e5-9614-c319bcceb7ea.png)

![2016-01-10_17 38 08](https://cloud.githubusercontent.com/assets/16395360/12223516/11aa535e-b7c1-11e5-965a-be1ea0c56e6a.png)

**Comment by CHENS85** [comment] 2016-01-10 19:43
can i have a awesome weapon like u

**Comment by stangefall** [comment] 2016-01-10 20:06
am i cused or something? (it was a rare undentified chesplate until server restart)
![2016-01-10_18 05 55](https://cloud.githubusercontent.com/assets/16395360/12223676/c2d38b84-b7c4-11e5-81f7-59ea51e5b156.png)

**Comment by oij92** [comment] 2016-01-10 20:58
I've the same problem with my fierté and with my pélier
![screen shot 01-10-16 at 09 54 pm](https://cloud.githubusercontent.com/assets/16638109/12223944/3c6d3b14-b7e5-11e5-8be7-b65f0d6fef58.PNG)
![screen shot 01-10-16 at 09 55 pm](https://cloud.githubusercontent.com/assets/16638109/12223943/3c6a6f6a-b7e5-11e5-806f-40f6623b3817.PNG)

**Comment by Trixter313** [comment] 2016-01-10 22:36
Duplicate of https://github.com/Wynncraft/Issues/issues/3175

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-10 22:36 UTC
