### ISSUE TITLE
Adamatite bug?

### ISSUE THREAD

**Issue by FwapaDurp** [Wynncraft/Issues#5550] opened 2016-07-22 13:54 UTC
Level 70 legendary chest plate Adamatite removes an absurd amount of elemental defence.
![2016-07-22_09 53 22](https://cloud.githubusercontent.com/assets/16434132/17059218/301c4f62-4ff2-11e6-8fb6-2754976be7b9.png)
![2016-07-22_09 53 07](https://cloud.githubusercontent.com/assets/16434132/17059219/301e2dc8-4ff2-11e6-8b5f-9c58b33f0cef.png)

**Comment by sammyvsparks** [comment] 2016-07-22 13:59
Those are the stats described by the api. The compass is known to be wrong and may be numbering Your stats wrong.

**Comment by Moe-Ronickah** [comment] 2016-07-22 20:08
Duplicate of #3179

**Closed by Moe-Ronickah** 2016-07-22 20:08 UTC
