### ISSUE TITLE
Harpoon (Bow Weapon) has a few, non-critical issues

### ISSUE THREAD

**Issue by CrashTC** [Wynncraft/Issues#4625] opened 2016-03-22 04:26 UTC
The Harpoon weapon has no custom texture (it is literally a slab), and when the user right-clicks on the ground, the chat will pop up "You don't have permission for this area." While neither issue prevents the user from using the "bow" as a weapon, this can get annoying, as evidenced in one screenshot attached here.
![2016-03-21_21 24 36](https://cloud.githubusercontent.com/assets/10406383/13942058/88ace4b8-efab-11e5-83c2-9f2b6da383be.png)
![2016-03-21_21 23 32](https://cloud.githubusercontent.com/assets/10406383/13942060/8b1947d2-efab-11e5-8b9f-f2bf9f59c2cf.png)

**Comment by Moe-Ronickah** [comment] 2016-03-22 05:45
Is this still happening even after you've logged out and back in?

**Comment by CrashTC** [comment] 2016-03-22 14:23
Yes, it has been happening consistently over the past few weeks (the duration I've had the weapon).

**Comment by CrashTC** [comment] 2016-03-26 21:13
The issue still persists and is still the exact same. Should I open another issue, or could you reopen this issue?

**Comment by Trixter313** [comment] 2016-03-27 01:23
Actually, this is a duplicate of https://github.com/Wynncraft/Issues/issues/4548

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-27 01:23 UTC
