### ISSUE TITLE
Suspended Flower Quest Problem

### ISSUE THREAD

**Issue by FryBai** [Wynncraft/Issues#4251] opened 2016-02-24 18:02 UTC
I've been waiting in the cave where the Aerolia flower was supposed to spawn and it didn't. Is this a bug? Glitch? I don't know but please can this bug/glitch be fixed as soon as possible. Ty

**Comment by Odnod** [comment] 2016-02-24 18:13
Duplicate of #4236, please close this thread and put any additional comments on the original.

**Closed** 2016-02-24 18:16 UTC
