### ISSUE TITLE
Guild Glitch!

### ISSUE THREAD

**Issue by AlexomonHD** [Wynncraft/Issues#6752] opened 2016-11-22 20:44 UTC
Help I cant leave our old Guild cause I changed my name when I was in it, I tried much things but nothing work. Our old Guild ,,TheDarkEmerald,, was creaded by my friend templiner but now it is glitched and no one is the Owner so we created a new and now I cant join so I would ask you to delete our old Guild ,,TheDarkEmerald,, pls.

Thx. Alexomon/AlexomonHD

**Comment by LordHelmchen98** [comment] 2016-11-22 21:28
Duplicate of #3665
Guilds are very glitched and glitches caused by namechanges are very common. Unfortunately there is no fix for this until guilds get fixed by staff which will hopefully happen in the next update.

**Comment by thecoolkogut4** [comment] 2016-11-22 22:55
staff will not delete the guild, remove you from the guild, or add you to another guild for the time being. lots of people are in the same boat as you.

**Closed** 2016-11-24 03:33 UTC
