### ISSUE TITLE
Cant leave guild

### ISSUE THREAD

**Issue by xSebo** [Wynncraft/Issues#6755] opened 2016-11-22 23:33 UTC
Right, I recently got back into wynncraft and realised none of my guild members are online. I know there's an issue where if you change usernames you can't join a guild but my problem is that I'm apparently not even in my guild, and there are people in my guild that ware in it twice. When I say I'm not in it, I mean in any of my previous usernames either. Help!

**Comment by thecoolkogut4** [comment] 2016-11-23 00:01
if you change your usernames, you can join a guild actually. if you change it you won't be able to leave or get your rank changed.
this happened to many other players where they changed their name and it says they aren't even in a guild but they are.

**Comment by ColinRioux** [comment] 2016-11-24 03:30
Duplicate of #3665

**Closed by ColinRioux** 2016-11-24 03:30 UTC
