### ISSUE TITLE
Diamond chestplate for level 64 issue

### ISSUE THREAD

**Issue by Loul60** [Wynncraft/Issues#4372] opened 2016-03-01 06:54 UTC
Ok so my ingame name is Loul.
In july 2015 I loot à diamond chestplate called dravarden. It was identified with the ancient method and when I reconnect 8 months later, in february 2016, I had to identify an other time all my items except this chestplate what is already identified with the ancient method, we can see It gives 65 defense and not HP, etc.
And I tried something, what is useless but this item can be used with lv 2 People. Please fix it and give me an other chestplate rare for level 64 or fix this one :) If you want to look thé item,

**Comment by Loul60** [comment] 2016-03-01 06:55
If you want to look the item, my in game name is Loul, it is in the bank.

**Comment by DarkDemonDragon** [comment] 2016-03-01 13:04
I'm sorry to inform you that your item may probably never be fixed. The only suggestion I have to fix it is to hold the item in your hand, click on a Emerald Villager (The NPCs at a bank), wait a second, and then exit out of the GUI. This has a chance of reverting broken items. If this doesn't work then there isn't much to be done. I recommend simply getting a new chestplate as Dravarden isn't too expensive. 

Also, Wynncraft has a strict no-refunds policy.

**Comment by Trixter313** [comment] 2016-03-01 18:23
Duplicate of https://github.com/Wynncraft/Issues/issues/3161

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-01 18:23 UTC
