### ISSUE TITLE
Typo: Drought Sand

### ISSUE THREAD

**Issue by alexdavid4** [Wynncraft/Issues#4995] opened 2016-05-15 00:35 UTC
Here it is:
1. Start the Quest
2. Talk to Irt
4. Talk to Irt again without the required amount
5. It says "24 Water Bottles"
I am sure someone would be fooled if they believe if he/she needs 24 water bottles

Evidence: http://imgur.com/wdtkq6j

**Comment by YunoFGasai** [comment] 2016-05-15 11:26
duplicate of #38 please refer all comments to the original thread.

**Closed** 2016-05-20 20:19 UTC
Labels: Duplicate
