### ISSUE TITLE
I Have Probleme with quest

### ISSUE THREAD

**Issue by ZoRo01** [Wynncraft/Issues#7151] opened 2017-01-11 20:44 UTC
Quest : WynnExcavation Site A
^
The quest theTranslation Paper i have lost 

i hope you can help me with this probleme

**Comment by DohdoEXE** [comment] 2017-01-12 02:44
Please only leave issues if the problem is new. To find out, you can do this: site:github.com/Wynncraft/Issues/issues/ [Insert Issue Here]

If nothing pops up, you're free to upload an issue

**Comment by ZoRo01** [comment] 2017-01-12 10:02
if i do /fixquests 

it the same nothing hanppning

**Comment by DebugMC** [comment] 2017-01-13 13:43
Dupe of (Insert number here later I forgot)

**Comment by JeffTheNub** [comment] 2017-01-16 15:12
/fixquest is a little bit glitchy now, so... maybe try it later?

**Closed** 2017-01-21 01:00 UTC
Labels: Duplicate
