### ISSUE TITLE
Floating Chest

### ISSUE THREAD

**Issue by RikioPT** [Wynncraft/Issues#7586] opened 2017-03-26 02:43 UTC
![2017-03-25_16 39 40](https://cloud.githubusercontent.com/assets/17153769/24327998/1462d97c-117a-11e7-962f-65cf0e10f8e3.png)
May have been left there from Wynnter Fair.

**Comment by LordHelmchen98** [comment] 2017-03-28 14:40
I told someone about this. Should be fixed with the next map push.

**Comment by DebugMC** [comment] 2017-04-08 03:33
Duplicate of #7154 #7441

**Comment by LordHelmchen98** [comment] 2017-04-08 08:10
I'm pretty sure it should be fixed, because Corkus is released now and the map was updated.

**Closed by LordHelmchen98** 2017-04-08 08:10 UTC
