### ISSUE TITLE
Pet Riding Glitch

### ISSUE THREAD

**Issue by ThePyromaniac** [Wynncraft/Issues#5794] opened 2016-08-21 14:33 UTC
Alright, well, it's only for the silverfish,  the VIP+ pet, whenever you repeateadly spawn your horse whilst looking at the silvrfish pet, it spawns a normal-normal horse.
Then when you're riding that normal horse, if you right click with your horse saddle, it changes the color of the horse you're riding. 

When that glitch has been "Activated" whenever you right click with a weapon, it spawns a normal horse. The only way to "De-activate" the glitch, is to despawn your pet. 

I've made a video clip explaining how to do so. http://tinypic.com/r/2uh49eh/9

**Comment by Trixter313** [comment] 2016-08-21 14:45
Duplicate of https://github.com/Wynncraft/Issues/issues/2860

**Closed by Trixter313** 2016-08-21 14:45 UTC
