### ISSUE TITLE
[Quest] WynnExcavation Site A quest not working

### ISSUE THREAD

**Issue by Britland** [Wynncraft/Issues#2103] opened 2015-07-15 05:05 UTC
The problem is that the quest tells me that I need to go talk to Vade, but vade tells me to talk to Tesha, and Tesha tells me to talk to Vade. The quest cannot be completed. The only weird thing that happened around when it broke is the server restarted.
![screenshot_145](https://cloud.githubusercontent.com/assets/13344362/8691190/169e7ff8-2a85-11e5-9c90-1f2b3d188261.png)
![screenshot_146](https://cloud.githubusercontent.com/assets/13344362/8691191/16c44a9e-2a85-11e5-9154-c7396a895aaf.png)

**Comment by Trixter313** [comment] 2015-07-15 05:54
Do you have the translated text in your inventory?

**Comment by Britland** [comment] 2015-07-15 09:33
I already turned it in, I do not. And I tried the command for fixing the lost quest item, didn't give it back. (Just fyi it would not let me progress the quest that far unless I already turned in the translated text, that photo of the quest book is after I explored the excavation site.)

**Comment by AssassinGamer13** [comment] 2015-07-29 19:39
Yea also happened to me, It's annoying

**Comment by Trixter313** [comment] 2015-08-09 02:20
Duplicate of https://github.com/Wynncraft/Issues/issues/1415

We recommend closing the duplicate and following the original to stay up to date on the status of the issue. Thanks!

**Closed** 2015-08-17 07:08 UTC
