### ISSUE TITLE
Losing Soul Points From Winning a Duel

### ISSUE THREAD

**Issue by pmatha123** [Wynncraft/Issues#3875] opened 2016-01-27 02:26 UTC
So, this issue happened to me once before but didn't really care much but it happened again and it was quite annoying. What happened was I was having a duel with someone in the centre of cinfras and I won. Under the bit saying that I won it also said:
"You have died"

Here is a screenshot:
![annoy](https://cloud.githubusercontent.com/assets/7629444/12601958/2f0af5c4-c4f1-11e5-8564-07cdee07db83.PNG)

**Comment by Trixter313** [comment] 2016-01-27 02:53
Duplicate of https://github.com/Wynncraft/Issues/issues/3559

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-27 02:53 UTC
