### ISSUE TITLE
Couldn't get into Wynncraft?

### ISSUE THREAD

**Issue by potatopvpmaster** [Wynncraft/Issues#3924] opened 2016-01-30 14:13 UTC
It says "Error occurred while contacting login servers, are they down?" I have tried to join many times and restarted my computer,what do I do?

**Comment by mickymaster24** [comment] 2016-01-30 14:25
They Admins and the owner say to report this if u cant get in for 2 or more days :(

**Comment by potatopvpmaster** [comment] 2016-01-30 14:35
but what do i do right now?

**Comment by mickymaster24** [comment] 2016-01-30 14:44
I guess we just wait :/

**Comment by Trixter313** [comment] 2016-01-30 14:51
Duplicate of https://github.com/Wynncraft/Issues/issues/3917

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-30 14:51 UTC
