### ISSUE TITLE
I cant escape my guild

### ISSUE THREAD

**Issue by Nikick** [Wynncraft/Issues#7402] opened 2017-02-20 07:20 UTC
I cant escape my guild since i changed my guild
so please help me
IGN:Nikick

**Comment by LordHelmchen98** [comment] 2017-02-20 12:56
Duplicate of #3665
Guilds are very glitched and you face this problem because you changed your name while you were in the guild. Unfortunately there is no known fix for this so just like numerous other players you will have to wait until guilds get fixed which will hopefully happen soon.

**Closed** 2017-02-20 16:22 UTC
