### ISSUE TITLE
Wynn excavation site A

### ISSUE THREAD

**Issue by OrdinaryWoulf** [Wynncraft/Issues#5791] opened 2016-08-21 11:51 UTC
In the quest of Wynn excavation site A i cannot enter the tomb when it said so when i go on the diamond block it say ''a strong force is preventing your entry'' when i need to go in tomb

**Comment by Trixter313** [comment] 2016-08-21 14:46
What does it say in your quest book?

**Comment by OrdinaryWoulf** [comment] 2016-08-21 23:46
it say go talk in the guy in the tents but ive already done it and already give the paper to the quest master
and he say .....throw a tribute in corner or something like that  .....

**Comment by Trixter313** [comment] 2016-08-22 00:03
Does the command /fixquests return any items for the quest?

**Comment by OrdinaryWoulf** [comment] 2016-08-25 22:53
no it doesent

**Comment by Trixter313** [comment] 2016-08-27 00:11
Many people seem to get stuck on this part. We don't currently have a fix if /fixquests doesn't work so unfortunately until we can fix it you won't be able to complete the quest.

**Comment by OrdinaryWoulf** [comment] 2016-08-27 12:52
0k so i cant do wynn excavation A B C D i will loose so many exop

**Comment by Moe-Ronickah** [comment] 2016-08-30 20:49
".....throw a tribute in corner or something like that ....."

When you enter the tomb, you will come to a room that has four corner pillars.  One of those pillars is not like the other three.  Pay that pillar a tribute (an emerald), and hatch will open in the center of the room.  Jump in.

**Comment by OrdinaryWoulf** [comment] 2016-08-30 23:28
I know and i done that but when i want to the place where were the diamond block it said a strong force is preventing your entry

**Comment by Moe-Ronickah** [comment] 2016-09-03 06:36
Go watch a tutorial on youtube for the quest just to be certain that you are looking in the right places.  Let us know if this helps.

**Comment by OrdinaryWoulf** [comment] 2016-09-08 23:34
Ive done it
ive done evry single thing dat we need to do and it said ...a strong force is preventing your entry...

**Comment by Moe-Ronickah** [comment] 2016-09-10 22:17
And you've talked to Excavator Vade and Tesha?

**Comment by Trixter313** [comment] 2016-10-21 22:39
Appears to be a duplicate of https://github.com/Wynncraft/Issues/issues/4079

There's currently nothing that the user can do, only an admin will be able to fix it.

Please follow the original thread for updates on the issue. Thanks!

**Closed by Trixter313** 2016-10-21 22:39 UTC
