### ISSUE TITLE
Connecting Problems

### ISSUE THREAD

**Issue by LelliPazi** [Wynncraft/Issues#6750] opened 2016-11-22 18:15 UTC
Since 2 weeks i have Connection Problems and always i get this:
minecraft error could not connect to default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotadedConnectExeption

Can someone help me? I really like the server :(

**Comment by LordHelmchen98** [comment] 2016-11-22 18:17
I assume you are using play.wynncraft.com to join the server. Use .net or .org instead. If that doesnt work start another minecraft version and log in once then disconnect and switch back to your preferred version.

**Comment by thecoolkogut4** [comment] 2016-11-22 18:32
as lord said but connect with Mc version 1.8.8 on play.wynncraft.com and play.wynncraft.com

**Comment by LordHelmchen98** [comment] 2016-11-22 18:56
@thecoolkogut4 `play.wynncraft.com and play.wynncraft.com`
;)

**Comment by ColinRioux** [comment] 2016-11-24 03:33
Duplicate of #6717

**Closed by ColinRioux** 2016-11-24 03:33 UTC
