### ISSUE TITLE
Item Texture Broken-

### ISSUE THREAD

**Issue by jamesjpk123** [Wynncraft/Issues#4631] opened 2016-03-22 18:24 UTC
When I was fighting I got an item called "Kelights Toothbrush". 
**Stats:
Slow Attack Speed
16-21 Neutral Damage
8-9 Thunder Damage
Class Req: Mage/Dark Wizard
lv Min. 17
%6+ XP Bonus
%9+ Loot Bonus
%-5 Earth Damage
%7+ Melee Damage
%-3 Earth Defense 
[0/1 Slots]
Rare Item
NBT: 1 tag(s)**
The problem with it is that in the wynncraft texture pack, it has the texture of minecraft:stone_slab. I hope this helps!

**Comment by DRedDogPE** [comment] 2016-03-22 22:24
Are you using 1.9?

**Comment by zingozman** [comment] 2016-03-24 15:10
I am using 1.9 and i have this problem

**Comment by TrashcanMan** [comment] 2016-03-24 20:53
1.9 is pretty buggy right now, I'd advise you to switch to 1.8.9 until they fix all the bugs.

**Comment by Trixter313** [comment] 2016-03-27 01:23
Duplicate of https://github.com/Wynncraft/Issues/issues/4548

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-27 01:23 UTC
