### ISSUE TITLE
two bugs in the ocean

### ISSUE THREAD

**Issue by Luc4sherobrine9** [Wynncraft/Issues#7453] opened 2017-02-26 14:56 UTC
1:when i enter in my boat it float for a while and go to the deep sea

2:galeon's graveyard dungeon is very gliched
i cant start the boss fight (boatxboat)

**Comment by Pyromanical** [comment] 2017-02-26 18:05
1. Duplicate of #7149.  Use 1.8.9 if you want boats not to sink.  This is because of a patch that fixed boats/horses in 1.9+ in the x and z directions, but not in the y direction.

2.  This is very well known a a duplicate of a lot of issues.  This dungeon is fixed on the build server, and will be on the main server next map push.  The next map push will be Corkus, which is happening soon (hopefully).

**Closed** 2017-02-26 18:31 UTC
