### ISSUE TITLE
Animal Dungeon Boss Problems

### ISSUE THREAD

**Issue by TurretBud** [Wynncraft/Issues#5084] opened 2016-05-25 06:04 UTC
You can push him out of the barriers by repeatedly hitting him (especially with archer, not sure about other classes)
Unable to hit him, he cannot hit you either. 
![](http://img.prntscr.com/img?url=http://i.imgur.com/OFIIDBK.png)
Also, sometimes I'll kill him and he'll respawn again, both issues get really annoying if you're running a lot of dungeons.

**Comment by Trixter313** [comment] 2016-05-25 10:03
Duplicate of https://github.com/Wynncraft/Issues/issues/3191

And the part about respawning is intended. There's a certain chance that the boss will respawn.

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-05-25 10:03 UTC
