### ISSUE TITLE
Double Guild Chat Messages (need help)

### ISSUE THREAD

**Issue by OliverF0103** [Wynncraft/Issues#8084] opened 2017-05-07 07:58 UTC
I understand that this is a duplicate, but in the other two posts, all that has been said is that it will be fixed or there is nothing you can do. Ever since changing my name, im experiencing two messages in chat, I don't want to leave the guild as i am the leader, i even checked on the stats thing for guilds and under owner there are two people, both with my username. Is there anyway to fix this as it is extremely annoying?

**Comment by LordHelmchen98** [comment] 2017-05-07 09:49
Duplicate of #3665
You said you are aware that this is a duplicate so please post on the original thread in future (I appreciate that you searched before unlike many others though).
However there is nothing that can be done for you. The guild code has to get rewritten which will hopefully be done soon but there is no estimated time. If someone changed their name they can't leave the guild by the way. They are stuck and can't leave or get kicked.

**Closed by LordHelmchen98** 2017-05-07 09:49 UTC
