### ISSUE TITLE
Quest: Hidden City Lock "minigame" doesn't work!

### ISSUE THREAD

**Issue by whocaresaboutUsernames** [Wynncraft/Issues#5880] opened 2016-08-29 18:55 UTC
Evidence if needed: https://gyazo.com/9e1b37550962ac62da1516aaef8d2d4e

**Comment by Trixter313** [comment] 2016-08-30 23:07
Duplicate of https://github.com/Wynncraft/Issues/issues/5855

**Closed by Trixter313** 2016-08-30 23:07 UTC
