### ISSUE TITLE
Amadel's Final Form not dropping the item.

### ISSUE THREAD

**Issue by norepinephrine** [Wynncraft/Issues#4058] opened 2016-02-09 22:38 UTC
I have fought Amadel about 4 times with 2 other friends and every time we kill him, he drops 2 items instead of 3. How do I fix this because otherwise there is no way I can do the quest.

**Comment by Trixter313** [comment] 2016-02-09 23:13
It drops one item for each person who did a decent amount of damage so it's most likely that you aren't damaging the boss enough. Compare weapons with the others and see if you notice any differences such as your weapon being mostly elemental and theirs being mostly neutral, etc. Some bosses are damaged more by certain elements than others and you might be using a weak one.

**Comment by DarkDemonDragon** [comment] 2016-02-09 23:17
In order for an enemy to drop an item I think you need to deal roughly 15%+ of the mob's hp in damage. For groups where one part of people attack and other's are defensive and don't attack as much, you'll have to kill the boss multiple times.

- First, kill the boss and have the attack team claim their pendants and cash the pendants in. 
- Next, the attack team fills up their inventory by spreading out items such as emeralds so they don't accidentally pick up an item
- Kill the boss again and this time the attack team backs away and the defensive team moves in for the item. It'll take about 1-2 minutes before the defensive team can pick up the item. 
- Repeat as many times as necessary until everyone has their item.

**Comment by Trixter313** [comment] 2016-02-20 21:15
So has your issue been resolved @norepinephrine ? Thanks!

**Comment by DarkDemonDragon** [comment] 2016-03-10 13:15
@Trixter313 just close this as this is most likely not a bug and just the mechanics of how boss drops work.

**Closed** 2016-03-15 06:10 UTC
