### ISSUE TITLE
Lost Items Fly Kicked

### ISSUE THREAD

**Issue by LemonLordIsSexyAndSilAndBlueKnowIt** [Wynncraft/Issues#5227] opened 2016-06-14 22:30 UTC
I was kicked for flying and when I joined again I didn't have my armor on and I have had this happen before and it goes into my inventory, BUT! This time when I looked into my inventory I saw it was full and I lost the two legendary peices of my armor Neandrathol boots (legendary) and some other legendary gold chest plate. It was a serer error so I was wondering if I could be re funded? Please and thanks, Love LemonLord! :D

**Comment by Trixter313** [comment] 2016-06-15 03:29
Duplicate of https://github.com/Wynncraft/Issues/issues/3153

Please direct any future comments to the original thread. Thanks!

Unfortunately Wynncraft has a strict no refunds policy so there's not much we can do about the already lost items. To try and prevent it from happening again, we suggest making sure you always have adequate disagree on your inventory in case it happens again. We are working to try and fix it so you don't have to worry about it any more.

**Closed by Trixter313** 2016-06-15 03:29 UTC
