### ISSUE TITLE
lost all my skills

### ISSUE THREAD

**Issue by picachuthefirst1** [Wynncraft/Issues#4454] opened 2016-03-05 13:30 UTC
i went on wynncraft to day and i look at me skills it said there were all 0 so i looked at my level and it was still 36 but i can't use and of my weapons now so is this a glitch???

**Comment by Moe-Ronickah** [comment] 2016-03-05 14:06
Try changing classes or reloging on.  Those usually fix the problem.

**Comment by Trixter313** [comment] 2016-03-05 20:30
Duplicate of https://github.com/Wynncraft/Issues/issues/4304

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-05 20:30 UTC
