### ISSUE TITLE
Drops for quests not spawning

### ISSUE THREAD

**Issue by Fenix180** [Wynncraft/Issues#4478] opened 2016-03-06 16:23 UTC
when i try to go in the cave of spiders for some sugarcane it doesnt spawn i had to ask if someoe had any so i can compleate the quest. and now th aerolia flowers dont spawn either.

**Comment by Trixter313** [comment] 2016-03-06 16:28
Duplicate of #4236 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-06 16:28 UTC
