### ISSUE TITLE
I am stuck!!

### ISSUE THREAD

**Issue by BasterMC** [Wynncraft/Issues#8076] opened 2017-05-06 12:29 UTC
i am stuck in Nesaak in ground at x:112 y:73 z:-808 
plz help me get out!!!
THX ;3

**Comment by PepinhoJp** [comment] 2017-05-06 13:32
The only way is /kill if you have +7 soul points or scrolls, the staff doesn't take people out!

**Comment by PepinhoJp** [comment] 2017-05-06 13:36
Duplicate of #8075

**Comment by BasterMC** [comment] 2017-05-06 13:42
thx

**Closed** 2017-05-06 13:42 UTC
