### ISSUE TITLE
"You do not have permission in this area"

### ISSUE THREAD

**Issue by AquaDragon10** [Wynncraft/Issues#8371] opened 2017-06-13 21:11 UTC
Hello,
I first received this message while trying to press the button to ring the bell on the Seaskipper. Since it was just a cosmetic effect, I brushed it off. Then, later (after I switched servers to one with a dungeon/xp bomb) while on the way to a dungeon, I passed a loot chest. I got the same message when I tried to open it. I could not open several other loot chests while on the road. I also could not press buttons while trying to get relic boots. Does anyone else have this issue?

**Comment by thecoolkogut4** [comment] 2017-06-13 21:11
Hey there!

This is because the item you were using is a retextured half-slab, and the game thinks you were trying to place it as a result it says you don't have permission to. To fix this right click with an empty hand or your soul point.

Duplicate of #3902

Goodluck.

**Comment by AquaDragon10** [comment] 2017-06-13 21:22
Okay.
But is this issue going to be fixed at some point?

**Comment by thecoolkogut4** [comment] 2017-06-13 21:38
Hopefully.

**Closed** 2017-06-14 15:08 UTC
