### ISSUE TITLE
Skill point glitch

### ISSUE THREAD

**Issue by CaptainPrickles** [Wynncraft/Issues#4681] opened 2016-03-27 22:25 UTC
I logged into server 16 today to find that all my skills were at "0". while I had no usable skill points. Not without frustration I used the reset scroll from my quest. This gave me back all my skill points...however when I went to use them the skill count didn't increase until after 5-6 clicks. This goes for all skill types.
So not only did I end up wasting my reset scroll, I ended up losing my points yet again.
For the sake of the picture I put my skills as shown, that isn't how I wanted them.. May I have two free scrolls to reset this issue? (1 to correct the skills as were, another to have my scroll back, wasn't ready to use!)

Image link: http://i.imgur.com/CfCg8gS.png?1
As you can see in the image there are 6 points in each skill type.
6x6 = 36. I have 29 skills left over...an odd number. weird. 36+29 = 65. I'm level 41. That means I should have 80 skill points. 

In game name: CaptainPrickles
Class: Assassin
UUID: dc46251b-2dc8-41f4-92b2-ec975b9e7605

**Comment by Odnod** [comment] 2016-03-27 22:52
just type /class or reconnect to the server to fix this.

Also, wynncraft has a strict no-refund policy, so I am afraid you can't get any scrolls back.

**Comment by CaptainPrickles** [comment] 2016-03-27 22:54
What about the skills I..... so I just ruined things for myself? :/

**Comment by CaptainPrickles** [comment] 2016-03-28 02:02
Please note:
This issue still exists. I have done as directed. I've lost skill points. Help?

**Comment by Odnod** [comment] 2016-03-28 03:26
You must have broken it by using a skill reset scroll while the glitch was applied. I honestly have no idea what to do in this situation.

**Comment by CaptainPrickles** [comment] 2016-03-28 18:35
I can't afford another scroll... can't use my armor or weapons as it requires my skills. :/

**Comment by DarkDemonDragon** [comment] 2016-03-29 00:59
@CaptainPrickles you'll just have to buy another skill reset scroll and hopefully it doesn't break.

**Comment by CaptainPrickles** [comment] 2016-03-29 04:55
I would rather not waste ...another scroll. If it happened once it will no doubt happen again. The glitch isn't going to get resolved that way.

**Comment by DarkDemonDragon** [comment] 2016-03-29 11:44
@CaptainPrickles was the first scroll used before you did /class?

**Comment by CaptainPrickles** [comment] 2016-03-29 17:42
I didn't do /class until after I had used my scroll.

**Comment by CaptainPrickles** [comment] 2016-03-29 17:43
At this point I am unable to use my armor because of skills. I'm also unable to get another scroll. I have 7eb total.

**Comment by DarkDemonDragon** [comment] 2016-03-29 18:43
@CaptainPrickles if you post on the forums and explain your situation maturely then someone might be kind enough to donate you 1 LE. Unfortunately Wynncraft has a strict no refunds policy so there's nothing more we can do for you here, so I'm going to have to ask you to close this. I wish you luck on the forums!

**Comment by CaptainPrickles** [comment] 2016-03-29 19:22
DarkDemonDragon, are you a developer/staff member for wynncraft? If not I will take this farther. What I want at this point is not a refund but the issue itself resolved. what will stop it from happening again, I don't want to waste my hard earned emeralds (5-6 hours of farming) on a glitch, over and over.

**Comment by DarkDemonDragon** [comment] 2016-03-29 22:28
No I am simply a volunteer. The skill points being reset temporarily bug has already been reported dozens of times and Salted is currently working on it. Due to the nature of the bug it will be awhile before it can be fixed because is it difficult to replicate and focus on the exact cause of the bug.

**Comment by DarkDemonDragon** [comment] 2016-03-29 22:29
All you can do is know how to deal with this bug:
1) Pick up all your armor (throw out junk if necessary) 
2) check if your skill points are still at 0
3) If yes do /class and relog

**Comment by CaptainPrickles** [comment] 2016-03-30 01:55
Alright, thanks.

**Comment by Trixter313** [comment] 2016-03-30 03:34
Duplicate of #4120 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-03-30 03:34 UTC
