### ISSUE TITLE
Kratke disappeared when switching servers

### ISSUE THREAD

**Issue by RaidingPro101** [Wynncraft/Issues#4323] opened 2016-02-28 00:38 UTC
Me and a friend were playing Wynn on DXP Wknd. Then, we were changing servers, and my friend got a problem. He was wearing Kratke, and it said that he couldn't wear it, even though he had the right requirements. It then disappeared, and it didn't pop up in his inv because it was full. The glitch was where it said he couldn't wear it. Anyone know why this happened? It was right after a crash, when we started changing servers.

**Comment by Trixter313** [comment] 2016-02-28 18:52
Duplicate of https://github.com/Wynncraft/Issues/issues/3153 for the item not dropping & https://github.com/Wynncraft/Issues/issues/4304 for the item not being able to be worn.

Wynncraft has a strict no refunds policy so there's nothing we can do about the lost item.

Please direct any future comments to the original threads. Thanks!

**Closed by Trixter313** 2016-02-28 18:52 UTC
