### ISSUE TITLE
The Issues of Armor Skins

### ISSUE THREAD

**Issue by LGLabyrinth006K** [Wynncraft/Issues#1914] opened 2015-05-22 23:55 UTC
So today I changed my skin because I wanted to spice up the old skin I had, and then when I went to play Wynncraft, the armor skins got confused as to who I was.

Here's me playing as a Warrior, level 3.
http://gyazo.com/a6481c02734560b06c4a0bb1534b0351
And then here's me, as the same exact character, three seconds later after equipping the Chipped Leather Helmet.
http://gyazo.com/92c1eb0d22d30bd02ec350483804aca6

I don't know if this is fixable or if the armor skin system needs to update in order to function normally, but if you guys could deal with it in some way that would be great for the future.

-LGLabyrinth006K

**Comment by epicman739** [comment] 2015-05-25 23:06
I think that this is a known issue where armor skins will take your previous Minecraft skin instead of your current one. Armor skins still have a few problems that need to be worked out, but I'm sure this will be fixed soon.

**Comment by Trixter313** [comment] 2015-06-19 08:12
Dupe of https://github.com/Wynncraft/Issues/issues/1909 I believe.

**Closed** 2015-07-06 03:51 UTC
