### ISSUE TITLE
Cant leave Guild

### ISSUE THREAD

**Issue by IEatChickenWingz** [Wynncraft/Issues#5113] opened 2016-05-31 23:53 UTC
I cant leave my guild and its getting frustrating because I want to join a guild with my friends. It takes my soul points and says you have left the guild but it still says im in the guild. I have tried re logging and restarting mc. Can an admin force kick me out of my guild please? Ign: IEatChickenWingz Guild: The Killers

**Comment by ChiefInferno** [comment] 2016-06-01 15:06
haha, I've been waiting since February for something to happen, nothing ever does. Gl, Also if something does change and an admin see this my IGN is PierceTheVeil_ and you know, do what ypu gotta do please fam

**Comment by ChiefInferno** [comment] 2016-06-01 15:07
this bug does kind of make something that was intended to be fun for Wynn craft hell

**Comment by ChiefInferno** [comment] 2016-06-01 16:40
Not to also mention how this now is restricting us from features that make Wynn craft what it is and we are left out of things like clan wars, being in clans with friends, Etc and usually we are in inactive clans which is why want to leave making us not being able to even speak, do clan wars or help the clan

**Comment by YunoFGasai** [comment] 2016-06-01 20:12
name changes fucked up the whole system and our one, yes ONE coder is doing all he can to keep the server running, living his life and fixing bugs on the sidr.

**Comment by Moe-Ronickah** [comment] 2016-06-01 21:38
@IEatChickenWingz , please do a proper search for "can't leave guild" and tell us which of those 22 issues is most like your issue.

**Comment by ChiefInferno** [comment] 2016-06-01 22:17
this server just doesn't give a shit about the players anymore do they, its the same bull shit from every mod, and sorry to bring it out on you Moe because your the only 1 doing this stuff but u do nothing, either step up your game or get more people on the job

**Comment by Moe-Ronickah** [comment] 2016-06-02 00:45
@ChiefInferno , you do not know what goes on behind the scenes, here, or anywhere else in WynnCraft, which makes your comments less than sensible.

**Comment by YunoFGasai** [comment] 2016-06-02 14:12
@ChiefInferno the server cares about its playerbase, but to be honest guilds aren't the main aspect of the server and there are more serious bugs to work on.
the mods aren't the one that fix bugs, all they do is inforce the rules and ban players.
the only one that currently is capable of fixing all these bugs is Jumla, our coder, he is working solo on the code of the custom plugins he made and fixing the other bugs. 
Moe is here because he wants to and all he can do is bring the bug to Jumla's attention, which have been done.
I suggest to you to get into the skype convo of your selected guild and just play the game as usual.

**Comment by Moe-Ronickah** [comment] 2016-06-03 08:26
@IEatChickenWingz , you changed your Minecraft name several times this year.  This is a duplicate of #3665.

**Closed by Moe-Ronickah** 2016-06-03 08:26 UTC
Labels: Duplicate
