### ISSUE TITLE
Repeat of a earlier issue that has not been solved. 

### ISSUE THREAD

**Issue by TimThePvpMaster** [Wynncraft/Issues#3871] opened 2016-01-26 19:13 UTC
Bug: /toggle autojoin Not being able to log into the game period. 
Where? Black box, where you spawn in the game to choose a class.
What happens? I spawn to choose a kit, then I get kicked off and fall into the floor, until I hit around -1 million y and crash.  
How to you attempted this glitch/bug? Simply /toggle autojoin then relog. 

There you have it. I am so sad that I can't join, and I know it is a popular bug. Please, if someone could fix this, you'd bring millions of people back. I am sure at least thousands of people are banned because of this glitch, and I really want to play again! 

This is a "repeat" of an earlier bug called: https://github.com/Wynncraft/Issues/issues/3785 I will be closing this issue once it is fixed, if ever fixed.... Thank you so much for working hard on this! I've tried every step in the book.

**Comment by Trixter313** [comment] 2016-01-27 02:51
Duplicate of 3785, there only needs to be one issue per bug report. The other one is still open and being worked on. Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-01-27 02:51 UTC
