### ISSUE TITLE
Guild Glitch

### ISSUE THREAD

**Issue by PhoenixRemast** [Wynncraft/Issues#6911] opened 2016-12-16 21:04 UTC
Okay so like ages ago I made a small guild called, Phoenix Network, (Crappy name) but now its broken I have 4 duplicated members, and i cant leave, im leader of the guild as I want to join my friend's guild.
If this isnt clear just ask questions but please help 
My name:PhoenixRemast
Guild member name:Relinkuish
Guild name Phoenix Network

**Comment by LordHelmchen98** [comment] 2016-12-16 21:12
Duplicate of #3665
Thats because you changed your name while being in the guild and Relinkuish as well. When you changed your name it made one of the three bugged "Relinkuishs" to the next owner but as you were stuck due to the name change you werent able to leave. Thats why there are still two Relinkuishs who are chief and one who is owner beside you. Unfortunately there is no known way that guarantees you to get out of your guild. There is a chance to be able to leave if you change to the name you had when you created the guild though.

**Closed** 2016-12-17 14:56 UTC
Labels: Duplicate
