### ISSUE TITLE
"You don't have permission for this area" on interactive blocks.

### ISSUE THREAD

**Issue by JediBurrell** [Wynncraft/Issues#8113] opened 2017-05-10 23:28 UTC
When trying to open a chest, press a button ( especially important ), or close a door, I get a message "**You don't have permission for this area.** "

I've had a couple people try it as well, and nobody else is having this issue, so I don't know how to replicate it from a different account.

![Screenshot](http://i.imgur.com/rC1Fhqnr.png)

**Comment by thecoolkogut4** [comment] 2017-05-10 23:32
Hey there!

This is because the item you were using is a retextured half-slab, and the game thinks you were trying to place it as a result it says you don't have permission to. To fix this right click with an empty hand or your soul point.

Duplicate of #3902

Goodluck.

**Comment by JediBurrell** [comment] 2017-05-10 23:36
Hey, thanks for the response.
I did a search and somehow didn't find that. :/

But Minecraft overrides block placing when you right click interactive blocks, why is this different?

_Sent from my LGE Nexus 5X using [FastHub for Android](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by thecoolkogut4** [comment] 2017-05-10 23:39
I'm not too sure, maybe because wynn is custom coded? I can't help you on that one, sorry.

**Closed** 2017-05-10 23:43 UTC
