### ISSUE TITLE
À issue with force Unicode font

### ISSUE THREAD

**Issue by KillerBee524** [Wynncraft/Issues#5845] opened 2016-08-29 01:12 UTC
So, I was excited for the 1.14.1 Then i saw new Dungeon TP Scrolls, and saw this in the text for the scrolls

It shows big A with lines, wondering if it was a typo
![2016-08-28_17 59 21](https://cloud.githubusercontent.com/assets/21299339/18038287/de8938f6-6d4a-11e6-908e-50df49ba0a6a.png)

![2016-08-28_17 59 22](https://cloud.githubusercontent.com/assets/21299339/18038289/e886ffa0-6d4a-11e6-9c23-8ce436bdb56c.png)

![2016-08-28_17 59 23](https://cloud.githubusercontent.com/assets/21299339/18038291/ee459ffa-6d4a-11e6-8d93-0a2909b4cc47.png)

**Comment by Trixter313** [comment] 2016-08-29 01:19
Where is the merchant you're seeing this in located? I'm at the Detlas one and am not having any issues.

**Comment by KillerBee524** [comment] 2016-08-29 01:21
Im In Troms, And Also When I went to the Jungle Dungeon Outside of Troms, this happened 

![2016-08-28_18 19 24](https://cloud.githubusercontent.com/assets/21299339/18038378/29537454-6d4c-11e6-9217-aa11f32aaa4f.png)

**Comment by KillerBee524** [comment] 2016-08-29 01:25
I just Got Another Thing, The Key is Messed up AS WELL. 
![2016-08-28_18 24 55](https://cloud.githubusercontent.com/assets/21299339/18038423/c8a96766-6d4c-11e6-99e1-2e3f47bdb040.png)

**Comment by 0x0000null** [comment] 2016-08-29 02:01
It's because you're using Force Unicode Font.

But either way, this is still a bug.

**Comment by 0x0000null** [comment] 2016-09-05 18:12
Also occurs on the website.

<img width="585" alt="website" src="https://cloud.githubusercontent.com/assets/16504771/18255020/91e9926a-7359-11e6-8cd6-1bb0140fb689.png">

**Comment by DebugMC** [comment] 2017-01-19 17:00
This issue is still alive, I had it happen last night :P

**Comment by Villageacules** [comment] 2017-03-23 16:11
@KillerBee524 @DebugMC @0x0000null @Trixter313 Can this be confirmed still happening? I think it may have been fixed by Salted during this update.

**Comment by 0x0000null** [comment] 2017-03-23 16:12
Still happens

**Comment by Villageacules** [comment] 2017-03-23 16:15
I've checked and it seems the issue has been fixed... notify me if else on the forums.

**Closed by Villageacules** 2017-03-23 16:15 UTC
