### ISSUE TITLE
Glitched Dragon Skin?

### ISSUE THREAD

**Issue by Cowmoonist** [Wynncraft/Issues#4220] opened 2016-02-22 00:03 UTC
So..

![2016-02-21_19 00 07](https://cloud.githubusercontent.com/assets/17394090/13206538/d507d330-d8cd-11e5-8c4f-6ff81f960873.png)

**Comment by Trixter313** [comment] 2016-02-22 20:06
Duplicate of #3175 

Please direct any future comments to the original thread. Thanks!

**Closed by Trixter313** 2016-02-22 20:06 UTC
